### PR TITLE
Prevent reconciling `BackupEntries` between migration and reconciliation

### LINKED ISSUE #10527: During CPM the `BackupEntry` can get reconciled immediately after it gets migrated to the destination `Seed`, before it is instructed to be restored
**How to categorize this issue?**

/area control-plan-migration
/kind bug

**What happened**:
We noticed this error during the `restore` phase of control plane migration across seeds with different provider types (gcp to aws seed). Trying to restore the  `BackupEntry` can fail with the following error:
```
task "Waiting until the backup entry has been reconciled" failed: Error while waiting for BackupEntry garden-foo/shoot--foo--bar--4dd5feee-e674-4d63-8f5c-d00a36381c4b to become ready: gardener operation "restore" is not yet picked up by controller
``` 

And the following in the `gardenlet` logs:
```
{"level":"error","ts":"2024-09-07T08:51:51.906Z","msg":"Reconciler error","controller":"backupentry","namespace":"garden-actions","name":"shoot--foo--bar--4dd5feee-e674-4d63-8f5c-d00a36381c4b","reconcileID":"56c08509-d56c-4953-89c1-5434314117eb","error":"admission webhook \"validation.extensions.backupentries.resources.gardener.cloud\" denied the request: BackupEntry.extensions.gardener.cloud \"shoot--foo--bar--4dd5feee-e674-4d63-8f5c-d00a36381c4b\" is invalid: spec.type: Invalid value: \"aws\": field is immutable","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:227"}
```

What happens is that the `core.BackupEntry` was reconciled on the destination Seed (gcp) too soon, while it was still referring to the `BackupBucket` of the source Seed (gcp). This leads to the deployment of an `extensions.BackupEntry` with `spec.type: gcp` field in the destination Seed (aws).
Later on, the `restore` phase tries to actually restore the `core.BackupEntry` in this step: https://github.com/gardener/gardener/blob/3abeb314e176f61134f81b0264ef15e9976623df/pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go#L254-L259
This has the effect of changing the referred `BackupBucket` of the `core.BackupEntry` to the destination (aws) `BackupBucket` and triggering a `restore` operation. The `restore` operation tries to redeploy the `extensions.BackupEntry` with the new provider type - aws. This in turn leads to the `validation.extensions.backupentries.resources.gardener.cloud` admission webhook denying the request as shown in the logs above. 

**What you expected to happen**:
The `core.BackupEntry` not getting reconciled on the destination seed after it gets migrated and before it gets restored.

**How to reproduce it (as minimally and precisely as possible)**:
This is caused by a race so it is hard to reproduce. However, here are the steps you can try out:
1. Setup a garden cluster by following the [Deploying Gardener Locally and Enabling Provider-Extensions](https://github.com/gardener/gardener/blob/release-v1.103/docs/deployment/getting_started_locally_with_extensions.md) guide
2. Create two seeds in different providers, e.g.: one in `gcp` and one in `aws`
3. Create a shoot cluster in the `gcp` provider
4. Migrate the shoot cluster from the `gcp` seed to the `aws` seed
5. If you do not encounter the error, migrate it back from the `aws` seed to the `gcp` seed (repeat until you encounter the error)

**Anything else we need to know?**:
We could potentially allow the `spec.type` field of `extension.BackupEntry` resources to be mutable. However, I believe that the correct approach is to prevent reconciliation of `core.BackupEntry` resources before their actual intended restoration.

**Environment**:

- Gardener version: v1.103.0

### LINKED ISSUE #10718: `core.BackupEntry` can get stuck in `Processing` state for long periods of time during `migrate` phase of control plane migration
**How to categorize this issue?**

/area control-plane-migration
/kind bug

**What happened**:
While performing control plane migration the `migrate` phase can get stuck for more than 45 minutes because the `lastOperation` of the `core.BackupEntry` is in `Processing` state and does not get update to `Successful`:

```
2024-10-10 11:30:34 | {"log":{"controller":"shoot","error":"extension state is not succeeded but Processing","kind":"BackupEntry","level":"error","msg":"Object did not get ready yet","name":"<redacted>","namespace":"garden-<redacted>","object":{"name":"<redacted>","namespace":"garden-<redacted>"},"operation":"migrate","reconcileID":"11f06568-36f5-454c-a337-af31f0d5f212","stacktrace":"github.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction.func1\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:104\ngithub.com/gardener/gardener/pkg/utils/retry.UntilFor\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:132\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).Until\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:176\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).UntilTimeout\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:183\ngithub.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:86\ngithub.com/gardener/gardener/pkg/component/garden/backupentry.(*backupEntry).Wait\n\t/go/src/github.com/gardener/gardener/pkg/component/garden/backupentry/backupentry.go:121\ngithub.com/gardener/gardener/pkg/component/garden/backupentry.(*backupEntry).WaitMigrate\n\t/go/src/github.com/gardener/gardener/pkg/component/garden/backupentry/backupentry.go:146\ngithub.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:226","ts":"2024-10-10T11:30:34.543Z"}}
...
...
...
2024-10-10 12:18:17 | {"log":{"controller":"shoot","error":"extension state is not succeeded but Processing","kind":"BackupEntry","level":"error","msg":"Object did not get ready yet","name":"<redacted>","namespace":"garden-<redacted>","object":{"name":"<redacted>","namespace":"garden-<redacted>"},"operation":"migrate","reconcileID":"c7aac264-894f-4609-9733-f6889df7c03c","stacktrace":"github.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction.func1\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:104\ngithub.com/gardener/gardener/pkg/utils/retry.UntilFor\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:132\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).Until\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:176\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).UntilTimeout\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:183\ngithub.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:86\ngithub.com/gardener/gardener/pkg/component/garden/backupentry.(*backupEntry).Wait\n\t/go/src/github.com/gardener/gardener/pkg/component/garden/backupentry/backupentry.go:121\ngithub.com/gardener/gardener/pkg/component/garden/backupentry.(*backupEntry).WaitMigrate\n\t/go/src/github.com/gardener/gardener/pkg/component/garden/backupentry/backupentry.go:146\ngithub.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:226","ts":"2024-10-10T12:18:17.528Z"}}
2024-10-10 12:18:21 | {"log":{"controller":"backupentry","level":"info","msg":"Skipping because BackupEntry is not managed by this gardenlet","name":"shoot--<redacted>","namespace":"garden-<redacted>","reconcileID":"9b191409-1c59-4dc9-9df7-20059e854b34","seedName":"<redacted>","ts":"2024-10-10T12:18:21.172Z"}}
2024-10-10 12:18:22 | {"log":{"controller":"shoot","flow":"Shoot cluster preparation for migration","level":"info","msg":"Succeeded","name":"<redacted>","namespace":"garden-<redacted>","object":{"name":"<redacted>","namespace":"garden-<redacted>"},"operation":"migrate","reconcileID":"c7aac264-894f-4609-9733-f6889df7c03c","task":"Waiting for BackupEntry to be migrated to new seed","ts":"2024-10-10T12:18:22.529Z"}}
```

**What you expected to happen**:

Shoot control plane migration to not have to wait so long for the `lastOperation` of the `core.BackupEntry` to become `Successful`.

**How to reproduce it (as minimally and precisely as possible)**:
Foreword: it's currently not known why exactly the `core.BackupEntry` is reconciled prematurely (right after it is migrated) on the destination seed, so you might have to trigger its reconciliation manually.

1. Follow the [getting started locally](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md) guide and setup two local seed clusters
2. Create a shoot cluster on one of the seeds and let it reconcile successfully.
3. Create a dummy `Secret` resource with a custom finalizer in the control plane namespace of the Shoot
4. Trigger control plane migration by following [this guide](https://github.com/gardener/gardener/blob/master/docs/operations/control_plane_migration.md#triggering-the-migration)
5. The `migrate` phase will be hang while trying to delete the shoot's control plane namespace as it will not be able to remove the secret you created. It will eventually be retried.
6. Observe that the `core.BackupEntry` is reconciled by the gardenlet on the destination seed and it's status is updated to `Processing`. Alternatively, you might have to annotate the `core.BackupEntry` with `gardener.cloud/operation=reconcile` to force reconciliation as stated in the "foreword" above.
8. When the `migrate` flow is retried, observe that it now hangs while waiting for the `lastOperation` of the `core.BackupEntry` to become `Successful`

**Anything else we need to know?**:
This issue is similar to #10527 - it happens because the `core.BackupEntry` can get reconciled on the destination seed immediately after it is migrated and before the shoot's restoration on the destination seed has began.

When the `core.BackupEntry` is reconciled on the destination seed too quickly the following happens: 
1. The `lastOperation` of the `core.BackupEntry` is set to `Processing` and the corresponding `extensions.BackupEntry` is created in the seed cluster https://github.com/gardener/gardener/blob/702361f7db33c203afe646642c58e449a052b3e7/pkg/gardenlet/controller/backupentry/reconciler.go#L256-L262
It should then be reconciled successfully by the corresponding extension controller.
2. The `core.BackupEntry` reconciler exits (returns nil) and the controller waits for a notification that the `extensions.BackupEntry` has been successfully reconciled via a mapper function before triggering a new reconciliation: https://github.com/gardener/gardener/blob/702361f7db33c203afe646642c58e449a052b3e7/pkg/gardenlet/controller/backupentry/add.go#L83-L88
https://github.com/gardener/gardener/blob/702361f7db33c203afe646642c58e449a052b3e7/pkg/gardenlet/controller/backupentry/add.go#L110-L131
3. The `MapExtensionBackupEntryToCoreBackupEntry` function depends on the cluster resource to exist in the seed so that it can retrieve the `Shoot` from it and get the namespace of the shoot in the garden cluster so that it can then map the name of the `extensions.BackupEntry` resource to the namespace and name of the corresponding `core.BackupEntry`. However, the cluster resource does not exist in the destination seed at this point , so the following error is returned:
    ```
    2024-10-10 11:18:19 | {"log":{"controller":"backupentry","error":"Cluster.extensions.gardener.cloud \"shoot--<redacted>\" not found","level":"error","msg":"Failed to get shoot from cluster","shootTechnicalID":"shoot--<redacted>","stacktrace":"github.com/gardener/gardener/pkg/gardenlet/controller/backupentry.(*Reconciler).MapExtensionBackupEntryToCoreBackupEntry\n\t/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/backupentry/add.go:121\ngithub.com/gardener/gardener/pkg/controllerutils/mapper.MapFunc.Map\n\t/go/src/github.com/gardener/gardener/pkg/controllerutils/mapper/enqueue_mapped.go:38\ngithub.com/gardener/gardener/pkg/controllerutils/mapper.(*enqueueRequestsFromMapFunc).mapAndEnqueue\n\t/go/src/github.com/gardener/gardener/pkg/controllerutils/mapper/enqueue_mapped.go:104\ngithub.com/gardener/gardener/pkg/controllerutils/mapper.(*enqueueRequestsFromMapFunc).Update\n\t/go/src/github.com/gardener/gardener/pkg/controllerutils/mapper/enqueue_mapped.go:91\nsigs.k8s.io/controller-runtime/pkg/internal/source.(*EventHandler).OnUpdate\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/source/event_handler.go:121\nk8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate\n\t/go/pkg/mod/k8s.io/client-go@v0.29.9/tools/cache/controller.go:246\nk8s.io/client-go/tools/cache.(*processorListener).run.func1\n\t/go/pkg/mod/k8s.io/client-go@v0.29.9/tools/cache/shared_informer.go:970\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.29.9/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.29.9/pkg/util/wait/backoff.go:227\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.29.9/pkg/util/wait/backoff.go:204\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.29.9/pkg/util/wait/backoff.go:161\nk8s.io/client-go/tools/cache.(*processorListener).run\n\t/go/pkg/mod/k8s.io/client-go@v0.29.9/tools/cache/shared_informer.go:966\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.29.9/pkg/util/wait/wait.go:72","ts":"2024-10-10T11:18:19.033Z"}}
    ```
    Due to this the `core.BackupEntry` does not get re-queued and its operation remains `Processing`.
4. Meanwhile, on the source seed, the `migrate` flow could get interrupted and retried after the `core.BackupEntry` was migrated successfully once. Then `migrate` flow has to [wait again until the `core.BackupEntry` is migrated successfully](https://github.com/gardener/gardener/blob/702361f7db33c203afe646642c58e449a052b3e7/pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go#L398-L402). If the `core.BackupEntry` was reconciled by gardenlet in the destination seed and it's `lastOperation` is stuck in `Processing` as explained above, this wait will never finish, unless the `core.BackupEntry` happens to be requeued for some other reason for reconciliation by gardenlet in the destination seed

**Environment**:

- Gardener version: `v1.105.0` 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
This PR fixes an issue that was causing the `core.gardener.cloud/v1beta1.BackupEntry` to be reconciled on the destination Seed after being successfully migrated from the source Seed, but before being restored.

The issue was occurring because `core.gardener.cloud/v1beta1.BackupEntry`s were enqueued for reconciliation when the corresponding `core.gardener.cloud/BackupBuckets` was reconciled successfully. Since `gardenlet`s on all Seeds watch for operation changes of all `core.gardener.cloud/BackupBuckets` as part of the following watch: https://github.com/gardener/gardener/blob/5417a7bbb3adab9d192abd8e8e2ac4b7fe7c9a2d/pkg/gardenlet/controller/backupentry/add.go#L83-L88

This resulted in the corresponding `core.gardener.cloud/v1beta1.BackupEntry`s to get enqueued on all `gardenlet`s. The reconciliations then end early due to this check: https://github.com/gardener/gardener/blob/5417a7bbb3adab9d192abd8e8e2ac4b7fe7c9a2d/pkg/gardenlet/controller/backupentry/reconciler.go#L86-L89

However, if the  `core.gardener.cloud/v1beta1.BackupEntry` is already migrated, the check above would pass on the destination seed, and reconciliation would continue.

With this PR we prevent enqueueing `core.gardener.cloud/v1beta1.BackupEntry` if they were successfully migrated, but not yet annotated with `gardener.cloud/operation: restore`. Additionally, this prevents a reconciliation on the destination seed if the `gardenlet` there is restarted  after `core.gardener.cloud/v1beta1.BackupEntry` was successfully migrated.

**Which issue(s) this PR fixes**:
Fixes #10718 
Fixes #10527 

**Special notes for your reviewer**:
/cc @shafeeqes @adenitiu 
**Release note**:

```other operator
Fixed an issue that that could occur during control plane migration causing the `core.gardener.cloud/v1beta1.BackupEntry` to be reconciled after it was successfully migrated, but before it was restored.
```

### CODE REVIEW

File: pkg/gardenlet/controller/backupentry/add.go [hunk 1]
```diff
@@ -138,3 +139,24 @@ func getBackupBucketLastOperation(obj client.Object) *gardencorev1beta1.LastOper
 
 	return backupBucket.Status.LastOperation
 }
+
+// restoreAfterMigratePredicate returns a predicate which returns false if the core.gardener.cloud/v1beta1.BackupEntry has been
+// successfully migrated and does not have the `gardener.cloud/operation: restore` annotation.
+// It returns true in all other cases.
+func restoreAfterMigratePredicate() func(obj client.Object) bool {
```
Comment (Kostov6) [inline pkg/gardenlet/controller/backupentry/add.go]: Do we need to return the function?
```suggestion
func restoreAfterMigratePredicate(obj client.Object) bool {
```

File: pkg/gardenlet/controller/backupentry/add.go [hunk 2]
```diff
@@ -138,3 +139,24 @@ func getBackupBucketLastOperation(obj client.Object) *gardencorev1beta1.LastOper
...
+		}
+
+		isMigrateSucceeded := backupEntry.Status.LastOperation != nil && backupEntry.Status.LastOperation.State == gardencorev1beta1.LastOperationStateSucceeded && backupEntry.Status.LastOperation.Type == gardencorev1beta1.LastOperationTypeMigrate
+		hasRestoreAnnotation := backupEntry.GetAnnotations()[v1beta1constants.GardenerOperation] == v1beta1constants.GardenerOperationRestore
+
+		if !isMigrateSucceeded || hasRestoreAnnotation {
+			return true
+		}
+
+		return false
```
Comment (Kostov6) [inline pkg/gardenlet/controller/backupentry/add.go]: Some simplifications and readability
```suggestion
	isMigrateSucceeded := backupEntry.Status.LastOperation != nil &&
		backupEntry.Status.LastOperation.State == gardencorev1beta1.LastOperationStateSucceeded &&
		backupEntry.Status.LastOperation.Type == gardencorev1beta1.LastOperationTypeMigrate

	hasRestoreAnnotation := backupEntry.GetAnnotations()[v1beta1constants.GardenerOperation] == v1beta1constants.GardenerOperationRestore

	return !isMigrateSucceeded || hasRestoreAnnotation
```

**Review by Kostov6 — COMMENTED** [review]
From initial reading

File: pkg/gardenlet/controller/backupentry/add.go [hunk 3]
```diff
@@ -138,3 +139,21 @@ func getBackupBucketLastOperation(obj client.Object) *gardencorev1beta1.LastOper
 
 	return backupBucket.Status.LastOperation
 }
+
+// restoreAfterMigratePredicate is a predicate which returns false if the core.gardener.cloud/v1beta1.BackupEntry has been
+// successfully migrated and does not have the `gardener.cloud/operation: restore` annotation.
+// It returns true in all other cases.
+func restoreAfterMigratePredicate(obj client.Object) bool {
```
Comment (timuthy) [inline pkg/gardenlet/controller/backupentry/add.go]:
```suggestion
// migrationOrRestorePending is a predicate which returns true if the core.gardener.cloud/v1beta1.BackupEntry is being migrated or restored.
func migrationOrRestorePending(obj client.Object) bool {
```

Nit

Comment (plkokanov) [reply pkg/gardenlet/controller/backupentry/add.go]: The way that this currently works is that the predicate returns `true` when the last operation is NOT `Migrate/Succeeded` because we want to enqueue reconciliation requests in those cases. 

We only want to block reconciliation requests (return `false`) if the operation IS `Migrate/Succeeded` and the resource does NOT have the `gardener.cloud/operation=restore` annotation.

In line with your suggestion, I could rename the function to better indicate this:
```
// restoreNotPending is a predicate which returns true if the `core.gardener.cloud/v1beta1.BackupEntry` is not waiting to be restored after being migrated.
restoreNotPending(...)
```
I wondered whether to use `predicates.Not` to invert the function, instead of having `Not` be part of the name, however the https://github.com/plkokanov/gardener/blob/556ea34276a51de759e5c0574f9a15ed845c77fa/pkg/gardenlet/controller/backupentry/add.go#L106 function only takes a `func(obj client.Obj) bool` as second argument. 
wdyt?

Comment (plkokanov) [reply pkg/gardenlet/controller/backupentry/add.go]: We discussed this with @timuthy in slack and decided to use the following:
```
// backupEntryPredicate is a predicate which returns true if the core.gardener.cloud/v1beta1.BackupEntry has not yet been successfully migrated or has the `gardener.cloud/operation: restore` annotation.
func backupEntryPredicate(obj client.Object) bool {
```

**Comment by timuthy** [comment]
@LucaBernstein, flake https://github.com/gardener/gardener/commit/cd9fe452b83dbcb9da1cb67e1891e5b5ef94d394?

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve
