### PR TITLE
Prevent deploying empty MR and resources when VPA is disabled

### LINKED ISSUE #12779: Seed with disabled `verticalPodAutoscaler` creates empty `VPA` MR
**How to categorize this issue?**

/area auto-scaling
/kind cleanup

**What happened**:
If VPA is disabled `allResources` will be empty
https://github.com/gardener/gardener/blob/708ca4f2ce31d32846c96bd8f879b59d85bae8b9/pkg/component/autoscaling/vpa/vpa.go#L132-L139
And MR with empty secret content will be created here:
https://github.com/gardener/gardener/blob/708ca4f2ce31d32846c96bd8f879b59d85bae8b9/pkg/component/resourceconfig.go#L145
We should remove `Enabled` field
https://github.com/gardener/gardener/blob/708ca4f2ce31d32846c96bd8f879b59d85bae8b9/pkg/component/autoscaling/vpa/vpa.go#L94-L95
And handle VPA deployment in a similar manner as Dashboard
https://github.com/gardener/gardener/blob/485c25124ea536e4610c627109017dd34d434921/pkg/gardenlet/operation/botanist/kubernetesdashboard.go#L47-L54

**How to reproduce it (as minimally and precisely as possible)**:
You can verify the problem and solution by enabling/disabling `verticalPodAutoscaler` through the seed resource in the local setup and looking at the `vpa` MR and its secret

### PR DESCRIPTION
**Pull request by RadaBDimitrova**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
Previously, even when disabled, VPA's `Deploy` function would still be called and a check of the `Enabled` field would determine whether its resources should be populated and created. However this would lead to the creation of an empty secret to be referenced in the VPA MR in the case of a disabled seed VPA, as mentioned in #12779.

With an additional check in `newVerticalPodAutoscaler` we can make sure that no VPA MR referencing an empty secret will be created after disabling it. Additionally we can remove the `Enabled` field and the logic surrounding it, since the proper check would be done on a higher level - even before going into the `Deploy` function.

**Which issue(s) this PR fixes**:
Fixes #12779

**Special notes for your reviewer**:
/cc @Kostov6 @plkokanov

**Release note**:

```other operator
The VPA ManagedResource and the Secret it references are now removed when VPA is disabled in the Shoot, Seed or Garden specification. Previously, when VPA was disabled a ManagedResource with an empty Secret would be created. Now, no ManagedResource is created.
```

### CODE REVIEW

**Review by Kostov6 — COMMENTED** [review]
/lgtm

File: pkg/gardenlet/controller/seed/seed/components.go [hunk 1]
```diff
@@ -753,6 +752,16 @@ func (r *Reconciler) newVerticalPodAutoscaler(settings *gardencorev1beta1.SeedSe
 		isGardenCluster,
 		featureGates,
 	)
+
```
Comment (plkokanov) [inline pkg/gardenlet/controller/seed/seed/components.go]: Unnecessary empty line
```suggestion
```

File: pkg/operator/controller/garden/garden/components.go [hunk 2]
```diff
@@ -466,6 +465,16 @@ func (r *Reconciler) newVerticalPodAutoscaler(garden *operatorv1alpha1.Garden, s
 		true,
 		featureGates,
 	)
+
```
Comment (plkokanov) [inline pkg/operator/controller/garden/garden/components.go]: Unnecessary empty line
```suggestion
```

**Review by plkokanov — CHANGES_REQUESTED** [review]
A few small nits and a reminder to add a release note describing that the MR is removed when vpa is disabled.

Additionally, I wanted to check what the story behind the `Enabled` field is. 
It was added in https://github.com/gardener/gardener/pull/5811 so that the vpa-exporter component can be deployed for the seed even if vpa is disabled in the seed settings.

Later https://github.com/gardener/gardener/pull/6771 removed the vpa-exporter component, hence it seems that it was indeed no longer necessary to keep the MR in the seed.

File: pkg/gardenlet/operation/botanist/vpa.go [hunk 3]
```diff
@@ -83,7 +83,6 @@ func (b *Botanist) DefaultVerticalPodAutoscaler() (vpa.Interface, error) {
 		b.SecretsManager,
 		vpa.Values{
 			ClusterType:              component.ClusterTypeShoot,
-			Enabled:                  true,
```
Comment (ialidzhikov) [inline pkg/gardenlet/operation/botanist/vpa.go:86]: Don't we have to destroy the component here when VPA is disabled?

Comment (ialidzhikov) [inline pkg/gardenlet/operation/botanist/vpa.go:86]: Can we add an unit test about it? When VPA is disabled in the Shoot spec, the returned vpa component's Deploy does Destroy.

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

File: pkg/gardenlet/operation/botanist/vpa.go (hunk 3 above)
Comment (plkokanov) [reply pkg/gardenlet/operation/botanist/vpa.go:86]: For shoots this is already handled separately in https://github.com/gardener/gardener/blob/841e737a8bcab1626a7995c5798a4cbeb1f72156/pkg/gardenlet/operation/botanist/vpa.go#L97-L103

**Comment by ialidzhikov** [comment]
Could you change the release note from 

```
The VPA MR and the secret it references are now removed when VPA is disabled in the Seed's settings.
```

to

```
The VPA ManagedResource and the Secret it references are now removed when VPA is disabled in the Shoot, Seed or Garden specification. Previously, when VPA is disabled a ManagedResource with empty Secret was created. Now, no ManagedResource is created.
```

?

File: pkg/gardenlet/operation/botanist/vpa.go (hunk 3 above)
Comment (ialidzhikov) [reply pkg/gardenlet/operation/botanist/vpa.go:86]: I now tested in local setup and it works as expected. The destroy is handled in the `DeployVerticalPodAutoscaler` func: https://github.com/gardener/gardener/blob/e812aa6c380a5ce8209ec3cc2f87685069fbc147/pkg/gardenlet/operation/botanist/vpa.go#L96-L102

So, nothing to be done.

Comment (ialidzhikov) [reply pkg/gardenlet/operation/botanist/vpa.go:86]: Obsolete, see https://github.com/gardener/gardener/pull/12870#discussion_r2324884678.

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

File: pkg/gardenlet/controller/seed/seed/components.go [hunk 4]
```diff
@@ -739,12 +739,11 @@ func (r *Reconciler) newVerticalPodAutoscaler(settings *gardencorev1beta1.SeedSe
 		featureGates = settings.VerticalPodAutoscaler.FeatureGates
 	}
 
-	return sharedcomponent.NewVerticalPodAutoscaler(
+	verticalPodAutoscaler, err := sharedcomponent.NewVerticalPodAutoscaler(
```
Comment (ialidzhikov) [inline pkg/gardenlet/controller/seed/seed/components.go:742]: Actually, we could rename the steps from `Deploying Kubernetes vertical pod autoscaler` to `Reconciling Kubernetes vertical pod autoscaler` because it is confusing the step name to be `Deploying Kubernetes vertical pod autoscaler` when VPA is disabled and gets deleted.

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Comment by RadaBDimitrova** [comment]
/retest
```
{"level":"error","ts":"2025-09-05T12:24:07.513Z","msg":"Timeout or abort while handling","logger":"UnhandledError","method":"GET","URI":"/apis/core.gardener.cloud/v1beta1","auditID":"c1e18b12-3b3b-46d7-b364-72e9ec35b090","stacktrace":"k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithPanicRecovery.func20\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/server/filters/wrap.go:53\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithPanicRecovery.withPanicRecovery.func33.1\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/server/filters/wrap.go:69\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash.func1\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.33.4/pkg/util/runtime/runtime.go:60\nk8s.io/apimachinery/pkg/util/runtime.handleCrash\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.33.4/pkg/util/runtime/runtime.go:110\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.33.4/pkg/util/runtime/runtime.go:64\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:783\nk8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/server/filters/timeout.go:274\nk8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/server/filters/timeout.go:147\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithRequestDeadline.withRequestDeadline.func28\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/endpoints/filters/request_deadline.go:100\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2322\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithWaitGroup.withWaitGroup.func29\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/server/filters/waitgroup.go:86\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2322\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithCacheControl.func14\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/endpoints/filters/cachecontrol.go:31\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2322\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithHTTPLogging.WithLogging.withLogging.func35\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/server/httplog/httplog.go:112\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2322\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithLatencyTrackers.func16\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/endpoints/filters/webhook_duration.go:56\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2322\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithRequestInfo.func18\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/endpoints/filters/requestinfo.go:39\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2322\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithRequestReceivedTimestamp.withRequestReceivedTimestampWithClock.func32\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/endpoints/filters/request_received_time.go:38\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2322\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithMuxAndDiscoveryComplete.func19\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/endpoints/filters/mux_discovery_complete.go:52\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2322\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithPanicRecovery.withPanicRecovery.func33\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/server/filters/wrap.go:73\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2322\nk8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithAuditInit.withAuditInit.func34\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/endpoints/filters/audit_init.go:63\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2322\nk8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP\n\t/home/prow/go/pkg/mod/k8s.io/apiserver@v0.33.4/pkg/server/handler.go:188\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3340\nnet/http.initALPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:4013\ngolang.org/x/net/http2.(*serverConn).runHandler\n\t/home/prow/go/pkg/mod/golang.org/x/net@v0.43.0/http2/server.go:2433"}
```

**Review by ialidzhikov — APPROVED** [review]
/lgtm
