### PR TITLE
Prevent creation of `ssh-keypair.old` secret on Shoot creation.

### LINKED ISSUE #4527: gardenlet always creates (useless?) ssh-keypair.old Secret on Shoot creation/reconciliation
/area quality
/area auto-scaling
/kind bug
/priority 3

**What happened**:
gardenlet always creates (useless?) ssh-keypair.old Secret on Shoot creation/reconciliation. First I was quite surprised that  ssh-keypair.old Secret is created on landscapes even when `RotateSSHKeypairOnMaintenance` feature gate was never enabled.
Then I found the communication in https://github.com/gardener/gardener/pull/4224/#discussion_r653302565.

Currently this is creating a huge waste as a these ssh-keypair.old Secrets contribute a large portion of the Secrets' count in the garden cluster. It is also proportional to the Shoots' count - more Shoots, more (useless?) ssh-keypair.old Secrets.

**What you expected to happen**:
ssh-keypair.old to be created only when a `rotate-ssh-keypair` operation is requested.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot

2. Make sure that the `${SHOOT_NAME}.ssh-keypair.old` Secret exist in the garden cluster. Note that no `rotate-ssh-keypair` operation was requested and the `RotateSSHKeypairOnMaintenance`  feature gate of gardener-controller-manager was never enabled -> so rotate-ssh-keypair operation was never requested.

```
$ k -n garden-foo get secrets | grep bar
bar.kubeconfig        Opaque                                3      13s
bar.monitoring        Opaque                                3      13s
bar.ssh-keypair       Opaque                                2      13s
bar.ssh-keypair.old   Opaque                                2      13s
```

**Environment**:

- Gardener version: v1.28.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ary1992**
**How to categorize this PR?**

/area quality
/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
Prevent gardenlet from creating  ssh-keypair.old Secret on Shoot creation.
**Which issue(s) this PR fixes**:
Fixes [#4527 ](https://github.com/gardener/gardener/issues/4527)

**Special notes for your reviewer**:
A new annotation field `gardener.cloud/ssh-keypair` is added to shoot when `ssh-keypair` is rotated. 
**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
Just curious?
Is it not nice to have just key only something like  `ShootSSHKeypairRotated`, it can be set to `true` indicating that the SSH keypair for the shoot nodes has been rotated at least once.

**Comment by ary1992** [comment]
> Just curious?
> Is it not nice to have just key only something like `ShootSSHKeypairRotated`, it can be set to `true` indicating that the SSH keypair for the shoot nodes has been rotated at least once.

Annotations also acts as key-value pair. Here we have assigned the value `rotated` to annotation `gardener.cloud/ssh-keypair`. Moreover , where should the field `ShootSSHKeypairRotated` be included ?

**Comment by acumino** [comment]
> > Just curious?
> > Is it not nice to have just key only something like `ShootSSHKeypairRotated`, it can be set to `true` indicating that the SSH keypair for the shoot nodes has been rotated at least once.
> 
> Annotations also acts as key-value pair. Here we have assigned the value `rotated` to annotation `gardener.cloud/ssh-keypair`. Moreover , where should the field `ShootSSHKeypairRotated` be included ?

ShootSSHKeypairRotated : "true"

File: pkg/operation/botanist/secrets.go [hunk 1]
```diff
@@ -350,9 +350,11 @@ func (b *Botanist) rotateSSHKeypairSecrets(ctx context.Context, gardenerResource
 	}
 	gardenerResourceDataList.Delete(v1beta1constants.SecretNameSSHKeyPair)
 
-	// remove operation annotation
+	// remove operation annotation and annotate shoot with GardenerSSHRotation annotation indicating that Shoot's ssh-keypair
+	// has been rotated.
 	return b.Shoot.UpdateInfo(ctx, b.K8sGardenClient.Client(), false, func(shoot *gardencorev1beta1.Shoot) error {
 		delete(shoot.Annotations, v1beta1constants.GardenerOperation)
+		metav1.SetMetaDataAnnotation(&shoot.ObjectMeta, v1beta1constants.GardenerSSHRotation, v1beta1constants.ShootOperationSSHKeypairRotated)
```
Comment (rfranzke) [inline pkg/operation/botanist/secrets.go]: Instead of storing this annotation on the `Shoot`, can we just ensure that the `ssh-keypair.old` secret in the shoot namespace in the seed only exists when it was really rotated at least once? Then we can check if this secret exists and only sync to garden if this condition holds true?

Comment (ary1992) [reply pkg/operation/botanist/secrets.go]: How can we check whether the `ssh-keypair` is rotated atleast once , as the annotation `gardener.cloud/operation : rotate-ssh-keypair` gets removed after reconcilation of shoot ?

Comment (rfranzke) [reply pkg/operation/botanist/secrets.go]: > can we just ensure that the `ssh-keypair.old` secret in the shoot namespace in the seed only exists when it was really rotated at least once? Then we can check if this secret exists and only sync to garden if this condition holds true?

Comment (ary1992) [reply pkg/operation/botanist/secrets.go]: Addressed the feedback in commit [267ef07](https://github.com/gardener/gardener/pull/5388/commits/267ef07500aadb48572e04da0637038a304ed92d).

File: pkg/operation/botanist/wanted_secrets.go [hunk 2]
```diff
@@ -411,6 +405,16 @@ func (b *Botanist) generateWantedSecretConfigs(basicAuthAPIServer *secrets.Basic
...
 
+	// Secret definition for ssh-keypair.old
+	gardenerResourceDataList := gardencorev1alpha1helper.GardenerResourceDataList(b.GetShootState().Spec.Gardener)
+	if secret := gardenerResourceDataList.Get(v1beta1constants.SecretNameOldSSHKeyPair); secret != nil {
+		secretList = append(secretList, &secrets.RSASecretConfig{
+			Name:       v1beta1constants.SecretNameOldSSHKeyPair,
+			Bits:       4096,
+			UsedForSSH: true,
+		})
+	}
```
Comment (rfranzke) [inline pkg/operation/botanist/wanted_secrets.go]: I think this is confusing. You are "exploiting" the fact that the secrets in this list will be synced to the seed cluster, but this is far from obvious.

Instead, can you please extend the [`rotateSSHKeypairSecrets `](https://github.com/gardener/gardener/blob/6fda095b4b1ecb4904c762f125e66fbedd3ecadb/pkg/operation/botanist/secrets.go#L329-L358) function as discussed in our meeting last week? This function already "copies" the current `ssh-keypair` secret to `ssh-keypair.old` in the `ShootState`/`gardenerResourceDataList` and then deletes the `ssh-keypair` from it so that it gets regenerated. The only thing that is missing here is that the `ssh-keypair.old` secret gets created/updated in the seed cluster.

So, concrete proposal:

1. Only delete the `SecretNameSSHKeyPair ` secret in https://github.com/gardener/gardener/blob/6fda095b4b1ecb4904c762f125e66fbedd3ecadb/pkg/operation/botanist/secrets.go#L346-L350. It will be regenerated and automatically synced as usual.
2. Afterwards, create or update the content of the `SecretNameOldSSHKeyPair` secret with the data of the `SecretNameSSHKeyPair`.

**Review by rfranzke — CHANGES_REQUESTED** [review]

File: pkg/operation/botanist/wanted_secrets.go (hunk 2 above)
Comment (ary1992) [reply pkg/operation/botanist/wanted_secrets.go]: Addressed the feedback in [commit](https://github.com/gardener/gardener/pull/5388/commits/7ce65d1e4e8b46c65ae9122ce9e7c8f1e01e8b90).

File: pkg/operation/botanist/secrets.go [hunk 3]
```diff
@@ -441,6 +452,16 @@ func (b *Botanist) SyncShootCredentialsToGarden(ctx context.Context) error {
 		},
 	}
 
+	// ssh-keypair.old secret will be synced to the Garden cluster if it is present in shoot namespace in seed.
+	oldSecret := &corev1.Secret{}
+	if err := b.K8sSeedClient.Client().Get(ctx, kutil.Key(b.Shoot.SeedNamespace, v1beta1constants.SecretNameOldSSHKeyPair), oldSecret); err == nil {
```
Comment (rfranzke) [inline pkg/operation/botanist/secrets.go]: Do not silently ignore the error here

**Review by rfranzke — COMMENTED** [review]
Thanks, this looks much better now!
Should we also delete all the `ssh-keypair.old` secrets in seed and garden if their content is equal to the `ssh-keypair`, i.e., if they were never rotated? This would free up some space. OTOH, maybe it's not worth the effort given that once there was at least one SSH key rotation there will always be both `ssh-keypair` and `ssh-keypair.old`, so it's just a matter of time until all shoots have both.
cc @ialidzhikov

File: pkg/operation/botanist/secrets.go (hunk 3 above)
Comment (ary1992) [reply pkg/operation/botanist/secrets.go]: Here `err` will not be nil when the shoot is newly created. For newly created shoot there will be no `ssh-keypair.old` secret. Hence I am only considering the case where `ssh-keypair.old` secret is present and only in that case secret will be synced to garden cluster.

Comment (rfranzke) [reply pkg/operation/botanist/secrets.go]: Sure, but please handle "IsNotFound" errors and all other errors accordingly. Just silently ignoring errors is not a good practice.

Comment (ary1992) [reply pkg/operation/botanist/secrets.go]: Addressed in [commit](https://github.com/gardener/gardener/pull/5388/commits/328decb0af508ddc927789babd8b18b9d8d7b66a)

**Comment by ary1992** [comment]
>Should we also delete all the ssh-keypair.old secrets in seed and garden if their content is equal to the ssh-keypair, i.e., if they were never rotated? This would free up some space.

By this you mean the `ssh-keypair.old` secrets which were created during the shoot creation process ? I don't think the content of ssh-keypair.old and ssh-keypair created during shoot creation are equal.

File: pkg/operation/botanist/secrets.go [hunk 4]
```diff
@@ -441,6 +453,21 @@ func (b *Botanist) SyncShootCredentialsToGarden(ctx context.Context) error {
...
+		if apierrors.IsNotFound(err) {
+			b.Logger.Info("Newly created shoot will not have ssh-keypair.old secret")
+		}
+	} else {
+		projectSecrets = append(projectSecrets, projectSecret{
+			secretName: v1beta1constants.SecretNameOldSSHKeyPair,
+			suffix:     gutil.ShootProjectSecretSuffixOldSSHKeypair,
+			labels:     map[string]string{v1beta1constants.GardenRole: v1beta1constants.GardenRoleSSHKeyPair},
+		})
+	}
```
Comment (rfranzke) [inline pkg/operation/botanist/secrets.go]:
```suggestion
	if err := b.K8sSeedClient.Client().Get(ctx, kutil.Key(b.Shoot.SeedNamespace, v1beta1constants.SecretNameOldSSHKeyPair), oldSecret); err != nil {
		if !apierrors.IsNotFound(err) {
			return err
		}
	} else {
		projectSecrets = append(projectSecrets, projectSecret{
			secretName: v1beta1constants.SecretNameOldSSHKeyPair,
			suffix:     gutil.ShootProjectSecretSuffixOldSSHKeypair,
			labels:     map[string]string{v1beta1constants.GardenRole: v1beta1constants.GardenRoleSSHKeyPair},
		})
	}
```

File: pkg/operation/botanist/secrets.go [hunk 5]
```diff
@@ -459,7 +486,11 @@ func (b *Botanist) SyncShootCredentialsToGarden(ctx context.Context) error {
 				secretObj.Annotations = s.annotations
 				secretObj.Labels = s.labels
 				secretObj.Type = corev1.SecretTypeOpaque
-				secretObj.Data = b.LoadSecret(s.secretName).Data
+				if s.secretName == v1beta1constants.SecretNameOldSSHKeyPair {
+					secretObj.Data = oldSecret.Data
+				} else {
+					secretObj.Data = b.LoadSecret(s.secretName).Data
+				}
```
Comment (rfranzke) [inline pkg/operation/botanist/secrets.go]: Why don't you simply run `b.StoreSecret` above when the old secret was found? Then you can keep this code untouched.

File: pkg/operation/botanist/secrets.go [hunk 6]
```diff
@@ -338,16 +340,31 @@ func (b *Botanist) rotateSSHKeypairSecrets(ctx context.Context, gardenerResource
...
+	if err := b.K8sSeedClient.Client().Get(ctx, kutil.Key(b.Shoot.SeedNamespace, v1beta1constants.SecretNameSSHKeyPair), secretSSHkeypair); err != nil {
+		return err
 	}
 
-	for _, secretName := range names {
-		if err := b.K8sSeedClient.Client().Delete(ctx, &corev1.Secret{ObjectMeta: metav1.ObjectMeta{Name: secretName, Namespace: b.Shoot.SeedNamespace}}); client.IgnoreNotFound(err) != nil {
-			return err
-		}
+	// old ssh keypair to be created in shoot namespace in seed
+	secretOldSSHkeypair := &corev1.Secret{
```
Comment (rfranzke) [inline pkg/operation/botanist/secrets.go]: Nit (symmetry):

```suggestion
	secretOldSSHKeyPair := &corev1.Secret{
```

**Comment by rfranzke** [comment]
> > Should we also delete all the ssh-keypair.old secrets in seed and garden if their content is equal to the ssh-keypair, i.e., if they were never rotated? This would free up some space.
> 
> By this you mean the `ssh-keypair.old` secrets which were created during the shoot creation process ?  I don't think the content of ssh-keypair.old and ssh-keypair created during shoot creation are equal.

Right... this means we have no good way to identify that there never was a rotation before. Well then, let's keep it...

File: pkg/operation/botanist/wanted_secrets.go [hunk 7]
```diff
@@ -290,13 +290,6 @@ func (b *Botanist) generateWantedSecretConfigs(basicAuthAPIServer *secrets.Basic
 			UsedForSSH: true,
 		},
 
-		// Secret definition for ssh-keypair.old
```
Comment (plkokanov) [inline pkg/operation/botanist/wanted_secrets.go:293]: Due to the way the infodata and secret generation work currently, removing the secret from here means that it will not be deployed during the restore phase of control plane migration, even if it gets added to the ShootState in the following lines in secrets.go:  [332-341](https://github.com/gardener/gardener/blob/328decb0af508ddc927789babd8b18b9d8d7b66a/pkg/operation/botanist/secrets.go#L332-L341)

~What you can do instead is: remove the SecretNameOldSSHKeyPair from line 293 (as you've already done in the PR) and then add the following on line [381](https://github.com/gardener/gardener/blob/328decb0af508ddc927789babd8b18b9d8d7b66a/pkg/operation/botanist/wanted_secrets.go#L381)~

```
	shootState := b.GetShootState()
	gardenerResourceDataList := gardencorev1alpha1helper.GardenerResourceDataList(shootState.Spec.Gardener)
	if gardenerResourceDataList.Get(v1beta1constants.SecretNameOldSSHKeyPair) != nil {
		secretList = append(secretList, &secrets.RSASecretConfig{
			Name:       v1beta1constants.SecretNameOldSSHKeyPair,
			Bits:       4096,
			UsedForSSH: true,
		})
	}
```

~Then I think you wouldn't need to make any changes at all in the `rotateSSHKeypairSecrets` function.~

**Edit**: I missed that this was already discussed and @ary1992 notified me of that and I agree that it's a bit of a "hacky" approach.
In that case if we need to have the old sshKeyPair in the shoot's namespace on the seed, you would have to get the old sshKeyPairSecret from the garden cluster, then deploy it in the shoot's namespace in the seed cluster during the restore phase of control plane migration.

**Review by plkokanov — CHANGES_REQUESTED** [review]
Really sorry for joining so late to this. Check my inline comments.

File: pkg/operation/botanist/secrets.go (hunk 4 above)
Comment (ary1992) [reply pkg/operation/botanist/secrets.go]: Addressed in [commit](https://github.com/gardener/gardener/pull/5388/commits/8e9970ad6576f23a3b8b79382aa9c8542ddd7ad4).

File: pkg/operation/botanist/secrets.go (hunk 5 above)
Comment (ary1992) [reply pkg/operation/botanist/secrets.go]: Addressed in [commit](https://github.com/gardener/gardener/pull/5388/commits/8e9970ad6576f23a3b8b79382aa9c8542ddd7ad4).

File: pkg/operation/botanist/secrets.go (hunk 6 above)
Comment (ary1992) [reply pkg/operation/botanist/secrets.go]: Addressed in [commit](https://github.com/gardener/gardener/pull/5388/commits/8e9970ad6576f23a3b8b79382aa9c8542ddd7ad4).

File: pkg/operation/botanist/wanted_secrets.go (hunk 7 above)
Comment (ary1992) [reply pkg/operation/botanist/wanted_secrets.go:293]: Addressed in [commit](https://github.com/gardener/gardener/pull/5388/commits/9f0cfab678679b06769f8b813b3ad2db5830a7ad).

**Review by rfranzke — DISMISSED** [review]

File: pkg/operation/botanist/secrets.go [hunk 8]
```diff
@@ -194,10 +197,43 @@ func (b *Botanist) DeploySecrets(ctx context.Context) error {
...
+				Namespace: b.Shoot.SeedNamespace,
+			},
+		}
+		if _, err := controllerutils.GetAndCreateOrMergePatch(ctx, b.K8sSeedClient.Client(), secret, func() error {
+			secret.Type = corev1.SecretTypeOpaque
+			secret.Data = oldSSHKeyPairData.SecretData()
+			return nil
+		}); err != nil {
+			return err
+		}
```
Comment (plkokanov) [inline pkg/operation/botanist/secrets.go:234]: The secret needs to be stored so that it can be used by the operating system config deployment [here](https://github.com/gardener/gardener/blob/4825315b78e020e612958d06fe613518dbf784d2/pkg/operation/botanist/operatingsystemconfig.go#L95):
```
b.StoreSecret(v1beta1constants.SecretNameOldSSHKeyPair, secret)
```
I see that it is currently stored in `SyncShootCredentialsToGarden` but the OSC deployment does not depend on that, so I think there's a chance that `DeployOperatingSystemConfig` can be called in parallel or before `SyncShootCredentialsToGarden`

**Review by plkokanov — CHANGES_REQUESTED** [review]

File: pkg/operation/botanist/secrets.go [hunk 9]
```diff
@@ -441,6 +467,21 @@ func (b *Botanist) SyncShootCredentialsToGarden(ctx context.Context) error {
...
 	}
 
+	// ssh-keypair.old secret will be synced to the Garden cluster if it is present in shoot namespace in seed.
+	oldSecret := &corev1.Secret{}
+	if err := b.K8sSeedClient.Client().Get(ctx, kutil.Key(b.Shoot.SeedNamespace, v1beta1constants.SecretNameOldSSHKeyPair), oldSecret); err != nil {
+		if !apierrors.IsNotFound(err) {
+			return err
+		}
+	} else {
+		b.StoreSecret(v1beta1constants.SecretNameOldSSHKeyPair, oldSecret)
```
Comment (rfranzke) [inline pkg/operation/botanist/secrets.go]: This line can be removed now, right? You already store it here: https://github.com/gardener/gardener/pull/5388/files#diff-5a59ce10d2c8c2ae85d9458b6e256e7e957d3b21b160380bb121fddb4a98befcR235

**Review by plkokanov — APPROVED** [review]
/lgtm
