### PR TITLE
ETCD Encryption Config: improve validation

### LINKED ISSUE #12338: ETCD Encryption Config: insufficient validation
**How to categorize this issue?**

/area security
/kind bug

**What happened**:
I tried encrypting encrypting all `ConfigMaps` in my `Shoot` cluster by adding them to the `spec.kubernetes.kubeAPIServer.encryptionConfig.resources` field:
``` yaml
spec:
  kubernetes:
    kubeAPIServer:
      encryptionConfig:
        resources:
          - ConfigMaps
```

The `Shoot` reconciliation failed on waiting the kube-apiserver to get ready. The apiserver pods were in errored state with logs:
```
E0617 07:10:33.024360       1 run.go:72] "command failed" err="error while parsing file: resources[0].resources[0]: Invalid value: \"ConfigMaps\": resource name should not contain capital letters"
```

Removing the `ConfigMaps` resource from `spec.kubernetes.kubeAPIServer.encryptionConfig.resources` is not allowed by validation:
```
Shoot.core.gardener.cloud "foo" is invalid: spec.kubernetes.kubeAPIServer.encryptionConfig.resources: Forbidden: resources cannot be changed because a previous encryption configuration change is currently being rolled out
```

You need to edit the `Shoot` status to mend the cluster.

**What you expected to happen**:
The `Shoot` API to not allow me to apply changes that would bring the cluster to an errored state.

**How to reproduce it (as minimally and precisely as possible)**:
Add string with capital letters to the `spec.kubernetes.kubeAPIServer.encryptionConfig.resources` field as shown above.

**Anything else we need to know?**:
We should adapt to the validation from [kubernetes](https://github.com/kubernetes/kubernetes/blob/8adc0f041b8e7ad1d30e29cc59c6ae7a15e19828/staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation_encryption.go#L122-L284).

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by AleksandarSavchev**
**How to categorize this PR?**

/area security
/kind bug

**What this PR does / why we need it**:
This PR adopts validation from [Kubernetes](https://github.com/kubernetes/kubernetes/blob/8adc0f041b8e7ad1d30e29cc59c6ae7a15e19828/staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation_encryption.go#L122-L284) for the encryption config. It also takes advantage of [schema.GroupResource](https://github.com/kubernetes/kubernetes/blob/8adc0f041b8e7ad1d30e29cc59c6ae7a15e19828/staging/src/k8s.io/apimachinery/pkg/runtime/schema/group_version.go#L54-L59) for more reliable comparisons between encryption configs.

**Which issue(s) this PR fixes**:
Fixes #12338

**Special notes for your reviewer**:

**Release note**:

```breaking user
Setting resources with `.` suffix in the `spec.kubernetes.kubeAPIServer.encryptionConfig.resources` field is now forbidden.
```
```bugfix user
A bug causing the `kube-apiserver` to crash due to invalid resources in the `spec.kubernetes.kubeAPIServer.encryptionConfig.resources` was fixed.
```
```bugfix user
A bug forbidding the update of `spec.kubernetes.kubeAPIServer.encryptionConfig.resources` due to use of `.` suffix in resources was fixed.
```

### CODE REVIEW

File: pkg/apis/core/validation/shoot.go [hunk 1]
```diff
@@ -1101,31 +1110,46 @@ func ValidateAPIServerRequests(requests *core.APIServerRequests, fldPath *field.
...
+		}
+		if resource == "apiserveripinfo" || resource == "serviceipallocations" || resource == "servicenodeportallocations" {
+			allErrs = append(allErrs, field.Invalid(idxPath, resource, "resource cannot be encrypted"))
 		}
 
-		// core resources can be mentioned with empty group (eg: secrets.)
-		if defaultEncryptedResources.Has(strings.TrimSuffix(resource, ".")) {
+		if gr.Group == "events.k8s.io" {
+			allErrs = append(allErrs, field.Invalid(idxPath, resource, "'*.events.k8s.io' objects are stored using the 'events' API group in etcd"))
+		}
```
Comment (shafeeqes) [inline pkg/apis/core/validation/shoot.go]: Maybe use the full error from https://github.com/kubernetes/kubernetes/blob/8adc0f041b8e7ad1d30e29cc59c6ae7a15e19828/staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation_encryption.go#L46?

File: pkg/component/shared/apiserver_test.go [hunk 2]
```diff
@@ -20,13 +22,38 @@ var _ = Describe("APIServer", func() {
...
+			Expect(StringifyGroupResources(nil)).To(BeNil())
+		})
+
+		It("should return the correct list of resources when resources are not nil", func() {
+			resources := []schema.GroupResource{
+				schema.GroupResource{Resource: "deployments", Group: "apps"},
+				schema.GroupResource{Resource: "fancyresource", Group: "customoperator.io"},
+				schema.GroupResource{Resource: "configmaps", Group: ""},
+				schema.GroupResource{Resource: "services", Group: ""},
+				schema.GroupResource{Resource: "daemonsets", Group: "apps"},
```
Comment (shafeeqes) [inline pkg/component/shared/apiserver_test.go]: Nit:
```suggestion
				{Resource: "deployments", Group: "apps"},
				{Resource: "fancyresource", Group: "customoperator.io"},
				{Resource: "configmaps", Group: ""},
				{Resource: "services", Group: ""},
				{Resource: "daemonsets", Group: "apps"},
```

File: pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go [hunk 3]
```diff
@@ -511,7 +511,7 @@ func (r *Reconciler) runReconcileShootFlow(ctx context.Context, o *operation.Ope
 					if err := o.Shoot.UpdateInfoStatus(ctx, o.GardenClient, true, false, func(shoot *gardencorev1beta1.Shoot) error {
 						var encryptedResources []string
 						if o.Shoot.GetInfo().Spec.Kubernetes.KubeAPIServer != nil {
-							encryptedResources = shared.GetResourcesForEncryptionFromConfig(o.Shoot.GetInfo().Spec.Kubernetes.KubeAPIServer.EncryptionConfig)
+							encryptedResources = shared.StringifyGroupResources(shared.GetResourcesForEncryptionFromConfig(o.Shoot.GetInfo().Spec.Kubernetes.KubeAPIServer.EncryptionConfig))
```
Comment (shafeeqes) [inline pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go:514]: This can cause a resource to be present as `services.` in the spec and just `services` in the status, right?
I don't think we want that.

File: pkg/operator/controller/garden/garden/reconciler_reconcile.go [hunk 4]
```diff
@@ -169,7 +169,7 @@ func (r *Reconciler) reconcile(
 		virtualClusterClientSet kubernetes.Interface
 		virtualClusterClient    client.Client
 		defaultEncryptedGVKs    = append(gardenerutils.DefaultGardenerGVKsForEncryption(), gardenerutils.DefaultGVKsForEncryption()...)
-		resourcesToEncrypt      = append(shared.NormalizeResources(getKubernetesResourcesForEncryption(garden)), getGardenerResourcesForEncryption(garden)...)
+		resourcesToEncrypt      = append(shared.StringifyGroupResources(getKubernetesResourcesForEncryption(garden)), shared.StringifyGroupResources(getGardenerResourcesForEncryption(garden))...)
```
Comment (shafeeqes) [inline pkg/operator/controller/garden/garden/reconciler_reconcile.go:172]: same here

File: pkg/utils/gardener/secretsrotation/etcd.go [hunk 5]
```diff
@@ -242,11 +239,11 @@ func GetResourcesForRewrite(
 	error,
 ) {
 	var (
-		resourcesForRewrite        = resourcesToEncrypt
-		encryptionConfigHasChanged = !apiequality.Semantic.DeepEqual(resourcesToEncrypt, encryptedResources)
+		resourcesForRewrite = resourcesToEncrypt
+		// encryptionConfigHasChanged = !apiequality.Semantic.DeepEqual(resourcesToEncrypt, encryptedResources)
```
Comment (shafeeqes) [inline pkg/utils/gardener/secretsrotation/etcd.go]: leftover?

File: pkg/utils/gardener/secretsrotation/etcd_test.go [hunk 6]
```diff
@@ -331,6 +331,35 @@ var _ = Describe("ETCD", func() {
 			))
 		})
 
+		It("should return the correct GVK list when not all resources are part from resourece list", func() {
```
Comment (shafeeqes) [inline pkg/utils/gardener/secretsrotation/etcd_test.go]: typo "resource"

Comment (shafeeqes) [reply pkg/utils/gardener/secretsrotation/etcd_test.go]: What exactly is the test case here? Is it when all the resources in the `resourcesToEncrypt` are not present in the discovered resouces? The string isn't very clear, can we improve it?

File: pkg/utils/gardener/secretsrotation/etcd.go [hunk 7]
```diff
@@ -257,22 +254,7 @@ func GetResourcesForRewrite(
...
-			coreResourcesToEncrypt.Insert(resource)
-			continue
-		}
-
-		if _, ok := groupResourcesToEncrypt[group]; !ok {
-			groupResourcesToEncrypt[group] = sets.New[string]()
-		}
-
-		groupResourcesToEncrypt[group].Insert(resource)
+		groupResourcesToEncrypt = append(groupResourcesToEncrypt, schema.ParseGroupResource(resource))
```
Comment (shafeeqes) [inline pkg/utils/gardener/secretsrotation/etcd.go:256]: Nice!

File: pkg/utils/gardener/secretsrotation/etcd.go [hunk 8]
```diff
@@ -310,12 +292,11 @@ func GetResourcesForRewrite(
 				version = apiResource.Version
 			}
 
-			if group == corev1.SchemeGroupVersion.Group && coreResourcesToEncrypt.Has(apiResource.Name) {
-				encryptedGVKs.Insert(schema.GroupVersionKind{Group: group, Version: version, Kind: apiResource.Kind})
-				continue
-			}
+			shouldEncrypt := slices.ContainsFunc(groupResourcesToEncrypt, func(gr schema.GroupResource) bool {
```
Comment (shafeeqes) [inline pkg/utils/gardener/secretsrotation/etcd.go]: Nit: variable can be inlined

**Review by shafeeqes — COMMENTED** [review]
Thanks for the well-structured PR!

File: pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go (hunk 3 above)
Comment (AleksandarSavchev) [reply pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go:514]: You are correct, this will cause core resources that end with `.` to be written in the status without the suffix. 

Currently there is a bug where the status is not updated when you edit a core resource by only removing/adding the `.` ref: https://github.com/gardener/gardener/issues/12338#issuecomment-2982796124. It happens since the status is updated on [this check](https://github.com/gardener/gardener/blob/2479022e2a59bb0e6b8bcf9ebbebfe366c9a08b9/pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go#L510) which compares resources after normalization.

It might be best to store the values in status the same way we store them for the EncryptionConfig used for the apiserver (which are also normalized/ stringified)?

File: pkg/apis/core/validation/shoot.go [hunk 9]
```diff
@@ -1134,7 +1134,7 @@ func validateEncryptionConfig(encryptionConfig *core.EncryptionConfig, defaultEn
 		}
 
 		if gr.Group == "events.k8s.io" {
-			allErrs = append(allErrs, field.Invalid(idxPath, resource, "'*.events.k8s.io' objects are stored using the 'events' API group in etcd"))
+			allErrs = append(allErrs, field.Invalid(idxPath, resource, "'*.events.k8s.io' objects are stored using the 'events' API group in etcd. Use 'events' instead in the config file"))
```
Comment (shafeeqes) [inline pkg/apis/core/validation/shoot.go]:
```suggestion
			allErrs = append(allErrs, field.Invalid(idxPath, resource, "'*.events.k8s.io' objects are stored using the 'events' API group in etcd. Use 'events' instead"))
```
User doesn't know about the config file

File: pkg/utils/gardener/secretsrotation/etcd.go [hunk 10]
```diff
@@ -292,11 +291,9 @@ func GetResourcesForRewrite(
 				version = apiResource.Version
 			}
 
-			shouldEncrypt := slices.ContainsFunc(groupResourcesToEncrypt, func(gr schema.GroupResource) bool {
+			if shouldEncrypt := slices.ContainsFunc(groupResourcesToEncrypt, func(gr schema.GroupResource) bool {
 				return gr.Group == group && gr.Resource == apiResource.Name
-			})
-
-			if shouldEncrypt {
+			}); shouldEncrypt {
```
Comment (shafeeqes) [inline pkg/utils/gardener/secretsrotation/etcd.go]:
```suggestion
			if slices.ContainsFunc(groupResourcesToEncrypt, func(gr schema.GroupResource) bool {
				return gr.Group == group && gr.Resource == apiResource.Name
			}) {
```

File: pkg/utils/gardener/secretsrotation/etcd_test.go [hunk 11]
```diff
@@ -331,7 +331,7 @@ var _ = Describe("ETCD", func() {
 			))
 		})
 
-		It("should return the correct GVK list when not all resources are part from resourece list", func() {
+		It("should return the correct GVK list when not all resources are part from the discovered resources list", func() {
```
Comment (shafeeqes) [inline pkg/utils/gardener/secretsrotation/etcd_test.go]:
```suggestion
		It("should return the correct GVK list when not all resources are part of the discovered resources list", func() {
```

File: pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go (hunk 3 above)
Comment (shafeeqes) [reply pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go:514]: Let's fix the check, then.
It might be confusing for the user if the resources in the spec and status are not the same. WDYT?

File: pkg/utils/gardener/shoot.go [hunk 12]
```diff
@@ -788,6 +788,13 @@ func DefaultGVKsForEncryption() []schema.GroupVersionKind {
 	}
 }
 
+// DefaultGRsForEncryption returns the list of GroupResources which are encrypted by default.
+func DefaultGRsForEncryption() []schema.GroupResource {
```
Comment (dimityrmirchev) [inline pkg/utils/gardener/shoot.go]: I do not think that shortening the name makes sense here.
```suggestion
func DefaultGroupResourcesForEncryption() []schema.GroupResource {
```

File: pkg/apis/core/validation/shoot.go [hunk 13]
```diff
@@ -1101,31 +1110,46 @@ func ValidateAPIServerRequests(requests *core.APIServerRequests, fldPath *field.
...
-			allErrs = append(allErrs, field.Duplicate(idxPath, resource))
+		var (
+			idxPath = fldPath.Child("encryptionConfig", "resources").Index(i)
+			gr      = schema.ParseGroupResource(resource)
+		)
+
+		if strings.ToLower(resource) != resource {
+			allErrs = append(allErrs, field.Invalid(idxPath, resource, "resource must be lower case"))
+		}
+		if resource == "apiserveripinfo" || resource == "serviceipallocations" || resource == "servicenodeportallocations" {
```
Comment (dimityrmirchev) [inline pkg/apis/core/validation/shoot.go:1134]: Can you please leave a comment referencing why these cannot be encrypted?

File: pkg/apis/core/validation/shoot.go [hunk 14]
```diff
@@ -1101,31 +1110,46 @@ func ValidateAPIServerRequests(requests *core.APIServerRequests, fldPath *field.
...
+			allErrs = append(allErrs, field.Invalid(idxPath, resource, "resource cannot be encrypted"))
 		}
 
-		// core resources can be mentioned with empty group (eg: secrets.)
-		if defaultEncryptedResources.Has(strings.TrimSuffix(resource, ".")) {
+		if gr.Group == "events.k8s.io" {
+			allErrs = append(allErrs, field.Invalid(idxPath, resource, "'*.events.k8s.io' objects are stored using the 'events' API group in etcd. Use 'events' instead in the config file"))
+		}
+		if gr.Group == "extensions" {
```
Comment (dimityrmirchev) [inline pkg/apis/core/validation/shoot.go:1147]: Please clarify why is this the case.

File: pkg/apis/core/validation/shoot.go [hunk 15]
```diff
@@ -2934,16 +2967,16 @@ func isShootReadyForRotationStart(lastOperation *core.LastOperation) bool {
 	return lastOperation.Type == core.LastOperationTypeReconcile
 }
 
-func getResourcesForEncryption(apiServerConfig *core.KubeAPIServerConfig) []string {
-	resources := sets.New[string]()
+func getResourcesForEncryption(apiServerConfig *core.KubeAPIServerConfig) []schema.GroupResource {
```
Comment (dimityrmirchev) [inline pkg/apis/core/validation/shoot.go:2975]: Can we have duplicates in this slice?

File: pkg/apis/core/validation/shoot_test.go [hunk 16]
```diff
@@ -2073,6 +2116,30 @@ var _ = Describe("Shoot Validation Tests", func() {
 					))
 				})
 
+				It("should deny specifying wildcard resources", func() {
```
Comment (dimityrmirchev) [inline pkg/apis/core/validation/shoot_test.go:2111]: Is `foo.*.bar` a valid test case?

File: pkg/apis/core/validation/shoot_test.go [hunk 17]
```diff
@@ -5457,7 +5564,7 @@ var _ = Describe("Shoot Validation Tests", func() {
 				shoot.Spec.Hibernation = &core.Hibernation{Enabled: ptr.To(false)}
 				shoot.Spec.Kubernetes.KubeAPIServer = &core.KubeAPIServerConfig{
 					EncryptionConfig: &core.EncryptionConfig{
-						Resources: []string{"events", "configmaps"},
+						Resources: []string{"events", "configmaps."},
```
Comment (dimityrmirchev) [inline pkg/apis/core/validation/shoot_test.go]: I am not sure how does `configmaps` differ from `configmaps.`. Can you please elaborate?

File: pkg/apis/core/validation/shoot.go [hunk 18]
```diff
@@ -1101,31 +1110,46 @@ func ValidateAPIServerRequests(requests *core.APIServerRequests, fldPath *field.
 	return allErrs
 }
 
-func validateEncryptionConfig(encryptionConfig *core.EncryptionConfig, defaultEncryptedResources sets.Set[string], fldPath *field.Path) field.ErrorList {
-	allErrs := field.ErrorList{}
+func validateEncryptionConfig(encryptionConfig *core.EncryptionConfig, defaultEncryptedResources []schema.GroupResource, fldPath *field.Path) field.ErrorList {
+	var (
+		allErrs       = field.ErrorList{}
+		seenResources []schema.GroupResource
```
Comment (dimityrmirchev) [inline pkg/apis/core/validation/shoot.go]: We can still use the set here?
```suggestion
		seenResources = sets.New[schema.GroupResource]()
```

File: pkg/apis/operator/v1alpha1/validation/garden.go [hunk 19]
```diff
@@ -392,27 +392,33 @@ func validateGardenerAPIServerConfig(config *operatorv1alpha1.GardenerAPIServerC
 	}
 
 	if config.EncryptionConfig != nil {
-		seenResources := sets.New[string]()
+		var seenResources []schema.GroupResource
```
Comment (dimityrmirchev) [inline pkg/apis/operator/v1alpha1/validation/garden.go]:
```suggestion
                 seenResources := sets.New[schema.GroupResource]()
```

File: pkg/apis/operator/v1alpha1/validation/garden.go [hunk 20]
```diff
@@ -392,27 +392,33 @@ func validateGardenerAPIServerConfig(config *operatorv1alpha1.GardenerAPIServerC
...
+			if slices.Contains(seenResources, gr) {
+				allErrs = append(allErrs, field.Duplicate(idxPath, resource))
+			}
+			if slices.Contains(gardenerutils.DefaultGardenerGRsForEncryption(), gr) {
 				allErrs = append(allErrs, field.Forbidden(idxPath, fmt.Sprintf("%q are always encrypted", resource)))
 			}
-
-			if !operator.IsServedByGardenerAPIServer(resource) {
-				allErrs = append(allErrs, field.Invalid(idxPath, resource, "should be a resource served by gardener-apiserver. ie; should have any of the suffixes {authentication,core,operations,security,settings,seedmanagement}.gardener.cloud"))
+			if gr.Resource == "*" || gr.Group == "*" {
```
Comment (dimityrmirchev) [inline pkg/apis/operator/v1alpha1/validation/garden.go]: Can we do this? It seems simpler.

```suggestion
			if strings.Contains(resource, "*") {
```

File: pkg/apis/operator/v1alpha1/validation/garden.go [hunk 21]
```diff
@@ -392,27 +392,33 @@ func validateGardenerAPIServerConfig(config *operatorv1alpha1.GardenerAPIServerC
...
+				allErrs = append(allErrs, field.Invalid(idxPath, resource, "wildcards are not supported"))
 			}
 
-			if strings.HasPrefix(resource, "*") {
-				allErrs = append(allErrs, field.Invalid(idxPath, resource, "wildcards are not supported"))
+			if !operator.IsServedByGardenerAPIServer(resource) && gr.Group != "*" {
```
Comment (dimityrmirchev) [inline pkg/apis/operator/v1alpha1/validation/garden.go]: Maybe we do not need the wildcard check.
```suggestion
			if !operator.IsServedByGardenerAPIServer(resource) {
```

File: pkg/component/shared/apiserver.go [hunk 22]
```diff
@@ -338,7 +354,7 @@ func NormalizeResources(resources []string) []string {
 	var out []string
 
 	for _, resource := range resources {
-		out = append(out, strings.TrimSuffix(resource, "."))
+		out = append(out, schema.ParseGroupResource(resource).String())
```
Comment (dimityrmirchev) [inline pkg/component/shared/apiserver.go]: This changes the behaviour as `configmap.foo.` would no longer be stripped from from "."

File: pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go (hunk 3 above)
Comment (dimityrmirchev) [reply pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go:514]: I wonder if we should even allow `services.` if there is no difference to `services`.

File: pkg/utils/gardener/garden.go [hunk 23]
```diff
@@ -329,6 +329,16 @@ func DefaultGardenerGVKsForEncryption() []schema.GroupVersionKind {
 	}
 }
 
+// DefaultGardenerGRsForEncryption returns the list of [schema.GroupResource] served by Gardener API Server which are encrypted by default.
+func DefaultGardenerGRsForEncryption() []schema.GroupResource {
```
Comment (dimityrmirchev) [inline pkg/utils/gardener/garden.go]:
```suggestion
func DefaultGardenerGroupResourcesForEncryption() []schema.GroupResource {
```

**Review by dimityrmirchev — CHANGES_REQUESTED** [review]
Thank you for improving the validation! I have left some comments and questions.

File: pkg/apis/core/validation/shoot_test.go (hunk 17 above)
Comment (AleksandarSavchev) [reply pkg/apis/core/validation/shoot_test.go]: In the context of encryption resources the core resources can be written with and without the suffix `.` (e.g. `configmaps` == `configmaps.`).

I think is done in Kubernetes in order to present a way to select all resources in the core group with `*.` [ref](https://github.com/kubernetes/kubernetes/blob/8adc0f041b8e7ad1d30e29cc59c6ae7a15e19828/staging/src/k8s.io/apiserver/pkg/apis/apiserver/types_encryption.go#L82). Using simply `*` would have been confusing given that `*` is normally used to target all resources.

Since we do not support wildcards for encrypted resources [ref](https://github.com/gardener/gardener/issues/12337), we can also forbid the use of the suffix `.`

File: pkg/apis/core/validation/shoot.go (hunk 15 above)
Comment (AleksandarSavchev) [reply pkg/apis/core/validation/shoot.go:2975]: We validate for duplicates here: https://github.com/gardener/gardener/blob/b09d978518c66c3dff2498964becaa31b7d986b3/pkg/apis/core/validation/shoot.go#L1142-L1144

File: pkg/apis/core/validation/shoot_test.go (hunk 16 above)
Comment (AleksandarSavchev) [reply pkg/apis/core/validation/shoot_test.go:2111]: `foo.*.bar` is a valid test case, we can also forbid using `*` as a substring in a resource since in our case there should be no use of wildcards and the resource name and group cannot contain `*`, as stated [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types): `Resource collections should be all lowercase and plural, whereas kinds are CamelCase and singular. Group names must be lower case and be valid DNS subdomains.`

File: pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go (hunk 3 above)
Comment (shafeeqes) [reply pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go:514]: Forbidding it now can be a breaking change

File: pkg/component/shared/apiserver.go (hunk 22 above)
Comment (AleksandarSavchev) [reply pkg/component/shared/apiserver.go]: Great catch! After testing on local setup, this would be a backward incompatible change.

Having a cluster with specified resources for encryption, other than the core group ones, ending with a `.` would currently lead to them being encrypted(e.g. `deployments.apps.` would lead to the encryption of `deployments.apps`). If Gardener is upgraded with the changes of this PR and the `Shoot` is updated to not include `deployments.apps.` it would not lead to the decryption of `deployments.apps` since `deployments.apps.` would not be stripped from the `.`. The resources then would not be able to be decrypted from the API server, but the decryption key would still be present in the config (until key rotation).

I will leave the trimming of `.` for backwards compatibility

File: pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go (hunk 3 above)
Comment (AleksandarSavchev) [reply pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go:514]: With the current changes to validation there can also be breaking cases (e.g. `foo.*.bar` would not longer be valid). 

There is also a "bug" where non core resources can be written in a `.` as suffix and we would resolve it to the correct resource [ref](https://github.com/gardener/gardener/pull/12355#discussion_r2158912772). It would not be trivial to fix and it might be best to forbid `.` as suffix to avoid further inconsistencies.

Comment (AleksandarSavchev) [reply pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go:514]: I have now added a commit which forbids the use of the `.` suffix as it can bring confusion, and would work not as intended for non core resources.

**Comment by dimityrmirchev** [comment]
@AleksandarSavchev We should add a breaking note that "." suffixes are forbidden.

File: pkg/utils/gardener/shoot_test.go [hunk 24]
```diff
@@ -1423,6 +1423,14 @@ var _ = Describe("Shoot", func() {
 		})
 	})
 
+	Describe("#DefaultGRForEncryption", func() {
```
Comment (dimityrmirchev) [inline pkg/utils/gardener/shoot_test.go]:
```suggestion
	Describe("#DefaultGroupResourcesForEncryption", func() {
```

File: pkg/utils/gardener/garden_test.go [hunk 25]
```diff
@@ -328,6 +328,17 @@ var _ = Describe("Garden", func() {
 		})
 	})
 
+	Describe("#DefaultGardenerGRsForEncryption", func() {
```
Comment (dimityrmirchev) [inline pkg/utils/gardener/garden_test.go]:
```suggestion
	Describe("#DefaultGardenerGroupResourcesForEncryption", func() {
```

**Review by dimityrmirchev — CHANGES_REQUESTED** [review]
Two nits

**Review by dimityrmirchev — APPROVED** [review]
/lgtm

File: pkg/apis/core/validation/shoot_test.go [hunk 26]
```diff
@@ -1996,51 +1996,100 @@ var _ = Describe("Shoot Validation Tests", func() {
...
-							"Type":  Equal(field.ErrorTypeDuplicate),
-							"Field": Equal("spec.kubernetes.kubeAPIServer.encryptionConfig.resources[3]"),
+							"Type":   Equal(field.ErrorTypeInvalid),
+							"Field":  Equal("spec.kubernetes.kubeAPIServer.encryptionConfig.resources[1]"),
+							"Detail": Equal("resource must be lower case"),
+						})),
+					))
+				})
+
+				It("should deny using none encryptable resources", func() {
```
Comment (shafeeqes) [inline pkg/apis/core/validation/shoot_test.go]:
```suggestion
				It("should deny using non-encryptable resources", func() {
```

File: pkg/apis/core/validation/shoot_test.go [hunk 27]
```diff
@@ -1996,51 +1996,100 @@ var _ = Describe("Shoot Validation Tests", func() {
...
+						})),
+						PointTo(MatchFields(IgnoreExtras, Fields{
+							"Type":   Equal(field.ErrorTypeInvalid),
+							"Field":  Equal("spec.kubernetes.kubeAPIServer.encryptionConfig.resources[2]"),
+							"Detail": Equal("resources which do not have REST API/s cannot be encrypted"),
+						})),
+					))
+				})
+
+				It("should deny using specific group", func() {
```
Comment (shafeeqes) [inline pkg/apis/core/validation/shoot_test.go]:
```suggestion
				It("should deny using specific groups", func() {
```

File: pkg/apis/core/validation/shoot_test.go [hunk 28]
```diff
@@ -1996,51 +1996,100 @@ var _ = Describe("Shoot Validation Tests", func() {
...
 						})),
+						PointTo(MatchFields(IgnoreExtras, Fields{
+							"Type":  Equal(field.ErrorTypeDuplicate),
+							"Field": Equal("spec.kubernetes.kubeAPIServer.encryptionConfig.resources[3]"),
+						})),
 					))
 				})
 
-				It("should deny specifying wildcard resources", func() {
+				It("should deny resoureces with '.' suffix", func() {
```
Comment (shafeeqes) [inline pkg/apis/core/validation/shoot_test.go]:
```suggestion
				It("should deny resources with '.' suffix", func() {
```

File: pkg/apis/core/validation/shoot.go [hunk 29]
```diff
@@ -1101,31 +1110,51 @@ func ValidateAPIServerRequests(requests *core.APIServerRequests, fldPath *field.
...
+			allErrs = append(allErrs, field.Invalid(idxPath, resource, "resource must be lower case"))
 		}
-
-		if strings.HasPrefix(resource, "*") {
+		if resource == "apiserveripinfo" || resource == "serviceipallocations" || resource == "servicenodeportallocations" {
+			allErrs = append(allErrs, field.Invalid(idxPath, resource, "resources which do not have REST API/s cannot be encrypted"))
+		}
+		if strings.HasSuffix(resource, ".") {
+			allErrs = append(allErrs, field.Invalid(idxPath, resource, "resource should not end with '.'"))
+		}
```
Comment (shafeeqes) [inline pkg/apis/core/validation/shoot.go:1139]: Can we drop this function now?
https://github.com/gardener/gardener/blob/8f12dd778f7e0e4b051f57f647dd25f2dfe485cc/pkg/component/shared/apiserver.go#L353-L364

File: pkg/apis/core/validation/shoot_test.go [hunk 30]
```diff
@@ -4952,12 +5035,33 @@ var _ = Describe("Shoot Validation Tests", func() {
...
+						},
+						EncryptedResources: []string{"configmaps"},
+					}),
+				Entry("when shoot spec encrypted resources and status encrypted resources are equal", true,
+					[]string{"configmaps"}, core.ShootStatus{
+						LastOperation: &core.LastOperation{
+							Type: core.LastOperationTypeReconcile,
+						},
+						EncryptedResources: []string{"configmaps."},
+					}),
```
Comment (shafeeqes) [inline pkg/apis/core/validation/shoot_test.go:5064]: This test case is not possible now, right?

File: pkg/component/shared/apiserver_test.go [hunk 31]
```diff
@@ -20,13 +21,38 @@ var _ = Describe("APIServer", func() {
...
+			Expect(StringifyGroupResources(nil)).To(BeNil())
+		})
+
+		It("should return the correct list of resources when resources are not nil", func() {
+			resources := []schema.GroupResource{
+				{Resource: "deployments", Group: "apps"},
+				{Resource: "fancyresource", Group: "customoperator.io"},
+				{Resource: "configmaps", Group: ""},
+				{Resource: "services", Group: ""},
+				{Resource: "daemonsets", Group: "apps."},
```
Comment (shafeeqes) [inline pkg/component/shared/apiserver_test.go:48]: Is this case possible now?

File: pkg/component/shared/apiserver_test.go [hunk 32]
```diff
@@ -38,7 +64,7 @@ var _ = Describe("APIServer", func() {
 		})
 
 		It("should return the correct list of resources when encryptionConfig is not nil", func() {
-			resources := []string{"deployments.apps", "fancyresource.customoperator.io", "endpoints.", "configmaps", "services."}
+			resources := []string{"deployments.apps.", "fancyresource.customoperator.io", "endpoints.", "configmaps", "services."}
```
Comment (shafeeqes) [inline pkg/component/shared/apiserver_test.go:67]: Is this case possible now?

**Review by shafeeqes — CHANGES_REQUESTED** [review]

File: pkg/apis/core/validation/shoot.go (hunk 29 above)
Comment (AleksandarSavchev) [reply pkg/apis/core/validation/shoot.go:1139]: We would need this function for backwards compatibility. Since currently resources can be written with the suffix '.', they are also written with it in the status field. Removing this function could lead to the gardenlet not being able to resolve resourecs like `pods.` to `pods`. [ref](https://github.com/gardener/gardener/pull/12355#discussion_r2158912772)

The unit tests below are left to verify this functionality.

**Review by shafeeqes — APPROVED** [review]
Thank you!
/lgtm

File: pkg/apis/core/validation/shoot.go (hunk 29 above)
Comment (shafeeqes) [reply pkg/apis/core/validation/shoot.go:1139]: Do you think we should add a TODO to clean this up later?
/hold
