### PR TITLE
[Fix] Allow Uppercase region names

### LINKED ISSUE #12232: Provider Region has to be all lowercase
**How to categorize this issue?**

/area controlplane
/kind bug

**What happened**:

When creating the seed cluster an instio-ingressgateway will be deployed for all defined zones. Unfortunately in our wisdom we created our OpenStack Zones with a mix out of upper and lowercase characters. Since the name of the Namespace will be generated from the zone, the deployment task will fail. 

**What you expected to happen**:

I'd expect the zone name to converted to lowercase characters.

**How to reproduce it (as minimally and precisely as possible)**:

Setup devstack and set your zone name to sth like RegionOne.

**Anything else we need to know?**:

I patched the `GetIstioNamespaceForZone` function and it seems to work. I just do not know what consequences that might have.

```diff
diff --git a/pkg/component/shared/istio.go b/pkg/component/shared/istio.go
index 9306ab2e97..21117562b2 100644
--- a/pkg/component/shared/istio.go
+++ b/pkg/component/shared/istio.go
@@ -206,7 +206,7 @@ func AddIstioIngressGateway(
 // In case the zone name is too long the first five characters of the hash of the zone are used as zone identifiers.
 func GetIstioNamespaceForZone(defaultNamespace string, zone string) string {
        const format = "%s--%s"
-       if ns := fmt.Sprintf(format, defaultNamespace, zone); len(ns) <= validation.DNS1035LabelMaxLength {
+       if ns := fmt.Sprintf(format, defaultNamespace, strings.ToLower(zone)); len(ns) <= validation.DNS1035LabelMaxLength {
                return ns
        }
        // Use the first five characters of the hash of the zone
```

**Environment**:

- Gardener version: v1.119.0
- Kubernetes version (use `kubectl version`): v1.32.5
- Cloud provider or hardware configuration: provider-openstack
- Others:

### PR DESCRIPTION
**Pull request by modzilla99**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:

On Cloud regions with uppercase characters the creation of the istio ingress will fail.

**Which issue(s) this PR fixes**:
Fixes #12232

**Release note**:

```bugfix operator
Fix istio creation on cloud regions with uppercase characters
```

### CODE REVIEW

**Comment by tobschli** [comment]
Hi @modzilla99 👋
Thank you for your PR :)

/invite @rfranzke 
/ok-to-test

File: pkg/component/shared/istio.go [hunk 1]
```diff
@@ -211,7 +211,7 @@ func AddIstioIngressGateway(
 // In case the zone name is too long the first five characters of the hash of the zone are used as zone identifiers.
 func GetIstioNamespaceForZone(defaultNamespace string, zone string) string {
 	const format = "%s--%s"
-	if ns := fmt.Sprintf(format, defaultNamespace, zone); len(ns) <= validation.DNS1035LabelMaxLength {
+	if ns := fmt.Sprintf(format, defaultNamespace, strings.ToLower(zone)); len(ns) <= validation.DNS1035LabelMaxLength {
```
Comment (ScheererJ) [inline pkg/component/shared/istio.go]: While the fix may work in an environment where always upper case is used this can break in case somebody is as clever as naming the zones with just different casing, e.g. "a" vs. "A".

How about handling any upper case characters like the length overflow case, i.e. use the hash logic below in case any character in the zone name is upper case.

```suggestion
	if ns := fmt.Sprintf(format, defaultNamespace, zone); len(ns) <= validation.DNS1035LabelMaxLength && zone == strings.ToLower(zone) {
```

**Review by ScheererJ — CHANGES_REQUESTED** [review]
Thanks for the contribution to solve your interesting edge case.

**Review by tobschli — COMMENTED** [review]
/lgtm

**Review by ScheererJ — APPROVED** [review]
Thanks a lot for adapting the fix.

/lgtm
/approve
