### PR TITLE
Fix updates to CA annotation on `MachineDeployment` upon change in worker specific options

### LINKED ISSUE #12547: Cluster Autoscaler annotations on `MachineDeployment` are not updated in accordance with `Worker` specific CA settings
**How to categorize this issue?**

/area auto-scaling
/kind bug

**What happened**:
A user removed `WorkerPool` specific `clusterAutoscaler` settings, one of the fields being set earlier was `scaleDownUtilizationThreshold` to `0.1`. Upon removal, the expectation was for the `scaleDownUtilizationThreshold` to fallback to the default value of `0.5` and thus remove nodes which are under-utilized. 

However upon checking the logs, nodes having less than 50% resources were not scaled down by CA, moreover the logs mentioned that those nodes were above the scale-down utilization threshold. Furthermore, the `machineDeployment` had annotation that still referred to the old `scaleDownUtilizationThreshold` value of `0.1`.

**What you expected to happen**:
Upon removal of the worker pool specific CA settings, nodes having less than 50% utilization should be scaled down.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a shoot having a worker pool with `scaleDownUtilizationThreshold` set to a value other than 0.5.
2. Check the `machineDeployment` for the same worker pool, it should have an annotation specifying the threshold.
3. Remove the pool specific CA setting from the shoot manifest, wait for the shoot reconciliation to be over.
4. Check the `machineDeployment`, the old annotation should still be present.

**Anything else we need to know?**:
When the annotations are set to the the machine deployment [in generateMachineConfig](https://github.com/gardener/gardener-extension-provider-azure/blob/b584c6e59c36b86ecda14d651a6e0d93876d381d/pkg/controller/worker/machines.go#L324), in case the worker specific CA settings are removed, the annotations map that is returned from [GetMachineDeploymentClusterAutoscalerAnnotations](https://github.com/gardener/gardener/blob/4c918d177b41d0d56f314de2485b51743bfb6511/pkg/apis/extensions/v1alpha1/helper/worker.go#L25) is a `nil` map.
When the `MachineDeployment` annotations are being updated [in deployMachineDeployments](https://github.com/gardener/gardener/blob/4c918d177b41d0d56f314de2485b51743bfb6511/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go#L247), since `deployment.ClusterAutoscalerAnnotations` are `nil` the annotations never got updated.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by takoverflow**
**How to categorize this PR?**

/area auto-scaling
/kind bug

**What this PR does / why we need it**:
This PR allows for removal/updates of `cluster-autoscaler` annotations on `MachineDeployment` in accordance with the changes to worker pool cluster-autoscaler options.

Presently when the worker specific CA options are removed, the annotations corresponding to them persist on the MachineDeployment.

By initializing the annotations with a default `""` (empty) value and explicit declaration of the worker pool specific options, when updating the deployment annotations a check is performed and the CA annotations for options that are no longer set are removed. 

**Which issue(s) this PR fixes**:
Fixes #12547 

**Special notes for your reviewer**:
/cc @aaronfern 

**Release note**:

```bugfix operator
Fix cluster-autoscaler specific annotations on machine deployment upon update in worker specific cluster autoscaler options.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Can you please improve the PR description?

**Comment by takoverflow** [comment]
Hi @rfranzke, I've updated the description, hope it clarifies the intent and makes it more readable, PTAL.

File: pkg/apis/extensions/v1alpha1/helper/worker_test.go [hunk 1]
```diff
@@ -34,12 +34,26 @@ var _ = Describe("Helper", func() {
...
-		It("should return nil when options passed is nil", func() {
-			Expect(GetMachineDeploymentClusterAutoscalerAnnotations(nil)).To(BeNil())
+		It("should return annotations with value \"\" when options passed is nil", func() {
+			expectedValues := map[string]string{
+				extensionsv1alpha1.ScaleDownUtilizationThresholdAnnotation:    "",
+				extensionsv1alpha1.ScaleDownGpuUtilizationThresholdAnnotation: "",
+				extensionsv1alpha1.ScaleDownUnneededTimeAnnotation:            "",
+				extensionsv1alpha1.ScaleDownUnreadyTimeAnnotation:             "",
+				extensionsv1alpha1.MaxNodeProvisionTimeAnnotation:             "",
+			}
```
Comment (aaronfern) [inline pkg/apis/extensions/v1alpha1/helper/worker_test.go:44]: You can move this to a BeforeEach block, and for each test update only the values needed

Comment (takoverflow) [reply pkg/apis/extensions/v1alpha1/helper/worker_test.go:44]: Hi @aaronfern, thanks for the review. The reason why I was explicitly defining the expected values for each test was to enhance the readability, so that its clear which values are non-default.

File: pkg/apis/extensions/v1alpha1/helper/worker.go [hunk 2]
```diff
@@ -21,9 +21,20 @@ func ClusterAutoscalerRequired(pools []extensionsv1alpha1.WorkerPool) bool {
...
 // GetMachineDeploymentClusterAutoscalerAnnotations returns a map of annotations with values intended to be used as cluster-autoscaler options for the worker group
 func GetMachineDeploymentClusterAutoscalerAnnotations(caOptions *extensionsv1alpha1.ClusterAutoscalerOptions) map[string]string {
-	var annotations map[string]string
+	annotations := make(map[string]string)
+	caAnnotationsKeys := []string{
+		extensionsv1alpha1.ScaleDownUtilizationThresholdAnnotation,
+		extensionsv1alpha1.ScaleDownGpuUtilizationThresholdAnnotation,
+		extensionsv1alpha1.ScaleDownUnneededTimeAnnotation,
+		extensionsv1alpha1.ScaleDownUnreadyTimeAnnotation,
+		extensionsv1alpha1.MaxNodeProvisionTimeAnnotation,
```
Comment (acumino) [inline pkg/apis/extensions/v1alpha1/helper/worker.go]: You can set the values to an empty string here itself instead of using a new loop.
```suggestion
	caAnnotationsKeys := []string{
		extensionsv1alpha1.ScaleDownUtilizationThresholdAnnotation: "",
		extensionsv1alpha1.ScaleDownGpuUtilizationThresholdAnnotation: "",
		extensionsv1alpha1.ScaleDownUnneededTimeAnnotation: "",
		extensionsv1alpha1.ScaleDownUnreadyTimeAnnotation: "",
		extensionsv1alpha1.MaxNodeProvisionTimeAnnotation: "",
```

File: extensions/pkg/controller/worker/genericactuator/actuator_reconcile_test.go [hunk 3]
```diff
@@ -16,12 +17,146 @@ import (
...
+						"autoscaler.gardener.cloud/scale-down-gpu-utilization-threshold": "",
+						"autoscaler.gardener.cloud/scale-down-unneeded-time":             "10m",
+						"autoscaler.gardener.cloud/scale-down-unready-time":              "",
+						"autoscaler.gardener.cloud/max-node-provision-time":              "",
+					},
+				},
+			}
+
+			Expect(seedClient.Create(ctx, testDeployment)).To(Succeed())
+			dep := extensionsworkercontroller.MachineDeployment{
```
Comment (acumino) [inline extensions/pkg/controller/worker/genericactuator/actuator_reconcile_test.go]: better name instead of dep
```suggestion
			}
			Expect(seedClient.Create(ctx, testDeployment)).To(Succeed())
			
			betterName := extensionsworkercontroller.MachineDeployment{
```

**Review by acumino — CHANGES_REQUESTED** [review]

**Review by acumino — COMMENTED** [review]
/lgtm
