### PR TITLE
Do not allow Shoot lifetime to be extended more than time.Now() + .spec.clusterLifetimeDays

### LINKED ISSUE #1837: shoot.garden.sapcloud.io/expirationTimestamp can be extended to infinity
**What happened**:
According to #81, lifetime of a Shoot can be extended only up to `.spec.clusterLifetimeDays` from the current date,  but never more.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create `Quota`
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Quota
metadata:
  name: my-quota
  namespace: garden-dev
spec:
  clusterLifetimeDays: 7
  metrics:
    cpu: "200"
    gpu: "20"
    loadbalancer: "100"
    memory: 4000Gi
    storage.premium: 2000Gi
    storage.standard: 8000Gi
  scope:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Project
```

2. Create `SecretBinding`
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  labels:
    cloudprofile.garden.sapcloud.io/name: gcp
  name: my-secretbinding
  namespace: garden-dev
quotas:
- name: my-quota
  namespace: garden-dev
secretRef:
  name: my-secret
  namespace: garden-dev
```

3. Create `Shoot` with that `SecretBinding` and ensure that the Shoot gets the annotation `shoot.garden.sapcloud.io/expirationTimestamp="2020-01-29T16:30:57+02:00"`

4. Run `./to-infinity.sh`

```sh
#/bin/bash +e

[[ -z "$1" ]] && echo "no namespace passed" && exit 1
[[ -z "$2" ]] && echo "no shoot name passed" && exit 1

while :
do
  oldExpirationTimestamp=$(kubectl get shoot -n $1 $2 -o jsonpath='{.metadata.annotations.shoot\.garden\.sapcloud\.io/expirationTimestamp}')
  newExpirationTimestamp=$(date --rfc-3339=seconds -d "$oldExpirationTimestamp + 6 day" | sed 's/ /T/')

  kubectl annotate shoot -n $1 $2 shoot.garden.sapcloud.io/expirationTimestamp="$newExpirationTimestamp" --overwrite > /dev/null
  echo "Set the expiration timestamp to $newExpirationTimestamp"

  sleep 1
done
```

```
./to-infinity.sh garden-dev crazy-botany
Set the expiration timestamp to 2020-02-04T16:30:57+02:00
Set the expiration timestamp to 2020-02-10T16:30:57+02:00
Set the expiration timestamp to 2020-02-16T16:30:57+02:00
Set the expiration timestamp to 2020-02-22T16:30:57+02:00
Set the expiration timestamp to 2020-02-28T16:30:57+02:00
Set the expiration timestamp to 2020-03-05T16:30:57+02:00
Set the expiration timestamp to 2020-03-11T16:30:57+02:00
Set the expiration timestamp to 2020-03-17T16:30:57+02:00
Set the expiration timestamp to 2020-03-23T16:30:57+02:00
Set the expiration timestamp to 2020-03-29T17:30:57+03:00
Set the expiration timestamp to 2020-04-04T17:30:57+03:00
Set the expiration timestamp to 2020-04-10T17:30:57+03:00
Set the expiration timestamp to 2020-04-16T17:30:57+03:00
Set the expiration timestamp to 2020-04-22T17:30:57+03:00
Set the expiration timestamp to 2020-04-28T17:30:57+03:00
Set the expiration timestamp to 2020-05-04T17:30:57+03:00
Set the expiration timestamp to 2020-05-10T17:30:57+03:00
Set the expiration timestamp to 2020-05-16T17:30:57+03:00
Set the expiration timestamp to 2020-05-22T17:30:57+03:00
Set the expiration timestamp to 2020-05-28T17:30:57+03:00
Set the expiration timestamp to 2020-06-03T17:30:57+03:00
Set the expiration timestamp to 2020-06-09T17:30:57+03:00
```

And ensure that the expirationTimestamp is delayed in the future not respecting the `Quota` `.spec.clusterLifetimeDays=7`

**Environment**:

- Gardener version: v0.35.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
Do not allow Shoot lifetime to be extended more than `time.Now()` + `.spec.clusterLifetimeDays`.

**Which issue(s) this PR fixes**:
Fixes #1837

**Special notes for your reviewer**:

**Release note**:

```improvement operator
An issue allowing Shoot lifetime (`shoot.garden.sapcloud.io/expirationTimestamp`) to be extended to infinity is now fixed. Now Shoot lifetime can be extended only up to `.spec.clusterLifetimeDays` from the current date, but never more.
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]

**Comment by ialidzhikov** [comment]
Nit - force-pushed to remove the wrongly introduced `vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/zz_generated.conversion.go` with #1802.

File: plugin/pkg/shoot/quotavalidator/admission.go [hunk 1]
```diff
@@ -238,20 +240,9 @@ func (q *QuotaValidator) Validate(ctx context.Context, a admission.Attributes, o
...
-			// Therefore we have to calculate the lifetime based on the maxShootLifetime.
-			oldLifetime = oldShoot.CreationTimestamp.Time.Add(time.Duration(*maxShootLifetime*24) * time.Hour).Format(time.RFC3339)
-		}
-		oldExpirationTime, err = time.Parse(time.RFC3339, oldLifetime)
-		if err != nil {
-			return apierrors.NewInternalError(err)
-		}
-
-		maxPossibleExpirationTime = oldExpirationTime.Add(time.Duration(*maxShootLifetime*24) * time.Hour)
+		maxPossibleExpirationTime = q.time.Now().Add(time.Duration(*maxShootLifetime*24) * time.Hour)
```
Comment (timebertt) [inline plugin/pkg/shoot/quotavalidator/admission.go:243]: I am not sure, but isn't it possible with this logic to come back for example after one day and prolong the Shoot's lifetime by another day?
Shouldn't we use `shoot.CreationTimestamp` instead of `time.Now()`?

Comment (rfranzke) [reply plugin/pkg/shoot/quotavalidator/admission.go:243]: AFAIK this is desired behaviour. We don't want to forbid extending the lifetime. We wanted to always allow it based on the configured `Quota`'s `clusterLifeTimeDays` field. The only thing we wanted to ensure is that it must be user-initiated. Hence, if an end-user requires his trial cluster to live longer he can extend it.
Yes, you can come back after a day, but then you have to do it explicitly. We never had a setting that says something like "extending the life time is only allowed three days before it expires". Consequently, I think what @ialidzhikov implemented is correct.

Comment (rfranzke) [reply plugin/pkg/shoot/quotavalidator/admission.go:243]: cc @dkistner as initial contributor of this feature

Comment (timebertt) [reply plugin/pkg/shoot/quotavalidator/admission.go:243]: Alright, then i guess it's perfectly fine :)

Comment (rfranzke) [reply plugin/pkg/shoot/quotavalidator/admission.go:243]: @ialidzhikov any feedback on this?

**Review by rfranzke — APPROVED** [review]

File: plugin/pkg/shoot/quotavalidator/admission.go (hunk 1 above)
Comment (ialidzhikov) [reply plugin/pkg/shoot/quotavalidator/admission.go:243]: > Shouldn't we use shoot.CreationTimestamp instead of time.Now()?

I think the desired and described behaviour in #81 is to allow lifetime to be extended (on user demand and action) only up to `.spec.clusterLifeTimeDays` from the current date. If we use  `metadata.creationTimestamp`, how we would allow lifetime to be extended?

The issue I am trying to fix with this PR is to allow only lifetime updates up to `time.Now() + .spec.clusterLifetimeDays`, but never more. See #1837 for a hack how you can currently extend your shoot lifetime to infinity.

/cc @dkistner for feedback

Comment (timebertt) [reply plugin/pkg/shoot/quotavalidator/admission.go:243]: Thanks for clarifying! 👍

Comment (dkistner) [reply plugin/pkg/shoot/quotavalidator/admission.go:243]: Yes the intention was to allow extending the cluster lifetime from now + max the amount of days configured in `.spec.clusterLifeTimeDays`. Extending to infinity was not intended. Nice catch and thanks for fixing it.

**Review by dkistner — APPROVED** [review]

**Comment by ialidzhikov** [comment]
/kind/bug
