### PR TITLE
Fix termination of `sshd` processes when `SSHAccess` is disabled

### LINKED ISSUE #10108: Unexpected termination of sshd running in pods when shoot disables SSH access
**How to categorize this issue?**

/area security
/kind bug

**What happened**:
A user reported that ssh server running as pod in a shoot cluster is continuously receiving SIGTERM signals.

**What you expected to happen**:
User maintained ssh processes should not receive a SIGTERM.

**How to reproduce it (as minimally and precisely as possible)**:
This is caused by [this line](https://github.com/gardener/gardener/blob/720e534ee0ece2bd5fc5aa16d38559887daf2946/pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/templates/scripts/disable-sshd.tpl.sh#L16) which is executed when ssh access is disabled in the [workers settings](https://gardener.cloud/docs/gardener/shoot_workers_settings/#example-usage-in-a-shoot) in a shoot spec.

cc @AleksandarSavchev

### PR DESCRIPTION
**Pull request by AleksandarSavchev**
**How to categorize this PR?**

/area security
/kind bug

**What this PR does / why we need it**:
This PR fixes a bug which was causing the termination of cluster pod `sshd` processes when `SSHAccess` is disabled. The command used to kill existing `sshd` connections `pkill -x sshd` kills `sshd` processes regardless of whether they are from the host or container.

To fix this issue we add the `-P 1` flag to `pkill` which causes the termination of only processes with parent `pid` = `1`. The container processes cannot have such `ppid` and the ones on the host would have inherited `ppid=1` when the `sshd` service was stopped https://github.com/gardener/gardener/blob/720e534ee0ece2bd5fc5aa16d38559887daf2946/pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/templates/scripts/disable-sshd.tpl.sh#L9-L12
Selecting by `ppid` would also catch orphaned connections that have persisted through service restart. 

This PR also improves the disablement of the `sshd.service` by also masking it after disabling it. Masking the service disallows other processes of activating the service.

**Which issue(s) this PR fixes**:
Fixes #10108
/cc @dimityrmirchev 

**Special notes for your reviewer**:

**Release note**:

```bugfix user
A bug causing `sshd` running in cluster pods to receive a SIGTERM when `SSHAccess` for worker nodes is disabled is now fixed.
```

### CODE REVIEW

**Comment by AleksandarSavchev** [comment]
/hold
Will add `systemctl mask sshd` to `disable-ssh` script as additional fail safe

File: pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/component_test.go [hunk 1]
```diff
@@ -124,18 +125,14 @@ fi
 	disableScript = `#!/bin/bash -eu
 set -e
 
-# Disable sshd service if enabled
-if systemctl is-enabled --quiet sshd.service ; then
-    systemctl disable sshd.service
+# Disable and mask sshd service if not masked
+if [ "$(systemctl is-enabled sshd.service)" != "masked" ] ; then
+    systemctl disable sshd.service || true
```
Comment (dnaeon) [inline pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/component_test.go:130]: Masking the service should be enough, so no need to call `systemctl disable ...` here.

Comment (AleksandarSavchev) [reply pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/component_test.go:130]: I agree. However the disablement of `sshd` was made with the following DISA K8s STIGs rules in mind: [242393](https://www.stigviewer.com/stig/kubernetes/2023-08-29/finding/V-242393), [242394](https://www.stigviewer.com/stig/kubernetes/2023-08-29/finding/V-242394). In 242394 it is specified to disable the `sshd` unit.

I also find it a nice touch to know that even if the unit gets unmasked it would still be disabled.

File: pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/templates/scripts/disable-sshd.tpl.sh [hunk 2]
```diff
@@ -1,16 +1,12 @@
...
-if systemctl is-active --quiet sshd.service ; then
-    systemctl stop sshd.service
-fi
-
-# Disabling the sshd service does not terminate already established connections
-# Kill all currently established ssh connections
-pkill -x sshd || true
+# Stopping the sshd service does not terminate already established connections
+# Kill all currently established orphaned ssh connections on the host
+pkill -P 1 -x sshd || true
```
Comment (ScheererJ) [inline pkg/component/extensions/operatingsystemconfig/original/components/sshdensurer/templates/scripts/disable-sshd.tpl.sh]: From my point of view the comment `Stopping the sshd service does not terminate...` should be reworked. In the script it is no longer obvious that sshd service is actually being stopped. You need implicit knowledge that the `--now` option of `systemctl mask` will stop a service. May that is also worth a comment.

**Review by ScheererJ — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
/approve
