### PR TITLE
Forbid hibernating shoots with problematic webhooks

### LINKED ISSUE #1575: Forbid hibernating shoots with problematic webhooks
We should prevent `Shoot`s from getting hibernated in case they have `ValidatingWebhookConfiguration`s or `MutatingWebhookConfiguration`s with rules for `CREATE` `pods` or `nodes` and `failurePolicy=Fail`.

Otherwise, we can never wake up this shoot cluster again as new nodes cannot get created, or our system component pods cannot get created (because the validating webhook pod is not yet running).

### PR DESCRIPTION
**Pull request by timebertt**
**What this PR does / why we need it**:
With this PR Gardener forbids to hibernate Shoot clusters with problematic Webhooks (defined by the user, see #1575).
Therefore the Shoot care controller now checks all the Webhooks in the Shoot cluster and writes the Condition to the newly introduced `Shoot.status.constraints[]` array (type `[]Condition`).
The `gardener-apiserver` looks into the `constraints` section and forbids hibernation accordingly.

**Which issue(s) this PR fixes**:
Fixes #1575

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Gardener now forbids hibernating Shoots with problematic Webhooks that might prevent the Shoot from being woken up again. Problematic Webhooks are `MutatingWebhookConfigurations` and `ValidatingWebhookConfigurations` with `failurePolicy=Fail|nil` and rules for `CREATE|UPDATE|* for pods|nodes`.
```

### CODE REVIEW

File: plugin/pkg/shoot/validator/admission.go [hunk 1]
```diff
@@ -310,6 +310,19 @@ func (v *ValidateShoot) Admit(a admission.Attributes, o admission.ObjectInterfac
 		}
 	}
 
+	// Prevent Shoots from getting hibernated in case they have problematic webhooks.
+	// Otherwise, we can never wake up this shoot cluster again.
+	oldHibernated := oldShoot.Spec.Hibernation != nil && oldShoot.Spec.Hibernation.Enabled != nil && *oldShoot.Spec.Hibernation.Enabled == true
```
Comment (rfranzke) [inline plugin/pkg/shoot/validator/admission.go]:
```suggestion
	oldIsHibernated := oldShoot.Spec.Hibernation != nil && oldShoot.Spec.Hibernation.Enabled != nil && *oldShoot.Spec.Hibernation.Enabled
```

File: plugin/pkg/shoot/validator/admission.go [hunk 2]
```diff
@@ -310,6 +310,19 @@ func (v *ValidateShoot) Admit(a admission.Attributes, o admission.ObjectInterfac
...
+	newHibernated := shoot.Spec.Hibernation != nil && shoot.Spec.Hibernation.Enabled != nil && *shoot.Spec.Hibernation.Enabled == true
```
Comment (rfranzke) [inline plugin/pkg/shoot/validator/admission.go]:
```suggestion
	newIsHibernated := shoot.Spec.Hibernation != nil && shoot.Spec.Hibernation.Enabled != nil && *shoot.Spec.Hibernation.Enabled
```

File: plugin/pkg/shoot/validator/admission.go [hunk 3]
```diff
@@ -310,6 +310,19 @@ func (v *ValidateShoot) Admit(a admission.Attributes, o admission.ObjectInterfac
...
+
+	if !oldHibernated && newHibernated {
+		if hibernationConstraint := helper.GetCondition(shoot.Status.Constraints, garden.ShootHibernationPossible); hibernationConstraint != nil {
+			if hibernationConstraint.Status == garden.ConditionFalse {
```
Comment (rfranzke) [inline plugin/pkg/shoot/validator/admission.go]:
```suggestion
			if hibernationConstraint.Status != garden.ConditionTrue {
```

File: plugin/pkg/shoot/validator/admission.go [hunk 4]
```diff
@@ -310,6 +310,19 @@ func (v *ValidateShoot) Admit(a admission.Attributes, o admission.ObjectInterfac
...
+				return admission.NewForbidden(a, fmt.Errorf(hibernationConstraint.Message))
+			}
+		}
+	}
```
Comment (rfranzke) [inline plugin/pkg/shoot/validator/admission.go:325]: Can we have a test for this part of the admission plugin?

File: pkg/operation/botanist/constraints_check.go [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+
+// CheckHibernationPossible checks the Shoot for problematic webhooks which could prevent wakeup after hibernation
+func (b *Botanist) CheckHibernationPossible(ctx context.Context, constraint gardencorev1alpha1.Condition, checker *ConstraintsChecker) (*gardencorev1alpha1.Condition, error) {
+	validatingWebhookConfigs := &admissionregistrationv1beta1.ValidatingWebhookConfigurationList{}
+	if err := b.K8sShootClient.Client().List(ctx, validatingWebhookConfigs); err != nil {
+		return nil, fmt.Errorf("could not get ValidatingWebhookConfigurations of Shoot cluster to check if Shoot can be hibernated")
+	}
+
+	for _, webhookConfig := range validatingWebhookConfigs.Items {
+		if exitConstraint := checker.CheckWebhooks(constraint, "ValidatingWebhookConfiguration", webhookConfig.Name, webhookConfig.Webhooks); exitConstraint != nil {
```
Comment (rfranzke) [inline pkg/operation/botanist/constraints_check.go]:
```suggestion
		if exitConstraint := checker.checkValidatingWebhookConfig(constraint, webhookConfig); exitConstraint != nil {
```

Comment (rfranzke) [reply pkg/operation/botanist/constraints_check.go]: Though, I don't get the benefit of these functions. They are not helping too much. Should we get rid of them and keep calling `checker.CheckWebhooks` directly?

File: pkg/operation/botanist/constraints_check.go [hunk 6]
```diff
@@ -0,0 +1,146 @@
...
+		if webhook.FailurePolicy != nil && *webhook.FailurePolicy != admissionregistrationv1beta1.Fail {
+			// in admissionregistration.k8s.io/v1 FailurePolicy is defaulted to `Fail`
+			// see https://github.com/kubernetes/api/blob/release-1.16/admissionregistration/v1/types.go#L195
+			// and https://github.com/kubernetes/api/blob/release-1.16/admissionregistration/v1/types.go#L324
+			// therefore, don't ignore FailurePolicy==nil
+			continue
+		}
+
+		if webhook.ClientConfig.URL != nil && len(*webhook.ClientConfig.URL) > 0 {
+			// Webhooks with external URL (out-of-cluster) are not problematic
```
Comment (rfranzke) [inline pkg/operation/botanist/constraints_check.go]: I don't know, this check is too inaccurate. I can have webhook with a url pointing to `https://my-svc.my-ns` which is still running in my cluster. Can we either improve it or get rid of it?

File: pkg/operation/botanist/constraints_check.go [hunk 7]
```diff
@@ -0,0 +1,146 @@
...
+			continue
+		}
+
+		for _, rule := range webhook.Rules {
+			apiGroups := sets.NewString(rule.APIGroups...)
+			resources := sets.NewString(rule.Resources...)
+
+			if apiGroups.Has(corev1.GroupName) && resources.HasAny("pods", "nodes") {
+				for _, op := range rule.Operations {
+					if op == admissionregistrationv1beta1.Create || op == admissionregistrationv1beta1.OperationAll {
```
Comment (rfranzke) [inline pkg/operation/botanist/constraints_check.go]: We should also consider the `UPDATE` verb. If a `Node` can be created but not updated then the kubelet can never mark it as ready, i.e., no pods can be scheduled (unless inside host network).

**Review by rfranzke — CHANGES_REQUESTED** [review]

**Comment by rfranzke** [comment]
In the release note, can you elaborate more on how the decision is taken?

File: plugin/pkg/shoot/validator/admission.go (hunk 4 above)
Comment (timebertt) [reply plugin/pkg/shoot/validator/admission.go:325]: Sure 👍

File: pkg/operation/botanist/constraints_check.go (hunk 5 above)
Comment (timebertt) [reply pkg/operation/botanist/constraints_check.go]: Of course, leftovers... 🙈
Removed the `checkValidatingWebhookConfig` and `checkMutatingWebhookConfig` functions.

File: pkg/operation/botanist/constraints_check.go (hunk 6 above)
Comment (timebertt) [reply pkg/operation/botanist/constraints_check.go]: Yes, this is a very rudimentary check (just as discussed in #1575) and relies on the user acting according to the [Kubernetes API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#webhookclientconfig-v1-admissionregistration-k8s-io):
> url: [...] The `host` should not refer to a service running in the cluster; use the `service` field instead.

One way to do a more accurate check would probably be to explicitly test if the host of the url can be resolved externally (like `nslookup host 8.8.8.8`). 
Though, then the question would be which DNS server to test against. So this would come with some effort.

However, external webhooks with `failurePolicy=Fail` can still cause the wakeup to fail. So I would suggest to drop this check and consider external Webhooks with `failurePolicy=Fail` to also be problematic.

WDYT?

cc @vpnachev

Comment (rfranzke) [reply pkg/operation/botanist/constraints_check.go]: +1 for dropping, makes sense.

**Comment by timebertt** [comment]
Thanks for your review. I addressed your comments and rebased onto master.
PTAL :)

File: pkg/operation/botanist/constraints_check.go [hunk 8]
```diff
@@ -0,0 +1,133 @@
...
+			continue
+		}
+
+		for _, rule := range webhook.Rules {
+			apiGroups := sets.NewString(rule.APIGroups...)
+			resources := sets.NewString(rule.Resources...)
+
+			if apiGroups.Has(corev1.GroupName) && resources.HasAny("pods", "nodes") {
+				for _, op := range rule.Operations {
+					if op == admissionregistrationv1beta1.Create || op == admissionregistrationv1beta1.OperationAll || (resources.Has("nodes") && op == admissionregistrationv1beta1.Update) {
```
Comment (rfranzke) [inline pkg/operation/botanist/constraints_check.go]: Why only UPDATE for nodes? Did you test this scenario and it worked? I'm not sure if it would work, hence, I would simply include UPDATE for both pods and nodes.

Comment (timebertt) [reply pkg/operation/botanist/constraints_check.go]: Oh, sorry. There was a misunderstanding from my side. You are right, I didn't consider this case...
I changed the check to consider Operations `CREATE`, `UPDATE` and `*` on both Pods and Nodes to be problematic.
Also rebased and solved the conflicts, PTAL.

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by timebertt** [comment]
Do not merge yet! I forgot to regenerate the API docs...

**Comment by timebertt** [comment]
Regenerated the API docs, now it should be fine

**Review by rfranzke — DISMISSED** [review]

File: pkg/apis/core/v1alpha1/types_shoot.go [hunk 9]
```diff
@@ -97,6 +97,9 @@ type ShootStatus struct {
 	// Conditions represents the latest available observations of a Shoots's current state.
 	// +optional
 	Conditions []Condition `json:"conditions,omitempty"`
+	// Constraints represents conditions of a Shoots's current state that constraint some operations on it.
```
Comment (timuthy) [inline pkg/apis/core/v1alpha1/types_shoot.go]:
```suggestion
	// Constraints represents conditions of a Shoot's current state that constraint some operations on it.
```

File: pkg/apis/garden/types.go [hunk 10]
```diff
@@ -839,6 +839,9 @@ const (
 type ShootStatus struct {
 	// Conditions represents the latest available observations of a Shoots's current state.
 	Conditions []Condition
+	// Constraints represents conditions of a Shoots's current state that constraint some operations on it.
```
Comment (timuthy) [inline pkg/apis/garden/types.go]:
```suggestion
	// Constraints represents conditions of a Shoot's current state that constraint some operations on it.
```

File: pkg/apis/garden/v1beta1/types.go [hunk 11]
```diff
@@ -741,6 +741,9 @@ type ShootStatus struct {
 	// Conditions represents the latest available observations of a Shoots's current state.
 	// +optional
 	Conditions []gardencorev1alpha1.Condition `json:"conditions,omitempty"`
+	// Constraints represents conditions of a Shoots's current state that constraint some operations on it.
```
Comment (timuthy) [inline pkg/apis/garden/v1beta1/types.go]:
```suggestion
	// Constraints represents conditions of a Shoot's current state that constraint some operations on it.
```

File: pkg/openapi/openapi_generated.go [hunk 12]
```diff
@@ -4859,6 +4859,19 @@ func schema_pkg_apis_core_v1alpha1_ShootStatus(ref common.ReferenceCallback) com
 							},
 						},
 					},
+					"constraints": {
+						SchemaProps: spec.SchemaProps{
+							Description: "Constraints represents conditions of a Shoots's current state that constraint some operations on it.",
```
Comment (timuthy) [inline pkg/openapi/openapi_generated.go]: Please re-generate when description has been amended.

File: pkg/operation/botanist/botanist_suite_test.go [hunk 13]
```diff
@@ -731,3 +733,140 @@ var _ = Describe("health check", func() {
 			})),
 	)
 })
+
+var _ = Describe("constraints checks", func() {
```
Comment (timuthy) [inline pkg/operation/botanist/botanist_suite_test.go]: Can you move this to a separate file `constraints_check_test.go`?

File: pkg/operation/botanist/constraints_check.go [hunk 14]
```diff
@@ -0,0 +1,133 @@
...
+	gardencorev1alpha1 "github.com/gardener/gardener/pkg/apis/core/v1alpha1"
+	gardencorev1alpha1helper "github.com/gardener/gardener/pkg/apis/core/v1alpha1/helper"
+
+	admissionregistrationv1beta1 "k8s.io/api/admissionregistration/v1beta1"
+	corev1 "k8s.io/api/core/v1"
+	"k8s.io/apimachinery/pkg/util/sets"
+)
+
+// ConstraintsChecker checks operational constraints of Shoot cluster.
+type ConstraintsChecker struct{}
```
Comment (timuthy) [inline pkg/operation/botanist/constraints_check.go]: Why have you chosen to use a struct here although it doesn't hold any state inside?

In my opinion, it'd rather make sense if  `ConstrainChecker` implemented an interface, e.g.

```
type ConstraintChecker interface {
  CheckConstraint(constraint gardencorev1alpha1.Condition) gardencorev1alpha1.Condition
}
```

File: pkg/operation/botanist/constraints_check.go [hunk 15]
```diff
@@ -0,0 +1,133 @@
...
+	c := gardencorev1alpha1helper.UpdatedCondition(constraint, gardencorev1alpha1.ConditionTrue, "NoProblematicWebhooks", "Shoot can be hibernated.")
+	return &c, nil
+}
+
+// CheckWebhooks checks all webhooks in the Shoot to determine if hibernation is not possible due to problematic Webhooks.
+// Problematic webhooks are: ValidationWebhookConfigurations and MutatingWebhookConfigurations with rules
+// for CREATE pods or nodes and failurePolicy=Fail and webhooks[].clientConfig.url == nil.
+// Otherwise, we can never wake up this shoot cluster again as new nodes cannot get created,
+// or our system component pods cannot get created (because the validating webhook pod is not yet running).
+func (c *ConstraintsChecker) CheckWebhooks(constraint gardencorev1alpha1.Condition, configKind string, configName string, webhooks []admissionregistrationv1beta1.Webhook) *gardencorev1alpha1.Condition {
```
Comment (timuthy) [inline pkg/operation/botanist/constraints_check.go]: Any reason you return a pointer here?

**Review by timuthy — CHANGES_REQUESTED** [review]
Sorry for the late review. Can you please have a look at my comments?

File: pkg/operation/botanist/botanist_suite_test.go (hunk 13 above)
Comment (timebertt) [reply pkg/operation/botanist/botanist_suite_test.go]: Sure, moved to `constraints_check_test.go`

File: pkg/openapi/openapi_generated.go (hunk 12 above)
Comment (timebertt) [reply pkg/openapi/openapi_generated.go]: Done

File: pkg/operation/botanist/constraints_check.go (hunk 14 above)
Comment (timebertt) [reply pkg/operation/botanist/constraints_check.go]: As discussed, I simplified the constraints checks as follows: removed the `ConstraintsChecker` type and refactored the func `CheckWeebhook` to `IsProblematicWebhook` which now only checks a single webhook and the calling function loops over all Webbhooks in a `MutatingWebhookConfig`/`ValidatingWebhookConfig`.

**Review by timebertt — COMMENTED** [review]
I addressed your suggesstions, PTAL, should be fine now...

**Review by timuthy — APPROVED** [review]
/lgtm
