### PR TITLE
Prevent confusing error messages about outdated cloud configs on nodes during rolling updates

### LINKED ISSUE #6483: During rolling node update shoot cluster reports outdated cloud-config error
**How to categorize this issue?**

A healthy Shoot Cluster which is in the state of being rolled for example due to a K8s minor version update will show a misleading `outdated cloud-config` error.

We observed this during a K8s minor version upgrade. Clusters with large node pools can take multiple hours to complete their node rolling (`maxSurge 1`). During the process of node rolling the cluster status will show the error:

```
 "2 errors occurred:\n\t* the last successfully applied cloud config on node ".." is outdated (current: 86ce9b767813e02798f02907d5382811a57b9c3334d0c170a4ee18dc645dbf2f, desired: a3f02d7f4e646ed7fb63d3d09c9f1616181df774d605eea1a6c77ee31a2e56c7)\n\t* the last successfully applied cloud config on node "..." is outdated (current: 86ce9b767813e02798f02907d5382811a57b9c3334d0c170a4ee18dc645dbf2f, desired: a3f02d7f4e646ed7fb63d3d09c9f1616181df774d605eea1a6c77ee31a2e56c7)\n\n"
```

This is problematic as this error message can:
a. lead to debugging of DoDs who are not familiar that this is a transient error (because it can persist over hours)
b. be either transient or point to a real issue if for example there would a real problem with the downloader-script.

**Why does error occur**

- With a minor version update a new to be downloaded cloud config secret is generated in the shoot cluster. Hash for secret name is generated [here](https://github.com/gardener/gardener/blob/77e9a93627e79f0024f1f5e3a4cd07c48ba65926/pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L711)
- The old cloud config secret was no longer existing in the cluster
- The cloud-config downloader tried to download the old cloud config and failed with error message as it was not found
- The cluster showed the above error message
- This situation stayed until the node finally got rolled with the new version. Then the cloud-config downloader script contained the new cloud-config hash and it downloaded the correct secret so that this [check](https://github.com/gardener/gardener/blob/77e9a93627e79f0024f1f5e3a4cd07c48ba65926/pkg/operation/botanist/worker.go#L138) could succeed

Maybe important to note that obviously we do *not* want to apply the new cloud config on the old nodes. So this works as expected. Maybe we can mask the error better?

  /area control-plane
  /area ops-productivity
  /kind bug

**What you expected to happen**:
Have a progressing status that indicates that the node rollout is still in progress instead of an error message about the cloud config.

**How to reproduce it (as minimally and precisely as possible)**:
Should be reproducible with worker pool large enough, `maxSurge: 1` and an update to k8s minor version or cri.

- Gardener version: 1.52.2
- Kubernetes version (use `kubectl version`) :1.23.6

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area ops-productivity
/kind bug

**What this PR does / why we need it**:
When the OSC key of a worker pool changes (e.g. when the Kubernetes version is upgraded) then a rolling update of the nodes is triggered.

Earlier, existing nodes (waiting for their removal (which can take some time)) were still considered by https://github.com/gardener/gardener/blob/c44dddf1439a0cbde65c7e9a8b54708b55656129/pkg/operation/botanist/worker.go#L119-L144
Hence, this health check failed and complained that the cloud config is outdated. However, this is actually the desired behaviour since old nodes/to-be-deleted nodes are not supposed to update their cloud config.

With this change, we will consider nodes whose OSC key does not match the OSC key of their cloud config secret as 'to-be-deleted soon'. Consequently, the health check is skipped for them, preventing the misleading error messages.

**Which issue(s) this PR fixes**:
Fixes #6483

**Special notes for your reviewer**:
bcf43a76eba4944a18b3abf0e330a800c417a0ef drops backwards-compatibility/migration code - the Secret checksum label was added with https://github.com/gardener/gardener/pull/3396 in v1.16.0. With this PR the `CloudConfigUpdatedForAllWorkerPools` no longer tolerates a missing checksum label on the Secret.

**Release note**:

```bugfix operator
A bug has been fixed which caused the `EveryNodeReady` condition on `Shoot`s to become `False` and complaining about outdated cloud configs on nodes during rolling updates.
```

### CODE REVIEW

File: pkg/operation/botanist/worker.go [hunk 1]
```diff
@@ -143,23 +156,41 @@ func CloudConfigUpdatedForAllWorkerPools(workers []gardencorev1beta1.Worker, wor
...
-		if taint.Key == MCMPreferNoScheduleKey && taint.Effect == corev1.TaintEffectPreferNoSchedule {
+		if taint.Key == mcmPreferNoScheduleKey && taint.Effect == corev1.TaintEffectPreferNoSchedule {
 			return true
 		}
 	}
 
 	return false
 }
 
+func nodeOSCKeyDifferentFromSecretOSCKey(node corev1.Node, secretOSCKey string) (bool, error) {
```
Comment (ialidzhikov) [inline pkg/operation/botanist/worker.go:180]: We were wondering whether when `nodeOSCKey != secretOSCKey` we can always assume that the node is "old" one (about to be removed during the rolling update)? Can it be there a case where `nodeOSCKey != secretOSCKey` but the Node is actually not an "old" one?

**Review by ialidzhikov — COMMENTED** [review]
We had a look with @ary1992. Actually while testing this PR we tried to reproduce the original issue reported by @BeckerMax. But we failed to reproduce it. Here is why:

1. In the current HEAD the health check properly ignores all Nodes with with the MCM taint "deployment.machine.sapcloud.io/prefer-no-schedule"

https://github.com/gardener/gardener/blob/431473961181bd0719a70fb98cbfdcf6a62c1b0e/pkg/operation/botanist/worker.go#L159-L164

2. In the MCM code our reading of the code is this taint should be added to all Nodes that are about to be rolled

https://github.com/gardener/machine-controller-manager/blob/116653d8baeeb3121ce33098050e0a296a86d292/pkg/controller/deployment_rolling.go#L61-L68

So we were wondering how it is possible to reproduce the issue having in mind the above details? I guess the only way would be have an issue in MCM that prevented all Nodes to be tainted. Or do we miss anything along the way?

We also had 1 inline question. If the newly introduces check guarantees us that the Node is "old" one (about to be removed) then lgtm.

**Comment by rfranzke** [comment]
> So we were wondering how it is possible to reproduce the issue having in mind the above details? I guess the only way would be have an issue in MCM that prevented all Nodes to be tainted. Or do we miss anything along the way?

Good question, I was wondering the same. I reproduced by adding some webhook that blocks MCM from adding the taint. I don't know whether there are more cases where MCM would not add it, but it seems to have happened quite often for @BeckerMax.
Generally, for regular rolling updates it's better to rely on gardenlet's information only, i.e. we know that certain nodes will be removed eventually so we don't consider them anymore (with this PR).
Relying on MCM taint is an optimization and helpful when cluster-autoscaler scales down and plans to remove certain nodes (gardenlet cannot know about this).

File: pkg/operation/botanist/worker.go (hunk 1 above)
Comment (rfranzke) [reply pkg/operation/botanist/worker.go:180]: > Can it be there a case where nodeOSCKey != secretOSCKey but the Node is actually not an "old" one?

I don't think so, no. That's what I assumed as well and what the whole PR is built upon.

**Review by ialidzhikov — COMMENTED** [review]
As I mentioned in https://github.com/gardener/gardener/pull/6555#pullrequestreview-1082047602, the only logical explanation for https://github.com/gardener/gardener/issues/6483 would be MCM to do not add the taint (or the taint to be removed by MCM or other machinery). I tried to reproduce the root issue today again - tried different scenarios but had no success.
@himanshu-kun can you also check whether we could have a (very often according to the issue author) case where the MCM would not taint the Nodes with `deployment.machine.sapcloud.io/prefer-no-schedule`?
I see only 1 corner case:
https://github.com/gardener/machine-controller-manager/blob/116653d8baeeb3121ce33098050e0a296a86d292/pkg/controller/deployment_rolling.go#L325-L334

It is when the Machine status does not contain the Node name. But I am not sure how likely is to happen.

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Comment by rfranzke** [comment]
Thanks @ialidzhikov for your thorough review. Also cc @BeckerMax, maybe you have more information on how to reproduce the issue you reported.

Independent on all this, I still think this PR improves the current situation.

**Comment by ialidzhikov** [comment]
> Independent on all this, I still think this PR improves the current situation.

Agree, that's why I lgtm-ed.
I just investigated whether we have other issue that is actually causing the error in https://github.com/gardener/gardener/issues/6483 to appear. I suspect that this is the case, otherwise I cannot explain why I am not able to reproduce https://github.com/gardener/gardener/issues/6483.

**Comment by himanshu-kun** [comment]
> It is when the Machine status does not contain the Node name. But I am not sure how likely is to happen.

we currently when reconciling a machine obj first update the spec, and in the next reconciliation update the `status.Node` of the machine obj.
So a situation can happen where when the machine spec is updated , but the status is not because of heavy delay in the queue (which is unlikely, can only happen in huge clusters)  and in the meanwhile node joined(as VM is already created) and the rollout happened, then the node would not get the `deployment.machine.sapcloud.io/prefer-no-schedule` taint.
This is something which can be averted by removing `status.Node` field and we will work on it now seeing this kind of situation arising. The tracking issue is https://github.com/gardener/machine-controller-manager/issues/389

**Comment by BeckerMax** [comment]
Thanks for your suggestions and discussion. 
We indeed only saw this for the largest clusters and there a couple of times. On the other hand the rollout process is significantly faster for small clusters. So we could miss this error for smaller clusters. I saw it twice and our APJ shift reported it more often.

Regarding:
> So a situation can happen where when the machine spec is updated , but the status is not because of heavy delay in the queue (which is unlikely, can only happen in huge clusters) and in the meanwhile node joined(as VM is already created) and the rollout happened, then the node would not get the deployment.machine.sapcloud.io/prefer-no-schedule taint.
This is something which can be averted by removing status.Node field and we will work on it now seeing this kind of situation arising. The tracking issue is https://github.com/gardener/machine-controller-manager/issues/389

In our case the nodes were already multiple days old - so it was not a new node that had this problem.
Sorry that I can't provide more information on the taints of the node when this problem was observed. In case this happens again I will provide an update here. 

Thanks, for taking care of it @rfranzke @ialidzhikov @ary1992
