### PR TITLE
cloudprofile: Fix regression when validating machine image versions

### LINKED ISSUE #14047: "supported" lifecycle stages must not overlap per minor version
**How to categorize this issue?**

/area usability
/kind bug

**What happened**:
I've updated the cloudprofile and  run into this issue:

```
The CloudProfile "gcp" is invalid: spec.machineImages[0].versions[1]: Forbidden: unable to add version "1877.12.0-inplace" with classification "supported". "supported" lifecycle stages must not overlap per minor version
```

The config is as follows:

```
  machineImages:
  - name: gardenlinux
    updateStrategy: minor
    versions:
    - architectures:
      - amd64
      - arm64
      classification: supported
      cri:
      - containerRuntimes:
        - type: gvisor
        name: containerd
      version: 1877.12.0
    - architectures:
      - amd64
      - arm64
      cri:
      - containerRuntimes:
        - type: gvisor
        name: containerd
      inPlaceUpdates:
        minVersionForUpdate: 1877.1.0-inplace
        supported: true
      version: 1877.12.0-inplace
```

If I write `classification: deprecated` for the inplace updates, it runs through. However I want the inplace updates for the same gardenlinux version supported as well.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by RAPSNX**
**How to categorize this PR?**

/area usability
/kind regression

**What this PR does / why we need it**:

This PR addresses a change introduced in #10982 that changed how nil classifications are handled and validated, causing them to default to “supported”.

This fix restores the previous behavior when validating old classifications, to skip it when they `nil`.

**Which issue(s) this PR fixes**:
Fixes #14047 

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

File: pkg/apis/core/validation/cloudprofile_test.go [hunk 1]
```diff
@@ -1044,6 +1044,35 @@ var _ = Describe("CloudProfile Validation Tests ", func() {
 					}))))
 				})
 
+				It("allow nil classification with same semver, but different flavor", func() {
```
Comment (timuthy) [inline pkg/apis/core/validation/cloudprofile_test.go]:
```suggestion
				It("should allow nil classification with same semver, but different flavor", func() {
```

File: pkg/apis/core/validation/cloudprofile.go [hunk 2]
```diff
@@ -180,7 +180,9 @@ func validateCloudProfileKubernetesSettings(kubernetes core.KubernetesSettings,
 func validateSupportedVersionsConfiguration(version core.ExpirableVersion, allVersions []core.ExpirableVersion, fldPath *field.Path) field.ErrorList {
 	allErrs := field.ErrorList{}
 
-	if helper.VersionIsSupported(version) {
+	// NOTE: Lifecycle classifications treat nil classifications as default, which differs in old classification.
+	// Keep skipping old classifications if they nil.
```
Comment (timuthy) [inline pkg/apis/core/validation/cloudprofile.go]:
```suggestion
	// Keep skipping old classifications if they are nil.
```

**Review by timuthy — COMMENTED** [review]
Thanks for addressing the regression!

**Review by LucaBernstein — COMMENTED** [review]
/lgtm

**Review by timuthy — COMMENTED** [review]
/approve
