### PR TITLE
Fix replicas on hibernation for vpn-seed-server

### LINKED ISSUE #7187: `vpn-seed-server` is not scaled-down on hibernation
**How to categorize this issue?**

/area cost
/kind bug

**What happened**:

`vpn-seed-server` is not scaled-down on hibernation

**What you expected to happen**:

`vpn-seed-server` is scaled-down on hibernation

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a hibernated shoot
2. Observe the `vpn-seed-server` is still deployed in the shoot control plane:
```
$ k -n shoot--local--local get po
NAME                               READY   STATUS    RESTARTS   AGE
vpn-seed-server-7f6765dfd9-xjq4w   2/2     Running   0          11m
```

**Anything else we need to know?**:

Probably broken by #6978

We might want to enhance the hibernation e2e tests to assert that there are no pods running in the control plane.

**Environment**:

- Gardener version: b53d99f3edadcfa6d1fb66510debbf5777a92209
- Cloud provider or hardware configuration: provider-local

### PR DESCRIPTION
**Pull request by MartinWeindel**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
`vpn-seed-server`deployment is not scaled-down on hibernation. The bug was introduced with #6978

**Which issue(s) this PR fixes**:
Fixes #7187

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fix replicas on hibernation for `vpn-seed-server` deployment.
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
/lgtm

**Comment by rfranzke** [comment]
The PR looks good. What about the 

> We might want to enhance the hibernation e2e tests to assert that there are no pods running in the control plane.

part in https://github.com/gardener/gardener/issues/7187?

**Review by ScheererJ — APPROVED** [review]
/lgtm

File: pkg/operation/botanist/vpnseedserver.go [hunk 1]
```diff
@@ -80,7 +80,7 @@ func (b *Botanist) DefaultVPNSeedServer() (vpnseedserver.Interface, error) {
 			ServiceCIDR: b.Shoot.Networks.Services.String(),
 			NodeCIDR:    pointer.StringDeref(b.Shoot.GetInfo().Spec.Networking.Nodes, ""),
 		},
-		Replicas:                             1,
+		Replicas:                             b.Shoot.GetReplicas(1),
```
Comment (ialidzhikov) [inline pkg/operation/botanist/vpnseedserver.go:83]: Is it possible to add unit test to prevent regressing the case in the future?

Comment (MartinWeindel) [reply pkg/operation/botanist/vpnseedserver.go:83]: A unit test has been added. Additionally the e2e test for the hibernated shoot has been extended to check for running pods in the control plane in hibernated state.

File: test/e2e/gardener/shoot/create_and_delete_hibernated.go [hunk 2]
```diff
@@ -40,9 +43,17 @@ var _ = Describe("Shoot Tests", Label("Shoot", "default"), func() {
 		Expect(f.CreateShootAndWaitForCreation(ctx, false)).To(Succeed())
 		f.Verify()
 
+		verifyNoPodsRunning(f)
```
Comment (rfranzke) [inline test/e2e/gardener/shoot/create_and_delete_hibernated.go]: Can we do this in https://github.com/gardener/gardener/blob/master/test/e2e/gardener/shoot/create_hibernate_wakeup_delete.go as well, please?

Comment (MartinWeindel) [reply test/e2e/gardener/shoot/create_and_delete_hibernated.go]: done

File: test/e2e/gardener/shoot/create_and_delete_hibernated.go [hunk 3]
```diff
@@ -40,9 +43,17 @@ var _ = Describe("Shoot Tests", Label("Shoot", "default"), func() {
...
+
 		By("Delete Shoot")
 		ctx, cancel = context.WithTimeout(parentCtx, 15*time.Minute)
 		defer cancel()
 		Expect(f.DeleteShootAndWaitForDeletion(ctx, f.Shoot)).To(Succeed())
 	})
 })
+
+func verifyNoPodsRunning(f *framework.ShootCreationFramework) {
```
Comment (rfranzke) [inline test/e2e/gardener/shoot/create_and_delete_hibernated.go]: Pass the proper context

File: test/e2e/gardener/shoot/create_and_delete_hibernated.go [hunk 4]
```diff
@@ -40,9 +43,17 @@ var _ = Describe("Shoot Tests", Label("Shoot", "default"), func() {
...
+	list := &corev1.PodList{}
+	Expect(f.ShootFramework.SeedClient.Client().List(context.Background(), list, client.InNamespace(f.Shoot.Status.TechnicalID))).To(Succeed())
+	Expect(list.Items).To(BeEmpty())
```
Comment (rfranzke) [inline test/e2e/gardener/shoot/create_and_delete_hibernated.go]: You could use `kutil.ResourcesExist` instead.

**Review by rfranzke — CHANGES_REQUESTED** [review]

**Review by rfranzke — COMMENTED** [review]
Nice!

/lgtm
/approve
