### PR TITLE
Consider compatibility matrix of metrics-server

### LINKED ISSUE #6345: After #6338 metrics-server no longer works for K8s 1.17 Shoot
**How to categorize this issue?**

/area quality
/kind bug
/kind regression

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Creata a K8s 1.17 Shoot cluster

2. Make sure that the Shoot cannot get healthy with reason

```yaml
  - lastTransitionTime: "2022-07-18T11:12:52Z"
    lastUpdateTime: "2022-07-18T11:11:32Z"
    message: 'Deployment "kube-system/metrics-server" is unhealthy: condition "Available"
      has invalid status False (expected True) due to MinimumReplicasUnavailable:
      Deployment does not have minimum availability.'
    reason: DeploymentUnhealthy
    status: "False"
    type: SystemComponentsHealthy
```

```
$ k -n kube-system get po metrics-server-787667cfff-ffv9t
NAME                              READY   STATUS    RESTARTS   AGE
metrics-server-787667cfff-ffv9t   0/1     Running   0          68m
```

```
$ k -n kube-system logs metrics-server-787667cfff-ffv9t

E0718 11:16:07.835621       1 scraper.go:140] "Failed to scrape node" err="request failed, status: \"404 Not Found\"" node="foo"
I0718 11:16:08.129480       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:16:18.130340       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:16:28.130376       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:16:38.129712       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:16:48.130232       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:16:58.130498       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0718 11:17:07.835013       1 scraper.go:140] "Failed to scrape node" err="request failed, status: \"404 Not Found\"" node="foo"
I0718 11:17:08.129418       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:17:18.130340       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:17:28.130350       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:17:38.129404       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:17:48.130616       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:17:58.130150       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0718 11:18:07.839001       1 scraper.go:140] "Failed to scrape node" err="request failed, status: \"404 Not Found\"" node="foo"
I0718 11:18:08.129546       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:18:18.130397       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:18:28.130181       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:18:38.129520       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:18:48.130465       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:18:58.130211       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
E0718 11:19:07.838533       1 scraper.go:140] "Failed to scrape node" err="request failed, status: \"404 Not Found\"" node="foo"
I0718 11:19:08.129414       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
I0718 11:19:18.129980       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: 04390112e1d6f8bf4efbd404cd8e0fc704d6b603
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area quality
/kind bug
/kind regression

**What this PR does / why we need it**:
https://github.com/gardener/gardener/pull/6338 did not consider the [compatibility matrix of metrics-server](https://github.com/kubernetes-sigs/metrics-server#compatibility-matrix) which causes a regression for Kubernetes version < 1.19

This PR uses metric-server v0.5.2 for Kubernetes < v1.19 and v.0.6.1 for Kubernetes >= v1.19.
ClusterRoles are defined to support both versions of metric-server ([see breaking changes of v.0.6.0](https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.6.0))

**Which issue(s) this PR fixes**:
Fixes #6345 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/operation/botanist/component/metricsserver/metrics_server_test.go [hunk 1]
```diff
@@ -422,7 +453,64 @@ status: {}
...
+			Expect(fakeClient.Get(ctx, client.ObjectKeyFromObject(managedResourceSecret), managedResourceSecret)).To(Succeed())
+			Expect(managedResourceSecret.Type).To(Equal(corev1.SecretTypeOpaque))
+			Expect(managedResourceSecret.Data).To(HaveLen(9))
+			Expect(string(managedResourceSecret.Data["apiservice____v1beta1.metrics.k8s.io.yaml"])).To(Equal(apiServiceYAML))
+			Expect(string(managedResourceSecret.Data["clusterrole____system_metrics-server.yaml"])).To(Equal(clusterRoleYAMLPreVersionZeroSix))
+			Expect(string(managedResourceSecret.Data["clusterrolebinding____system_metrics-server.yaml"])).To(Equal(clusterRoleBindingYAML))
+			Expect(string(managedResourceSecret.Data["clusterrolebinding____metrics-server_system_auth-delegator.yaml"])).To(Equal(clusterRoleBindingAuthDelegatorYAML))
+			Expect(string(managedResourceSecret.Data["rolebinding__kube-system__metrics-server-auth-reader.yaml"])).To(Equal(roleBindingYAML))
+			Expect(string(managedResourceSecret.Data["service__kube-system__metrics-server.yaml"])).To(Equal(serviceYAML))
+			Expect(string(managedResourceSecret.Data["serviceaccount__kube-system__metrics-server.yaml"])).To(Equal(serviceAccountYAML))
```
Comment (acumino) [inline pkg/operation/botanist/component/metricsserver/metrics_server_test.go]: Why is there no VPA here? Shouldn't there be VPA deployed here similar to line 446?

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 2]
```diff
@@ -134,6 +136,21 @@ func (m *metricsServer) computeResourcesData(serverSecret, caSecret *corev1.Secr
 	}
 	utilruntime.Must(kutil.MakeUnique(secret))
 
+	// Required RBAC resources change in v0.6.0. Ref: https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.6.0
+	if m.image == nil || m.image.Tag == nil {
+		return nil, fmt.Errorf("image and image.tag must not be nil")
+	}
+	// v0.6.0 rbac resources
+	rbacResources := []string{"pods", "nodes", "nodes/metrics", "namespaces", "configmaps"}
+	preVersionZeroSix, err := version.CheckVersionMeetsConstraint(*m.image.Tag, "< v0.6.0")
```
Comment (ialidzhikov) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]: I don't think it is fine to rely on the tag. You know that we have a concept/feature about image vector overwrite - see [`./docs/deployment/image_vector.md`](https://github.com/gardener/gardener/blob/v1.51.0/docs/deployment/image_vector.md). We cannot rely that the tag will be preserved as v0.6.0 if image vector overwrite is used. I think even sometimes our CI/CD overwrites the tags with some suffixes - for example `v0.6.0` becomes `v0.6.0-mod1` (don't ask me why, I don't know). 
I would rather suggest to use the K8s version of the Shoot. For K8s < 1.19 use the old RBAC, for K8s >= 1.19 use the new one.

Comment (oliver-goetz) [reply pkg/operation/botanist/component/metricsserver/metrics_server.go]: In the recent nginx update PR, I have seen that we don't necessary create different cases for RBAC changes https://github.com/gardener/gardener/pull/6356/files#r924183792
I could do the same here and add both resources and we would have only minimal changes here. WDYT?

**Review by rfranzke — COMMENTED** [review]
/approve

**Review by ialidzhikov — COMMENTED** [review]
/lgtm
