### PR TITLE
Tolerate certain leftovers during shoot cleanup

### LINKED ISSUE #13847: Shoot Deletion Stuck/Slow, Exceeding Configured Timeouts
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**Impact** — Multiple project Shoots are affected, leading to critical deprovisioning failures for customer's infrastructure manager due to exceeding its 2-hour timeout, impacting dozens of customers.

**Symptoms** —
- Shoots remain in a "Delete Processing, Cluster marked for deletion" state for extended periods (3-4 hours), exceeding the expected ~2h10m forceful deletion threshold and customer's 2-hour timeout.
- Dashboard status shows: "Cleaning up the cluster failed as some resource are stuck in deletion. Please remove these resources properly or a forceful deletion will happen if this error persists."
```
shoot.status.lastOperation and shoot.status.lastErrors indicate:
task "Cleaning Kubernetes resources" failed: ... namespaces "dynatrace" not found
failed to clean up resources with kind PersistentVolumeClaim: ... namespaces "mission-control" not found, namespaces "family-search3" not found, namespaces "search-dse" not found
failed to clean up resources with kind Job: ... namespaces "mission-control" not found, namespaces "family-search3" not found
failed to clean up resources with kind VolumeSnapshot: ... namespaces "family-search3" not found
task "Cleaning extended API groups" failed: 1 error occurred: * retry failed with context deadline exceeded, last error: remaining objects are still present: [v1.CustomResourceDefinition /apigateways.operator.kyma-project.io v1.CustomResourceDefinition /apirules.gateway.kyma-project.io]
```
- In some cases, VMs are left orphaned in the hyperscaler account even after the Shoot resource is eventually deleted.

**Investigations / Mitigations / Solutions** —
**Investigations:**
- Analysis of shoot.status.lastErrors revealed that the Gardener cleanup process failed to remove resources (DaemonSets, PVCs, Jobs, VolumeSnapshots) because their respective namespaces (dynatrace, mission-control, family-search3, search-dse) were reported as "not found". This suggests premature deletion of namespaces or removal of finalizers.
For other cases, CustomResourceDefinitions (apirules.gateway.kyma-project.io) were found to be stuck during the "Cleaning extended API groups" task.
- Hypothesis: User actions (e.g., manual resource creation not tracked by Gardener) or automation (e.g., ArgoCD) are removing finalizers from namespaces too early, causing cleanup tasks to fail and preventing timely forceful deletion.

**Mitigations/Solutions (Manual Interventions):**
- Operators manually force-deleted several stuck shoots.
- Finalizers were manually removed from apirules CRDs for shoots to allow deletion to proceed.
- Manual cleanup of specific namespaces and orphaned VMs in the hyperscaler was performed for.

**Current Status** — The issue of prolonged and stuck Shoot deletion for customer clusters is ongoing. While manual interventions have cleared specific instances, the underlying problem of Gardener's cleanup process failing and the forceful deletion mechanism not triggering within the expected timeframe persists. Further investigation is required to understand why the "forceful finalization" is not consistently working as documented.

**What would you like to be added**:
Recreate any missing namespaces to resolve namespace errors effectively.

**Why is this needed**:
Allow the cleanup process to effectively and smoothly remove resources.

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area ops-productivity
/area usability
/kind enhancement

**What this PR does / why we need it**:
This PR enhances the shoot deletion flow to tolerate resource leftovers in the following situations:
- Objects that belong to namespaces which have already been deleted (finalized).
- Objects that were created after the cleanup process began for the first time, plus the finalize grace period.

`Gardenlet` logs the remaining but tolerated objects during shoot deletion, so operators can review them retrospectively.

**Which issue(s) this PR fixes**:
Fixes #13847

**Special notes for your reviewer**:
I consider this PR as an enhancement rather than a bug fix. Shoot deletion and resource cleanup have functioned as intended, but this update extends support to scenarios reported by users and operators (see #13847)

In particular, the situation where objects remain in deleted namespaces is exceptional and should be treated as such. Namespaces have special deletion protection, and users should not bypass this.

/cc @rfranzke

**Release note**:

```noteworthy user
The shoot deletion flow has been enhanced to tolerate leftover resources in the following situations:
- Objects that belong to namespaces which have already been deleted (finalized).
- Objects that were created after the cleanup process began for the first time, plus the finalize grace period.
```

### CODE REVIEW

File: pkg/gardenlet/operation/botanist/cleanup.go [hunk 1]
```diff
@@ -211,43 +213,123 @@ func (b *Botanist) CleanKubernetesResources(ctx context.Context) error {
 		return err
 	}
 
+	cleanupStartTime, err := b.addAndGetCleanupStartTime(ctx)
+	if err != nil {
+		return err
```
Comment (rfranzke) [inline pkg/gardenlet/operation/botanist/cleanup.go]: fmt.Errorf?

File: pkg/gardenlet/operation/botanist/cleanup.go [hunk 2]
```diff
@@ -211,43 +213,123 @@ func (b *Botanist) CleanKubernetesResources(ctx context.Context) error {
...
+// and returns the timestamp.
+func (b *Botanist) addAndGetCleanupStartTime(ctx context.Context) (*time.Time, error) {
+	namespace := &corev1.Namespace{
+		ObjectMeta: metav1.ObjectMeta{
+			Name: b.Shoot.ControlPlaneNamespace,
+		},
+	}
+	if err := b.SeedClientSet.Client().Get(ctx, client.ObjectKeyFromObject(namespace), namespace); err != nil {
+		return nil, fmt.Errorf("failed to get shoot namespace %s: %w", b.Shoot.ControlPlaneNamespace, err)
+	}
```
Comment (rfranzke) [inline pkg/gardenlet/operation/botanist/cleanup.go]: You can use `b.SeedNamespaceObject` which should be already set here

File: pkg/gardenlet/operation/botanist/cleanup.go [hunk 3]
```diff
@@ -211,43 +213,123 @@ func (b *Botanist) CleanKubernetesResources(ctx context.Context) error {
...
+
+func (b *Botanist) addAdditionalCleanOptionsForKubernetesCleanup(
+	ctx context.Context,
+	cleanOptions *utilclient.CleanOptions,
+	cleanupStartTime *time.Time,
+	defaultFinalizeAfter utilclient.FinalizeGracePeriodSeconds,
+	customFinalizeAfterAnnotation string,
+) error {
+	// Kubernetes objects in unknown namespaces should be ignored.
+	// Finalizing such objects will fail and block the cleanup process indefinitely.
```
Comment (rfranzke) [inline pkg/gardenlet/operation/botanist/cleanup.go:300]: Can you link to the issue here for future reference? This is not quite obvious

File: pkg/gardenlet/operation/botanist/cleanup.go [hunk 4]
```diff
@@ -211,43 +213,123 @@ func (b *Botanist) CleanKubernetesResources(ctx context.Context) error {
...
+		seconds, err := strconv.Atoi(v)
+		if err != nil {
+			return fmt.Errorf("could not parse finalize seconds from annotation %s: %w", customFinalizeAfterAnnotation, err)
+		}
+		finalizeSeconds = int64(seconds)
+	}
+
+	cleanOptions.IgnoreLeftovers = append(cleanOptions.IgnoreLeftovers,
+		utilclient.IgnoreObjectsCreatedAfter(cleanupStartTime.Add(time.Duration(finalizeSeconds)*time.Second)),
+	)
```
Comment (rfranzke) [inline pkg/gardenlet/operation/botanist/cleanup.go:327]: I had something simpler in mind: Instead of handling an excess of the cleanup start time here in the cleaner itself, we could simply check if the time is exceeded in the shoot delete flow. If so, we can just skip the entire function here.

File: pkg/utils/kubernetes/client/client.go [hunk 5]
```diff
@@ -282,35 +284,60 @@ func DefaultGoneEnsurer() GoneEnsurer {
...
 
-	if meta.LenList(list) > 0 {
+	objectsInList := meta.LenList(list)
+	ignoredObjects := 0
+
+	if err := meta.EachListItem(list, func(object runtime.Object) error {
+		for _, ignore := range ignoreFns {
+			// Iterate over all objects to log them.
+			if ignore(log, object.(client.Object)) {
+				ignoredObjects += 1
```
Comment (rfranzke) [inline pkg/utils/kubernetes/client/client.go:334]: Can't we return here? If an `ignoreFn` returns `true`, we don't need to call another `ignoreFn` again for the same object.

File: pkg/utils/kubernetes/client/client.go [hunk 6]
```diff
@@ -282,35 +284,60 @@ func DefaultGoneEnsurer() GoneEnsurer {
...
+			}
+		}
+		return nil
+	}); err != nil {
+		return fmt.Errorf("failed to iterate over list: %w", err)
+	}
+
+	if objectsInList > 0 && ignoredObjects < objectsInList {
```
Comment (rfranzke) [inline pkg/utils/kubernetes/client/client.go]: Nit: To simplify readability, can you exit early when `objectsInList == 0` before the entire `EachListItem`?

**Review by rfranzke — COMMENTED** [review]
Nice, thanks for taking care!

File: pkg/gardenlet/operation/botanist/cleanup.go (hunk 4 above)
Comment (timuthy) [reply pkg/gardenlet/operation/botanist/cleanup.go:327]: Hm, is this really simpler? I think the `IgnoreObjectsCreatedAfter` is already pretty simple and suits well into the `IgnoreLeftovers` procedure, plus we log out the leftovers in case there are doubts from (previous) shoot owners.

Comment (rfranzke) [reply pkg/gardenlet/operation/botanist/cleanup.go:327]: I'm fine with keeping it as is - no ask to change. It has the log benefit (although, we would also have these logs from previous executions of the deletion flow if we skipped the entire task) and it fits because you need to have the ignore-handling for the missing namespaces.

File: pkg/gardenlet/operation/botanist/cleanup.go (hunk 2 above)
Comment (timuthy) [reply pkg/gardenlet/operation/botanist/cleanup.go]: Reading should be fine, but I'm hesitant using this for modifications, since `b.SeedNamespaceObject` is a shared object for many concurrently running operations.

We had issues like this in the past with the `Shoot` object (see https://github.com/gardener/gardener/pull/4459).

Comment (rfranzke) [reply pkg/gardenlet/operation/botanist/cleanup.go]: It doesn't make a big difference, but I guess it might be beneficial to have this object up-to-date. Anyway, we can leave it for now... I don't think there is a use-case atm.

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
