### PR TITLE
Fix leak of `extension-controlplane-shoot-webhooks` ManagedResource

### LINKED ISSUE #8688: Leaked ManagedResource `extension-controlplane-shoot-webhooks` might prevent shoot deletion
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
It is possible between gardenlet's tasks `Waiting until shoot control plane has been destroyed` and `Waiting until shoot managed resources have been deleted` in shoot deletion flow an extension's  `webhook-certificate` to create `extension-controlplane-shoot-webhooks` MR
https://github.com/gardener/gardener/blob/00365d6c0fa6fb9053dec6f1e2fa489c53ef53cc/extensions/pkg/webhook/certificates/reconciler.go#L196-L198
This will prevent shoot deletion

**How to reproduce it (as minimally and precisely as possible)**:
1. Manually crash `waitUntilControlPlaneDeleted `
``` golang
		waitUntilControlPlaneDeleted = g.Add(flow.Task{
			Name: "Waiting until shoot control plane has been destroyed",
			Fn: flow.TaskFn(func(ctx context.Context) error {
				time.Sleep(5 * time.Second)
				return fmt.Errorf("Fake error")
				//return botanist.Shoot.Components.Extensions.ControlPlane.WaitCleanup(ctx)
			}).SkipIf(o.Shoot.IsWorkerless),
			Dependencies: flow.NewTaskIDs(destroyControlPlane),
		})
```
2. Comment this line
https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/extensions/pkg/webhook/shoot/webhook.go#L115
``` golang 
	log.Info("Continuing as in local setup there is no expected netpol")
	//return nil
```
3. Create and delete a local shoot
4. Watch for `extension-controlplane-shoot-webhooks` MR

Task `Destroying shoot control plane` will delete  `extension-controlplane-shoot-webhooks` MR
Because `webhook-certificate` runs every 5 minutes it will eventually create `extension-controlplane-shoot-webhooks`

This demonstrates how an extension can create `extension-controlplane-shoot-webhooks` between a tight time period when it is expected to not exist

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area ops-productivity
/area usability
/kind bug

**What this PR does / why we need it**:
This PR eliminates a race condition that led to a leaked managed resource `extension-controlplane-shoot-webhooks` during shoot deletion (see #8688 for more details).
Unlike before, the said `ManagedResource` is only updated when all shoot namespaces are reconciled. Creation won't happen anymore in this scope.

**Which issue(s) this PR fixes**:
Fixes #8688

**Special notes for your reviewer**:
/cc @Kostov6 @ialidzhikov

**Release note**:

```bugfix dependency
An issue was fixed that sometimes led to leaked `extension-controlplane-shoot-webhooks` which blocked the shoot deletion.
```

### CODE REVIEW

**Review by Kostov6 — COMMENTED** [review]
Thanks for the PR!
Just an initial question from my side: isn't it more clearer to use `createOnReconcile` instead of `createOnUpdate` because the variable is being used for creation in the context of the `Reconcile` function in the `builder` package?

**Comment by timuthy** [comment]
@Kostov6 thanks for the feedback!

> Just an initial question from my side: isn't it more clearer to use createOnReconcile instead of createOnUpdate

I can rename it 👍 

Any additional feedback from your side @rfranzke?

File: pkg/utils/managedresources/builder/managedresources.go [hunk 1]
```diff
@@ -31,20 +31,28 @@ import (
 
 // ManagedResource is a structure managing a ManagedResource.
 type ManagedResource struct {
-	client   client.Client
-	resource *resourcesv1alpha1.ManagedResource
+	client         client.Client
+	createOnUpdate bool
```
Comment (rfranzke) [inline pkg/utils/managedresources/builder/managedresources.go]: > Just an initial question from my side: isn't it more clearer to use `createOnReconcile` instead of `createOnUpdate` because the variable is being used for creation in the context of the `Reconcile` function in the `builder` package?

Actually, I think something like `createIfNotExists` or `updateOnly` is even more clear. WDYT?

File: pkg/utils/managedresources/builder/managedresources.go [hunk 2]
```diff
@@ -31,20 +31,28 @@ import (
...
 	return &ManagedResource{
-		client:   client,
-		resource: &resourcesv1alpha1.ManagedResource{},
+		client:         client,
+		createOnUpdate: true,
+		resource:       &resourcesv1alpha1.ManagedResource{},
 	}
 }
 
+// CreateOnUpdate determines if the managed resources should be created if it does not exist.
```
Comment (rfranzke) [inline pkg/utils/managedresources/builder/managedresources.go]: Here you already wrote it in the doc string 😄

File: pkg/utils/managedresources/builder/resourcemanager_test.go [hunk 3]
```diff
@@ -201,6 +203,57 @@ var _ = Describe("Resource Manager", func() {
...
+			}))
+		})
+
+		It("should fail to update the secret if it doesn't exist", func() {
+			secret := NewSecret(fakeClient).
+				WithNamespacedName(namespace, name).
+				WithLabels(labels).
+				CreateOnUpdate(false)
+
+			Expect(secret.Reconcile(ctx)).To(BeNotFoundError())
```
Comment (rfranzke) [inline pkg/utils/managedresources/builder/resourcemanager_test.go:253]: Should this really be the expected behaviour? As a user, if I set `CreateOnUpdate=false` then I wouldn't expect a failure/error when it doesn't exist yet.

File: extensions/pkg/webhook/shoot/webhook.go [hunk 4]
```diff
@@ -68,8 +70,16 @@ func ReconcileWebhookConfig(
...
+	if createOnUpdate {
+		err := managedresources.Create(ctx, c, shootNamespace, managedResourceName, nil, false, "", data, nil, nil, nil)
+		if err != nil {
+			return fmt.Errorf("could not create or update managed resource '%s/%s' containing shoot webhooks: %w", shootNamespace, managedResourceName, err)
+		}
+	} else {
+		err := managedresources.Update(ctx, c, shootNamespace, managedResourceName, nil, false, "", data, nil, nil, nil)
+		if err != nil {
+			return fmt.Errorf("could not update managed resource '%s/%s' containing shoot webhooks: %w", shootNamespace, managedResourceName, err)
+		}
```
Comment (rfranzke) [inline extensions/pkg/webhook/shoot/webhook.go]: Nit:

```suggestion
	f := managedresources.Create
	if !createOnUpdate {
		f = managedresources.Update
	}
	
	if err := f(ctx, c, shootNamespace, managedResourceName, nil, false, "", data, nil, nil, nil); err != nil {
		return fmt.Errorf("failed reconciling managed resource '%s/%s' containing shoot webhooks: %w", shootNamespace, managedResourceName, err)
	}
```

File: extensions/pkg/webhook/shoot/webhook.go [hunk 5]
```diff
@@ -114,7 +124,15 @@ func ReconcileWebhooksForAllNamespaces(
...
 			}
 
-			return ReconcileWebhookConfig(ctx, c, namespaceName, extensionNamespace, extensionName, managedResourceName, *shootWebhookConfigs.DeepCopy(), cluster)
+			if err := ReconcileWebhookConfig(ctx, c, namespaceName, extensionNamespace, extensionName, managedResourceName, *shootWebhookConfigs.DeepCopy(), cluster, false); err != nil {
+				statusErr := &apierrors.StatusError{}
+				if !errors.As(err, &statusErr) {
+					return err
+				}
+				// Ignore not found errors since the managed resource can be deleted in parallel during shoot deletion.
+				return client.IgnoreNotFound(err)
```
Comment (rfranzke) [inline extensions/pkg/webhook/shoot/webhook.go]: Maybe I'm missing something, but why don't we use the typical pattern?

```golang
if apierrors.IsNotFound(err) {
	return nil
}
return err
```

File: pkg/utils/managedresources/builder/resourcemanager_test.go (hunk 3 above)
Comment (timuthy) [reply pkg/utils/managedresources/builder/resourcemanager_test.go:253]: Hm, I don't quite understand that expectation you're posting.

If you tell a client to update (only) a resource and the resource to update does not exist, then it's natural to get an error message.

File: pkg/utils/managedresources/builder/managedresources.go (hunk 1 above)
Comment (timuthy) [reply pkg/utils/managedresources/builder/managedresources.go]: The `createOnUpdate` term was derived from the `AllowCreateOnUpdate` functions ([example](https://github.com/gardener/gardener/blob/3e5ef9a4880f86a5e05b44bc24cecd3416451685/pkg/registry/core/shootstate/strategy.go#L79)), but I really don't have a strong preference 🙂

File: pkg/utils/managedresources/builder/resourcemanager_test.go (hunk 3 above)
Comment (rfranzke) [reply pkg/utils/managedresources/builder/resourcemanager_test.go:253]: Perhaps the naming confused me already. Let's rename this field to make it more clear (in your text, you use "update only" which seems a good option) and then I'll go over it again 😉

Comment (timuthy) [reply pkg/utils/managedresources/builder/resourcemanager_test.go:253]: I tried both, but decided for `createIfNotExists` since it seems more natural IMO. Hope that's fine.

File: extensions/pkg/webhook/shoot/webhook.go [hunk 6]
```diff
@@ -114,7 +120,18 @@ func ReconcileWebhooksForAllNamespaces(
...
-			return ReconcileWebhookConfig(ctx, c, namespaceName, extensionNamespace, extensionName, managedResourceName, *shootWebhookConfigs.DeepCopy(), cluster)
+			if err := ReconcileWebhookConfig(ctx, c, namespaceName, extensionNamespace, extensionName, managedResourceName, *shootWebhookConfigs.DeepCopy(), cluster, false); err != nil {
+				statusErr := &apierrors.StatusError{}
+				if !errors.As(err, &statusErr) {
+					return err
+				}
+				// Ignore not found errors since the managed resource can be deleted in parallel during shoot deletion.
+				if apierrors.IsNotFound(err) {
+					return nil
+				}
```
Comment (rfranzke) [inline extensions/pkg/webhook/shoot/webhook.go]: I'm confused 😄 Can't we get rid of L124-L127? Then we could also go back and use

```golang
if err := ReconcileWebhookConfig(ctx, c, namespaceName, extensionNamespace, extensionName, managedResourceName, *shootWebhookConfigs.DeepCopy(), cluster, false); client.IgnoreNotFound(err) != nil {
	return err
}
```

Comment (timuthy) [reply extensions/pkg/webhook/shoot/webhook.go]: Nice, thanks for the hint. The NotFound error is **wrapped** but this is supported by `apierrors.IsNotFound`, which I didn't know 🙂

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
