### PR TITLE
Enhance `vpn-seed-server` netpol label to consider exposure class

### LINKED ISSUE #7583: Unable to establish vpn tunnel
**How to categorize this issue?**

/area control-plane
/kind regression

**What happened**:
For OpenStack shoots, reconciliation fails because vpn-shoot tunnel connection can't get established. In older version of gardener netpol for vpn-seed-server was like this:
```
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: kubernetes
          gardener.cloud/role: controlplane
          role: apiserver
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: kubernetes
          gardener.cloud/role: controlplane
          role: apiserver
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
          gardener.cloud/role: monitoring
          role: monitoring
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: istio-ingressgateway
          istio: ingressgateway
  podSelector:
    matchLabels:
      app: vpn-seed-server
      gardener.cloud/role: controlplane
  policyTypes:
  - Ingress
  - Egress
```

Ingress traffic was allowed to vpn-seed-server pods from all namespace having labels :
```
app: istio-ingressgateway
istio: ingressgateway
```

In gardener version 1.65 network policy for ingress from `istio` to `vpn-seed-server` look something like this :
```
 ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-ingress
      podSelector:
        matchLabels:
          networking.resources.gardener.cloud/to-all-shoots-vpn-seed-server-tcp-1194: allowed
    ports:
    - port: 1194
      protocol: TCP
  podSelector:
    matchLabels:
      app: vpn-seed-server
  policyTypes:
  - Ingress
```
In the above case, ingress from only ` istio-ingress` namespace is allowed. But in OpenStack system ingress should be allowed from `istio-ingress-handler-converged-cloud-internet` namespace also. 
Because ingress is not possible from `istio-ingress-handler-converged-cloud-internet` tunnel connection can't get established

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: `v.1.65`
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind regression

**What this PR does / why we need it**:
The motivation for this PR is explained in https://github.com/gardener/gardener/issues/7583. This PR enhances `vpn-seed-server` svc netpol label `networking.resources.gardener.cloud/namespace-selectors` to consider exposureclass-handler.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/7583

**Special notes for your reviewer**:

**Release note**:

```other operator
This PR adds required labels for exposureclass handler in `vpn-seed-server` service so that `NetworkPolicy` controller can create required network policies for allowing ingress traffice to `vpn-seed-server` pods.
```

### CODE REVIEW

File: pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go [hunk 1]
```diff
@@ -716,7 +716,8 @@ func (v *vpnSeedServer) deployService(ctx context.Context, idx *int) error {
 		metav1.SetMetaDataAnnotation(&service.ObjectMeta, "networking.istio.io/exportTo", "*")
 
 		metav1.SetMetaDataAnnotation(&service.ObjectMeta, resourcesv1alpha1.NetworkingPodLabelSelectorNamespaceAlias, v1beta1constants.LabelNetworkPolicyShootNamespaceAlias)
-		utilruntime.Must(gardenerutils.InjectNetworkPolicyNamespaceSelectors(service, metav1.LabelSelector{MatchLabels: map[string]string{v1beta1constants.GardenRole: v1beta1constants.GardenRoleIstioIngress}}))
+		utilruntime.Must(gardenerutils.InjectNetworkPolicyNamespaceSelectors(service, metav1.LabelSelector{MatchLabels: map[string]string{v1beta1constants.GardenRole: v1beta1constants.GardenRoleIstioIngress}},
+			metav1.LabelSelector{MatchLabels: map[string]string{v1beta1constants.GardenRole: v1beta1constants.GardenRoleExposureClassHandler}}))
```
Comment (timuthy) [inline pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go]:
```suggestion
			metav1.LabelSelector{MatchExpressions: []metav1.LabelSelectorRequirement{{Key: v1beta1constants.LabelExposureClassHandlerName, Operator: metav1.LabelSelectorOpExists}}}))
```

Unfortunately, the role value is not consistent across all exposure class namespaces, e.g. when they are created for dedicated zones. Please see this commit https://github.com/gardener/gardener/pull/7570/commits/12d5f31f48066f50d836c08d09596a3b73622986#diff-77bddb7bf8b36c35180321a88ccd81424ff675ff29a47d6c372189c95bb27cb9.

**Review by timuthy — COMMENTED** [review]
Awesome, thanks for the PR.

File: pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go (hunk 1 above)
Comment (acumino) [reply pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go]: Adapted in 8823ec9a08de60654eb6535145dec6b1eec41990. I thought if there is a constant defined `GardenRoleExposureClassHandler`, then it should be the same everywhere.

Comment (timuthy) [reply pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go]: That was my assumption in the beginning as well but unfortunately I was told otherwise 😄 However, there is a plan to make this consistent in the future.

**Review by timuthy — COMMENTED** [review]
/lgtm

**Review by shafeeqes — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Thank you for picking this up!
