### PR TITLE
Fix failing creation of hibernated shoots

### LINKED ISSUE #5296: Creation of hibernated Shoot fails
**How to categorize this issue?**

/area quality dev-productivity ops-productivity
/kind bug

**What happened**:
Creation of hibernated Shoot failed.

**What you expected to happen**:
Creation of hibernated Shoot to succeed as before.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot with `spec.hibernation.enabled=true`

```yaml
spec:
  hibernation:
    enabled: true
```

2. Make sure that the creation fails with:

```yaml
  lastOperation:
    description: >-
      Flow "Shoot cluster reconciliation" encountered task errors: [task
      "Deploying gardener-resource-manager" failed: retry failed with context
      deadline exceeded, last error: retry failed with context deadline
      exceeded, last error: token not yet generated] Operation will be retried.
    lastUpdateTime: '2022-01-19T09:54:11Z'
    progress: 51
    state: Error
    type: Create
```

**Environment**:

- Gardener version: 4dde96a5994f181a998e59831aacdcaab8246b48
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area quality
/kind bug
/merge squash

**What this PR does / why we need it**:
This PR fixes an issue preventing hibernated shoots from being created. Details are provided in the individual commit messages.

**Which issue(s) this PR fixes**:
Fixes #5296

**Special notes for your reviewer**:
This PR is similar to #5246 or #5269 given that there are many special cases with hibernation, reconciliation, creation, deletion, etc. With @timebertt we plan to look into integrating more e2e tests during PR verification to prevent regressions like this in the future.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Btw, these were my test cases when developing this:

1. Creating hibernated shoot and delete it afterwards
2. Create (non-hibernated) shoot and delete it afterwards
3. Create (non-hibernated) shoot, reconcile it, hibernate it, reconcile it again, and delete it afterwards
4. Create (non-hibernated) shoot, hibernate it, wake it up, and delete it afterwards

File: pkg/operation/botanist/controlplane.go [hunk 1]
```diff
@@ -152,6 +152,24 @@ func (b *Botanist) DeployVerticalPodAutoscaler(ctx context.Context) error {
 	)
 }
 
+func (b *Botanist) determineControllerReplicas(ctx context.Context, deploymentName string, defaultReplicas int32) (int32, error) {
```
Comment (timuthy) [inline pkg/operation/botanist/controlplane.go:155]: Hint for future work: Also handle `b.Shoot.GetInfo().Status.LastOperation.Type == gardencorev1beta1.LastOperationTypeDelete` so that we don't have to set the replicas in the delete flow separately.

**Review by timuthy — APPROVED** [review]
Thanks for the fix 🚀 
/lgtm

File: pkg/operation/botanist/controlplane.go (hunk 1 above)
Comment (rfranzke) [reply pkg/operation/botanist/controlplane.go:155]: Good point. Let's first integrate some more integration tests so that we can ensure functionality without manual effort, but I like the suggestion! :)
