### PR TITLE
Make `ConcurrentSyncs` field in `ControllerConfiguration` of GCM Controllers optional and Default them

### LINKED ISSUE #5758: GCM configuration for projects doesn't require concurrentSyncs to be set, deploys 0 workers
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

When not setting `controllers.project.concurrentSyncs` in the `ControllerManagerConfiguration` (but any other `project` setting), this isn't caught by the validation step and results in 0 workers being deployed, so the `Project` resource isn't reconciled.

**What you expected to happen**:

Either a validation failure stating that `controllers.project.concurrentSyncs` is a required value, so the user can make a consciuous choice about the number of workers. The helm template e. g. already marks this as required.

Or, when not explicitly setting the `concurrentSyncs` value, just use the default value of `5`. Maybe a pointer value could be used in order to distinguish between a `nil` value and a `0` value.

**How to reproduce it (as minimally and precisely as possible)**:

Change the `ControllerManagerConfiguration` in the according section to something like this:

```yaml
controllers:
  project:
    staleGracePeriodDays: 20
```

in the `gardener-controller-manager-configmap` by hand.

**Anything else we need to know?**:

Should be changed around here:

https://github.com/gardener/gardener/blob/eec37223cb90475ec3e023136a7d5ba28ad48f0d/pkg/controllermanager/apis/config/v1alpha1/defaults.go#L78

This also affects other controllers with similiar settings.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR makes the `ConcurrentSyncs` field in `ControllerConfiguration` of GCM Controllers optional, and defaults them to a valid value.

**Which issue(s) this PR fixes**:
Fixes #5758 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
I am not sure if we want to add validation for all controllers now. Once it is confirmed, I will add unit tests accordingly.

**Comment by acumino** [comment]
> I am not sure if we want to add validation for all controllers now. Once it is confirmed, I will add unit tests accordingly.

It's better to add for all, we will be needing this validation even though this will not occur very often.

**Comment by rfranzke** [comment]
Do we really want to enforce that `concurrentSyncs > 0` for all the controllers? This way, we cannot disable individual controllers anymore, right? Wouldn't the better approach be to make the `concurrentSyncs` field optional and default it if unset (`nil`)?

**Comment by shafeeqes** [comment]
We would want to default ConcurrentSyncs of these controllerConfigs as well, right?
I'm asking, because currently they are not defaulted in https://github.com/gardener/gardener/blob/master/pkg/controllermanager/apis/config/v1alpha1/defaults.go since they aren't optional.
https://github.com/gardener/gardener/blob/f5882800d5821bcc18198da96324bbe013bb1afe/pkg/controllermanager/apis/config/types.go#L80-L85

**Comment by rfranzke** [comment]
Yeah, I think the current defaulting or type definitions in these configurations are not consistent. I think making the `concurrentSync` field optional everywhere and default if `nil` makes sense.

**Comment by shafeeqes** [comment]
So drop the validation functions templates, as well? we can add them once there is something we want to validate, or do we just keep them empty?

**Comment by rfranzke** [comment]
Let's keep them empty for now, now that you already spent the time to introduce them consistently. This will make it easy in the future to add additional logic if needed.

**Comment by shafeeqes** [comment]
/title Make `ConcurrentSyncs` field in `ControllerConfiguration` of GCM Controllers optional and Default them

File: pkg/controllermanager/apis/config/v1alpha1/defaults.go [hunk 1]
```diff
@@ -44,41 +44,64 @@ func SetDefaults_ControllerManagerConfiguration(obj *ControllerManagerConfigurat
 	if obj.Controllers.Bastion == nil {
 		obj.Controllers.Bastion = &BastionControllerConfiguration{}
 	}
-	if obj.Controllers.Bastion.ConcurrentSyncs == 0 {
-		obj.Controllers.Bastion.ConcurrentSyncs = 5
+	if obj.Controllers.Bastion.ConcurrentSyncs == nil {
+		v := 5
```
Comment (rfranzke) [inline pkg/controllermanager/apis/config/v1alpha1/defaults.go]: What about having a variable `defaultConcurrentSyncs = 5` which you can reuse everywhere instead of redefining `v := 5` everywhere?

Comment (shafeeqes) [reply pkg/controllermanager/apis/config/v1alpha1/defaults.go]: https://github.com/gardener/gardener/blob/7d52217e6b92881dba08aabf3432048e7e6e08d9/pkg/gardenlet/apis/config/v1alpha1/types.go#L704-L705

Should we define it in `types.go` like gardenlet?
