### PR TITLE
Fixes restoration of worker resource

### LINKED ISSUE #5376: Restoration of worker resource can fail when trying to restore the machine objects
**How to categorize this issue?**

/area control-plane-migration
/kind bug
/priority 2

**What happened**:
During the restore phase of control plane migration the following error occurs:
```
Error restoring worker: failed restoration
      of the machineSet and the machines: Machine.machine.sapcloud.io "<machine-name>"
      is invalid: [status.lastOperation.lastUpdateTime: Invalid value: "null": status.lastOperation.lastUpdateTime
      in body must be of type string: "null", status.currentStatus.lastUpdateTime:
      Invalid value: "null": status.currentStatus.lastUpdateTime in body must be of
      type string: "null"]
```

**What you expected to happen**:
Control Plane Migration to finish successfully

**Anything else we need to know?**:
This was initially fixed by https://github.com/gardener/gardener/pull/4681. However, the code was later modified to use `Update()` instead of `Patch()` in https://github.com/gardener/gardener/pull/4799. Seems like update calls fail (atleast for v1.Time fields) when the fields in the `status` struct are defaulted and in the `machines` CRD the corresponding fields type is `string` . Only calling `Patch` most likely works since it would only try to change the `machine.status.node` field and not send the other `machine.status` fields in the request.

I encountered this issue when migrating shoots to seeds running kubernetes 1.19.5 and 1.18.20. It does not occur on kubernetes 1.22.2

Currently the reason that we want to update the status of the machines is to write the `machine.status.node` field so that when MCM is started the machine objects can "adopt" the already existing nodes. However, this `node` information is also present in the machine labels which get added to the machines during restoration as well. So perhaps we could completely omit updating the machine status after creation.

**Environment**:

- Gardener version: 1.39.0
- Kubernetes version (use `kubectl version`): reproduced on 1.19.5, 1.18.20
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
Fixes an issue that can happen during the restoration of the worker resource:
```
Error restoring worker: failed restoration
      of the machineSet and the machines: Machine.machine.sapcloud.io "<machine-name>"
      is invalid: [status.lastOperation.lastUpdateTime: Invalid value: "null": status.lastOperation.lastUpdateTime
      in body must be of type string: "null", status.currentStatus.lastUpdateTime:
      Invalid value: "null": status.currentStatus.lastUpdateTime in body must be of
      type string: "null"]
```

This was originally fixed in #4681 but then the issue started appearing again after #4799 (which replaced the call to `TryPatch()` with `Update()`.

The error is caused because marshalling a non initialised `metav1.Time` to json returns `null` and the `lastUpdateTime` fields in the `machines` CRD are not nullable. Using `Patch()` to only update the `machine.Status.Node` is a workaround until https://github.com/gardener/machine-controller-manager/issues/642 is fixed.

**Which issue(s) this PR fixes**:
Fixes #5376 

**Special notes for your reviewer**:
/cc @timebertt @BeckerMax (as release responsible)

**Release note**:

```bugfix operator
Fixes an issue that prevents the status of `Machine` objects to be modified during the restore phase of control plane migration. Patch is now used to do the modification instead of an update call.
```

### CODE REVIEW

**Review by timebertt — CHANGES_REQUESTED** [review]
I think, this is not a proper solution for the referenced issue, some thoughts:
- Isn't the proper way to resolve it to fix the CRD / type definition of `MachineStatus` in mcm? See https://github.com/gardener/machine-controller-manager/issues/642#issuecomment-1028704539. Maybe I'm missing something here, so I'm happy to clarify that. But this is quite unclear and confusing to me.
- Patch is only a "lucky" workaround and as you described in https://github.com/gardener/gardener/issues/5376: it only "most likely works"
- Even if this was the proper fix: how do you prevent further regressions of this? There is no unit test for it, the PR description is a bit unclear to me, and there is not even a code comment, which would prevent other developers to simply change that line again (like me in https://github.com/gardener/gardener/pull/4799).

**Comment by plkokanov** [comment]
This should definitely be fixed and/or addressed further in https://github.com/gardener/machine-controller-manager/issues/642. However, in the meantime I think that it would be good to have this workaround in, so that control plane migration isn't broken. 
I can add a comment indicating that and also modify the tests to use mocks and check that Patch is called during the restoration of the machines.

File: extensions/pkg/controller/worker/genericactuator/actuator_restore.go [hunk 1]
```diff
@@ -138,8 +138,12 @@ func (a *genericActuator) restoreMachineSetsAndMachines(ctx context.Context, log
 				}
 			}
 
-			newMachine.Status = machine.Status
-			return a.client.Status().Update(ctx, newMachine)
+			// Patch() is used here instead of Update() so that only the machine.Status.Node field is modified as a workaround
```
Comment (ialidzhikov) [inline extensions/pkg/controller/worker/genericactuator/actuator_restore.go:141]: Does it make sense to add a todo so we don't forget to switch back to update?

```suggestion
			// TODO (plkokanov): Switch back to Update() when https://github.com/gardener/machine-controller-manager/issues/642 is resolved.
			// Patch() is used here instead of Update() so that only the machine.Status.Node field is modified as a workaround
```

**Review by ialidzhikov — COMMENTED** [review]
Having in mind that Patch() was the behaviour before https://github.com/gardener/gardener/pull/4799 and (if I followed correctly) the issue seems to be on machine-controller-manager side and this PR is rather a mitigation, then I am fine with this PR as short-term mitigation until the machine-controller-manager issue is resolved.

File: extensions/pkg/controller/worker/genericactuator/actuator_restore.go (hunk 1 above)
Comment (plkokanov) [reply extensions/pkg/controller/worker/genericactuator/actuator_restore.go:141]: I was wondering whether to add such a comment, but decided to leave it out since `Patch()` works just as well. 
Btw there is currently a discussion with the MCM maintainers whether we can stop using the `status.Node` field and instead rely on the `node` label in the machine objects. So in the future I would prefer to completely remove the status modification if possible. I can actually open an issue so that we track such a possibility for a change.

Comment (ialidzhikov) [reply extensions/pkg/controller/worker/genericactuator/actuator_restore.go:141]: @timebertt is there a particular reason we would like to switch to Update() in the future, or is the Patch() in this usage does the same job?

**Review by ialidzhikov — APPROVED** [review]
/lgtm

File: extensions/pkg/controller/worker/genericactuator/actuator_restore.go (hunk 1 above)
Comment (timebertt) [reply extensions/pkg/controller/worker/genericactuator/actuator_restore.go:141]: IIRC, I changed it to `Update` because the code was modifying the entire status section, which was not safe to be done without optimistic locking.
However, it seems that we only want to modify one specific field (`machine.Status.Node`), which is safe to do without optimistic locking.
Hence, it should not be needed to switch to `Update()` again in the future.

**Review by timebertt — APPROVED** [review]
Thanks.
/lgtm
