### PR TITLE
Mark `ShootSystemComponentsHealthy` condition unhealthy if `ManagedResource` is stuck in progressing for more than threshold time

### LINKED ISSUE #6775: Unready calico-node Pod is not reflected in the Shoot status
**How to categorize this issue?**

/area control-plane quality
/kind bug

**What happened**:
For a Shoot calico-node Pod is unhealthy since longtime:
```
$ k -n kube-system get po -l k8s-app=calico-node
NAME                READY   STATUS    RESTARTS   AGE
calico-node-rgd9p   0/1     Running   0          6d10h
calico-node-w9zmf   1/1     Running   0          7d

$ k -n kube-system describe po calico-node-rgd9p

Events:
  Type     Reason     Age                      From     Message
  ----     ------     ----                     ----     -------
  Warning  Unhealthy  77s (x63115 over 6d10h)  kubelet  (combined from similar events): Readiness probe failed: 2022-10-05 08:59:22.390 [INFO][1946539] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.180.13.235

$ k -n kube-system get ds calico-node
NAME          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
calico-node   2         2         1       1            1           kubernetes.io/os=linux   7d
```

```
$ k -n kube-system get ds calico-node -o yaml

status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  numberUnavailable: 1
  observedGeneration: 2
  updatedNumberScheduled: 1
```

Looks lie GRM threats this that the DaemonSet is Progressing:
```
$ k -n shoot--foo--bar get mr extension-networking-calico-config
NAME                                 CLASS   APPLIED   HEALTHY   PROGRESSING   AGE
extension-networking-calico-config           True      True      True          7d
```

And this issue is not reflected in any way in the Shoot status.

**What you expected to happen**:
The issue to be reflected in the Shoot status.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.56.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane quality
/kind enhancement

**What this PR does / why we need it**:
This PR introduces a new field `controllers.shootCare.managedResourceProgressingThreshold` in `GardenletConfiguration` which can be used to set threshold time for managed resource progressing condition. So if an MR's `Progressing` and `Healthy` condition status is `true` for more than the threshold time, `ShootSystemComponentsHealthy` condition status will be changed to false.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/6775

**Special notes for your reviewer**:

**Release note**:

```feature operator
A new field `controllers.shootCare.managedResourceProgressingThreshold` is introduced in `GardenletConfiguration`, which can be used to set the threshold time for tolerating long-running `ManagedResources` with `Progressing=True` condition.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
There is no single unit/integration test added to cover the newly introduced functionality.

File: pkg/apis/core/v1beta1/types_utils.go [hunk 1]
```diff
@@ -69,4 +69,7 @@ const (
 	// OutdatedStatusError is a constant for a reason in a condition that indicates
 	// that the observed generation in a status is outdated.
 	OutdatedStatusError = "OutdatedStatus"
+	// ManagedResourceStuckInProgressingError is a constant for a reason in a condition that indicates
+	// managed resource progressing condition is stuck in the true state for more than the threshold time.
```
Comment (shafeeqes) [inline pkg/apis/core/v1beta1/types_utils.go:73]:
```suggestion
	// ManagedResource progressing condition is stuck in the true state for more than the threshold time.
```

File: pkg/operation/care/checker.go [hunk 2]
```diff
@@ -257,13 +260,27 @@ func resourcesNotProgressingCheck() func(status gardencorev1beta1.ConditionStatu
 	}
 }
 
-func (b *HealthChecker) checkManagedResourceConditions(condition gardencorev1beta1.Condition, mr *resourcesv1alpha1.ManagedResource, conditionsToCheck map[gardencorev1beta1.ConditionType]func(status gardencorev1beta1.ConditionStatus) bool) *gardencorev1beta1.Condition {
+func (b *HealthChecker) checkManagedResourceConditions(
+	condition gardencorev1beta1.Condition,
+	mr *resourcesv1alpha1.ManagedResource,
+	conditionsToCheck map[gardencorev1beta1.ConditionType]func(status gardencorev1beta1.ConditionStatus) bool,
+	managedResourceProgressingThreshold *metav1.Duration) *gardencorev1beta1.Condition {
```
Comment (shafeeqes) [inline pkg/operation/care/checker.go]: Can't we directly use this from the `HealthChecker` struct?

File: pkg/operation/care/checker.go [hunk 3]
```diff
@@ -284,6 +301,11 @@ func (b *HealthChecker) checkManagedResourceConditions(condition gardencorev1bet
 		return &c
 	}
 
+	if conditionProgressing && conditionHealthy {
+		c := b.FailedCondition(condition, gardencorev1beta1.ManagedResourceStuckInProgressingError, fmt.Sprintf("ManagedResource %s progressing state is true for more than %v time", mr.Name, managedResourceProgressingThreshold.Duration))
```
Comment (shafeeqes) [inline pkg/operation/care/checker.go]: What about "ManagedResource is in Progressing state for more than..."?

File: pkg/operation/care/health.go [hunk 4]
```diff
@@ -87,9 +87,10 @@ func (h *Health) Check(
 	ctx context.Context,
 	thresholdMappings map[gardencorev1beta1.ConditionType]time.Duration,
 	healthCheckOutdatedThreshold *metav1.Duration,
+	managedResourceProgressingThreshold *metav1.Duration,
```
Comment (shafeeqes) [inline pkg/operation/care/health.go]: Should we make this also part of the struct? If not, then can we harmonize the above case too?

**Review by shafeeqes — CHANGES_REQUESTED** [review]

File: pkg/gardenlet/apis/config/v1alpha1/types.go [hunk 5]
```diff
@@ -350,6 +350,9 @@ type ShootCareControllerConfiguration struct {
 	// StaleExtensionHealthChecks defines the configuration of the check for stale extension health checks.
 	// +optional
 	StaleExtensionHealthChecks *StaleExtensionHealthChecks `json:"staleExtensionHealthChecks,omitempty"`
+	// ManagedResourceProgressingThreshold is the duration after which if managed resource progressing
+	// condition remains true then managed resource is considered stuck.
```
Comment (ialidzhikov) [inline pkg/gardenlet/apis/config/v1alpha1/types.go]: `+optional` tag is missing.

```suggestion
	// condition remains true then managed resource is considered stuck.
	// +optional
```

File: pkg/gardenlet/apis/config/types.go [hunk 6]
```diff
@@ -284,6 +284,9 @@ type ShootCareControllerConfiguration struct {
 	SyncPeriod *metav1.Duration
 	// StaleExtensionHealthChecks defines the configuration of the check for stale extension health checks.
 	StaleExtensionHealthChecks *StaleExtensionHealthChecks
+	// ManagedResourceProgressingThreshold is the duration after which if managed resource progressing
+	// condition remains true then managed resource is considered stuck.
```
Comment (ialidzhikov) [inline pkg/gardenlet/apis/config/types.go]: Cosmetic suggestion

```suggestion
	// ManagedResourceProgressingThreshold is the allowed duration a ManagedResource can be with condition
	// Progressing=True before being considered as "stuck" from the shoot-care controller.
	// If the field is not specified, the check for ManagedResource "stuck" in progressing state is not performed.
```

File: pkg/gardenlet/apis/config/v1alpha1/types.go (hunk 5 above)
Comment (ialidzhikov) [inline pkg/gardenlet/apis/config/v1alpha1/types.go]:
```suggestion
	// ManagedResourceProgressingThreshold is the allowed duration a ManagedResource can be with condition
	// Progressing=True before being considered as "stuck" from the shoot-care controller.
	// If the field is not specified, the check for ManagedResource "stuck" in progressing state is not performed.
```

File: example/20-componentconfig-gardenlet.yaml [hunk 7]
```diff
@@ -52,6 +52,7 @@ controllers:
     staleExtensionHealthChecks:
       enabled: true
     # threshold: 5m
+    managedResourceProgressingThreshold: 1h
```
Comment (ialidzhikov) [inline example/20-componentconfig-gardenlet.yaml:55]: The gardenlet chart has to be adapted as well to support the new field in the GardenletConfiguration:

https://github.com/gardener/gardener/blob/9fae12b4cc29928cefd5f0cade44290e33378844/charts/gardener/gardenlet/templates/_helpers.tpl#L191-L205

File: pkg/operation/care/checker.go [hunk 8]
```diff
@@ -257,13 +260,27 @@ func resourcesNotProgressingCheck() func(status gardencorev1beta1.ConditionStatu
...
 	for _, cond := range mr.Status.Conditions {
+		if cond.Type == resourcesv1alpha1.ResourcesProgressing &&
+			cond.Status == gardencorev1beta1.ConditionTrue &&
+			managedResourceProgressingThreshold != nil &&
+			time.Since(cond.LastTransitionTime.Time) >= managedResourceProgressingThreshold.Duration {
+			conditionProgressing = true
+		}
+		if cond.Type == resourcesv1alpha1.ResourcesHealthy && cond.Status == gardencorev1beta1.ConditionTrue {
+			conditionHealthy = true
+		}
```
Comment (ialidzhikov) [inline pkg/operation/care/checker.go]: Is it possible to perform this check via the `conditionsToCheck` map that is passed? I see that currently the func in `conditionsToCheck` accepts only the condition status but we could give a try to adapt it to accept the whole ManagedResource?
I am writing down this comment because `ResourcesApplied` and `ResourcesHealthy` conditions are checked via funcs in this `conditionsToCheck` map but on the other side we have custom coding inline for the Progressing condition.

File: pkg/apis/core/v1beta1/types_utils.go (hunk 1 above)
Comment (acumino) [reply pkg/apis/core/v1beta1/types_utils.go:73]: It is not a variable name so `managed resource` it's fine

File: pkg/operation/care/checker.go (hunk 8 above)
Comment (acumino) [reply pkg/operation/care/checker.go]: I think keeping it this way is better -> This is not just checking `ResourceProgressing` condition but depends on `ResourcesHealthy` so to make it work via `conditionsToCheck ` whole managed resource needs to be passed in the function, and this is not the main reason. The main reason I prefer not to do so is - 
For all conditions, it will be required to loop through all conditions so that 3*3 total 9 operations but in the current scenario, it is required only 3. So if there are many shoots in one seed this can created overhead.
But if it is not important I can change it. WDYT?

File: example/20-componentconfig-gardenlet.yaml (hunk 7 above)
Comment (rfranzke) [inline example/20-componentconfig-gardenlet.yaml:55]: Should we also add this for the seed-care controller? Can't we face similar problems there as well?

Comment (rfranzke) [inline example/20-componentconfig-gardenlet.yaml:55]: Please extend https://github.com/gardener/gardener/blob/master/docs/concepts/gardenlet.md#care-reconciler-2

File: pkg/apis/core/v1beta1/types_utils.go [hunk 9]
```diff
@@ -69,4 +69,7 @@ const (
...
+	ManagedResourceStuckInProgressingError = "ManagedResourceStuckInProgressing"
```
Comment (rfranzke) [inline pkg/apis/core/v1beta1/types_utils.go]:
```suggestion
	ManagedResourceStuckInProgressingError = "ProgressingRolloutStuck"
```

Maybe this or `ProgressingStuck` is clearer for a "reason" - the message can then contain all the details why.

File: pkg/operation/care/checker.go [hunk 10]
```diff
@@ -258,13 +261,26 @@ func resourcesNotProgressingCheck() func(status gardencorev1beta1.ConditionStatu
...
 		c := b.FailedCondition(condition, gardencorev1beta1.OutdatedStatusError, fmt.Sprintf("observed generation of managed resource '%s/%s' outdated (%d/%d)", mr.Namespace, mr.Name, mr.Status.ObservedGeneration, mr.Generation))
 		return &c
 	}
 
+	var conditionProgressing, conditionHealthy bool
 	for _, cond := range mr.Status.Conditions {
+		if cond.Type == resourcesv1alpha1.ResourcesProgressing &&
+			cond.Status == gardencorev1beta1.ConditionTrue &&
+			b.managedResourceProgressingThreshold != nil &&
+			time.Since(cond.LastTransitionTime.Time) >= b.managedResourceProgressingThreshold.Duration {
```
Comment (rfranzke) [inline pkg/operation/care/checker.go]: Use a clock instead?

File: pkg/operation/care/checker.go [hunk 11]
```diff
@@ -258,13 +261,26 @@ func resourcesNotProgressingCheck() func(status gardencorev1beta1.ConditionStatu
...
+			conditionProgressing = true
```
Comment (rfranzke) [inline pkg/operation/care/checker.go]: Why do we set this variable to `true`? This is confusing - shouldn't we use a new variable for this scenario?

File: pkg/operation/care/checker.go [hunk 12]
```diff
@@ -285,6 +301,11 @@ func (b *HealthChecker) checkManagedResourceConditions(condition gardencorev1bet
 		return &c
 	}
 
+	if conditionProgressing && conditionHealthy {
+		c := b.FailedCondition(condition, gardencorev1beta1.ManagedResourceStuckInProgressingError, fmt.Sprintf("ManagedResource %s progressing state is true for more than %v", mr.Name, b.managedResourceProgressingThreshold.Duration))
```
Comment (rfranzke) [inline pkg/operation/care/checker.go]:
```suggestion
		c := b.FailedCondition(condition, gardencorev1beta1.ManagedResourceStuckInProgressingError, fmt.Sprintf("ManagedResource %s is progressing for more than %v", mr.Name, b.managedResourceProgressingThreshold.Duration))
```

File: example/20-componentconfig-gardenlet.yaml (hunk 7 above)
Comment (acumino) [reply example/20-componentconfig-gardenlet.yaml:55]: There was no such case observed in past  that's why I didn't add it.

Comment (rfranzke) [reply example/20-componentconfig-gardenlet.yaml:55]: OK, but conceptionally it can happen there as well, so let's better add it now since we touch this code anyways instead of having follow-up effort later.

Comment (acumino) [reply example/20-componentconfig-gardenlet.yaml:55]: For seed, we already check MR progressing condition, https://github.com/gardener/gardener/blob/d9ac107ea424bae2200ecfa0b93a84bd4c956f0e/pkg/operation/care/checker.go#L255-L259
https://github.com/gardener/gardener/blob/d9ac107ea424bae2200ecfa0b93a84bd4c956f0e/pkg/operation/care/seed_health.go#L146-L154
 So if MR is in progressing for more than `SeedSystemComponentsHealthy` threshold MR is considered in failed state and subsequently, `SeedSystemComponentsHealthy` is considered to be in failed state.
 Should I keep this behavior or harmonize it to match it with shoot care controller and use `managedResourceProgressingThreshold` for marking progressing MR as failed? I prefer the second option.

Comment (rfranzke) [reply example/20-componentconfig-gardenlet.yaml:55]: I just checked again what's happening, and this is what I understand:

For `Seed`s, if a `ManagedResource` is `Progressing` then the `SeedSystemComponentsHealthy` also becomes `Progressing`, and if this takes longer than `1m` we mark it as false, I think. We don't want to keep `SeedSystemComponentsHealthy` as `True` if there are `ManagedResource` with `healthy=progressing=true` since we need to ensure that the seed is healthy and up to date before we start a `Shoot` reconciliation. 

In this light, the change of this PR does not seem to make sense for the seed-care controller. WDYT?

Comment (acumino) [reply example/20-componentconfig-gardenlet.yaml:55]: > For Seeds, if a ManagedResource is Progressing then the SeedSystemComponentsHealthy also becomes Progressing, and if this takes longer than 1m we mark it as false, I think. We don't want to keep SeedSystemComponentsHealthy as True if there are ManagedResource with healthy=progressing=true since we need to ensure that the seed is healthy and up to date before we start a Shoot reconciliation.

Yes, But I was suggesting harmonizing things every where and using `managedResourceProgressingThreshold ` field to mark MR unhealthy/failed, and based on it `SeedSystemComponentsHealthy` will be marked unhealthy/failed.

But this will increase overall complexity without adding any value. And it is better to not add this field in the seed care controller configuration.

Comment (rfranzke) [reply example/20-componentconfig-gardenlet.yaml:55]: Yes, then let's keep it only for the shoot controller for now. We can revisit this if needed later. :)

File: pkg/operation/care/health_check_test.go [hunk 13]
```diff
@@ -159,7 +159,7 @@ var _ = Describe("health check", func() {
 	var (
 		ctx        = context.TODO()
 		fakeClient client.Client
-		fakeClock  *testclock.FakeClock
+		fakeClock  = testclock.NewFakeClock(time.Now())
```
Comment (shafeeqes) [inline pkg/operation/care/health_check_test.go:162]: Why did you change this, we already initialize with `time.Now()` in the `BeforeEach`

File: docs/concepts/gardenlet.md [hunk 14]
```diff
@@ -408,6 +408,8 @@ It maintains four conditions and performs the following checks:
 - `EveryNodyReady`: The conditions of the worker nodes are checked (e.g., `Ready`, `MemoryPressure`, etc.). Also, it's checked whether the Kubernetes version of the installed `kubelet` matches the desired version specified in the `Shoot` resource.
 - `SystemComponentsHealthy`: The conditions of the `ManagedResource`s are checked (e.g. `ResourcesApplied`, etc.). Also, it is verified whether the VPN tunnel connection is established (which is required for the `kube-apiserver` to communicate with the worker nodes).
 
+Sometimes there can be case where ManagedReosurce get stuck with both `Healthy` and `Progressing` condition set to `true`. To prevent it one can set `GardenletConfiguration.controllers.shootCare.managedResourceProgressingThreshold`. So if ManagedReosurce `Progressing` condition is `true` for more than `managedResourceProgressingThreshold`, `SystemComponentsHealthy` condition is marked `Progressing` or `False` accordingly.
+
```
Comment (shafeeqes) [inline docs/concepts/gardenlet.md]:
```suggestion
If `GardenletConfiguration.controllers.shootCare.managedResourceProgressingThreshold` is set and the ManagedResource is in `Progressing=True` state for more than `managedResourceProgressingThreshold`, `SystemComponentsHealthy` condition is set to `False`.
```

File: pkg/operation/care/health_check_test.go (hunk 13 above)
Comment (acumino) [reply pkg/operation/care/health_check_test.go:162]: It's required. Because we can't use uninitialized variables in Table entries.

File: docs/concepts/gardenlet.md [hunk 15]
```diff
@@ -408,6 +408,8 @@ It maintains four conditions and performs the following checks:
 - `EveryNodyReady`: The conditions of the worker nodes are checked (e.g., `Ready`, `MemoryPressure`, etc.). Also, it's checked whether the Kubernetes version of the installed `kubelet` matches the desired version specified in the `Shoot` resource.
 - `SystemComponentsHealthy`: The conditions of the `ManagedResource`s are checked (e.g. `ResourcesApplied`, etc.). Also, it is verified whether the VPN tunnel connection is established (which is required for the `kube-apiserver` to communicate with the worker nodes).
 
+Sometimes there can be case where ManagedReosurce get stuck with both `Healthy` and `Progressing` condition set to `true`. To prevent it one can set `GardenletConfiguration.controllers.shootCare.managedResourceProgressingThreshold`. So if ManagedReosurce `Progressing` condition is `true` for more than `managedResourceProgressingThreshold`, `SystemComponentsHealthy` condition is marked `Progressing` or `False` accordingly.
```
Comment (rfranzke) [inline docs/concepts/gardenlet.md]:
```suggestion
Sometimes, `ManagedResource`s can have both `Healthy` and `Progressing` conditions set to `True` (e.g., when a `DaemonSet` rolls out one-by-one on a large cluster with many nodes) while this is not reflected in the `Shoot` status. In order to catch issues where the rollout gets stuck, one can set `.controllers.shootCare.managedResourceProgressingThreshold` in the `gardenlet`'s component configuration. If the `Progressing` condition is still `True` for more than the configured duration, the `SystemComponentsHealthy` condition in the `Shoot` is set to `False`, eventually.
```

File: pkg/apis/core/v1beta1/types_utils.go [hunk 16]
```diff
@@ -69,4 +69,7 @@ const (
 	// OutdatedStatusError is a constant for a reason in a condition that indicates
 	// that the observed generation in a status is outdated.
 	OutdatedStatusError = "OutdatedStatus"
+	// ManagedResourceStuckInProgressingError is a constant for a reason in a condition that indicates
+	// managed resource progressing condition is stuck in the true state for more than the threshold time.
+	ManagedResourceStuckInProgressingError = "ProgressingRolloutStuck"
```
Comment (rfranzke) [inline pkg/apis/core/v1beta1/types_utils.go]:
```suggestion
	ManagedResourceProgressingRolloutStuck = "ProgressingRolloutStuck"
```

File: pkg/operation/care/checker.go [hunk 17]
```diff
@@ -258,13 +261,26 @@ func resourcesNotProgressingCheck() func(status gardencorev1beta1.ConditionStatu
 	}
 }
 
-func (b *HealthChecker) checkManagedResourceConditions(condition gardencorev1beta1.Condition, mr *resourcesv1alpha1.ManagedResource, conditionsToCheck map[gardencorev1beta1.ConditionType]func(status gardencorev1beta1.ConditionStatus) bool) *gardencorev1beta1.Condition {
+func (b *HealthChecker) checkManagedResourceConditions(
+	condition gardencorev1beta1.Condition,
+	mr *resourcesv1alpha1.ManagedResource,
+	conditionsToCheck map[gardencorev1beta1.ConditionType]func(status gardencorev1beta1.ConditionStatus) bool) *gardencorev1beta1.Condition {
```
Comment (rfranzke) [inline pkg/operation/care/checker.go]:
```suggestion
	conditionsToCheck map[gardencorev1beta1.ConditionType]func(status gardencorev1beta1.ConditionStatus) bool,
) *gardencorev1beta1.Condition {
```

File: pkg/operation/care/checker.go [hunk 18]
```diff
@@ -258,13 +261,26 @@ func resourcesNotProgressingCheck() func(status gardencorev1beta1.ConditionStatu
...
 	if mr.Generation != mr.Status.ObservedGeneration {
 		c := b.FailedCondition(condition, gardencorev1beta1.OutdatedStatusError, fmt.Sprintf("observed generation of managed resource '%s/%s' outdated (%d/%d)", mr.Namespace, mr.Name, mr.Status.ObservedGeneration, mr.Generation))
 		return &c
 	}
 
+	var conditionProgressingForMoreThanThreshold, conditionHealthy bool
```
Comment (rfranzke) [inline pkg/operation/care/checker.go]:
```suggestion
	var conditionProgressingTooLong, conditionHealthy bool
```

File: pkg/operation/care/checker.go [hunk 19]
```diff
@@ -285,6 +301,11 @@ func (b *HealthChecker) checkManagedResourceConditions(condition gardencorev1bet
 		return &c
 	}
 
+	if conditionProgressingForMoreThanThreshold && conditionHealthy {
+		c := b.FailedCondition(condition, gardencorev1beta1.ManagedResourceStuckInProgressingError, fmt.Sprintf("ManagedResource %s is progressing for more than %v", mr.Name, b.managedResourceProgressingThreshold.Duration))
```
Comment (rfranzke) [inline pkg/operation/care/checker.go]:
```suggestion
		c := b.FailedCondition(condition, gardencorev1beta1.ManagedResourceStuckInProgressingError, fmt.Sprintf("ManagedResource %s is progressing for more than %s", mr.Name, b.managedResourceProgressingThreshold.Duration))
```

File: pkg/gardenlet/apis/config/helper/helpers_test.go [hunk 20]
```diff
@@ -296,4 +296,46 @@ var _ = Describe("helper", func() {
...
+		It("should return non nil value when ManagedResourceProgressingThreshold value is set", func() {
+			gardenletConfig := &config.GardenletConfiguration{
+				Controllers: &config.GardenletControllerConfiguration{
+					ShootCare: &config.ShootCareControllerConfiguration{
+						ManagedResourceProgressingThreshold: &metav1.Duration{},
+					},
+				},
+			}
+
+			Expect(GetManagedResourceProgressingThreshold(gardenletConfig)).To(Not(BeNil()))
```
Comment (ialidzhikov) [inline pkg/gardenlet/apis/config/helper/helpers_test.go]: Nit: to make sure that the configured threshold is returned (and not a random one).

```suggestion
			threshold := &metav1.Duration{Duration: time.Minute}
			gardenletConfig := &config.GardenletConfiguration{
				Controllers: &config.GardenletControllerConfiguration{
					ShootCare: &config.ShootCareControllerConfiguration{
						ManagedResourceProgressingThreshold: threshold,
					},
				},
			}

			Expect(GetManagedResourceProgressingThreshold(gardenletConfig)).To(Equal(threshold))
```

File: pkg/operation/care/checker.go (hunk 8 above)
Comment (ialidzhikov) [reply pkg/operation/care/checker.go]: It is more challenging to perform the check via the `conditionsToCheck` map.

I don't think it is that important how many times (3 or 9) we will loop over the conditions. I could only came with the following suggestion about improving the readability:

```diff
diff --git a/pkg/operation/care/checker.go b/pkg/operation/care/checker.go
index 5166968cb..b2d04a934 100644
--- a/pkg/operation/care/checker.go
+++ b/pkg/operation/care/checker.go
@@ -271,17 +271,7 @@ func (b *HealthChecker) checkManagedResourceConditions(
 		return &c
 	}

-	var conditionProgressingTooLong, conditionHealthy bool
 	for _, cond := range mr.Status.Conditions {
-		if cond.Type == resourcesv1alpha1.ResourcesProgressing &&
-			cond.Status == gardencorev1beta1.ConditionTrue &&
-			b.managedResourceProgressingThreshold != nil &&
-			b.clock.Since(cond.LastTransitionTime.Time) >= b.managedResourceProgressingThreshold.Duration {
-			conditionProgressingTooLong = true
-		}
-		if cond.Type == resourcesv1alpha1.ResourcesHealthy && cond.Status == gardencorev1beta1.ConditionTrue {
-			conditionHealthy = true
-		}
 		checkConditionStatus, ok := conditionsToCheck[cond.Type]
 		if !ok {
 			continue
@@ -302,6 +292,14 @@ func (b *HealthChecker) checkManagedResourceConditions(
 		return &c
 	}

+	resourcesHealthyCondition := v1beta1helper.GetCondition(mr.Status.Conditions, resourcesv1alpha1.ResourcesHealthy)
+	resourcesProgressingCondition := v1beta1helper.GetCondition(mr.Status.Conditions, resourcesv1alpha1.ResourcesProgressing)
+	conditionHealthy := resourcesHealthyCondition != nil && resourcesHealthyCondition.Status == gardencorev1beta1.ConditionTrue
+	conditionProgressingTooLong := resourcesProgressingCondition != nil &&
+		resourcesProgressingCondition.Status == gardencorev1beta1.ConditionTrue &&
+		b.managedResourceProgressingThreshold != nil &&
+		b.clock.Since(resourcesProgressingCondition.LastTransitionTime.Time) >= b.managedResourceProgressingThreshold.Duration
+
 	if conditionProgressingTooLong && conditionHealthy {
 		c := b.FailedCondition(condition, gardencorev1beta1.ManagedResourceProgressingRolloutStuck, fmt.Sprintf("ManagedResource %s is progressing for more than %s", mr.Name, b.managedResourceProgressingThreshold.Duration))
 		return &c
```

It keeps the first look short and focused only on the checks from the `conditionsToCheck` map. The newly introduced check is moved afterwards.

Comment (ialidzhikov) [reply pkg/operation/care/checker.go]: Draft approach using the `conditionsToCheck` map.

```diff
diff --git a/pkg/operation/care/checker.go b/pkg/operation/care/checker.go
index 5166968cb..7296fdcc5 100644
--- a/pkg/operation/care/checker.go
+++ b/pkg/operation/care/checker.go
@@ -241,52 +241,51 @@ func (b *HealthChecker) checkNodes(condition gardencorev1beta1.Condition, nodes
 
 // CheckManagedResource checks the conditions of the given managed resource and reflects the state in the returned condition.
 func (b *HealthChecker) CheckManagedResource(condition gardencorev1beta1.Condition, mr *resourcesv1alpha1.ManagedResource) *gardencorev1beta1.Condition {
-	conditionsToCheck := map[gardencorev1beta1.ConditionType]func(status gardencorev1beta1.ConditionStatus) bool{
-		resourcesv1alpha1.ResourcesApplied: defaultSuccessfulCheck(),
-		resourcesv1alpha1.ResourcesHealthy: defaultSuccessfulCheck(),
+	conditionsToCheck := map[gardencorev1beta1.ConditionType]func(condition gardencorev1beta1.Condition) bool{
+		resourcesv1alpha1.ResourcesApplied:     defaultSuccessfulCheck(),
+		resourcesv1alpha1.ResourcesHealthy:     defaultSuccessfulCheck(),
+		resourcesv1alpha1.ResourcesProgressing: resourcesNotProgressingCheck(b.clock, b.managedResourceProgressingThreshold),
 	}
 
 	return b.checkManagedResourceConditions(condition, mr, conditionsToCheck)
 }
 
-func defaultSuccessfulCheck() func(status gardencorev1beta1.ConditionStatus) bool {
-	return func(status gardencorev1beta1.ConditionStatus) bool {
-		return status != gardencorev1beta1.ConditionFalse && status != gardencorev1beta1.ConditionUnknown
+func defaultSuccessfulCheck() func(condition gardencorev1beta1.Condition) bool {
+	return func(condition gardencorev1beta1.Condition) bool {
+		return condition.Status != gardencorev1beta1.ConditionFalse && condition.Status != gardencorev1beta1.ConditionUnknown
 	}
 }
 
-func resourcesNotProgressingCheck() func(status gardencorev1beta1.ConditionStatus) bool {
-	return func(status gardencorev1beta1.ConditionStatus) bool {
-		return status != gardencorev1beta1.ConditionTrue && status != gardencorev1beta1.ConditionUnknown
+func resourcesNotProgressingCheck(clock clock.Clock, theshold *metav1.Duration) func(gardencorev1beta1.Condition) bool {
+	return func(condition gardencorev1beta1.Condition) bool {
+		notProgressing := condition.Status != gardencorev1beta1.ConditionTrue && condition.Status != gardencorev1beta1.ConditionUnknown
+
+		if theshold != nil && !notProgressing && clock.Since(condition.LastTransitionTime.Time) < theshold.Duration {
+			// ManagedResource is progressing but the given threshold didn't pass.
+			// Hence, return that the ManagedResource is not progressing.
+			return true
+		}
+
+		return notProgressing
 	}
 }
 
 func (b *HealthChecker) checkManagedResourceConditions(
 	condition gardencorev1beta1.Condition,
 	mr *resourcesv1alpha1.ManagedResource,
-	conditionsToCheck map[gardencorev1beta1.ConditionType]func(status gardencorev1beta1.ConditionStatus) bool,
+	conditionsToCheck map[gardencorev1beta1.ConditionType]func(condition gardencorev1beta1.Condition) bool,
 ) *gardencorev1beta1.Condition {
 	if mr.Generation != mr.Status.ObservedGeneration {
 		c := b.FailedCondition(condition, gardencorev1beta1.OutdatedStatusError, fmt.Sprintf("observed generation of managed resource '%s/%s' outdated (%d/%d)", mr.Namespace, mr.Name, mr.Status.ObservedGeneration, mr.Generation))
 		return &c
 	}
 
-	var conditionProgressingTooLong, conditionHealthy bool
 	for _, cond := range mr.Status.Conditions {
-		if cond.Type == resourcesv1alpha1.ResourcesProgressing &&
-			cond.Status == gardencorev1beta1.ConditionTrue &&
-			b.managedResourceProgressingThreshold != nil &&
-			b.clock.Since(cond.LastTransitionTime.Time) >= b.managedResourceProgressingThreshold.Duration {
-			conditionProgressingTooLong = true
-		}
-		if cond.Type == resourcesv1alpha1.ResourcesHealthy && cond.Status == gardencorev1beta1.ConditionTrue {
-			conditionHealthy = true
-		}
 		checkConditionStatus, ok := conditionsToCheck[cond.Type]
 		if !ok {
 			continue
 		}
-		if !checkConditionStatus(cond.Status) {
+		if !checkConditionStatus(cond) {
 			c := b.FailedCondition(condition, cond.Reason, cond.Message)
 			return &c
 		}
@@ -302,11 +301,6 @@ func (b *HealthChecker) checkManagedResourceConditions(
 		return &c
 	}
 
-	if conditionProgressingTooLong && conditionHealthy {
-		c := b.FailedCondition(condition, gardencorev1beta1.ManagedResourceProgressingRolloutStuck, fmt.Sprintf("ManagedResource %s is progressing for more than %s", mr.Name, b.managedResourceProgressingThreshold.Duration))
-		return &c
-	}
-
 	return nil
 }
 
diff --git a/pkg/operation/care/seed_health.go b/pkg/operation/care/seed_health.go
index 7752279d2..9232415f0 100644
--- a/pkg/operation/care/seed_health.go
+++ b/pkg/operation/care/seed_health.go
@@ -144,10 +144,10 @@ func (h *SeedHealth) checkSeedSystemComponents(
 }
 
 func checkManagedResourceForSeed(checker *HealthChecker, condition gardencorev1beta1.Condition, managedResource *resourcesv1alpha1.ManagedResource) *gardencorev1beta1.Condition {
-	conditionsToCheck := map[gardencorev1beta1.ConditionType]func(status gardencorev1beta1.ConditionStatus) bool{
+	conditionsToCheck := map[gardencorev1beta1.ConditionType]func(condition gardencorev1beta1.Condition) bool{
 		resourcesv1alpha1.ResourcesApplied:     defaultSuccessfulCheck(),
 		resourcesv1alpha1.ResourcesHealthy:     defaultSuccessfulCheck(),
-		resourcesv1alpha1.ResourcesProgressing: resourcesNotProgressingCheck(),
+		resourcesv1alpha1.ResourcesProgressing: resourcesNotProgressingCheck(checker.clock, nil),
 	}
 
 	return checker.checkManagedResourceConditions(condition, managedResource, conditionsToCheck)

```

WDYT? The approach does not check the healthy condition when checking the Progressing condition. I assume we don't have to check the healthy condition. There is already a separate check for it and it makes sense to fail a Shoot condition when MR is Progressing after the allowed threshold. Am I missing something?

Comment (acumino) [reply pkg/operation/care/checker.go]: It works, I made the changes in 54eee174f8eecd8e372978edef01e3fe06c58305. My initial idea was to check both `Progressing` and `Healthy` but checking only the `Progressing` condition makes things simpler.

File: charts/gardener/gardenlet/templates/_helpers.tpl [hunk 21]
```diff
@@ -198,6 +198,9 @@ config.yaml: |
         threshold: {{ .Values.config.controllers.shootCare.staleExtensionHealthChecks.threshold }}
         {{- end }}
       {{- end }}
+      {{- if .Values.config.controllers.shootCare.managedResourceProgressingThreshold }}
+      managedResourceProgressingThreshold: {{ .Values.config.controllers.shootCare.managedResourceProgressingThreshold }}
```
Comment (ialidzhikov) [inline charts/gardener/gardenlet/templates/_helpers.tpl:202]: You could add example value to `values.yaml`:
```diff
diff --git a/charts/gardener/gardenlet/values.yaml b/charts/gardener/gardenlet/values.yaml
index 74c3ee316..2cb3b1d2c 100644
--- a/charts/gardener/gardenlet/values.yaml
+++ b/charts/gardener/gardenlet/values.yaml
@@ -99,7 +99,9 @@ config:
       syncPeriod: 30s
       staleExtensionHealthChecks:
         enabled: true
-      # threshold: 5m
+        # threshold: 5m
+      # TODO(acumino): Enable by default the check for ManagedResources stuck in Progressing state.
+      # managedResourceProgressingThreshold: 1h
       conditionThresholds:
       - type: APIServerAvailable
         duration: 1m
```

If we are confident enough with the change, you can directly enable it by default.

Comment (acumino) [reply charts/gardener/gardenlet/templates/_helpers.tpl:202]: > you can directly enable it by default.

Are you suggesting, adding defaulting for this value here https://github.com/gardener/gardener/blob/master/pkg/gardenlet/apis/config/v1alpha1/defaults.go?

Comment (ialidzhikov) [reply charts/gardener/gardenlet/templates/_helpers.tpl:202]: No.

If you add a defaulting, then the field will be always non-nil. Right now when managedResourceProgressingThreshold=nil, we assume that the check is disabled. If we add such defaulting, there will be now way to disable the check, right?

By "you can directly enable it by default." I mean to add to the values.yaml file the value uncommented. 

With the current revision of the PR, the managedResourceProgressingThreshold is not present in values.yaml. We have 2 options:
1. Add it commented as suggested in https://github.com/gardener/gardener/pull/7241#discussion_r1080953038 and enable it in controlled manner on our landscapes. When we gain experience with it, add the managedResourceProgressingThreshold field to the values file without the comment and let the check be enabled by default.
2. Directly add the managedResourceProgressingThreshold field to the values file and let the check be enabled by default.

Comment (acumino) [reply charts/gardener/gardenlet/templates/_helpers.tpl:202]: I am only worried about the correct timeout. Is one hour right or wrong? May be we can set default to 1hr and then on landscapes it can be modified. WDYT?

Comment (ialidzhikov) [reply charts/gardener/gardenlet/templates/_helpers.tpl:202]: Okay, let's go on with 1h.

File: charts/gardener/gardenlet/values.yaml [hunk 22]
```diff
@@ -99,6 +99,7 @@ config:
       syncPeriod: 30s
       staleExtensionHealthChecks:
         enabled: true
+      managedResourceProgressingThreshold: 1h
       # threshold: 5m
```
Comment (ialidzhikov) [inline charts/gardener/gardenlet/values.yaml]: The threshold field is under staleExtensionHealthChecks, hence:

```suggestion
      staleExtensionHealthChecks:
        enabled: true
      # threshold: 5m
      managedResourceProgressingThreshold: 1h
```

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Comment by rfranzke** [comment]
@shafeeqes Anything left from your side?

**Comment by ialidzhikov** [comment]
One minor thing that came to my mind is that validation can be introduced for the new field that it is a non-negative duration - ref https://github.com/gardener/gardener/blob/9a8c281dd526abac2f137674e1b9ae65b3892c65/pkg/gardenlet/apis/config/validation/validation.go#L35

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
/approve
