### PR TITLE
Validate `kubeReserved` and `systemReserved` resources against Node allocatable resources

### LINKED ISSUE #6106: Validate `kubeReserved` and `systemReserved` against the `Node`'s allocatable resources
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
Currently one can specify a kubeReserved that exceeds the Node allocatable resources. See steps to reproduce for more details.

**What you expected to happen**:
User to be not allowed to configure kubeReserved that exceeds the Node allocatable resources

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with the following kubeReserved and machine type that has only 8 CPU cores (for example `m5.2xlarge`):

```yaml
      kubeReserved:
        cpu: 9400m
        memory: 4Gi
        pid: 20k
```

2. Make sure that kubelet fails to start with (hence Nodes fail to join the cluster):

```
Jun 14 06:58:51 ip-10-250-17-68.eu-central-1.compute.internal kubelet[7198]: F0614 06:58:51.248209    7198 kubelet.go:1316] Failed to start ContainerManager invalid Node Allocatable configuration. Resource "cpu" has an allocatable of {{9400 -3} {<nil>}  DecimalSI}, capacity of {{-14
00 -3} {<nil>}  DecimalSI}
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.48.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:

This PR introduces a validation for `kubeReserved` and `systemReserved` resources against the allocatable resources of a  machine. The sum of kubeReserved and systemReserved resources (CPU, memory) for a worker should be less than the allocatable resources for the same. These reserved fields in the shoot yaml are validated against the corresponding machine type in the cloudProfile. This validation is introduced for both creation of new shoots and updation of existing shoots.

For example, now creating a shoot  with the following kubeReserved and machine type that has only 8 CPU cores (for example m5.2xlarge):
``` 
     kubeReserved:
        cpu: 9400m
        memory: 4Gi
```
gives the error:
```
Error from server (Forbidden): error when creating "90-shoot.yaml": shoots.core.gardener.cloud "shoot-aws" is forbidden: [spec.provider.workers[0].kubernetes.kubelet: Invalid value: "kubeReserved CPU + systemReserved CPU: 9400m": total reserved CPU (kubeReserved+systemReserved) cannot be more than allocatable CPU:8]
```
**Which issue(s) this PR fixes**:
Fixes #6106 

**Special notes for your reviewer**:

**Release note**:

```breaking user
The kubeReserved and systemReserved specs of workers are now validated against the node allocatable resources of the corresponding machine type.
```

### CODE REVIEW

File: plugin/pkg/shoot/validator/admission.go [hunk 1]
```diff
@@ -922,6 +926,47 @@ top:
...
+		if machineType.Name == workerMachineType {
+			allocatableCPU := machineType.CPU
+			allocatableMemory := machineType.Memory
+
+			if cmp := reservedCPU.Cmp(allocatableCPU); cmp >= 0 {
+				allErrs = append(allErrs, field.Invalid(fldPath, fmt.Sprintf("kubeReserved CPU + systemReserved CPU: %s", reservedCPU.String()), fmt.Sprintf("total reserved CPU (kubeReserved+systemReserved) cannot be more than allocatable CPU:%s", allocatableCPU.String())))
+			}
+
+			if cmp := reservedMemory.Cmp(allocatableMemory); cmp >= 0 {
+				allErrs = append(allErrs, field.Invalid(fldPath, fmt.Sprintf("kubeReserved Memory + systemReserved Memory: %s", reservedMemory.String()), fmt.Sprintf("total reserved memory (kubeReserved+systemReserved) cannot be more than allocatable memory:%s", allocatableMemory.String())))
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission.go]:
```suggestion
				allErrs = append(allErrs, field.Invalid(fldPath, fmt.Sprintf("kubeReserved memory + systemReserved memory: %s", reservedMemory.String()), fmt.Sprintf("total reserved memory (kubeReserved + systemReserved) cannot be more than the Node's allocatable memory '%s'", allocatableMemory.String())))
```

File: plugin/pkg/shoot/validator/admission.go [hunk 2]
```diff
@@ -630,22 +630,26 @@ func (c *validationContext) validateProvider(a admission.Attributes) field.Error
...
 			allErrs = append(allErrs, field.Invalid(idxPath.Child("volume", "size"), worker.Volume.VolumeSize, fmt.Sprintf("size must be >= %s", minSize)))
 		}
-
-		if worker.Kubernetes != nil && worker.Kubernetes.Version != nil {
-			oldWorkerKubernetesVersion := c.oldShoot.Spec.Kubernetes.Version
-			if oldWorker.Kubernetes != nil && oldWorker.Kubernetes.Version != nil {
-				oldWorkerKubernetesVersion = *oldWorker.Kubernetes.Version
+		if worker.Kubernetes != nil {
+			if worker.Kubernetes.Kubelet != nil {
+				allErrs = append(allErrs, validateKubeletConfig(idxPath.Child("kubernetes").Child("kubelet"), c.cloudProfile.Spec.MachineTypes, worker.Machine.Type, worker.Kubernetes.Kubelet)...)
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission.go]: There is also the following case - the kubeletConfig can be also specified on a global level under `.spec.kubernetes.kubeletConfig`. For now in this PR we only validate the kubeletConfig that is specified on Worker pool level. We also have to consider the global kubeletConfig - IIRC the pattern is that kubeletConfig can be specified on a global level and can be overwritten on worker pool level (otherwise the global kubeletConfig values will apply).

File: plugin/pkg/shoot/validator/admission.go [hunk 3]
```diff
@@ -922,6 +926,47 @@ top:
...
+		}
+	}
+
+	for _, machineType := range machineTypes {
+		if machineType.Name == workerMachineType {
+			allocatableCPU := machineType.CPU
+			allocatableMemory := machineType.Memory
+
+			if cmp := reservedCPU.Cmp(allocatableCPU); cmp >= 0 {
+				allErrs = append(allErrs, field.Invalid(fldPath, fmt.Sprintf("kubeReserved CPU + systemReserved CPU: %s", reservedCPU.String()), fmt.Sprintf("total reserved CPU (kubeReserved+systemReserved) cannot be more than allocatable CPU:%s", allocatableCPU.String())))
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission.go]:
```suggestion
				allErrs = append(allErrs, field.Invalid(fldPath, fmt.Sprintf("kubeReserved CPU + systemReserved CPU: %s", reservedCPU.String()), fmt.Sprintf("total reserved CPU (kubeReserved+systemReserved) cannot be more than the Node's allocatable CPU '%s'", allocatableCPU.String())))
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 4]
```diff
@@ -1566,6 +1566,132 @@ var _ = Describe("validator", func() {
...
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeForbiddenError())
+					Expect(err.Error()).To(ContainSubstring("total reserved memory (kubeReserved+systemReserved) cannot be more than allocatable memory"))
+				})
+
+				It("should not allow updation of Shoot if reservedCPU is more than allocatable CPU", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should not allow update of Shoot if reservedCPU is more than allocatable CPU", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 5]
```diff
@@ -1566,6 +1566,132 @@ var _ = Describe("validator", func() {
...
+
+					attrs := admission.NewAttributesRecord(&shoot, oldShoot, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Update, &metav1.UpdateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeForbiddenError())
+					Expect(err.Error()).To(ContainSubstring("total reserved CPU (kubeReserved+systemReserved) cannot be more than allocatable CPU"))
+				})
+
+				It("should not allow updation of Shoot if reservedMemory is more than allocatable Memory", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should not allow update of Shoot if reservedMemory is more than allocatable Memory", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 6]
```diff
@@ -1566,6 +1566,132 @@ var _ = Describe("validator", func() {
...
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeForbiddenError())
+					Expect(err.Error()).To(ContainSubstring("total reserved memory (kubeReserved+systemReserved) cannot be more than allocatable memory"))
+				})
+
+				It("should not allow updation of Shoot if reservedCPU is more than allocatable CPU", func() {
+					oldShoot := shoot.DeepCopy()
+					worker.Kubernetes.Kubelet.KubeReserved.CPU = &resourceCPU2
+					worker.Kubernetes.Kubelet.KubeReserved.Memory = &resourceMemory2
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]: Seems to be not needed for the purposes of the test

```suggestion
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 7]
```diff
@@ -1566,6 +1566,132 @@ var _ = Describe("validator", func() {
...
+					worker.Kubernetes.Kubelet.SystemReserved.CPU = &resourceCPU2
+					worker.Kubernetes.Kubelet.SystemReserved.Memory = &resourceMemory2
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]: Seems to be not needed for the purposes of the test

```suggestion
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 8]
```diff
@@ -1566,6 +1566,132 @@ var _ = Describe("validator", func() {
...
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeForbiddenError())
+					Expect(err.Error()).To(ContainSubstring("total reserved CPU (kubeReserved+systemReserved) cannot be more than allocatable CPU"))
+				})
+
+				It("should not allow updation of Shoot if reservedMemory is more than allocatable Memory", func() {
+					oldShoot := shoot.DeepCopy()
+					worker.Kubernetes.Kubelet.KubeReserved.CPU = &resourceCPU2
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]: Seems to be not needed for the purposes of the test

```suggestion
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 9]
```diff
@@ -1566,6 +1566,132 @@ var _ = Describe("validator", func() {
...
+					worker.Kubernetes.Kubelet.KubeReserved.Memory = &resourceMemory2
+					worker.Kubernetes.Kubelet.SystemReserved.CPU = &resourceCPU2
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]: Seems to be not needed for the purposes of the test

```suggestion
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 10]
```diff
@@ -1566,6 +1566,132 @@ var _ = Describe("validator", func() {
...
+					}
+
+					cloudProfile.Spec.MachineTypes = append(cloudProfile.Spec.MachineTypes, machineType)
+
+					Expect(coreInformerFactory.Core().InternalVersion().Projects().Informer().GetStore().Add(&project)).To(Succeed())
+					Expect(coreInformerFactory.Core().InternalVersion().CloudProfiles().Informer().GetStore().Add(&cloudProfile)).To(Succeed())
+					Expect(coreInformerFactory.Core().InternalVersion().Seeds().Informer().GetStore().Add(&seed)).To(Succeed())
+				})
+
+				It("should allow creation of Shoot if reserved resources are less than allocatable resources", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]: Can we also add tests cases when:
1. kubeReserved itself on its own is >= than Node's allocatable
1. systemReserved itself on its own is >= than Node's allocatable
1. kubeReserved + systemReserved is >= than Node's allocatable - already exists

File: plugin/pkg/shoot/validator/admission.go [hunk 11]
```diff
@@ -630,22 +630,26 @@ func (c *validationContext) validateProvider(a admission.Attributes) field.Error
 		if ok, minSize := validateVolumeSize(c.cloudProfile.Spec.VolumeTypes, c.cloudProfile.Spec.MachineTypes, worker.Machine.Type, worker.Volume); !ok {
 			allErrs = append(allErrs, field.Invalid(idxPath.Child("volume", "size"), worker.Volume.VolumeSize, fmt.Sprintf("size must be >= %s", minSize)))
 		}
-
-		if worker.Kubernetes != nil && worker.Kubernetes.Version != nil {
-			oldWorkerKubernetesVersion := c.oldShoot.Spec.Kubernetes.Version
-			if oldWorker.Kubernetes != nil && oldWorker.Kubernetes.Version != nil {
-				oldWorkerKubernetesVersion = *oldWorker.Kubernetes.Version
+		if worker.Kubernetes != nil {
+			if worker.Kubernetes.Kubelet != nil {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission.go:640]: Just for awareness for the future (out of score of this PR) we could try to implement a validation about the ephemeral-storage (out CloudProfile does not have information about it  but in the future we could validate the volume size against the kubeReserved for ephemeral storage. But let's for now leave this out of scope of this PR.

**Review by ialidzhikov — COMMENTED** [review]
With @plkokanov we had a joint review.

File: plugin/pkg/shoot/validator/admission.go (hunk 2 above)
Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission.go]: Sorry, I had missed it, thanks!

File: plugin/pkg/shoot/validator/admission.go [hunk 12]
```diff
@@ -926,6 +933,52 @@ top:
...
+			reservedMemory.Add(*kubeletConfig.SystemReserved.Memory)
+		}
+	}
+
+	for _, machineType := range machineTypes {
+		if machineType.Name == workerMachineType {
+			allocatableCPU := machineType.CPU
+			allocatableMemory := machineType.Memory
+
+			if cmp := reservedCPU.Cmp(allocatableCPU); cmp >= 0 {
```
Comment (plkokanov) [inline plugin/pkg/shoot/validator/admission.go]: Why do we also return an error if the `reservedCPU` has the same value as the `allocatableCPU` (same for `reservedMemory` and `allocatableMemory`?

File: plugin/pkg/shoot/validator/admission_test.go [hunk 13]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+					shoot.Spec.Provider.Workers = append(shoot.Spec.Provider.Workers, worker)
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeNil())
+				})
+
+				It("should not throw any errors if both global and worker kubeletConfigs are nil", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should allow creation of Shoot if both global and worker kubeletConfigs are nil", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 14]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+					worker.Kubernetes.Kubelet = nil
+					shoot.Spec.Provider.Workers = append(shoot.Spec.Provider.Workers, worker)
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeNil())
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]: Any reason to not use

```suggestion
					Expect(err).ToNot(HaveOccurred())
```

?

File: plugin/pkg/shoot/validator/admission_test.go [hunk 15]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+					kubeletConfig.SystemReserved.CPU = &resourceCPU2
+					shoot.Spec.Kubernetes.Kubelet = kubeletConfig
+
+					shoot.Spec.Provider.Workers = append(shoot.Spec.Provider.Workers, worker)
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeNil())
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]: Any reason to not use

```suggestion
					Expect(err).ToNot(HaveOccurred())
```

?

File: plugin/pkg/shoot/validator/admission_test.go [hunk 16]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeForbiddenError())
+					Expect(err.Error()).To(ContainSubstring("total reserved CPU (kubeReserved + systemReserved) cannot be more than the Node's allocatable CPU"))
+				})
+
+				It("should allow creation of Shoot if reserved CPU in the global kubeletConfig is more than allocatable CPU but the worker kubeletConfig have lesser reserved CPU", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should allow creation of Shoot if reserved CPU in the global kubeletConfig is more than allocatable CPU but the worker kubeletConfig has lesser reserved CPU", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 17]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+					shoot.Spec.Provider.Workers = append(shoot.Spec.Provider.Workers, worker)
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeNil())
+				})
+
+				It("should not allow creation of Shoot if reserved CPU in the global kubeletConfig is less than allocatable CPU but the worker kubeletConfig have more reserved CPU", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should not allow creation of Shoot if reserved CPU in the global kubeletConfig is less than allocatable CPU but the worker kubeletConfig has more reserved CPU", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 18]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+					kubeletConfig.SystemReserved.Memory = &resourceMemory2
+					shoot.Spec.Kubernetes.Kubelet = kubeletConfig
+
+					shoot.Spec.Provider.Workers = append(shoot.Spec.Provider.Workers, worker)
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeNil())
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]: Any reason to not use

```suggestion
					Expect(err).ToNot(HaveOccurred())
```

?

File: plugin/pkg/shoot/validator/admission_test.go [hunk 19]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+				})
+
+				It("should not allow creation of Shoot if reserved memory in the global kubeletConfig is less than allocatable memory but the worker kubeletConfig have more reserved memory", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should not allow creation of Shoot if reserved memory in the global kubeletConfig is less than allocatable memory but the worker kubeletConfig has more reserved memory", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 20]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeForbiddenError())
+					Expect(err.Error()).To(ContainSubstring("total reserved memory (kubeReserved + systemReserved) cannot be more than the Node's allocatable memory"))
+				})
+
+				It("should not allow creation of Shoot if kubeReserved Memory is more than allocatable Memory", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should not allow creation of Shoot if kubeReserved memory is more than allocatable memory", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 21]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeForbiddenError())
+					Expect(err.Error()).To(ContainSubstring("total reserved memory (kubeReserved + systemReserved) cannot be more than the Node's allocatable memory"))
+				})
+
+				It("should not allow creation of Shoot if systemReserved Memory is more than allocatable Memory", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should not allow creation of Shoot if systemReserved Memory is more than allocatable memory", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 22]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeForbiddenError())
+					Expect(err.Error()).To(ContainSubstring("total reserved memory (kubeReserved + systemReserved) cannot be more than the Node's allocatable memory"))
+				})
+
+				It("should not allow creation of Shoot if sum of kubeReserved and systemReserved Memory is more than allocatable Memory", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should not allow creation of Shoot if sum of kubeReserved and systemReserved memory is more than allocatable memory", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 23]
```diff
@@ -1562,6 +1562,303 @@ var _ = Describe("validator", func() {
...
+
+					attrs := admission.NewAttributesRecord(&shoot, oldShoot, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Update, &metav1.UpdateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeForbiddenError())
+					Expect(err.Error()).To(ContainSubstring("total reserved CPU (kubeReserved + systemReserved) cannot be more than the Node's allocatable CPU"))
+				})
+
+				It("should not allow update of Shoot if reserved memory is more than allocatable Memory", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should not allow update of Shoot if reserved memory is more than allocatable memory", func() {
```

File: plugin/pkg/shoot/validator/admission.go [hunk 24]
```diff
@@ -634,22 +635,28 @@ func (c *validationContext) validateProvider(a admission.Attributes) field.Error
...
+				kubeletConfig = worker.Kubernetes.Kubelet
 			}
-			ok, isDefaulted, validKubernetesVersions, versionDefault := validateKubernetesVersionConstraints(c.cloudProfile.Spec.Kubernetes.Versions, *worker.Kubernetes.Version, oldWorkerKubernetesVersion)
-			if !ok {
-				err := field.NotSupported(idxPath.Child("kubernetes", "version"), worker.Kubernetes.Version, validKubernetesVersions)
-				if isDefaulted {
-					err.Detail = fmt.Sprintf("unable to default version - couldn't find a suitable patch version for %s. Suitable patch versions have a non-expired expiration date and are no 'preview' versions. 'Preview'-classified versions have to be selected explicitly -  %s", *worker.Kubernetes.Version, err.Detail)
+			allErrs = append(allErrs, validateKubeletConfig(idxPath.Child("kubernetes").Child("kubelet"), c.cloudProfile.Spec.MachineTypes, worker.Machine.Type, kubeletConfig)...)
+
+			if worker.Kubernetes.Version != nil {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission.go:645]: It looks like the Shoot creation in the e2e tests fails with:

```
              Message: "shoots.core.gardener.cloud \"e2e-default\" is forbidden: [spec.provider.workers[1].kubernetes.kubelet: Invalid value: \"kubeReserved memory + systemReserved memory: 1Gi\": total reserved memory (kubeReserved + systemReserved) cannot be more than the Node's allocatable memory '1Gi' spec.provider.workers[2].kubernetes.kubelet: Invalid value: \"kubeReserved memory + systemReserved memory: 1Gi\": total reserved memory (kubeReserved + systemReserved) cannot be more than the Node's allocatable memory '1Gi']",
```

We should default the kubeReserved.memory to `1Gi`. @timebertt @rfranzke can you point us to the `local` CloudProfile that is used in the e2e tests. What's the allocatable for the corresponding machine type?

Comment (rfranzke) [reply plugin/pkg/shoot/validator/admission.go:645]: https://github.com/gardener/gardener/blob/2eb54485231408cbdbabaa49812572a07124364f/example/provider-local/garden/base/cloudprofile.yaml#L18-L22

Comment (ialidzhikov) [reply plugin/pkg/shoot/validator/admission.go:645]: Hm, how this worked so far with 1Gi allocatable and Shoot that reserved 1Gi for the kubelet?

Comment (plkokanov) [reply plugin/pkg/shoot/validator/admission.go:645]: Isn't that actually because of what I commented here: https://github.com/gardener/gardener/pull/6198#discussion_r908418709

Comment (ialidzhikov) [reply plugin/pkg/shoot/validator/admission.go:645]: I am not sure. The should be plenty of Shoot system components that have to be scheduled and running. Even if kubelet starts there should not be any allocatable memory to run the system components. Or does the value in the CloudProfile does not reflect the real machine memory?

File: plugin/pkg/shoot/validator/admission_test.go (hunk 15 above)
Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission_test.go]: No reason, Just that the Admit function returns a nil if there isn't error. I can change it if you want.

File: plugin/pkg/shoot/validator/admission.go (hunk 12 above)
Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission.go]: It doesn't help if the total reserved resource takes up the whole allocatable resource as well, right?

File: plugin/pkg/shoot/validator/admission.go (hunk 24 above)
Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission.go:644]: Where is this `kubeReserved` for the e2e tests configured? I couldn't find anything here.
https://github.com/gardener/gardener/blob/8885108b020f97a224d61ab46e1a3e209177f2d5/test/e2e/shoot/common.go#L55-L93

Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission.go:645]: @timebertt could you help with this?

**Comment by shafeeqes** [comment]
> @shafeeqes: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-unit	[ec47987](https://github.com/gardener/gardener/commit/ec479873035ff5fcf097d2fca2253f0b68524772)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6198/pull-gardener-unit/1542445830353457152)	true	`/test pull-gardener-unit`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=6198). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Ashafeeqes). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener).

~~That is weird, the unit tests pass locally for me without any issues.~~
After rebase, it started failing locally as well, fixing it.

File: plugin/pkg/shoot/validator/admission.go (hunk 24 above)
Comment (voelzmo) [reply plugin/pkg/shoot/validator/admission.go:645]: I think nodes started in the local setup have a much larger capacity than the `machineType` suggests. Here's what I get on my system for `k describe node <nodename>`
```
Capacity:
  cpu:                6
  ephemeral-storage:  140105160Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             6086504Ki
  pods:               110
Allocatable:
  cpu:                5920m
  ephemeral-storage:  136294299542
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             4935528Ki
  pods:               110
```

So in total it has 6GiB and of that 4.7GiB is allocatable.

Which is in line with what I configured in Docker Desktop
Screenshot 2022-07-01 at 16 22 14

File: example/provider-local/garden/base/cloudprofile.yaml [hunk 25]
```diff
@@ -18,7 +18,7 @@ spec:
   machineTypes:
   - cpu: "1"
     gpu: "0"
-    memory: 1Gi
+    memory: 8Gi
```
Comment (voelzmo) [inline example/provider-local/garden/base/cloudprofile.yaml:23]: I understand this makes the validation pass, but we are aware that this may or may not be the truth, right? Should we add a comment to the `machineType` to help the next person stumbling across this? @timebertt?

File: plugin/pkg/shoot/validator/admission.go [hunk 26]
```diff
@@ -930,6 +937,52 @@ top:
...
+			reservedCPU.Add(*kubeletConfig.SystemReserved.CPU)
+		}
+		if kubeletConfig.SystemReserved.Memory != nil {
+			reservedMemory.Add(*kubeletConfig.SystemReserved.Memory)
+		}
+	}
+
+	for _, machineType := range machineTypes {
+		if machineType.Name == workerMachineType {
+			allocatableCPU := machineType.CPU
```
Comment (voelzmo) [inline plugin/pkg/shoot/validator/admission.go]: Can we rename this from `allocatable` to `capacity`?
Technically, `allocatable` [has a defined meaning](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#node-allocatable): It is the amount that is available for Pods. I think what you're doing here is checking against the `capacity` and ensure that `allocatable` cannot be 0 – because `allocatable = capacity - reserved`.

This renaming should also be reflected in the error messages and tests below.

File: plugin/pkg/shoot/validator/admission_test.go [hunk 27]
```diff
@@ -1567,6 +1567,305 @@ var _ = Describe("validator", func() {
 				})
 			})
 
+			Context("kubelet config checks", func() {
+				var (
+					worker          core.Worker
+					resourceCPU1    = resource.MustParse("2")
```
Comment (voelzmo) [inline plugin/pkg/shoot/validator/admission_test.go:1573]: I think `resourceCPU1` and `resourceCPU2` have specific semantics: One is "enough capacity", the other is "insufficient capacity" – can we reflect this in the names, so it becomes clear when reading the tests without looking up the specific values?
The same applies to the memory variables as well.

**Review by voelzmo — CHANGES_REQUESTED** [review]
Thanks for adding the validation, just a few smaller comments.

File: plugin/pkg/shoot/validator/admission_test.go (hunk 27 above)
Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission_test.go:1573]: Hmm.. but these are not capacity, like, I'm just using two values each to create more and less `kubeReserved` and `systemReserved` resources. And we have cases where they add up and exceed the capacity or exceed the capacity by themselves. I'm not sure renaming them to enough and insufficient will make things clear in this case.

File: plugin/pkg/shoot/validator/admission.go (hunk 26 above)
Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission.go]: addressed in gardener@e6dd39c

File: example/provider-local/garden/base/cloudprofile.yaml (hunk 25 above)
Comment (shafeeqes) [reply example/provider-local/garden/base/cloudprofile.yaml:23]: How about
```yaml
  # These values do not represent the actual machine capacity. The actual
  # capacity of the machine depends on your docker resource allocation. 
```

File: plugin/pkg/shoot/validator/admission.go (hunk 24 above)
Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission.go:645]: Yes, @voelzmo. You are right. The values in the cloudprofile are just dummy values.

File: plugin/pkg/shoot/validator/admission_test.go (hunk 27 above)
Comment (voelzmo) [reply plugin/pkg/shoot/validator/admission_test.go:1573]: You're right, we're also having the scenarios where only the sum of the two reservations is too high, while both values alone are perfectly fine – I didn't think this through entirely.

My initial goal was to make the tests more readable without having to look up the individual values and compare them to the worker's capacity in the test – if we cannot have variable names that are helpful, maybe we should just inline the values, so the tests become more clear?

By now, I'm leaving this up to you: If you feel this doesn't add to the tests readability, it's fine to leave this as-is.

Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission_test.go:1573]: >  if we cannot have variable names that are helpful, maybe we should just inline the values, so the tests become more clear?

I can do that, yes.

Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission_test.go:1573]: Okay, now I checked the same, the CPU and Memory fields are taking pointers to `resource.Quantity`, so we would have to assign them to variables.

Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission_test.go:1573]: > My initial goal was to make the tests more readable without having to look up the individual values and compare them to the worker's capacity in the test

Yes, got it. I guess we can leave it as it is, given the above reason and we have used simple values like 2, 3 etc. It should not be too hard to follow.

**Review by voelzmo — APPROVED** [review]
/lgtm

File: plugin/pkg/shoot/validator/admission_test.go [hunk 28]
```diff
@@ -1567,6 +1567,305 @@ var _ = Describe("validator", func() {
...
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeForbiddenError())
+					Expect(err.Error()).To(ContainSubstring("total reserved memory (kubeReserved + systemReserved) cannot be more than the Node's memory capacity"))
+				})
+
+				It("should not allow creation of Shoot if systemReserved Memory is more than memory capacity", func() {
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
				It("should not allow creation of Shoot if systemReserved memory is more than memory capacity", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 29]
```diff
@@ -1567,6 +1567,305 @@ var _ = Describe("validator", func() {
...
+				})
+
+				It("should allow creation of Shoot if reserved resources are less than resource capacity", func() {
+					shoot.Spec.Provider.Workers = append(shoot.Spec.Provider.Workers, worker)
+
+					attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+
+					err := admissionHandler.Admit(context.TODO(), attrs, nil)
+
+					Expect(err).To(BeNil())
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
					Expect(err).ToNot(HaveOccurred())
```

**Review by ialidzhikov — COMMENTED** [review]
Cosmetic nits, otherwise lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm
