### PR TITLE
When defaulting and maintaining OS version, prefer older and supported version over newer but deprecated

### LINKED ISSUE #4324: OS version for a shoot is defaulted to newer but deprecated version when older but supported is available.
**How to categorize this issue?**

/kind bug
/priority 2
/assign

**What happened**:
A shoot cluster was created with empty OS version. The gardener API has defaulted it to newer but deprecated version when older and supported one is available.

**What you expected to happen**:
To not default worker pool to a deprecated OS version.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cloud profile with the following machineImages spec
```yaml
  machineImages:
  - name: gardenlinux
    versions:
    - classification: preview
      version: 318.8.0
    - classification: deprecated
      expirationDate: '2021-08-31T23:59:59Z'
      version: 318.4.0
    - classification: supported
      version: 184.0.0
```

Create a shoot or add a worker pool to existing shoot with the following spec
```yaml
    - machine:
        image:
          name: gardenlinux
```

Check that the worker os version for this worker pool is set to use the deprecated `318.4.0` instead of the supported `184.0.0`.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.26.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area ops-productivity
/kind bug
/merge squash

**What this PR does / why we need it**:
Fix a bug that 
- API server defaults the OS version to higher and deprecated one when there is still  lowed but supported one.
- shoot maintenance controller is not updating to higher but deprecated versions. 

**Which issue(s) this PR fixes**:
Fixes #4324 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
A bug that the shoot maintenance controller was upgrading the OS version to higher but deprecated version instead of using lower and supported has been fixed.
```

```bugfix operator
A bug that the OS version of worker pool is defaulted to higher and deprecated version instead of lower and supported is now fixed.
```

### CODE REVIEW

File: pkg/apis/core/helper/helpers.go [hunk 1]
```diff
@@ -90,18 +97,22 @@ func DetermineLatestMachineImageVersion(versions []core.MachineImageVersion, fil
 	return core.MachineImageVersion{}, fmt.Errorf("the latest machine version has been removed")
 }
 
-// DetermineLatestExpirableVersion determines the latest ExpirableVersion from a slice of ExpirableVersions
-// when filterPreviewVersions is set, versions with classification preview are not considered
-func DetermineLatestExpirableVersion(versions []core.ExpirableVersion, filterPreviewVersions bool) (core.ExpirableVersion, error) {
+// DetermineLatestExpirableVersion determines the latest and latest non-deprecated version from a slice of ExpirableVersions.
```
Comment (rfranzke) [inline pkg/apis/core/helper/helpers.go]:
```suggestion
// DetermineLatestExpirableVersion determines the latest expirable version and the latest non-deprecated version from a slice of ExpirableVersions.
```

File: pkg/apis/core/helper/helpers.go [hunk 2]
```diff
@@ -90,18 +97,22 @@ func DetermineLatestMachineImageVersion(versions []core.MachineImageVersion, fil
...
+// When filterPreviewVersions is set, versions with classification preview are not considered.l
```
Comment (rfranzke) [inline pkg/apis/core/helper/helpers.go]:
```suggestion
// When filterPreviewVersions is set, versions with classification preview are not considered.
```

File: pkg/apis/core/helper/helpers.go [hunk 3]
```diff
@@ -73,14 +73,21 @@ func DetermineLatestMachineImageVersions(images []core.MachineImage) (map[string
...
-	latestVersion, err := DetermineLatestExpirableVersion(ToExpirableVersions(versions), filterPreviewVersions)
+	latestVersion, latestNonDeprecatedVersion, err := DetermineLatestExpirableVersion(ToExpirableVersions(versions), filterPreviewVersions)
 	if err != nil {
 		return core.MachineImageVersion{}, err
 	}
 
+	for _, version := range versions {
+		if version.Version == latestNonDeprecatedVersion.Version {
+			return version, nil
+		}
```
Comment (rfranzke) [inline pkg/apis/core/helper/helpers.go:89]: Merge this into below `for` loop instead of looping again?

**Review by rfranzke — CHANGES_REQUESTED** [review]

File: pkg/apis/core/helper/helpers.go (hunk 3 above)
Comment (vpnachev) [reply pkg/apis/core/helper/helpers.go:89]: Then it will be again possible `deprecated` version to be preferred over `supported` one. 
I have added a test to catch this.

Comment (vpnachev) [reply pkg/apis/core/helper/helpers.go:89]: Basically, this is possible when the `deprecated` version is earlier in the `versions` slice, so it will be visited first and returned immediately.

**Comment by vpnachev** [comment]
/hold

The defaulting is working as expected. 
Maintenance controller however seems to be not fixed.

**Comment by vpnachev** [comment]
The maintenance controller is now fixed, too.
/unhold
/squash

File: pkg/apis/core/helper/helpers.go (hunk 3 above)
Comment (rfranzke) [reply pkg/apis/core/helper/helpers.go:89]: Understood, makes sense, thanks!

Comment (rfranzke) [reply pkg/apis/core/helper/helpers.go:89]: Maybe you can add a comment about this to prevent that somebody refactors this unintentionally in the future :)

Comment (vpnachev) [reply pkg/apis/core/helper/helpers.go:89]: Done with https://github.com/gardener/gardener/pull/4327/commits/16d44eed2fcb00d135cdb58754aee79df6e051ac.

**Review by rfranzke — APPROVED** [review]
/lgtm
