### PR TITLE
Extend the SeedPredicate of `controllerregistration` controller

### LINKED ISSUE #7732: `Controller{Installation,Registration}` is not reconciled when `Seed` spec is updated
**How to categorize this issue?**

/area quality
/kind enhancement

**What happened**:
The controllerinstallation controller is passing the following values for the extension chart - ref https://github.com/gardener/gardener/blob/9a2c97ef73768342f53a1d3db84de69c8723bc12/pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go#L188-L215. It is passing many values depending on the Seed spec and it is passing the Seed spec itself. There are extension charts that rely on the Seed spec or values coming from the Seed spec. Example - https://github.com/ialidzhikov/gardener-extension-provider-aws/blob/4793018f4a43581bdbb8988f47e3e040dfd1f004/charts/gardener-extension-provider-aws/templates/service.yaml#L15

Updating the Seed spec does not trigger reconciliation for the Controller{Installation,Registration}. See https://github.com/gardener/gardener-extension-provider-aws/pull/703#discussion_r1138688247

**What you expected to happen**:
Updating the Seed spec to trigger reconciliation for the Controller{Installation,Registration}

**How to reproduce it (as minimally and precisely as possible)**:
See https://github.com/gardener/gardener-extension-provider-aws/pull/703#discussion_r1138688247

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.67.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:
This PR enhances the SeedPredicate of the `controllerregistration` controller to return true if there is a change in spec, labels or annotations.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/7732

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/controllermanager/controller/controllerregistration/seed/add.go [hunk 1]
```diff
@@ -124,7 +124,8 @@ func (r *Reconciler) SeedPredicate() predicate.Predicate {
 			}
 
 			return !apiequality.Semantic.DeepEqual(oldSeed.Spec.DNS.Provider, seed.Spec.DNS.Provider) ||
-				seed.DeletionTimestamp != nil
+				seed.DeletionTimestamp != nil ||
+				topologyAwareRoutingSettingsHasChanged(oldSeed.Spec.Settings, seed.Spec.Settings)
```
Comment (rfranzke) [inline pkg/controllermanager/controller/controllerregistration/seed/add.go]: While this fixes the specific problem, I think we should rather change the predicate such that it returns `true` whenever
- deletion timestamp is set
- labels change
- annotations change
- spec changes

The reason is that we provide this information when installing the Helm charts https://github.com/gardener/gardener/blob/1278a323d19c5aaae0eed120024960beefa685fe/pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go#L201-L218

Hence, any extension could rely on any field in these structs, just like it happened now for the topology-aware routing setting.

**Review by rfranzke — CHANGES_REQUESTED** [review]

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
