### PR TITLE
Fix wrongfully added  `keep-after-project-deletion` annotation

### LINKED ISSUE #5192: `keep-after-project-deletion` annotation is wrongly added to the Project Namespace
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
`namespace.gardener.cloud/keep-after-project-deletion: "true"` is wrongly added to the Project namespace on Project creation that requests a new Namespace.

**What you expected to happen**:
`namespace.gardener.cloud/keep-after-project-deletion: "true"` to be not added to the Project Namespace.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Project that requests a new Namespace (make sure that the project `garden-foo` does not exist)

```yaml
---
apiVersion: core.gardener.cloud/v1beta1
kind: Project
metadata:
  name: foo
spec:
  owner:
    apiGroup: rbac.authorization.k8s.io
    kind: User
    name: john.doe@example.com
  members:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: alice.doe@example.com
    role: admin
  namespace: garden-foo
```

2. Make sure that the `namespace.gardener.cloud/keep-after-project-deletion: "true"` annotation is wrongly added to the newly created Namespace.

```
$ k get ns garden-foo -o jsonpath="{.metadata.annotations}"
{"namespace.gardener.cloud/keep-after-project-deletion":"true","namespace.gardener.cloud/project":"2be8076c-68d0-4a83-a1aa-d414a83168b8"}
```

3. Make sure the Project deletion does not delete the namespace and it "leaks"

```
$ ./hack/usage/delete project foo

$ k get project foo
Error from server (NotFound): projects.core.gardener.cloud "foo" not found

$ k get ns garden-foo
NAME         STATUS   AGE
garden-foo   Active   9m14s
```

4. Create Project `foo` once again

5. Make sure that it is Failed state because of the previously "leaked" Namespace (that now does not have the project labels):

```
$ k describe project foo

Events:
  Type     Reason                    Age                From                         Message
  ----     ------                    ----               ----                         -------
  Warning  NamespaceReconcileFailed  3s (x13 over 24s)  gardener-controller-manager  namespace cannot be used as it needs the project labels map[string]string{"gardener.cloud/role":"project", "project.gardener.cloud/name":"foo"}
```

**Anything else we need to know?**:
I was not able to reproduce the issue against a Gardener landscape. But it is always reproducible locally.

**Environment**:

- Gardener version: v1.38.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area quality
/kind bug

**Which issue(s) this PR fixes**:
Fixes #5192

**Special notes for your reviewer**:
CC - @ialidzhikov 

**Release note**:

```bugfix operator
An issue causing the `namespace.gardener.cloud/keep-after-project-deletion="true"` annotation to be wrongly added to the Project Namespace when the Project controller does not adopt existing Project Namespace is now fixed.
```

### CODE REVIEW

**Review by ialidzhikov — COMMENTED** [review]
I see `c.Status().Patch()` is being used in bunch of places in gardener/gardener. To me this PR does not provide any useful information/explanation why exactly this status patch does not work but all of the others work.

**Comment by timebertt** [comment]
> I see `c.Status().Patch()` is being used in bunch of places in gardener/gardener. To me this PR does not provide any useful information/explanation why exactly this status patch does not work but all of the others work.

Same for me. I'm not sure, if I understand, how the change fixes the linked issue.

**Comment by acumino** [comment]
The issue seems to be the same as 2nd point mentioned here [ #5295 (comment).](https://github.com/gardener/gardener/issues/5295#issuecomment-1017415479)

In the project controller also there are consecutive updates https://github.com/gardener/gardener/blob/31b8385f6fbae62af46e18f9c55a6e7624cec16e/pkg/controllermanager/controller/project/project_control_reconcile.go#L107-L151

**Comment by acumino** [comment]
> I see `c.Status().Patch()` is being used in bunch of places in gardener/gardener. To me this PR does not provide any useful information/explanation why exactly this status patch does not work but all of the others work.

The issue seems to be the same as 2nd point mentioned here [ #5295 (comment).](https://github.com/gardener/gardener/issues/5295#issuecomment-1017415479)

In the project controller also there are consecutive updates https://github.com/gardener/gardener/blob/31b8385f6fbae62af46e18f9c55a6e7624cec16e/pkg/controllermanager/controller/project/project_control_reconcile.go#L107-L151

**Comment by timebertt** [comment]
> The issue seems to be the same as 2nd point mentioned here [ #5295 (comment).](https://github.com/gardener/gardener/issues/5295#issuecomment-1017415479)

How is that related to https://github.com/gardener/gardener/issues/5192?

> In the project controller also there are consecutive updates

These consecutive updates will have the most recent state in-memory, so there will not be any stale cache read problems... 🤔

**Comment by BeckerMax** [comment]
We updated our findings in the issue https://github.com/gardener/gardener/issues/5192#issuecomment-1024129825 based on that @acumino will work on an updated PR

File: pkg/controllermanager/controller/project/project_control.go [hunk 1]
```diff
@@ -112,7 +112,7 @@ func (r *projectReconciler) Reconcile(ctx context.Context, request reconcile.Req
 		return r.delete(ctx, project, r.gardenClient.Client(), r.gardenClient.Client())
```
Comment (rfranzke) [inline pkg/controllermanager/controller/project/project_control.go]: Use `APIReader` here as well

**Review by rfranzke — CHANGES_REQUESTED** [review]

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by acumino** [comment]
/title Add `keep-after-project-deletion` annotation to project namespace only if the namespace creation is triggered by the project

File: pkg/apis/core/v1beta1/constants/types_constants.go [hunk 2]
```diff
@@ -499,6 +499,10 @@ const (
 	// should not be deleted if the corresponding `Project` gets deleted. Please note that all project related labels
 	// from the namespace will be removed when the project is being deleted.
 	NamespaceKeepAfterProjectDeletion = "namespace.gardener.cloud/keep-after-project-deletion"
+	// NamespaceCreatedByProject is a constant for annotation on a `Namespace` resource that states that it
+	// was created by the project because either the user didn't specify the namespace in the project `spec.Namespace`
+	// or the specified namespace was not present.
+	NamespaceCreatedByProject = "namespace.gardener.cloud/created-by-project"
```
Comment (ialidzhikov) [inline pkg/apis/core/v1beta1/constants/types_constants.go]: I would rather vote to rename the annotation to `namespace.gardener.cloud/created-by-project-controller` to clearly indicate the "author" of the create operation.

```suggestion
	NamespaceCreatedByProjectController = "namespace.gardener.cloud/created-by-project-controller"
```

File: pkg/apis/core/v1beta1/constants/types_constants.go [hunk 3]
```diff
@@ -499,6 +499,10 @@ const (
 	// should not be deleted if the corresponding `Project` gets deleted. Please note that all project related labels
 	// from the namespace will be removed when the project is being deleted.
 	NamespaceKeepAfterProjectDeletion = "namespace.gardener.cloud/keep-after-project-deletion"
+	// NamespaceCreatedByProject is a constant for annotation on a `Namespace` resource that states that it
+	// was created by the project because either the user didn't specify the namespace in the project `spec.Namespace`
+	// or the specified namespace was not present.
```
Comment (ialidzhikov) [inline pkg/apis/core/v1beta1/constants/types_constants.go]:
```suggestion
	// NamespaceCreatedByProject is a constant for annotation on a `Namespace` resource that states that it
	// was created by the project controller because either the Project's `spec.namespace` field was not specified
	// or the specified namespace was not present.
```

File: pkg/controllermanager/controller/project/project_control_reconcile.go [hunk 4]
```diff
@@ -203,9 +205,9 @@ func (r *projectReconciler) reconcileNamespaceForProject(ctx context.Context, ga
 	namespace.Labels = utils.MergeStringMaps(namespace.Labels, projectLabels)
 	namespace.Annotations = utils.MergeStringMaps(namespace.Annotations, projectAnnotations)
 
-	// If the project is reconciled for the first time then its observed generation is 0. Only in this case we want
+	// If the namespace creation was not triggred by the  project only in this case we want
 	// to add the "keep-after-project-deletion" annotation to the namespace when we adopt it.
```
Comment (ialidzhikov) [inline pkg/controllermanager/controller/project/project_control_reconcile.go]:
```suggestion
	// Add the "keep-after-project-deletion" annotation to the namespace only when we adopt it
	// (i.e. the namespace was not created by the project controller).
```

**Review by ialidzhikov — COMMENTED** [review]
Minor suggestions.

**Review by ialidzhikov — APPROVED** [review]
Thanks!

/lgtm
/squash

File: pkg/controllermanager/controller/project/project_control.go [hunk 5]
```diff
@@ -109,10 +109,10 @@ func (r *projectReconciler) Reconcile(ctx context.Context, request reconcile.Req
 	projectLogger.Infof("[PROJECT RECONCILE] %s", project.Name)
 
 	if project.DeletionTimestamp != nil {
-		return r.delete(ctx, project, r.gardenClient.Client(), r.gardenClient.Client())
+		return r.delete(ctx, project, r.gardenClient.Client(), r.gardenClient.APIReader())
 	}
 
-	return r.reconcile(ctx, project, r.gardenClient.Client(), r.gardenClient.Client())
+	return r.reconcile(ctx, project, r.gardenClient.Client(), r.gardenClient.APIReader())
```
Comment (timebertt) [inline pkg/controllermanager/controller/project/project_control.go:115]: Ufff, this will put a lot of load on the API server and etcd after a restart (e.g. rolling update).
Every project is read with quorum read from etcd...

**Review by timebertt — COMMENTED** [review]
To be honest, I think this change is not a good solution for https://github.com/gardener/gardener/issues/5192 and imposes more scalability problems.

We should figure out a way to implement the project controller without relying on direct reads.
See https://github.com/gardener/gardener/blob/master/docs/development/kubernetes-clients.md#to-cache-or-not-to-cache for more ideas how to do that, e.g.:
- deterministic naming of project namespace
- tracking creation of project namespace (if sticking to `generateName`)
- leverage optimistic locking on project resource

Considering the amount of load that controller-manager already puts on the API server on a restart (see internal discussions/investigations), I'm afraid that this change on top might effectively bring it down entirely.

File: pkg/controllermanager/controller/project/project_control.go (hunk 5 above)
Comment (acumino) [reply pkg/controllermanager/controller/project/project_control.go:115]: This is reasonable.
`APIReader()` was changed to `APIClient()` in #4111. I am not sure that was it changed because of the issue you described? Regarding reverting the PR we can consider other's opinions also. Meanwhile, I will try to figure out new logic for project reconciliation.
