### PR TITLE
Replace `TryUpdateShoot{Labels,Annotations}` functions with `Patch` requests

### LINKED ISSUE #3351: Removing shoot annotation in  "RestartControlPlanePods" fails
**How to categorize this issue?**

/kind bug
/priority normal

**What happened**:

Removing shoot annotation in  "RestartControlPlanePods" fails because it is operating on an outdated version.
This is a temporary situation and should not lead right away to a failed reocniliation.

> Warning  ReconcileError  45s (x5 over 17m)      gardenlet  Flow "Shoot cluster reconciliation" encountered task errors: [task "Restart control plane pods" failed: Operation cannot be fulfilled on shoots.core.gardener.cloud "em-prod-aus": the object has been modified; please apply your changes to the latest version and try again]
**What you expected to happen**:

Possible reason
 - shoot is updated by Gardenlet at the same time

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

[I think the retry of the annotation removal is not high enough](https://github.com/gardener/gardener/blob/4f397c424923fc2c496fc37b0d1f9b3cac996692/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L502-L501). We should increase it. Otherwise, the task fails quite instantly leading to more full reconciliations and backoff.
 
**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area usability
/kind cleanup technical-debt
/priority normal

**What this PR does / why we need it**:
This PR replaces the `TryUpdateShoot{Labels,Annotations}` functions with `Patch` requests to prevent undesired conflict updates that we anyways don't care about.

**Which issue(s) this PR fixes**:
Fixes #3351

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/shoot_care_control.go [hunk 1]
```diff
@@ -374,22 +376,16 @@ func (c *defaultCareControl) Care(shootObj *gardencorev1beta1.Shoot, key string)
...
+	oldObj := shoot.DeepCopy()
+	kutil.SetMetaDataLabel(&shoot.ObjectMeta, common.ShootStatus, string(shootpkg.ComputeStatus(
+		shoot.Status.LastOperation,
+		shoot.Status.LastErrors,
+		conditionAPIServerAvailable,
+		conditionControlPlaneHealthy,
+		conditionEveryNodeReady,
+		conditionSystemComponentsHealthy,
+	)))
+	if err := gardenClient.DirectClient().Patch(ctx, shoot, client.MergeFrom(oldObj)); err != nil {
```
Comment (timebertt) [inline pkg/gardenlet/controller/shoot/shoot_care_control.go]: This call doesn't read anything from the API server, so `Client` and `DirectClient` are behaving equally here.
```suggestion
	if err := gardenClient.Client().Patch(ctx, shoot, client.MergeFrom(oldObj)); err != nil {
```

File: pkg/gardenlet/controller/shoot/shoot_control.go [hunk 2]
```diff
@@ -692,7 +692,13 @@ func (c *Controller) updateShootStatusOperationError(ctx context.Context, g gard
 		return nil, err
 	}
 
-	return kutil.TryUpdateShootLabels(ctx, g, retry.DefaultRetry, newShoot.ObjectMeta, shootpkg.StatusLabelTransform(shootpkg.StatusUnhealthy))
+	oldObj := newShoot.DeepCopy()
+	kutil.SetMetaDataLabel(&newShoot.ObjectMeta, common.ShootStatus, string(shootpkg.StatusUnhealthy))
+	if err := gardenClient.DirectClient().Patch(ctx, newShoot, client.MergeFrom(oldObj)); err != nil {
```
Comment (timebertt) [inline pkg/gardenlet/controller/shoot/shoot_control.go]: Same here

File: pkg/gardenlet/controller/shoot/shoot_control_reconcile.go [hunk 3]
```diff
@@ -499,18 +499,17 @@ func (c *Controller) runReconcileShootFlow(o *operation.Operation) *gardencorev1
...
 
-	o.Shoot.Info = newShoot
-	return nil
+	if shoot.Generation != generation {
+		return nil
+	}
+
+	oldObj := o.Shoot.Info.DeepCopy()
+	controllerutils.RemoveTasks(o.Shoot.Info.Annotations, tasksToRemove...)
+	return o.K8sGardenClient.DirectClient().Patch(ctx, o.Shoot.Info, client.MergeFrom(oldObj))
```
Comment (timebertt) [inline pkg/gardenlet/controller/shoot/shoot_control_reconcile.go]: Same here

File: pkg/operation/botanist/secrets.go [hunk 4]
```diff
@@ -219,12 +217,11 @@ func (b *Botanist) rotateKubeconfigSecrets(ctx context.Context, gardenerResource
...
-		delete(shoot.Annotations, v1beta1constants.GardenerOperation)
-		delete(shoot.Annotations, common.ShootOperationDeprecated)
-		return shoot, nil
-	})
-	return err
+
+	oldObj := b.Shoot.Info.DeepCopy()
+	delete(b.Shoot.Info.Annotations, v1beta1constants.GardenerOperation)
+	delete(b.Shoot.Info.Annotations, common.ShootOperationDeprecated)
+	return b.K8sGardenClient.DirectClient().Patch(ctx, b.Shoot.Info, client.MergeFrom(oldObj))
```
Comment (timebertt) [inline pkg/operation/botanist/secrets.go]: Same here

**Review by timebertt — COMMENTED** [review]
Very nice!
Generally, I think this change moves things into the right direction.
Only nits.

**Review by timebertt — DISMISSED** [review]
Thanks!
/lgtm

File: pkg/gardenlet/controller/shoot/shoot_control_reconcile.go [hunk 5]
```diff
@@ -499,18 +499,17 @@ func (c *Controller) runReconcileShootFlow(o *operation.Operation) *gardencorev1
...
-	newShoot, err := kutil.TryUpdateShootAnnotations(ctx, o.K8sGardenClient.GardenCore(), retry.DefaultRetry, o.Shoot.Info.ObjectMeta,
-		func(shoot *gardencorev1beta1.Shoot) (*gardencorev1beta1.Shoot, error) {
-			if shoot.Generation == generation {
-				controllerutils.RemoveTasks(shoot.Annotations, tasksToRemove...)
-			}
-			return shoot, nil
-		},
-	)
-	if err != nil {
+	// Check if shoot generation was changed mid-air
```
Comment (danielfoehrKn) [inline pkg/gardenlet/controller/shoot/shoot_control_reconcile.go]:
```suggestion
	// Check if shoot generation was changed mid-air
	// if that is the case, we do not remove the task annotation so that the action
	//  associated with the task is executed again in the subsequent reconciliation
```

**Review by danielfoehrKn — COMMENTED** [review]
Thanks for taking this! Only one nit that adds some context

**Review by timebertt — DISMISSED** [review]
/lgtm

**Comment by rfranzke** [comment]
I had to rebase to resolve some merge conflicts.

**Review by timebertt — APPROVED** [review]
/lgtm
