### PR TITLE
[GEP-28] Tolerate transient errors while waiting until the `shoot-gardener-node-agent` ManagedResource gets healthy

### LINKED ISSUE #14484: `gardenadm init` got extremely flaky
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
I have a WIP branch with a script that uses `gardenadm init` based on the steps in [Deploying Self-Hosted Shoot Clusters Locally](https://github.com/gardener/gardener/blob/v1.139.0/docs/deployment/getting_started_locally_with_gardenadm.md).
My WIP branch was based on the upstream `release-v1.135`. When I rebased on `release-v1.139`, `gardenadm init` became extremely flaky.

The failure reason is:
```
2026-04-02T05:48:58.636Z	ERROR	Error	{"flow": "init", "task": "Waiting until control plane components (static pods) are ready", "error": "the operating system configs for the worker nodes were not populated yet: Get \"https://api.root.garden.external.local.gardener.cloud/apis/resources.gardener.cloud/v1alpha1/namespaces/kube-system/managedresources/shoot-gardener-node-agent\": dial tcp 10.2.0.99:443: connect: connection refused - error from a previous attempt: unexpected EOF"}
github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2
	github.com/gardener/gardener/pkg/utils/flow/flow.go:239
2026-04-02T05:48:58.636Z	INFO	Finished	{"flow": "init"}
Error: 1 error occurred:
	* task "Waiting until control plane components (static pods) are ready" failed: the operating system configs for the worker nodes were not populated yet: Get "https://api.root.garden.external.local.gardener.cloud/apis/resources.gardener.cloud/v1alpha1/namespaces/kube-system/managedresources/shoot-gardener-node-agent": dial tcp 10.2.0.99:443: connect: connection refused - error from a previous attempt: unexpected EOF


command terminated with exit code 1
```

**What you expected to happen**:
`gardenadm init` to do not flake in such a manner.

**How to reproduce it (as minimally and precisely as possible)**:
```
# Create the setup according to the local setup with gardenadm
make kind-single-node-up
export KUBECONFIG=$PWD/dev-setup/kubeconfigs/runtime/kubeconfig
make gardenadm-up

# Create control plane Node
kubectl -n gardenadm-unmanaged-infra exec -it machine-0 -- gardenadm init -d /gardenadm/resources --use-bootstrap-etcd
```

**Anything else we need to know?**:
There are also failing `{ci,pull}-gardener-e2e-kind-gardenadm` runs with the same error:
- https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind-gardenadm-release-v1-138/2039494151141068800#1:build-log.txt%3A1701-1718

**Environment**:

- Gardener version: v1.139.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
`gardenadm init` deploys the control plane components (static pods) in the following step: https://github.com/gardener/gardener/blob/c8ca51630c682542ddc4807cdd102ca56be7e95a/pkg/gardenadm/cmd/init/init.go#L365-L369. Later, it waits until the control plane components (static pods) are ready in the following step: https://github.com/gardener/gardener/blob/c8ca51630c682542ddc4807cdd102ca56be7e95a/pkg/gardenadm/cmd/init/init.go#L370-L376. The wait consists of waiting until the `shoot-gardener-node-agent` ManagedResource is healthy and waiting until the OperatingSystemConfig is updated for all worker pools. See the [`WaitUntilOperatingSystemConfigUpdatedForAllWorkerPools` func](https://github.com/gardener/gardener/blob/526ca2f5fbce83cda15a35ccef2844ec35ffb8ea/pkg/gardenlet/operation/botanist/worker.go#L195-L228).

The flake described in https://github.com/gardener/gardener/issues/14484 occurs in https://github.com/gardener/gardener/blob/526ca2f5fbce83cda15a35ccef2844ec35ffb8ea/pkg/gardenlet/operation/botanist/worker.go#L199-L201. The wait for the `shoot-gardener-node-agent` ManagedResource does not tolerate errors and fails the whole `gardenadm init` flow due to transient errors. Transient errors occur because the first step from above deploys the static pods (incl. kube-apiserver). The static pods are being rolled out and the kube-apiserver is expected to fail wait transient errors during this rollout.

This PR ignores transient errors in the wait for the `shoot-gardener-node-agent` ManagedResource. Transient errors are now retried.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/14484

**Special notes for your reviewer**:
On the master branch (16afe9dcdf0c6e13619a2b49c802921410d0b3c5), I can reproduce the issue 5/5 (5 times fails from 5 tries).
On this PR, I am not able to reproduce the issue 0/3 (0 times fails from 3 tries).

The script that I used for reproducing the issue:
```bash
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Create the setup according to the local setup with gardenadm
make kind-single-node-up
export KUBECONFIG=$PWD/dev-setup/kubeconfigs/runtime/kubeconfig
make gardenadm-up

# Create control plane Node
kubectl -n gardenadm-unmanaged-infra exec -it machine-0 -- gardenadm init -d /gardenadm/resources --use-bootstrap-etcd
```

**Release note**:

```bugfix operator
A bug was fixed where `gardenadm init` could fail due to a transient error while fetching the `shoot-gardener-node-agent` ManagedResource when the Kubernetes API server is temporarily unavailable due to static pod rollout.
```

### CODE REVIEW

**Comment by tobschli** [comment]
Amazing find! Thank you so much for this! 🤩

Today, I also looked a bit in the state of the flakes: https://github.com/gardener/gardener/issues/14025#issuecomment-4258575291

I observed the `pull-gardener-e2e-kind-gardenadm-unmanaged-infra-external-gardener` test failing often during this step as well. The runs I described in the comment seem to itme out due to "just taking too long" in my eyes.

But reading this PR now, I feel like this might be connected. Do you think this is related?

File: pkg/gardenlet/operation/botanist/worker.go [hunk 1]
```diff
@@ -196,18 +196,24 @@ func (b *Botanist) WaitUntilOperatingSystemConfigUpdatedForAllWorkerPools(ctx co
...
-
-	timeoutCtx2, cancel2 := context.WithTimeout(ctx, GetTimeoutWaitOperatingSystemConfigUpdated(b.Shoot))
-	defer cancel2()
-
 	retryFn := retry.SevereError
 	if tolerateErrors {
 		retryFn = retry.MinorError
 	}
 
+	if err := retry.Until(timeoutCtx, IntervalWaitOperatingSystemConfigUpdated, func(ctx context.Context) (done bool, err error) {
```
Comment (rfranzke) [inline pkg/gardenlet/operation/botanist/worker.go:208]: 1. I think this deserves a comment because it's not quite obvious why we are retrying here (while `WaitUntilHealthy` already retries on its own).
2. Can we do this only for self-hosted shoots?

**Comment by ialidzhikov** [comment]
> Amazing find! Thank you so much for this! 🤩
> 
> Today, I also looked a bit in the state of the flakes: [#14025 (comment)](https://github.com/gardener/gardener/issues/14025#issuecomment-4258575291)
> 
> I observed the `pull-gardener-e2e-kind-gardenadm-unmanaged-infra-external-gardener` test failing often during this step as well. The runs I described in the comment seem to itme out due to "just taking too long" in my eyes.
> 
> But reading this PR now, I feel like this might be connected. Do you think this is related?

Hi @tobschli ,

Locally, I can reproduce it quite frequently. The error is:
```
2026-04-16T08:54:54.183Z	INFO	Finished	{"flow": "init"}
Error: 1 error occurred:
	* task "Waiting until control plane components (static pods) are ready" failed: the operating system configs for the worker nodes were not populated yet: Get "https://api.root.garden.external.local.gardener.cloud/apis/resources.gardener.cloud/v1alpha1/namespaces/kube-system/managedresources/shoot-gardener-node-agent": EOF


command terminated with exit code 1
```

I will run some more tests locally and share what is the frequency on my side.

When opening https://github.com/gardener/gardener/issues/14484, I was able to find only a single failure of `ci-gardener-e2e-kind-gardenadm` job. I didn't check for `{ci,pull}-gardener-e2e-kind-gardenadm-unmanaged-infra-external-gardener` failures. But if it is a timeout and not concretely the above error, then it seems to be something else. The step waits for all static pods to be healthy and timeout in this step can be caused by something else. This flake is only about a transient error which should be retried but it is not retried.

File: pkg/gardenlet/operation/botanist/worker.go (hunk 1 above)
Comment (ialidzhikov) [reply pkg/gardenlet/operation/botanist/worker.go:208]: Thank you for the review!

> 1. I think this deserves a comment because it's not quite obvious why we are retrying here (while `WaitUntilHealthy` already retries on its own).

Agree. I pushed f624a9b6b5339cf6a34b65c9d98f640e90b50c57.

> 2. Can we do this only for self-hosted shoots?

The `tolerateErrors` parameter is already the mechanism that gates this to self-hosted shoots — it's only passed as `true` from `gardenadm init`. When `tolerateErrors=false` (all non-self-hosted paths), `retryFn` is `retry.SevereError`, which means the outer retry loop exits immediately on the first error — effectively the same behavior as before.

Adding an extra condition would be redundant. But let me know if I miss something.

---

In general, there are also other options to fix the issue. The flow step could be retried. The signature of `managedresources.WaitUntilHealthy` can be changed to accept a `tolerateErrors` argument, however I didn't like this option.
But let me know if you see a more elegant or efficient solution.

**Comment by ialidzhikov** [comment]
> I will run some more tests locally and share what is the frequency on my side.

I updated the PR description. Interestingly, I can always reproduce the issue on the master branch (16afe9dcdf0c6e13619a2b49c802921410d0b3c5) - 5 times reproduced from 5 tries. I don't know if it is the same for you or something is unusual on my side or is it just timing.
