### PR TITLE
Fix `ManagedSeed` bootstrapping for Kubernetes 1.24+ clusters

### LINKED ISSUE #7311: Gardenlet Service Account Bootstrap broken on K8s > 1.23
**How to categorize this issue?**
/area control-plane
/area usability
/kind bug

**What happened**:
Tried to bootstrap a ManagedSeed with the parent Gardenlet running on K8s 1.24.9.
Gardenlet got stuck waiting for KCM to issue a secret for the service account.

This doesn't work on Kubernetes 1.24 and above, as KCM doesn't generate a long lived token / secret for the service account automatically.

After talking with @rfranzke about this on slack, https://github.com/gardener/gardener/blob/584e63d5ae7672dd5f95f3af1fdfdcdd881465e0/pkg/gardenlet/bootstrap/util/util.go#L258 seems to be the problem.

Unfortunately our setup doesn't support BootstrapTokens, so we can't switch to that.

**What you expected to happen**:
Gardener should request the token of the Service Account via the /token subresource or create the required secret.

**How to reproduce it (as minimally and precisely as possible)**:
- Setup Gardener v1.62.1 and Gardenlet on K8s 1.24.9
- Create ManagedSeed with bootstrap set to ServiceAccount

**Environment**:

- Gardener version: v1.62.1
- Kubernetes version (use `kubectl version`):
Client Version: v1.26.0
Server Version: v1.24.9
- Cloud provider or hardware configuration: OpenStack

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area usability
/kind bug

**What this PR does / why we need it**:
The non-default `ServiceAccount` bootstrapping mode is currently broken for 1.24+ clusters because it relies on the `ServiceAccount` controller to populate a static token secret. However, this is no longer happening automatically for 1.24+ clusters.
This PR adapts the code to use the `serviceaccounts/token` subresource instead.

**Which issue(s) this PR fixes**:
Fixes #7311

**Release note**:

```bugfix operator
A bug preventing `ManagedSeed` bootstrapping for 1.24+ Kubernetes clusters has been fixed.
```

### CODE REVIEW

File: pkg/gardenlet/bootstrap/util/util.go [hunk 1]
```diff
@@ -255,31 +257,33 @@ func ComputeGardenletKubeconfigWithBootstrapToken(ctx context.Context, gardenCli
...
 		return nil, err
 	}
 
-	// Get the service account secret
-	if len(sa.Secrets) == 0 {
-		return nil, fmt.Errorf("service account token controller has not yet created a secret for the service account")
+	// Get a token for this service account
+	tokenRequest := &authenticationv1.TokenRequest{
+		Spec: authenticationv1.TokenRequestSpec{
+			ExpirationSeconds: pointer.Int64(600),
```
Comment (acumino) [inline pkg/gardenlet/bootstrap/util/util.go:275]: How this 10 min expiration is selected?

**Review by acumino — COMMENTED** [review]
One question other than that LGTM!
/lgtm

File: pkg/gardenlet/bootstrap/util/util.go (hunk 1 above)
Comment (rfranzke) [reply pkg/gardenlet/bootstrap/util/util.go:275]: `10m` is the lowest possible duration that can be used for expiration.

**Review by acumino — APPROVED** [review]
/approve
