### PR TITLE
Fix `Secret etcd-backup not found`

### LINKED ISSUE #9749: If backupentry reconciles before Shoot namespace gets created cluster creation will fail
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
https://github.com/gardener/gardener/blob/c024f371f3b65d82f4ec16f975960209c8a00410/extensions/pkg/controller/backupentry/genericactuator/actuator.go#L51-L59
There is no dependency in the shoot reconciliation flow between the steps for deploying shoot namespace and deploying backup entry. So if the extension Backupentry gets created when shoot namespace is missing it can succeed without deploying backup secret. After that a second BE reconciliation won't happen. Therefore `etcd-backup` won't get created and shoot won't get created.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Add `time.Sleep(20*time.Seconds)` in the beginning of `pkg/gardenlet/operation/botanist/namespaces.go@DeploySeedNamespace` and create local shoot

```
$ k -n garden-local get shoot local -o yaml | yq '.status.lastErrors'
- description: 'task "Deploying main and events etcd" failed: retry failed with context deadline exceeded, last error: Secret "etcd-backup" not found'
  lastUpdateTime: "2024-05-14T14:36:16Z"
  taskID: Deploying main and events etcd
```

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by Kostov6**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
This PR fixes a bug where shoot creation may fail with `Secret etcd-backup not found`

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/9749

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
gardenlet: An issue causing Shoot deletion to fail due to "Secret `etcd-backup` not found" error caused by not yet created shoot namespace is now fixed.
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go [hunk 1]
```diff
@@ -228,7 +228,8 @@ func (r *Reconciler) runReconcileShootFlow(ctx context.Context, o *operation.Ope
 			Name:         "Deploying backup entry",
 			Fn:           botanist.DeployBackupEntry,
 			SkipIf:       !allowBackup,
-			Dependencies: flow.NewTaskIDs(waitUntilSourceBackupEntryInGardenReconciled),
+			Dependencies: flow.NewTaskIDs(deployNamespace, waitUntilSourceBackupEntryInGardenReconciled),
+			// deployNamespace dependency needed for shoot creation
```
Comment (shafeeqes) [inline pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go]: I think we can omit this comment
```suggestion
```

**Review by ialidzhikov — COMMENTED** [review]
Apart from @shafeeqes 's suggestion, lgtm. 
Please add a release note.
