### PR TITLE
Move seed garbage collection to `seed-care`, ignore stale `Pod`s when checking for updated `Deployment`s

### LINKED ISSUE #10476: Pods in status `Completed` cause deployments to be considered `Progressing` forever
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:
On a seed several pods in various namespaces went into status `Completed` or `OutOfCpu`. The responsible replicaset controller created new pods and the deployment was considered healthy from an K8s perspective.

From Gardener perspective it was considered `progressing` and the seed could not sync because of messages like this:

```
Some extensions are progressing: map[
extension-registry-cache-z942g: condition ResourcesProgressing of managed resource garden/extension-registry-cache-z942g is True: Deployment "extension-extension-registry-cache-z942g/gardener-extension-registry-cache" is progressing: there are still non-terminated old pods 
provider-openstack-25tpw: condition ResourcesProgressing of managed resource garden/provider-openstack-25tpw is True: Deployment "extension-provider-openstack-25tpw/gardener-extension-provider-openstack" is progressing: there are still non-terminated old pods
]
``` 

This in turn could only be healed by manually cleaning up the pods.

**What you expected to happen**:
Ideally, the [DeploymentHasExactNumberOfPods function](https://github.com/gardener/gardener/blob/fa42aecfe5573618031c7bdf25a975a6445d7df8/pkg/utils/kubernetes/health/deployment.go#L142-L150) would [filter for active pods](https://github.com/kubernetes/kubernetes/blob/3b86da0c0cacd1cbf9cbaeee65dcf19be292c64a/pkg/controller/controller_utils.go#L947C4-L958) similar to what the [replicaset controller](https://github.com/kubernetes/kubernetes/blob/3b86da0c0cacd1cbf9cbaeee65dcf19be292c64a/pkg/controller/replicaset/replica_set.go#L710-L711) does.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Maybe gardenlet's garbage collection could be applied to all namespaces on a seed / kube-system?

**Environment**:

- Gardener version: v1.102.1

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR addresses the concerns mentioned in #10476:

1. Stale `Pod`s (e.g., those still existing in `Evicted` or other stale statuses) are ignored when checking whether a `Deployment` rollout succeeded (i.e., whether all `Pod`s belonging to older `ReplicaSet`s have been terminated).
2. For legacy reasons, the seed garbage collection was part of `shoot-care` controller. Hence, it was only active in shoot namespaces in the seed cluster. Now, we have moved this part to the `seed-care` controller. It will be active in all namespaces in the seed except for `kube-system`. If the seed is a managed seed (i.e., a shoot cluster), then the still existing garbage collection in the `shoot-care` controller will take care of it. If it is an unmanaged seed, it is out of the responsibility of `gardenlet`.

**Which issue(s) this PR fixes**:
Fixes #10476

**Release note**:

```feature operator
`gardenlet` now performs garbage collection of stale `Pod`s in all namespaces (except `kube-system`) in the seed cluster.
```
```bugfix operator
When checking whether a `Deployment` rollout is complete, stale `Pod`s are now ignored and no longer counted.
```

### CODE REVIEW

File: pkg/utils/kubernetes/health/deployment_test.go [hunk 1]
```diff
@@ -313,5 +313,17 @@ var _ = Describe("Deployment", func() {
...
+			for i := 0; i < 2; i++ {
+				p := pod.DeepCopy()
+				p.Status.Reason = "Evicted"
+				Expect(fakeClient.Create(ctx, p)).To(Succeed())
+			}
+
+			ok, err := health.DeploymentHasExactNumberOfPods(ctx, fakeClient, deployment)
+			Expect(err).NotTo(HaveOccurred())
+			Expect(ok).To(BeFalse())
+		})
```
Comment (ScheererJ) [inline pkg/utils/kubernetes/health/deployment_test.go]: Would it not be better to have only one evicted pod being created or have an additional "normal" one so that this succeeds? This test would have yielded the exact same result before the change, i.e. there are two pods, which does not match the exact number of expected pods.

File: test/integration/gardenlet/seed/care/care_test.go [hunk 2]
```diff
@@ -177,6 +177,33 @@ var _ = Describe("Seed Care controller tests", func() {
...
+			Expect(testClient.Status().Update(ctx, pod1)).To(Succeed())
+
+			Eventually(func() error {
+				return testClient.Get(ctx, client.ObjectKeyFromObject(pod1), &corev1.Pod{})
+			}).Should(BeNotFoundError())
+
+			Consistently(func() error {
+				return testClient.Get(ctx, client.ObjectKeyFromObject(pod2), &corev1.Pod{})
+			}).Should(Succeed())
+		})
```
Comment (ScheererJ) [inline test/integration/gardenlet/seed/care/care_test.go]: Maybe I am missing something, but this test does not look complete from my point of view. I would have expected to have `pod2` also being stale otherwise it would never be evicted anyway. Furthermore, there is no call to delete stale pod. Is that somehow happening magically?

**Review by ScheererJ — COMMENTED** [review]
Thanks a lot for the extended stale pod garbage collection.

The changes are good. I only have comments concerning the tests.

File: test/integration/gardenlet/seed/care/care_test.go (hunk 2 above)
Comment (rfranzke) [reply test/integration/gardenlet/seed/care/care_test.go]: You're right, I was missing to also update the status of `pod2` to `Evicted`. This way, we ensure that stale pods in `kube-system` namespaces are ignored.

> Furthermore, there is no call to delete stale pod. Is that somehow happening magically?

This is an integration test - the controller running in the background is performing the deletion. This is actually what we want to test, i.e., whether the controller behaves as expected :)

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve
