### PR TITLE
Validate seed network configuration on gardenlet startup.

### LINKED ISSUE #6548: Failing to create seed in local setup
**How to categorize this issue?**

/area testing
/kind bug

**What happened**:
When creating a seed in a local setup, the seed cannot be ready because of `kube-state-metrics`. `kube-state-metrics` goes into `CrashLoopBackOff` without any error in logs.

**What you expected to happen**:
Should be able to create seed in a local setup.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new shoot and use this new shoot for shooted seed in local setup, check garden namespace in this shoot to confirm `kube-state-metrics` goes into `CrashLoopBackOff`.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.53.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
Validate seed network configuration on gardenlet startup.

In case the seed specification does not fit to the actual seed cluster configuration
the result may be hard to find issues, e.g. in the network policies. Therefore, this
change introduces a validation during the gardenlet startup to compare the seed
specification with the reality in the seed cluster.
For now, this only works in case the seed cluster is managed itself by Gardener as
it uses the shoot-info config map. Other clusters are always accepted.

**Which issue(s) this PR fixes**:
Fixes #6548.

**Special notes for your reviewer**:

**Release note**:

```feature operator
Gardenlet now checks that the seed network configuration conforms to the reality in the seed cluster in case the seed is a shoot itself.
```

/invite @rfranzke @timebertt

### CODE REVIEW

File: cmd/gardenlet/app/gardenlet.go [hunk 1]
```diff
@@ -608,3 +615,38 @@ func extractID(line string) string {
...
+	shootInfo := &corev1.ConfigMap{}
+	if err := seedClient.Get(ctx, kutil.Key(metav1.NamespaceSystem, v1beta1constants.ConfigMapNameShootInfo), shootInfo); client.IgnoreNotFound(err) != nil {
+		return err
+	} else if apierrors.IsNotFound(err) {
+		// Seed cluster does not seem to be managed by Gardener
+		return nil
+	}
+
+	podNetwork := shootInfo.Data["podNetwork"]
+	if podNetwork != seedConfig.Spec.Networks.Pods {
```
Comment (rfranzke) [inline cmd/gardenlet/app/gardenlet.go]: Cosmetics:

```suggestion
	if podNetwork := shootInfo.Data["podNetwork"]; podNetwork != seedConfig.Spec.Networks.Pods {
```

File: cmd/gardenlet/app/gardenlet.go [hunk 2]
```diff
@@ -608,3 +615,38 @@ func extractID(line string) string {
...
+		return fmt.Errorf("incorrect pod network specified in seed configuration (cluster=%q vs. config=%q)", podNetwork, seedConfig.Spec.Networks.Pods)
+	}
+
+	serviceNetwork := shootInfo.Data["serviceNetwork"]
+	if serviceNetwork != seedConfig.Spec.Networks.Services {
```
Comment (rfranzke) [inline cmd/gardenlet/app/gardenlet.go]: Cosmetics:

```suggestion
	if serviceNetwork := shootInfo.Data["serviceNetwork"]; serviceNetwork != seedConfig.Spec.Networks.Services {
```

File: cmd/gardenlet/app/gardenlet.go [hunk 3]
```diff
@@ -608,3 +615,38 @@ func extractID(line string) string {
...
+		return fmt.Errorf("incorrect service network specified in seed configuration (cluster=%q vs. config=%q)", serviceNetwork, seedConfig.Spec.Networks.Services)
+	}
+
+	nodeNetwork, exists := shootInfo.Data["nodeNetwork"]
+	// Be graceful in case the (optional) node network is only available on one side
+	if seedConfig.Spec.Networks.Nodes != nil && exists {
+		if nodeNetwork != *seedConfig.Spec.Networks.Nodes {
```
Comment (rfranzke) [inline cmd/gardenlet/app/gardenlet.go]: Cosmetics:

```suggestion
	if nodeNetwork, exists := shootInfo.Data["nodeNetwork"]; exists &&
		seedConfig.Spec.Networks.Nodes != nil &&
		*seedConfig.Spec.Networks.Nodes != nodeNetwork {
		// Be graceful in case the (optional) node network is only available on one side
```

**Review by rfranzke — COMMENTED** [review]
Looks promising :) Thanks!
Does it make sense to write a short unit test for this `checkSeedConfig` function?

File: cmd/gardenlet/app/gardenlet.go (hunk 1 above)
Comment (ScheererJ) [reply cmd/gardenlet/app/gardenlet.go]: Addressed in latest commit.

File: cmd/gardenlet/app/gardenlet.go (hunk 2 above)
Comment (ScheererJ) [reply cmd/gardenlet/app/gardenlet.go]: Addressed in latest commit.

File: cmd/gardenlet/app/gardenlet.go (hunk 3 above)
Comment (ScheererJ) [reply cmd/gardenlet/app/gardenlet.go]: Addressed in latest commit.

**Comment by ScheererJ** [comment]
> Looks promising :) Thanks! Does it make sense to write a short unit test for this `checkSeedConfig` function?

Added tests.

@rfranzke Do I need to register those tests somewhere so that they are included in the ordinary unit tests or does this happen automatically?

File: cmd/gardenlet/app/gardenlet_test.go [hunk 4]
```diff
@@ -0,0 +1,138 @@
...
+	"k8s.io/apimachinery/pkg/runtime"
+	"sigs.k8s.io/controller-runtime/pkg/client"
+)
+
+var _ = Describe("Gardenlet", func() {
+	Describe("#CheckSeedConfig", func() {
+		var (
+			ctx    = context.TODO()
+			ctrl   *gomock.Controller
+			client *mockclient.MockClient
```
Comment (rfranzke) [inline cmd/gardenlet/app/gardenlet_test.go]: Please use a fake client instead, see https://github.com/gardener/gardener/blob/master/docs/development/testing.md#writing-unit-tests:

> generally, prefer fakes over mocks, e.g., use controller-runtime fake client over mock clients

File: cmd/gardenlet/app/gardenlet_suite_test.go [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+import (
+	"testing"
+
+	. "github.com/onsi/ginkgo/v2"
+	. "github.com/onsi/gomega"
+)
+
+func TestGardenlet(t *testing.T) {
+	RegisterFailHandler(Fail)
+	RunSpecs(t, "Gardenlet Suite")
```
Comment (rfranzke) [inline cmd/gardenlet/app/gardenlet_suite_test.go]:
```suggestion
	RunSpecs(t, "Command Gardenlet App Suite")
```

**Review by rfranzke — COMMENTED** [review]
> @rfranzke Do I need to register those tests somewhere so that they are included in the ordinary unit tests or does this happen automatically?

This is already covered by https://github.com/gardener/gardener/blob/c8180396cfdec9e07875535ceef7339d79fbe1ff/Makefile#L237 and indeed they were already executed in CI:

```
ok  	github.com/gardener/gardener/cmd/gardenlet/app	0.251s
```

File: cmd/gardenlet/app/gardenlet_suite_test.go (hunk 5 above)
Comment (ScheererJ) [reply cmd/gardenlet/app/gardenlet_suite_test.go]: Renamed accordingly.

File: cmd/gardenlet/app/gardenlet_test.go (hunk 4 above)
Comment (ScheererJ) [reply cmd/gardenlet/app/gardenlet_test.go]: Switched to fake client, but I do not see the big advantage in this scenario. It might be different in other cases.

**Review by timebertt — APPROVED** [review]
Thanks!
/lgtm
