### PR TITLE
Fixes `make gardener-down` failing at deletion of `garden` `Project`

### LINKED ISSUE #6656: `make gardener-down` fails at deletion of `garden` `Project`
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
Calling `make gardener-down` fails with the following error:
```
$ make gardener-down 
hack/tools/bin/kubectl delete seed local --ignore-not-found --wait --timeout 5m
seed.core.gardener.cloud "local" deleted
hack/tools/bin/kubectl delete seed local2 --ignore-not-found --wait --timeout 5m
hack/tools/bin/skaffold delete -m provider-local,gardenlet
Cleaning up...
release "gardener-extension-provider-local-registration" uninstalled
release "gardener-gardenlet" uninstalled
hack/tools/bin/kubectl delete validatingwebhookconfiguration/validate-namespace-deletion --ignore-not-found
validatingwebhookconfiguration.admissionregistration.k8s.io "validate-namespace-deletion" deleted
hack/tools/bin/kubectl annotate project local confirmation.gardener.cloud/deletion=true
project.core.gardener.cloud/local annotated
hack/tools/bin/skaffold delete -m local-env
Cleaning up...
 - secret "bootstrap-token-07401c" deleted
 - namespace "garden-local" deleted
 - secret "backup-local" deleted
 - secret "local" deleted
 - cloudprofile.core.gardener.cloud "local" deleted
 - controllerdeployment.core.gardener.cloud "networking-calico" deleted
 - controllerregistration.core.gardener.cloud "networking-calico" deleted
 - project.core.gardener.cloud "local" deleted
 - secretbinding.core.gardener.cloud "local" deleted
 - secretbinding.core.gardener.cloud "local" deleted
 - secret "seed-local" deleted
 - Error from server (Forbidden): error when deleting "STDIN": projects.core.gardener.cloud "garden" is forbidden: must have a "confirmation.gardener.cloud/deletion" annotation to delete
kubectl delete: exit status 1
make: *** [gardener-down] Error 1
```

**What you expected to happen**:
`make gardener-down to complete successfully`

**How to reproduce it (as minimally and precisely as possible)**:
1. `make kind-up`
2. `make gardener-up`
3. `make gardener-down`

**Anything else we need to know?**:
The `garden` `Project` was added to the `kustomize` configuration here: https://github.com/gardener/gardener/blob/master/example/provider-local/garden/base/project.yaml with #6293

Perhaps we could add `make gardener-down` to our e2e tests, maybe as a last step in the [ci-e2e-kind.sh](https://github.com/gardener/gardener/blob/master/hack/ci-e2e-kind.sh) script to prevent future errors.

**Environment**:

- Gardener version: 1da39002ccd90e8b3dc08763dcf41708e48d907f
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: 
- Others:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area dev-productivity
/kind bug

**What this PR does / why we need it**:
This pr fixes an issue that would cause `make gardener-down` to fail when trying to delete the `garden` project. Additionally, `make gardener-down` and `make gardenlet-kind2-down` are added to the e2e test scripts so that they also get tested.

**Which issue(s) this PR fixes**:
Fixes #6656 

**Special notes for your reviewer**:
Instead of adding a `confirmation.gardener.cloud/deletion=true` annotation to the `Project` definition directly [here](https://github.com/gardener/gardener/blob/203027d0526b2bf3ebcf1a08d6ac69e9c15a0a66/example/provider-local/garden/base/project.yaml#L2-L7), I added it to the `Makefile` as I saw that that is what we already do for the `local` project.

**Release note**:

```other operator
Fixed an issue that caused `make gardener-down` to fail when deleting the `garden` `Project`.
```
```feature developer
The e2e tests do now also tear down the Gardener environment, effectively verifying whether the `Seed` deletion works as expected.
```

### CODE REVIEW

File: hack/ci-e2e-kind-migration.sh [hunk 1]
```diff
@@ -39,3 +39,6 @@ make gardenlet-kind2-up
 
 # run test
 make test-e2e-local-migration
+
+make gardener-down
+make gardenlet-kind2-down
```
Comment (oliver-goetz) [inline hack/ci-e2e-kind-migration.sh:46]: how about stopping the kind clusters in the end?
```
make kind2-down
make kind-down
```
That's at least something kubernetes is doing too: [ref](https://github.com/kubernetes-sigs/kind/blob/e3a4cd8884aa6ffde81e39888db9fec7aa1c24e9/hack/ci/e2e-k8s.sh#L38)

File: hack/ci-e2e-kind.sh [hunk 2]
```diff
@@ -35,3 +35,5 @@ make gardener-up
 
 # run test
 make test-e2e-local
+
+make gardener-down
```
Comment (oliver-goetz) [inline hack/ci-e2e-kind.sh:41]: same here
```
make kind-down
```

**Review by oliver-goetz — CHANGES_REQUESTED** [review]
🚀 
One small thing. We could stop the kind clusters after the tests.

We might get rid of this "refused to die" exit message in the prow tests then.
```
wrapper.sh] [CLEANUP] Cleaning up after Docker in Docker ...
fd1367d528b9
4ada290a4c49
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
wrapper.sh] [CLEANUP] Done cleaning up after Docker in Docker.
```

File: hack/ci-e2e-kind-migration.sh (hunk 1 above)
Comment (plkokanov) [reply hack/ci-e2e-kind-migration.sh:46]: Ah right, thanks for reminding me. Was planning to do it as well initially :D

Comment (plkokanov) [reply hack/ci-e2e-kind-migration.sh:46]: I would have to add these to the `trap` call so that they get executed after exporting logs. 

Btw something that came to my mind is that exporting logs at the end of the script execution when everything succeeds will not include logs from gardener since the releases will be deleted. But I think that would be ok, right?

Comment (rfranzke) [reply hack/ci-e2e-kind-migration.sh:46]: Yes, we only care about logs/events when something went wrong :)

**Review by oliver-goetz — APPROVED** [review]
/lgtm
