### PR TITLE
Fix race in test

### LINKED ISSUE #10189: [Flaky Test] managedresources #WaitUntilHealthy [It] should retry when the managed resource is not healthy yet
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
- managedresources #WaitUntilHealthy [It] should retry when the managed resource is not healthy yet
- managedresources #WaitUntilHealthyAndNotProgressing() [It] should retry when the managed resource is not healthy yet or still progressing

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/10180/pull-gardener-unit/1816009268977995776
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/10185/pull-gardener-unit/1816011125670547456

**Reason for failure**:
```
• [FAILED] [0.293 seconds]
managedresources #WaitUntilHealthy [It] should retry when the managed resource is not healthy yet
/home/prow/go/src/github.com/gardener/gardener/pkg/utils/managedresources/managedresources_test.go:458
  [FAILED] Expected
      <bool>: true
  to be false
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/pkg/utils/managedresources/managedresources_test.go:562 @ 07/24/24 07:30:55.052
```

**Anything else we need to know**:
```
% stress -p 16 ./pkg/utils/managedresources/managedresources.test -ginkgo.focus "should retry when the managed resource is not healthy yet"

6m30s: 9700 runs so far, 7 failures (0.07%)
6m35s: 9828 runs so far, 7 failures (0.07%)
6m40s: 9956 runs so far, 7 failures (0.07%)
6m45s: 10068 runs so far, 7 failures (0.07%)
```

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
Please see the issue description.

Thanks @ialidzhikov for reporting

**Which issue(s) this PR fixes**:
Fixes #10189

**Special notes for your reviewer**:
```
stress -p 16 ./managedresources.test -ginkgo.focus "should retry when the managed resource is not healthy yet"

5s: 96 runs so far, 0 failures
10s: 239 runs so far, 0 failures
15s: 368 runs so far, 0 failures
20s: 496 runs so far, 0 failures
25s: 624 runs so far, 0 failures
30s: 768 runs so far, 0 failures
35s: 896 runs so far, 0 failures
40s: 1024 runs so far, 0 failures
45s: 1158 runs so far, 0 failures
50s: 1296 runs so far, 0 failures
55s: 1424 runs so far, 0 failures
1m0s: 1568 runs so far, 0 failures
1m5s: 1696 runs so far, 0 failures
1m10s: 1824 runs so far, 0 failures
1m15s: 1968 runs so far, 0 failures
```
**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
Thanks!
/lgtm
/approve

File: pkg/utils/managedresources/managedresources_test.go [hunk 1]
```diff
@@ -559,7 +559,7 @@ var _ = Describe("managedresources", func() {
 			timeoutCtx, cancel := context.WithTimeout(ctx, time.Second*5)
 			defer cancel()
 			Expect(WaitUntilHealthy(timeoutCtx, fakeClient, namespace, name)).To(Succeed())
-			Expect(shouldFail.Load()).To(BeFalse()) // to ensure that the goroutine actually applies all patches
+			Eventually(shouldFail.Load()).Should(BeFalse()) // to ensure that the goroutine actually applies all patches
```
Comment (ialidzhikov) [inline pkg/utils/managedresources/managedresources_test.go]: I was also thinking about such fix but I don't think it is correct one. The whole purpose of `shouldFail` is to prevent `WaitUntilHealthy` to succeed before the goroutine did all updates. With the above change, there could be a bug where `WaitUntilHealthy` succeeds right away wrongly, then due to the `Eventually` usage the assertion for shouldFail passes after several retries.

Comment (dimityrmirchev) [reply pkg/utils/managedresources/managedresources_test.go]: Yes, I see. But this was already the case even with the previous implementation. In case `WaitUntilHealthy ` succeeds immediately then the race is between the 
`Expect(shouldFail.Load())` & all the updates of the MR status + `shouldFail.Store(false)`

Do you have a suggestion how can we prevent that? My thinking is that if we want to test that all other status combinations are not healthy then we should have tests where the wait function fails because of that

**Comment by dimityrmirchev** [comment]
OK. I moved the `shouldFail.Store(false)` inside the patch closure. In addition to that I added a wait group that will assert that the last error check in the goroutine is not skipped. I am not 100% convinced in the correctness of this solution (if the wait function returns early for whatever reason then we race the patches against the last `Expect(shouldFail.Load())` as noted in https://github.com/gardener/gardener/pull/10190#discussion_r1689697978), but PTAL. I am also open to other suggestions

```
1m55s: 6864 runs so far, 0 failures
2m0s: 7169 runs so far, 0 failures
```

**Comment by ialidzhikov** [comment]
Thanks for looking into it and sorry for distracting you today with my finding for a flaky test!

When I check how we unit test such `WaitUntil...` funcs that under the hood use `retry.Until/UntilTimeout`, I see that:
- we use a fake retry implementation that does not wait between the retries: https://github.com/gardener/gardener/blob/41a694b024144465bd4f02f39d6d1c3493549c2f/pkg/extensions/customresources_test.go#L88-L91
- we have dedicated tests cases for each different state of the underlying object: https://github.com/gardener/gardener/blob/41a694b024144465bd4f02f39d6d1c3493549c2f/pkg/extensions/customresources_test.go#L99 (not a single test case that tries to cover all cases)

Let me try to draft something tomorrow morning! I will share the diff if I am happy with it.

**Comment by ialidzhikov** [comment]
```diff
diff --git a/pkg/utils/managedresources/managedresources_test.go b/pkg/utils/managedresources/managedresources_test.go
index 115c769ea..544daf4f3 100644
--- a/pkg/utils/managedresources/managedresources_test.go
+++ b/pkg/utils/managedresources/managedresources_test.go
@@ -8,7 +8,6 @@ import (
 	"context"
 	"errors"
 	"fmt"
-	"sync/atomic"
 	"time"
 
 	. "github.com/onsi/ginkgo/v2"
@@ -28,6 +27,8 @@ import (
 	"github.com/gardener/gardener/pkg/utils"
 	kubernetesutils "github.com/gardener/gardener/pkg/utils/kubernetes"
 	. "github.com/gardener/gardener/pkg/utils/managedresources"
+	"github.com/gardener/gardener/pkg/utils/retry"
+	retryfake "github.com/gardener/gardener/pkg/utils/retry/fake"
 	"github.com/gardener/gardener/pkg/utils/test"
 	. "github.com/gardener/gardener/pkg/utils/test/matchers"
 )
@@ -102,6 +103,9 @@ var _ = Describe("managedresources", func() {
 
 		fakeClient client.Client
 		mr         *resourcesv1alpha1.ManagedResource
+
+		fakeOps   *retryfake.Ops
+		resetVars func()
 	)
 
 	BeforeEach(func() {
@@ -110,6 +114,15 @@ var _ = Describe("managedresources", func() {
 			Name:      name,
 			Namespace: namespace,
 		}}
+
+		fakeOps = &retryfake.Ops{MaxAttempts: 1}
+		resetVars = test.WithVars(
+			&retry.Until, fakeOps.Until,
+		)
+	})
+
+	AfterEach(func() {
+		resetVars()
 	})
 
 	Describe("#NewForShoot", func() {
@@ -455,249 +468,214 @@ var _ = Describe("managedresources", func() {
 			Expect(WaitUntilHealthy(ctx, errClient, namespace, name)).To(MatchError(fakeErr))
 		})
 
-		It("should retry when the managed resource is not healthy yet", func() {
-			DeferCleanup(test.WithVar(&IntervalWait, time.Millisecond*10))
+		It("should return error when the managed resource is not healthy yet (observed generation does not match)", func() {
+			Expect(fakeClient.Create(ctx, mr)).To(Succeed())
+			_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
+				mr.ObjectMeta.Generation = 2
+				mr.Status = resourcesv1alpha1.ManagedResourceStatus{
+					ObservedGeneration: 1,
+				}
+				return nil
+			})
+			Expect(err).To(Not(HaveOccurred()))
+
+			Expect(WaitUntilHealthy(ctx, fakeClient, namespace, name)).To(MatchError(ContainSubstring("managed resource test/managed-resource is not healthy")))
+		})
+
+		It("should return error when the managed resource is not healthy yet (ResourcesApplied is not true)", func() {
+			Expect(fakeClient.Create(ctx, mr)).To(Succeed())
+			_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
+				mr.ObjectMeta.Generation = 1
+				mr.Status = resourcesv1alpha1.ManagedResourceStatus{
+					ObservedGeneration: 1,
+					Conditions: []gardencorev1beta1.Condition{
+						{
+							Type:   resourcesv1alpha1.ResourcesApplied,
+							Status: gardencorev1beta1.ConditionFalse,
+						},
+					},
+				}
+
+				return nil
+			})
+			Expect(err).To(Not(HaveOccurred()))
+
+			Expect(WaitUntilHealthy(ctx, fakeClient, namespace, name)).To(MatchError(ContainSubstring("managed resource test/managed-resource is not healthy")))
+		})
 
+		It("should return error when the managed resource is not healthy yet (ResourcesHealthy is not true)", func() {
 			Expect(fakeClient.Create(ctx, mr)).To(Succeed())
-			shouldFail := atomic.Bool{}
-			shouldFail.Store(true)
-			go func() {
-				defer GinkgoRecover()
-				_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 2
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 1,
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 2
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 2,
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 2
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 2,
-						Conditions: []gardencorev1beta1.Condition{
-							{
-								Type:   resourcesv1alpha1.ResourcesApplied,
-								Status: gardencorev1beta1.ConditionTrue,
-							},
+			_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
+				mr.ObjectMeta.Generation = 1
+				mr.Status = resourcesv1alpha1.ManagedResourceStatus{
+					ObservedGeneration: 1,
+					Conditions: []gardencorev1beta1.Condition{
+						{
+							Type:   resourcesv1alpha1.ResourcesApplied,
+							Status: gardencorev1beta1.ConditionTrue,
 						},
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 2
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 2,
-						Conditions: []gardencorev1beta1.Condition{
-							{
-								Type:   resourcesv1alpha1.ResourcesHealthy,
-								Status: gardencorev1beta1.ConditionTrue,
-							},
+						{
+							Type:   resourcesv1alpha1.ResourcesHealthy,
+							Status: gardencorev1beta1.ConditionFalse,
 						},
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 1
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 1,
-						Conditions: []gardencorev1beta1.Condition{
-							{
-								Type:   resourcesv1alpha1.ResourcesApplied,
-								Status: gardencorev1beta1.ConditionFalse,
-							},
-							{
-								Type:   resourcesv1alpha1.ResourcesHealthy,
-								Status: gardencorev1beta1.ConditionFalse,
-							},
+					},
+				}
+
+				return nil
+			})
+			Expect(err).To(Not(HaveOccurred()))
+
+			Expect(WaitUntilHealthy(ctx, fakeClient, namespace, name)).To(MatchError(ContainSubstring("managed resource test/managed-resource is not healthy")))
+		})
+
+		It("should succeed when the managed resource is healthy", func() {
+			Expect(fakeClient.Create(ctx, mr)).To(Succeed())
+			_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
+				mr.ObjectMeta.Generation = 1
+				mr.Status = resourcesv1alpha1.ManagedResourceStatus{
+					ObservedGeneration: 1,
+					Conditions: []gardencorev1beta1.Condition{
+						{
+							Type:   resourcesv1alpha1.ResourcesApplied,
+							Status: gardencorev1beta1.ConditionTrue,
 						},
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 1
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 1,
-						Conditions: []gardencorev1beta1.Condition{
-							{
-								Type:   resourcesv1alpha1.ResourcesApplied,
-								Status: gardencorev1beta1.ConditionTrue,
-							},
-							{
-								Type:   resourcesv1alpha1.ResourcesHealthy,
-								Status: gardencorev1beta1.ConditionTrue,
-							},
+						{
+							Type:   resourcesv1alpha1.ResourcesHealthy,
+							Status: gardencorev1beta1.ConditionTrue,
 						},
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				shouldFail.Store(false)
-			}()
-
-			timeoutCtx, cancel := context.WithTimeout(ctx, time.Second*5)
-			defer cancel()
-			Expect(WaitUntilHealthy(timeoutCtx, fakeClient, namespace, name)).To(Succeed())
-			Expect(shouldFail.Load()).To(BeFalse()) // to ensure that the goroutine actually applies all patches
+					},
+				}
+
+				return nil
+			})
+			Expect(err).To(Not(HaveOccurred()))
+
+			Expect(WaitUntilHealthy(ctx, fakeClient, namespace, name)).To(Succeed())
 		})
 	})
 
-	Describe("#WaitUntilHealthyAndNotProgressing()", func() {
+	Describe("#WaitUntilHealthyAndNotProgressing", func() {
 		It("should fail when the managed resource cannot be read", func() {
 			errClient := &errorClient{err: fakeErr, failMRGet: true, Client: fakeClient}
 			Expect(WaitUntilHealthyAndNotProgressing(ctx, errClient, namespace, name)).To(MatchError(fakeErr))
 		})
 
-		It("should retry when the managed resource is not healthy yet or still progressing", func() {
-			DeferCleanup(test.WithVar(&IntervalWait, time.Millisecond*10))
+		It("should return error when the managed resource is not healthy yet (observed generation does not match)", func() {
+			Expect(fakeClient.Create(ctx, mr)).To(Succeed())
+			_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
+				mr.ObjectMeta.Generation = 2
+				mr.Status = resourcesv1alpha1.ManagedResourceStatus{
+					ObservedGeneration: 1,
+				}
+				return nil
+			})
+			Expect(err).To(Not(HaveOccurred()))
 
+			Expect(WaitUntilHealthyAndNotProgressing(ctx, fakeClient, namespace, name)).To(MatchError(ContainSubstring("managed resource test/managed-resource is not healthy")))
+		})
+
+		It("should return error when the managed resource is not healthy yet (ResourcesApplied is not true)", func() {
 			Expect(fakeClient.Create(ctx, mr)).To(Succeed())
-			shouldFail := atomic.Bool{}
-			shouldFail.Store(true)
-			go func() {
-				defer GinkgoRecover()
-				_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 2
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 1,
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 2
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 2,
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 2
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 2,
-						Conditions: []gardencorev1beta1.Condition{
-							{
-								Type:   resourcesv1alpha1.ResourcesApplied,
-								Status: gardencorev1beta1.ConditionTrue,
-							},
+			_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
+				mr.ObjectMeta.Generation = 1
+				mr.Status = resourcesv1alpha1.ManagedResourceStatus{
+					ObservedGeneration: 1,
+					Conditions: []gardencorev1beta1.Condition{
+						{
+							Type:   resourcesv1alpha1.ResourcesApplied,
+							Status: gardencorev1beta1.ConditionFalse,
 						},
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 2
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 2,
-						Conditions: []gardencorev1beta1.Condition{
-							{
-								Type:   resourcesv1alpha1.ResourcesHealthy,
-								Status: gardencorev1beta1.ConditionTrue,
-							},
+					},
+				}
+
+				return nil
+			})
+			Expect(err).To(Not(HaveOccurred()))
+
+			Expect(WaitUntilHealthyAndNotProgressing(ctx, fakeClient, namespace, name)).To(MatchError(ContainSubstring("managed resource test/managed-resource is not healthy")))
+		})
+
+		It("should return error when the managed resource is not healthy yet (ResourcesHealthy is not true)", func() {
+			Expect(fakeClient.Create(ctx, mr)).To(Succeed())
+			_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
+				mr.ObjectMeta.Generation = 1
+				mr.Status = resourcesv1alpha1.ManagedResourceStatus{
+					ObservedGeneration: 1,
+					Conditions: []gardencorev1beta1.Condition{
+						{
+							Type:   resourcesv1alpha1.ResourcesApplied,
+							Status: gardencorev1beta1.ConditionTrue,
 						},
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 1
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 1,
-						Conditions: []gardencorev1beta1.Condition{
-							{
-								Type:   resourcesv1alpha1.ResourcesApplied,
-								Status: gardencorev1beta1.ConditionFalse,
-							},
-							{
-								Type:   resourcesv1alpha1.ResourcesHealthy,
-								Status: gardencorev1beta1.ConditionFalse,
-							},
+						{
+							Type:   resourcesv1alpha1.ResourcesHealthy,
+							Status: gardencorev1beta1.ConditionFalse,
 						},
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 1
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 1,
-						Conditions: []gardencorev1beta1.Condition{
-							{
-								Type:   resourcesv1alpha1.ResourcesApplied,
-								Status: gardencorev1beta1.ConditionTrue,
-							},
-							{
-								Type:   resourcesv1alpha1.ResourcesHealthy,
-								Status: gardencorev1beta1.ConditionTrue,
-							},
+					},
+				}
+
+				return nil
+			})
+			Expect(err).To(Not(HaveOccurred()))
+
+			Expect(WaitUntilHealthyAndNotProgressing(ctx, fakeClient, namespace, name)).To(MatchError(ContainSubstring("managed resource test/managed-resource is not healthy")))
+		})
+
+		It("should return error when the managed resource is not healthy yet (ResourcesProgressing is not false)", func() {
+			Expect(fakeClient.Create(ctx, mr)).To(Succeed())
+			_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
+				mr.ObjectMeta.Generation = 1
+				mr.Status = resourcesv1alpha1.ManagedResourceStatus{
+					ObservedGeneration: 1,
+					Conditions: []gardencorev1beta1.Condition{
+						{
+							Type:   resourcesv1alpha1.ResourcesApplied,
+							Status: gardencorev1beta1.ConditionTrue,
 						},
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				time.Sleep(time.Millisecond * 50)
-
-				_, err = controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
-					mr.ObjectMeta.Generation = 1
-					mr.Status = resourcesv1alpha1.ManagedResourceStatus{
-						ObservedGeneration: 1,
-						Conditions: []gardencorev1beta1.Condition{
-							{
-								Type:   resourcesv1alpha1.ResourcesApplied,
-								Status: gardencorev1beta1.ConditionTrue,
-							},
-							{
-								Type:   resourcesv1alpha1.ResourcesHealthy,
-								Status: gardencorev1beta1.ConditionTrue,
-							},
-							{
-								Type:   resourcesv1alpha1.ResourcesProgressing,
-								Status: gardencorev1beta1.ConditionFalse,
-							},
+						{
+							Type:   resourcesv1alpha1.ResourcesHealthy,
+							Status: gardencorev1beta1.ConditionTrue,
 						},
-					}
-					return nil
-				})
-				Expect(err).To(Not(HaveOccurred()))
-				shouldFail.Store(false)
-			}()
-
-			timeoutCtx, cancel := context.WithTimeout(ctx, time.Second*5)
-			defer cancel()
-			Expect(WaitUntilHealthyAndNotProgressing(timeoutCtx, fakeClient, namespace, name)).To(Succeed())
-			Expect(shouldFail.Load()).To(BeFalse()) // to ensure that the goroutine actually applies all patches
+						{
+							Type:   resourcesv1alpha1.ResourcesProgressing,
+							Status: gardencorev1beta1.ConditionTrue,
+						},
+					},
+				}
+
+				return nil
+			})
+			Expect(err).To(Not(HaveOccurred()))
+
+			Expect(WaitUntilHealthyAndNotProgressing(ctx, fakeClient, namespace, name)).To(MatchError(ContainSubstring("managed resource test/managed-resource is still progressing")))
+		})
+
+		It("should succeed when the managed resource is healthy and not progressing", func() {
+			Expect(fakeClient.Create(ctx, mr)).To(Succeed())
+			_, err := controllerutils.GetAndCreateOrMergePatch(ctx, fakeClient, mr, func() error {
+				mr.ObjectMeta.Generation = 1
+				mr.Status = resourcesv1alpha1.ManagedResourceStatus{
+					ObservedGeneration: 1,
+					Conditions: []gardencorev1beta1.Condition{
+						{
+							Type:   resourcesv1alpha1.ResourcesApplied,
+							Status: gardencorev1beta1.ConditionTrue,
+						},
+						{
+							Type:   resourcesv1alpha1.ResourcesHealthy,
+							Status: gardencorev1beta1.ConditionTrue,
+						},
+						{
+							Type:   resourcesv1alpha1.ResourcesProgressing,
+							Status: gardencorev1beta1.ConditionFalse,
+						},
+					},
+				}
+
+				return nil
+			})
+			Expect(err).To(Not(HaveOccurred()))
+
+			Expect(WaitUntilHealthyAndNotProgressing(ctx, fakeClient, namespace, name)).To(Succeed())
 		})
 	})
 
```

You could apply it with `git apply foo.diff`.

```
% stress -p 16 ./pkg/utils/managedresources/managedresources.test

2m50s: 22352 runs so far, 0 failures
2m55s: 23219 runs so far, 0 failures
3m0s: 24114 runs so far, 0 failures
3m5s: 25012 runs so far, 0 failures
```

**Comment by dimityrmirchev** [comment]
@ialidzhikov Thanks for taking the time to compile the diff. I like your approach for testing this functionality better!

**Review by ialidzhikov — APPROVED** [review]
/lgtm
