### PR TITLE
Fix `kubelet` when `protectKernelDefaults=true`

### LINKED ISSUE #7069: Kubelet stuck in auto reset state when `protectKernelDefaults=true`
**How to categorize this issue?**

/area security
/kind bug

**What happened**:
When creating a shoot with `kubelet` option `protectKernelDefaults=true` and machine image `gardenlinux` my machine nodes stay in a pending state with `kubelet` getting constantly reset and giving the following error:
`Failed to start ContainerManager” err=“[invalid kernel flag: kernel/panic, expected value: 10, actual value: 0, invalid kernel flag: kernel/panic_on_oops, expected value: 1, actual value: 0, invalid kernel flag: vm/overcommit_memory, expected value: 1, actual value: 0`.

**What you expected to happen**:
Kubelet to be in a running state in nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot with `kubelet` option `protectKernelDefaults=true` and machine image `gardenlinux`.

**Anything else we need to know?**:
The bug appears because with `protectKernelDefaults=true` the `kubelet` is not enabled to change the sysctl config to what it needs:
```
kernel.keys.root_maxbytes=25000000
kernel.keys.root_maxkeys=1000000
kernel.panic=10
kernel.panic_on_oops=1
vm.overcommit_memory=1
vm.panic_on_oom=0
```
When `protectKernelDefaults=true`  this config should be set by gardener for the `kubelet` to run.

**Environment**:

- Gardener version: v1.60.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by AleksandarSavchev**
**How to categorize this PR?**

/area security
/kind bug

**What this PR does / why we need it**:
When `protectKernelDefaults` is set to `true` the `kubelet` is not able to set it's needed sysctl configs. This PR adds the needed configs when `protectKernelDefaults` is set to `true`.

**Which issue(s) this PR fixes**:
Fixes #7069

**Special notes for your reviewer**:

**Release note**:

```bugfix user
A bug was fixed where nodes may get stuck in `Pending` state when kubelet's `protectKernelDefaults` is set to `true`.
```

### CODE REVIEW

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go [hunk 1]
```diff
@@ -33,7 +38,21 @@ func (component) Name() string {
...
+		(ctx.KubeletConfigParameters.ProtectKernelDefaults == nil && ctx.KubernetesVersion != nil && version.ConstraintK8sGreaterEqual126.Check(ctx.KubernetesVersion)) {
+		newData += "#Needed configuration by kubelet\n" +
+			"#The kubelet sets these values but it is not able to when protectKernelDefaults=true\n" +
+			"#Ref https://github.com/gardener/gardener/issues/7069\n" +
+			fmt.Sprintf("%s = %s\n", sysctl.VMOvercommitMemory, strconv.Itoa(sysctl.VMOvercommitMemoryAlways)) +
+			fmt.Sprintf("%s = %s\n", sysctl.VMPanicOnOOM, strconv.Itoa(sysctl.VMPanicOnOOMInvokeOOMKiller)) +
+			fmt.Sprintf("%s = %s\n", sysctl.KernelPanicOnOops, strconv.Itoa(sysctl.KernelPanicOnOopsAlways)) +
+			fmt.Sprintf("%s = %s\n", sysctl.KernelPanic, strconv.Itoa(sysctl.KernelPanicRebootTimeout)) +
+			fmt.Sprintf("%s = %s\n", sysctl.RootMaxKeys, strconv.Itoa(sysctl.RootMaxKeysSetting)) +
+			fmt.Sprintf("%s = %s\n", sysctl.RootMaxBytes, strconv.Itoa(sysctl.RootMaxBytesSetting))
```
Comment (timuthy) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go:53]: I assume that these parameters depend or can depend on the use Kubernetes version?! Is there a reference we can cross check in the form of a unit test? Ideally, the unit test fails as soon as something has changed from Kubernetes's side.

Comment (dimityrmirchev) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go:53]: This is also what I think. Maybe we can have a test that will have the current values hardcoded and if something changes in k/k for example in `v1.26.0` this will start to fail when we revendor the new version.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go [hunk 2]
```diff
@@ -15,47 +15,70 @@
 package kernelconfig_test
 
 import (
+	"fmt"
+	"strconv"
+
+	"github.com/Masterminds/semver"
```
Comment (dimityrmirchev) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go]: Please move this in the bottom section of imports so that we keep it consistent.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go [hunk 3]
```diff
@@ -33,7 +38,21 @@ func (component) Name() string {
 	return "kernel-config"
 }
 
-func (component) Config(_ components.Context) ([]extensionsv1alpha1.Unit, []extensionsv1alpha1.File, error) {
+func (component) Config(ctx components.Context) ([]extensionsv1alpha1.Unit, []extensionsv1alpha1.File, error) {
+	var newData = data
+	if (ctx.KubeletConfigParameters.ProtectKernelDefaults != nil && *ctx.KubeletConfigParameters.ProtectKernelDefaults) ||
+		(ctx.KubeletConfigParameters.ProtectKernelDefaults == nil && ctx.KubernetesVersion != nil && version.ConstraintK8sGreaterEqual126.Check(ctx.KubernetesVersion)) {
```
Comment (dimityrmirchev) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go]: I find it not ideal that we have to make this check two times (see [here](https://github.com/gardener/gardener/blob/c38a317bb0dccea0f25546acdffc39e697d0588a/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go#L237)) but I guess this is out of scope of this PR since this can also concern other configurations. Can we also add a comment on this check to clarify why it is made.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go [hunk 4]
```diff
@@ -15,47 +15,70 @@
...
-		BeforeEach(func() {
-			component = New()
-		})
+	BeforeEach(func() {
+		component = New()
+	})
 
-		It("should return the expected units and files", func() {
-			units, files, err := component.Config(components.Context{})
+	DescribeTable("#Config", func(k8sVersion, additionalData string, ProtectKernelDefaults *bool) {
```
Comment (dimityrmirchev) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go]:
```suggestion
	DescribeTable("#Config", func(k8sVersion, additionalData string, protectKernelDefaults *bool) {
```

**Review by dimityrmirchev — CHANGES_REQUESTED** [review]
A few minor comments. Other looks good.

**Comment by dimityrmirchev** [comment]
Maybe also adapt the release note to something like 

A bug was fixed where nodes may stuck in `Pending` state when kubelet's `protectKernelDefaults` is set to `true`.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go (hunk 1 above)
Comment (AleksandarSavchev) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go:53]: Nice catch! I will create such a test.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go [hunk 5]
```diff
@@ -33,7 +38,22 @@ func (component) Name() string {
 	return "kernel-config"
 }
 
-func (component) Config(_ components.Context) ([]extensionsv1alpha1.Unit, []extensionsv1alpha1.File, error) {
+func (component) Config(ctx components.Context) ([]extensionsv1alpha1.Unit, []extensionsv1alpha1.File, error) {
+	var newData = data
+	// checking if ProtectKernelDefaults is set to true or if it is not set, but should be set by default to true since the default settings are applied after this function.
```
Comment (dimityrmirchev) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go]:
```suggestion
	// Gardener sets protectKernelDefaults = true by default for k8s >= 1.26
```

**Review by dimityrmirchev — APPROVED** [review]
/lgtm

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go [hunk 6]
```diff
@@ -15,47 +15,80 @@
...
 	. "github.com/onsi/ginkgo/v2"
 	. "github.com/onsi/gomega"
+	"k8s.io/component-helpers/node/util/sysctl"
 	"k8s.io/utils/pointer"
 )
 
 var _ = Describe("Component", func() {
-	Describe("#Config", func() {
-		var component components.Component
+	var component components.Component
```
Comment (plkokanov) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go]: nit: can you group these definitions in a single `var()` block

**Review by plkokanov — CHANGES_REQUESTED** [review]
Just one nit, otherwise it looks ok.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go (hunk 3 above)
Comment (timuthy) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component.go]: Can you add a helper function for this which can be used [here](https://github.com/gardener/gardener/blob/c38a317bb0dccea0f25546acdffc39e697d0588a/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go#L237) as well?

```
func ProtectedKernelDefaultsEnabled(kubeletConfigParameters, k8sVersion) bool
```

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go [hunk 7]
```diff
@@ -15,47 +15,83 @@
...
+	var (
+		component components.Component
 
-		BeforeEach(func() {
-			component = New()
-		})
+		kubeletSysctlConfigComment = "#Needed configuration by kubelet\n" +
+			"#The kubelet sets these values but it is not able to when protectKernelDefaults=true\n" +
+			"#Ref https://github.com/gardener/gardener/issues/7069\n"
+		kubeletSysctlConfig = kubeletSysctlConfigComment +
```
Comment (timuthy) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go:39]: In all test cases the `hardCodedKubeletSysctlConfig` can be used, so that we can remove `kubeletSysctlConfig`. WDYT?

**Review by timuthy — COMMENTED** [review]
Thanks for the changes. @acumino and I had another look, please see the comments.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go (hunk 7 above)
Comment (AleksandarSavchev) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go:39]: We can remove `kubeletSysctlConfig`, but then I might need to remove the last test as well, which checks if k8s has changed the parameters in a newer version since it will have the same parameters as a previous test.
I feel like even if I leave all test I would prefer that when k8s is updated with new sysctl config to have only 1 test fail.

Comment (timuthy) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kernelconfig/component_test.go:39]: Okay, fine. You could probably rename the test and what its purpose is.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go [hunk 8]
```diff
@@ -147,6 +147,11 @@ var (
 	}
 )
 
+func ProtectedKernelDefaultsEnabled(kubeletConfigParameters components.ConfigurableKubeletConfigParameters, kubernetesVersion *semver.Version) bool {
+	return (kubeletConfigParameters.ProtectKernelDefaults != nil && *kubeletConfigParameters.ProtectKernelDefaults) ||
+		(kubeletConfigParameters.ProtectKernelDefaults == nil && kubernetesVersion != nil && version.ConstraintK8sGreaterEqual126.Check(kubernetesVersion))
+}
+
```
Comment (dimityrmirchev) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go]:
```suggestion
// ShouldEnableProtectKernelDefaults returns true if ProtectKernelDefaults should be enabled in the kubelet's configuration.
func ShouldEnableProtectKernelDefaults(kubeletConfigParameters *components.ConfigurableKubeletConfigParameters, kubernetesVersion *semver.Version) bool {
	if kubeletConfigParameters.ProtectKernelDefaults != nil {
		return *kubeletConfigParameters.ProtectKernelDefaults
	}
	return kubernetesVersion != nil && version.ConstraintK8sGreaterEqual126.Check(kubernetesVersion)
}


```

Comment (dimityrmirchev) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go]: I have some doubts about the name of this function. Maybe the most suitable name will be `ShouldProtectKernelDefaultsBeEnabled`, WDYT? In one case we use it to check if we need to enable the setting and in the other case we use it to determine if this setting will be enabled

Comment (acumino) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go]: WDYT about `IsProtectKernelDefaultsEnabled`?

Comment (dimityrmirchev) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go]: This again is not ideal since the function can return true but the configuration can be empty. Basically

```golang
 if IsProtectKernelDefaultsEnabled(config, version) {
 // here we expect that this is set in the config, but it is actually not because the function returned true cause of >= 1.26 defaulting
 }
```

I would still rather vote for `ShouldProtectKernelDefaultsBeEnabled`

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go [hunk 9]
```diff
@@ -147,6 +147,11 @@ var (
 	}
 )
 
+func ProtectedKernelDefaultsEnabled(kubeletConfigParameters components.ConfigurableKubeletConfigParameters, kubernetesVersion *semver.Version) bool {
```
Comment (timuthy) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go]: Please add a doc string.

I'd also rather see this utility in `pkg/apis/core/v1beta1/helper/helper.go`.

Comment (dimityrmirchev) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go]: Having in mind the result of [pull-gardener-unit](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7088/pull-gardener-unit/1597882096603369472) job I think it is logical that we do not import `pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components` in `pkg/apis/core`. Maybe it will be best if we leave this helper function under `pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet` since it is either way tightly coupled to the kubelet and only relevant for it. WDYT @timuthy ?

Comment (timuthy) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go]: Yes, makes sense 👍 My bad, I thought we operate directly on the API object.

**Review by timuthy — COMMENTED** [review]
/lgtm
@acumino do you want to take another look?

**Review by acumino — APPROVED** [review]
/lgtm
