### PR TITLE
Re-fetch `BackupEntry` secret before removing the `extensions.gardener.cloud/backupentry` finalizer

### LINKED ISSUE #12612: Removal of `extensions.gardener.cloud/backupentry` finalizer fails if `BackupEntry` deletion takes time
**How to categorize this issue?**

/area backup
/area control-plane-migration
/area ops-productivity
/kind regression

**What would you like to be added**:

I would like the `secretMetadata` `metav1.PartialObjectMeta` to be re-fetched before the patch is computed and made to remove the finalizer `extensions.gardener.cloud/backupentry`.

**Why is this needed**:

It was observed that when the `extensions.BackupEntry` deletion takes a long time, the finalizer removal on the secret fails. The reason for this is that the `resourceVersion` of the secret object changes during the deletion of the `extensions.BackupEntry`, and when the patch is computed and the call is made, it fails since the patch was computed on a stale version of the secret.

https://github.com/gardener/gardener/blob/51b88ca758cf8f8b312d9dfbb8143063929f92a0/extensions/pkg/controller/backupentry/reconciler.go#L206-L211

A simple fix is to simply re-fetch the `metav1.PartialObjectMeta` of the secret again, and compute and make the patch.

We observed multiple control plane migrations to fail and not end, due to this; where manual intervention was needed to complete the migration. The errors looked like so:

```
failed to remove finalizer from secret: Operation cannot be fulfilled on secrets \"entry-source-shoot--project--==shoot==--uid\": the object has been modified; please apply your changes to the latest version and try again
```

cc: @plkokanov @adenitiu

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
The `extensions.BackupEntry`'s secret is re-fetched before removing the `extensions.gardener.cloud/backupentry` finalizer, since the Secret's resourceVersion might change while waiting for the extensions.BackupEntry to be deleted.

The change in the secret happens because the reconciler of the `core.BackupEntry` in gardenlet could update it while the backup entry resources on the cloud provider side are being deleted.

**Which issue(s) this PR fixes**:
Fixes #12612

**Special notes for your reviewer**:
This is a re-open of https://github.com/gardener/gardener/pull/12614

I have also written integration tests for the `BackupEntry` controller that include tests for this change. However, I found some flakes when running them with the `stress` tool and need to spend more time to deflake the tests. Ref: https://github.com/gardener/gardener/pull/13776

This fix is required as the problem keeps appearing during control plane migrations and gets more and more annoying. For this reason we could merge this PR now and the PR for the tests a bit later once they have been deflaked.

/cc @renormalize @adenitiu @shafeeqes 

**Release note**:

```bugfix dependency
extension library: An issue causing deletions of `extensions.BackupEntry` to be stuck due to conflicts while removing the finalizer from the BackupEntry Secret is now fixed. This mostly affected the deletion of the source `BackupEntry` during the `restore` phase of control plane migration.
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
Thanks for the fix.
/lgtm

**Comment by ialidzhikov** [comment]
/retitle Re-fetch `BackupEntry` secret before removing the `extensions.gardener.cloud/backupentry` finalizer

File: extensions/pkg/controller/backupentry/reconciler.go [hunk 1]
```diff
@@ -203,6 +203,12 @@ func (r *reconciler) delete(ctx context.Context, log logr.Logger, be *extensions
 		return reconcile.Result{}, err
 	}
 
+	// re-fetch secretMetadata since r.actuator.Delete might take long, during which the Secret's resourceVersion might change.
+	secretMetadata, err := kubernetesutils.GetSecretMetadataByReference(ctx, r.client, &be.Spec.SecretRef)
+	if err != nil && !apierrors.IsNotFound(err) {
+		return reconcile.Result{}, fmt.Errorf("failed to get backup entry secret: %+v", err)
```
Comment (ialidzhikov) [inline extensions/pkg/controller/backupentry/reconciler.go]:
```suggestion
		return reconcile.Result{}, fmt.Errorf("failed to get backup entry secret: %w", err)
```

File: extensions/pkg/controller/backupentry/reconciler.go [hunk 2]
```diff
@@ -176,7 +176,7 @@ func (r *reconciler) delete(ctx context.Context, log logr.Logger, be *extensions
 
 	log.Info("Starting the deletion of BackupEntry")
 
-	secretMetadata, err := kubernetesutils.GetSecretMetadataByReference(ctx, r.client, &be.Spec.SecretRef)
+	_, err := kubernetesutils.GetSecretMetadataByReference(ctx, r.client, &be.Spec.SecretRef)
 	if err != nil {
 		if !apierrors.IsNotFound(err) {
 			return reconcile.Result{}, fmt.Errorf("failed to get backup entry secret: %+v", err)
```
Comment (ialidzhikov) [inline extensions/pkg/controller/backupentry/reconciler.go]:
```suggestion
			return reconcile.Result{}, fmt.Errorf("failed to get backup entry secret: %w", err)
```

File: extensions/pkg/controller/backupentry/reconciler.go [hunk 3]
```diff
@@ -203,6 +203,12 @@ func (r *reconciler) delete(ctx context.Context, log logr.Logger, be *extensions
 		return reconcile.Result{}, err
 	}
 
+	// re-fetch secretMetadata since r.actuator.Delete might take long, during which the Secret's resourceVersion might change.
+	secretMetadata, err := kubernetesutils.GetSecretMetadataByReference(ctx, r.client, &be.Spec.SecretRef)
+	if err != nil && !apierrors.IsNotFound(err) {
```
Comment (ialidzhikov) [inline extensions/pkg/controller/backupentry/reconciler.go]: What happens if the returned err is not found? I think it will be a nil pointer dereference in L212. The `controllerutil.ContainsFinalizer` func tries to get the finalizers of the passed object `o.GetFinalizers()` which should panic with nil pointer dereference.

PS: I know that it is not very likely the Secret to be deleted meanwhile but it is still a possible case the secret to be deleted by a human operator or by a bug somewhere in the system.

File: extensions/pkg/controller/backupentry/reconciler.go [hunk 4]
```diff
@@ -203,6 +203,12 @@ func (r *reconciler) delete(ctx context.Context, log logr.Logger, be *extensions
 		return reconcile.Result{}, err
 	}
 
+	// re-fetch secretMetadata since r.actuator.Delete might take long, during which the Secret's resourceVersion might change.
```
Comment (ialidzhikov) [inline extensions/pkg/controller/backupentry/reconciler.go]:
```suggestion
	// Re-fetch secretMetadata since r.actuator.Delete might take long, during which the Secret's resourceVersion might change.
```

Comment (ialidzhikov) [inline extensions/pkg/controller/backupentry/reconciler.go]: Could you add details about the other controller that updates the Secret and causes its resourceVersion to be updated? Just to make it clear for the reader and to ensure that someone won't try to "optimize" this by removing this piece of code introduced with this PR. You mentioned something like the Secret being updated every 5s by a controller. I would personally appreciate details who (and how frequently) updates the Secret which causes the conflicts.

**Review by ialidzhikov — CHANGES_REQUESTED** [review]
Wrt to the release note, earlier today I changed the categories from `other operator` to `bugfix operator` as we plan to backport this fix.


I suggest also the following release note.

Current:
```bugfix operator
Fixed an issue that caused control plane migrations to get stuck due to the error `failed to remove finalizer from secret: Operation cannot be fulfilled on secrets \"entry-source-shoot--project--==shoot==--uid\": the object has been modified; please apply your changes to the latest version and try again`.
```

Suggestion:
```bugfix operator
extension library: An issue causing control plane migrations to get stuck while deleting the source `extensions.BackupEntry` due to conflics while removing the finalizer from the BackupEntry Secret is now fixed.
```

My motivation:
- Denote that the fix is in the extension library and not in a Gardener core component
- Instead of including a long error message, describe the error as a conflict error.

I am also fine if you prefer to keep it as it is. No strong feelings.

File: extensions/pkg/controller/backupentry/reconciler.go (hunk 3 above)
Comment (ialidzhikov) [reply extensions/pkg/controller/backupentry/reconciler.go]: I guess an easy fix will be 
```diff
diff --git a/extensions/pkg/controller/backupentry/reconciler.go b/extensions/pkg/controller/backupentry/reconciler.go
index 5b6c7db106..5114df6a5b 100644
--- a/extensions/pkg/controller/backupentry/reconciler.go
+++ b/extensions/pkg/controller/backupentry/reconciler.go
@@ -205,7 +205,7 @@ func (r *reconciler) delete(ctx context.Context, log logr.Logger, be *extensions
 
 	// re-fetch secretMetadata since r.actuator.Delete might take long, during which the Secret's resourceVersion might change.
 	secretMetadata, err := kubernetesutils.GetSecretMetadataByReference(ctx, r.client, &be.Spec.SecretRef)
-	if err != nil && !apierrors.IsNotFound(err) {
+	if err != nil {
 		return reconcile.Result{}, fmt.Errorf("failed to get backup entry secret: %+v", err)
 	}
 
```

In the next try, it will enter in https://github.com/gardener/gardener/blob/1f99bb0009b4f58a1f1451b9e7d46819ed6ca842/extensions/pkg/controller/backupentry/reconciler.go#L179-L195 and the deletion will succeed.

**Review by ialidzhikov — APPROVED** [review]
Thank you for addressing the PR review feedback!

/lgtm

**Review by renormalize — APPROVED** [review]
The included comment is very helpful, thanks for taking this PR up again!

**Comment by timuthy** [comment]
@ialidzhikov @plkokanov I kept the release note for the backports, but in the future, I think 'bugfix dependency' would be a more appropriate category. Also their description [here](https://github.com/gardener/gardener/blob/master/docs/operations/upgrade-gardener.md#1-prepare-before-touching-anything):

```
[USER] (end-users or users of Shoot resources and related configuration)
[OPERATOR] (operators deploying Gardener, managing configuration, seed clusters, etc.)
[DEVELOPER] (developers changing or reviewing code in this repository)
[DEPENDENCY] (developers depending on code in this repository (e.g., extension developers))
```

The extension repository again should use 'bugfix operator', since their release fixes the actual issue for operators.

**Comment by ialidzhikov** [comment]
@timuthy , thanks for the pointer. But I am always confused about the `dependency` category. If you check the release notes of past releases and the PRs created by renovate, it is mainly used for dependency updates in Gardener:
Screenshot 2026-01-16 at 9 49 02

IMO these are 2 different usage purposes that cannot be combined.

So, what is the purpose of the `dependency` category? Is it about dependency updates on Gardener side or is it about repositories which depend on Gardener (extensions)?

**Comment by timuthy** [comment]
That's a good point @ialidzhikov 👍 Following the description in [this document](https://github.com/gardener/gardener/blob/master/docs/operations/upgrade-gardener.md#1-prepare-before-touching-anything), the currently used 'dependency' target group for code-dependency updates might be ambiguous.

Let's keep the current release note and discuss this topic separately.
