### PR TITLE
Extend error code mapping

### LINKED ISSUE #5364: Extend error code mapping for user issues
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What would you like to be added**:
We should extend our error code mapping to cover user issues like this one:

```
task "Waiting until shoot worker nodes have been reconciled" failed: Error while waiting for Worker shoot--foo--bar/bar to become ready: error during reconciliation: Error reconciling worker: Failed while waiting for all machine deployments to be ready: 'machine(s) failed: 1 error occurred: "shoot--foo--bar-worker-h1s0l-z1-78587-ksv9l": Cloud provider message - machine codes error: code = [Internal] message = [Create machine "shoot--foo--bar-worker-h1s0l-z1-78587-ksv9l" failed: The following errors occurred: [{SERVICE_ACCOUNT_ACCESS_DENIED  The user does not have access to service account 'shoot--foo--bar@my-project.iam.gserviceaccount.com'.  User: 'shoot--foo--bar@sap-foo-gcp.iam.gserviceaccount.com'.  Ask a project owner to grant you the iam.serviceAccountUser role on the service account [] []}]]'
```

**Why is this needed**:
Reduce ops effort.

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
Extend error code mapping

**Which issue(s) this PR fixes**:
Fixes #5364

**Special notes for your reviewer**:
/cc @shafeeqes 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by shafeeqes — DISMISSED** [review]
/lgtm

File: pkg/apis/core/v1beta1/helper/errors.go [hunk 1]
```diff
@@ -53,13 +53,13 @@ func (e *ErrorWithCodes) Error() string {
...
+	resourcesDepletedRegexp             = regexp.MustCompile(`(?i)(not available in the current hardware cluster|InsufficientInstanceCapacity|SkuNotAvailable|ZonalAllocationFailed|out of stock|Zone.NotOnSale)`)
+	configurationProblemRegexp          = regexp.MustCompile(`(?i)(AzureBastionSubnet|not supported in your requested Availability Zone|InvalidParameter|InvalidParameterValue|notFound|NetcfgInvalidSubnet|InvalidSubnet|Invalid value|KubeletHasInsufficientMemory|KubeletHasDiskPressure|KubeletHasInsufficientPID|violates constraint|no attached internet gateway found|Your query returned no results|PrivateEndpointNetworkPoliciesCannotBeEnabledOnPrivateEndpointSubnet|invalid VPC attributes|PrivateLinkServiceNetworkPoliciesCannotBeEnabledOnPrivateLinkServiceSubnet|unrecognized feature gate|runtime-config invalid key|LoadBalancingRuleMustDisableSNATSinceSameFrontendIPConfigurationIsReferencedByOutboundRule|strict decoder error|not allowed to configure an unsupported|error during apply of object .* is invalid:|OverconstrainedZonalAllocationRequest|duplicate zones|overlapping zones|could not find DNS hosted zone)`)
```
Comment (ialidzhikov) [inline pkg/apis/core/v1beta1/helper/errors.go]: Maybe `could not find DNS hosted zone` should be already tackled in provider-aws?

https://github.com/gardener/gardener-extension-provider-aws/blob/896e7b66af416ecb57657fadd34855b003693b66/pkg/controller/dnsrecord/actuator.go#L147-L159

At least the dnsrecord actuator is already tackling few similar cases and setting proper error codes.

Instead of returning 

```go
fmt.Errorf("could not find DNS hosted zone for name %s", dns.Spec.Name)
```

we could return 

```go
gardencorev1beta1helper.NewErrorWithCodes(fmt.Errorf(...), gardencorev1beta1.ErrorConfigurationProblem)
```

This should be 1 step closer to the target picture.

PS. Currently from the provider extensions only provider-aws returns such `could not find DNS hosted zone` error, so indeed this seems to be the better place to put this error detection.

Comment (rfranzke) [reply pkg/apis/core/v1beta1/helper/errors.go]: Nice catch, I was not aware that this is a custom message from one of our components!
I opened https://github.com/gardener/gardener-extension-provider-aws/pull/522

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/squash
