### PR TITLE
Keep project namespaces after deletion if they existed already

### LINKED ISSUE #2978: Add keep-after-project-deletion annotation when adopting namespaces
**How to categorize this issue?**

/area usability
/kind bug
/priority normal

**What happened**:
In my local setup, gcm cleaned up the `garden` project and also namespace, as I don't have any shoots or other resources in the project.
```
time="2020-10-15T08:42:18+02:00" level=info msg="[STALE PROJECT RECONCILE] Project is being marked as 'stale' because it is not being used by any resource" project=garden
time="2020-10-15T08:42:18+02:00" level=info msg="[STALE PROJECT RECONCILE] Project is stale since 2020-07-13 14:41:09 +0200 CEST" project=garden
time="2020-10-15T08:42:18+02:00" level=info msg="[STALE PROJECT RECONCILE] Project will be deleted at 2020-10-11 14:41:09 +0200 CEST" project=garden
time="2020-10-15T08:42:18+02:00" level=info msg="[STALE PROJECT RECONCILE] Deleting Project now because it's auto-delete timestamp is expired" project=garden
```

**What you expected to happen**:
As the `garden` project is a bit of a special case, I would expect, that it won't be marked as `stale` and deleted by the project stale controller. 

**How to reproduce it (as minimally and precisely as possible)**:
- Delete all resources from the `garden` project
- See gcm mark the project as `stale`
- See gcm delete the project after the configured time in the GCM config

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area usability
/kind enhancement
/priority normal

**What this PR does / why we need it**:
When existing `Namespace`s are adopted for `Project`s then they will now be configured to remain even after the `Project` is being deleted later again. Earlier, such namespaces were also deleted together with the `Project`.

**Which issue(s) this PR fixes**:
Fixes #2978

**Special notes for your reviewer**:

**Release note**:

```improvement operator
When existing `Namespace`s are adopted for `Project`s then they will now be configured to remain even after the `Project` is being deleted later again. Earlier, such namespaces were also deleted together with the `Project`. Please note that this only takes effect for newly adopted project namespaces.
```

### CODE REVIEW

File: pkg/controllermanager/controller/project/project_control_reconcile.go [hunk 1]
```diff
@@ -251,6 +251,10 @@ func (c *defaultControl) reconcileNamespaceForProject(ctx context.Context, garde
 		ns.Labels = utils.MergeStringMaps(ns.Labels, projectLabels)
 		ns.Annotations = utils.MergeStringMaps(ns.Annotations, projectAnnotations)
 
+		if _, ok := ns.Annotations[common.ProjectCausedNamespaceCreation]; !ok {
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_control_reconcile.go]: What about namespaces that have been created before this change and thus don't have a `"project.gardener.cloud/caused-namespace-creation"` annotation?

Comment (rfranzke) [reply pkg/controllermanager/controller/project/project_control_reconcile.go]: Nothing, we cannot handle them because we cannot decide whether they were created by us or by somebody else. I've clarified it in the release note.

Comment (rfranzke) [reply pkg/controllermanager/controller/project/project_control_reconcile.go]: @timuthy I misunderstood your comment earlier. After a sync with @timebertt I've adapted the logic now.

File: pkg/controllermanager/controller/project/project_control_reconcile.go [hunk 2]
```diff
@@ -251,6 +251,12 @@ func (c *defaultControl) reconcileNamespaceForProject(ctx context.Context, garde
 		ns.Labels = utils.MergeStringMaps(ns.Labels, projectLabels)
 		ns.Annotations = utils.MergeStringMaps(ns.Annotations, projectAnnotations)
 
+		// If the project is reconciled for the first time then its observed generation is 0. Only in this case we want
+		// to add the "keep-after-project-deletion" annotation to the namespace when we adopt it.
+		if project.Status.ObservedGeneration == 0 {
+			ns.Annotations = utils.MergeStringMaps(ns.Annotations, map[string]string{common.NamespaceKeepAfterProjectDeletion: "true"})
```
Comment (timebertt) [inline pkg/controllermanager/controller/project/project_control_reconcile.go]: Can this be simplified? Or what am I missing?
```suggestion
			ns.Annotations[common.NamespaceKeepAfterProjectDeletion] = "true"
```

Comment (rfranzke) [reply pkg/controllermanager/controller/project/project_control_reconcile.go]: done

**Review by timebertt — DISMISSED** [review]
Thanks for addressing my suggestions.
/lgtm

**Review by timuthy — DISMISSED** [review]

**Comment by rfranzke** [comment]
@timebertt @timuthy I had to rebase, please check again.

**Review by timebertt — APPROVED** [review]
