### PR TITLE
Fix debootstaping for gardener-kube-scheduler

### LINKED ISSUE #3378: Failed to unbootstrap Seed Cluster (image is required)
/kind bug
/kind regression
/priority normal

**What happened**:
Deletion of Seed cluster does not work.

**What you expected to happen**:
Deletion of Seed cluster to work.

**How to reproduce it (as minimally and precisely as possible)**:

1. Register a v1.18.14 Seed cluster.

2. Make sure that it is successfully bootstrapped and registered.

3. Delete the Seed cluster

4. Make sure that the deboostrap fails with:
```
time="2021-01-12T11:38:54+02:00" level=error msg="Failed to unbootstrap Seed Cluster (image is required)." seed=seed-local
time="2021-01-12T11:39:10+02:00" level=error msg="Failed to unbootstrap Seed Cluster (image is required)." seed=seed-local
time="2021-01-12T11:39:25+02:00" level=error msg="Failed to unbootstrap Seed Cluster (image is required)." seed=seed-local
```

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by mvladev**
**How to categorize this PR?**

/area scalability
/kind bug
/priority normal

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #3378

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/operation/seed/seed.go [hunk 1]
```diff
@@ -883,8 +884,8 @@ func bootstrapComponents(c kubernetes.Interface, namespace string, imageVector i
 	}
 	components = append(components, seedadmission.New(c.Client(), namespace, gsacImage.String(), kubernetesVersion))
 
-	// gardener-seed-scheduler
-	schedulerImage := &imagevector.Image{}
+	// gardener-seed-scheduler. Need dummy image in order to allow debootstrap to work
+	schedulerImage := &imagevector.Image{Name: "dummy", Repository: "dummy", Tag: pointer.StringPtr("dummy")}
```
Comment (rfranzke) [inline pkg/operation/seed/seed.go]: Hm, TBH, I don't like it too much (rather not at all).  Can't we rather improve the validations to make instantiating a new object work with a `non-nil` image? Or, simply remove this entirely:

https://github.com/gardener/gardener/blob/4769e2b102502312967fc9d1c1ab8983eb767104/pkg/operation/seed/scheduler/gardener_kube_scheduler.go#L86-L88

This check isn't too meaningful anyways. If it's empty it doesn't work, yes, but for the validation to be really valuable you'd also have to check that a correct image is used. Hence, Maybe we should just get rid of it entirely instead of such workarounds?

**Comment by mvladev** [comment]
I've reworked the PR. Those checks for images and so are only done during the `Deploy` call (where they are used).

**Review by rfranzke — APPROVED** [review]
/lgtm
Thanks @mvladev, this looks way cleaner!

**Review by timuthy — APPROVED** [review]
