### PR TITLE
Deflake garden controller integration test

### LINKED ISSUE #7200: [Flaky Test] Garden Controller Integration Test Suite
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
• [FAILED] [10.869 seconds]
Garden controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/operator/garden/garden_test.go:44
  [It] should properly maintain the Reconciled condition
  /home/prow/go/src/github.com/gardener/gardener/test/integration/operator/garden/garden_test.go:100
```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7035/pull-gardener-integration/1602607380611207168

**Reason for failure**:

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:

Deflakes one problem in the garden controller integration test: the controller doesn't retry fast enough for the test to succeed.

Co-Authored-By: @rfranzke 

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/7200

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by timebertt** [comment]
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7393/pull-gardener-integration/1618570010458853376 is exactly the other problem from https://github.com/gardener/gardener/issues/7200#issuecomment-1404822598 which is not addressed by this PR.

/test pull-gardener-integration

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
/retest-required

**Comment by timebertt** [comment]
/hold
This PR makes the garden controller test suite even more flaky by provoking the other problem.

**Comment by rfranzke** [comment]
/unhold

I added two more commits implementing what was discovered/suggested in https://github.com/gardener/gardener/issues/7200#issuecomment-1408139325.

Stress results:

```
5m5s: 561 runs so far, 0 failures
```

File: test/utils/operationannotation/operationannotation.go [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+		Named("operationannotation").
+		For(r.ForObject(), builder.WithPredicates(r.hasOperationAnnotation())).
+		WithOptions(controller.Options{
+			MaxConcurrentReconciles: 5,
+			RecoverPanic:            true,
+		}).
+		Complete(r)
+}
+
+// Reconcile finalizes namespaces as soon as they are marked for deletion.
```
Comment (acumino) [inline test/utils/operationannotation/operationannotation.go]: Doc string need to be adapted?

File: test/utils/operationannotation/operationannotation.go [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+		if apierrors.IsNotFound(err) {
+			log.V(1).Info("Object is gone, stop reconciling")
+			return reconcile.Result{}, nil
+		}
+		return reconcile.Result{}, fmt.Errorf("error retrieving object from store: %w", err)
+	}
+
+	if obj.GetAnnotations()[v1beta1constants.GardenerOperation] == "" {
+		return reconcile.Result{}, nil
+	}
```
Comment (acumino) [inline test/utils/operationannotation/operationannotation.go]: Is this check need? predicate for this reconciler ensures that there will always be operation annotation on the object it reconciles.

**Review by acumino — COMMENTED** [review]
This is a nice improvement.
Thanks!
/lgtm
