### PR TITLE
Drop undesired metadata fields from referenced resources in `Shoot`s

### LINKED ISSUE #5554: Shoot referenced resources copies objects with finalizers
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
Gardenlet copies referenced resources in `shoot.spec.resources` to the seed cluster but unfortunately also keeps `metadata.finalizers`, i.e. finalizers for objects set in the Garden cluster are replicated to the object in the seed cluster. Of course, these finalizers are unmanaged (since there if for example no `shoot-reference-controller` in the seed) and the removal of such objects fail.

This blocks the entire shoot deletion.

**What you expected to happen**:
The deletion of replicated referenced objects should succeed.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot with `.spec.resources` and delete it.

/cc @Diaphteiros 

**Environment**:

- Gardener version: v1.41.3

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area ops-productivity
/kind bug
/merge squash

**What this PR does / why we need it**:
We do not care about the metadata like `labels`, `annotations` or `finalizers` (other metadata fields are already removed by the `unstructuredutils.GetObjectByRef` function call) when deploying referenced resources of `Shoot`s to the seed cluster, so let's remove them.

**Which issue(s) this PR fixes**:
Fixes #5554

**Special notes for your reviewer**:
/invite @timuthy 
/cc @Diaphteiros 

**Release note**:

```bugfix operator
An issue has been fixed leading to shoot namespaces in the seed blocking deletion due to referenced objects with finalizers.
```

### CODE REVIEW

**Review by timuthy — DISMISSED** [review]
/lgtm
Thanks a lot 🚀

File: pkg/operation/botanist/resources.go [hunk 1]
```diff
@@ -45,6 +45,8 @@ func (b *Botanist) DeployReferencedResources(ctx context.Context) error {
 			return fmt.Errorf("object not found %v", resource.ResourceRef)
 		}
 
+		obj = unstructuredutils.FilterMetadata(obj, "finalizers", "labels", "annotations")
```
Comment (ialidzhikov) [inline pkg/operation/botanist/resources.go]: Q: can it be the case that the extension relies on a label/annotation on the referenced resource. I don't have in mind existing case but it sounds reasonable to keep the original labels and annotations. WDYT?

**Review by ialidzhikov — COMMENTED** [review]
1 inline question, otherwise lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm
