### PR TITLE
Fix missing update of OSC status

### LINKED ISSUE #39: Failing to populate the command, cloudConfig and units in the OSC status
**How to categorize this issue?**

/area os
/kind bug
/priority 3
/os ubuntu

**What happened**:
Shoot creation is failing with 
```
Error while waiting for OperatingSystemConfig shoot--foo--bar/cloud-config-worker-1-a93d4-downloader to become ready: no cloud config information provided in status.
```

For some reason, the OSC status is not updated properly here https://github.com/gardener/gardener-extension-os-ubuntu/blob/168ece194e252c02bfaf7ecfe867ef7dedf44ac5/vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/reconciler.go#L146 even though the resource is successfully reconciled by the extension. There is no error also in the extension's logs.

**What you expected to happen**:
The osc.status.cloudConfig to be properly populated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant): master
- Extension version: 168ece194e252c02bfaf7ecfe867ef7dedf44ac5
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Observed on Alicloud and OpenStack, but most probably is not cloud specific.
- Others:

### PR DESCRIPTION
**Pull request by BeckerMax**
**How to categorize this PR?**

/kind bug
  /area control-plane

**What this PR does / why we need it**:

https://github.com/gardener/gardener/commit/7ce34ccdf71485be404014526e624667860f4101 introduced a regression that let to the osc Status.Units and Status.CloudConfig not being updated anymore.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-os-ubuntu/issues/39

**Special notes for your reviewer**:
Also refactors the StatusUpdater to use Patch instead of TryUpdateStatus.

I created this PR as a draft because I did not have time to fully test it. The original error is gone though.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
The change looks good, thanks for catching this!

For reference (because it wasn't entirely obvious for me when first looking at it): With #3869, the `OperatingSystemConfig` controller (and all others) are using `TryUpdateStatus` which does a `GET` request first. Consequently, the changes made by the `setOSCStatus` function (setting the `.status.units` and `.status.cloudConfig`) get overwritten immediately: https://github.com/gardener/gardener/blob/893f4042fa3e4a1814ab04b4dd79e9a09e1f914a/extensions/pkg/controller/operatingsystemconfig/reconciler.go#L146-L150

**Comment by rfranzke** [comment]
@vpnachev, as @BeckerMax is off for the rest of the week, will you have some time to validate this change with some OS extension?

**Comment by vpnachev** [comment]
I will try to find some time this week, worst case it will be beginning of the next one.

**Review by vpnachev — DISMISSED** [review]
I have tested with os-gardenlinux.
Just had to add `github.com/gardener/gardener => github.com/BeckerMax/gardener v1.7.1-0.20210601173949-30ed6cfa2bfb` in the replace block.

And it is working as expected.
/lgtm

File: extensions/pkg/controller/status.go [hunk 1]
```diff
@@ -69,7 +69,7 @@ type StatusUpdater interface {
 	// Error updates the last operation of an extension resource when an operation was erroneous.
 	Error(context.Context, extensionsv1alpha1.Object, error, gardencorev1beta1.LastOperationType, string) error
 	// Success updates the last operation of an extension resource when an operation was successful.
-	Success(context.Context, extensionsv1alpha1.Object, gardencorev1beta1.LastOperationType, string) error
+	Success(context.Context, extensionsv1alpha1.Object, gardencorev1beta1.LastOperationType, string, func() error) error
```
Comment (vpnachev) [inline extensions/pkg/controller/status.go]: While the fix do work, I am wondering whether we should implement it this way.
This method is supposed to update only the last operation field with the provided message. 
Can we rather send dedicated update request to add the secret and units to the OSC status instead of re-using the last operation update method?

File: extensions/pkg/controller/operatingsystemconfig/reconciler.go [hunk 2]
```diff
@@ -143,9 +143,10 @@ func (r *reconciler) reconcile(ctx context.Context, osc *extensionsv1alpha1.Oper
...
 
-	setOSCStatus(osc, secret, command, units)
-
-	if err := r.statusUpdater.Success(ctx, osc, operationType, "Successfully reconciled operating system config"); err != nil {
+	if err := r.statusUpdater.Success(ctx, osc, operationType, "Successfully reconciled operating system config", func() error {
+		setOSCStatus(osc, secret, command, units)
+		return nil
+	}); err != nil {
 		return reconcile.Result{}, err
 	}
```
Comment (vpnachev) [inline extensions/pkg/controller/operatingsystemconfig/reconciler.go]:
```suggestion
	patch := client.MergeFrom(osc.DeepCopy())
	setOSCStatus(osc, secret, command, units)
	if err := r.client.Status().Patch(ctx, osc, patch); err != nil {
		_ = r.statusUpdater.Error(ctx, osc, extensionscontroller.ReconcileErrCauseOrErr(err), gardencorev1beta1.LastOperationTypeRestore, "Could not update units and secret ref.")
		return extensionscontroller.ReconcileErr(err)
	}

	if err := r.statusUpdater.Success(ctx, osc, operationType, "Successfully reconciled operating system config"); err != nil {
		return reconcile.Result{}, err
	}
```

**Review by vpnachev — COMMENTED** [review]
Just an example implementation that adds one extra step to ensure the units and secret in the OSC status before updating the last operation of the OSC.

File: extensions/pkg/controller/status.go (hunk 1 above)
Comment (BeckerMax) [reply extensions/pkg/controller/status.go]: Mmh, I have no strong opinion here.
- I liked this implementation because then only one patch request is sent and not two and because it feels better readable to me.
- On the other side the osc is the only user of this mutate parameter and you are right - the `Success` method seems to do more than just one thing now. I will try out your suggestion.

Comment (BeckerMax) [reply extensions/pkg/controller/status.go]: I tested it and the osc status got updated successfully.

**Review by vpnachev — APPROVED** [review]
/lgtm
/merge squash

**Review by rfranzke — APPROVED** [review]
