### PR TITLE
respecting global machine image for v1beta1

### LINKED ISSUE #1496: Gardener does not respect machineImage on shoot level
**What happened**:
When a shoot cluster is created with this manifest(only relevant fields are show)
```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: foo
  namespace: garden-bar
spec:
  ...
  cloud:
    aws:
      machineImage:
        name: non-default-os
        version: 1.2.3
      workers:
      - autoScalerMax: 2
        autoScalerMin: 2
        machineType: m4.xlarge
        maxSurge: 1
        maxUnavailable: 0
        name: worker-coreos
        volumeSize: 50Gi
        volumeType: standard
...
```

The API defaulting sets the worker pool level os to be the default from the cloud profile, not the default defined on shoot level. So if I get the manifest of the created shoot, I will see this:
```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  annotations:
    migration.shoot.gardener.cloud/globalMachineImage: '{"Name":"non-default-os","ProviderConfig":null,"Version":"1.2.3"}'
    migration.shoot.gardener.cloud/workers: '{"worker-coreos":{"ProviderConfig":null,"Volume":null,"Zones":null}}'
  name: foo
  namespace: garden-bar
spec:
  ...
  cloud:
    aws:
      machineImage:
        name: non-default-os
        version: 1.2.3
      workers:
      - autoScalerMax: 2
        autoScalerMin: 2
        machineImage:
          name: coreos
          version: 2135.6.0
        machineType: m4.xlarge
        maxSurge: 1
        maxUnavailable: 0
        name: worker-coreos
        volumeSize: 50Gi
        volumeType: standard
...
```

**What you expected to happen**:
I expect the shoot level defined machine image to be respected.

**How to reproduce it (as minimally and precisely as possible)**:
It is standard Gardener landscape with support for at least 2 operating systems, for example `coreos` and `ubuntu`.

**Anything else we need to know?**:
Most probably this was caused because of the conversions between the old and new API, for reference #1430. 

**Environment**:

- Gardener version: 0.30.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**What this PR does / why we need it**:

The admission plugin before the migration to v1alpha used to default machine images of workers
 - worker.image == nil -> set global machine image
 - if  worker.image == nil  && global machine image == nil  -> take default from CloudProfile

v1alpha1 does not have the concept of global machine images anymore, thus this logic was removed from the admissionplugin.

**This fix sets the global machine image in the v1beta1 defaulting of the shoot to replace the removed functionality in the admissionplugin.**

**Which issue(s) this PR fixes**:
Fixes #1496

**Special notes for your reviewer**:

**Release note**:

```improvement operator
An issue has been fixed that didn't respect the global machine image for v1beta1 Shoots
```

### CODE REVIEW

**Review by timuthy — APPROVED** [review]

File: pkg/apis/garden/v1beta1/defaults_test.go [hunk 1]
```diff
@@ -153,6 +153,38 @@ var _ = Describe("#SetDefaults_Shoot", func() {
 							Expect(shoot.Spec.Kubernetes.KubeControllerManager.NodeCIDRMaskSize).To(Equal(&expectedSize))
 						})
 					})
+
+					Context("global machine image", func() {
+						globalMachineImageName := "jeOs"
+						globalMachineImageVersion := "1.1"
```
Comment (vpnachev) [inline pkg/apis/garden/v1beta1/defaults_test.go:159]: I am just curious how these tests succeed, because the versions must be semver?

File: pkg/apis/garden/v1beta1/defaults_test.go [hunk 2]
```diff
@@ -425,6 +489,38 @@ var _ = Describe("#SetDefaults_Shoot", func() {
...
+								{
+									Worker: v1beta1.Worker{
+										Name: "worker-default",
+									},
+								},
+								{
+									Worker: v1beta1.Worker{
+										MachineImage: &v1beta1.ShootMachineImage{
+											Name:    "coreos",
+											Version: "1.0",
```
Comment (vpnachev) [inline pkg/apis/garden/v1beta1/defaults_test.go]: this one, too

File: pkg/apis/garden/v1beta1/defaults_test.go [hunk 3]
```diff
@@ -425,6 +489,38 @@ var _ = Describe("#SetDefaults_Shoot", func() {
 							Expect(shoot.Spec.Kubernetes.KubeControllerManager.NodeCIDRMaskSize).To(Equal(&expectedSize))
 						})
 					})
+
+					Context("global machine image", func() {
+						globalMachineImageName := "jeOs"
+						globalMachineImageVersion := "1.1"
```
Comment (vpnachev) [inline pkg/apis/garden/v1beta1/defaults_test.go]: this one, too

File: pkg/apis/garden/v1beta1/defaults_test.go [hunk 4]
```diff
@@ -281,6 +313,38 @@ var _ = Describe("#SetDefaults_Shoot", func() {
...
+								{
+									Worker: v1beta1.Worker{
+										Name: "worker-default",
+									},
+								},
+								{
+									Worker: v1beta1.Worker{
+										MachineImage: &v1beta1.ShootMachineImage{
+											Name:    "coreos",
+											Version: "1.0",
```
Comment (vpnachev) [inline pkg/apis/garden/v1beta1/defaults_test.go]: this one, too

File: pkg/apis/garden/v1beta1/defaults_test.go [hunk 5]
```diff
@@ -583,6 +679,38 @@ var _ = Describe("#SetDefaults_Shoot", func() {
...
```
Comment (vpnachev) [inline pkg/apis/garden/v1beta1/defaults_test.go]: this one, too

File: pkg/apis/garden/v1beta1/defaults_test.go [hunk 6]
```diff
@@ -728,6 +856,38 @@ var _ = Describe("#SetDefaults_Shoot", func() {
...
```
Comment (vpnachev) [inline pkg/apis/garden/v1beta1/defaults_test.go]: this one, too

File: pkg/apis/garden/v1beta1/defaults_test.go [hunk 7]
```diff
@@ -728,6 +856,38 @@ var _ = Describe("#SetDefaults_Shoot", func() {
 							Expect(shoot.Spec.Kubernetes.KubeControllerManager.NodeCIDRMaskSize).To(Equal(&expectedSize))
 						})
 					})
+
+					Context("global machine image", func() {
+						globalMachineImageName := "jeOs"
+						globalMachineImageVersion := "1.1"
```
Comment (vpnachev) [inline pkg/apis/garden/v1beta1/defaults_test.go]: this one, too

File: pkg/apis/garden/v1beta1/defaults_test.go [hunk 8]
```diff
@@ -841,6 +1001,38 @@ var _ = Describe("#SetDefaults_Shoot", func() {
...
```
Comment (vpnachev) [inline pkg/apis/garden/v1beta1/defaults_test.go]: this one, too

File: pkg/apis/garden/v1beta1/defaults_test.go [hunk 9]
```diff
@@ -841,6 +1001,38 @@ var _ = Describe("#SetDefaults_Shoot", func() {
...
+								{
+									Worker: v1beta1.Worker{
+										Name: "worker-default",
+									},
+								},
+								{
+									Worker: v1beta1.Worker{
+										MachineImage: &v1beta1.ShootMachineImage{
+											Name:    "coreos",
+											Version: "1.0",
```
Comment (vpnachev) [inline pkg/apis/garden/v1beta1/defaults_test.go]: this one, too

**Review by vpnachev — COMMENTED** [review]
@danielfoehrKn thank you for the fix.
I am just curious about the version numbers used in the tests, as far as I know they must be semver format, but the tests did not fail?

**Comment by vpnachev** [comment]
Please, cherry pick this fix to `release-0.30`

**Comment by timuthy** [comment]
@vpnachev I'll take care of this

File: pkg/apis/garden/v1beta1/defaults_test.go (hunk 1 above)
Comment (danielfoehrKn) [reply pkg/apis/garden/v1beta1/defaults_test.go:159]: Right, a shoot creation would fail with these version numbers.
These are just tests for the defaulting, the semver checks happen in the shoot strategy / storage validation :)

Comment (vpnachev) [reply pkg/apis/garden/v1beta1/defaults_test.go:159]: thanks
