### PR TITLE
Issue 11505: CoreDNS not truly configurable / import *.override not working as intended

### LINKED ISSUE #11505: CoreDNS not truly configurable / import *.override not working as intended
**How to categorize this issue?**
/area networking
/kind bug

**What happened**:
https://github.com/gardener/gardener/blob/master/pkg/component/networking/coredns/coredns.go#L286
defines the default CoreDNS configuration (Corefile) of Shoot clusters.
```
{
  errors
  log . {
      class error
  }
  health {
      lameduck 15s
  }
  ready` + getSearchPathRewrites(c.values.ClusterDomain, c.values.SearchPathRewriteCommonSuffixes) + `
  kubernetes ` + c.values.ClusterDomain + ` in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
      ttl 30
  }
  prometheus :` + strconv.Itoa(portMetrics) + `
  forward . /etc/resolv.conf
  cache 30
  loop
  reload
  loadbalance round_robin
  import custom/*.override
}
import custom/*.server
```

The idea of this configuration as laid out by https://gardener.cloud/docs/gardener/networking/custom-dns-config/ and https://github.com/gardener/gardener/blob/master/docs/usage/networking/custom-dns-config.md is that the 
``` 
import custom/*.override
``` 
in conjunction with the editable configmap "coredns-custom" that gets mounted to /etc/coredns/custom (https://github.com/gardener/gardener/blob/master/pkg/component/networking/coredns/coredns.go#L64) would create a mechanism that allows convenient custom configuration if so desired, while sensible defaults are ensured.

However, the whole construction is based on the assumption that multiple plugin declarations (such as forward or cache) within a server block each override the previous one which just does not hold. 

Instead, each plugin follows its own logic with regard to multiple declarations. For example:
- forward: https://coredns.io/plugins/forward/
Note that a CoreDNS server configured with multiple forward plugins in a server block will evaluate those forward plugins in the order they are listed when serving a request. 
- cache: multiple declarations are not allowed at all. coredns will ignore those.

Unfortunately, the ConfigMap "coredns" is managed by Gardener Resource Manager, so it cannot be changed effectively at all. Ultimately, the intended attempt to make CoreDNS configurable in a Shoot cluster just falls short which is an awful pitty.

**What you expected to happen**:
I would expect that each plugin directive in an override block would override whatever previous definition exists. To give some examples:  

I would expect that the following definition causes coredns to log all requests not just error messages.
```yaml
data:
  foo.override: |
     log . {
       class all
     }
```
but this is not the case. As far as my tests go, multiple declarations of log are just ignored.

I would also expect that 
```yaml
data:
  foo.override: |
     forward . 1.1.1.1
```
overrides the default forwarding directive that uses /etc/resolv.conf. But this is not the case as even the docs of coredns https://coredns.io/plugins/forward/ say.

**How to reproduce it (as minimally and precisely as possible)**:
Has been answered.

**Anything else we need to know?**:
The easiest way to make coredns configurable would be to remove the ConfigMap "coredns" from Gardener ResourceManager and remove "coredns-custom" alltogether. 

**Environment**:

- Gardener version: trunk
- Kubernetes version (use `kubectl version`): any

### PR DESCRIPTION
**Pull request by veith4f**
**How to categorize this PR?**
/area networking
/area bug

**What this PR does / why we need it**:
ConfigMap coredns-custom is imported into CoreDNS Corefile. However, the import is late in the Corefile and ultimately does not meet the expectations raised by:
- https://gardener.cloud/docs/gardener/networking/custom-dns-config/
- https://github.com/gardener/gardener/blob/master/docs/usage/networking/custom-dns-config.md

This fix is an attempt to be consistent with the expectations raised by existing documentation.

**Which issue(s) this PR fixes**:
Fixes #11505  

**Special notes for your reviewer**:
Hello @plkokanov and @ScheererJ. How are things in Walldorf? Allow me to send regards from us guys at plusserver.com. We are using Gardener in our product PSKE (plusserver kubernetes engine) and we would like to extend a big thanks to you for open sourcing the great work you have put in. I am really just starting out with golang and gardener but would like to get my hands dirty. I made a proposition here: https://github.com/gardener/gardener-extension-networking-cilium/issues/495
Feel free to ask me about implementing other things. Cheers guys.

**Release note**:

```
Make ConfigMap coredns-custom behave the way existing documentation suggests.
```

### CODE REVIEW

**Comment by veith4f** [comment]
@ScheererJ I understand your comment https://github.com/gardener/gardener/pull/11522#issuecomment-2684559568. However, I think existing documentation has raised certain user expectations. This fix attempts to meet those expectations. 
I think adding another import *.precedence just uglifies the whole construction. Why would anyone continue to use *.override as soon as *.precedence exists? Why 2 options when 1 does the job? -> KISS

**Comment by ScheererJ** [comment]
/hold

Let's discuss the topic first in #11505.

File: pkg/component/networking/coredns/coredns.go [hunk 1]
```diff
@@ -289,11 +289,7 @@ func (c *coreDNS) computeResourcesData() (map[string][]byte, error) {
 				Namespace: metav1.NamespaceSystem,
 			},
 			Data: map[string]string{
-				configDataKey: `.:` + strconv.Itoa(corednsconstants.PortServer) + ` {
-  errors
-  log . {
-      class error
-  }
+				configDataKey: `.:` + strconv.Itoa(corednsconstants.PortServer) + ` {
```
Comment (ScheererJ) [inline pkg/component/networking/coredns/coredns.go]:
```suggestion
				configDataKey: `.:` + strconv.Itoa(corednsconstants.PortServer) + ` {
```

**Review by ScheererJ — COMMENTED** [review]
Could you please fix the whitespace in the config map and adapt the [tests](https://github.com/gardener/gardener/blob/3b181bacc61a526de24740227f5ca98f39a92424/pkg/component/networking/coredns/coredns_test.go) as well?

Apart from that it looks good.

/unhold

File: pkg/component/networking/coredns/coredns.go (hunk 1 above)
Comment (shepses) [reply pkg/component/networking/coredns/coredns.go]: done

**Comment by ScheererJ** [comment]
Code/test changes look good.

@veith4f Could you please adapt the [documentation](https://github.com/gardener/gardener/blob/master/docs/usage/networking/custom-dns-config.md) as well and add a note of caution/warning with regards to changing the configuration with examples for `log`, `forward` and `cache` plugins? Increasing `log` level can lead to increased load/reduced throughput. Changing the `forward` target may lead to unexpected results. Playing with the `cache` settings can impact the timeframe how long it takes for changes to become visible.

File: docs/usage/networking/custom-dns-config.md [hunk 2]
```diff
@@ -45,6 +45,41 @@ In order for the destination DNS server to be reachable, it must listen on port
 It is important to have the `ConfigMap` keys ending with `*.server` (if you would like to add a new server) or `*.override`
 if you want to customize the current server configuration (it is optional setting both).
 
+## Warning
+Be careful when overriding plugins log, forward or cache.
```
Comment (ScheererJ) [inline docs/usage/networking/custom-dns-config.md]:
```suggestion
Be careful when overriding plugins `log`, `forward` or `cache`.
```

File: docs/usage/networking/custom-dns-config.md [hunk 3]
```diff
@@ -45,6 +45,41 @@ In order for the destination DNS server to be reachable, it must listen on port
 It is important to have the `ConfigMap` keys ending with `*.server` (if you would like to add a new server) or `*.override`
 if you want to customize the current server configuration (it is optional setting both).
 
+## Warning
+Be careful when overriding plugins log, forward or cache. 
+- Increasing log level can lead to increased load/reduced throughput. 
+- Changing the forward target may lead to unexpected results. 
+- Playing with the cache settings can impact the timeframe how long it takes for changes to become visible.
+
+*.override and *.server data points from coredns-custom are imported into Corefile as follows.
```
Comment (ScheererJ) [inline docs/usage/networking/custom-dns-config.md]:
```suggestion
`*.override` and `*.server` data points from `coredns-custom` `ConfigMap` are imported into Corefile as follows.
```

File: docs/usage/networking/custom-dns-config.md [hunk 4]
```diff
@@ -45,6 +45,41 @@ In order for the destination DNS server to be reachable, it must listen on port
...
+Consult plugin specifications from https://coredns.io/plugins/ for potential side-effects.
```
Comment (ScheererJ) [inline docs/usage/networking/custom-dns-config.md]:
```suggestion
Please consult `coredns` [plugin documentation](https://coredns.io/plugins/) for potential side-effects.
```

**Review by ScheererJ — COMMENTED** [review]
Thanks for adapting the documentation. There are only a few nits left.

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve
