### PR TITLE
Validate shoot default dns even if shoot's seed spec is not specified

### LINKED ISSUE #5808: Shoot can takeover DNS domains from the default domain
**How to categorize this issue?**

/area ops-productivity security 
/kind bug

**What happened**:
Gardener allows me to use hostname from the default domain that does not belongs to my project.

**What you expected to happen**:
To be disallowed to takeover DNS domains from the default domain

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a gardener project `bar` with namespace `garden-bar`.
2. Create a shoot with similar spec
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: foo
  namespace: garden-bar
spec:
  dns:
    domain: baz.bar.<default-domain> # The only allowed domain from the default domain should be foo.bar.<default-domain>
```

**Anything else we need to know?**:
If the spec.seedName is not set, gardener-scheduler is failing with 
```json
{
  "level": "error",
  "ts": "2022-04-14T10:46:03.313Z",
  "logger": "controller.shoot-scheduler",
  "msg": "Reconciler error",
  "name": "foo",
  "namespace": "garden-foo",
  "error": "Shoot.core.gardener.cloud \"foo\" is invalid: spec.dns: Invalid value: \"foo\": shoot uses a default domain but does not match expected scheme: <shoot-name>.<project-name>.<default-domain>",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"
}
```

**Environment**:

- Gardener version: f5882800d5821bcc18198da96324bbe013bb1afe (but most probably affect released versions, too)
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area ops-productivity security
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #5808

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: plugin/pkg/shoot/dns/admission.go [hunk 1]
```diff
@@ -158,6 +158,15 @@ func (d *DNS) Admit(ctx context.Context, a admission.Attributes, o admission.Obj
 		return err
 	}
 
+	specPath := field.NewPath("spec")
+	// If shoot uses deafult domain validate domain even though shoot can be assigned to seed
+	// having dns disabled
+	if !helper.ShootUsesUnmanagedDNS(shoot) {
+		if err := assignDefaultDomainIfNeeded(a, shoot, d.projectLister, defaultDomains); err != nil {
```
Comment (plkokanov) [inline plugin/pkg/shoot/dns/admission.go]: Won't this assign a new domain to the Shoot cluster if it doesn't have one? This means that shoot clusters will always have domain names and won't be allowed to be scheduled on a seed that has dns disabled.

File: plugin/pkg/shoot/dns/admission_test.go [hunk 2]
```diff
@@ -676,7 +677,7 @@ var _ = Describe("dns", func() {
 
 				err := admissionHandler.Admit(context.TODO(), attrs, nil)
 
-				Expect(err).To(Not(HaveOccurred()))
+				Expect(err).To(HaveOccurred())
```
Comment (plkokanov) [inline plugin/pkg/shoot/dns/admission_test.go:680]: The test description states "should not reject shoots using a non compliant default domain on updates", but actually the opposite is expected.

File: plugin/pkg/shoot/dns/admission_test.go [hunk 3]
```diff
@@ -796,7 +797,7 @@ var _ = Describe("dns", func() {
 
 					err := admissionHandler.Admit(context.TODO(), attrs, nil)
 
-					Expect(err).To(Not(HaveOccurred()))
+					Expect(err).To(HaveOccurred())
```
Comment (plkokanov) [inline plugin/pkg/shoot/dns/admission_test.go:800]: The test description states "should not reject shoots using a non compliant default domain on updates", but actually the opposite is expected.

**Review by plkokanov — CHANGES_REQUESTED** [review]

File: plugin/pkg/shoot/dns/admission.go (hunk 1 above)
Comment (acumino) [reply plugin/pkg/shoot/dns/admission.go]: If the user-specified DNS in shoot yaml doesn't it mean they want to use it. Also if user specifies DNS it can't be scheduled on DNS disabled seed as this validation will fail https://github.com/gardener/gardener/blob/64869baf1aa7cca708dcb174ba59b2549ecad216/plugin/pkg/shoot/dns/admission.go#L229-L231

File: plugin/pkg/shoot/dns/admission_test.go (hunk 2 above)
Comment (acumino) [reply plugin/pkg/shoot/dns/admission_test.go:680]: It should reject. I will update the test description

File: plugin/pkg/shoot/dns/admission.go (hunk 1 above)
Comment (plkokanov) [reply plugin/pkg/shoot/dns/admission.go]: I meant that if the user does not specify a DNS, it will now always get generated. Previously this only happened if the shoot was scheduled on a seed that enables DNS. 
You can even test this out
1. Create a seed with dns disabled
2. Try to create a shoot that has empty DNS setting and schedule it to the seed from 1.
3. See that the shoot creation fails with:
```
k apply -f local/shoot.yaml 
The Shoot "aws-shoot3" is invalid: spec.dns: Invalid value: core.DNS{Domain:(*string)(0xc005516ef0), Providers:[]core.DNSProvider(nil)}: shoot's .spec.dns section must be nil if seed with disabled DNS is chosen
```

Comment (acumino) [reply plugin/pkg/shoot/dns/admission.go]: @plkokanov PTAL.

Comment (plkokanov) [reply plugin/pkg/shoot/dns/admission.go]: Looks good now, but I think it will be even better if you split `assignDefaultDomainIfNeeded` into two functions - one that checks if a DNS is valid, and one that assigns DNS to the shoot if it is scheduled on a seed with dns Enabled, but shoot.spec.dns=nil

Comment (plkokanov) [reply plugin/pkg/shoot/dns/admission.go:165]: Looks good now, but I think it will be even better if you split `assignDefaultDomainIfNeeded` into two functions - one that checks if a DNS is valid, and one that assigns DNS to the shoot if it is scheduled on a seed with dns Enabled, but shoot.spec.dns=nil

Comment (acumino) [reply plugin/pkg/shoot/dns/admission.go]: @plkokanov PTAL.

File: plugin/pkg/shoot/dns/admission.go [hunk 4]
```diff
@@ -334,11 +342,35 @@ func assignDefaultDomainIfNeeded(a admission.Attributes, shoot *core.Shoot, proj
...
+func checkDefaultDomainFormat(a admission.Attributes, shoot *core.Shoot, projectLister corelisters.ProjectLister, defaultDomains []string) error {
+	project, err := admissionutils.ProjectForNamespaceFromInternalLister(projectLister, shoot.Namespace)
+	if err != nil {
+		return apierrors.NewInternalError(err)
 	}
 
+	shootDomain := shoot.Spec.DNS.Domain
+
 	for _, domain := range defaultDomains {
 		if shootDomain != nil && strings.HasSuffix(*shootDomain, "."+domain) {
```
Comment (plkokanov) [inline plugin/pkg/shoot/dns/admission.go]: You already check whether this is nil before calling the `checkDefaultDomainFormat`. There's no reason to do it again here since the function is not exported.

**Review by plkokanov — CHANGES_REQUESTED** [review]

File: plugin/pkg/shoot/dns/admission.go (hunk 4 above)
Comment (acumino) [reply plugin/pkg/shoot/dns/admission.go]: There we are checking shoot.Spec.DNS here it is shoot.Spec.DNS.Domain. Is it should be checked before calling the function?

Comment (plkokanov) [reply plugin/pkg/shoot/dns/admission.go]: Ah yes, you are right. In that case can you move this nil check outside of the for loop? I think it's not necessary to be checked on every iteration.
```
shootDomain := shoot.Spec.DNS.Domain
if shootDomian == nil {
    return nil
}
```

**Review by plkokanov — APPROVED** [review]
Thanks for applying the comments!
/lgtm
