### PR TITLE
Fix validation and scheduling of shoots with failure tolerance type node

### LINKED ISSUE #6827: Requirements for failureTolerance "node" are not checked on Shoot creation/update
**How to categorize this issue?**

/area high-availability
/kind bug

**What happened**:
It is possible to create shoots with `failureTolerance` type `node` even when there are no seeds with this feature enabled.

_Shoot creation:_
New shoots with failure tolerance type node can be scheduled anywhere, even on seeds having HA disabled. 

_Shoot update:_
Failure tolerance of type node can be activated on shoots which are scheduled on a seed having HA disabled. 

In both cases the shoots run in a non HA setup. **This is not visible for the user**. You can just see it by checking etcd pods in control-plane.
For failure tolerance type zone on the other hand, there is a check which prevents updating the shoot (update case) or at least making them unschedulable (create case).

**What you expected to happen**:
It should not be possible to create/update shoots with failure tolerance type node if there are no suitable seeds.

**How to reproduce it (as minimally and precisely as possible)**:
Create or update shoots in a landscape without any HA seeds with this config:
```
...
spec:
  controlPlane:
    highAvailability:
      failureTolerance:
        type: node
...
```

**Anything else we need to know?**:
I found two places where the availability of `failureTolerance` type `node` on the seed is not checked
- gardener-admission-controller: [ref](https://github.com/gardener/gardener/blob/3c02b2b99184f6789306965256e940a2da71d052/plugin/pkg/shoot/validator/admission.go#L360)
- gardener-scheduler: [ref](https://github.com/gardener/gardener/blob/3c02b2b99184f6789306965256e940a2da71d052/pkg/scheduler/controller/shoot/reconciler.go#L222)

This list might not be complete.

**Environment**:

- Gardener version: v1.57.0

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area high-availability
/kind bug

**What this PR does / why we need it**:
At the moment shoot spec for high-availability control-planes with failure tolerance type node are not checked correctly
a) those shoots could be scheduled on seeds where high-availability feature is not enabled
b) existing shoots on seeds without high-availability feature could be updated to a HA shoot with failure tolerance type node

In both scenarios the shoot will run in a non-HA setup, but remains specified as HA-shoot. This cannot be undone, because the failure tolerance attribute is immutable.

This PR changes these things
- `gardener-apiserver`: Check if `.spec.highAvailability` on the seed is configured, when enabling high-available control-plane on a shoot.
- `gardener-scheduler`: Filter seeds by high-availability feature enabled when a shoot uses high-available control-planes
- `gardener-scheduler`: Remove check for HA feature flag when filtering for multi-zonal seeds, because gardener-scheduler should not schedule HA shoots if the feature is not enabled.

This fix does not solve the root cause of the issue. This will be done in a separate PR which switches `HAControlPlanes` feature flag from `gardenlet` to `gardener-apiserver`.
However, this PR prevents users from specifying HA shoots with failureTolerance type "node" in landscapes which are not prepared for the HA feature yet.

**Which issue(s) this PR fixes**:
Part of #6827 

**Special notes for your reviewer**:

**Release note**:

```breaking user
Shoots with failure tolerance type `node` can be scheduled on seeds with `.spec.highAvailability != nil` only.
```

```breaking operator
`HAControlPlanes` feature flag is removed from `gardener-scheduler`.
```

### CODE REVIEW

File: pkg/apis/core/helper/helpers.go [hunk 1]
```diff
@@ -464,6 +464,20 @@ func SecretBindingHasType(secretBinding *core.SecretBinding, providerType string
 	return sets.NewString(types...).Has(providerType)
 }
 
+// IsHAControlPlaneConfigured returns true if HA configuration for the shoot control plane has been set either
+// via an alpha-annotation or ControlPlane Spec.
+func IsHAControlPlaneConfigured(shoot *core.Shoot) bool {
```
Comment (ialidzhikov) [inline pkg/apis/core/helper/helpers.go:470]: A similar function exists in

https://github.com/gardener/gardener/blob/39059990179c2c33cfa616d17d49c39701f521fb/pkg/apis/core/v1beta1/helper/helper.go#L1409-L1413

We usually try to preserve the functions same across the helpers for the different api versions. So, I would rather suggest reusing the body of the existing function.

Comment (ialidzhikov) [inline pkg/apis/core/helper/helpers.go:470]: You could also add unit tests for the newly introduced helper funcs.

File: pkg/apis/core/helper/helpers.go [hunk 2]
```diff
@@ -483,3 +497,16 @@ func IsMultiZonalSeed(seed *core.Seed) bool {
 	}
 	return seed.Spec.HighAvailability != nil && seed.Spec.HighAvailability.FailureTolerance.Type == core.FailureToleranceTypeZone
 }
+
+// IsHASeedConfigured returns true if HA configuration for the seed system components has been set either via label or spec.
+func IsHASeedConfigured(seed *core.Seed) bool {
```
Comment (ialidzhikov) [inline pkg/apis/core/helper/helpers.go:495]: You could reuse the body of https://github.com/gardener/gardener/blob/39059990179c2c33cfa616d17d49c39701f521fb/pkg/apis/core/v1beta1/helper/helper.go#L1452-L1455.

File: pkg/scheduler/controller/shoot/reconciler.go [hunk 3]
```diff
@@ -217,12 +219,27 @@ func filterSeedsMatchingProviders(cloudProfile *gardencorev1beta1.CloudProfile,
...
+	// for any shoot that is non-HA
+	return seedList, nil
+}
+
 // filterSeedsMatchingMultiZonalAttribute filters seeds by label `seed.gardener.cloud/multi-zonal`,
 // based on whether the shoot requires a multi-zonal control plane or not
 func filterSeedsMatchingMultiZonalAttribute(seedList []gardencorev1beta1.Seed, shoot *gardencorev1beta1.Shoot) ([]gardencorev1beta1.Seed, error) {
-	if !gardenerschedulerfeatures.FeatureGate.Enabled(features.HAControlPlanes) {
-		return seedList, nil
-	}
```
Comment (ialidzhikov) [inline pkg/scheduler/controller/shoot/reconciler.go:225]: As far as I see this is the only usage of the `HAControlPlanes` feature gate in the gardener-scheduler. Can you elaborate why we remove this check now?
If we preserve this, I think we have to clean up also https://github.com/gardener/gardener/blob/18bb09016bb0dd61d5fabdb7a3012220c34d4b5d/docs/deployment/feature_gates.md#L159
and usages of this feature gate in the unit tests.

File: pkg/scheduler/controller/shoot/reconciler.go [hunk 4]
```diff
@@ -217,12 +219,27 @@ func filterSeedsMatchingProviders(cloudProfile *gardencorev1beta1.CloudProfile,
 	return matchingSeeds, nil
 }
 
+// filterHighAvailabilitySeeds filters seeds based on their high-availability configurations
+func filterHighAvailabilitySeeds(seedList []gardencorev1beta1.Seed, shoot *gardencorev1beta1.Shoot) ([]gardencorev1beta1.Seed, error) {
```
Comment (ialidzhikov) [inline pkg/scheduler/controller/shoot/reconciler.go:223]: Is it possible to add a env test to covert this case not only with unit test but also env test test case?

https://github.com/gardener/gardener/blob/52e9635b0bd2009a92d7801e976e4420f6bba3bc/test/integration/scheduler/shoot/scheduler_suite_test.go#L41

Comment (unmarshall) [reply pkg/scheduler/controller/shoot/reconciler.go:223]: We already have https://github.com/gardener/gardener/blob/3cbc43c7000a7f5032f4b75d59d80a1147672bb9/pkg/scheduler/controller/shoot/reconciler.go#L222-L242
Is this not working as expected?

File: plugin/pkg/shoot/validator/admission.go [hunk 5]
```diff
@@ -355,9 +355,13 @@ func (c *validationContext) validateProjectMembership(a admission.Attributes) er
 }
 
 // validateSeedSelectionForHAShoot validates the seed assigned for the shoot based on the following criteria:
-// 1. A HA shoot with failure tolerance of 'zone' can only be scheduled on multi-zonal seeds
-// 2. A HA shoot with failure tolerance of 'node' or a non-HA shoot can be scheduled onto a multi-zonal as well as non-multi-zonal seed.
+// 1. A HA shoot can be scheduled on a seed with HA enabled only
```
Comment (unmarshall) [inline plugin/pkg/shoot/validator/admission.go:358]: This was not the original requirement.
HA shoot with failureTolerance.type = "node" can be scheduled on both non-HA and HA seeds. Is there a change in the requirement?
https://github.com/gardener/gardener/blob/master/docs/proposals/20-ha-control-planes.md#hosting-a-ha-shoot-control-plane-with-node-failure-tolerance also only mentions that to host a HA shoot with "failureTolerance.type = node" a.k.a `single-zone` the only requirement is that it should have at least 3 nodes in a single zone. There was no requirement for the seed to have multiple zones.

File: pkg/scheduler/controller/shoot/reconciler.go (hunk 3 above)
Comment (oliver-goetz) [reply pkg/scheduler/controller/shoot/reconciler.go:225]: This filter removes seeds which are not multi zonal from the set of seeds when the shoot has failure tolerance "zone".
The feature flag can disable this filter, so that seeds which are not multi zonal remain in the set of potential seeds for this shoot.
I do not see any scenario where this is useful, because admission-controller prevents it anyway.
https://github.com/gardener/gardener/blob/8f48339c5b5be7ca96072dbe680b9e7935ebe811/plugin/pkg/shoot/validator/admission.go#L360-L365

File: plugin/pkg/shoot/validator/admission.go (hunk 5 above)
Comment (oliver-goetz) [reply plugin/pkg/shoot/validator/admission.go:358]: As far as I understand it `HAControlPlanes` feature in gardenlet controls the number of replicas of the shoots control plane components rather than the HA configuration of the seeds itself.
I'm able to bootstrap a gardenlet with HA control plane "true on a cluster without and found this in botanist.

https://github.com/gardener/gardener/blob/8f48339c5b5be7ca96072dbe680b9e7935ebe811/pkg/operation/botanist/etcd.go#L268-L273
https://github.com/gardener/gardener/blob/8f48339c5b5be7ca96072dbe680b9e7935ebe811/pkg/operation/botanist/kubeapiserver.go#L303-L305

In all my tests where the gardenlet HA control plane feature was "false", shoots with failure tolerance "node" node have been created with one replica of etcd and apiserver.

File: pkg/scheduler/controller/shoot/reconciler.go (hunk 4 above)
Comment (oliver-goetz) [reply pkg/scheduler/controller/shoot/reconciler.go:223]: It does not filter anything for failure tolerance type node.
This could lead to a scenario where such a shoot is scheduled to a seed where HAControlPlanes is false. 
Gardenlet feature HAControlPlanes controls the number of replicas of etcd and apiserver on shoot (please see my comment below), so a shoot defined with a HA control plane in fact does not have one.

File: plugin/pkg/shoot/validator/admission.go (hunk 5 above)
Comment (timuthy) [reply plugin/pkg/shoot/validator/admission.go:358]: @unmarshall we discussed this today and essentially yes, the seed tolerance is orthogonal to the shoot CP tolerance.

However, we already defined that a seed must have tolerance `zone` to schedule shoot with tolerance `zone` -> it would be consequent to have an equivalent requirement for `node` level.
Considering the `alpha` status of the feature, we can still ship this incompatible requirement and if it turns out to be "impractical", we'll simply relax the restriction again. This won't be possible at a later point in time.

File: pkg/apis/core/helper/helpers.go (hunk 1 above)
Comment (oliver-goetz) [reply pkg/apis/core/helper/helpers.go:470]: done

Comment (oliver-goetz) [reply pkg/apis/core/helper/helpers.go:470]: I copied the tests too.

File: pkg/apis/core/helper/helpers.go (hunk 2 above)
Comment (oliver-goetz) [reply pkg/apis/core/helper/helpers.go:495]: done

File: plugin/pkg/shoot/validator/admission.go (hunk 5 above)
Comment (unmarshall) [reply plugin/pkg/shoot/validator/admission.go:358]: Ok in other words:
- for a shoot with controlPlane.failureTolerance.type = zone => seed should have spec.highAvailability.type = zone
- for a shoot with controlPlane.failureTolerance.type = node => seed should have spec.highAvailability.type = node or zone
@timuthy  Till now we have only set failureTolerance.type = zone for the seed. Also keep in mind that there is no equivalent label for seed which has a failureTolerance.type of node.

File: pkg/scheduler/controller/shoot/reconciler.go (hunk 4 above)
Comment (unmarshall) [reply pkg/scheduler/controller/shoot/reconciler.go:223]: >This could lead to a scenario where such a shoot is scheduled to a seed where HAControlPlanes is false.

Ok. Can we not additionally check the feature flag. Ideally adding a HA spec to the Seed/ManagedSeed is orthogonal to the feature being enabled. So an additional feature flag check would suffice, WDYT? 

>Gardenlet feature HAControlPlanes controls the number of replicas of etcd and apiserver on shoot 

Yes that is one of the two checks that controls is. The other check being that the HA spec has been defined for the shoot.

File: pkg/scheduler/controller/shoot/reconciler.go (hunk 3 above)
Comment (ialidzhikov) [reply pkg/scheduler/controller/shoot/reconciler.go:225]: Ok, thanks for explaining! Sounds reasonable.

@timuthy, can you confirm that we can drop this usage of the `HAControlPlanes` feature gate in the gardener-scheduler? Asking just to make sure we don't miss anything.

If we proceed with removal of the feature gate usage, then we have to also adapt 

https://github.com/gardener/gardener/blob/18bb09016bb0dd61d5fabdb7a3012220c34d4b5d/docs/deployment/feature_gates.md#L159

and drop usages like
https://github.com/gardener/gardener/blob/db1e5d45618b877014dfbe8294f075580d38ae61/pkg/scheduler/controller/shoot/reconciler_test.go#L208

from the unit test.

File: pkg/scheduler/controller/shoot/reconciler.go (hunk 4 above)
Comment (ialidzhikov) [reply pkg/scheduler/controller/shoot/reconciler.go:223]: This comment was a little bit "hijacked". 😅 

My initial suggest was to add new test cases to the scheduler env test that verify:
- HA Shoot with `node` failureTolerance type will fail to be scheduled if there are no HA Seeds with failureTolerance type `node` or `zone`
- HA Shoot with `node` failureTolerance type will succeed to be scheduled when there is a HA Seed with failureTolerance type `node`

File: pkg/scheduler/controller/shoot/reconciler.go [hunk 6]
```diff
@@ -142,6 +140,10 @@ func determineSeed(
 	if err != nil {
 		return nil, err
 	}
+	filteredSeeds, err = filterHighAvailabilitySeeds(filteredSeeds, shoot)
```
Comment (timuthy) [inline pkg/scheduler/controller/shoot/reconciler.go:143]: As discussed, please also adjust `docs/concepts/scheduler.md` to the changes here.

File: pkg/scheduler/controller/shoot/reconciler.go (hunk 3 above)
Comment (timuthy) [reply pkg/scheduler/controller/shoot/reconciler.go:225]: As discussed, fine for me to remove the feature gate from the scheduler. Please also add a proper release note.

File: plugin/pkg/shoot/validator/admission_test.go [hunk 7]
```diff
@@ -1262,9 +1262,26 @@ var _ = Describe("validator", func() {
...
+
+					It("reject allow scheduling of single-zonal HA shoot identified by alpha annotation on seeds where high-availability feature is not enabled", func() {
+						shoot.Annotations = make(map[string]string)
+						shoot.ObjectMeta.Annotations[v1beta1constants.ShootAlphaControlPlaneHighAvailability] = v1beta1constants.ShootAlphaControlPlaneHighAvailabilitySingleZone
+						attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, nil)
+						err := admissionHandler.Admit(ctx, attrs, nil)
+						Expect(err).To(BeForbiddenError())
+					})
+
 					It("should allow scheduling of single-zonal HA shoot identified by alpha annotation on non multi-zonal seeds", func() {
```
Comment (timuthy) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
					It("should allow scheduling of single-zonal HA shoot identified by alpha annotation on single-zonal seeds", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 8]
```diff
@@ -1273,6 +1290,7 @@ var _ = Describe("validator", func() {
 					It("should allow scheduling of single-zonal HA shoot identified by shoot ControlPlane Spec on non multi-zonal seeds", func() {
```
Comment (timuthy) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
					It("should allow scheduling of single-zonal HA shoot identified by shoot ControlPlane Spec on single-zonal seeds", func() {
```

**Review by timuthy — CHANGES_REQUESTED** [review]
Thanks for the pull request. Some minor comments from our review round.
Please also add breaking release notes for:
- `node` shoots can only be scheduled onto `node` seeds
- `HAControlPlane` feature gate was removed from scheduler

File: pkg/scheduler/controller/shoot/reconciler.go (hunk 4 above)
Comment (oliver-goetz) [reply pkg/scheduler/controller/shoot/reconciler.go:223]: There are some new env tests for the scenario. I reworked the existing env tests for high availability too. They did not work properly, because the `seed` and `shoot` objects were changed after they have been created on the api-server.

Additionally, I added some tests for HA and minimal distance scheduler and general minimal distance tests.

I might have found an error in the minimal distance calculation. In my opinion [this test](https://github.com/oliver-goetz/gardener/blob/5c3b5f1128429aea2950770f68f6e781f530bc5e/test/integration/scheduler/shoot/scheduler_test.go#L241-L256) should fail, because `eu-west-1` is closer to `us-east-2` than `eu-east-2`. This would be something for a different PR though.

**Comment by oliver-goetz** [comment]
I just noticed, that in the current stage the `gardenlet` feature flag `HAControlPlanes` is rather confusing than useful.
When we ensure that HA shoots run on seeds where `.spec.highAvailability != nil` we could determine the number of replicas for etcd and friends ~~by this property too~~ from `shoot.spec.controlPlane.highAvailability`.

**Comment by timuthy** [comment]
> I just noticed, that in the current stage the `gardenlet` feature flag `HAControlPlanes` is rather confusing than useful. When we ensure that HA shoots run on seeds where `.spec.highAvailability != nil` we could determine the number of replicas for etcd and friends by this property too.

I kind of agree as soon as we have the "global" feature gate, i.e. the feature gate at the Apiserver level.

However, the statement that the number of replicas is derived from `seed.spec.highAvailability != nil` is not true. This still needs to be decided based on the shoot configuration (see [this helper function](https://github.com/gardener/gardener/blob/486cf716a47bc84d37e328558e62d4d8f2d375e6/pkg/apis/core/v1beta1/helper/helper.go#L1411)). The reason is that there can still be non-HA shoots on HA seed clusters.

Do we want to continue with this PR as it is and create a new PR wrt the Apiserver feature gate and Gardenlet feature gate removal?

**Comment by oliver-goetz** [comment]
I did not write down what I really meant and corrected my statement of my previous post now 😅

**Comment by oliver-goetz** [comment]
@timuthy and me agreed to switch HAControlPlane feature flag from gardenlet to gardener-apiserver in a separate PR. 
It will be easier to understand the release notes and we won't have an orphaned feature flag for a while.

File: docs/concepts/scheduler.md [hunk 9]
```diff
@@ -35,7 +35,8 @@ The following **sequence** describes the steps involved to determine a seed cand
    * having `.spec.settings.shootDNS.enabled=false` (only if the shoot specifies a DNS domain or does not use the `unmanaged` DNS provider)
    * whose taints (`.spec.taints`) are tolerated by the `Shoot` (`.spec.tolerations`)
    * whose capacity for shoots would not be exceeded if the shoot is scheduled onto the seed, see [Ensuring seeds capacity for shoots is not exceeded](#ensuring-seeds-capacity-for-shoots-is-not-exceeded)
-   * which are labelled with `seed.gardener.cloud/multi-zonal` if feature gate `HAControlPlanes` is turned on and shoot requests a high available control plane.
+   * which have a `.spec.highAvailability` configuration if shoot requests a high available control plane.
+   * which are labelled with `seed.gardener.cloud/multi-zonal` or having a `.spec.highAvailability.failureTolerance.type=node` specification if shoot requests a high available control plane with failureTolerance type `zone`.
```
Comment (timuthy) [inline docs/concepts/scheduler.md]:
```suggestion
   * which are labelled with `seed.gardener.cloud/multi-zonal` or having a `.spec.highAvailability.failureTolerance.type=zone` specification if shoot requests a high available control plane with failureTolerance type `zone`.
```

File: docs/concepts/scheduler.md [hunk 10]
```diff
@@ -35,7 +35,8 @@ The following **sequence** describes the steps involved to determine a seed cand
    * having `.spec.settings.shootDNS.enabled=false` (only if the shoot specifies a DNS domain or does not use the `unmanaged` DNS provider)
    * whose taints (`.spec.taints`) are tolerated by the `Shoot` (`.spec.tolerations`)
    * whose capacity for shoots would not be exceeded if the shoot is scheduled onto the seed, see [Ensuring seeds capacity for shoots is not exceeded](#ensuring-seeds-capacity-for-shoots-is-not-exceeded)
-   * which are labelled with `seed.gardener.cloud/multi-zonal` if feature gate `HAControlPlanes` is turned on and shoot requests a high available control plane.
+   * which have a `.spec.highAvailability` configuration if shoot requests a high available control plane.
```
Comment (timuthy) [inline docs/concepts/scheduler.md]:
```suggestion
   * which have a `.spec.highAvailability` configuration (or `seed.gardener.cloud/multi-zonal` label) if shoot requests a high available control plane.
```

File: test/integration/scheduler/shoot/scheduler_test.go [hunk 11]
```diff
@@ -354,3 +479,17 @@ func createShoot(providerType, cloudProfile, region string, dnsDomain *string) *
 	})
 	return shoot
 }
+
+func getHighAvailabilityType(failureToleranceType string) *gardencorev1beta1.HighAvailability {
```
Comment (timuthy) [inline test/integration/scheduler/shoot/scheduler_test.go]:
```suggestion
func getHighAvailabilityWithType(failureToleranceType string) *gardencorev1beta1.HighAvailability {
```

File: test/integration/scheduler/shoot/scheduler_test.go [hunk 12]
```diff
@@ -354,3 +479,17 @@ func createShoot(providerType, cloudProfile, region string, dnsDomain *string) *
...
+	return &gardencorev1beta1.HighAvailability{
+		FailureTolerance: gardencorev1beta1.FailureTolerance{
+			Type: gardencorev1beta1.FailureToleranceType(failureToleranceType),
+		},
+	}
+}
+
+func getControlPlaneType(failureToleranceType string) *gardencorev1beta1.ControlPlane {
```
Comment (timuthy) [inline test/integration/scheduler/shoot/scheduler_test.go]:
```suggestion
func getControlPlaneWithType(failureToleranceType string) *gardencorev1beta1.ControlPlane {
```

File: pkg/scheduler/controller/shoot/reconciler.go (hunk 4 above)
Comment (timuthy) [reply pkg/scheduler/controller/shoot/reconciler.go:223]: > I might have found an error in the minimal distance calculation. In my opinion [this test](https://github.com/oliver-goetz/gardener/blob/5c3b5f1128429aea2950770f68f6e781f530bc5e/test/integration/scheduler/shoot/scheduler_test.go#L241-L256) should fail, because eu-west-1 is closer to us-east-2 than eu-east-2. This would be something for a different PR though.

(Probably) makes sense. Reading the [implementation details](https://github.com/gardener/gardener/blob/master/docs/concepts/scheduler.md#strategies) though, I'd say that this is expected. You can open an issue and link @mandelsoft, who can provider provide more input 🙂

**Review by timuthy — CHANGES_REQUESTED** [review]
Thanks for the amendments, just some smaller changes are required from my point of view.

In addition, I wondered about the release notes:

```bugfix user
Shoots with failure tolerance type node can be scheduled on seeds with `.spec.highAvailability != nil` only.
```

--> IMO, this is the actual **breaking change**.

```breaking user
Existing shoots with failure tolerance type node on seeds where `.spec.highAvailability` is not specified cannot be changed unless it becomes configured.
```

--> Can you explain what is meant by this statement, i.e. what exactly cannot be changed and how is this PR involved? 👀

**Comment by oliver-goetz** [comment]
> Thanks for the amendments, just some smaller changes are required from my point of view.
> 
> In addition, I wondered about the release notes:
> 
> ```
> Shoots with failure tolerance type node can be scheduled on seeds with `.spec.highAvailability != nil` only.
> ```
> 
> --> IMO, this is the actual **breaking change**.

That's probably easier to understand. We could tag this change as `breaking` and remove the following one, which might be hard to understand anyway.
WDYT?

> ```
> Existing shoots with failure tolerance type node on seeds where `.spec.highAvailability` is not specified cannot be changed unless it becomes configured.
> ```
> 
> --> Can you explain what is meant by this statement, i.e. what exactly cannot be changed and how is this PR involved? 👀

Since release v1.56 you could create shoots with `.spec.controlPlane.highAvailability,failureTolerance.type=node` on any seed in any landscape.
When this PR is merged `gardener-admission-controller` forbids creating/updating shoots on seeds where `.spec.highAvailability == nil`.
Thus, all such shoots which have been created on those seeds before the PR was applied cannot be updated anymore, unless their seed config was changed to `.spec.highAvailability,failureTolerance.type=[node/zone]`

**Review by timuthy — COMMENTED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
Wrt to https://github.com/gardener/gardener/pull/6833#issuecomment-1284576044, I see 4 Shoots on 4 different Seeds that specify `.spec.controlPlane.highAvailability,failureTolerance.type=node` in one of our landscapes.
What is the plan for these Shoots to prevent gardener-apiserver failing any update request for them? Make the corresponding seeds HA with failureTolerance type `node`?

**Comment by ialidzhikov** [comment]
On other landscape there are 378 Shoots that specify `.spec.controlPlane.highAvailability,failureTolerance.type=node`.

**Comment by ialidzhikov** [comment]
One potential way to prevent blocking updates on existing Shoots with `.spec.controlPlane.highAvailability,failureTolerance.type=node` would be to execute https://github.com/gardener/gardener/blob/40b0bf10522e53c55ceaf1b361a4d016a94fe741/plugin/pkg/shoot/validator/admission.go#L495-L497 only when Shoot is being scheduled or is being rescheduled https://github.com/gardener/gardener/blob/40b0bf10522e53c55ceaf1b361a4d016a94fe741/plugin/pkg/shoot/validator/admission.go#L375

**Comment by plkokanov** [comment]
@ialidzhikov good point. Tbh I was a bit curious why that validation isn't done only in those cases in the first place.

**Comment by oliver-goetz** [comment]
> @ialidzhikov good point. Tbh I was a bit curious why that validation isn't done only in those cases in the first place.

You can migrate an existing non-HA shoot to a HA shoot by specifying `.spec.controlPlane.highAvailability.failureTolerance.type`. The shoot does not have to be rescheduled in this case. That might be the reason why the check is running on any update.

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Review by timuthy — COMMENTED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
We should close the cherry-picks. I don't think we want to cherry-pick the 2 breaking changes.
