### PR TITLE
Fix ManagedResource health checks

### LINKED ISSUE #5357: Failing system components are not reported in `ManagedResource` and `Shoot` conditions
**How to categorize this issue?**

/area robustness ops-productivity monitoring
/kind bug

**What happened**:
We saw failing `kube-proxy` `Pod`s in a `Shoot`'s `kube-system` namespace. Their `status`es were as follows:

```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-27T22:27:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-01-31T14:44:56Z"
    message: 'containers with unready status: [kube-proxy]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-01-31T14:44:56Z"
    message: 'containers with unready status: [kube-proxy]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-01-27T22:27:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://0837dd14c071a6b57cb12ceb9c61a9fbb29e3c43e584103f6caaf2830e604879
    image: k8s.gcr.io/kube-proxy:v1.21.7
    lastState:
      terminated:
        containerID: containerd://0837dd14c071a6b57cb12ceb9c61a9fbb29e3c43e584103f6caaf2830e604879
        exitCode: 1
        finishedAt: "2022-01-31T15:00:15Z"
        reason: Error
        startedAt: "2022-01-31T15:00:15Z"
    name: kube-proxy
    ready: false
    restartCount: 1046
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=kube-proxy pod=kube-proxy-operator-v1.21.7-7djlq_kube-system(95d839a3-85f6-4c7f-a7f4-e8b719a1e88e)
        reason: CrashLoopBackOff
[...]
```

The `DaemonSet`s `status`es were as follows:

```yaml
status:
  currentNumberScheduled: 4
  desiredNumberScheduled: 4
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  numberUnavailable: 1
  observedGeneration: 1
  updatedNumberScheduled: 4
```

However, the `shoot-core` `ManagedResource` in the shoot's namespace in the seed was not reporting any issues:

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-01-27T22:33:17Z"
    lastUpdateTime: "2022-01-27T22:33:17Z"
    message: All resources are healthy.
    reason: ResourcesHealthy
    status: "True"
    type: ResourcesHealthy
  - lastTransitionTime: "2022-01-27T22:33:17Z"
    lastUpdateTime: "2022-01-27T22:33:17Z"
    message: All resources are applied.
    reason: ApplySucceeded
    status: "True"
    type: ResourcesApplied
```

Consequently, the `Shoot`'s `SystemComponentsHealthy` condition had status `True`.

**What you expected to happen**:
The `ResourcesHealthy` condition part of the `ManagedResource` should evaluate to `False`, eventually causing the `Shoot's `SystemComponentsHealthy` condition evaluating to `False`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a shoot
2. Manipulate the `gardener-resource-manager` deployment in the control plane: set `--sync-period=10m` and `--health-sync-period=10s`. This makes it easier to reproduce and observe the issue.
```bash
k -n shoot--local--local edit deploy gardener-resource-manager
```
3. Break some system component, e.g. kube-proxy, with the following command:
```bash
k -n kube-system set image daemonset kube-proxy-local-v1.23.1 kube-proxy=nginx
```
4. Observe that neither the respective ManagedResource nor the Shoot itself turn to an unhealthy status.

**Anything else we need to know?**:
~~It seems that the [`health.CheckDaemonSet`](https://github.com/gardener/gardener/blob/ca661c0502eb1f885a2ac3793913025788d5102d/pkg/utils/kubernetes/health/daemonset.go#L45-L67) function is not precise enough to cover such situations.~~ not true, see https://github.com/gardener/gardener/issues/5357#issuecomment-1040150204

**Environment**:

- Gardener version: v1.38.4
- Kubernetes version (use `kubectl version`): v1.21.7

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area robustness ops-productivity monitoring
/kind bug

**What this PR does / why we need it**:

Fix ManagedResource health checks.
If target cache is disabled, `TypeMeta` is unset (when reading structured objects
directly from the API server). Fix the wrong assumption in `CheckHealth`.

Also:
- cleanup other code making the same wrong assumption
- add the missing unit tests
- document this learning in the client developer guideline
- Distinguish between not checked and failed health checks

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/5357

**Special notes for your reviewer**:

/squash

**Release note**:

```bugfix user
Fixed a bug, that broken Shoot system components didn't cause failing Shoot health checks.
```

### CODE REVIEW

**Comment by timebertt** [comment]
I used the reproduction steps from https://github.com/gardener/gardener/issues/5357 to verify that this PR fixes the issue.
Tomorrow, I will add unit tests and integration tests accordingly.

File: pkg/resourcemanager/controller/health/health_checker.go [hunk 1]
```diff
@@ -29,74 +32,93 @@ import (
...
+	// https://github.com/kubernetes/kubernetes/issues/80609 and https://github.com/gardener/gardener/issues/5357#issuecomment-1040150204.
+	// Instead of using GetObjectKind(), we use the scheme to figure out the GroupVersionKind which works for both typed
+	// and unstructured objects.
+	gvk, err := apiutil.GVKForObject(obj, scheme)
+	if err != nil {
+		if runtime.IsNotRegisteredError(err) {
+			// types that this function runs health checks on must be registered in the given scheme
+			// if the scheme doesn't recognize it the object, skip the check as we probably don't have a corresponding health check for it
+			// TODO: probably we should have a dedicated scheme for this func in order to prevent regressions when changing the
+			// target client scheme.
```
Comment (timebertt) [inline pkg/resourcemanager/controller/health/health_checker.go]: The problem I'm having is: the function basically relies on the given scheme for doing its job. If a scheme is passed without the needed types in it, the function will silently skip the health checks.
This means, we can't be sure that the function correctly works in unit tests, because we are depending on the scheme that is plumbed through in the controller.
A dedicated scheme for this func would allow us to verify functionality in an encapsulated manner.

However, with a dedicated scheme we would need to add types to it, every time we want to cover more objects with health checks. But I think, this should be fine.

WDYT @rfranzke?

Comment (rfranzke) [reply pkg/resourcemanager/controller/health/health_checker.go]: > However, with a dedicated scheme we would need to add types to it, every time we want to cover more objects with health checks. But I think, this should be fine.

When we had the unit/integration tests then we would probably add a new test case when we cover more objects with health checks, I assume/expect. Consequently, if somebody misses adding the respective type to this dedicated scheme then the test would fail, right? In this case, I think it's fine to go with this approach.

Comment (timebertt) [reply pkg/resourcemanager/controller/health/health_checker.go]: Yes, exactly. Ok, then I will go for it :)

**Comment by timebertt** [comment]
This is ready now.
I will open a dedicated PR including a new integration test as part of https://github.com/gardener/gardener/issues/4805 tomorrow.

File: pkg/resourcemanager/controller/health/reconciler.go [hunk 2]
```diff
@@ -154,12 +154,20 @@ func (r *reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
...
 			var (
 				reason  = ref.Kind + "Unhealthy"
 				message = fmt.Sprintf("%s %q is unhealthy: %v", ref.Kind, objectKey.String(), err)
 			)
 
+			if !checked {
+				// there was an error executing the health check (which is different than a failed health check)
+				// handle it separately and log it prominently
+				reason = "HealthCheckError"
+				message = fmt.Sprintf("Error executing health check for %s %q: %v", ref.Kind, objectKey.String(), err)
```
Comment (rfranzke) [inline pkg/resourcemanager/controller/health/reconciler.go:167]: If the GVK is not registered then `err` is `nil`, this will generate a strange message here, or?

File: pkg/utils/kubernetes/health/job_test.go [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+	})
+
+	It("should return an error if JobFailed is True", func() {
+		job := &batchv1.Job{Status: batchv1.JobStatus{
+			Conditions: []batchv1.JobCondition{{
+				Type:   batchv1.JobFailed,
+				Status: corev1.ConditionTrue,
+			}},
+		}}
+		Expect(health.CheckJob(job)).To(MatchError(ContainSubstring("condition \"Failed\"")))
```
Comment (rfranzke) [inline pkg/utils/kubernetes/health/job_test.go]: Nit:

```suggestion
		Expect(health.CheckJob(job)).To(MatchError(ContainSubstring(`condition "Failed"`)))
```

File: pkg/resourcemanager/controller/health/health_suite_test.go [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+import (
+	"testing"
+
+	. "github.com/onsi/ginkgo/v2"
+	. "github.com/onsi/gomega"
+)
+
+func TestHealth(t *testing.T) {
+	RegisterFailHandler(Fail)
+	RunSpecs(t, "Health Controller Suite")
```
Comment (rfranzke) [inline pkg/resourcemanager/controller/health/health_suite_test.go:26]:
```suggestion
	RunSpecs(t, "ResourceManager Health Controller Suite")
```

File: docs/development/kubernetes-clients.md [hunk 5]
```diff
@@ -92,6 +92,12 @@ _Important characteristics of controller-runtime clients:_
...
   - Therefore, if you need to use the same in-memory object in multiple goroutines concurrently (e.g., shared state), remember to leverage proper synchronization techniques like channels, mutexes, `atomic.Value` and/or copy the object prior to use. The average controller however, will not need to share in-memory API objects between goroutines, and it's typically an indicator that the controller's design should be improved.
+- The client decoder erases the object's `TypeMeta` (`apiVersion` and `kind` fields) after retrieval from the API server, see [kubernetes/kubernetes#80609](https://github.com/kubernetes/kubernetes/issues/80609), [kubernetes-sigs/controller-runtime#1517](https://github.com/kubernetes-sigs/controller-runtime/issues/1517).
+  Unstructured and metadata-only requests objects are an exception to this, because the contained `TypeMeta` is the only way to identify the object's type.
```
Comment (rfranzke) [inline docs/development/kubernetes-clients.md]:
```suggestion
  Unstructured and metadata-only requests objects are an exception to this because the contained `TypeMeta` is the only way to identify the object's type.
```

File: pkg/resourcemanager/controller/health/reconciler.go (hunk 2 above)
Comment (timebertt) [reply pkg/resourcemanager/controller/health/reconciler.go:167]: Then we will not run into this code, right? 😄

**Comment by timebertt** [comment]
@rfranzke PTAL :)

File: pkg/resourcemanager/controller/health/reconciler.go (hunk 2 above)
Comment (rfranzke) [reply pkg/resourcemanager/controller/health/reconciler.go:167]: ... :)

**Review by rfranzke — APPROVED** [review]
/lgtm
