### PR TITLE
Move the deletion of the Observability tasks as late as possible in the reconciliation loop

### LINKED ISSUE #12352: Prometheus gets deleted too early
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:
Prometheus can get deleted before `Cleaning Kubernetes resources` step
`initializeShootClients` -> `syncPointReadyForCleanup` -> `cleanKubernetesResources`
`initializeShootClients` -> `deletePrometheus`

It is possible for `cleanKubernetesResources` to fail with `storage is (re)initializing` which seems related to spamming of LIST requests to KAPI. But with a missing Prometheus this can not be double-checked 

```
		deletePrometheus = g.Add(flow.Task{
			Name:         "Deleting Shoot Prometheus",
			Fn:           flow.TaskFn(botanist.DestroyPrometheus).RetryUntilTimeout(defaultInterval, defaultTimeout),
			Dependencies: flow.NewTaskIDs(initializeShootClients),
		})
...

		deletePlutono = g.Add(flow.Task{
			Name:         "Deleting Plutono in Seed",
			Fn:           flow.TaskFn(botanist.Shoot.Components.ControlPlane.Plutono.Destroy).RetryUntilTimeout(defaultInterval, defaultTimeout),
			Dependencies: flow.NewTaskIDs(waitUntilInfrastructureDeleted),
		})
		destroySeedLogging = g.Add(flow.Task{
			Name:         "Deleting logging stack in Seed",
			Fn:           flow.TaskFn(botanist.DestroySeedLogging).RetryUntilTimeout(defaultInterval, defaultTimeout),
			Dependencies: flow.NewTaskIDs(waitUntilInfrastructureDeleted),
		})
```

**What you expected to happen**:
Prometheus to be deleted as late as possible

### PR DESCRIPTION
**Pull request by iypetrov**
**How to categorize this issue?**

/area monitoring
/kind bug

**What this PR does / why we need it**:
Refine the reconciliation logic so that all Observability-related components are removed as late as possible. This ensures that if any issues arise during the deletion of other components, Observability is still available to capture and report those problems.

**Which issue(s) this PR fixes**:
Fixes #12352 

**Release note**:
```bugfix operator
The observability setup is deleted as late as possible so that, in case an error occurs during the deletion of any components, there is still enough information available to investigate the issue.
```

### CODE REVIEW

**Comment by iypetrov** [comment]
/rename Move the deletion of the Observability tasks as late as possible in the reconciliation loop

**Comment by iypetrov** [comment]
Hey @rrhubenov, if you have time can you review this?

File: pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go [hunk 1]
```diff
@@ -650,57 +635,76 @@ func (r *Reconciler) runDeleteShootFlow(ctx context.Context, o *operation.Operat
 			SkipIf:       !nonTerminatingNamespace,
 			Dependencies: flow.NewTaskIDs(syncPointCleaned, waitUntilKubeAPIServerDeleted),
 		})
+
+		syncPoint = flow.NewTaskIDs(
```
Comment (rrhubenov) [inline pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go]: I would change the name of this variable to something more descriptive like `syncPointControlPlaneDown`

File: pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go [hunk 2]
```diff
@@ -650,57 +635,76 @@ func (r *Reconciler) runDeleteShootFlow(ctx context.Context, o *operation.Operat
...
 		})
 		destroySeedLogging = g.Add(flow.Task{
 			Name:         "Deleting logging stack in Seed",
 			Fn:           flow.TaskFn(botanist.DestroySeedLogging).RetryUntilTimeout(defaultInterval, defaultTimeout),
-			Dependencies: flow.NewTaskIDs(waitUntilInfrastructureDeleted),
+			Dependencies: flow.NewTaskIDs(syncPoint),
 		})
 
-		syncPoint = flow.NewTaskIDs(
+		syncObservabilityPoint = flow.NewTaskIDs(
```
Comment (rrhubenov) [inline pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go]: Would also rename to something like `syncPointObservabilityDown`

**Review by rrhubenov — CHANGES_REQUESTED** [review]

**Comment by iypetrov** [comment]
@rrhubenov I renamed the variables, it sounds better to me as well

**Comment by chrkl** [comment]
I'm wondering if this could cause any alert spam if the control-plane gets partially deleted and Prometheus stays. Any observations like this?

**Comment by iypetrov** [comment]
@chrkl I think it’s acceptable that some alerts may fire if the control-plane is partially deleted. To reduce potential alert spam, we could consider two approaches:

- Adjust the deletion order – move the Alertmanager deletion to occur before syncPointObservabilityDown.

- Enhance Alertmanager setup – implement mechanisms such as rate limiting, error budgets, or improved aggregation logic to control how many alerts are sent within a given time window.

IMO second option is better, because such change will be beneficial in other scenarios as well and I would be happy to make a PR for it.

**Comment by chrkl** [comment]
> IMO second option is better, because such change will be beneficial in other scenarios as well and I would be happy to make a PR for it.

Let's move forward with this PR and see if this is a real problem before putting more effort into it.

/lgtm

**Review by rfranzke — COMMENTED** [review]
/approve

**Comment by plkokanov** [comment]
/hold

The should have a proper release note. @iypetrov could you please use the release note template specified in the PR template.

**Comment by plkokanov** [comment]
Thanks for adding the release note!

/unhold
