### PR TITLE
Check if seed kubeconfig using client-certificate has expired in `gardener-extensions-up.sh` and `gardener-extensions-down.sh`

### LINKED ISSUE #10024: Report when seed kubeconfig has expired in `gardener/example/provider-extensions/seed/configure-seed.sh`
**How to categorize this issue?**

/area quality
/kind bug

**What would you like to be added**:
Right now when the following command fails
https://github.com/gardener/gardener/blob/8a80f8c644482cc4fe002846a19c27a74bbc80e4/example/provider-extensions/seed/configure-seed.sh#L135
It is expected that the cause is a non-Shooted cluster and the script tries to promote it to a seed. But the same command can fail if the seed kubeconfig has expired.

**Why is this needed**:
It is easy to forget that the seed kubeconfig has expired and the following messages from the seed promotion steps are confusing
https://github.com/gardener/gardener/blob/8a80f8c644482cc4fe002846a19c27a74bbc80e4/example/provider-extensions/seed/configure-seed.sh#L157-L160

### PR DESCRIPTION
**Pull request by Kostov6**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
This PR ensures that the seed kubeconfig has not expired before executing `gardener-extensions-up.sh` and `gardener-extensions-down.sh`

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/10024

**Special notes for your reviewer**:

**Release note**:

```bugfix developer
Seed kubeconfig is checked for expiration before running `gardener-extensions-up.sh` and `gardener-extensions-down.sh`
```

### CODE REVIEW

File: example/provider-extensions/seed/configure-seed.sh [hunk 1]
```diff
@@ -132,6 +132,21 @@ relay_domain=
 internal_dns_secret=$(yq -e 'select(document_index == 1) | .metadata.name' "$REPO_ROOT_DIR"/example/provider-extensions/garden/controlplane/domain-secrets.yaml)
 dns_provider_type=$(yq -e 'select(document_index == 1) | .metadata.annotations.["dns.gardener.cloud/provider"]' "$REPO_ROOT_DIR"/example/provider-extensions/garden/controlplane/domain-secrets.yaml)
 
+CERT_DATA=$(kubectl config view --kubeconfig "$seed_kubeconfig" --raw -o jsonpath='{.users[0].user.client-certificate-data}')
```
Comment (plkokanov) [inline example/provider-extensions/seed/configure-seed.sh]: Lets follow what is done in the file and use lower case letters for the variable names.

File: example/provider-extensions/seed/configure-seed.sh [hunk 2]
```diff
@@ -132,6 +132,21 @@ relay_domain=
...
+if [[ -n "$CERT_DATA" ]]; then 
+  echo "Verifying that seed kubeconfig has not expired"
+  EXPIRY_DATE=$(echo "$CERT_DATA" | base64 --decode | openssl x509 -noout -enddate 2>/dev/null | sed -E 's/notAfter=(.+)/\1/')
```
Comment (plkokanov) [inline example/provider-extensions/seed/configure-seed.sh]: If you don't need to know the exact date, then you can use the `-checkend` option instead of `-enddate`. With `-checkend` you could even see if the certificate will expire in the next 60 seconds (or 600) and ask the user to regenerate it as the setup would still break, even if the certificate has not expired yet but would expire soon-ish.

**Review by plkokanov — CHANGES_REQUESTED** [review]

File: hack/gardener-extensions-down.sh [hunk 3]
```diff
@@ -34,6 +34,11 @@ parse_flags() {
 
 parse_flags "$@"
 
+if ! kubectl config view --kubeconfig "$PATH_SEED_KUBECONFIG" --raw -o jsonpath='{.users[0].user.client-certificate-data}' | base64 --decode | openssl x509 -noout -checkend 300 2>/dev/null ;then 
+  echo "Seed kubeconfig ${PATH_SEED_KUBECONFIG} has expired. Please provide a non-exipired kubeconfig and try again"
```
Comment (shafeeqes) [inline hack/gardener-extensions-down.sh]:
```suggestion
  echo "Seed kubeconfig ${PATH_SEED_KUBECONFIG} has expired or will expire soon. Please provide a valid kubeconfig and try again"
```

File: hack/gardener-extensions-up.sh [hunk 4]
```diff
@@ -34,6 +34,11 @@ parse_flags() {
 
 parse_flags "$@"
 
+if ! kubectl config view --kubeconfig "$PATH_SEED_KUBECONFIG" --raw -o jsonpath='{.users[0].user.client-certificate-data}' | base64 --decode | openssl x509 -noout -checkend 300 2>/dev/null ;then 
+  echo "Seed kubeconfig ${PATH_SEED_KUBECONFIG} has expired. Please provide a non-exipired kubeconfig and try again"
```
Comment (shafeeqes) [inline hack/gardener-extensions-up.sh]: same as above

File: hack/gardener-extensions-down.sh [hunk 5]
```diff
@@ -34,7 +34,7 @@ parse_flags() {
 
 parse_flags "$@"
 
-if ! kubectl config view --kubeconfig "$PATH_SEED_KUBECONFIG" --raw -o jsonpath='{.users[0].user.client-certificate-data}' | base64 --decode | openssl x509 -noout -checkend 10 2>/dev/null ;then 
+if ! kubectl config view --kubeconfig "$PATH_SEED_KUBECONFIG" --raw -o jsonpath='{.users[0].user.client-certificate-data}' | base64 --decode | openssl x509 -noout -checkend 300 2>/dev/null ;then
```
Comment (ScheererJ) [inline hack/gardener-extensions-down.sh]: You only consider `kubeconfig`s with client certificates here, but what about tokens? It is possible to have a completely valid & working `kubeconfig` with a token, which will not pass this test.

Please adapt so that tokens are considered as well or at least not blocked.

**Review by ScheererJ — CHANGES_REQUESTED** [review]
Thanks a lot for making it more obvious if a `kubeconfig` expired. Please enable non-client-certificate scenarios as well instead of blocking them.

File: hack/gardener-extensions-down.sh (hunk 5 above)
Comment (ScheererJ) [reply hack/gardener-extensions-down.sh]: I am not sure about other options apart from client certificates and tokens. Maybe `gardenctl` based `kubeconfig`s should work as well.

Comment (Kostov6) [reply hack/gardener-extensions-down.sh]: I'll make it so that if `.users[0].user.client-certificate-data` is missing the script does not get blocked. That's because I don't think I have the knowledge to handle the other cases

File: hack/gardener-extensions-down.sh [hunk 6]
```diff
@@ -34,6 +34,12 @@ parse_flags() {
 
 parse_flags "$@"
 
+client_certificate_data=$(kubectl config view --kubeconfig "$PATH_SEED_KUBECONFIG" --raw -o jsonpath='{.users[0].user.client-certificate-data}')
+if [[ -n "$client_certificate_data" ]] && ! echo "$client_certificate_data"| base64 --decode | openssl x509 -noout -checkend 300 2>/dev/null ; then
+  echo "Seed kubeconfig ${PATH_SEED_KUBECONFIG} has expired or will expire soon. Please provide a valid kubeconfig and try again"
+  exit
```
Comment (ialidzhikov) [inline hack/gardener-extensions-down.sh]:
```suggestion
  exit 1
```

File: hack/gardener-extensions-down.sh [hunk 7]
```diff
@@ -34,6 +34,12 @@ parse_flags() {
 
 parse_flags "$@"
 
+client_certificate_data=$(kubectl config view --kubeconfig "$PATH_SEED_KUBECONFIG" --raw -o jsonpath='{.users[0].user.client-certificate-data}')
+if [[ -n "$client_certificate_data" ]] && ! echo "$client_certificate_data"| base64 --decode | openssl x509 -noout -checkend 300 2>/dev/null ; then
+  echo "Seed kubeconfig ${PATH_SEED_KUBECONFIG} has expired or will expire soon. Please provide a valid kubeconfig and try again"
```
Comment (ialidzhikov) [inline hack/gardener-extensions-down.sh]:
```suggestion
  echo "Seed kubeconfig ${PATH_SEED_KUBECONFIG} has expired or will expire in 5min. Please provide a valid kubeconfig and try again!"
```

File: hack/gardener-extensions-down.sh [hunk 8]
```diff
@@ -34,6 +34,12 @@ parse_flags() {
 
 parse_flags "$@"
 
+client_certificate_data=$(kubectl config view --kubeconfig "$PATH_SEED_KUBECONFIG" --raw -o jsonpath='{.users[0].user.client-certificate-data}')
+if [[ -n "$client_certificate_data" ]] && ! echo "$client_certificate_data"| base64 --decode | openssl x509 -noout -checkend 300 2>/dev/null ; then
```
Comment (ialidzhikov) [inline hack/gardener-extensions-down.sh]:
```suggestion
if [[ -n "$client_certificate_data" ]] && ! echo "$client_certificate_data" | base64 --decode | openssl x509 -noout -checkend 300 2>/dev/null ; then
```

**Review by ialidzhikov — APPROVED** [review]
