### PR TITLE
`ManagedResource` controller only considers `ConfigMap`s/`Secret`s as garbage-collectable resources

### LINKED ISSUE #7156: [GRM] ManagedResource deletion flow to ignore "garbagecollectable" resources only if they are secret or configmap
**How to categorize this issue?**

/area usability 
/kind bug

**What happened**:
I had deleted a managed resource and its deletion was successful, though almost all referenced resource were orphaned and never deleted. The reason is that the deletion flow of ManagedResource ignores any resource that has the metadata classifying it as garbagecollectable (not only secrets and configmaps), ref:
https://github.com/gardener/gardener/blob/0d37c8a33483d8e497a0f79dc70f38a0aeecfd57/pkg/resourcemanager/controller/managedresource/reconciler.go#L699-L703

On the other side, the garbage collector cleans-up only secrets and configmaps, refs:
https://github.com/gardener/gardener/blob/0d37c8a33483d8e497a0f79dc70f38a0aeecfd57/pkg/resourcemanager/controller/garbagecollector/reconciler.go#L69-L70 and https://github.com/gardener/gardener/blob/0d37c8a33483d8e497a0f79dc70f38a0aeecfd57/pkg/resourcemanager/controller/garbagecollector/reconciler.go#L148-L155

**What you expected to happen**:
GRM to not leak "garbagecollectable" resources like Deployments, VPAs, PDBs, etc.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a managed resource that deploys a PDB labeled with `resources.gardener.cloud/garbage-collectable-reference=true`. 
2. Delete the MR
3. Make sure that the PDB is never deleted.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area usability
/kind bug

**What this PR does / why we need it**:
`gardener-resource-manager` now only considers `ConfigMap`s/`Secret`s as garbage-collectable resources (i.e., other resources with the "garbage-collectable" label will not be kept even if removed from the `ManagedResource` or when it is deleted).

**Which issue(s) this PR fixes**:
Fixes #7156

**Release note**:

```bugfix operator
`gardener-resource-manager` now only considers `ConfigMap`s/`Secret`s as garbage-collectable resources (i.e., other resources with the "garbage-collectable" label will not be kept even if removed from the `ManagedResource` or when it is deleted).
```

### CODE REVIEW

File: test/integration/resourcemanager/managedresource/resource_test.go [hunk 1]
```diff
@@ -536,6 +537,74 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+			})
+
+			JustBeforeEach(func() {
+				Eventually(func(g Gomega) []gardencorev1beta1.Condition {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(Succeed())
+					return managedResource.Status.Conditions
+				}).Should(
+					ContainCondition(OfType(resourcesv1alpha1.ResourcesApplied), WithStatus(gardencorev1beta1.ConditionTrue), WithReason(resourcesv1alpha1.ConditionApplySucceeded)),
+				)
+			})
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/resource_test.go:567]: Why do we need this separation of `BeforeEach` and `JustBeforeEach`?

File: test/integration/resourcemanager/managedresource/resource_test.go [hunk 2]
```diff
@@ -536,6 +537,74 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+				Eventually(func(g Gomega) []gardencorev1beta1.Condition {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(Succeed())
+					return managedResource.Status.Conditions
+				}).Should(
+					ContainCondition(OfType(resourcesv1alpha1.ResourcesApplied), WithStatus(gardencorev1beta1.ConditionTrue), WithReason(resourcesv1alpha1.ConditionApplySucceeded)),
+				)
+
+				Consistently(func(g Gomega) {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)).To(Succeed())
+				}).Should(Succeed())
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/resource_test.go]:
```suggestion
				Consistently(func() {
					return testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)
				}).Should(Succeed())
```
Nit

File: test/integration/resourcemanager/managedresource/resource_test.go [hunk 3]
```diff
@@ -536,6 +537,74 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+
+				Eventually(func(g Gomega) {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(node), node)).To(BeNotFoundError())
+				}).Should(Succeed())
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/resource_test.go]:
```suggestion
				Eventually(func() {
					return testClient.Get(ctx, client.ObjectKeyFromObject(node), node)
				}).Should(BeNotFoundError())
```
Nit

File: test/integration/resourcemanager/managedresource/resource_test.go (hunk 1 above)
Comment (rfranzke) [reply test/integration/resourcemanager/managedresource/resource_test.go:567]: The `BeforeEach` constructs the `ManagedResource` and its `Secret`, so we have to define the resources here. The `JustBeforeEach` creates the `ManagedResource`.
Hence, here in this context, we wait un the `JustBeforeEach` for the `ManagedResource` to be applied before we execute the tests and start to make assertions.

**Review by acumino — APPROVED** [review]
/lgtm
/approve
