### PR TITLE
Suffix `plutono-datasources` configmap name to avoid name collision with operator

### LINKED ISSUE #12785: [Flaky Test] Test cleanup after E2E tests is flaky
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
The cleanup after all e2e tests succeed can timeout and fail. This seems to be independent of test suites.

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/12759/pull-gardener-e2e-kind-ha-multi-node/1958445651062689792
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/12759/pull-gardener-e2e-kind-ipv6/1958465366808072192

**Reason for failure**:
```
Cleaning up...
 - secret "seed-local" deleted
 - gardenlet.seedmanagement.gardener.cloud "local" deleted
seed.core.gardener.cloud "local" deleted
error: timed out waiting for the condition on seeds/local
make[1]: *** [Makefile:418: seed-down] Error 1
```

<details>
<summary>Example logs from pull-gardener-e2e-kind-ha-multi-node</summary>

```
make[1]: Leaving directory '/home/prow/go/src/github.com/gardener/gardener'
+ export KUBECONFIG=/home/prow/go/src/github.com/gardener/gardener/example/gardener-local/kind/multi-zone/kubeconfig
+ KUBECONFIG=/home/prow/go/src/github.com/gardener/gardener/example/gardener-local/kind/multi-zone/kubeconfig
+ export_artifacts gardener-operator-local
+ cluster_name=gardener-operator-local
+ echo '> Exporting logs of kind cluster '\''gardener-operator-local'\'''
> Exporting logs of kind cluster 'gardener-operator-local'
+ kind export logs /logs/artifacts/gardener-operator-local --name gardener-operator-local
Exporting logs for cluster "gardener-operator-local" to:
/logs/artifacts/gardener-operator-local
+ echo '> Exporting events of kind cluster '\''gardener-operator-local'\'' > '\''/logs/artifacts/gardener-operator-local'\'''
> Exporting events of kind cluster 'gardener-operator-local' > '/logs/artifacts/gardener-operator-local'
+ export_events_for_cluster /logs/artifacts/gardener-operator-local
+ local dir=/logs/artifacts/gardener-operator-local/events
+ mkdir -p /logs/artifacts/gardener-operator-local/events
+ IFS=
+ read -r namespace
++ kubectl get ns -oname
++ cut -d/ -f2
+ kubectl -n default get event --sort-by=lastTimestamp
+ IFS=
+ read -r namespace
+ kubectl -n garden get event --sort-by=lastTimestamp
+ IFS=
+ read -r namespace
+ kubectl -n istio-system get event --sort-by=lastTimestamp
+ IFS=
+ read -r namespace
+ kubectl -n kube-node-lease get event --sort-by=lastTimestamp
+ IFS=
+ read -r namespace
+ kubectl -n kube-public get event --sort-by=lastTimestamp
+ IFS=
+ read -r namespace
+ kubectl -n kube-system get event --sort-by=lastTimestamp
+ IFS=
+ read -r namespace
+ kubectl -n local-path-storage get event --sort-by=lastTimestamp
+ IFS=
+ read -r namespace
+ kubectl -n registry get event --sort-by=lastTimestamp
+ IFS=
+ read -r namespace
+ kubectl -n runtime-extension-provider-local get event --sort-by=lastTimestamp
+ IFS=
+ read -r namespace
+ kubectl -n virtual-garden-istio-ingress get event --sort-by=lastTimestamp
+ IFS=
+ read -r namespace
+ export_resource_yamls_for seeds shoots bastions.operations.gardener.cloud etcds leases
+ mkdir -p /logs/artifacts
+ for resource_type in "$@"
+ echo '> Exporting Resource '\''seeds'\'' yaml > /logs/artifacts/seeds.yaml'
> Exporting Resource 'seeds' yaml > /logs/artifacts/seeds.yaml
+ echo -e '---\n# cluster name: '\''gardener-operator-local'\'''
+ kubectl get seeds -A -o yaml
error: the server doesn't have a resource type "seeds"
+ true
+ for resource_type in "$@"
+ echo '> Exporting Resource '\''shoots'\'' yaml > /logs/artifacts/shoots.yaml'
> Exporting Resource 'shoots' yaml > /logs/artifacts/shoots.yaml
+ echo -e '---\n# cluster name: '\''gardener-operator-local'\'''
+ kubectl get shoots -A -o yaml
error: the server doesn't have a resource type "shoots"
+ true
+ for resource_type in "$@"
+ echo '> Exporting Resource '\''bastions.operations.gardener.cloud'\'' yaml > /logs/artifacts/bastions.operations.gardener.cloud.yaml'
> Exporting Resource 'bastions.operations.gardener.cloud' yaml > /logs/artifacts/bastions.operations.gardener.cloud.yaml
+ echo -e '---\n# cluster name: '\''gardener-operator-local'\'''
+ kubectl get bastions.operations.gardener.cloud -A -o yaml
error: the server doesn't have a resource type "bastions"
+ true
+ for resource_type in "$@"
+ echo '> Exporting Resource '\''etcds'\'' yaml > /logs/artifacts/etcds.yaml'
> Exporting Resource 'etcds' yaml > /logs/artifacts/etcds.yaml
+ echo -e '---\n# cluster name: '\''gardener-operator-local'\'''
+ kubectl get etcds -A -o yaml
+ for resource_type in "$@"
+ echo '> Exporting Resource '\''leases'\'' yaml > /logs/artifacts/leases.yaml'
> Exporting Resource 'leases' yaml > /logs/artifacts/leases.yaml
+ echo -e '---\n# cluster name: '\''gardener-operator-local'\'''
+ kubectl get leases -A -o yaml
+ export_events_for_shoots
+ IFS=
+ read -r shoot
++ kubectl get shoot -A -o=custom-columns=namespace:metadata.namespace,name:metadata.name,id:status.technicalID --no-headers
error: the server doesn't have a resource type "shoot"
+ IFS=
+ read -r namespace
++ kubectl get ns -l gardener.cloud/role=shoot -oname
++ cut -d/ -f2
++ kubectl get ns -l export-artifacts=true -oname
++ cut -d/ -f2
+ echo '> Exporting /etc/hosts'
> Exporting /etc/hosts
+ cp /etc/hosts /logs/artifacts/gardener-operator-local/hosts
+ export_resource_yamls_for gardens extop
+ mkdir -p /logs/artifacts
+ for resource_type in "$@"
+ echo '> Exporting Resource '\''gardens'\'' yaml > /logs/artifacts/gardens.yaml'
> Exporting Resource 'gardens' yaml > /logs/artifacts/gardens.yaml
+ echo -e '---\n# cluster name: '\''gardener-operator-local'\'''
+ kubectl get gardens -A -o yaml
+ for resource_type in "$@"
+ echo '> Exporting Resource '\''extop'\'' yaml > /logs/artifacts/extop.yaml'
> Exporting Resource 'extop' yaml > /logs/artifacts/extop.yaml
+ echo -e '---\n# cluster name: '\''gardener-operator-local'\'''
+ kubectl get extop -A -o yaml
+ export KUBECONFIG=/home/prow/go/src/github.com/gardener/gardener/dev-setup/kubeconfigs/virtual-garden/kubeconfig
+ KUBECONFIG=/home/prow/go/src/github.com/gardener/gardener/dev-setup/kubeconfigs/virtual-garden/kubeconfig
+ export cluster_name=virtual-garden
+ cluster_name=virtual-garden
+ export_resource_yamls_for seeds shoots
+ mkdir -p /logs/artifacts
+ for resource_type in "$@"
+ echo '> Exporting Resource '\''seeds'\'' yaml > /logs/artifacts/seeds.yaml'
> Exporting Resource 'seeds' yaml > /logs/artifacts/seeds.yaml
+ echo -e '---\n# cluster name: '\''virtual-garden'\'''
+ kubectl get seeds -A -o yaml
+ for resource_type in "$@"
+ echo '> Exporting Resource '\''shoots'\'' yaml > /logs/artifacts/shoots.yaml'
> Exporting Resource 'shoots' yaml > /logs/artifacts/shoots.yaml
+ echo -e '---\n# cluster name: '\''virtual-garden'\'''
+ kubectl get shoots -A -o yaml
+ export_events_for_shoots
+ IFS=
+ read -r shoot
++ kubectl get shoot -A -o=custom-columns=namespace:metadata.namespace,name:metadata.name,id:status.technicalID --no-headers
+ make kind-multi-node-down
make[1]: Entering directory '/home/prow/go/src/github.com/gardener/gardener'
./hack/kind-down.sh \
	--cluster-name gardener-operator-local \
	--path-kubeconfig /home/prow/go/src/github.com/gardener/gardener/dev-setup/gardenlet/components/kubeconfigs/seed-local/kubeconfig
Deleting cluster "gardener-operator-local" ...
Deleted nodes: ["gardener-operator-local-control-plane" "gardener-operator-local-worker2" "gardener-operator-local-worker"]
# We need root privileges to clean the backup bucket directory, see https://github.com/gardener/gardener/issues/6752
docker run --rm --user root:root -v /home/prow/go/src/github.com/gardener/gardener/dev/local-backupbuckets:/dev/local-backupbuckets alpine rm -rf /dev/local-backupbuckets/garden-*
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
9824c27679d3: Pulling fs layer
9824c27679d3: Download complete
9824c27679d3: Pull complete
Digest: sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
Status: Downloaded newer image for alpine:latest
make[1]: Leaving directory '/home/prow/go/src/github.com/gardener/gardener'
make: *** [Makefile:474: ci-e2e-kind-ha-multi-node] Error 2
wrapper.sh] [TEST] Test Command exit code: 2
wrapper.sh] [CLEANUP] Waiting 30 seconds for pods stopped with terminationGracePeriod:30
wrapper.sh] [CLEANUP] Cleaning up after Docker in Docker ...
72e29375b10c
e6cd3e0bbc57
b1d71d03b1bc
281c0a6a6e05
c348569b2b27
5edc1abf72dd
dd24ce24b6fb
wrapper.sh] [CLEANUP] Waiting for docker to stop for 30 seconds
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
wrapper.sh] [CLEANUP] Done cleaning up after Docker in Docker.
================================================================================
wrapper.sh] Exiting 2
```

</details>

<details>
<summary>Logs from pull-gardener-e2e-kind-ipv6 are a bit different after a similar error occurs</summary>

```
Cleaning up...
 - secret "seed-local" deleted
 - gardenlet.seedmanagement.gardener.cloud "local" deleted
seed.core.gardener.cloud "local" deleted
error: timed out waiting for the condition on seeds/local
make[1]: *** [Makefile:418: seed-down] Error 1
make[1]: Leaving directory '/home/prow/go/src/github.com/gardener/gardener'
> Exporting logs of kind cluster 'gardener-operator-local'
Exporting logs for cluster "gardener-operator-local" to:
/logs/artifacts/gardener-operator-local
> Exporting events of kind cluster 'gardener-operator-local' > '/logs/artifacts/gardener-operator-local'
E0821 10:58:27.402665  969172 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.404506  969172 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.406127  969172 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.407692  969172 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.409277  969172 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
> Exporting Resource 'seeds' yaml > /logs/artifacts/seeds.yaml
E0821 10:58:27.452174  969187 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.453987  969187 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.455880  969187 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.457662  969187 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.459328  969187 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
> Exporting Resource 'shoots' yaml > /logs/artifacts/shoots.yaml
E0821 10:58:27.504707  969200 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.506327  969200 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.508136  969200 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.509666  969200 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.511181  969200 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
> Exporting Resource 'bastions.operations.gardener.cloud' yaml > /logs/artifacts/bastions.operations.gardener.cloud.yaml
E0821 10:58:27.552866  969216 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.554637  969216 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.556126  969216 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.557652  969216 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.559174  969216 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.560701  969216 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.562165  969216 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
> Exporting Resource 'etcds' yaml > /logs/artifacts/etcds.yaml
E0821 10:58:27.607676  969231 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.609450  969231 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.610989  969231 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.612534  969231 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.614150  969231 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
> Exporting Resource 'leases' yaml > /logs/artifacts/leases.yaml
E0821 10:58:27.656947  969244 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.659185  969244 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.660831  969244 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.662513  969244 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.664070  969244 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0821 10:58:27.705938  969259 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.707710  969259 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.709509  969259 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.711227  969259 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.712862  969259 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0821 10:58:27.756584  969275 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.758201  969275 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.759742  969275 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.761214  969275 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0821 10:58:27.762864  969275 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
> Exporting /etc/hosts
make[1]: Entering directory '/home/prow/go/src/github.com/gardener/gardener'
./hack/kind-down.sh \
	--cluster-name gardener-operator-local \
	--path-kubeconfig /home/prow/go/src/github.com/gardener/gardener/dev-setup/gardenlet/components/kubeconfigs/seed-local/kubeconfig
Deleting cluster "gardener-operator-local" ...
Deleted nodes: ["gardener-operator-local-control-plane"]
# We need root privileges to clean the backup bucket directory, see https://github.com/gardener/gardener/issues/6752
docker run --rm --user root:root -v /home/prow/go/src/github.com/gardener/gardener/dev/local-backupbuckets:/dev/local-backupbuckets alpine rm -rf /dev/local-backupbuckets/garden-*
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
9824c27679d3: Pulling fs layer
9824c27679d3: Verifying Checksum
9824c27679d3: Download complete
9824c27679d3: Pull complete
Digest: sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
Status: Downloaded newer image for alpine:latest
make[1]: Leaving directory '/home/prow/go/src/github.com/gardener/gardener'
make: *** [Makefile:468: ci-e2e-kind] Error 2
wrapper.sh] [TEST] Test Command exit code: 2
wrapper.sh] [CLEANUP] Waiting 30 seconds for pods stopped with terminationGracePeriod:30
wrapper.sh] [CLEANUP] Cleaning up after Docker in Docker ...
ca9df255414f
2bd736668e25
5cdedf475542
21c124024833
e012c4e87fd0
8fd67cc6f8a3
d2435eb63158
wrapper.sh] [CLEANUP] Waiting for docker to stop for 30 seconds
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
wrapper.sh] [CLEANUP] Done cleaning up after Docker in Docker.
================================================================================
wrapper.sh] Exiting 2
```

</details>

**Anything else we need to know**:
N/A

### PR DESCRIPTION
**Pull request by Kostov6**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
Seems to be caused by https://github.com/gardener/gardener/pull/12762

This PR suffixes `plutono-datasources` when `OnlyDeployDataSourcesAndDashboards` is set mirroring the behavior of the data field
https://github.com/gardener/gardener/blob/bdfa23af92eb972840ed93f3c7541cc00bb1c3cf/pkg/component/observability/plutono/plutono.go#L238

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/12785

**Special notes for your reviewer**:
Result after running local operator setup
```
❯ k -n garden get configmap | grep plutono
plutono-dashboard-providers-140e41f3                1      8m6s
plutono-dashboards-garden                           31     8m6s
plutono-dashboards-seed                             18     96s
plutono-datasources                                 1      8m6s
plutono-datasources-seed                            1      96s
```

/cc @rfranzke 

**Release note**:

```bugfix operator
An issue causing the `plutono-datasources` ConfigMap to be reconciled by 2 ManagedResources when Seed is Garden managed by `gardener-operator` is now fixed. Occasionally, the issue was preventing successful Seed deletion.
```

### CODE REVIEW

**Comment by plkokanov** [comment]
[pull-gardener-e2e-kind-ipv6](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/12794/pull-gardener-e2e-kind-ipv6/1958816587406381056) failed with:

```
• [FAILED] [0.654 seconds]
Shoot Tests Create Shoot, Rotate Credentials and Delete Shoot Shoot with workers with workers rollout [It] Create Shoot [Shoot, default, credentials-rotation, basic, with-workers-rollout]
/home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_rotate_delete.go:244
   Timeline >>
  > Enter [It] Create Shoot @ 08/22/25 09:16:13.394
  2025-08-22T09:16:13.394Z	INFO	Creating Shoot	{"shoot": {"name":"e2e-rotate","namespace":"garden-local"}}
  [FAILED] in [It] - /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/shoot.go:86 @ 08/22/25 09:16:14.048
  < Exit [It] Create Shoot @ 08/22/25 09:16:14.048 (654ms)
  << Timeline
   [FAILED] Told to stop trying after 0.654s.
  shoot already exists
  At one point, however, the function did return successfully.
  Yet, Eventually failed because the matcher was not satisfied:
  Expected success, but got an error:
      <*errors.StatusError | 0xc0026dd360>: 
      the server is currently unable to handle the request (post shoots.core.gardener.cloud)
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "the server is currently unable to handle the request (post shoots.core.gardener.cloud)",
              Reason: "ServiceUnavailable",
              Details: {
                  Name: "",
                  Group: "core.gardener.cloud",
                  Kind: "shoots",
                  UID: "",
                  Causes: [
                      {
                          Type: "UnexpectedServerResponse",
                          Message: "error trying to reach service: unexpected EOF",
                          Field: "",
                      },
                  ],
                  RetryAfterSeconds: 0,
              },
              Code: 503,
          },
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/shoot.go:86 @ 08/22/25 09:16:14.048
```

This seems different from https://github.com/gardener/gardener/issues/12020

/retest pull-gardener-e2e-kind-ipv6

---

[pull-gardener-e2e-kind](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/12794/pull-gardener-e2e-kind/1958816589180571648) failed with

```
• [FAILED] [13.461 seconds]
Shoot Tests Create, Authenticate, Delete [It] should verify a shoot cannot be accessed with a client certificate from another shoot by manipulating the apiserver-proxy header [Shoot, default, authentication]
/home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_authenticate_delete.go:129
   Timeline >>
  > Enter [It] should verify a shoot cannot be accessed with a client certificate from another shoot by manipulating the apiserver-proxy header @ 08/22/25 09:23:47.208
  [FAILED] in [It] - /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_authenticate_delete.go:141 @ 08/22/25 09:24:00.669
  < Exit [It] should verify a shoot cannot be accessed with a client certificate from another shoot by manipulating the apiserver-proxy header @ 08/22/25 09:24:00.669 (13.461s)
  << Timeline
   [FAILED] Failed after 13.460s.
  The function passed to Consistently failed at /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_authenticate_delete.go:139 with:
  Expected success, but got an error:
      <*retry.Error | 0xc003bccaa0>: 
      retry failed with context deadline exceeded, last error: failed to get server groups: Get "https://kubernetes.default.svc.cluster.local/api": Get "https://kubernetes.default.svc.cluster.local/api": EOF
      {
          ctxError: <context.deadlineExceededError>{},
          err: <*fmt.wrapError | 0xc003bcca80>{
              msg: "failed to get server groups: Get \"https://kubernetes.default.svc.cluster.local/api\": Get \"https://kubernetes.default.svc.cluster.local/api\": EOF",
              err: <*url.Error | 0xc003dc4240>{
                  Op: "Get",
                  URL: "https://kubernetes.default.svc.cluster.local/api",
                  Err: <*url.Error | 0xc003dc4210>{
                      Op: "Get",
                      URL: "https://kubernetes.default.svc.cluster.local/api",
                      Err: <*errors.errorString | 0x50b7c50>{s: "EOF"},
                  },
              },
          },
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_authenticate_delete.go:141 @ 08/22/25 09:24:00.669
```

/retest pull-gardener-e2e-kind

Update: I opened https://github.com/gardener/gardener/issues/12795 for this case as I have also seen it in the past.

**Comment by ialidzhikov** [comment]
@Kostov6 , could you add a release note as we have to cherry-pick this PR?

File: pkg/component/observability/plutono/plutono.go [hunk 1]
```diff
@@ -231,7 +231,7 @@ func (p *plutono) computeResourcesData(ctx context.Context) (*corev1.ConfigMap,
 	}
 	dataSourceConfigMap := &corev1.ConfigMap{
 		ObjectMeta: metav1.ObjectMeta{
-			Name:      "plutono-datasources",
+			Name:      "plutono-datasources" + dataSourcesKeySuffix,
```
Comment (ialidzhikov) [inline pkg/component/observability/plutono/plutono.go:234]: Is it possible to cover this with unit test to make sure we won't regress it in the future?

**Comment by Kostov6** [comment]
Note to reviewers:
- First commit introduces test that passes capturing the behavior prior to the change
- Second commit introduces the bug fix, test from first commit fails and then it fixes the test

File: pkg/component/observability/plutono/plutono_test.go [hunk 2]
```diff
@@ -697,6 +709,37 @@ status:
...
+				Context("managed by gardener-operator", func() {
+					BeforeEach(func() {
+						values.OnlyDeployDataSourcesAndDashboards = true
+					})
+
+					It("should successfully deploy all resources", func() {
+
+						dashboardConfigMapName := "plutono-dashboards-garden"
+						dashboardCount := 28
+						GinkgoHelper()
```
Comment (ialidzhikov) [inline pkg/component/observability/plutono/plutono_test.go]: AFAIK, `GinkgoHelper()` should be used in test helper funcs. But here we are not in such helper func. Let me know if I miss something.

```suggestion
```

File: pkg/component/observability/plutono/plutono_test.go [hunk 3]
```diff
@@ -697,6 +709,37 @@ status:
...
+						dashboardsConfigMap := &corev1.ConfigMap{ObjectMeta: metav1.ObjectMeta{Name: dashboardConfigMapName, Namespace: namespace}}
+						Expect(c.Get(ctx, client.ObjectKeyFromObject(dashboardsConfigMap), dashboardsConfigMap)).To(Succeed(), "Could not successfully get dashboards configMap")
+						Expect(dashboardsConfigMap.Labels).To(HaveKeyWithValue("dashboard.monitoring.gardener.cloud/"+clusterLabelKey(values), "true"), "Dashboards configMap does not contain expected key")
+
+						availableDashboards := sets.Set[string]{}
+						for key := range dashboardsConfigMap.Data {
+							availableDashboards.Insert(key)
+						}
+						Expect(availableDashboards).To(HaveLen(dashboardCount), "The number of deployed dashboards differs from the expected one")
+
```
Comment (ialidzhikov) [inline pkg/component/observability/plutono/plutono_test.go]:
```suggestion
```

File: pkg/component/observability/plutono/plutono_test.go [hunk 4]
```diff
@@ -697,6 +709,37 @@ status:
 					})
 				})
 
+				Context("managed by gardener-operator", func() {
+					BeforeEach(func() {
+						values.OnlyDeployDataSourcesAndDashboards = true
+					})
+
+					It("should successfully deploy all resources", func() {
+
```
Comment (ialidzhikov) [inline pkg/component/observability/plutono/plutono_test.go]:
```suggestion
```

File: pkg/component/observability/plutono/plutono_test.go [hunk 5]
```diff
@@ -697,6 +709,37 @@ status:
...
+						dashboardConfigMapName := "plutono-dashboards-garden"
+						dashboardCount := 28
+						GinkgoHelper()
+
+						deployment := deploymentYAMLFor(values)
+						utilruntime.Must(references.InjectAnnotations(deployment))
```
Comment (ialidzhikov) [inline pkg/component/observability/plutono/plutono_test.go]: Doesn't seems to be as part of this unit test.

```suggestion
```

**Review by ialidzhikov — COMMENTED** [review]
Thanks for the fix!

/lgtm

**Review by rfranzke — COMMENTED** [review]
Sounds reasonable, thank you for finding this!
/approve
