### PR TITLE
[node-agent] Fix kubelet datavolume & moving files between different block devices

### LINKED ISSUE #4424: Configure separate disk for /var/lib/kubelet for worker nodes
**How to categorize this issue?**
/area os
/area storage
/kind enhancement
/priority 3

**What would you like to be added**:
At the moment, only the WHOLE `/var/lib` can be assigned to additional disks using for worker nodes:
https://github.com/gardener/gardener/blob/a6eda4d63195f9373c1c17055f1b18d3f962bfb9/example/90-shoot.yaml#L50-L55

This configuration description:
<html>
<body>

kubeletDataVolumeName | (Optional)KubeletDataVolumeName contains the name of a dataVolume that should be used for storing kubelet state.
-- | --

</body>
</html>

The problem is that the OS and services (e.g. docker) would still create their own folder structure and use `/var/lib`.
And by this, there is no clear separation of the storage of `kubelet` working folder from others as the description indicates.

In my opinion, with the setting of `kubeletDataVolumeName` the point would be to:
_Only the `/var/lib/kubelet` is mounted to different disk, and not the whole `/var/lib`._
I'd like to add an option to mount the additional disk to `/var/lib/kubelet` only.

**Proof**
```
# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0   50G  0 disk               <======= OS FS
|-sda1   8:1    0    1M  0 part 
|-sda2   8:2    0   16M  0 part /boot/efi
|-sda3   8:3    0    1G  0 part /usr
`-sda4   8:4    0   49G  0 part /
sdb      8:16   0   25G  0 disk /var/lib      <======= Additional disk
sdc      8:32   0  128G  0 disk 
`-sdc1   8:33   0  128G  0 part /mnt/resource
sr0     11:0    1  652K  0 rom  

```

These folder will be located on the additional disk besides the kubelet folder
```
/var/lib# ls -1
apt
calico
cloud-config-downloader
cni
dbus
dictionaries-common
docker
dockershim
dpkg
dracut
gardener-user
gardener-user-ssh.key
grub
kube-proxy
kubelet           <==== not separated on different storage
logrotate
lost+found
misc
nfs
pam
polkit-1
private
python
quota
sudo
systemd
ucf
vim
waagent
```

**Why is this needed**:
I believe that the point of  `kubeletDataVolumeName` is to separate kubelet workdir from OS filesystem. Even if it is configured;
once kubernetes workload impacts the storage behind the `/var/lib/kubelet` on a give host, it could effect the whole host and system since the OS is still using the very same disk for different services (through `/var/lib`).

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
There was a bug when assigned a separate data volume as `kubeletDataVolumeName` on worker groups ([ref](https://github.com/gardener/gardener/blob/master/docs/api-reference/core.md#worker)) for a while. The datavolume was mounted to `/var/lib` instead of `/var/lib/kubelet` (see #4424). With `gardener-node-agent` nodes of worker groups where this settings was activated did not join the cluster at all anymore. GNA stores some files in `/var/lib/gardener-node-agent` and does not like it when they are moved while it is running.
This PR fixes this issue and renames the OSC component to `varlibkubeletmount`. 

Additionally, the PR fixes an error where GNA was not able to move files between different devices (see also [slack](https://gardener-cloud.slack.com/archives/C045DSWJZB9/p1713279648295749)). 
This error came up in this context too when `/var/lib/kubelet` has its own device. In this case GNA was not able to copy files anymore.
```
"error":"failed applying changed files: unable to rename temporary file \"/var/lib/gardener-node-agent/tmp/osc-reconciliation-file-716655486/ca.crt\" to \"/var/lib/kubelet/ca.crt\": rename /var/lib/gardener-node-agent/tmp/osc-reconciliation-file-716655486/ca.crt /var/lib/kubelet/ca.crt: invalid cross-device link"
```

**Which issue(s) this PR fixes**:
Fixes #4424
Part of #8023

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
A bug in `gardener-node-agent` which prevented copying files between different block devices has been fixed.
```
```bugfix user
A bug which mounted the kubelet data volume to `/var/lib` instead of `/var/lib/kubelet` when `kubeletDataVolumeName` was set has been fixed.
```

### CODE REVIEW

File: pkg/nodeagent/registry/containerd_extractor.go [hunk 1]
```diff
@@ -133,56 +134,122 @@ func unmountImage(ctx context.Context, snapshotter snapshots.Snapshotter, direct
...
+	defer func() { utilruntime.HandleError(srcFile.Close()) }()
 
-	if err := fs.MkdirAll(path.Dir(destinationFile), permissions); err != nil {
-		return fmt.Errorf("destination directory %q could not be created", path.Dir(destinationFile))
+	if err := fs.MkdirAll(path.Dir(destination), os.ModeDir); err != nil {
+		return fmt.Errorf("destination directory %q could not be created", path.Dir(destination))
 	}
 
-	tempDir, err := fs.TempDir(nodeagentv1alpha1.TempDir, "copy-image-")
+	dstFile, err := fs.OpenFile(destination, os.O_CREATE|os.O_RDWR, 0755)
```
Comment (MichaelEischer) [inline pkg/nodeagent/registry/containerd_extractor.go]: When called via `CopyFile`, the destination file already exists. Then the dstFile must be truncated using `os.O_TRUNC` to make sure that no leftovers remain.

Comment (oliver-goetz) [reply pkg/nodeagent/registry/containerd_extractor.go]: `CopyFile` first creates a new temporary dir ([ref](https://github.com/gardener/gardener/blob/2c24775e3243897903cec5d3dc94b38da0b8bab9/pkg/nodeagent/registry/containerd_extractor.go#L150)) and copies the file there ([ref](https://github.com/gardener/gardener/blob/2c24775e3243897903cec5d3dc94b38da0b8bab9/pkg/nodeagent/registry/containerd_extractor.go#L157-L159)).
Thus, it should not exist shouldn't it?

File: pkg/nodeagent/registry/containerd_extractor.go [hunk 2]
```diff
@@ -133,56 +134,122 @@ func unmountImage(ctx context.Context, snapshotter snapshots.Snapshotter, direct
...
+	if err != nil {
+		return err
+	}
 	if !sourceFileStat.Mode().IsRegular() {
-		return fmt.Errorf("source %q is not a regular file", sourceFile)
+		return fmt.Errorf("source %q is not a regular file", source)
 	}
 
-	if destinationFileStat, err := fs.Stat(destinationFile); err == nil {
+	if destinationFileStat, err := fs.Stat(destination); err == nil {
```
Comment (MichaelEischer) [inline pkg/nodeagent/registry/containerd_extractor.go]: as this doesn't use `Lstat` (do we really want to follow symlinks here?), it would be cleaner to check the file stats after opening the destination file. Then `dstFile.Stat()` is available and race condition free.

File: pkg/nodeagent/registry/containerd_extractor.go (hunk 1 above)
Comment (MichaelEischer) [reply pkg/nodeagent/registry/containerd_extractor.go]: I'd suggest to use ~`0700`~ `0600` as filemode, it will be replace by `Chmod` anyways.

Comment (MichaelEischer) [reply pkg/nodeagent/registry/containerd_extractor.go]: > Thus, it should not exist shouldn't it?

Oh, indeed I didn't notice the TempDir that's used there. Although in that case `os.O_CREATE|os.O_RDWR|os.O_EXCL` would be much cleaner than trying to check that the destination file does not already exist.

But if I'm not mistaken, this guarantee does not hold for `moveCrossDevice` at the moment? There the destination is not a random location.

File: pkg/nodeagent/registry/containerd_extractor.go (hunk 2 above)
Comment (oliver-goetz) [reply pkg/nodeagent/registry/containerd_extractor.go]: I'm pretty sure that the file won't be a symlink in practice, because it is created by `gardener-node-agent` in the first place.

We are in a bit of a hurry now, because today is the last day where we could cherry-pick this PR in v1.90 where `gardener-node-agent` became GA.
Thus, I suggest to do these small improvements in a separate PR.

/unhold

File: pkg/nodeagent/files/files.go [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+
+	err = fs.Rename(source, destination)
+	if err != nil && strings.Contains(err.Error(), "cross-device link") {
+		return moveCrossDevice(fs, source, destination)
+	}
+	return err
+}
+
+func moveCrossDevice(fs afero.Afero, source, destination string) error {
+	tmpFilePath := destination + ".tmp"
```
Comment (MichaelEischer) [inline pkg/nodeagent/files/files.go:142]: One last question. Shouldn't this delete the file at `tmpFilePath` first? `copyAndSync` will fail otherwise if there's already a file with that name.

File: pkg/nodeagent/files/files.go [hunk 4]
```diff
@@ -89,7 +89,7 @@ func copyAndSync(fs afero.Afero, source, destination string) error {
 		return fmt.Errorf("destination directory %q could not be created", path.Dir(destination))
 	}
 
-	dstFile, err := fs.OpenFile(destination, os.O_CREATE|os.O_RDWR, 0755)
+	dstFile, err := fs.OpenFile(destination, os.O_CREATE|os.O_RDWR|os.O_EXCL, 0700)
```
Comment (MichaelEischer) [inline pkg/nodeagent/files/files.go:92]: For a quick fix, I'd suggest to use for now
```
dstFile, err := fs.OpenFile(destination, os.O_CREATE|os.O_RDWR|os.O_TRUNC, 0600)
```

That should be good enough for the `Copy` (shouldn't make a difference) and `moveCrossDevice` (still works if `tmpFilePath` already exists) cases for now.

Comment (oliver-goetz) [reply pkg/nodeagent/files/files.go:92]: There is always room for improvement 😄 
I was afk today, but address your feedback in a separate PR.
