### PR TITLE
Ignore `status` subresources and `metadata.managedFields` for resource size limit admission

### LINKED ISSUE #9039: Shoot resource status.lastOperation.description can get too large (easily reach resource size limit)
**What happened**:
We have seen, e.g. when people fail to update their credentials, that the error message repeats in `status.lastOperation.description`, e.g. for each node separately (observed by @mliepold @kon-angelo), driving the size of the `shoot` resource beyond the permitted limit, breaking further automated updates that do not strip the status first.

**What you expected to happen**:
It seems reasonable to prevent status updates from blowing up the resource in this way and either do not repeat the same message (may or may not be easy to achieve or at least truncate the field if it gets "too" large). @kon-angelo suggested:
> It should be handled for all extensions and most of their code reside in the form of libraries in gardener/gardener.

**How to reproduce it (as minimally and precisely as possible)**:
Please contact the above mentioned colleagues.

### PR DESCRIPTION
**Pull request by LucaBernstein**
**How to categorize this PR?**

/area open-source
/area robustness
/kind enhancement

**What this PR does / why we need it**:
Ignore `status` subresources fields and `metadata.managedFields` on update in admission controller size limit comparison to not block updates e.g. because of large status description contents.

**Which issue(s) this PR fixes**:
Fixes #9039

**Special notes for your reviewer**:
/cc @timuthy 

**Release note**:

```breaking operator
The [Resource Size Validator](https://github.com/gardener/gardener/blob/master/docs/concepts/admission-controller.md) of the `gardener-admission-controller` ignores `status` subresource and `metadata.managedFields` for resource size limits. Please consider adjusting your configuration if you already increased the limits because of these now ignored sections.
```

### CODE REVIEW

File: pkg/admissioncontroller/webhook/admission/resourcesize/handler.go [hunk 1]
```diff
@@ -100,6 +105,17 @@ func (h *Handler) handle(req admission.Request) error {
...
 }
 
+func relevantObjectSize(rawObject []byte) (int64, error) {
+	var obj map[string]any
+	err := json.Unmarshal(rawObject, &obj)
+	if err != nil {
+		return 0, err
+	}
+	delete(obj, "status")
+	marshalled, err := json.Marshal(obj)
```
Comment (MartinWeindel) [inline pkg/admissioncontroller/webhook/admission/resourcesize/handler.go:115]: Missing error check on marshalling
```suggestion
	marshalled, err := json.Marshal(obj)
	if err != nil {
		return 0, err
	}	
```

File: pkg/admissioncontroller/webhook/admission/resourcesize/handler_test.go [hunk 2]
```diff
@@ -245,6 +245,31 @@ var _ = Describe("handler", func() {
...
+				},
+				Status: gardencorev1beta1.ShootStatus{
+					LastOperation: &gardencorev1beta1.LastOperation{
+						Description: "This is a very long description that can happen if e.g. each node's error message is appended and a lot of nodes exist.",
+					},
+				},
+			}
+			objData, err := runtime.Encode(testEncoder, shootWithLargeStatus)
+			Expect(err).NotTo(HaveOccurred())
+			Expect(shootsv1beta1SizeLimit.CmpInt64(int64(len(objData)))).Should(BeNumerically("==", -1))
```
Comment (MartinWeindel) [inline pkg/admissioncontroller/webhook/admission/resourcesize/handler_test.go]: Can be simplified
```suggestion
			Expect(shootsv1beta1SizeLimit.CmpInt64(int64(len(objData)))).Should(Equal(-1))
```

**Review by MartinWeindel — COMMENTED** [review]
Looks good to me, only one minor nit

File: pkg/admissioncontroller/webhook/admission/resourcesize/handler_test.go (hunk 2 above)
Comment (LucaBernstein) [reply pkg/admissioncontroller/webhook/admission/resourcesize/handler_test.go]: Thanks for the review and the hint! I will simplify this as you suggested :)

**Review by timuthy — CHANGES_REQUESTED** [review]
Besides ignoring managed fields (as discussed), could you please adapt the documentation https://github.com/gardener/gardener/blob/master/docs/concepts/admission-controller.md#resource-size-validator?

File: docs/concepts/admission-controller.md [hunk 3]
```diff
@@ -35,6 +35,7 @@ One example is the creation of shoot resources with large annotation values (up
 [Vertical autoscaling](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) can help to mitigate such situations, but we cannot expect to scale infinitely, and thus need means to block the attack itself.
 
 The Resource Size Validator checks arbitrary incoming admission requests against a configured maximum size for the resource's group-version-kind combination. It denies the request if the object exceeds the quota.
+The values of the following keys are not taken into account for the resource size calculation: `status`, `metadata.managedFields`
```
Comment (timuthy) [inline docs/concepts/admission-controller.md]: Nit
```suggestion

> [!NOTE]
> The content of `status` subresources and `metadata.managedFields` are not taken into account for the resource size calculation.
```

**Review by timuthy — CHANGES_REQUESTED** [review]
Thank you!
Could you also adjust the release note, please?

File: docs/concepts/admission-controller.md (hunk 3 above)
Comment (LucaBernstein) [reply docs/concepts/admission-controller.md]: Thank you for having a look! Applied suggestion, also modified PR title and release note accordingly.

File: pkg/admissioncontroller/webhook/admission/resourcesize/handler.go [hunk 4]
```diff
@@ -100,6 +105,20 @@ func (h *Handler) handle(req admission.Request) error {
...
 }
 
+func relevantObjectSize(rawObject []byte) (int64, error) {
+	var obj map[string]any
+	err := json.Unmarshal(rawObject, &obj)
+	if err != nil {
+		return 0, err
+	}
+	delete(obj, "status")
+	if obj["metadata"] != nil {
```
Comment (LucaBernstein) [inline pkg/admissioncontroller/webhook/admission/resourcesize/handler.go:115]: wdyt? Is this nil check required, as every persisted resource should have `ObjectMeta`, which cannot be `nil`, correct?

File: pkg/admissioncontroller/webhook/admission/resourcesize/handler.go [hunk 5]
```diff
@@ -100,6 +105,20 @@ func (h *Handler) handle(req admission.Request) error {
...
+		delete(obj["metadata"].(map[string]any), "managedFields")
+	}
```
Comment (LucaBernstein) [inline pkg/admissioncontroller/webhook/admission/resourcesize/handler.go:117]: wdyt? Is this nil check required, as every persisted resource should have ObjectMeta, which cannot be nil, correct?

Comment (timuthy) [reply pkg/admissioncontroller/webhook/admission/resourcesize/handler.go:117]: Actually, yes it should not be nil. But it doesn't harm either 🙂

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve
