### PR TITLE
Machines of MachineDeployments of deleted Worker Pools are able to join cluster

### LINKED ISSUE #13431: Machines of MachineDeployments of deleted Worker Pools are unable to join cluster
**How to categorize this issue?**

/area cost
/area auto-scaling
/area high-availability
/kind bug

**What happened**:

Old MachineDeployments of deleted Worker Pools are only removed after all currently desired machineDeployments are fully healthy (This is ok and works as designed).

In cases where a user removes an Worker Pool, but another pool is stuck (e.g., because the configured worker pool does not exist or is exhausted) the **old** machineDeployments will still exist.

If the old machineDeployments is rolled the new machines of the old machineDeployment cannot join.

This leads to a state where the old as well as the new machine deployments have no working machines.

**What you expected to happen**:

The old machine deployment can successfully schedule a node that is able to join the cluster (even though the corresponding worker pool is deleted). This is important as a fallback in case of misconfiguration or resource exhaustion.

**How to reproduce it (as minimally and precisely as possible)**:

- create shoot with worker pool `worker-deleteme`
    - status:
        - `worker.spec.pools = ["worker-deleteme"]`
        - list of machindeployments = `["worker-deleteme"]`
- add pool `worker-kaputt` (important: this worker pool must not be schedulable, e.g. no VMs available) 
    - status:
        - `worker.spec.pools = ["worker-deleteme", "worker-kaputt"]`
        - list of MachineDeployments = `["worker-deleteme", "worker-kaputt"]`
- delete `worker-deleteme` from node pool
    - status:
        - `worker.spec.pools = ["worker-kaputt"]`
        - list of machindeployments = `["worker-deleteme", "worker-kaputt"]`
- `worker-deleteme`-deployment and its scheduled machines still exists. Triggering an event which will lead to schedule a machine for `worker-deleteme` (e.g. by deleting all existing machines) will lead to a pending machine, not able to join the cluster

**Anything else we need to know?**:

Deleting a node pool, will also delete a corresponding OSC secret, which contains information on how to join the node.
When a new machines starts to boot their `gardener-node-agent` service will be unable to retrieve the OSC secret as it is not existent anymore. As a result the node is unable to join.

From what I understand: the OSC secret should only be removed, AFTER the corresponding MachineDeployment gets removed. In other words: [`getWantedOSCNames()`](https://github.com/gardener/gardener/blob/9267010aa24a0fef8fb15f8561aaaea643a897f8/pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L570) should not only consider Workers, but also MachineDeployments (possibly there is more to a fix).

**Environment**:

- Gardener version: `v1.131.1`
- Kubernetes version:
```
$ kubectl version
Client Version: v1.34.1
Kustomize Version: v5.7.1
Server Version: v1.33.5
```
- Cloud provider or hardware configuration: OpenStack

### PR DESCRIPTION
**Pull request by aniruddha2000**
**How to categorize this PR?**

/area usability
/area auto-scaling
/kind bug

**What this PR does / why we need it**:

The OperatingSystemConfig cleanup holds the secrets for the existing machines if if the worker pool is deleted, so they can join back the cluster when the worker pool is again created.

**Which issue(s) this PR fixes**:
Fixes #13431

**Special notes for your reviewer**:

**Release note**:

```bugfix user
The machines of a deleted worker pool are able to join back cluster in healthy state.
```

### CODE REVIEW

**Comment by aniruddha2000** [comment]
I have started testing this PR with local gardener setup, but the I am unable to get the logs written here in the `gardener-extension-provider-local` deployment, seems I need some help :)

**Comment by timuthy** [comment]
Feedback copied from [Slack thread](https://gardener-cloud.slack.com/archives/C045DSWJZB9/p1767775477714089):

> Thanks for taking care about the issue.
You said that you've started testing the PR with the local garden setup (ref). Has this been  successful?
The changes partly look like they are WIP (commented code) - what's the state of the PR?
Basically, you should be able to test and reproduce everything locally and once finalized, maintainers can put a /ok-to-test to execute the e2e tests.

**Comment by timebertt** [comment]
@aniruddha2000 is this PR ready for review?

**Comment by aniruddha2000** [comment]
No @timebertt we are not done yet. me and @shafeeqes tried to reproduce it and could not do it anymore, and we found that the machines does not have any deletion timestamp as `cleanupMachineDeployments` was not called before the `waitUntilWantedMachineDeploymentsAvailable` is not successfully done

**Comment by timuthy** [comment]
/work-in-progress

@aniruddha2000 feel free to remove the WIP label as soon as you are ready and post a message here, so the maintainers can add the `ok-to-test` label.

**Comment by aniruddha2000** [comment]
The code now allows the OSC secret to persist for the MDs in the cluster, allowing machines to join the node. would be now ok to test @timuthy

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 1]
```diff
@@ -588,10 +592,29 @@ func (o *operatingSystemConfig) getWantedOSCNames() (sets.Set[string], error) {
 			if err != nil {
 				return nil, err
 			}
+			o.log.Info("inserted osc data from worker", "data", oscKey+keySuffix(version, worker.Machine.Image, purpose)) // gardener-node-agent-worker-kaputt-15050ccbf2cd566b-init || gardener-node-agent-worker-kaputt-15050ccbf2cd566b-original
```
Comment (timuthy) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: Could you please remove this log or make it a debug log (`o.log.V(1).Info`)?

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 2]
```diff
@@ -588,10 +592,29 @@ func (o *operatingSystemConfig) getWantedOSCNames() (sets.Set[string], error) {
...
+	}
+
+	for _, machine := range mdList.Items {
+		o.log.Info("machine name", "name", machine.Name)
+
+		if val, ok := machine.Spec.NodeTemplateSpec.ObjectMeta.Labels[gardencorev1beta1constants.LabelWorkerPoolGardenerNodeAgentSecretName]; ok {
+			originalVal := val + "-original"
+			initVal := val + "-init"
+
+			o.log.Info("found wanted OSC name from existing machine", "oscName-originalVal", originalVal, "oscName-initVal", initVal, "machineName", machine.Name)
```
Comment (timuthy) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]:
```suggestion
			o.log.Info("found wanted OSC name from existing machine", "init", initVal, "original", originalVal, "machine", machine.Name)
```

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 3]
```diff
@@ -588,10 +592,29 @@ func (o *operatingSystemConfig) getWantedOSCNames() (sets.Set[string], error) {
...
 		}
 	}
 
+	mdList := &v1alpha1.MachineList{}
+	if err := o.client.List(ctx, mdList, client.InNamespace(o.values.Namespace), client.HasLabels{}); err != nil {
+		return nil, fmt.Errorf("failed to list Machines: %w", err)
+	}
+
+	for _, machine := range mdList.Items {
+		o.log.Info("machine name", "name", machine.Name)
```
Comment (timuthy) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: Can this log entry be removed, too?

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 4]
```diff
@@ -588,10 +592,29 @@ func (o *operatingSystemConfig) getWantedOSCNames() (sets.Set[string], error) {
 			if err != nil {
 				return nil, err
 			}
+			o.log.Info("inserted osc data from worker", "data", oscKey+keySuffix(version, worker.Machine.Image, purpose)) // gardener-node-agent-worker-kaputt-15050ccbf2cd566b-init || gardener-node-agent-worker-kaputt-15050ccbf2cd566b-original
 			wantedOSCNames.Insert(oscKey + keySuffix(version, worker.Machine.Image, purpose))
 		}
 	}
 
+	mdList := &v1alpha1.MachineList{}
+	if err := o.client.List(ctx, mdList, client.InNamespace(o.values.Namespace), client.HasLabels{}); err != nil {
```
Comment (timuthy) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: Why is the `client.HasLabels{}` option empty?

**Review by timuthy — CHANGES_REQUESTED** [review]

**Comment by shafeeqes** [comment]
Can we not just clean up the stale OSCs after the deploy worker step?

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go (hunk 4 above)
Comment (aniruddha2000) [reply pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: it was a mistake, i though the label `gardencorev1beta1constants.LabelWorkerPoolGardenerNodeAgentSecretName` is in the machine label, but it seems in the machine.Spec.NodeTemplateSpec.ObjectMeta.Labels instead

**Comment by shafeeqes** [comment]
@aniruddha2000 wanted to have an offline discussion to resolve https://github.com/gardener/gardener/pull/13715#issuecomment-3802943288. Currently waiting on that.

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 5]
```diff
@@ -588,10 +589,27 @@ func (o *operatingSystemConfig) getWantedOSCNames() (sets.Set[string], error) {
 			if err != nil {
 				return nil, err
 			}
+			o.log.V(1).Info("Inserted osc data from worker", "data", oscKey+keySuffix(version, worker.Machine.Image, purpose))
 			wantedOSCNames.Insert(oscKey + keySuffix(version, worker.Machine.Image, purpose))
 		}
 	}
 
+	mdList := &v1alpha1.MachineList{}
```
Comment (rfranzke) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]:
```suggestion
	machineList := &v1alpha1.MachineList{}
```

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 6]
```diff
@@ -588,10 +589,27 @@ func (o *operatingSystemConfig) getWantedOSCNames() (sets.Set[string], error) {
...
+	if err := o.client.List(ctx, mdList, client.InNamespace(o.values.Namespace)); err != nil {
+		return nil, fmt.Errorf("failed to list Machines: %w", err)
+	}
+
+	for _, machine := range mdList.Items {
+		if val, ok := machine.Spec.NodeTemplateSpec.Labels[v1beta1constants.LabelWorkerPoolGardenerNodeAgentSecretName]; ok {
+			originalVal := val + "-original"
+			initVal := val + "-init"
```
Comment (rfranzke) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: Can you make a function that is called here and in the existing `keySuffix` function that takes the OSC `purpose` as input and returns this name? This way, this suffixing would not be duplicated.

**Comment by aniruddha2000** [comment]
@rfranzke all test passed, is there anything else can be improved, or else can we merge this? because in our team its a very important one :)

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go (hunk 6 above)
Comment (rfranzke) [reply pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: I don't see the `keySuffix` function being adapted 👁️

**Comment by rfranzke** [comment]
Does this issue also fix https://github.com/gardener/gardener/issues/6569? cc @ialidzhikov

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 7]
```diff
@@ -588,10 +589,34 @@ func (o *operatingSystemConfig) getWantedOSCNames() (sets.Set[string], error) {
 			if err != nil {
 				return nil, err
 			}
+			o.log.V(1).Info("Inserted osc data from worker", "data", oscKey+keySuffix(version, worker.Machine.Image, purpose))
```
Comment (rfranzke) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: Can we remove this log again? It looks like it was used for dev purposes.

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 8]
```diff
@@ -15,6 +15,7 @@ import (
 	"time"
 
 	"github.com/Masterminds/semver/v3"
+	"github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1"
```
Comment (rfranzke) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]:
```suggestion
	machinev1alpha1 "github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1"
```

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 9]
```diff
@@ -1118,17 +1143,42 @@ func KeyV2(
 	return fmt.Sprintf("gardener-node-agent-%s-%s", worker.Name, utils.ComputeSHA256Hex([]byte(result.String()))[:16])
 }
 
-func keySuffix(version int, machineImage *gardencorev1beta1.ShootMachineImage, purpose extensionsv1alpha1.OperatingSystemConfigPurpose) string {
+func oscPurposeSuffix(purpose extensionsv1alpha1.OperatingSystemConfigPurpose) string {
+	switch purpose {
+	case extensionsv1alpha1.OperatingSystemConfigPurposeProvision:
+		return "init"
+	case extensionsv1alpha1.OperatingSystemConfigPurposeReconcile:
+		return "original"
```
Comment (rfranzke) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]:
```suggestion
		return "-init"
	case extensionsv1alpha1.OperatingSystemConfigPurposeReconcile:
		return "-original"
```

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go [hunk 10]
```diff
@@ -13,6 +13,7 @@ import (
 	"time"
 
 	"github.com/Masterminds/semver/v3"
+	"github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1"
```
Comment (rfranzke) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]: same here

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go (hunk 9 above)
Comment (aniruddha2000) [reply pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: are you sure? because in keySuffix function in return `return imagePrefix + "-" + suffix`

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 11]
```diff
@@ -1180,5 +1179,5 @@ func generateOSCName(
 	if suffix == "" {
 		return val
 	}
-	return fmt.Sprintf("%s-%s", val, suffix)
+	return fmt.Sprintf("%s%s", val, suffix)
```
Comment (rfranzke) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]:
```suggestion
return val+suffix
```

Nit, but much easier?

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Comment by rfranzke** [comment]
@aniruddha2000 Can you also add a proper release note, please?
@timuthy @shafeeqes Do you wanna take a final look?

**Review by rfranzke — COMMENTED** [review]
/lgtm

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go (hunk 7 above)
Comment (shafeeqes) [reply pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: The log is still present

Comment (rfranzke) [reply pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: @aniruddha2000 ?

Comment (aniruddha2000) [reply pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: done
