### PR TITLE
Switch update strategy for shoot condition controller

### LINKED ISSUE #5295: Shoots registered as Seeds do not get Seed conditions updated
**How to categorize this issue?**

/kind bug

**What happened**:
Shoots registered as Seeds sometimes do not get Seed conditions updated. 
This results in the Seed resource to have a mismatch in conditions with the corresponding Shoot resource leading to Shoots falsely reporting as healthy or non-healthy. The dashboard relies on the conditions in the Shoot and therefore will display healthiness potentially wrongly.

**What you expected to happen**:
Conditions to be coherent between Seed and Shoot resource for managed Seeds

**How to reproduce it (as minimally and precisely as possible)**:
Unclear - seems like it only sometimes happens and self heals after days.

**Anything else we need to know?**:
Most likely introduced with https://github.com/gardener/gardener/pull/5013

For the scheduling decision the Seed resource is used which in our case has the bootstrap condition set correctly. Therefore, this bug is not influencing scheduling decisions.

### PR DESCRIPTION
**Pull request by BeckerMax**
**How to categorize this PR?**
/kind bug

**What this PR does / why we need it**:
This fixes the issues described in https://github.com/gardener/gardener/issues/5295 . In some cases the shoot conditions controller would not or only partially update Seed conditions in the shoot resource for managedSeeds.

For the problem description see https://github.com/gardener/gardener/issues/5295#issuecomment-1017415479 for a description of the solutions see the commit messages.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/5295

**Release note**:

```bugfix operator
Fixes bugs which could cause Seed conditions not being properly copied over to the corresponding Shoot due to a stale cache.
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]
/lgtm
/second-opinion

**Review by timebertt — DISMISSED** [review]
/lgtm

Do you want to apply the other suggestions from https://github.com/gardener/gardener/issues/5295 as well (predicate should evaluate to true for add events and for update events with unchanged `resourceVersion`s)?

**Comment by BeckerMax** [comment]
> Do you want to apply the other suggestions from #5295 as well (predicate should evaluate to true for add events and for update events with unchanged resourceVersions)? 

done PTAL

File: pkg/controllermanager/controller/shoot/shoot_conditions_control.go [hunk 1]
```diff
@@ -111,7 +115,8 @@ func (r *shootConditionsReconciler) Reconcile(ctx context.Context, request recon
 	// Update the shoot conditions if needed
 	if gardencorev1beta1helper.ConditionsNeedUpdate(shoot.Status.Conditions, conditions) {
 		r.logger.Debugf("Updating shoot %s conditions", kutil.ObjectName(shoot))
-		if err := r.updateShootConditions(ctx, shoot, conditions); err != nil {
+		shoot.Status.Conditions = conditions
+		if err := r.gardenClient.Status().Update(ctx, shoot); err != nil {
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/shoot_conditions_control.go:91]: Does it make sense to add a comment here? Using `Update()` instead of `Patch()` is done very consciously here, so probably we should prevent that this gets reverted somewhen in the future when we are no longer aware of the details.

Comment (BeckerMax) [reply pkg/controllermanager/controller/shoot/shoot_conditions_control.go:91]: done

**Review by rfranzke — DISMISSED** [review]
/lgtm
/second-opinion

**Review by timuthy — DISMISSED** [review]

File: pkg/controllermanager/controller/shoot/shoot_conditions_control.go [hunk 2]
```diff
@@ -38,26 +38,30 @@ func (c *Controller) shootConditionsAdd(obj interface{}) {
 	c.shootConditionsQueue.Add(key)
 }
 
-func (c *Controller) filterSeedForShootConditions(obj, oldObj, _ client.Object, deleted bool) bool {
+func (c *Controller) filterSeedForShootConditions(obj, oldObj, _ client.Object, _ bool) bool {
```
Comment (timebertt) [inline pkg/controllermanager/controller/shoot/shoot_conditions_control.go]: Such changes definitely deserve a unit test, as they are not particularly obvious to all developers. 
I appreciate that you added a comment explaining it. However, a unit test ensuring this logic would be even better.

File: pkg/controllermanager/controller/shoot/shoot_conditions_control.go [hunk 3]
```diff
@@ -38,26 +38,30 @@ func (c *Controller) shootConditionsAdd(obj interface{}) {
...
+
+	if !apiequality.Semantic.DeepEqual(seed.Status.Conditions, oldSeed.Status.Conditions) {
+		logger.Logger.Debugf("Seed %s conditions changed", seed.Name)
+		return true
 	}
 
-	if deleted {
-		logger.Logger.Debugf("Seed %s deleted", seed.Name)
+	// We want to enqueue on periodic cache resync events to catch up if we missed updates.
+	if seed.ResourceVersion == oldSeed.ResourceVersion {
```
Comment (timebertt) [inline pkg/controllermanager/controller/shoot/shoot_conditions_control.go]: Considering my findings in https://github.com/gardener/gardener/issues/5295#issuecomment-1018285002, I'm asking myself if it wouldn't be better to handling resync events in the seed event handler (seeds are kind of the "owned objects" here) and instead add an update handler to the shoot informer (shoots are the "controlled objects" here), which respects periodic resyncs.
The advantage would be that resync events also cause the controller to remove seed conditions from shoots where the seed has been deleted (relevant for cases where the seed informer lags behind).

WDYT?

**Review by timebertt — CHANGES_REQUESTED** [review]
Some additional thoughts in the second round of review and after digging a bit deeper into the cache resyncs.

File: pkg/controllermanager/controller/shoot/shoot_conditions_control.go (hunk 3 above)
Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_conditions_control.go]: > and instead add an update handler to the shoot informer

Hm, let's suppose we missed an update or the seed informer lags behind, don't we want to have a resync on seeds rather than on shoots?
How would a resync on shoots let us consider the "right' conditions of the seed?

Comment (timebertt) [reply pkg/controllermanager/controller/shoot/shoot_conditions_control.go]: I was thinking about the following case:
- seed informer lags behind
- seed is deleted
- watch connection eventually breaks and seed informer does a full relist

I thought, that a shoot resync helps to mitigate missing seed delete events.

Now I realize that neither a seed nor shoot resync help in this case:
A resync of the seed informer doesn't help, because it doesn't refresh the cache's state. Even if the predicate evaluates to `true` and the reconciler starts, it will still not detect that the seed was deleted (it reads from an outdated cache).
A shoot resync doesn't help as well, because the reconciler still reads from a stale seed cache.

The only thing that helps in that case is actually a the eventual full relist of the seed informer.
This will emit delete events for objects in the cache that are not included in the list of the relist operation, see [delta_fifo.go](https://github.com/kubernetes/client-go/blob/a4e27104a2f8f5d3965f1520f74a190eba1ad221/tools/cache/delta_fifo.go#L598).
Hence, the only way to miss a delete event is by the controller going down. But after a restart, we will enqueue all shoots and accordingly remove seed conditions if the seed object is gone.

I admit, it's pretty hard to wrap my head around this. 
What about simply respecting resync events for both informers to be on the safe side? Shouldn't hurt, right?

Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_conditions_control.go]: Sounds good to me 👍

Comment (BeckerMax) [reply pkg/controllermanager/controller/shoot/shoot_conditions_control.go]: > Hence, the only way to miss a delete event is by the controller going down. But after a restart, we will enqueue all shoots and accordingly remove seed conditions if the seed object is gone. 

Doesn't that mean we are already safe and sound with the current solution?
I am hesitant to add more code for a potential problem happening on seed deletion. Especially as Seed deletion is such a corner case. But if you insist I will add it. WDYT?

Comment (timebertt) [reply pkg/controllermanager/controller/shoot/shoot_conditions_control.go]: Fine for me, then leave it as it.

**Review by timebertt — APPROVED** [review]
/lgtm

**Review by timuthy — APPROVED** [review]

**Comment by BeckerMax** [comment]
FYI I did not cherry pick to 1.36 as https://github.com/gardener/gardener/pull/5013 was not yet present in 1.36
