### PR TITLE
Make HOSTNAME env to lowercase for promtail service

### LINKED ISSUE #7114: Can't see logs from kube-system namespace of shoot cluster
**How to categorize this issue?**
/area logging
/kind bug

**What happened**:
I create a shoot on Alicloud and try to get the logs from kube-system namespace of my shoot from operator grafana, 
The logs are not available. 
**What you expected to happen**:
we should be able to see the logs from Loki in grafana
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by vlvasilev**
**How to categorize this PR?**

/area logging
/kind enhancement

**What this PR does / why we need it**:
The name of a K8s Node object must be a valid [DNS subdomain name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names#dns-subdomain-names). But Promtail uses the `HOSTNAME` env variable to search for pods running on its hostname and on Alicloud the node can consist of capital letters. Since the search is case-sensitive Promtail fails to get the pods running on the node. So the logs from `kube-system` are missing for all clusters on Alicloud. With this PR the `HOSTNAME` variable is transformed to lowercase.

**Which issue(s) this PR fixes**:
Fixes [#7114](https://github.com/gardener/gardener/issues/7114)

**Special notes for your reviewer**:

**Release note**:

```other operator
Promtail installed on each shoot node now scrapes log from pods when `HOSTNAME` contains capital letters
```

### CODE REVIEW

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/config.go [hunk 1]
```diff
@@ -138,7 +138,7 @@ MemorySwapMax=0
 Restart=always
 RestartSec=5
 EnvironmentFile=/etc/environment
-ExecStartPre=/bin/sh -c "systemctl set-environment HOSTNAME=$(hostname)"
+ExecStartPre=/bin/sh -c "systemctl set-environment HOSTNAME=$(echo -n $(hostname) | tr '[:upper:]' '[:lower:]')"
```
Comment (dimityrmirchev) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/promtail/config.go]:
```suggestion
ExecStartPre=/bin/sh -c "systemctl set-environment HOSTNAME=$(hostname | tr [:upper:] [:lower:])"
```

I think that you do not need the `echo` and the single quotes. I did not run the code but tested with this command
```bash
/bin/sh -c "echo -n $(hostname | tr [:upper:] [:lower:])"
```

**Review by dimityrmirchev — COMMENTED** [review]
Just one minor suggestion, but overall
/lgtm

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
