### PR TITLE
fix(dnsrecord): reconcile dnsrecords when changing their spec

### LINKED ISSUE #6463: gardenlet doesn't reconcile `DNSRecords` when changing their spec
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
We recently migrated from `dnsentries` to `dnsrecords`. Upon the migration, we noticed that after gardener cleared all `dnsentries` and migrated them to `dnsrecords` it got stuck with the following error message:

> task "Deploying external domain DNS record" failed: Error while waiting for DNSRecord shoot--garden--r-eu01m-0/r-eu01m-0-external to become ready: observed generation outdated (1/2)

We then removed all previously migrated `dnsrecords` and let Gardener re-create the `dnsrecord`. After that the migration went through without a hitch.
```bash
k get dnsrecords.extensions.gardener.cloud -A | tail -n +2 | awk -F ' ' '{print $1, $2}' | xargs -l1 -- sh -c 'kubectl annotate dnsrecord "$2" -n "$1" confirmation.gardener.cloud/deletion=true' --
k get dnsrecords.extensions.gardener.cloud -A | tail -n +2 | awk -F ' ' '{print $1, $2}' | xargs -l1 -- sh -c 'kubectl delete dnsrecord "$2" -n "$1" --wait=false' --
```

**What you expected to happen**:

Migration from `dnsentries` to `dnsrecords` without any manual intervention. Also we can not be sure at the moment that this issue was just a "one time thing" (only once during migration) and if it might happen again.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enabled google gcp extension (provider-gcp)
2. Set `UseDNSRecords` to true

```yaml
# gardener.values.global.apiserver.featureGates
# gardener.values.global.controllers.featureGates
UseDNSRecords: true

# acre.yaml
# landscape.iaas.[].featureGates
UseDNSRecords: true
```
3. Deploy changes
> ./deploy.sh deploy gardener/virtual gardener/runtime gardencontent/seeds/soils
4. Set `UseDNSRecords` to true for Seeds (ManagedSeedSet, ManagedSeed)
```yaml
        config:
          featureGates:
            UseDNSRecords: true
```
5. After Step 4 enable
```yaml
ManagedIstio: true
APIServerSNI: true
````

Step 5 halts the complete reconciliation as Gardener can **not** update the dnsrecord for the shoots/seed/initial.

> task "Deploying internal domain DNS record" failed: Error while waiting for DNSRecord shoot-bla-bla to become ready: observed generation outdated (1/2)

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.43.2
- Kubernetes version (use `kubectl version`): 1.21.11
- Cloud provider or hardware configuration: OpenStack
- Others:

### PR DESCRIPTION
**Pull request by nschad**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
Since https://github.com/gardener/gardener/pull/5531, the DNSRecord is only annotated with gardener.cloud/operation=reconcile if the shoot.gardener.cloud/tasks annotation contains deployDNSRecord*. This in turn is only done during maintenance in order to limit the number of API calls made to the DNS provider.

If the DNSRecord object is not annotated with gardener.cloud/operation=reconcile, the DNSRecord controller will not act on it, even if the spec has changed.

**Which issue(s) this PR fixes**:
Fixes #6463 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fixed a bug where the Shoot reconciliation could get stuck due to `DNSRecords` not being reconciled.
```

### CODE REVIEW

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go [hunk 1]
```diff
@@ -143,6 +143,11 @@ func (c *dnsRecord) deploy(ctx context.Context, operation string) (extensionsv1a
 		return nil, err
 	}
 
+	// reconcile dnsrecords when the spec changes
+	if !c.values.AnnotateOperation {
+		c.values.AnnotateOperation = c.valuesDontMatchDNSRecord()
```
Comment (timebertt) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: At this point in time, `c.dnsRecord` is not filled with the current spec yet.

You were right, it's probably better to simply combine this with line 152:
```go
		if c.values.AnnotateOperation || c.valuesDontMatchDNSRecord() {
			metav1.SetMetaDataAnnotation(&c.dnsRecord.ObjectMeta, v1beta1constants.GardenerOperation, operation)
		}```

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go [hunk 2]
```diff
@@ -219,6 +220,7 @@ var _ = Describe("DNSRecord", func() {
 					Namespace: namespace,
 					Annotations: map[string]string{
 						v1beta1constants.GardenerTimestamp: now.UTC().String(),
+						v1beta1constants.GardenerOperation: v1beta1constants.GardenerOperationReconcile,
```
Comment (timebertt) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go:257]: Can you adapt the `It` description accordingly?

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go [hunk 3]
```diff
@@ -341,6 +343,38 @@ var _ = Describe("DNSRecord", func() {
...
+				Expect(dnsRecord.Deploy(ctx)).To(Succeed())
+
+				deployedDNS := &extensionsv1alpha1.DNSRecord{}
+				err = c.Get(ctx, client.ObjectKey{Name: name, Namespace: namespace}, deployedDNS)
+				Expect(err).NotTo(HaveOccurred())
+
+				patch := client.MergeFrom(deployedDNS.DeepCopy())
+				deployedDNS.Spec.Values = []string{address, "8.8.8.8", "1.1.1.1"}
+				Expect(c.Patch(ctx, deployedDNS, patch)).To(Succeed())
+				Expect(dnsRecord.Deploy(ctx)).To(Succeed())
```
Comment (timebertt) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go]: I'm not sure, if I fully get what you are doing in this test case:
Why are you calling `Deploy` twice?
Also, you would need to get the `DNSRecord` again after deploying to assert the expected object.

**Review by timebertt — COMMENTED** [review]
Thanks for taking care of the fix!

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go (hunk 3 above)
Comment (nschad) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go]: Trying to simulate the bug basically while making sure that it doesn't happen again

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go (hunk 1 above)
Comment (nschad) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: Okay!

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go (hunk 3 above)
Comment (nschad) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go]: Okay I think I had it backwards. Obviously we want to change the addresses of the `dnsRecord` so that the `gardenlet` can update the `extensionsv1alpha1.DNSRecord` with the `reconcile` operation hopefully :P

**Review by timebertt — COMMENTED** [review]
Thanks again!
/lgtm
/approve

/hold
as @nschad wants to test the fix in a real landscape first before merging.
Please `/hold cancel` whenever you're ready :)

**Comment by nschad** [comment]
Alright finally had some time to test the changes. Observed Generation was bumped to `2` without manual intervention. Migration went smoothly.

Thank you! @timebertt 

/hold cancel
