### PR TITLE
[provider-local] Harmonize local VPN setup with real-world scenario

### LINKED ISSUE #9020: [Flaky Test] E2E tests for extensions can fail due to unavailability of `clusterrole-machine-controller-manager.local.extensions.gardener.cloud` webhook
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
E2E tests for extensions which use the KinD setup  can sometimes flake during the step which deploys the extensions' charts in the local KinD cluster.

**CI link**:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener-extension-shoot-rsyslog-relp/34/pull-gardener-extension-shoot-rsyslog-relp-e2e-kind/1723972989701066752
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener-extension-shoot-rsyslog-relp/38/pull-gardener-extension-shoot-rsyslog-relp-e2e-kind/1731974321494036480

**Reason for failure**:
This can happen if the extensions' charts contain a `clusterrole` resource. E.g. the [`shoot-rsyslog-relp`](https://github.com/gardener/gardener-extension-shoot-rsyslog-relp) extension deploys a [ClusterRole](https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/blob/main/charts/gardener-extension-shoot-rsyslog-relp-admission/charts/application/templates/cluster-role.yaml) as part of the skaffold deployment for the [`shoot-rsyslog-relp-admission`](https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/blob/5ad228a5d4548d8f790b9db0054eeb02c86aba4f/skaffold.yaml#L65-L88) used for the e2e tests.

This skaffold deployment can fail with the following error:
```
Error: INSTALLATION FAILED: 1 error occurred:
	* Internal error occurred: failed calling webhook "clusterrole-machine-controller-manager.local.extensions.gardener.cloud": failed to call webhook: Post "[https://gardener-extension-provider-local.extension-provider-local-5mf8n.svc:443/clusterrole-machine-controller-manager?timeout=5s](https://gardener-extension-provider-local.extension-provider-local-5mf8n.svc/clusterrole-machine-controller-manager?timeout=5s)": dial tcp 10.2.126.230:443: connect: connection refused
```

The reason for the failure is that the `gardener-extension-provider-local` pods could get evicted by VPA during the deployment of the extension charts, meaning that the `gardener-extension-provider-local`s webhook server will be temporarily unavailable. 

The `clusterrole-machine-controller-manager.local.extensions.gardener.cloud` webhook does not have any selectors: 
https://github.com/gardener/gardener/blob/bcaed6dcbf8e06ea9a3b9a7ea726aaaf7c3dbbd2/pkg/provider-local/webhook/machinecontrollermanager/add.go#L71-L80
However, it is only responsible for the `system:machine-controller-manager-runtime` ClusterRole: 
https://github.com/gardener/gardener/blob/bcaed6dcbf8e06ea9a3b9a7ea726aaaf7c3dbbd2/pkg/provider-local/webhook/machinecontrollermanager/mutator.go#L30-L32.

Therefore, anything that tries to deploy a ClusterRole while the `gardener-extension-provider-local` pods are down will fail.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
Currently, in the local scenario, some pods talk to the machine pods directly (instead of using the VPN tunnel). See the referenced issue for a more detailed description.

This PR harmonizes the local VPN setup by specifying the node network for `Shoot`s and creating a dedicated IP pool.
With this, the VPN components correctly configure IP routes for talking to the shoot node network.
As a consequence, all traffic correctly traverses the VPN tunnel and gardenlet's tunnel health check reliably detects a broken tunnel.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/9604
Fixes https://github.com/gardener/gardener/issues/9020
See also: https://github.com/gardener-community/hackathon/blob/main/2024-05_Schelklingen/README.md#-harmonize-local-vpn-setup-with-real-world-scenario

**Special notes for your reviewer**:
/cc @timebertt 

We need to do some workarounds for making the e2e upgrade tests pass for this specific version. The workarounds are only active until the next minor release.

**Release note**:

```breaking developer
The `allow-shoot-networks` `NetworkPolicy` has been dropped entirely, hence, the `networking.gardener.cloud/to-shoot-networks=allowed` label has no effect anymore and should be removed.
```

### CODE REVIEW

**Comment by timebertt** [comment]
We figured that we must perform the `NetworkPolicy`-related changes (dropping the `allow-shoot-networks` `NetworkPolicy`) in the next release. Otherwise, the upgrade tests will fail because the VPN will be broken after the upgrade.

File: pkg/provider-local/controller/infrastructure/actuator.go [hunk 1]
```diff
@@ -56,12 +65,37 @@ func (a *actuator) Reconcile(ctx context.Context, _ logr.Logger, infrastructure
...
+  allowedUses:
+  - Workload
+  - Tunnel
+  blockSize: 26
+  cidr: ` + *cluster.Shoot.Spec.Networking.Nodes + `
+  ipipMode: Always
+  natOutgoing: true
+  nodeSelector: all()
+  vxlanMode: Never
+`)).Read()
```
Comment (ScheererJ) [inline pkg/provider-local/controller/infrastructure/actuator.go]: Could you please share your reasoning why this is defined as inline `yaml` with a little templating while above we use typed objects? Is that not possible with the calico objects or do we simply omit the `go` dependency?

Anyway, I suggest to stick to the minimum and not fill in default values, which we do not need:

```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: ` + IPPoolName(infrastructure.Namespace) + `
spec:
  cidr: ` + *cluster.Shoot.Spec.Networking.Nodes + `
  ipipMode: Always
  natOutgoing: true
```

Especially using the fixed `blockSize` of `26` should break the IPv6 scenario.

File: pkg/provider-local/controller/infrastructure/actuator.go [hunk 2]
```diff
@@ -74,29 +77,27 @@ func (a *actuator) Reconcile(ctx context.Context, _ logr.Logger, infrastructure
...
+		}
+		objects = append(objects, ipPoolV4)
+	}
+	if ipFamilies.Has(gardencorev1beta1.IPFamilyIPv6) {
+		ipPoolV6, err := ipPool(infrastructure.Namespace, string(gardencorev1beta1.IPFamilyIPv6), *cluster.Shoot.Spec.Networking.Nodes)
+		if err != nil {
+			return err
+		}
+		objects = append(objects, ipPoolV6)
+	}
```
Comment (ScheererJ) [inline pkg/provider-local/controller/infrastructure/actuator.go]: Why not just use a `for` loop over `cluster.Shoot.Spec.Networking.IPFamilies` instead? There should be validation in place to prevent duplicate values and the code will look cleaner.

File: pkg/provider-local/controller/infrastructure/actuator.go [hunk 3]
```diff
@@ -140,6 +142,24 @@ func emptyNetworkPolicy(name, namespace string) *networkingv1.NetworkPolicy {
...
 
 // IPPoolName returns the name of the crd.projectcalico.org/v1.IPPool resource for the given shoot namespace.
-func IPPoolName(shootNamespace string) string {
-	return "shoot-machine-pods-" + shootNamespace
+func IPPoolName(shootNamespace, ipFamily string) string {
+	return "shoot-machine-pods-" + shootNamespace + "-" + strings.ToLower(ipFamily)
+}
+
+func ipPool(shootNamespace, ipFamily, nodeCIDR string) (client.Object, error) {
+	// we don't specify the blockSize configuration so that it is defaulted correctly based on the IP family
```
Comment (ScheererJ) [inline pkg/provider-local/controller/infrastructure/actuator.go]: Why specify the other default values anyway?

File: pkg/provider-local/controller/worker/machines.go [hunk 4]
```diff
@@ -104,6 +107,23 @@ func (w *workerDelegate) generateMachineConfig(ctx context.Context) error {
...
+			"image": image,
+		}
+
+		ipFamilies := sets.New(w.cluster.Shoot.Spec.Networking.IPFamilies...)
+		if ipFamilies.Has(gardencorev1beta1.IPFamilyIPv4) {
+			providerConfig["ipPoolNameV4"] = infrastructure.IPPoolName(w.worker.Namespace, string(gardencorev1beta1.IPFamilyIPv4))
+		}
+		if ipFamilies.Has(gardencorev1beta1.IPFamilyIPv6) {
+			providerConfig["ipPoolNameV6"] = infrastructure.IPPoolName(w.worker.Namespace, string(gardencorev1beta1.IPFamilyIPv6))
+		}
```
Comment (ScheererJ) [inline pkg/provider-local/controller/worker/machines.go]: I would prefer a loop again over explicitly coding IPv4 and IPv6 paths.

WDYT?

**Review by ScheererJ — COMMENTED** [review]
Thanks for bringing the local setup closer to Gardener in the real world.

It looks like there are still some end-to-end tests failing, though.

File: pkg/provider-local/controller/infrastructure/actuator.go (hunk 1 above)
Comment (rfranzke) [reply pkg/provider-local/controller/infrastructure/actuator.go]: > or do we simply omit the `go` dependency?

This is the reason, we do not want to pull in the go dependency

Comment (timebertt) [reply pkg/provider-local/controller/infrastructure/actuator.go]: > I suggest to stick to the minimum and not fill in default values, which we do not need

Good point, done :)

File: pkg/provider-local/controller/infrastructure/actuator.go (hunk 2 above)
Comment (timebertt) [reply pkg/provider-local/controller/infrastructure/actuator.go]: Well, that's way more elegant. Wondering where my head was at the time 😄 
Done :)

**Comment by timebertt** [comment]
@ScheererJ thanks for checking the PR. I rebased and addressed your suggestions.
We will take a look at the failing tests later today.

**Review by ScheererJ — COMMENTED** [review]
/lgtm

**Comment by rfranzke** [comment]
Kaum macht man's richtig, schon geht's 😉
