### PR TITLE
[GEP-26] Fix backup migration from WorkloadIdentity to Secret

### LINKED ISSUE #13245: WorkloadIdentity labels and annotations are persisted on backup entry secrets even if the seed uses static credentials
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
When I enable and then revert `WorkloadIdentity` credentials for seed backup the backup entry secret in the `garden` namespace in the seed continues to have workload identity labels and annotations. This causes confusion (and essentially does not disable workload identity) as extensions determine if workload identity is enabled based on those labels and annotations.

**What you expected to happen**:
Workload identity labels and annotations to be removed.

FYI @ialidzhikov @vpnachev

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**
/kind bug
/area security ipcei
/label ipcei/workload-identity

**What this PR does / why we need it**:
Fix backup migration from WorkloadIdentity to Secret

When the WorkloadIdentity relevant annotations and labels are left on the backup bucket/entry secret in the seed, other controllers decides that indeed WorkloadIdentity credentials are being used, however they fail to reconcile because data fields like 'config' are not set. Therefore, the backupbucket and backupentry controllers now cleanup all unknown annotations and labels. Data fields are already being cleaned up.

**Which issue(s) this PR fixes**:
Fixes #13245
Part of #9586 

**Special notes for your reviewer**:

/cc @dimityrmirchev
cc @ialidzhikov @dimitar-kostadinov @plkokanov @vitanovs 

**Release note**:

```bugfix operator
Gardenlet's backupbucket and backupentry controllers are now unsetting all unknown labels and annotations on the extension secrets in the seed cluster, this fixes a bug that occurs after migration from `WorkloadIdentity` to `Secret` credentials the workload identity annotations and labels were kept in the secrets causing other controllers to keep trying to use the WorkloadIdentity credentials.
```

```bugfix developer
Backupentry generic actuator is fixed to clean all unknown annotations and labels from the `etcd-backup` secret, this change fixes issues when the credentials are switched between static secret and workload identity.
```

### CODE REVIEW

**Comment by vpnachev** [comment]
/ready

I have successfully test migration back and forth between Secret and WorkloadIdentity on GCP.

**Comment by vpnachev** [comment]
https://github.com/gardener/gardener/pull/12321 has introduced the support for Workload Identity credentials to the backup controllers and it was released with v1.123.0, provider-extensions were required to vendor this version or newer to enable support for WorkloadIdentity for ETCD backups, therefore I will open cherry pick PRs for all currently supported versions.

/cherry-pick release-v1.131

File: extensions/pkg/controller/backupentry/genericactuator/actuator.go [hunk 1]
```diff
@@ -132,6 +132,10 @@ func (a *actuator) deployEtcdBackupSecret(ctx context.Context, log logr.Logger,
 			if token, ok := etcdSecret.Data[securityv1alpha1constants.DataKeyToken]; ok {
 				etcdSecretData[securityv1alpha1constants.DataKeyToken] = token
 			}
+		} else {
+			// Unset all annotations and labels when static credentials are used.
+			etcdSecret.Annotations = map[string]string{}
```
Comment (dimityrmirchev) [inline extensions/pkg/controller/backupentry/genericactuator/actuator.go:137]: Nit: this I think is more consistent with the assignment of the labels
```suggestion
			etcdSecret.Annotations = nil
```

**Review by dimityrmirchev — COMMENTED** [review]
Looks good, one nit

File: extensions/pkg/controller/backupentry/genericactuator/actuator.go (hunk 1 above)
Comment (vpnachev) [reply extensions/pkg/controller/backupentry/genericactuator/actuator.go:137]: The reason I did not set it to `nil` is that the actuator always sets at least one annotation key-value pair, i.e. a map needs to be allocated. 

I see `metav1.SetMetaDataAnnotation` allocates a map if the annotation is `nil`, but I see nothing wrong if we do it instead of 3rd party function.

**Review by dimityrmirchev — COMMENTED** [review]
/lgtm

**Review by plkokanov — COMMENTED** [review]
/lgtm
/approve
