### PR TITLE
Fix cluster autoscaler permissions

### LINKED ISSUE #6370: cluster-autoscaler missing permissions for configmaps: expander type `priority` not usable
**How to categorize this issue?**

/area auto-scaling
/kind bug

**What happened**
Users tried to make use of customizing the cluster-autoscaler's expander to `priority` [as described in the documentation](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md). This requires adding a configmap to assign priorities to the worker pools. This configmap is watched by the cluster-autoscaler, therefore it needs permissions to do so.

Currently, we see these cluster-autoscaler logs hinting to permissions issues:
```
E0721 08:46:00.357443       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "namespaces" in API gro
up "" at the cluster scope
(...) 
E0721 08:48:10.192047       1 reflector.go:138] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:366: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resou
rce "configmaps" in API group "" in the namespace "kube-system"
```

Comparing [our clusterrole settings](https://github.com/gardener/gardener/blob/115733caad7e60110fbd379ad85b526fd151825e/pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go#L383-L458) with the official repo, we see that there is
* [additional `configmaps` permissions](https://github.com/gardener/autoscaler/blob/v1.22.1/charts/cluster-autoscaler/templates/role.yaml) defined in the `kube-system` namespace. This is also present in our fork
* [a fix for the missing `namespace` permissions](https://github.com/kubernetes/autoscaler/commit/38ccc594581b45b656c263c6e48f3213aadc06bf), which is not part of our fork, but still necessary in the version we're using apparently

This prevents the cluster-autoscaler from watching/reading the configmap, and therefore `expander: priority` doesn't work.

**What you expected to happen**
* Priority expander to work
  * When cluster-autoscaler scales up and uses the priority expander, you should see logs like this https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/priority.go#L163 or error messages if your provided configuration is [missing](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/priority.go#L64) or [incorrect](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/priority.go#L77) 
* No errors regarding permission issues in the cluster-autoscaler logs, unless we think we absolutely don't need these permissions

**How to reproduce it (as minimally and precisely as possible)**:
1. upload a configuration as described [as described in the documentation](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md)
2. Set [`clusterAutoscaler.expander: priority`](https://gardener.cloud/docs/gardener/api-reference/core/#core.gardener.cloud/v1beta1.ExpanderMode) for your Shoot
3. Create enough workload such that cluster-autoscaler is triggered
4. See a [message indicating that priority expander did its job](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/priority.go#L163) in the logs

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.51
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.23.4
```

### PR DESCRIPTION
**Pull request by voelzmo**
**How to categorize this PR?**

/area auto-scaling
/kind bug

**What this PR does / why we need it**
Adjust permissions for cluster-autoscaler, such that we don't see any error messages anymore and we can make use of `expander: priority`. At the same time, I reduced the scope of permissions for ConfigMaps, as the cluster-autoscaler only needs access to the `kube-system` namespace. 

**Which issue(s) this PR fixes**:
Fixes #6370 

**Release note**:

```bugfix user
Fixed a bug that prevented Shoots from being able to use `expander: priority` for cluster-autoscaler
```

### CODE REVIEW

**Review by himanshu-kun — APPROVED** [review]
/lgtm
Thanks for the changes, I also think a role seperately for kube-system  is better.
I have a concern/doubt though, upstream I see they still have configmap rules in [ClusterRole](https://github.com/kubernetes/autoscaler/blob/226784a223a2bc3a5c9edde714bbb6b6cc5094fb/charts/cluster-autoscaler/templates/clusterrole.yaml#L116-L122). Maybe they forgot to update it

File: pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go [hunk 1]
```diff
@@ -454,6 +448,11 @@ func (c *clusterAutoscaler) computeShootResourcesData(serviceAccountName string)
 					Resources: []string{"jobs", "cronjobs"},
 					Verbs:     []string{"get", "list", "watch"},
 				},
+				{
+					APIGroups: []string{""},
+					Resources: []string{"namespaces"},
+					Verbs:     []string{"get", "list", "watch"},
+				},
```
Comment (ialidzhikov) [inline pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go]: Nit:

```diff
--- a/pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
+++ b/pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go
@@ -409,7 +409,7 @@ func (c *clusterAutoscaler) computeShootResourcesData(serviceAccountName string)
                                },
                                {
                                        APIGroups: []string{""},
-                                       Resources: []string{"pods", "services", "replicationcontrollers", "persistentvolumeclaims", "persistentvolumes"},
+                                       Resources: []string{"namespaces", "pods", "services", "replicationcontrollers", "persistentvolumeclaims", "persistentvolumes"},
                                        Verbs:     []string{"watch", "list", "get"},
                                },
                                {
@@ -448,11 +448,6 @@ func (c *clusterAutoscaler) computeShootResourcesData(serviceAccountName string)
                                        Resources: []string{"jobs", "cronjobs"},
                                        Verbs:     []string{"get", "list", "watch"},
                                },
-                               {
-                                       APIGroups: []string{""},
-                                       Resources: []string{"namespaces"},
-                                       Verbs:     []string{"get", "list", "watch"},
-                               },
                        },
                }

```

Ref https://github.com/kubernetes/autoscaler/blob/226784a223a2bc3a5c9edde714bbb6b6cc5094fb/charts/cluster-autoscaler/templates/clusterrole.yaml#L47-L59

Comment (voelzmo) [reply pkg/operation/botanist/component/clusterautoscaler/cluster_autoscaler.go]: done, thanks for the thorough look!

**Review by ialidzhikov — COMMENTED** [review]
/lgtm
/approve
