### PR TITLE
Fix panic on initializing Shoot clients

### LINKED ISSUE #2526: Gardenlet panics when deleting Shoot
**How to categorize this issue?**

/area quality
/kind bug
/priority blocker

**What happened**:
#2449 seems to have introduced a regression: when the gardenlet tries to cleanup webhooks in the shoot with the kube-apiserver deployment scaled down to 0, it panics here:
https://github.com/gardener/gardener/blob/f120f2c74a503ab4a388aa055cd08d4081eaf5ed/pkg/operation/botanist/cleanup.go#L183

This is probably because the Shoot clients are not initialized anymore, if the kube-apiserver is scaled down:
https://github.com/gardener/gardener/blob/f120f2c74a503ab4a388aa055cd08d4081eaf5ed/pkg/operation/operation.go#L293-L300

**What you expected to happen**:
gardenlet not to panic

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: `v1.7.0-dev-e47e4c057e49b2245529ac3a7bffc943973f40d1`
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: azure (but probably also applies to others)
- Others:

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area quality
/kind bug
/priority blocker

**What this PR does / why we need it**:
This PR fixes a regression/panic introduced by #2449.
Basically the motivation in the PR was to ensure, the shoot clients are not initialized when its API server is not running at the moment (mainly to avoid, that the care controller would create new clientsets when the shoot is hibernated or being deleted). However, if the API server is scaled down for whatever reason, when the gardenlet tries to initialize clients and the reconcile/delete flow, it should not skip initializing the clients as this will cause it to panic later on in the flow when trying to use the client.

**Which issue(s) this PR fixes**:
Fixes #2526

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

File: pkg/operation/operation.go [hunk 1]
```diff
@@ -289,13 +289,15 @@ func (o *Operation) InitializeShootClients() error {
...
 	}
 
-	apiServerRunning, err := o.IsAPIServerRunning()
-	if err != nil {
-		return err
-	}
-	// Don't initialize clients for Shoots, that have are currently hibernated or in the process of being created or deleted.
-	if !apiServerRunning {
-		return nil
+	if o.Shoot.HibernationEnabled {
```
Comment (rfranzke) [inline pkg/operation/operation.go:292]: Hm, what about the case when a shoot is being woken up? Then `o.Shoot.HibernationEnabled=false`. Wouldn't it be safer to not have this condition?

Comment (timebertt) [reply pkg/operation/operation.go:292]: Actually, I just reverted this func to how it was before my PR (plus/minus renaming). The removal of this condition was actually the problem, that caused the regresssion.
If the shoot is woken up, the condition is false, so it skips checking if the API server is running and directly tries to get a client for the shoot, which is what we want in the reconcile flow. In the care controller, we don't want this, so we do the check for a running API server there.

Comment (rfranzke) [reply pkg/operation/operation.go:292]: OK, thanks for the explanation.

**Review by rfranzke — APPROVED** [review]
/lgtm
