### PR TITLE
Fix migration flow when cloud prvider config injection is required

### LINKED ISSUE #4484: Migration of hibernated Azure cluster can get stuck
**How to categorize this issue?**

/area control-plane-migration
/kind bug
/priority 3

**What happened**:
Trying to migrate a hibernated cluster on Azure can get stuck if the migration flow fails after the `ControlPlane` resource is migrated successfully, but before the kube-apiserver deployment is removed.

**What you expected to happen**:
Migration to succeed without a problem.

**How to reproduce it (as minimally and precisely as possible)**:
Create a hibernated cluster on azure. Migrate the `ControlPlane` resource manually by annotating it with `gardener.cloud/operation=migrate` and wait for the operation to succeed. Trigger shoot migration and observe that it fails when trying to scale up the kube-apiserver.

**Anything else we need to know?**:
The error is caused because migrating the `ControlPlane` removes the cloud-provider-config secret, which then prevents the provider extension from properly mutating the kube-apiserver deployment.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
For providers that require the `cloud-provider-config` secret to be injected in the kube-apiserver deployment, if the migration flow is interrupted after the `Controlplane` resource has been migrated but before the kube-apiserver deployment is deleted and the migration flow gets restarted it will fail. Additionally, for hibernated shoots on azure the `Controlplane` has to be "woken up" so that the remedy controller gets scaled up and the additional resources it manages can be properly cleaned up.

This PR adds a few additional steps to the migration flow that restore the `Controlplane` resource if the kube-apiserver deployment still exists.

**Which issue(s) this PR fixes**:
Fixes #4484

**Special notes for your reviewer**:
The migration flow now only handles managedresources deployed by gardenlet. 

**Release note**:

```bugfix operator
Fixed migration flow for shoots on providers that require the `cloud-provider-config` secret to be injected in some control plane components.
```
```bugfix operator
Fixed migration flow for hibernated clusters on azure where resources managed by the remedy controller were not removed due to the remedy controller being scaled down to 0.
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/shoot_control.go [hunk 1]
```diff
@@ -164,6 +169,14 @@ func (c *Controller) deleteClusterResourceFromSeed(ctx context.Context, shoot *g
 	return client.IgnoreNotFound(seedClient.Client().Delete(ctx, cluster))
 }
 
+func getActiveSeedName(shoot *gardencorev1beta1.Shoot) *string {
+	if shoot.Status.SeedName != nil {
+		return shoot.Status.SeedName
+	}
+
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control.go]: Nit
```suggestion
```

File: pkg/gardenlet/controller/shoot/shoot_control.go [hunk 2]
```diff
@@ -786,6 +799,51 @@ func (c *Controller) isHibernationActive(ctx context.Context, shootSeedNamespace
...
+	if providerStatus := infrastructure.Status.ProviderStatus; providerStatus != nil {
+		// The infrastructure resource has been found with a non-nil provider status, so redeploy the control plane
+		return true, nil
+	}
+
+	// The infrastructure resource has been found, but its provider status is nil
+	// In this case the control plane could not have been created at all, so no need to redeploy it
+	return false, nil
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control.go]: Nit: I think replacing this series of ifs with a `switch` would be slightly easier to read and understand.

File: pkg/gardenlet/controller/shoot/shoot_control_migrate.go [hunk 3]
```diff
@@ -83,6 +88,8 @@ func (c *Controller) runPrepareShootControlPlaneMigration(o *operation.Operation
 		botanist                     *botanistpkg.Botanist
 		err                          error
 		tasksWithErrors              []string
+		controlPlaneDeploymentNeeded bool
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_migrate.go]:
```suggestion
		controlPlaneRestorationNeeded bool
```

File: pkg/gardenlet/controller/shoot/shoot_control_migrate.go [hunk 4]
```diff
@@ -180,56 +202,104 @@ func (c *Controller) runPrepareShootControlPlaneMigration(o *operation.Operation
...
+			Name:         "Deleting all Managed Resources from the Shoot's namespace",
+			Fn:           flow.TaskFn(botanist.DeleteManagedResources),
+			Dependencies: flow.NewTaskIDs(keepManagedResourcesObjectsInShoot, ensureResourceManagerScaledUp),
+		})
+		waitForManagedResourcesDeletion = g.Add(flow.Task{
+			Name:         "Waiting until ManagedResources are deleted",
+			Fn:           flow.TaskFn(botanist.WaitUntilManagedResourcesDeleted).Timeout(10 * time.Minute),
+			Dependencies: flow.NewTaskIDs(deleteManagedResources),
+		})
 		annotateExtensionCRsForMigration = g.Add(flow.Task{
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_migrate.go]:
```suggestion
		migrateExtensionResources = g.Add(flow.Task{
```

File: pkg/gardenlet/controller/shoot/shoot_control_migrate.go [hunk 5]
```diff
@@ -180,56 +202,104 @@ func (c *Controller) runPrepareShootControlPlaneMigration(o *operation.Operation
...
 			Name:         "Annotating Extensions CRs with operation - migration",
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_migrate.go]:
```suggestion
			Name:         "Migrating extension resources",
```

File: pkg/gardenlet/controller/shoot/shoot_control_migrate.go [hunk 6]
```diff
@@ -180,56 +202,104 @@ func (c *Controller) runPrepareShootControlPlaneMigration(o *operation.Operation
...
-			Fn:           botanist.MigrateAllExtensionResources,
-			Dependencies: flow.NewTaskIDs(ensureResourceManagerScaledUp),
+			Fn:           botanist.MigrateExtensionResourcesInParallel,
+			Dependencies: flow.NewTaskIDs(waitForManagedResourcesDeletion),
 		})
 		waitForExtensionCRsOperationMigrateToSucceed = g.Add(flow.Task{
 			Name:         "Waiting until all extension CRs are with lastOperation Status Migrate = Succeeded",
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_migrate.go]:
```suggestion
		waitUntilExtensionResourcesMigrated = g.Add(flow.Task{
			Name:         "Waiting until extension resources have been migrated",
```

File: pkg/gardenlet/controller/shoot/shoot_control_migrate.go [hunk 7]
```diff
@@ -180,56 +202,104 @@ func (c *Controller) runPrepareShootControlPlaneMigration(o *operation.Operation
...
-			Fn:           botanist.WaitUntilAllExtensionResourcesMigrated,
+			Fn:           botanist.WaitUntilExtensionResourcesMigrated,
 			Dependencies: flow.NewTaskIDs(annotateExtensionCRsForMigration),
 		})
 		deleteAllExtensionCRs = g.Add(flow.Task{
 			Name:         "Deleting all extension CRs from the Shoot namespace",
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_migrate.go]:
```suggestion
		deleteExtensionResources = g.Add(flow.Task{
			Name:         "Deleting extension resources",
```

File: pkg/gardenlet/controller/shoot/shoot_control_migrate.go [hunk 8]
```diff
@@ -180,56 +202,104 @@ func (c *Controller) runPrepareShootControlPlaneMigration(o *operation.Operation
...
+			Fn:           botanist.DestroyExtensionResourcesInParallel,
 			Dependencies: flow.NewTaskIDs(waitForExtensionCRsOperationMigrateToSucceed),
-			Fn:           botanist.DestroyAllExtensionResources,
 		})
-		keepManagedResourcesObjectsInShoot = g.Add(flow.Task{
-			Name:         "Configuring Managed Resources objects to be kept in the Shoot",
-			Fn:           flow.TaskFn(botanist.KeepObjectsForAllManagedResources).DoIf(cleanupShootResources),
+		waitForExtensionCRsDeletion = g.Add(flow.Task{
+			Name:         "Waiting for all extension CRs to be deleted",
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_migrate.go]:
```suggestion
		waitUntilExtensionResourcesDeleted = g.Add(flow.Task{
			Name:         "Waiting until extension resources have been deleted",
```

File: pkg/gardenlet/controller/shoot/shoot_control_migrate.go [hunk 9]
```diff
@@ -180,56 +202,104 @@ func (c *Controller) runPrepareShootControlPlaneMigration(o *operation.Operation
...
-			Name:         "Waiting until ManagedResources are deleted",
-			Fn:           flow.TaskFn(botanist.WaitUntilAllManagedResourcesDeleted).Timeout(10 * time.Minute),
-			Dependencies: flow.NewTaskIDs(deleteAllManagedResourcesFromShootNamespace),
+		destroyControlPlane = g.Add(flow.Task{
+			Name:         "Deleting shoot control plane",
+			Fn:           flow.TaskFn(botanist.Shoot.Components.Extensions.ControlPlane.Destroy).RetryUntilTimeout(defaultInterval, defaultTimeout),
+			Dependencies: flow.NewTaskIDs(migrateControlPlane),
+		})
+		waitUntilControlPlaneDeleted = g.Add(flow.Task{
+			Name:         "Waiting until shoot control plane has been destroyed",
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_migrate.go]:
```suggestion
			Name:         "Waiting until shoot control plane has been deleted",
```

File: pkg/gardenlet/controller/shoot/shoot_control_migrate.go [hunk 10]
```diff
@@ -180,56 +202,104 @@ func (c *Controller) runPrepareShootControlPlaneMigration(o *operation.Operation
...
+			Fn:           botanist.Shoot.Components.Extensions.ControlPlane.WaitCleanup,
+			Dependencies: flow.NewTaskIDs(destroyControlPlane),
 		})
 		prepareKubeAPIServerForMigration = g.Add(flow.Task{
 			Name:         "Preparing kube-apiserver in Shoot's namespace for migration, by deleting it and its respective hvpa",
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_migrate.go]:
```suggestion
		deleteKubeAPIServer = g.Add(flow.Task{
			Name:         "Deleting kube-apiserver deployment",
```

File: pkg/gardenlet/controller/shoot/shoot_control_migrate.go [hunk 11]
```diff
@@ -180,56 +202,104 @@ func (c *Controller) runPrepareShootControlPlaneMigration(o *operation.Operation
...
-			Fn:           flow.TaskFn(botanist.Shoot.Components.ControlPlane.KubeAPIServer.Destroy).SkipIf(!kubeAPIServerDeploymentFound),
-			Dependencies: flow.NewTaskIDs(waitForManagedResourcesDeletion, waitUntilEtcdReady),
+			Fn:           flow.TaskFn(botanist.DeleteKubeAPIServer).SkipIf(!kubeAPIServerDeploymentFound),
+			Dependencies: flow.NewTaskIDs(waitForManagedResourcesDeletion, waitUntilEtcdReady, waitUntilControlPlaneDeleted),
 		})
 		waitUntilAPIServerDeleted = g.Add(flow.Task{
 			Name:         "Waiting until kube-apiserver doesn't exist",
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_migrate.go]:
```suggestion
		waitUntilKubeAPIServerDeleted = g.Add(flow.Task{
			Name:         "Waiting until kube-apiserver has been deleted",
```

File: pkg/gardenlet/controller/shoot/shoot_control_migrate.go [hunk 12]
```diff
@@ -180,56 +202,104 @@ func (c *Controller) runPrepareShootControlPlaneMigration(o *operation.Operation
...
 			Fn:           flow.TaskFn(botanist.Shoot.Components.ControlPlane.KubeAPIServer.WaitCleanup),
 			Dependencies: flow.NewTaskIDs(prepareKubeAPIServerForMigration),
 		})
+		migrateInfrastructure = g.Add(flow.Task{
+			Name:         "Migrating shoot infrastructure",
+			Fn:           botanist.Shoot.Components.Extensions.Infrastructure.Migrate,
+			Dependencies: flow.NewTaskIDs(waitUntilAPIServerDeleted),
+		})
+		waitInfrastructureMigration = g.Add(flow.Task{
+			Name:         "Waiting until shoot infrastructure migrated",
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_migrate.go]:
```suggestion
		waitUntilInfrastructureMigrated = g.Add(flow.Task{
			Name:         "Waiting until shoot infrastructure has been migrated",
```

File: pkg/operation/botanist/controlplane.go [hunk 13]
```diff
@@ -268,6 +268,12 @@ func (b *Botanist) deployOrRestoreControlPlane(ctx context.Context, controlPlane
 	return controlPlane.Deploy(ctx)
 }
 
+// RestoreControlPlane will restore the ControlPlane custom resource (purpose normal)
```
Comment (stoyanr) [inline pkg/operation/botanist/controlplane.go]:
```suggestion
// RestoreControlPlane restores the ControlPlane custom resource (purpose normal)
```

File: pkg/operation/botanist/migration.go [hunk 14]
```diff
@@ -22,27 +22,34 @@ import (
...
-	return b.runParallelTaskForEachComponent(ctx, b.Shoot.GetExtensionComponentsForMigration(), func(c component.DeployMigrateWaiter) func(context.Context) error {
+// DestroyExtensionResourcesInParallel deletes extension CRs from the Shoot namespace.
+func (b *Botanist) DestroyExtensionResourcesInParallel(ctx context.Context) error {
+	return b.runParallelTaskForEachComponent(ctx, b.Shoot.GetExtensionComponentsForParallelMigration(), func(c component.DeployMigrateWaiter) func(context.Context) error {
 		return c.Destroy
 	})
 }
 
+// WaitUntilExtensionResourcesAreDeleted waits until extension CRs are deleted from the Shoot namespace.
+func (b *Botanist) WaitUntilExtensionResourcesAreDeleted(ctx context.Context) error {
```
Comment (stoyanr) [inline pkg/operation/botanist/migration.go]:
```suggestion
// WaitUntilExtensionResourcesDeleted waits until extension CRs have been deleted from the Shoot namespace.
func (b *Botanist) WaitUntilExtensionResourcesDeleted(ctx context.Context) error {
```

File: pkg/operation/botanist/migration.go [hunk 15]
```diff
@@ -22,27 +22,34 @@ import (
...
+func (b *Botanist) MigrateExtensionResourcesInParallel(ctx context.Context) (err error) {
+	return b.runParallelTaskForEachComponent(ctx, b.Shoot.GetExtensionComponentsForParallelMigration(), func(c component.DeployMigrateWaiter) func(context.Context) error {
 		return c.Migrate
 	})
 }
 
-// WaitUntilAllExtensionResourcesMigrated waits until all extension CRs were successfully migrated.
-func (b *Botanist) WaitUntilAllExtensionResourcesMigrated(ctx context.Context) error {
-	return b.runParallelTaskForEachComponent(ctx, b.Shoot.GetExtensionComponentsForMigration(), func(c component.DeployMigrateWaiter) func(context.Context) error {
+// WaitUntilExtensionResourcesMigrated waits until extension CRs were successfully migrated.
```
Comment (stoyanr) [inline pkg/operation/botanist/migration.go]:
```suggestion
// WaitUntilExtensionResourcesMigrated waits until extension CRs have been successfully migrated.
```

**Review by stoyanr — CHANGES_REQUESTED** [review]
For now I have only some nits and naming suggestions (also involving names not changed by this PR) for consistency / readability. I will also test the PR locally and provide more feedback if I encounter any issues.

**Comment by stoyanr** [comment]
I tested successfully the following cases with a revendored azure extension:
* Migrating a hibernated azure shoot
* Migrating a hibernated azure shoot with a panic just before the `kube-apiserver` deployment is deleted
* Deleting a hibernated azure shoot

**Comment by stoyanr** [comment]
While testing migrating a hibernated gcp shoot with a non-revendored gcp extension I encountered the following error:
```
{"backupentry":"shoot--dev--i500152-gcp--1805d92f-7221-46a4-94ce-0b9e2b6250a9","flow":"Backup Entry migration","level":"info","msg":"Succeeded","task":"Waiting until extension backup entry is deleted","time":"2021-09-03T15:16:04+03:00"}
{"backupentry":"shoot--dev--i500152-gcp--1805d92f-7221-46a4-94ce-0b9e2b6250a9","flow":"Backup Entry migration","level":"info","msg":"Succeeded","task":"Deleting backup entry secret in seed","time":"2021-09-03T15:16:05+03:00"}
{"backupentry":"shoot--dev--i500152-gcp--1805d92f-7221-46a4-94ce-0b9e2b6250a9","flow":"Backup Entry migration","level":"info","msg":"Finished","time":"2021-09-03T15:16:05+03:00"}
E0903 15:16:05.780490   16472 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 655 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2e334c0, 0x45511a0)
	/Users/I500152/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/I500152/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x2e334c0, 0x45511a0)
	/usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:965 +0x1b9
github.com/gardener/gardener/pkg/gardenlet/controller/backupentry.(*reconciler).migrateBackupEntry(0xc000d1e8a0, 0x3460c20, 0xc000dc36c0, 0x348a918, 0xc000622500, 0xc00074e2c0, 0x3d, 0x3490b98, 0xc00074e2c0, 0x0)
	/Users/I500152/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/backupentry/backup_entry_reconciler.go:229 +0x32e
```
By the time I noticed it, the backup entry was already gone.

**Comment by stoyanr** [comment]
While testing migrating a hibernated gcp shoot with a non-revendored gcp extension and with a panic just before the kube-apiserver deployment is deleted, after the restart the migration is stuck with the following error:

```
{"error":"gardener operation \"restore\" is not yet picked up by controller","level":"error","msg":"ControlPlane shoot--dev--i500152-gcp/i500152-gcp did not get ready yet","operation":"migrate","shoot":"garden-dev/i500152-gcp","time":"2021-09-03T15:31:17+03:00"}
```

It seems all extensions have to be revendored first with the changes in the first commit from this PR, before it could be merged without issues.

/hold
/cc @plkokanov Let's split this PR into 2 PRs, 1 for each commit, and merge only the first one.

File: pkg/operation/shoot/shoot.go [hunk 16]
```diff
@@ -355,15 +355,13 @@ func (s *Shoot) UpdateInfoStatus(ctx context.Context, c client.Client, useStrate
 	return nil
 }
 
-// GetExtensionComponentsForMigration returns a list of component.DeployMigrateWaiters of extension components that
-// should be migrated by the shoot controller.
-func (s *Shoot) GetExtensionComponentsForMigration() []component.DeployMigrateWaiter {
+// GetExtensionComponentsForParallelMigration returns a list of component.DeployMigrateWaiters of extension components that
+// should be migrated by the shoot controller in parallel.
```
Comment (rfranzke) [inline pkg/operation/shoot/shoot.go]: You should probably state that `ControlPlane` and `Infrastructure` are not returned here and must be handled elsewhere.

**Review by stoyanr — DISMISSED** [review]
Looks good, but as mentioned above should be merged only after all extensions have been released based on g/g v1.31
/lgtm
/hold

**Comment by vpnachev** [comment]
> should be merged only after all extensions have been released based on g/g v1.31


This is not so good as each extension follow its own lifecycle and there was never official version matrix between them and the gardener. So far this was solved by feature gates that can be used to easily change the behavior and achieve compatibility until enough time has been given to all extension to be released and adopted.

Out of interest, will extension running with vendor gardener >=v1.31 run with gardener <=v1.30?

**Comment by plkokanov** [comment]
@vpnachev older gardeners can run with extensions revendored with gardener >=v1.31

As for the other question - you're right that each extension has its own lifecycle but we already have a feature gate for the control plane migration that can be disabled if necessary.
However, currently the only dependency is for provider extensions and more concretely - ControlPlane extension controllers.

**Comment by stoyanr** [comment]
Set to Draft to reflect the fact that it shouldn't be merged until certain conditions are met.

**Review by stoyanr — DISMISSED** [review]
/lgtm

File: pkg/gardenlet/controller/shoot/shoot_control.go [hunk 17]
```diff
@@ -837,6 +837,47 @@ func computeOperationType(shoot *gardencorev1beta1.Shoot) gardencorev1beta1.Last
...
+	exists, markedForDeletion, err := extensionResourceStillExists(ctx, o.K8sSeedClient.APIReader(), &extensionsv1alpha1.ControlPlane{}, namespace, name)
+	if err != nil {
+		return false, err
+	}
+
+	switch {
+	// treat `ControlPlane` in deletion as if it is already gone. If it is marked for deletion, we also shouldn't wait
+	// for it to be reconciled, as it can potentially block the whole deletion flow (deletion depends on other control
+	// plane components like kcm and grm) which are scaled up later in the flow
+	case (!exists || markedForDeletion) && !kubeAPIServerDeploymentFound:
```
Comment (rfranzke) [inline pkg/gardenlet/controller/shoot/shoot_control.go]: Earlier, this was

```golang
	if !exists && !kubeAPIServerDeploymentFound || markedForDeletion {
```

is this change intended?

File: pkg/operation/botanist/controlplane.go [hunk 18]
```diff
@@ -278,6 +278,12 @@ func (b *Botanist) deployOrRestoreControlPlane(ctx context.Context, controlPlane
 	return controlPlane.Deploy(ctx)
 }
 
+// RestoreControlPlane restores the ControlPlane custom resource (purpose normal)
+func (b *Botanist) RestoreControlPlane(ctx context.Context) error {
+	b.Shoot.Components.Extensions.ControlPlane.SetInfrastructureProviderStatus(b.Shoot.Components.Extensions.Infrastructure.ProviderStatus())
+	return b.Shoot.Components.Extensions.ControlPlane.Restore(ctx, b.GetShootState())
+}
```
Comment (rfranzke) [inline pkg/operation/botanist/controlplane.go:310]: Why is this function needed? It seems to do the same as in `DeployControlPlane`, right?

File: pkg/gardenlet/controller/shoot/shoot_control.go (hunk 17 above)
Comment (plkokanov) [reply pkg/gardenlet/controller/shoot/shoot_control.go]: Nice catch. I must have reverted it to the older logic by accident when I was rebasing the PR.

File: pkg/operation/botanist/controlplane.go (hunk 18 above)
Comment (plkokanov) [reply pkg/operation/botanist/controlplane.go:310]: DeployControlPlane will either deploy or restore the controlplane depending on whether isRestorePhase() is true, but now we also need to call Restore() during the migration phase (where it is not necessary to check if only deployment is needed). 

I thought that a separate function would be a bit more clear.

**Comment by rfranzke** [comment]
@plkokanov You have to rebase this PR, please :)

File: pkg/operation/botanist/controlplane.go (hunk 18 above)
Comment (rfranzke) [reply pkg/operation/botanist/controlplane.go:310]: OK, thanks.

**Comment by plkokanov** [comment]
Rebased the PR.
/unassign

**Review by rfranzke — APPROVED** [review]

**Comment by rfranzke** [comment]
Thanks @plkokanov!
