### PR TITLE
Fixes for concurrent access of Operation object

### LINKED ISSUE #4443: gardenlet: concurrent map writes
/area quality
/kind bug
/priority 3

**What happened**:

```
fatal error: concurrent map writes

goroutine 66549 [running]:
runtime.throw(0x254a142, 0x15)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc004a03be0 sp=0xc004a03bb0 pc=0x436fb2
runtime.mapassign_faststr(0x2207420, 0xc018c5f260, 0x253d13d, 0xd, 0xc01bc12e80)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc004a03c48 sp=0xc004a03be0 pc=0x414671
github.com/gardener/gardener/pkg/operation/botanist.(*Botanist).DeployCloudProviderSecret(0xc01933e930, 0x2854a98, 0xc00005a030, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/pkg/operation/botanist/secrets.go:207 +0x2a7 fp=0xc004a03d18 sp=0xc004a03c48 pc=0x1f6b2a7
github.com/gardener/gardener/pkg/operation/botanist.(*Botanist).DeployCloudProviderSecret-fm(0x2854a98, 0xc00005a030, 0x256b0de, 0x27)
	/go/src/github.com/gardener/gardener/pkg/operation/botanist/secrets.go:181 +0x47 fp=0xc004a03d50 sp=0xc004a03d18 pc=0x1fc26e7
github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func1(0xc01af6fb20, 0x256b0de, 0x27, 0x2854a98, 0xc00005a030)
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:223 +0x1cf fp=0xc004a03fb8 sp=0xc004a03d50 pc=0x1cef2af
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc004a03fc0 sp=0xc004a03fb8 pc=0x46d361
created by github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:218 +0x14f
```

Checkout full logs in [gardenlet-dd84747cc-wd5kj.log](https://github.com/gardener/gardener/files/6884659/gardenlet-dd84747cc-wd5kj.log)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.28.0-dev-489e985691671faac0a73bc9a4a4cf62c2acbcc2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area robustness
/kind bug

**What this PR does / why we need it**:
This PR primarily fixes a concurrent map writes bug reported in #4443. But instead of just adding the missing lock, the PR makes `checkSums` and `secrets` maps of the `Operation` struct thread safe in general. It helps to prevent such issues in the future because locking is now coordinated by the corresponding functions which must be used to mutate or read objects from these maps.

**Which issue(s) this PR fixes**:
Fixes #4443

**Release note**:

```bugfix operator
A bug has been fixed which can cause the Gardenlet to panic when VPA is enabled for shoot clusters.
```

### CODE REVIEW

File: pkg/operation/operation.go [hunk 1]
```diff
@@ -678,3 +678,44 @@ func (o *Operation) DeleteCheckSum(key string) {
 
 	delete(o.checkSums, key)
 }
+
+// StoreCheckSum stores the passed secret under the given key from the operation. Calling this function is thread-safe.
```
Comment (timebertt) [inline pkg/operation/operation.go]:
```suggestion
// StoreSecret stores the passed secret under the given key from the operation. Calling this function is thread-safe.
```

File: pkg/operation/operation.go [hunk 2]
```diff
@@ -678,3 +678,44 @@ func (o *Operation) DeleteCheckSum(key string) {
...
+	defer o.secretsMutex.RUnlock()
+
+	var keys []string
+	for key := range o.secrets {
+		keys = append(keys, key)
+	}
+	return keys
+}
+
+// LoadCheckSum loads the secret under the given key from the operation. Calling this function is thread-safe.
```
Comment (timebertt) [inline pkg/operation/operation.go]:
```suggestion
// LoadSecret loads the secret under the given key from the operation. Calling this function is thread-safe.
```

File: pkg/operation/operation.go [hunk 3]
```diff
@@ -650,3 +649,32 @@ func (o *Operation) ToAdvertisedAddresses() []gardencorev1beta1.ShootAdvertisedA
...
+
+	if o.checkSums == nil {
+		o.checkSums = make(map[string]string)
+	}
+
+	o.checkSums[key] = value
+}
+
+// LoadCheckSum loads the checksum value under the given key from the operation. Calling this function is thread-safe.
+func (o *Operation) LoadCheckSum(key string) string {
```
Comment (vpnachev) [inline pkg/operation/operation.go:666]: I am thinking if this function now have to handle the case when the key does not exist?
Currently it simply returns empty string.

Comment (timuthy) [reply pkg/operation/operation.go:666]: You're right, this is the more secure way. However, we already read values from the `CheckSums` map directly before, see this [example](https://github.com/gardener/gardener/blob/543217d363c57073e0bf681f19937e95fd6419c9/pkg/operation/botanist/controlplane.go#L65). I decided to adopt this 1:1 to only address the concurrency problem in this PR.

**Review by timebertt — APPROVED** [review]
Thank you!
/lgtm
/squash

File: pkg/operation/operation.go (hunk 3 above)
Comment (vpnachev) [reply pkg/operation/operation.go:666]: Thanks for the explanation!

**Comment by timebertt** [comment]
@timuthy should we cherry-pick this?

**Comment by timuthy** [comment]
> @timuthy should we cherry-pick this?

Yep. Let me open the required PRs for that.
