### PR TITLE
Integration test for ManagedResource

### LINKED ISSUE #4805: ☂️ Integration tests for resource-manager
**How to categorize this issue?**

/area testing dev-productivity
/kind enhancement

**What would you like to be added**:

We need several [integration tests (envtests)](https://github.com/gardener/gardener/blob/master/docs/development/testing.md#integration-tests-envtests) for gardener-resource-manager. There are a few integration tests for some of the more recent features (e.g. tokenrequestor), but the core functionality of resource-manager is not tested at all so far.

Basically, we should add integration tests for all controllers covering a reasonable amount of cases:

- [x] ManagedResource controller, basic case: create, update, delete ManagedResources; condition `ResourcesApplied` is correctly maintained: https://github.com/gardener/gardener/pull/5610 (@kris94 @plkokanov)
- [x] ManagedResource controller, condition `ResourcesHealthy` is correctly set to `Progressing`, if set of resources is changed: https://github.com/gardener/gardener/pull/5772 (@acumino)
- [x] ManagedResource controller, modes/annotations on resource: ignore, delete on invalid update, keep object: https://github.com/gardener/gardener/pull/5772 (@acumino)
- [x] ManagedResource controller, different classes: responsibility, predicates, finalizers, etc.: https://github.com/gardener/gardener/pull/5772 (@acumino)
- [x] ManagedResource controller, reconcile on operation annotation: https://github.com/gardener/gardener/pull/5772 (@acumino)
- [x] ManagedResource controller, preserve replicas/resources: resources with annotations `resources.gardener.cloud/preserve-{replicas,resources}`, resources scaled by HPA/VPA/HVPA: https://github.com/gardener/gardener/pull/5772 (@acumino)
- [x] ManagedResource controller, ignore case (https://github.com/gardener/gardener/pull/5556)
- [x] Secret controller: finalizer, reconciliation on secret change, etc.: https://github.com/gardener/gardener/pull/5687 (@acumino)
- [x] Health controller, condition `ResourcesHealthy` is correctly maintained: healthy/missing/unhealthy objects, not set if MR is currently being applied: https://github.com/gardener/gardener/pull/5469 (@timebertt)
- [x] Garbage collector, basic case: unreferenced resources are deleted, referenced resources are kept: https://github.com/gardener/gardener/pull/5534 (@rfranzke)

**Why is this needed**:

With the growing number of features of resource-manager, it becomes imperative to have automated tests for all of them to not introduce regressions / miss any important case, when performing changes to the codebase.
There are also not many unit tests for core functionality of resource-manager, so there should be at least some integration tests covering the base cases.
ref https://github.com/gardener/gardener/issues/5357

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #4805

**Special notes for your reviewer**:
This PR is supposed to complete all tasks in #4805.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 1]
```diff
@@ -254,6 +254,226 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+				Eventually(func(g Gomega) {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(BeNotFoundError())
+				}, time.Minute, 5*time.Second).Should(Succeed())
+
+				Expect(testClient.Delete(ctx, secretForManagedResource)).To(Or(Succeed(), BeNotFoundError()))
+			})
+		})
+
+		Context("#Ignore Mode", func() {
+			It("should remove the resource from the ManagedResource status", func() {
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]: can we phrase this better? 
maybe, "should not update/re-apply resources having Ignore Mode annotation"

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 2]
```diff
@@ -254,6 +254,226 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+
+			DeferCleanup(func() {
+				Expect(testClient.Delete(ctx, managedResource)).To(Or(Succeed(), BeNotFoundError()))
+				Eventually(func(g Gomega) {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(BeNotFoundError())
+				}, time.Minute, 5*time.Second).Should(Succeed())
+
+				Expect(testClient.Delete(ctx, secretForManagedResource)).To(Or(Succeed(), BeNotFoundError()))
+			})
+		})
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go:410]: Can't we reuse these code here?
https://github.com/gardener/gardener/blob/190bceffa4415cbe5eda12cd8fe878565b37a53e/test/integration/resourcemanager/managedresource/reconciler_test.go#L53-L85
We would have to adapt some code, of course.

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 3]
```diff
@@ -254,6 +309,513 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+				Expect(testClient.Create(ctx, managedResource)).To(Succeed())
+
+				Eventually(func(g Gomega) bool {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(Succeed())
+					condition := gardenerv1beta1helper.GetCondition(managedResource.Status.Conditions, resourcesv1alpha1.ResourcesApplied)
+					return condition != nil && condition.Status == gardencorev1beta1.ConditionTrue
+				}, time.Minute, time.Second).Should(BeTrue())
+			})
+
+			It("should not revert any manual update on reosurce managed by ManagedResource", func() {
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
			It("should not revert any manual update on resource managed by ManagedResource", func() {
```

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 4]
```diff
@@ -254,6 +309,513 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+				}, time.Minute, 5*time.Second).Should(Succeed())
+
+				Expect(testClient.Delete(ctx, secretForManagedResource)).To(Or(Succeed(), BeNotFoundError()))
+				Expect(testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)).To(Succeed())
+			})
+		})
+
+		Context("#Ignore", func() {
+			BeforeEach(func() {
+				configMap.SetAnnotations(map[string]string{resourcesv1alpha1.Ignore: "true"})
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go:553]: Why is the resource annotated?
Shouldn't we annotate the ManagedResource itself?

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 5]
```diff
@@ -254,6 +309,513 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+			Eventually(func(g Gomega) {
+				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(deployment), deployment)).To(BeNotFoundError())
+				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(BeNotFoundError())
+			}, time.Minute, 5*time.Second).Should(Succeed())
+
+			Expect(testClient.Delete(ctx, secretForManagedResource)).To(Or(Succeed(), BeNotFoundError()))
+		})
+
+		Context("Preserve Replicas", func() {
+			It("should not preserve changes in replica if the resource don't have annotation", func() {
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
			It("should not preserve changes in the number of replicas if the resource doesn't have annotation", func() {
```

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 6]
```diff
@@ -254,6 +309,513 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+				metav1.SetMetaDataAnnotation(&managedResource.ObjectMeta, v1beta1constants.GardenerOperation, v1beta1constants.GardenerOperationReconcile)
+				Expect(testClient.Update(ctx, managedResource)).To(Succeed())
+
+				Eventually(func(g Gomega) bool {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(deployment), deployment)).To(Succeed())
+					return *deployment.Spec.Replicas == int32(1)
+				}, time.Minute, time.Second).Should(BeTrue())
+			})
+
+			It("should preserve changes in replica if the resource has annotation", func() {
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
			It("should preserve changes in the number of replicas if the resource has annotation", func() {
```

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 7]
```diff
@@ -254,6 +309,513 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+						corev1.ResourceMemory: resource.MustParse("35Mi"),
+					},
+					Limits: corev1.ResourceList{
+						corev1.ResourceCPU:    resource.MustParse("60m"),
+						corev1.ResourceMemory: resource.MustParse("60Mi"),
+					},
+				}
+			})
+
+			It("should not preserve changes in resource requests and limits in Pod if the resource don't have annotation", func() {
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
			It("should not preserve changes in resource requests and limits in Pod if the resource doesn't have annotation", func() {
```

**Review by shafeeqes — COMMENTED** [review]
Few suggestions and some questions.

File: test/integration/resourcemanager/managedresource/reconciler_test.go (hunk 4 above)
Comment (acumino) [reply test/integration/resourcemanager/managedresource/reconciler_test.go:553]: No.

Comment (acumino) [reply test/integration/resourcemanager/managedresource/reconciler_test.go:553]: Check this https://github.com/gardener/gardener/pull/5556

Comment (shafeeqes) [reply test/integration/resourcemanager/managedresource/reconciler_test.go:553]: Yes.

"If a ManagedResource is annotated with resources.gardener.cloud/ignore=true then it will be skipped entirely by the controller (no reconciliations or deletions of managed resources at all)."

Ref: https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#preventing-reconciliations

Comment (acumino) [reply test/integration/resourcemanager/managedresource/reconciler_test.go:553]: Got it

File: test/integration/resourcemanager/managedresource/reconciler_test.go (hunk 2 above)
Comment (acumino) [reply test/integration/resourcemanager/managedresource/reconciler_test.go:410]: I have kept them separately so the contexts are clean, and the code is more readable.

Comment (shafeeqes) [reply test/integration/resourcemanager/managedresource/reconciler_test.go:410]: hmm.. I still think we can prevent repeating these lines.

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 8]
```diff
@@ -136,6 +142,55 @@ var _ = Describe("ManagedResource controller tests", func() {
 					return condition != nil && condition.Status == gardencorev1beta1.ConditionFalse
 				}, 30*time.Second, time.Second).Should(BeTrue())
 			})
+
+			It("should correctly set the condition ResourceApplied to Progressing", func() {
+				// finalizer is added so this resource can not be deleted once we remove it from the MangedResource
+				// referenced secret meanwhile adding a new resource in the refrenced secret set the ResourceApplied
+				// condition to progressing and stuck at this untill we remove finalizer from the old resource
```
Comment (ary1992) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
				// condition to progressing and stuck at this until we remove finalizer from the old resource.
```

File: test/integration/resourcemanager/managedresource/reconciler_test.go (hunk 4 above)
Comment (acumino) [reply test/integration/resourcemanager/managedresource/reconciler_test.go:553]: This is also right and expected test https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#ignoring-updates

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 9]
```diff
@@ -254,6 +309,513 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+			Expect(testClient.Delete(ctx, managedResource)).To(Or(Succeed(), BeNotFoundError()))
+			Eventually(func(g Gomega) {
+				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(BeNotFoundError())
+				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)).To(BeNotFoundError())
+			}, time.Minute, 5*time.Second).Should(Succeed())
+
+			Expect(testClient.Delete(ctx, secretForManagedResource)).To(Or(Succeed(), BeNotFoundError()))
+		})
+
+		It("controller running for default class should not reconcile ManagedResource of any other class", func() {
```
Comment (ary1992) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
		It("should not reconcile ManagedResource of any other class except the default class", func() {
```

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 10]
```diff
@@ -254,6 +309,513 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+				metav1.SetMetaDataAnnotation(&managedResource.ObjectMeta, v1beta1constants.GardenerOperation, v1beta1constants.GardenerOperationReconcile)
+				Expect(testClient.Update(ctx, managedResource)).To(Succeed())
+
+				Eventually(func(g Gomega) bool {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(deployment), deployment)).To(Succeed())
+					return compareResource(deployment.Spec.Template.Spec.Containers[0].Resources, defaultPodTemplateSpec.Spec.Containers[0].Resources)
+				}, time.Minute, time.Second).Should(BeTrue())
+			})
+
+			It("should preserve changes in resource requests and limits in Pod if the resource has annotation", func() {
```
Comment (ary1992) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]: Can we mention the annotation as well. WDYT ?

**Review by ary1992 — COMMENTED** [review]
Nicely structured PR. Just minor changes.

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 11]
```diff
@@ -136,6 +142,55 @@ var _ = Describe("ManagedResource controller tests", func() {
 					return condition != nil && condition.Status == gardencorev1beta1.ConditionFalse
 				}, 30*time.Second, time.Second).Should(BeTrue())
 			})
+
+			It("should correctly set the condition ResourceApplied to Progressing", func() {
+				// finalizer is added so this resource can not be deleted once we remove it from the MangedResource
+				// referenced secret meanwhile adding a new resource in the refrenced secret set the ResourceApplied
+				// condition to progressing and stuck at this until we remove finalizer from the old resource
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
				// this finalizer is added to prolong the deletion of the resource so that we can
				// observe the controller successfully setting ResourceApplied condition to Progressing
```

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 12]
```diff
@@ -254,6 +309,539 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+				Eventually(func(g Gomega) {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(BeNotFoundError())
+				}, time.Minute, 5*time.Second).Should(Succeed())
+
+				Expect(testClient.Delete(ctx, secretForManagedResource)).To(Or(Succeed(), BeNotFoundError()))
+			})
+		})
+
+		Context("#Ignore Mode", func() {
+			It("should not apply/create resources and remove the resource from the ManagedResource status having ignore mode annotation", func() {
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
			It("should not update/re-apply resources having ignore mode annotation and remove them from the ManagedResource status ", func() {
```
This annotation is only used for migration purposes so I think we can phrase it something like this rather than using the word create.

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 13]
```diff
@@ -254,6 +309,539 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(Succeed())
+					condition := gardenerv1beta1helper.GetCondition(managedResource.Status.Conditions, resourcesv1alpha1.ResourcesApplied)
+					return condition != nil && condition.Status == gardencorev1beta1.ConditionTrue
+				}, time.Minute, time.Second).Should(BeTrue())
+
+				Consistently(func(g Gomega) bool {
+					g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)).To(Succeed())
+					return configMap.Data != nil && configMap.Data["foo"] == "bar"
+				}, 10*time.Second, time.Second).Should(BeTrue())
+			})
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
```
Probably, you missed to remove this?

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 14]
```diff
@@ -254,6 +309,539 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+
+			It("should not revert any manual update on resources managed by ManagedResource when ManagedResource has ignore annotation", func() {
```
Comment (shafeeqes) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
			It("should not revert any manual update on the resources when the ManagedResource has ignore annotation", func() {
```

File: test/integration/resourcemanager/managedresource/reconciler_test.go (hunk 13 above)
Comment (acumino) [reply test/integration/resourcemanager/managedresource/reconciler_test.go]: No, as I mentioned above this is also a test case  https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#ignoring-updates

Comment (shafeeqes) [reply test/integration/resourcemanager/managedresource/reconciler_test.go:586]: So is it possible to ignore just one resource? I see. Cool, then.

Comment (shafeeqes) [reply test/integration/resourcemanager/managedresource/reconciler_test.go]: But, then why are we using this annotation to ignore the resource and not the ignore mode? 
I thought this annotation is particularly for managed resources.
As discussed here, https://github.com/gardener/gardener/pull/5556#discussion_r827790565

Comment (acumino) [reply test/integration/resourcemanager/managedresource/reconciler_test.go]: Ignore mode doesn't create the resource at all. But here the resource is created for the first time but later manual changes don't get reverted by the reconciler.
Please check this https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#ignoring-updates.

Comment (shafeeqes) [reply test/integration/resourcemanager/managedresource/reconciler_test.go]: I'm confused, If we could ignore updates to resources this way, why introduce #5556?

Comment (acumino) [reply test/integration/resourcemanager/managedresource/reconciler_test.go]: If we need a change for some time or some special cases.

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 15]
```diff
@@ -254,6 +309,539 @@ var _ = Describe("ManagedResource controller tests", func() {
 			})
 		})
 	})
+
+	Context("#Resource class", func() {
```
Comment (rfranzke) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]:
```suggestion
	Context("Resource class", func() {
```

 (remove those characters everywhere, those are typically only used for unit tests of a specific function)

File: test/integration/resourcemanager/managedresource/reconciler_test.go [hunk 16]
```diff
@@ -254,6 +309,539 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+
+			Consistently(func() error {
+				return testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)
+			}, 5*time.Second, time.Second).Should(BeNotFoundError())
+
+			Consistently(func(g Gomega) bool {
+				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(Succeed())
+				condition := gardenerv1beta1helper.GetCondition(managedResource.Status.Conditions, resourcesv1alpha1.ResourcesApplied)
+				return condition == nil
+			}, 10*time.Second, time.Second).Should(BeTrue())
```
Comment (rfranzke) [inline test/integration/resourcemanager/managedresource/reconciler_test.go]: This will wait `10s`, right? Do we really need this? Can't we stick to the defaults? Same below (this occurs multiple times)

**Review by rfranzke — COMMENTED** [review]
Very nice, looking forward to this improvement! Thank you!

File: test/integration/resourcemanager/managedresource/reconciler_test.go (hunk 16 above)
Comment (acumino) [reply test/integration/resourcemanager/managedresource/reconciler_test.go]: I want to give some extra time to be sure it is right for the whole time. Default is 5sec seems very low.

Comment (rfranzke) [reply test/integration/resourcemanager/managedresource/reconciler_test.go]: I think it's good enough. If the code breaks then we will probably see this test becoming flaky. `10s` doesn't bring additional value (why not even more than `10s`?) and just prolongs the test execution.

Comment (acumino) [reply test/integration/resourcemanager/managedresource/reconciler_test.go]: Will change it to default.

**Review by rfranzke — COMMENTED** [review]
/approve
