### PR TITLE
Check `ResourcesApplied` condition first while reporting MR health

### LINKED ISSUE #7451: `ManagedResource`s with a failing `ResourcesApplied` condition produce a confusing `SystemComponentsHealthy` condition in `Shoot`s
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What would you like to be added**:

A `Shoot` for which the `ResourcesApplied` condition of a `ManagedResource` is `False` can produce a confusing `SystemComponentsHealthy` condition in the `Shoot`:

```yaml
    - type: SystemComponentsHealthy
      status: 'False'
      lastTransitionTime: '2023-02-06T09:29:55Z'
      lastUpdateTime: '2023-02-05T09:31:04Z'
      reason: ChecksPending
      message: >-
        The health checks have not yet been executed for the current set of
        resources.
```

Instead, the message should be more clear indicating what the problem with the system components is.

**Details**:

When looking at the `ManagedResource`s, we can see the following conditions:

```yaml
  conditions:
  - lastTransitionTime: "2023-02-01T17:32:08Z"
    lastUpdateTime: "2023-02-01T17:32:08Z"
    message: The health checks have not yet been executed for the current set of resources.
    reason: ChecksPending
    status: Unknown
    type: ResourcesHealthy
  - lastTransitionTime: "2023-02-01T17:32:08Z"
    lastUpdateTime: "2023-02-01T17:32:08Z"
    message: Checks have not yet been executed for the current set of resources.
    reason: ChecksPending
    status: Unknown
    type: ResourcesProgressing
  - lastTransitionTime: "2023-02-06T12:30:41Z"
    lastUpdateTime: "2023-02-01T17:32:08Z"
    message: 'error during apply of object "networking.k8s.io/v1/IngressClass/default/nginx":
      IngressClass.networking.k8s.io "nginx" is invalid: spec.controller: Invalid
      value: "k8s.io/nginx": field is immutable'
    reason: ApplyFailed
    status: "False"
    type: ResourcesApplied
```

`gardenlet` could consider the message of `ResourcesApplied` when computing the result of the `SystemComponentsHealthy` condition.

**Why is this needed**:
Improve ops productivity.

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
Check the motivation for this PR in [issue](https://github.com/gardener/gardener/issues/7451). This PR prioritizes check of `ResourceApplied` condition of MR, while performing health check for ManagedResource.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/7451

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/operation/care/checker.go [hunk 1]
```diff
@@ -293,10 +293,22 @@ func (b *HealthChecker) checkManagedResourceConditions(
...
+			}
+		}
+
 		return &c
 	}
 
-	for _, cond := range mr.Status.Conditions {
+	mrConditions := make([]gardencorev1beta1.Condition, len(mr.Status.Conditions))
+	copy(mrConditions, mr.Status.Conditions)
+	sortConditions(mrConditions)
```
Comment (rfranzke) [inline pkg/operation/care/checker.go]: This is a little bit weird - if we want to check them in a specific order, then let's rather do this explicitly by using   https://github.com/gardener/gardener/blob/e753481ced744cc99e0dfb986bab54156f9bf08f/pkg/apis/core/v1beta1/helper/helper.go#L51-L61 instead of sorting and looping.

**Review by rfranzke — CHANGES_REQUESTED** [review]

File: pkg/operation/care/checker.go (hunk 1 above)
Comment (acumino) [reply pkg/operation/care/checker.go]: Addressed in 9f35955328d56ea8059d8972ab35c6d2ede523b1. PTAL

File: pkg/operation/care/checker.go [hunk 2]
```diff
@@ -293,15 +293,30 @@ func (b *HealthChecker) checkManagedResourceConditions(
...
+		}
+
 		return &c
 	}
 
-	for _, cond := range mr.Status.Conditions {
+	for _, condType := range []gardencorev1beta1.ConditionType{
+		resourcesv1alpha1.ResourcesApplied,
+		resourcesv1alpha1.ResourcesHealthy,
+		resourcesv1alpha1.ResourcesProgressing} {
```
Comment (rfranzke) [inline pkg/operation/care/checker.go]: Nit/style:

```suggestion
		resourcesv1alpha1.ResourcesProgressing,
	} {
```

**Review by rfranzke — COMMENTED** [review]
Looks good now, thanks!

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
