### PR TITLE
Report failed machines for hibernated clusters

### LINKED ISSUE #2691: Generic worker actuator doesn't check machine status when a shoot is hibernated
**How to categorize this issue?**

/area ops-productivity
/kind bug
/priority normal
/platform all
/exp intermediate
/topology seed

**What happened**:
When a shoot is hibernated then we don't check the error messages in the machines or machine deployments. For example, when the user changes the AWS credentials without updating the secret in Gardener and then tries to hibernate the shoot then it will never succeed, though, we don't show why. Let's improve this 

**What you expected to happen**:
Generic worker actuator should clearly state what is wrong.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

- Gardener version: v1.8
- Kubernetes version (use `kubectl version`): all
- Cloud provider or hardware configuration: all

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area ops-productivity
/kind bug
/priority normal

**What this PR does / why we need it**:
This PR fixes an issues which prevented machine error from being reported if the shoot is being hibernated. More details can be found in the linked issue.

I tested the change/scenario with a re-vendored GCP provider extension successfully.

**Which issue(s) this PR fixes**:
Fixes #2691

**Release note**:

```improvement operator
The generic worker actuator now also reports failed machines from the corresponding machine deployment in case the shoot cluster is being hibernated. Earlier scale down issues during hibernation were not reported to users, e.g. if something was wrong with the configured cloud provider account and thus the machine deletion was denied.
```

### CODE REVIEW

File: extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go [hunk 1]
```diff
@@ -357,9 +357,16 @@ func (a *genericActuator) waitUntilWantedMachineDeploymentsAvailable(ctx context
 				}
 			}
 
-			// If the shoot get hibernated we want to wait until all wanted machine deployments have been deleted
-			// entirely.
+			// We want to wait until all wanted machine deployments have as many
+			// available replicas as desired (specified in the .spec.replicas).
+			// However, if we see any error in the status of the deployment then we return it.
+			for _, failedMachine := range deployment.Status.FailedMachines {
```
Comment (danielfoehrKn) [inline extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go]: While you are already at it: if there are multiple failed machines, can we return a summary/or the number of all failed machines here. Otherwise only one failed machine is reported.

**Review by rfranzke — DISMISSED** [review]
/lgtm

File: extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go (hunk 1 above)
Comment (timuthy) [reply extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go]: Here my suggestion 296c56125224d7ff4d59fa544ab1e3e0407306b1.

**Comment by timuthy** [comment]
I pushed another commit (296c56125224d7ff4d59fa544ab1e3e0407306b1) to address @danielfoehrKn's comment and group all failed machines of a deployment.

File: extensions/pkg/controller/worker/helper/helper.go [hunk 2]
```diff
@@ -77,3 +82,29 @@ func GetMachineSetWithMachineClass(machineDeploymentName, machineClassName strin
...
+		}
+		descriptionPerFailedMachines[machine.LastOperation.Description] += fmt.Sprintf(", %q", machine.Name)
+	}
+
+	allErrs := &multierror.Error{
+		ErrorFormat: utilerrors.NewErrorFormatFuncWithPrefix("machine(s) failed"),
+	}
+	for description, names := range descriptionPerFailedMachines {
+		allErrs = multierror.Append(allErrs, fmt.Errorf("%s: %s", names, description))
+	}
```
Comment (rfranzke) [inline extensions/pkg/controller/worker/helper/helper.go]: What about replacing `map[string]string` with `map[string][]string` and `append`ing the machine names, so that you can later `strings.Join` them with `,` as delimiter? This way you also wouldn't need the check in line 95 whether the description is already known.

Comment (timuthy) [reply extensions/pkg/controller/worker/helper/helper.go]: Sure, no strong opinion.

**Review by rfranzke — APPROVED** [review]

**Review by danielfoehrKn — APPROVED** [review]
Thanks for improving the error messages!
