### PR TITLE
Forbid hibernating the `Shoot` during credential rotation and triggering rotation when the `Shoot` is waking up

### LINKED ISSUE #8155: gardenlet: invalid memory address or nil pointer dereference
**How to categorize this issue?**

/area quality ops-productivity
/kind bug

**What happened**:
```
% k -n garden logs gardenlet-746c5fb7d9-qz84x

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1edea2d]

goroutine 27363 [running]:
github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot.(*Reconciler).runReconcileShootFlow.func13({0x2a0d500, 0xc0ba720210})
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go:391 +0x4d
github.com/gardener/gardener/pkg/utils/flow.TaskFn.RetryUntilTimeout.func1.1({0x2a0d500?, 0xc0ba720210?})
	/go/src/github.com/gardener/gardener/pkg/utils/flow/taskfn.go:74 +0x27
github.com/gardener/gardener/pkg/utils/retry.UntilFor({0x2a0d500, 0xc0ba720210}, 0x22051c0?, {0x29fcf80?, 0xc0b3cc9400?}, 0xc0b3cc93f0)
	/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:142 +0x59
github.com/gardener/gardener/pkg/utils/retry.(*ops).Until(0xc00072b500, {0x2a0d500, 0xc0ba720210}, 0x22051c0?, 0x8bb2c97001?)
	/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:186 +0x75
github.com/gardener/gardener/pkg/utils/flow.TaskFn.RetryUntilTimeout.func1({0x2a0d538?, 0xc089b7e300?})
	/go/src/github.com/gardener/gardener/pkg/utils/flow/taskfn.go:73 +0xc3
github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func1()
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:212 +0x219
created by github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:208 +0x20f
```

The nil pointer comes from https://github.com/gardener/gardener/blob/0f62246189813cc25088fd65a23b2d6d1a5262ce/pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go#L391. `o.ShootClientSet` is nil for a Shoot with enabled hibernation:
https://github.com/gardener/gardener/blob/48bd154e4b3f2644d38f8a7a328976f85b446d36/pkg/operation/operation.go#L307-L346

**What you expected to happen**:
No such panic.

**How to reproduce it (as minimally and precisely as possible)**:
Trigger ETCD encryption key rotation and hibernation at the same time.
Or maybe even trigger etcd encryption key rotation for hibernated cluster.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.73.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area quality ops-productivity
/kind bug

**What this PR does / why we need it**:
It is not possible to support etcd-encryption key rotation and ServiceAccount signing key rotation for hibernated/hibernating Shoots as shared in https://github.com/gardener/gardener/issues/8155#issuecomment-1607066937.
If the shoot is in waking up and the rotation is triggered, and if the reconciliation is retried, this is also a problem.

This PR adds validation to:
- Forbid hibernating a shoot if ETCD encryption key rotation or ServiceAccount signing key rotation is in progress, ie; in `Preparing` or `Completing` phase.
- Forbid triggering a rotation operation on Shoots which are waking up, ie; `status.IsHibernated=true`.

**Which issue(s) this PR fixes**:
Fixes #8155

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
A bug causing the gardenlet to panic when a ETCD encryption key rotation operation is triggered for a hibernated Shoot is now fixed. Now, triggering ETCD encryption key rotation or ServiceAccount signing key rotation is forbidden when the Shoot is in waking up phase.
```

### CODE REVIEW

File: pkg/apis/core/helper/helpers.go [hunk 1]
```diff
@@ -337,7 +337,16 @@ func GetShootAuditPolicyConfigMapRef(apiServerConfig *core.KubeAPIServerConfig)
 
 // HibernationIsEnabled checks if the given shoot's desired state is hibernated.
 func HibernationIsEnabled(shoot *core.Shoot) bool {
-	return shoot.Spec.Hibernation != nil && shoot.Spec.Hibernation.Enabled != nil && *shoot.Spec.Hibernation.Enabled
+	return shoot.Spec.Hibernation != nil && pointer.BoolDeref(shoot.Spec.Hibernation.Enabled, false)
+}
+
+// HibernationIsEnabled checks if the given shoot is in hibernation or is waking up.
```
Comment (ary1992) [inline pkg/apis/core/helper/helpers.go]:
```suggestion
// IsShootInHibernation checks if the given shoot is in hibernation or is waking up.
```

File: pkg/apis/core/helper/helpers.go [hunk 2]
```diff
@@ -337,7 +337,16 @@ func GetShootAuditPolicyConfigMapRef(apiServerConfig *core.KubeAPIServerConfig)
...
+func IsShootInHibernation(shoot *core.Shoot) bool {
+	if shoot.Spec.Hibernation != nil && shoot.Spec.Hibernation.Enabled != nil {
+		return *shoot.Spec.Hibernation.Enabled || shoot.Status.IsHibernated
+	}
```
Comment (ary1992) [inline pkg/apis/core/helper/helpers.go:347]: Can it be done like this?
```suggestion
	if shoot.Spec.Hibernation != nil {
		return pointer.BoolDeref(shoot.Spec.Hibernation.Enabled, false) || shoot.Status.IsHibernated
	}
```

Comment (shafeeqes) [reply pkg/apis/core/helper/helpers.go:347]: Yes, but if `Enabled` is nil, anyways we return `status.IsHibernated` already. I don't see much benefit in changing this.

File: pkg/apis/core/validation/shoot.go [hunk 3]
```diff
@@ -1024,6 +1025,32 @@ func isPSPDisabled(kubeAPIServerConfig *core.KubeAPIServerConfig) bool {
...
+		allErrs                 = field.ErrorList{}
+		fldPath                 = field.NewPath("spec", "hibernation", "enabled")
+		hibernationEnabledInOld = old.Spec.Hibernation != nil && pointer.BoolDeref(old.Spec.Hibernation.Enabled, false)
+		hibernationEnabledInNew = new.Spec.Hibernation != nil && pointer.BoolDeref(new.Spec.Hibernation.Enabled, false)
+	)
+
+	if !hibernationEnabledInOld && hibernationEnabledInNew {
+		if new.Status.Credentials != nil && new.Status.Credentials.Rotation != nil && new.Status.Credentials.Rotation.ETCDEncryptionKey != nil {
+			etcdEncryptionKeyRotation := new.Status.Credentials.Rotation.ETCDEncryptionKey
+			if etcdEncryptionKeyRotation.Phase == core.RotationPreparing || etcdEncryptionKeyRotation.Phase == core.RotationCompleting {
```
Comment (rfranzke) [inline pkg/apis/core/validation/shoot.go]:
```suggestion		
			if etcdEncryptionKeyRotation := new.Status.Credentials.Rotation.ETCDEncryptionKey; etcdEncryptionKeyRotation.Phase == core.RotationPreparing || etcdEncryptionKeyRotation.Phase == core.RotationCompleting {
```

File: pkg/apis/core/validation/shoot.go [hunk 4]
```diff
@@ -1024,6 +1025,32 @@ func isPSPDisabled(kubeAPIServerConfig *core.KubeAPIServerConfig) bool {
...
+				allErrs = append(allErrs, field.Forbidden(fldPath, fmt.Sprintf("shoot cannot be hibernated when .status.credentials.rotation.etcdEncryptionKey.phase is %q", string(etcdEncryptionKeyRotation.Phase))))
+			}
+		}
+		if new.Status.Credentials != nil && new.Status.Credentials.Rotation != nil && new.Status.Credentials.Rotation.ServiceAccountKey != nil {
+			serviceAccountKeyRotation := new.Status.Credentials.Rotation.ServiceAccountKey
+			if serviceAccountKeyRotation.Phase == core.RotationPreparing || serviceAccountKeyRotation.Phase == core.RotationCompleting {
```
Comment (rfranzke) [inline pkg/apis/core/validation/shoot.go]:
```suggestion
			if serviceAccountKeyRotation := new.Status.Credentials.Rotation.ServiceAccountKey; serviceAccountKeyRotation.Phase == core.RotationPreparing || serviceAccountKeyRotation.Phase == core.RotationCompleting {
```

**Review by rfranzke — COMMENTED** [review]
Looks good, thanks
