### PR TITLE
Fix `gardenlet` cache sync timeout

### LINKED ISSUE #14391: `gardenlet` cache sync timeout
**How to categorize this issue?**

/area scalability
/kind bug

**What happened**:
Same as https://github.com/gardener/gardener/pull/14212 but for `gardenlet`. The waiting for cache sync times out in clusters with many `OperatingSystemConfig` resources:

Image

- Gardener version: v1.138.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area scalability
/kind bug

**What this PR does / why we need it**:
Fixes the `gardenlet` cache sync timeout in large seed clusters by deferring the registration of the complex `controllerinstallation-required` mapping functions. The registration now happens in the first reconciliation run, after the cache was successfully synced.

**Which issue(s) this PR fixes**:
Fixes #14391

**Special notes for your reviewer**:
Thanks @rfranzke for the suggestion.

This is a minimal change, easy to review, with a reduced risk for cherry-picks. Consider it a special workaround for overcoming the regression introduced with https://github.com/kubernetes-sigs/controller-runtime/pull/3406. 
On the long run, we should consider eliminating the complex mapper function by offloading the calculation of required extension kind/type combinations to the reconciler.

**Release note**:

```bugfix operator
A bug causing the `gardenlet` to crash during startup was fixed. Earlier, the startup procedure occasionally failed on large-scale seed clusters due to cache sync timeouts.
```

### CODE REVIEW

File: pkg/gardenlet/controller/controllerinstallation/required/add.go [hunk 1]
```diff
@@ -36,6 +37,17 @@ import (
 // ControllerName is the name of this controller.
 const ControllerName = "controllerinstallation-required"
 
+type eventHandlerRegistration struct {
+	once       sync.Once
+	registerFn func() error
+}
```
Comment (rfranzke) [inline pkg/gardenlet/controller/controllerinstallation/required/add.go:43]: `sync.Once` is not retriable — if `registerFn()` fails (panic recovered), the `Once` is spent and the watch is never registered. This silently degrades the controller permanently.

Replace with `sync.Mutex` + a `registered bool` so that a failed registration is retried on the next reconciliation. Return the error from `Reconcile` instead of panicking.

Also, the `eventHandlerRegistration` type is unnecessary abstraction for what it does. A single `sync.Mutex` on the reconciler guarding a `[]func() error` + `registered bool` is simpler and sufficient — all registrations happen at the same point anyway.

**Review by rfranzke — CHANGES_REQUESTED** [review]
Overall approach makes sense — deferring the costly `source.Kind` watch registration until after the cache is synced is the right idea.

Main concern is the `sync.Once` + `utilruntime.Must` combination: if the watch registration fails for a transient reason, the panic is recovered, but `sync.Once` is permanently spent. The watch is never registered, and the controller silently degrades — it keeps reconciling but can never correctly determine which `ControllerInstallation`s are required. No retry, no error surfaced.

File: pkg/gardenlet/controller/controllerinstallation/required/add.go (hunk 1 above)
Comment (timuthy) [reply pkg/gardenlet/controller/controllerinstallation/required/add.go:43]: Thanks for the feedback.

> Also, the eventHandlerRegistration type is unnecessary abstraction for what it does. A single sync.Mutex on the reconciler guarding a []func() error + registered bool is simpler and sufficient — all registrations happen at the same point anyway.

I partly disagree with the AI here 😆 We should stick to the mutex per registration function which prevents re-registering already added event handler in previous runs.

File: pkg/gardenlet/controller/controllerinstallation/required/add.go [hunk 2]
```diff
@@ -36,6 +36,28 @@ import (
...
+
+func (e *eventHandlerRegistration) registerOnce() error {
+	e.lock.Lock()
+	defer e.lock.Unlock()
+
+	if e.registered {
+		return nil
+	}
```
Comment (rfranzke) [inline pkg/gardenlet/controller/controllerinstallation/required/add.go:51]: Nit: This could be at the very top, before the lock?

**Review by rfranzke — COMMENTED** [review]
/lgtm

File: pkg/gardenlet/controller/controllerinstallation/required/add.go (hunk 2 above)
Comment (timuthy) [reply pkg/gardenlet/controller/controllerinstallation/required/add.go:51]: I think this will be racy.

t0 - process1: `e.registered` --> `false`
t1 - process2: `e.registered` --> `false`
t2 - process1: acquires lock, calls `e.registerFn()`
t3 - process2: waiting for lock
t4 - process1: sets `e.registered = true`, releases lock, exits function
t5 - process2: acquires lock, calls `e.registerFn()` --> ❌ should not happen

**Review by oliver-goetz — APPROVED** [review]
thanks for fixing 🚀 

/approve
