### PR TITLE
Trigger project reconcile on shoot creation and add LastActivity timestamp to the project

### LINKED ISSUE #4417: Stale project controller does not detect project usage
**How to categorize this issue?**

/kind bug
/area ops-productivity robustness usability
/priority 3

**What happened**:
The stale project controller is  reconciling the project resource on pre-defined period of time. The default sync period is 12 hours and during this long time a user can create and delete a shoot cluster, the controller will not see it and will still consider the project as stale 

**What you expected to happen**:
Each usage of project to be counted when considering it as stale.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This can be mitigated by using much shorter sync periods, e.g. 5 to 15m as the shoot creation and deletion usually requires 10+ minutes.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by krgostev**
**How to categorize this PR?**

/area ops-productivity
/kind bug

**What this PR does / why we need it**:
1. This PR adds `LastActivityTimestamp` field to the `Project` status to track whether the project is in use or not.
During the reconcile process of the stale project controller it will check this timestamp and it will compare it with the `MinimumLifetimeDays` to determine if the project was used recently and should be marked as stale or not.

2. Event handlers for newly created shoots is added. This way when a new shoot is added to the project it will update the `LastActivityTimestamp` and then it will trigger reconcile process in the stale project controller. That way stale projects will be updated immediately when used. Also, the implementation is generic and all objects can use `updateLastActivityTimestamp` function if needed.
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```other operator
Projects are now reconciled every time a shoot is created.
```

### CODE REVIEW

File: pkg/apis/core/types_project.go [hunk 1]
```diff
@@ -75,6 +75,9 @@ type ProjectStatus struct {
 	Phase ProjectPhase
 	// StaleSinceTimestamp contains the timestamp when the project was first discovered to be stale/unused.
 	StaleSinceTimestamp *metav1.Time
+	// LastActivityTimestamp contains the timestamp from the last activity performed in this project.
+	// +optional
```
Comment (timuthy) [inline pkg/apis/core/types_project.go]: Not needed for internal API types.

File: pkg/apis/core/v1alpha1/types_project.go [hunk 2]
```diff
@@ -89,13 +89,16 @@ type ProjectStatus struct {
 	ObservedGeneration int64 `json:"observedGeneration,omitempty" protobuf:"varint,1,opt,name=observedGeneration"`
 	// Phase is the current phase of the project.
 	Phase ProjectPhase `json:"phase,omitempty" protobuf:"bytes,2,opt,name=phase,casttype=ProjectPhase"`
+	// LastActivityTimestamp contains the timestamp from the last activity performed in this project.
+	// +optional
+	LastActivityTimestamp *metav1.Time `json:"lastActivityTimestamp,omitempty" protobuf:"bytes,3,opt,name=lastActivityTimestamp"`
```
Comment (timuthy) [inline pkg/apis/core/v1alpha1/types_project.go]: Changing the order in protobuf is an incompatible change. Thus, you need to append the new field.

File: pkg/apis/core/v1beta1/types_project.go [hunk 3]
```diff
@@ -89,13 +89,16 @@ type ProjectStatus struct {
 	ObservedGeneration int64 `json:"observedGeneration,omitempty" protobuf:"varint,1,opt,name=observedGeneration"`
 	// Phase is the current phase of the project.
 	Phase ProjectPhase `json:"phase,omitempty" protobuf:"bytes,2,opt,name=phase,casttype=ProjectPhase"`
+	// LastActivityTimestamp contains the timestamp from the last activity performed in this project.
+	// +optional
+	LastActivityTimestamp *metav1.Time `json:"lastActivityTimestamp,omitempty" protobuf:"bytes,3,opt,name=lastActivityTimestamp"`
```
Comment (timuthy) [inline pkg/apis/core/v1beta1/types_project.go]: Changing the order in protobuf is an incompatible change. Thus, you need to append the new field.

File: pkg/controllermanager/controller/project/project.go [hunk 4]
```diff
@@ -97,9 +101,14 @@ func NewProjectController(
 		DeleteFunc: func(obj interface{}) { projectController.roleBindingDelete(ctx, obj) },
 	})
 
+	shootInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+		AddFunc: func(obj interface{}) { projectController.updateLastActivityTimestamp(ctx, obj) },
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project.go]: The `AddFunc` will be called every time the GCM is started, i.e. it will iterate over all shoots and updates the `LastActivityTimestamp` which is probably not what we want. Instead, I suggest to register and `UpdateFunc` and renew the `LastActivityTimestamp` when the shoot was first scheduled on a seed.

**Review by timuthy — CHANGES_REQUESTED** [review]
I had a first quick look and added a few suggestions.

File: pkg/controllermanager/controller/project/project.go (hunk 4 above)
Comment (krgostev) [reply pkg/controllermanager/controller/project/project.go]: Make sense, but I am not sure that this will work if the user creates a shoot with `spec.SeedName:<seed>`. 
Also, the update function will be called far more often and I don't think that we need to know about every update of the shoot, or other resources, but only when new resources are created. 
I will try a solution where the `AddFunc`  will compare the `CreationTimestamp` of the object with the `LastActivityTimestamp`, and then it will update the last activity only if the creation timestamp is newer, if that make sense to you.

Comment (timuthy) [reply pkg/controllermanager/controller/project/project.go]: Okay thanks 👍  Maybe it's also worth a thought to write a separate reconciler for this concern because it enables you to react upon error, e.g. you can re-queue the request in case an update error happened. WDYT?

Comment (krgostev) [reply pkg/controllermanager/controller/project/project.go]: I have played around with the code to see what will turn out and I don't think that we should overcomplicate by adding another reconciler just for this field in the project status. I would prefer if we stick to that approach that is similar to what is done with the [RoleBInding update](https://github.com/gardener/gardener/blob/master/pkg/controllermanager/controller/project/rolebinding_control.go)

Comment (timuthy) [reply pkg/controllermanager/controller/project/project.go]: > I would prefer if we stick to that approach that is similar to what is done with the RoleBInding update

The difference is that "RoleBInding update" only does a mapping while your event handler also mutates a resource. There won't be any retries if that update fails, i.e. a new timestamp will only be set when another shoot is created or GCM is restarted.

I think we ideally had:
1) Reconciler which updates the `status.lastActivityTimestamp` whenever a relevant resource is created (shoot)
2) Update from (1) triggers the `ProjectStaleReconciler` which marks the project as not stale

This has the following benefits even though with a bigger boilerplate code:
- Retry in case of an error of lastActivityTimestamp
- Tests for new reconciler can be added easily (whereas there are no tests in this PR for the event handler)
- Isolation & separation of concern
- Follows controller best practices

File: pkg/controllermanager/controller/project/project_control.go [hunk 5]
```diff
@@ -125,6 +127,49 @@ func (r *projectReconciler) reportEvent(project *gardencorev1beta1.Project, isEr
...
+		logger.Logger.Errorf("Couldn't split namespace key %s due to: %v", objKey, err)
+		return
+	}
+
+	project, err := gutil.ProjectForNamespaceFromReader(ctx, c.gardenClient, namespace)
+	if err != nil {
+		if apierrors.IsNotFound(err) {
+			logger.Logger.Debugf("Secret don`t belong to a project: %v", err)
+			return
+		}
```
Comment (vpnachev) [inline pkg/controllermanager/controller/project/project_control.go]: Do you need this check?
If yes, the error message should not be about secret bot for Project. And it would be nice to include project and namespace names in the error message.

File: pkg/controllermanager/controller/project/project_control.go [hunk 6]
```diff
@@ -125,6 +127,49 @@ func (r *projectReconciler) reportEvent(project *gardencorev1beta1.Project, isEr
...
+		logger.Logger.Errorf("Couldn't get project due to: %v", err)
+		return
+	}
+
+	if clientObject, ok := obj.(client.Object); ok {
+		if clientObject.GetCreationTimestamp().UTC().After(project.Status.LastActivityTimestamp.UTC()) {
```
Comment (vpnachev) [inline pkg/controllermanager/controller/project/project_control.go]: You can avoid one nested if block here.
```suggestion
	if clientObject, ok := obj.(client.Object); ok  && clientObject.GetCreationTimestamp().UTC().After(project.Status.LastActivityTimestamp.UTC()) {
```

File: pkg/controllermanager/controller/project/project_control.go [hunk 7]
```diff
@@ -125,6 +127,49 @@ func (r *projectReconciler) reportEvent(project *gardencorev1beta1.Project, isEr
...
+			if err := updateStatus(ctx, c.gardenClient, project, func() {
+				now := metav1.Now()
```
Comment (vpnachev) [inline pkg/controllermanager/controller/project/project_control.go]: I guess it should be the object creation timestamp
```suggestion
				now := clientObject.GetCreationTimestamp()
```

**Review by vpnachev — COMMENTED** [review]
Thanks!

Could you change the PR description so that #4417 to be not closed when this PR is merged because there are other resources that should be considered, too. 

See https://github.com/gardener/gardener/blob/v1.28.0/docs/concepts/controller-manager.md#stale-projects-reconciler for more details. 

Probably, you can now also mention the new status field `lastActivityTimestamp` in this document.

**Comment by krgostev** [comment]
@timuthy  I have added a reconciler and some unit tests as requested.
@vpnachev I think we can add the other resources  in this PR as well. This would mean that there will be a different reconciler for every object. My only concern is  about the `Secret` objects, because there will be quite a lot of API calls, especially on GCM restart.

**Comment by vpnachev** [comment]
> My only concern is about the Secret objects, because there will be quite a lot of API calls, especially on GCM restart.

Valid point, and we are having this concern since long time. I guess the secret binding controller can take care to label the referred secrets with something like `secretbinding.gardener.cloud/referred : true` (you can come with other name) and then filter only for the secrets matching this label. Anyway, I think this deserves dedicated PR and should not be implemented in this one.

File: pkg/controllermanager/controller/project/project_activity_control.go [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+		}); err != nil {
+			logger.Logger.Errorf("Error while updating project: %v", err)
+			return reconcile.Result{}, err
+		}
+		return r.projectStaleReconciler.Reconcile(ctx, reconcile.Request{NamespacedName: types.NamespacedName{Name: project.Name, Namespace: project.Name}})
+	}
+	return reconcile.Result{}, nil
+}
+
+func (c *Controller) updateShootActivity(ctx context.Context, obj interface{}) {
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_activity_control.go]: The passed context is unused.

File: pkg/controllermanager/controller/project/project_activity_control.go [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+		gardenClient:           gardenClient,
+		projectsLastActivity:   projectsLastActivityMap,
+		projectStaleReconciler: projectStaleReconciler,
+	}
+}
+
+type projectActivityReconciler struct {
+	logger                 logrus.FieldLogger
+	gardenClient           client.Client
+	config                 *config.ProjectControllerConfiguration
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_activity_control.go]: Why is `config` needed here?

File: pkg/controllermanager/controller/project/project_activity_control.go [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+	projectsLastActivity   map[string]metav1.Time
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_activity_control.go]: Leftover?

File: pkg/controllermanager/controller/project/project_activity_control.go [hunk 11]
```diff
@@ -0,0 +1,101 @@
...
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/types"
+	"k8s.io/client-go/tools/cache"
+
+	"github.com/sirupsen/logrus"
+	"sigs.k8s.io/controller-runtime/pkg/client"
+	"sigs.k8s.io/controller-runtime/pkg/reconcile"
+)
+
+// NewProjectStaleReconciler creates a new instance of a reconciler which reconciles the LastActivityTimestamp of a project, then it calls the stale reconciler.
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_activity_control.go]:
```suggestion
// NewActivityReconciler creates a new instance of a reconciler which reconciles the LastActivityTimestamp of a project, then it calls the stale reconciler.
```

File: pkg/controllermanager/controller/project/project_activity_control.go [hunk 12]
```diff
@@ -0,0 +1,101 @@
...
+
+	if obj.GetCreationTimestamp().UTC().After(project.Status.LastActivityTimestamp.UTC()) {
+		if err := updateStatus(ctx, r.gardenClient, project, func() {
+			now := obj.GetCreationTimestamp()
+			project.Status.LastActivityTimestamp = &now
+		}); err != nil {
+			logger.Logger.Errorf("Error while updating project: %v", err)
+			return reconcile.Result{}, err
+		}
+		return r.projectStaleReconciler.Reconcile(ctx, reconcile.Request{NamespacedName: types.NamespacedName{Name: project.Name, Namespace: project.Name}})
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_activity_control.go]: Suggestion: Change the [projectUpdate](https://github.com/gardener/gardener/blob/83deabdcd595c7672a872ce8f811bf58c95d1d79/pkg/controllermanager/controller/project/project_control.go#L44) event handler to enqueue the project `c.projectStaleQueue.Add(key)` when `project.Status.LastActivityTimestamp` is updated. This way, you get rid of the `projectStaleReconciler` dependency.

**Review by timuthy — CHANGES_REQUESTED** [review]
Thanks for the changes @kris94. I added a few comments. Can you also update the documentation about the stale project handling in https://github.com/gardener/gardener/blob/master/docs/concepts/controller-manager.md?

**Comment by timuthy** [comment]
@kris94 can you please check the failing `verify` step?

File: pkg/controllermanager/controller/project/project_control.go [hunk 13]
```diff
@@ -46,8 +46,12 @@ func (c *Controller) projectUpdate(oldObj, newObj interface{}) {
 	if !ok {
 		return
 	}
+	oldProject, ok := oldObj.(*gardencorev1beta1.Project)
+	if !ok {
+		return
+	}
 
-	if newProject.Generation == newProject.Status.ObservedGeneration {
+	if newProject.Generation == newProject.Status.ObservedGeneration && newProject.Status.LastActivityTimestamp == oldProject.Status.LastActivityTimestamp {
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_control.go]: Hm, why do you want to enqueue also to `projectQueue` (by calling c.projectAdd(newObj) below)? If `newProject.Status.LastActivityTimestamp != oldProject.Status.LastActivityTimestamp` then `c.projectStaleQueue.Add(key)` should be called, right?

File: pkg/controllermanager/controller/project/project_control_reconcile.go [hunk 14]
```diff
@@ -142,10 +142,13 @@ func (r *projectReconciler) reconcile(ctx context.Context, project *gardencorev1
...
 	}
 
-	// Update the project status to mark it as 'ready'.
+	// Update the project status to mark it as 'ready' and add activity timestamp if it is missing.
 	if err := updateStatus(ctx, gardenClient, project, func() {
 		project.Status.Phase = gardencorev1beta1.ProjectReady
 		project.Status.ObservedGeneration = generation
+		if project.Status.LastActivityTimestamp == nil {
+			project.Status.LastActivityTimestamp = &project.CreationTimestamp
+		}
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_control_reconcile.go]: Can you elaborate why this is needed? Normally, [this check](https://github.com/gardener/gardener/blob/c71c50b53bb7de36a441d9d4df43cb1dd6ac89ae/pkg/controllermanager/controller/project/project_stale_control.go#L109) already considers newly created projects.

File: docs/concepts/controller-manager.md [hunk 15]
```diff
@@ -84,6 +85,12 @@ The component configuration of the Gardener Controller Manager offers to configu
 
 > Gardener administrators/operators can exclude specific `Project`s from the stale check by annotating the related `Namespace` resource with `project.gardener.cloud/skip-stale-check=true`.
 
+#### "Activity" Reconciler
+
+Since the other two reconcilers are unable to actively monitor the relevant objects that are used in a `Project` (`Shoot`, `Plant`, etc.), there could be a situation where the user creates and deletes objects in a short period of time. In that case the `Stale Project Reconciler` could not see that there was any activity on that project and it will still mark it as a `Stale`, even though it is actively used.
+
+The `Project Activity Reconciler` is implemented to take care of such cases. An event handler will notify the reconciler for any acitivity (Currently only for `Shoots`) and then it will update the `Project.Status.LastActivityTimestamp`. This update will also trigger the `Stale Project Reconciler`.
```
Comment (timuthy) [inline docs/concepts/controller-manager.md:92]:
```suggestion
The `Project Activity Reconciler` is implemented to take care of such cases. An event handler will notify the reconciler for any activity (currently only for `Shoots`) and then it will update the `Project.Status.LastActivityTimestamp`. This update will also trigger the `Stale Project Reconciler`.
```

File: pkg/controllermanager/controller/project/project_activity_control_test.go [hunk 16]
```diff
@@ -0,0 +1,196 @@
...
+		namespace = &corev1.Namespace{
+			ObjectMeta: metav1.ObjectMeta{Name: namespaceName},
+		}
+		partialObjectMetadata = &metav1.PartialObjectMetadata{
+			ObjectMeta: metav1.ObjectMeta{Namespace: namespaceName},
+		}
+
+		logger.Logger = logger.NewLogger("info")
+		ctrl = gomock.NewController(GinkgoT())
+		k8sGardenRuntimeClient = mockclient.NewMockClient(ctrl)
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_activity_control_test.go:104]: Can you double check the `EXPECT()` calls for this mock. I think there are a few leftovers after you removed the dependency to the stale project reconciler.

**Review by timuthy — CHANGES_REQUESTED** [review]

File: pkg/controllermanager/controller/project/project_control.go (hunk 13 above)
Comment (krgostev) [reply pkg/controllermanager/controller/project/project_control.go]: Yes exactly, I have completely missed that

File: pkg/controllermanager/controller/project/project_control_reconcile.go (hunk 14 above)
Comment (krgostev) [reply pkg/controllermanager/controller/project/project_control_reconcile.go]: The last activity timestamp may not be set on older projects so we need to initialise it first somewhere. Otherwise there would be panics in the activity reconciler. Thats why I have added [this](https://github.com/gardener/gardener/blob/3b0f8dc8eba36d78b63dba523f3f1b1065bb9808/pkg/controllermanager/controller/project/project_activity_control.go#L71) as well.

File: pkg/controllermanager/controller/project/project_activity_control_test.go (hunk 16 above)
Comment (krgostev) [reply pkg/controllermanager/controller/project/project_activity_control_test.go:104]: Yep, there were some `EXPECT()s` that were not actually expected

File: pkg/controllermanager/controller/project/project_control_reconcile.go (hunk 14 above)
Comment (timuthy) [reply pkg/controllermanager/controller/project/project_control_reconcile.go]: > The last activity timestamp may not be set on older projects so we need to initialise it first somewhere.

Suggestion: Also set it `project_activity_control.go` because logically it belongs to that controller. If you want to take a shortcut there, then iterate over all shoots in the project namespace and take the newest one for the `LastActivityTimestamp`. This spares a lot of update calls for existing projects when the timestamp is set.

Comment (krgostev) [reply pkg/controllermanager/controller/project/project_control_reconcile.go]: I don't think we need to iterate over all shoots because the first update for whatever reason will trigger the activity reconciler and with the last change of the `reconcile()`function  the `LastActivityTimestamp` will be set.

Comment (timuthy) [reply pkg/controllermanager/controller/project/project_control_reconcile.go]: A start of GCM will cause the `AddFunc` to be called for every shoot at a random order (at least I'm not aware of any specific order). Hence, if you have a project with shoots, but the project doesn't have a `LastActivityTimestamp`, then the reconciliation function will update the project status probably many times in a row until the newest `CreationTimestamp` is set.

Comment (krgostev) [reply pkg/controllermanager/controller/project/project_control_reconcile.go]: Ok now I see what you mean, thanks!

File: pkg/controllermanager/controller/project/project_control.go [hunk 17]
```diff
@@ -46,6 +46,19 @@ func (c *Controller) projectUpdate(oldObj, newObj interface{}) {
 	if !ok {
 		return
 	}
+	oldProject, ok := oldObj.(*gardencorev1beta1.Project)
+	if !ok {
+		return
+	}
+
+	if newProject.Status.LastActivityTimestamp != oldProject.Status.LastActivityTimestamp {
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_control.go]:
```suggestion
	if reflect.DeepEqual(newProject.Status.LastActivityTimestamp, oldProject.Status.LastActivityTimestamp) {
```
The pointer comparison before will always be true.

File: pkg/controllermanager/controller/project/project_control_reconcile.go [hunk 18]
```diff
@@ -142,7 +142,7 @@ func (r *projectReconciler) reconcile(ctx context.Context, project *gardencorev1
 		}
 	}
 
-	// Update the project status to mark it as 'ready'.
+	// Update the project status to mark it as 'ready' and add activity timestamp if it is missing.
```
Comment (timuthy) [inline pkg/controllermanager/controller/project/project_control_reconcile.go]:
```suggestion
	// Update the project status to mark it as 'ready'.
```

**Review by timuthy — CHANGES_REQUESTED** [review]

**Review by timuthy — APPROVED** [review]
/lgtm

File: docs/concepts/controller-manager.md [hunk 19]
```diff
@@ -71,6 +71,7 @@ This reconciler is enabled by default and works as following:
     1. `BackupEntry` resources.
     1. `Secret` resources that are referenced by a `SecretBinding` that is in use by a `Shoot` (not necessarily in the same namespace).
     1. `Quota` resources that are referenced by a `SecretBinding` that is in use by a `Shoot` (not necessarily in the same namespace).
+    1. The time period when the projet was used for the last time (`Project.Status.LastActivityTimestamp`) is longer than the configured `minimumLifetimeDays`
```
Comment (vpnachev) [inline docs/concepts/controller-manager.md:74]:
```suggestion
    1. The time period when the projet was used for the last time (`.status.lastActivityTimestamp`) is longer than the configured `minimumLifetimeDays`
```
Just looking around resource fields are referenced this way.

File: docs/concepts/controller-manager.md (hunk 15 above)
Comment (vpnachev) [reply docs/concepts/controller-manager.md:92]:
```suggestion
The `Project Activity Reconciler` is implemented to take care of such cases. An event handler will notify the reconciler for any acitivity (Currently only for `Shoots`) and then it will update the `.status.lastActivityTimestamp`. This update will also trigger the `Stale Project Reconciler`.
```

File: pkg/controllermanager/controller/project/project_activity_control_test.go [hunk 20]
```diff
@@ -0,0 +1,186 @@
...
+		Expect(err).To(HaveOccurred())
+		Expect(reconcileResult).To(Equal(reconcile.Result{}))
+	})
+
+	It("Reconcile should fail since the projects can not be listed ", func() {
+		reconcileResult, err := reconciler.Reconcile(ctx, errorRequest)
+		Expect(err).To(HaveOccurred())
+		Expect(reconcileResult).To(Equal(reconcile.Result{}))
+	})
+	It("The empty LastActivityTimestamp should be set to the newest shoot", func() {
```
Comment (vpnachev) [inline pkg/controllermanager/controller/project/project_activity_control_test.go:179]:
```suggestion
	})

	It("The empty LastActivityTimestamp should be set to the newest shoot", func() {
```

File: pkg/controllermanager/controller/project/project_activity_control_test.go [hunk 21]
```diff
@@ -0,0 +1,186 @@
...
+
+			return nil
+		})
+
+		k8sGardenRuntimeClient.EXPECT().Patch(ctx, gomock.AssignableToTypeOf(&gardencorev1beta1.Project{}), gomock.Any()).DoAndReturn(
+			func(_ context.Context, prj *gardencorev1beta1.Project, _ client.Patch, _ ...client.PatchOption) error {
+				*project = *prj
+				return nil
+			},
+		).AnyTimes()
```
Comment (vpnachev) [inline pkg/controllermanager/controller/project/project_activity_control_test.go:142]: This should not be expected in all tests. Project patch request is not always sent.

File: pkg/controllermanager/controller/project/project_activity_control_test.go [hunk 22]
```diff
@@ -0,0 +1,186 @@
...
+				}
+			}
+			return apierrors.NewNotFound(gardencorev1beta1.Resource("Project"), "<unknown>")
+		})
+
+		k8sGardenRuntimeClient.EXPECT().List(ctx, gomock.AssignableToTypeOf(&gardencorev1beta1.ShootList{}), gomock.Any()).DoAndReturn(func(_ context.Context, obj *gardencorev1beta1.ShootList, _ ...client.ListOption) error {
+			obj.Items = []gardencorev1beta1.Shoot{*shoot, *shootWithoutProject, *errorShoot}
+
+			return nil
+		})
```
Comment (vpnachev) [inline pkg/controllermanager/controller/project/project_activity_control_test.go:135]: This is expected only if the last activity timestamp is not set, otherwise there will be no list shoots requests.

**Review by vpnachev — COMMENTED** [review]
As long as the shoot exist and has no deletion timestamp, shouldn't you set the last activity timestamp to `time.Now()`?

**Comment by timuthy** [comment]
> As long as the shoot exist and has no deletion timestamp, shouldn't you set the last activity timestamp to time.Now()?

We can think about that when the user changes the shoot spec, that makes probably sense for semantic reasons.
