### PR TITLE
Fix: Forbid creation/update of expired k8s/machine image versions 

### LINKED ISSUE #8824: Shoot worker pools can be updated to reference expired OS versions
**How to categorize this issue?**

/area os
/kind bug

**What happened**:

Creating a new Shoot with an expired OS version for its worker pools is impossible and will be caught by the admission controller. However, an existing Shoot can be updated with a new/modified worker pool that references an expired OS version.

**What you expected to happen**:

Updating a Shoot with an expired OS version should be impossible (at least for end-users and their automation).

**How to reproduce it (as minimally and precisely as possible)**:

Create a Shoot. Once the Shoot is up and running, update the Shoot manifest and add another worker pool that references an expired OS version (that is still present in the CloudProfile).

**Anything else we need to know?**:

Probably caused by the `a.GetOperation() == admission.Update` check in https://github.com/gardener/gardener/blob/f05b0d1c0442966cbe9186d5d97ca18be607aa70/plugin/pkg/shoot/validator/admission.go#L1508-L1511

**Environment**:

- Gardener version: v1.83.1
- Kubernetes version (use `kubectl version`): irrelevant

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**How to categorize this PR?**

/area ops-productivity
/kind bug

**What this PR does / why we need it**:

Fixed a bug where a Shoot with an expired machine image or Kubernetes version could be created. 

**For machine images**: only allow updating to a higher expired machine image version for an existing worker pool
**For Kubernetes versions**: do not allow creation of a worker pool with an expired K8s version, but still allow updating an existing worker pool to a higher expired version.

**Background**: Updating to a **higher** expired version is required for consecutive force updates by the maintenance controller. But previously, an update or creation using any expired version was allowed, which makes it difficult to remove expired versions from the cloudprofile (can always revert the force update by the maintenance controller).

**Which issue(s) this PR fixes**:
Fixes #8824

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fixed a bug where a Shoot with an expired machine image or Kubernetes version could be created. 
For machine images: only allow updating to a higher expired machine image version for an existing worker pool
For Kubernetes versions: do not allow creation of a worker pool with an expired K8s version, but still allow updating an existing worker pool to a higher expired version.
```

### CODE REVIEW

File: plugin/pkg/shoot/validator/admission.go [hunk 1]
```diff
@@ -1505,27 +1509,38 @@ func validateMachineImagesConstraints(a admission.Attributes, constraints []core
 		for _, machineVersion := range machineImage.Versions {
 			machineImageVersion := fmt.Sprintf("%s:%s", machineImage.Name, machineVersion.Version)
 
-			// update to an expired version is allowed (required for maintenance force updates)
-			if a.GetOperation() == admission.Update || machineVersion.ExpirationDate == nil || machineVersion.ExpirationDate.Time.UTC().After(time.Now().UTC()) {
+			if machineVersion.ExpirationDate == nil || machineVersion.ExpirationDate.Time.UTC().After(time.Now().UTC()) {
 				activeMachineImageVersions.Insert(machineImageVersion)
+			} else if machineVersion.ExpirationDate != nil && machineVersion.ExpirationDate.Time.UTC().Before(time.Now().UTC()) && a.GetOperation() == admission.Update && !isNewWorkerPool {
+				// An already expired machine image version is a viable machine image version for the worker pool iff.
```
Comment (plkokanov) [inline plugin/pkg/shoot/validator/admission.go]:
```suggestion
				// An already expired machine image version is a viable machine image version for the worker pool if:
```

File: plugin/pkg/shoot/validator/admission.go [hunk 2]
```diff
@@ -1505,27 +1509,38 @@ func validateMachineImagesConstraints(a admission.Attributes, constraints []core
...
+				//  - this is an update call (no new Shoot creation)
+				//  - updates an existing worker pool (not for a new worker pool)
+				//  - the expired version is higher than the old machine's version
+				// Reason: updating an existing worker pool to an expired machine image version is required for maintenance force updates
+				downgrade, _ := versionutils.CompareVersions(machineVersion.Version, "<", oldMachine.Image.Version)
```
Comment (plkokanov) [inline plugin/pkg/shoot/validator/admission.go:1520]: Shouldn't we still perform the error check here? We have validation whether the versions can be parsed, but what if `CompareVersions` starts returning errors in other cases?

**Review by plkokanov — CHANGES_REQUESTED** [review]

File: plugin/pkg/shoot/validator/admission.go (hunk 2 above)
Comment (danielfoehrKn) [reply plugin/pkg/shoot/validator/admission.go:1520]: The first argument `machineVersion` comes from the cloud profile and is known to be parseable. The second argument comes from the the machine image of the existing shoot (not the just updated version), which we also know is parseable.
The `CompareVersion` Utils only returns an error in two cases in the subroutine [here](https://github.com/gardener/gardener/blob/187d3e2045e717bd3197ffa924252c4803af37aa/pkg/utils/version/version.go#L78-L77) which can only happen in the `semver.NewConstraint` & `semver.NewVersion`. For the former, we know that the operator `<` and the version are valid, hence there cannot be an error (unless the `semVer` package has a bug) . For the latter, only an error can be returned if the version cannot be parsed which we already established above cannot be the case.

That's why I don't think we need an error check here.

File: plugin/pkg/shoot/validator/admission.go (hunk 1 above)
Comment (danielfoehrKn) [reply plugin/pkg/shoot/validator/admission.go]: That was a short-hand for if-and-only-if, I made it more clear now, thanks.

File: plugin/pkg/shoot/validator/admission.go (hunk 2 above)
Comment (plkokanov) [reply plugin/pkg/shoot/validator/admission.go:1520]: After I checked the PR, I saw that we have multiple similar places where we skip the error check :).

**Review by acumino — COMMENTED** [review]
/approve
