### PR TITLE
Log a minor retriable error as info instead of an error

### LINKED ISSUE #8148: Don't log minor retriable errors as errors
**How to categorize this issue?**

/area logging ops-productivity
/kind enhancement

**What would you like to be added**:
https://github.com/gardener/gardener/blob/e7599b86f3d0a6c30910bccc5501408ef474e399/pkg/extensions/customresources.go#L95-L129
On line 107 the error might be minor that will cause the function to retry. In this case I don't see the point in logging it as error. Instead it is better to be logged as info.  This is an extraction from gardenlet logs where we have 4 error logs for transient errors that get resolved.

```
2023-06-20 12:50:29	{"log":{"controller":"shoot","flow":"Shoot cluster deletion","level":"info","msg":"Succeeded","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"161f6648-4c9d-4567-b373-d2599a8281e4","task":"Deploying main and events etcd","ts":"2023-06-20T12:50:29.224Z"}}
2023-06-20 12:50:35	{"log":{"controller":"shoot","flow":"Shoot cluster deletion","level":"info","msg":"Succeeded","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"161f6648-4c9d-4567-b373-d2599a8281e4","task":"Scaling up etcd main and event","ts":"2023-06-20T12:50:35.486Z"}}
2023-06-20 12:50:35	{"log":{"controller":"shoot","error":"gardener operation \"reconcile\" is not yet picked up by etcd-druid","etcd":"shoot--foo--bar/etcd-main","level":"error","msg":"Object did not get ready yet","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"161f6648-4c9d-4567-b373-d2599a8281e4","stacktrace":"github.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction.func1\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:107\ngithub.com/gardener/gardener/pkg/utils/retry.UntilFor\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:142\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).Until\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:186\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).UntilTimeout\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:193\ngithub.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:95\ngithub.com/gardener/gardener/pkg/component/etcd.(*etcd).Wait\n\t/go/src/github.com/gardener/gardener/pkg/component/etcd/waiter.go:42\ngithub.com/gardener/gardener/pkg/utils/flow.Parallel.func1.1\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/taskfn.go:132","ts":"2023-06-20T12:50:35.486Z"}}
2023-06-20 12:50:35	{"log":{"controller":"shoot","error":"gardener operation \"reconcile\" is not yet picked up by etcd-druid","etcd":"shoot--foo--bar/etcd-events","level":"error","msg":"Object did not get ready yet","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"161f6648-4c9d-4567-b373-d2599a8281e4","stacktrace":"github.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction.func1\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:107\ngithub.com/gardener/gardener/pkg/utils/retry.UntilFor\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:142\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).Until\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:186\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).UntilTimeout\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:193\ngithub.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:95\ngithub.com/gardener/gardener/pkg/component/etcd.(*etcd).Wait\n\t/go/src/github.com/gardener/gardener/pkg/component/etcd/waiter.go:42\ngithub.com/gardener/gardener/pkg/utils/flow.Parallel.func1.1\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/taskfn.go:132","ts":"2023-06-20T12:50:35.486Z"}}
2023-06-20 12:50:40	{"log":{"controller":"shoot","error":"is not ready yet","etcd":"shoot--foo--bar/etcd-events","level":"error","msg":"Object did not get ready yet","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"161f6648-4c9d-4567-b373-d2599a8281e4","stacktrace":"github.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction.func1\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:107\ngithub.com/gardener/gardener/pkg/utils/retry.UntilFor\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:142\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).Until\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:186\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).UntilTimeout\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:193\ngithub.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:95\ngithub.com/gardener/gardener/pkg/component/etcd.(*etcd).Wait\n\t/go/src/github.com/gardener/gardener/pkg/component/etcd/waiter.go:42\ngithub.com/gardener/gardener/pkg/utils/flow.Parallel.func1.1\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/taskfn.go:132","ts":"2023-06-20T12:50:40.487Z"}}
2023-06-20 12:50:45	{"log":{"controller":"shoot","error":"is not ready yet","etcd":"shoot--foo--bar/etcd-events","level":"error","msg":"Object did not get ready yet","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"161f6648-4c9d-4567-b373-d2599a8281e4","stacktrace":"github.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction.func1\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:107\ngithub.com/gardener/gardener/pkg/utils/retry.UntilFor\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:142\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).Until\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:186\ngithub.com/gardener/gardener/pkg/utils/retry.(*ops).UntilTimeout\n\t/go/src/github.com/gardener/gardener/pkg/utils/retry/retry.go:193\ngithub.com/gardener/gardener/pkg/extensions.WaitUntilObjectReadyWithHealthFunction\n\t/go/src/github.com/gardener/gardener/pkg/extensions/customresources.go:95\ngithub.com/gardener/gardener/pkg/component/etcd.(*etcd).Wait\n\t/go/src/github.com/gardener/gardener/pkg/component/etcd/waiter.go:42\ngithub.com/gardener/gardener/pkg/utils/flow.Parallel.func1.1\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/taskfn.go:132","ts":"2023-06-20T12:50:45.488Z"}}
2023-06-20 12:50:50	{"log":{"controller":"shoot","flow":"Shoot cluster deletion","level":"info","msg":"Succeeded","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"161f6648-4c9d-4567-b373-d2599a8281e4","task":"Waiting until main and event etcd report readiness","ts":"2023-06-20T12:50:50.488Z"}}
```
**Why is this needed**:
Better ops productivity when searching for severe errors

### PR DESCRIPTION
**Pull request by Kostov6**
**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:
There is an transient error that gets logged as an actual error. We will just log it as info

**Which issue(s) this PR fixes**:
Fixes: https://github.com/gardener/gardener/issues/8148

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/extensions/customresources.go [hunk 1]
```diff
@@ -223,7 +223,7 @@ func WaitUntilExtensionObjectDeleted(
 		}
 
 		if lastErr := obj.GetExtensionStatus().GetLastError(); lastErr != nil {
-			log.Error(fmt.Errorf(lastErr.Description), "Object did not get deleted yet")
+			log.Info("Object did not get deleted yet", "details", lastErr.Description)
```
Comment (rfranzke) [inline pkg/extensions/customresources.go]:
```suggestion
			log.Info("Object did not get deleted yet", "description", lastErr.Description)
```

?

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
