### PR TITLE
extensions-healthcheck: skip cluster lookup for seed class

### LINKED ISSUE #14161: Extension healthcheck fails for seed extensions
**How to categorize this issue?**

/area TODO
/kind bug

**What happened**:

With https://github.com/gardener/gardener/pull/13789, it added support for the garden class but if you use the seed class on extensions there is also no cluster object present. Therefore the healthcheck reconciler errors out:
```
2026-02-25T12:44:58.609Z    ERROR    Reconciler error    {"controller": "healthcheck-Extension-extensions.gardener.cloud-v1alpha1-FCKa4Rk5z8", "namespace": "garden", "name": "my-extension", "reconcileID": "ad964efe-8e12-4f6d-9c4c-73ab2c077ee3", "error": "Cluster.extensions.gardener.cloud \"garden\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
    sigs.k8s.io/controller-runtime@v0.22.5/pkg/internal/controller/controller.go:474
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
    sigs.k8s.io/controller-runtime@v0.22.5/pkg/internal/controller/controller.go:421
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func1.1
    sigs.k8s.io/controller-runtime@v0.22.5/pkg/internal/controller/controller.go:296
```

The extension looks like this:
```yaml
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: my-extension
  namespace: garden
spec:
  class: seed
  type: my-extension
```

**What you expected to happen**:
Healthcheck controller for extensions should work for Seed extensions

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: my-extension
  namespace: garden
spec:
  class: seed
  type: my-extension
```

```go
import "github.com/gardener/gardener/extensions/pkg/controller/healthcheck"

var opts = healthcheck.DefaultAddArgs{
	ExtensionClass: extensionsv1alpha1.ExtensionClassShoot
}

func registerHealthChecks(mgr manager.Manager, extensionType string, checks []healthcheck.ConditionTypeToHealthCheck, opts *healthcheck.DefaultAddArgs) error {
  return healthcheck.DefaultRegistration(
  	extensionType,
  	extensionsv1alpha1.SchemeGroupVersion.WithKind(extensionsv1alpha1.ExtensionResource),
  	func() client.ObjectList { return &extensionsv1alpha1.ExtensionList{} },
  	func() extensionsv1alpha1.Object { return &extensionsv1alpha1.Extension{} },
  	mgr,
  	*opts,
  	nil,
  	checks,
  	nil,
  )
}
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.36
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by hown3d**
**How to categorize this PR?**

/area dev-productivity ops-productivity
/kind enhancement

**What this PR does / why we need it**:
Support healthcheck reconciler for extension of class **seed**.

**Which issue(s) this PR fixes**:
Fixes #14161

**Special notes for your reviewer**:
/cc @theoddora @timuthy 

**Release note**:

```bugfix developer
The healthcheck controller now supports the seed extension class.
```

### CODE REVIEW

File: extensions/pkg/controller/healthcheck/controller.go [hunk 1]
```diff
@@ -219,6 +220,23 @@ func getHealthCheckTypes(healthChecks []ConditionTypeToHealthCheck) []string {
...
+	switch extensionClass {
+	case extensionsv1alpha1.ExtensionClassGarden:
+		return false
+	case extensionsv1alpha1.ExtensionClassSeed:
+		return false
+	case extensionsv1alpha1.ExtensionClassShoot:
+		return true
+	default:
+		return false
+	}
```
Comment (timuthy) [inline extensions/pkg/controller/healthcheck/controller.go]:
```suggestion
func isShootClass(extensionClass extensionsv1alpha1.ExtensionClass) bool {
	return extensionClass == extensionsv1alpha1.ExtensionClassShoot
	}
```

Nit: This is even easier. The shoot class is the only one relevant for the cluster object.

File: extensions/pkg/controller/healthcheck/healthcheck_actuator.go [hunk 2]
```diff
@@ -274,6 +274,9 @@ func (a *Actuator) getPreCheckFuncObject(ctx context.Context, request types.Name
 		}
 		return garden, nil
 	}
+	if !classesHaveClusterObject(a.extensionClasses) {
```
Comment (hown3d) [inline extensions/pkg/controller/healthcheck/healthcheck_actuator.go:277]: I am not sure what to do in this case. The precheck func could panic if it expects the object to always be populated. WDYT how to handle this?

Comment (timuthy) [reply extensions/pkg/controller/healthcheck/healthcheck_actuator.go:277]: Generally, I think it is fine: Supporting the `seed` class is an enhancement and we could document [here](https://github.com/gardener/gardener/blob/e3707e999b9112cc6559d73792fc861ef99d05e4/extensions/pkg/controller/healthcheck/actuator.go#L50) that `nil` is passed in such a scenario.
It would be consistent to pass the `Seed` object in such a case, but we can't easily derive the seed name here ...

**Review by timuthy — COMMENTED** [review]
Thanks for taking care! :)

**Review by timuthy — COMMENTED** [review]
/approve
@hown3d I'd like to suggest a release note change. Would you adapt it please?
"The healthcheck controller now supports the `seed` extension class."

**Comment by hown3d** [comment]
Release note is adapted 👍

**Review by timuthy — COMMENTED** [review]
/lgtm
