### PR TITLE
Deploy `Etcd` CRDs independent of Etcd bootstrap

### LINKED ISSUE #7997: Seed creation is failing
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
While creating a seed, it never gets healthy with the error `waiting for required extension to get ready`.  This https://github.com/gardener/gardener/pull/7928 PR introduced a check which checks for required extension to get ready for seed before any other things are deployed [ref](https://github.com/gardener/gardener/blob/26de2da9046127d0fe1a7c7ae2a10f163adc698b/pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go#L464C1-L467).

But there are provider-extension which need `etcd` crds [ref](https://github.com/gardener/gardener-extension-provider-aws/blob/ef0455a950ee6d947372d818e284e6741a1b7659/pkg/webhook/controlplaneexposure/add.go#LL53C4-L53C4) to present to get healthy.

This creates a deadlock as provider-extension waits for ectd crds to be present to get healthy, whereas etcds crds deployment step is after the check of required extension to get healthy.
Because of above case seed never gets a chance to get healthy.

/cc @ary1992 

**What you expected to happen**:
Seed creation to succeed successfully.

**How to reproduce it (as minimally and precisely as possible)**:
- make `kind-extension-up`
- make `gardener-extension-up`

check for seed status, as it never gets healthy and complains that `required extensions are not ready`.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 716d42380275fd13344a5f12466bb824e018d1a9
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR separates the Etcd CRD deployment from Etcd Bootstrap step. Check the motivation for this PR in https://github.com/gardener/gardener/issues/7997

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/7997

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/component/etcd/crd.go [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+	"github.com/gardener/gardener/pkg/client/kubernetes"
+	"github.com/gardener/gardener/pkg/component"
+	"github.com/gardener/gardener/pkg/utils/flow"
+	gardenerutils "github.com/gardener/gardener/pkg/utils/gardener"
+)
+
+var (
+	//go:embed crds/templates/crd-druid.gardener.cloud_etcds.yaml
+	// CRD holds the etcd custom resource definition template
+	CRD string
```
Comment (rfranzke) [inline pkg/component/etcd/crd.go:38]:
```suggestion
	etcdCRD string
```

File: pkg/operator/controller/garden/reconciler_delete.go [hunk 2]
```diff
@@ -170,6 +170,11 @@ func (r *Reconciler) delete(
 			Fn:           flow.TaskFn(c.hvpaCRD.Destroy).DoIf(hvpaEnabled()),
 			Dependencies: flow.NewTaskIDs(destroyGardenerResourceManager),
 		})
+		_ = g.Add(flow.Task{
+			Name:         "Destroying custom resource definition for ETCD/EtcdCopyBackupsTask",
```
Comment (rfranzke) [inline pkg/operator/controller/garden/reconciler_delete.go]:
```suggestion
			Name:         "Destroying ETCD-related custom resource definitions",
```

File: pkg/operator/controller/garden/reconciler_reconcile.go [hunk 3]
```diff
@@ -113,6 +113,10 @@ func (r *Reconciler) reconcile(
 				return r.generateGenericTokenKubeconfig(ctx, secretsManager)
 			},
 		})
+		deployEtcdCRD = g.Add(flow.Task{
+			Name: "Deploying custom resource definition for ETCD/EtcdCopyBackupsTask",
```
Comment (rfranzke) [inline pkg/operator/controller/garden/reconciler_reconcile.go]:
```suggestion
			Name: "Deploying ETCD-related custom resource definitions",
```

File: pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go [hunk 4]
```diff
@@ -377,6 +377,17 @@ func (r *Reconciler) runReconcileSeedFlow(
 	// Deploy the CRDs in the seed cluster.
 	log.Info("Deploying custom resource definitions")
 
+	if !seedIsGarden {
```
Comment (rfranzke) [inline pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go:380]: Please adapt https://github.com/gardener/gardener/blob/master/test/integration/gardenlet/seed/seed/seed_test.go to cover this case

File: pkg/gardenlet/controller/seed/seed/reconciler_delete.go [hunk 5]
```diff
@@ -339,6 +340,11 @@ func (r *Reconciler) runDeleteSeedFlow(
 				Fn:           component.OpDestroyAndWait(fluentOperator).Destroy,
 				Dependencies: flow.NewTaskIDs(destroyFluentOperatorResources),
 			})
+			destroyEtcdCRD = g.Add(flow.Task{
+				Name:         "Destroy custom resource definition for ETCD/EtcdCopyBackupsTask",
```
Comment (rfranzke) [inline pkg/gardenlet/controller/seed/seed/reconciler_delete.go]:
```suggestion
				Name:         "Destroy ETCD-related custom resource definitions",
```

File: pkg/component/etcd/crd.go [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+	//go:embed crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
+	etcdCopyBackupsTaskCRD string
+
+	etcdCRDName                = "etcds.druid.gardener.cloud"
+	etcdCopyBackupsTaskCRDName = "etcdcopybackupstasks.druid.gardener.cloud"
+	crdResources               []string
+)
+
+type etcdCRD struct {
```
Comment (rfranzke) [inline pkg/component/etcd/crd.go]:
```suggestion
type crd struct {
```

File: pkg/component/etcd/bootstrap.go [hunk 7]
```diff
@@ -375,8 +359,6 @@ func (b *bootstrapper) Deploy(ctx context.Context) error {
 	if err != nil {
 		return err
 	}
-	resources["crd.yaml"] = []byte(CRD)
-	resources["crdEtcdCopyBackupsTask.yaml"] = []byte(etcdCopyBackupsTaskCRD)
```
Comment (rfranzke) [inline pkg/component/etcd/bootstrap.go:379]: This will make GRM try to delete the CRDs, right?
I guess we have to keep them with the ignore annotation for at least one release.

**Review by rfranzke — CHANGES_REQUESTED** [review]

File: pkg/component/etcd/crd.go (hunk 1 above)
Comment (acumino) [reply pkg/component/etcd/crd.go:38]: This is exported for testing.

File: pkg/component/etcd/bootstrap.go (hunk 7 above)
Comment (acumino) [reply pkg/component/etcd/bootstrap.go:379]: Adapted in a668c17cf65f1e98fc2ea0e23e938d2ff33c3261

File: pkg/component/etcd/bootstrap.go [hunk 8]
```diff
@@ -375,8 +370,8 @@ func (b *bootstrapper) Deploy(ctx context.Context) error {
...
+	resources["crd.yaml"] = []byte(etcdCRD)
```
Comment (rfranzke) [inline pkg/component/etcd/bootstrap.go:375]: Add a TODO statement to clean this up after v1.72 got released.

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

Thanks!
