### PR TITLE
Include signing CA certificate in `kube-apiserver`'s certificate chain

### LINKED ISSUE #7905: CA not returned by api server during tls handshake
/area control-plane
/area security
/kind bug

**What happened**:

AWS requires the certificate authority to be present in the certificate chain that is returned by the jwt issuer. This way it can be verified against the thumbprint that is configured on the AWS side.

I am trying to configure AWS IRSA to trust the service account tokens in my gardener shoot. The api server in gardener shoots does not return a certificate chain that includes the CA - it only returns the server certificate.
Since the CA is not returned by that shoot's api server , authentication against AWS IRSA fails with error like this:
> InvalidIdentityToken: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint

_mroe info from my side:_

AWS IAM stores only a hash (thumbprint) of the jwt issuer's certificate in the oidc trust configuration. As stated by AWS support personnel, this trust mechanism does not support verifying CAs not returned explicitly by the jwt issuer endpoint.

**What you expected to happen**:

api-server to return a certificate chain that contains the CA

**How to reproduce it (as minimally and precisely as possible)**:

Configure IRSA for gardener shoot
1. enable anonymous auth
2. give anonymous rbac for jwt discovery
3. in aws iam, put thumbprint of the CA (not api server cert) in oidc provider config
4. configure pod with irsa (role arn in env, projected token with correct audience)
5. aws auth fails due to mismatched jwt issuer cert

**Anything else we need to know?**:

I'm not sure but kubernetes api-server does seem to support returning a CA via `--tls-cert-file`. official doc:
> File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert).

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Environment**:

- Gardener version: 1.68.2
- Kubernetes version (use `kubectl version`): 1.25.8
- Cloud provider or hardware configuration: aws
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:
With this PR, the certificate chain of `kube-apiserver` not only includes its server certificate but also the CA certificate used to sign it.

**Which issue(s) this PR fixes**:
Fixes #7905

**Special notes for your reviewer**:
/cc @dimityrmirchev 

**Release note**:

```feature user
The certificate chains served by `kube-apiserver`s does now include the CA certificates used to sign their server certificates.
```

### CODE REVIEW

File: pkg/utils/secrets/certificate.go [hunk 1]
```diff
@@ -162,11 +167,17 @@ func (c *Certificate) SecretData() map[string][]byte {
 		// compatibility).
 		data[DataKeyCertificateCA] = c.CertificatePEM
 		data[DataKeyPrivateKeyCA] = c.PrivateKeyPEM
+
 	case c.CA != nil:
-		// The certificate is not a CA certificate, so we add the signing CA certificate to it and use different
-		// keys in the secret data.
+		cert := c.CertificatePEM
```
Comment (dimityrmirchev) [inline pkg/utils/secrets/certificate.go:172]: I am wondering if it make sense to copy/clone the slices always instead of returning the same underlying data in some cases 🤔 Basically if I modify the elements of a slice returned by the `SecretData` function do I also expect to modify the elements of the `Certificate` slice? There is the [Clone](https://pkg.go.dev/golang.org/x/exp/slices#Clone) function that can help to prevent that. This will also be included in the std lib with go 1.21.

**Review by dimityrmirchev — COMMENTED** [review]
Thanks for opening the PR! I have just one question which is not strictly connected to the functionality introduced with this PR. Other looks good.

File: pkg/utils/secrets/certificate.go (hunk 1 above)
Comment (rfranzke) [reply pkg/utils/secrets/certificate.go:172]: While you are probably right, I think this is quite theoretical and also already the case in many other places. We can certainly consider streamlining this, but probably in a different PR and not only in this particular file but perhaps the larger code base.

Comment (dimityrmirchev) [reply pkg/utils/secrets/certificate.go:172]: Agree. I just wanted to point that out as something that can be improved in the future.

**Review by dimityrmirchev — APPROVED** [review]
/lgtm

**Review by acumino — COMMENTED** [review]
/approve
