### PR TITLE
Isolate envtests

### LINKED ISSUE #4036: [Flaky Test] `ControllerManager Shoot Controller Suite` fails with data race
/area testing
/kind flake
/priority 3

**Which test(s)/suite(s) are flaking**:
`ControllerManager Shoot Controller Suite` and `Gardener Envtest Suite` fail with data race

**CI link**:
- https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-head-update-job/builds/234
- https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-head-update-job/builds/233
- https://concourse.ci.gardener.cloud/builds/11207009

**Reason for failure**:

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area testing
/kind enhancement

**What this PR does / why we need it**:

Extract envtests into dedicated directories to run them isolated from unit tests (just like k/k does it) to
- apply different timeout settings for unit / integration tests
- disable the race detector for envtests
- increase stability in pipelines

Also, disable metrics serving in envtests (makes test suites runnable in parallel, e.g. with `stress`).

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/3765
Fixes https://github.com/gardener/gardener/issues/4036

**Special notes for your reviewer**:

**Release note**:

```other developer
Envtests are now run in a dedicated make target (`make test-integration`).
```
```other dependency
Envtests that require the control plane binaries now have to be run using `hack/test-integration.sh`. Please consult gardener's [Makefile](https://github.com/gardener/gardener/blob/master/Makefile) as a reference usage.
```

### CODE REVIEW

**Comment by timebertt** [comment]
Rebased to resolve conflicts.

**Comment by timebertt** [comment]
Rebased to resolve conflicts.

File: test/integration/envtest/shootretry/shootretry_suite_test.go [hunk 1]
```diff
@@ -0,0 +1,93 @@
+// Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```
Comment (vpnachev) [inline test/integration/envtest/shootretry/shootretry_suite_test.go]:
```suggestion
// Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```

File: test/integration/envtest/shootretry/shootretry_suite_test.go [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+	. "github.com/onsi/gomega"
+	"k8s.io/client-go/rest"
+	"sigs.k8s.io/controller-runtime/pkg/client"
+	logf "sigs.k8s.io/controller-runtime/pkg/log"
+	logzap "sigs.k8s.io/controller-runtime/pkg/log/zap"
+	"sigs.k8s.io/controller-runtime/pkg/manager"
+
+	"github.com/gardener/gardener/pkg/client/kubernetes"
+	"github.com/gardener/gardener/pkg/envtest"
+	"github.com/gardener/gardener/test/framework"
```
Comment (vpnachev) [inline test/integration/envtest/shootretry/shootretry_suite_test.go]:
```suggestion
	"github.com/gardener/gardener/pkg/client/kubernetes"
	"github.com/gardener/gardener/pkg/envtest"
	"github.com/gardener/gardener/test/framework"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"k8s.io/client-go/rest"
	"sigs.k8s.io/controller-runtime/pkg/client"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	logzap "sigs.k8s.io/controller-runtime/pkg/log/zap"
	"sigs.k8s.io/controller-runtime/pkg/manager"
```

File: test/integration/envtest/shootretry/shootretry_control_test.go [hunk 3]
```diff
@@ -35,6 +28,13 @@ import (
 	"sigs.k8s.io/controller-runtime/pkg/handler"
 	"sigs.k8s.io/controller-runtime/pkg/manager"
 	"sigs.k8s.io/controller-runtime/pkg/source"
+
+	gardencorev1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
+	"github.com/gardener/gardener/pkg/controllermanager/apis/config"
+	"github.com/gardener/gardener/pkg/controllermanager/controller/shoot"
+	"github.com/gardener/gardener/pkg/logger"
+	retryutils "github.com/gardener/gardener/pkg/utils/retry"
+	. "github.com/gardener/gardener/pkg/utils/test/matchers"
```
Comment (vpnachev) [inline test/integration/envtest/shootretry/shootretry_control_test.go]: Make this second import block again.

**Review by vpnachev — COMMENTED** [review]
Overall lgtm, just some nits.

File: test/integration/envtest/shootretry/shootretry_suite_test.go (hunk 2 above)
Comment (timebertt) [reply test/integration/envtest/shootretry/shootretry_suite_test.go]: I'm not sure, why you are suggesting this.
The import blocks are well-formed (stdlib, external, local imports separated and sorted) and `goimports` (i.e. `make check`) accepts it. I thought, we agreed on just accepting such sorting, if it's accepted by `goimports`.

Should we formalize this agreement somewhere?
If you rather want to have stricter sorting than what `goimports` provides, let's forge that into some tooling that can automate sorting + verification. I would vote against it, because imports should generally be nothing to care about and we wanted to go with community-supported tools.

Comment (vpnachev) [reply test/integration/envtest/shootretry/shootretry_suite_test.go]: Actually, I think we have some agreement on this but I do not recall if we have it somewhere documented. 
The policy was first block is always the built-in packages, then the second block is about the repository own packages and the third block is the 3rd party packages.

Comment (timebertt) [reply test/integration/envtest/shootretry/shootretry_suite_test.go]: For the sake of getting this PR in and not blocking on this discussion, I sorted the imports as suggested by you.

**Review by vpnachev — DISMISSED** [review]
/lgtm

**Comment by timebertt** [comment]
Rebased one more time to resolve conflicts.

**Review by vpnachev — DISMISSED** [review]
/lgtm

**Comment by timebertt** [comment]
Fixed failing tests for `DNSRecord`.

**Comment by stoyanr** [comment]
/lgtm
Tested locally, works great.

**Review by stoyanr — APPROVED** [review]
