### PR TITLE
Fix disabling of seed VPA

### LINKED ISSUE #5810: VPA is wrongly deployed when Seed `.spec.settings.verticalPodAutoscaler.enabled=false`
**How to categorize this issue?**

/area auto-scaling
/kind bug
/kind regression

**What happened**:
We observe a high amount Pod evictions by VPA for our ManagedSeeds.

```
$ k get events -A | grep EvictedByVPA | wc -l
1027
```

We have 2 VPA stacks acting for the same clusters leading to this high number of Pod evictions.

Our ManagedSeeds enable VPA in the Shoot spec with `spec.kubernetes.verticalPodAutoscaler.enabled=true`. And disable the Seed VPA in the Seed spec with  `.spec.settings.verticalPodAutoscaler.enabled=false`.

It seems that after https://github.com/gardener/gardener/pull/5745 the Seed VPA is wrongly deployed when Seed `.spec.settings.verticalPodAutoscaler.enabled=false`.

Before:

```
$ k -n garden get deploy -l gardener.cloud/role=vpa
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
vpa-exporter   1/1     1            1           490d
```

After:

```
$ k -n garden get deploy -l gardener.cloud/role=vpa
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
vpa-admission-controller   1/1     1            1           2m43s
vpa-exporter               1/1     1            1           2m44s
vpa-recommender            1/1     1            1           2m43s
vpa-updater                1/1     1            1           2m44s
```

(`vpa-admission-controller`, `vpa-recommender`, `vpa-updater` are wrongly deployed, the only present deployment should be `vpa-exporter`)

**What you expected to happen**:
VPA components to be not deployed when Seed `.spec.settings.verticalPodAutoscaler.enabled=false`.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: f5882800d5821bcc18198da96324bbe013bb1afe
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area auto-scaling
/kind bug

**What this PR does / why we need it**:
Ensures that the seed VPA is properly destroyed when the corresponding seed setting is false, fixing the previous issue introduced with #5745.

**Which issue(s) this PR fixes**:
Fixes #5810 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
NONE
```

### CODE REVIEW

**Review by andrerun — APPROVED** [review]
/lgtm

File: pkg/operation/seed/seed.go [hunk 1]
```diff
@@ -1074,8 +1068,14 @@ func runCreateSeedFlow(
...
-			Name: "Deploying Kubernetes vertical pod autoscaler",
-			Fn:   vpa.Deploy,
+			Name: "Deploying or destroying Kubernetes vertical pod autoscaler",
+			Fn: flow.TaskFn(func(ctx context.Context) error {
+				if vpaEnabled {
+					return vpa.Deploy(ctx)
+				} else {
+					return component.OpDestroyAndWait(vpa).Destroy(ctx)
+				}
+			}),
```
Comment (ialidzhikov) [inline pkg/operation/seed/seed.go]: I don't think that this will be enough. Written like this, each Seed reconciliation will destroy the vpa-exporter Deployment. To my knowledge vpa-exporter is a kind of separate seed component and should be always deployed to the Seed (having in mind the prerequisite that Seed has to have VPA installed). I can rather image that vpa-exporter is extracted to a separate component that is always deployed on Seed reconcile and never destroyed when Seed does not enable VPA.

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

**Comment by rfranzke** [comment]
Let's please not extract vpa-exporter into a separate component. Instead, we can enable/disable the three others by setting proper Values (I think this is how it was done with the Helm charts before).

**Comment by ialidzhikov** [comment]
> Let's please not extract vpa-exporter into a separate component. Instead, we can enable/disable the three others by setting proper Values (I think this is how it was done with the Helm charts before).

AFAIS it was a separate chart - https://github.com/gardener/gardener/tree/v1.44.3/charts/seed-bootstrap/templates/vpa-exporter. The problem is rather in the Destroy - on seed reconcile it should not destroy the vpa-exporter, but on deletion - it should.

**Comment by rfranzke** [comment]
Would it maybe be possible to only call Destroy on seed deletion, and call Reconcile in all other cases with proper "Enabled" settings in the values? Since VPA is now managed via GRM, it will take care of cleaning up no longer required resources.

**Comment by stoyanr** [comment]
> Let's please not extract vpa-exporter into a separate component. Instead, we can enable/disable the three others by setting proper Values (I think this is how it was done with the Helm charts before).

From my perspective it doesn't matter much how it was done before. I agree with @ialidzhikov that having vpa-exporter as a separate component would be cleaner, even though perhaps a bit more verbose. Nevertheless I will fix it as suggested above.

File: pkg/operation/seed/seed.go (hunk 1 above)
Comment (stoyanr) [reply pkg/operation/seed/seed.go]: Fixed as suggested by @rfranzke below.

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/approve
