### PR TITLE
Fix duplicated service account issuers

### LINKED ISSUE #8420: `kube-apiserver` fails to start due to duplicate `service-account-issuer`
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
The `kube-apiserver` pod fails to start if default service account issuer is configured in accepted issuers in the `Shoot` manifest
```
% k -n shoot--local--local get po -l role=apiserver
NAME                              READY   STATUS             RESTARTS      AGE
kube-apiserver-68c77898f4-klrl4   1/1     Running            0             66m
kube-apiserver-68c77898f4-qgcwj   1/1     Running            0             65m
kube-apiserver-7fdc8d9db-ww6mc    0/1     CrashLoopBackOff   5 (44s ago)   3m44s
```
```
% k -n shoot--local--local logs kube-apiserver-7fdc8d9db-ww6mc
I0904 13:31:32.553284       1 flags.go:64] FLAG: --admission-control="[]"
...
I0904 13:31:32.553835       1 flags.go:64] FLAG: --watch-cache="true"
I0904 13:31:32.553836       1 flags.go:64] FLAG: --watch-cache-sizes="[]"
E0904 13:31:32.554683       1 run.go:74] "command failed" err="service-account-issuer \"https://api.local.local.internal.local.gardener.cloud\" is already specified"
```
`Shoot` reconciliation fails:
```
% k -n garden-local get shoots local
NAME    CLOUDPROFILE   PROVIDER   REGION   K8S VERSION   HIBERNATION   LAST OPERATION               STATUS      AGE
local   local          local      local    1.27.1        Awake         Reconcile Processing (25%)   unhealthy   90m
```
and `Shoot` manifest contains the following `acceptedIssuers`: 
```
% k -n garden-local get shoots local -o yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  ...
  name: local
  namespace: garden-local
spec:
  cloudProfileName: local
  dns:
    domain: local.local.external.local.gardener.cloud
  kubernetes:
    enableStaticTokenKubeconfig: false
    kubeAPIServer:
      defaultNotReadyTolerationSeconds: 300
      ...
      requests:
        maxMutatingInflight: 200
        maxNonMutatingInflight: 400
      serviceAccountConfig:
        acceptedIssuers:
        - https://api.local.local.internal.local.gardener.cloud
    kubeControllerManager:
      nodeCIDRMaskSize: 24
      nodeMonitorGracePeriod: 40s
   ...
```

**What you expected to happen**:
It should not be possible to set default service account issuer in `acceptedIssuers`

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot in local setup and configure default service account issuer `https://api.local.local.internal.local.gardener.cloud` as accepted issuers in the shoot manifest.

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version: v1.78.1
- Kubernetes version (use `kubectl version`):
  Client Version: v1.28.1
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.27.1
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by dimitar-kostadinov**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
Adds validation for `.spec.kubernetes.kubeAPIServer.serviceAccountConfig.acceptedIssuers` field of the `Shoot` manifest.  
Duplicate values in `acceptedIssuers` are no longer allowed and `acceptedIssuers` could not contains the 
value of `issuer` field.

**Which issue(s) this PR fixes**:
Fixes #8420

**Special notes for your reviewer**:
N/A
**Release note**:

```bugfix operator
The `.spec.kubernetes.kubeAPIServer.serviceAccountConfig.acceptedIssuers` field of the `Shoot` spec no longer allows duplicate values.
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
Thanks, the change looks good. However, I'm wondering whether we should remove this from existing `Shoot`s to not break the validation, similar to https://github.com/gardener/gardener/pull/8457/files#diff-a04dba2257c8893abf53b88a89b74aad4031f17b636f5d1e975e5b1dc8daa835?

File: pkg/registry/core/shoot/strategy.go [hunk 1]
```diff
@@ -87,6 +87,8 @@ func (shootStrategy) PrepareForUpdate(_ context.Context, obj, old runtime.Object
 
 	// TODO(acumino): Drop this after v1.83 has been released.
 	removeDuplicateExtensions(newShoot)
+	// TODO(dimitar-kostadinov): Drop this after v1.83 has been released.
+	removeDuplicateServiceAccountIssuers(newShoot)
```
Comment (rfranzke) [inline pkg/registry/core/shoot/strategy.go:94]: Should this also be added to `PrepareForCreate` like `removeDuplicateExtensions`?

File: pkg/registry/core/shoot/strategy.go [hunk 2]
```diff
@@ -192,6 +194,24 @@ func removeDuplicateExtensions(shoot *core.Shoot) {
 	}
 }
 
+func removeDuplicateServiceAccountIssuers(shoot *core.Shoot) {
+	apiSrv := shoot.Spec.Kubernetes.KubeAPIServer
+	if apiSrv != nil && apiSrv.ServiceAccountConfig != nil && len(apiSrv.ServiceAccountConfig.AcceptedIssuers) > 0 {
+		issuers := make(map[string]struct{})
```
Comment (rfranzke) [inline pkg/registry/core/shoot/strategy.go]: You could use a `sets.Set` for more convenience

File: pkg/registry/core/shoot/strategy.go (hunk 1 above)
Comment (dimitar-kostadinov) [reply pkg/registry/core/shoot/strategy.go:94]: Duplicate service account publishers cause `kube-apiserver` to fail to start. In this case, it's better to avoid `Shoot` creation instead of silently fixing the faulty configuration.

Comment (rfranzke) [reply pkg/registry/core/shoot/strategy.go:94]: Pls see discussion in https://github.com/gardener/gardener/pull/8457#pullrequestreview-1621190904 and following. It's the same here. I guess it makes sense to follow the same approach.

File: pkg/apis/core/validation/shoot.go [hunk 3]
```diff
@@ -1205,6 +1205,19 @@ func ValidateKubeAPIServer(kubeAPIServer *core.KubeAPIServerConfig, version stri
 				allErrs = append(allErrs, field.Forbidden(fldPath.Child("serviceAccountConfig", "maxTokenExpiration"), "must be at most 2160h (90d)"))
 			}
 		}
+		if len(kubeAPIServer.ServiceAccountConfig.AcceptedIssuers) > 0 {
+			issuers := sets.New[string]()
+			if kubeAPIServer.ServiceAccountConfig.Issuer != nil {
+				issuers.Insert(*kubeAPIServer.ServiceAccountConfig.Issuer)
+			}
```
Comment (shafeeqes) [inline pkg/apis/core/validation/shoot.go:1212]: Should we print a different error for this case? Printing `field.Duplicate` can get confusing between this field and a different slice.

**Review by shafeeqes — COMMENTED** [review]
Only one minor nit, otherwise looks good

File: pkg/apis/core/validation/shoot.go [hunk 4]
```diff
@@ -1212,7 +1212,12 @@ func ValidateKubeAPIServer(kubeAPIServer *core.KubeAPIServerConfig, version stri
 			}
 			for i, issuer := range kubeAPIServer.ServiceAccountConfig.AcceptedIssuers {
 				if issuers.Has(issuer) {
-					allErrs = append(allErrs, field.Duplicate(fldPath.Child("serviceAccountConfig", "acceptedIssuers").Index(i), issuer))
+					path := fldPath.Child("serviceAccountConfig", "acceptedIssuers").Index(i)
+					if kubeAPIServer.ServiceAccountConfig.Issuer != nil && issuer == *kubeAPIServer.ServiceAccountConfig.Issuer {
```
Comment (shafeeqes) [inline pkg/apis/core/validation/shoot.go]:
```suggestion
					if issuer == pointer.StringDeref(kubeAPIServer.ServiceAccountConfig.Issuer) {
```

Comment (dimitar-kostadinov) [reply pkg/apis/core/validation/shoot.go]: The `pointer.StringDeref` requires default value param, so the repeating `kubeAPIServer.ServiceAccountConfig.Issuer` is fixed in another way

Comment (shafeeqes) [reply pkg/apis/core/validation/shoot.go]: Ah, yes. You could use `""`.

**Review by rfranzke — COMMENTED** [review]
/lgtm
