### PR TITLE
Prefix DNSRecord secret names to avoid collisions

### LINKED ISSUE #4895: Creation of Shoot with name "gardener" fails when UseDNSRecords=true
**How to categorize this issue?**

/area quality
/kind bug
/priority 3

**What happened**:
Cannot create a Shoot with name "gardener" when `UseDNSRecords` feature gate is enabled.
Currently there is a name collision between the Secret that gardenlet creates for the internal kubeconfig (its name is "gardener-internal") and the Secret that is created by gardenlet for the internal DNSRecord (its name is "<shoot-name>-internal"). When the Shoot name is "gardener", then both Secret names are "gardener-internal" which leads the Shoot creation to fail.

**What you expected to happen**:
To be able to create a Shoot with name "gardener".

**How to reproduce it (as minimally and precisely as possible)**:
0. Make sure that the `UseDNSRecords` feature gate of gardenlet is enabled.

1. Create a Shoot with name "gardener".

2. Make sure that the Shoot creation fails with

```yaml
  lastErrors:
    - description: >-
        task "Initializing connection to Shoot" failed: retry failed with
        context deadline exceeded, last error: error creating new ClientSet for
        key "garden-foo/gardener": the secret does not contain a field with
        name 'kubeconfig'
      taskID: Initializing connection to Shoot
```

The "gardener-internal" Secret data looks like:

```yaml
data:
  AWS_ACCESS_KEY_ID: <omitted>
  AWS_REGION: <omitted>
  AWS_SECRET_ACCESS_KEY: <omitted>
```

**Environment**:

- Gardener version: v1.34.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by voelzmo**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
When a shoot with name `gardener` is created, the secret for the internal DNSRecord was created as `gardener-internal`. This had a collision with the secret containing the information how to reach the apiserver, which is also called `gardener-internal`. This PR prefixes the dnsrecord related secrets with `dnsrecord-` and therefore avoids the name collision.

**Which issue(s) this PR fixes**:
Fixes #4895

**Special notes for your reviewer**:
There could be other ways on how to change the name. This change keeps the shoot's name and adds a dnsrecord prefix, allowing to easier understanding where these secrets come from.

**Release note**:

```bug user
Fixed a bug which didn't allow Shoots with the name 'gardener' to be created succesfully.
```

### CODE REVIEW

File: pkg/operation/botanist/dnsrecord.go [hunk 1]
```diff
@@ -27,7 +27,7 @@ import (
 func (b *Botanist) DefaultExternalDNSRecord() extensionsdnsrecord.Interface {
 	values := &extensionsdnsrecord.Values{
 		Name:       b.Shoot.GetInfo().Name + "-" + DNSExternalName,
-		SecretName: b.Shoot.GetInfo().Name + "-" + DNSExternalName,
+		SecretName: "dnsrecord-" + b.Shoot.GetInfo().Name + "-" + DNSExternalName,
```
Comment (ialidzhikov) [inline pkg/operation/botanist/dnsrecord.go]: What about the cleanup of old dnsrecord Secrets? Looks like such change will "orphan" the old dnsrecord Secrets in the Shoot control planes.

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

File: pkg/operation/botanist/dnsrecord.go (hunk 1 above)
Comment (voelzmo) [reply pkg/operation/botanist/dnsrecord.go]: That's a good point! What do you think how we should deal with the old dnsrecord secrets?

Comment (ialidzhikov) [reply pkg/operation/botanist/dnsrecord.go]: We can introduce a logic that deletes the orphaned dnsrecord Secrets.

Comment (stoyanr) [reply pkg/operation/botanist/dnsrecord.go]: How about extracting `"dnsrecord-"` to a constant?

To delete the orphaned secret, you could modify https://github.com/gardener/gardener/blob/247aeda692d432554052392d10a46b5c2ca5342e/pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go#L135 to delete the old secret (named like the new one, minus the prefix), ignoring not found errors. You could also add a comment to remove this code in a later release.

**Review by stoyanr — CHANGES_REQUESTED** [review]

File: pkg/operation/botanist/dnsrecord.go (hunk 1 above)
Comment (voelzmo) [reply pkg/operation/botanist/dnsrecord.go]: > How about extracting "dnsrecord-" to a constant?

This makes sense, will do.

> To delete the orphaned secret, you could modify https://github.com/gardener/gardener/blob/247aeda692d432554052392d10a46b5c2ca5342e/pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go#L135

This was what @ialidzhikov suggested as well. I'm not sure if I misunderstood how secrets are used by the different DNSRecords, but it seems that secrets are used by more than one DNSRecord. For example, the `external` secret is used by the `ingress` DNSRecord as well as the `external` DNSRecord. The `internal` secret is used by the `owner` DNSRecord as well as the `internal` DNSRecord. Can we really remove a secret after deploying only one of these records while the other might still be referencing the old secret? Especially seeing how far apart e.g. deploying the `ingress` record is from the `external` one during the Shoot reconciliation?

Comment (stoyanr) [reply pkg/operation/botanist/dnsrecord.go]: This is a good question. I think it should be ok, since reconciliations of `DNSRecord` resources, similarly to most other extension resources, only happen if they are annotated the `operation=reconcile`, but at the moment this annotation is added, the `secretRef` will be corrected as well. A reconciliation of `ingress` taking place at the same time or shortly after `external` is reconciled should only be possible if it has failed for whatever reason and is in a retry with backoff loop, but I also think in this case a failed reconciliation because of an invalid `secretRef` wouldn't cause any extra trouble, the resource will have to be updated anyway to make it succeed.

I would of course recommend not to take my assumptions for granted and test this, including some manually forced reconciliations of resources with invalid `secretRef` just in case.

Comment (timuthy) [reply pkg/operation/botanist/dnsrecord.go]: Speaking of the `ingress` DNSRecord @voelzmo, don't we need an adaption [here](https://github.com/gardener/gardener/blob/97e2e316891bfad3c7e381d7fea7d068f7453aa9/pkg/operation/botanist/addons.go#L141) as well?

Comment (voelzmo) [reply pkg/operation/botanist/dnsrecord.go]: > Speaking of the ingress DNSRecord @voelzmo, don't we need an adaption here as well?

Yeah, sorry, all of this is already on my branch – I thought I had pushed this already. I'll add it for the sake of discussion, although Stoyan already suggested a different approach, just for the sake of discussion.

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go [hunk 2]
```diff
@@ -275,3 +276,7 @@ func (c *dnsRecord) SetRecordType(recordType extensionsv1alpha1.DNSRecordType) {
 func (c *dnsRecord) SetValues(values []string) {
 	c.values.Values = values
 }
+
+func (c *dnsRecord) GetSecret() *corev1.Secret {
+	return c.secret
+}
```
Comment (stoyanr) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: I believe the implementation of this method is wrong for its intended purpose. It will be used later to check if the name of the secret that **exists** contains `dnrecord-`. However, as currently implemented, it will return the name of the secret that has been initialized (but not necessarily already updated), and so it will return a `dnsrecord-` prefixed name also before the actual secret has been updated.

File: pkg/operation/botanist/dnsrecord.go [hunk 3]
```diff
@@ -206,3 +211,38 @@ func (b *Botanist) deployOrRestoreDNSRecord(ctx context.Context, dnsRecord compo
 	}
 	return dnsRecord.Deploy(ctx)
 }
+
+// CleanupOrphanedDNSRecordSecrets cleans up secrets related to DNSRecords which may be orphaned after introducing the 'dnsrecord-' prefix
+func (b *Botanist) CleanupOrphanedDNSRecordSecrets(ctx context.Context) error {
```
Comment (stoyanr) [inline pkg/operation/botanist/dnsrecord.go:216]: I don't see this method used anywhere? Did you intend to use it in the flow?

File: pkg/operation/botanist/dnsrecord.go [hunk 4]
```diff
@@ -206,3 +211,38 @@ func (b *Botanist) deployOrRestoreDNSRecord(ctx context.Context, dnsRecord compo
...
+	internalDNSRecordSecretName := b.Shoot.Components.Extensions.InternalDNSRecord.GetSecret().Name
+	ownerDNSRecordSecretName := b.Shoot.Components.Extensions.OwnerDNSRecord.GetSecret().Name
```
Comment (stoyanr) [inline pkg/operation/botanist/dnsrecord.go]: As mentioned above, getting the secret names in this way doesn't guarantee the so named secrets are actually already deployed. I believe this logic and the ifs below could simply be skipped in favor of indiscriminately deleting all secrets with old names (if they exist) which would be safe if executed at the right point in the flow, that is after all DNSRecords have been updated, e.g.:

```go
b.cleanupOrphanedDNSRecordSecret(ctx, b.Shoot.GetInfo().Name + "-" + DNSExternalName)
b.cleanupOrphanedDNSRecordSecret(ctx, b.Shoot.GetInfo().Name + "-" + DNSInternalName)
```

(with proper error handling of course)

File: pkg/operation/botanist/dnsrecord.go [hunk 5]
```diff
@@ -206,3 +211,38 @@ func (b *Botanist) deployOrRestoreDNSRecord(ctx context.Context, dnsRecord compo
...
+}
+
+func (b *Botanist) cleanupOrphanedDNSRecordSecret(ctx context.Context, secretName string) error {
+	err := b.K8sSeedClient.Client().Delete(ctx, &corev1.Secret{ObjectMeta: metav1.ObjectMeta{Name: secretName, Namespace: b.Shoot.SeedNamespace}})
+	if err != nil {
+		if !errors.IsNotFound(err) {
+			return err
+		}
+	}
+	return nil
```
Comment (stoyanr) [inline pkg/operation/botanist/dnsrecord.go]:
```suggestion
	return client.IgnoreNotFound(b.K8sSeedClient.Client().Delete(ctx, &corev1.Secret{ObjectMeta: metav1.ObjectMeta{Name: secretName, Namespace: b.Shoot.SeedNamespace}}))
```
And since there is not much left of this method I would also remove the method itself and use the above one-liner directly.

**Review by stoyanr — CHANGES_REQUESTED** [review]
Besides the other remarks, I still don't see the prefix `dnsrecord-` extracted as a constant, as previously suggested.

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go (hunk 2 above)
Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: Ah, thanks, that makes sense!

File: pkg/operation/botanist/dnsrecord.go (hunk 3 above)
Comment (voelzmo) [reply pkg/operation/botanist/dnsrecord.go:216]: Indeed, this change was incomplete when I pushed it. I just wanted to put my current state of work out there for the discussion on how to implement this.

File: pkg/operation/botanist/dnsrecord.go (hunk 4 above)
Comment (voelzmo) [reply pkg/operation/botanist/dnsrecord.go]: Thanks, done.

File: pkg/operation/botanist/dnsrecord.go (hunk 5 above)
Comment (voelzmo) [reply pkg/operation/botanist/dnsrecord.go]: done.

File: pkg/operation/botanist/dnsrecord.go [hunk 6]
```diff
@@ -206,3 +210,16 @@ func (b *Botanist) deployOrRestoreDNSRecord(ctx context.Context, dnsRecord compo
 	}
 	return dnsRecord.Deploy(ctx)
 }
+
+// CleanupOrphanedDNSRecordSecrets cleans up secrets related to DNSRecords which may be orphaned after introducing the 'dnsrecord-' prefix
+func (b *Botanist) CleanupOrphanedDNSRecordSecrets(ctx context.Context) error {
+	err := client.IgnoreNotFound(b.K8sSeedClient.Client().Delete(ctx, &corev1.Secret{ObjectMeta: metav1.ObjectMeta{Name: b.Shoot.GetInfo().Name + "-" + DNSInternalName, Namespace: b.Shoot.SeedNamespace}}))
+	if err != nil {
+		return err
+	}
```
Comment (stoyanr) [inline pkg/operation/botanist/dnsrecord.go]: Nit: Slightly more idiomatic / popular in our codebase:
```suggestion
	if err := b.K8sSeedClient.Client().Delete(ctx, &corev1.Secret{ObjectMeta: metav1.ObjectMeta{Name: b.Shoot.GetInfo().Name + "-" + DNSInternalName, Namespace: b.Shoot.SeedNamespace}}); client.IgnoreNotFound(err) != nil {
		return err
	}
```

File: pkg/gardenlet/controller/shoot/shoot_control_reconcile.go [hunk 7]
```diff
@@ -421,6 +421,11 @@ func (r *shootReconciler) runReconcileShootFlow(ctx context.Context, o *operatio
 			Fn:           flow.TaskFn(botanist.DeployIngressDNSResources).DoIf(!o.Shoot.HibernationEnabled),
 			Dependencies: flow.NewTaskIDs(nginxLBReady),
 		})
+		_ = g.Add(flow.Task{
+			Name:         "Cleaning up orphaned DNSRecord secrets",
+			Fn:           flow.TaskFn(botanist.CleanupOrphanedDNSRecordSecrets),
+			Dependencies: flow.NewTaskIDs(deployInternalDomainDNSRecord, deployExternalDomainDNSRecord, deployOwnerDomainDNSRecord, deployIngressDomainDNSRecord)})
+
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_reconcile.go]: Let's align the formatting:
```suggestion
			Dependencies: flow.NewTaskIDs(deployInternalDomainDNSRecord, deployExternalDomainDNSRecord, deployOwnerDomainDNSRecord, deployIngressDomainDNSRecord)
		})
```

**Review by stoyanr — DISMISSED** [review]
Looks quite good, just 2 small comments. I would also like to test this change a bit and will report the results.

File: pkg/operation/botanist/dnsrecord.go (hunk 6 above)
Comment (voelzmo) [reply pkg/operation/botanist/dnsrecord.go]: done, thanks!

File: pkg/gardenlet/controller/shoot/shoot_control_reconcile.go [hunk 8]
```diff
@@ -421,6 +421,11 @@ func (r *shootReconciler) runReconcileShootFlow(ctx context.Context, o *operatio
 			Fn:           flow.TaskFn(botanist.DeployIngressDNSResources).DoIf(!o.Shoot.HibernationEnabled),
 			Dependencies: flow.NewTaskIDs(nginxLBReady),
 		})
+		_ = g.Add(flow.Task{
+			Name:         "Cleaning up orphaned DNSRecord secrets",
+			Fn:           flow.TaskFn(botanist.CleanupOrphanedDNSRecordSecrets),
```
Comment (stoyanr) [inline pkg/gardenlet/controller/shoot/shoot_control_reconcile.go]: I think this should only be executed if the cluster is not hibernated, since deploying some of the DNS records is also constrained by the same condition.
```suggestion
			Fn:           flow.TaskFn(botanist.CleanupOrphanedDNSRecordSecrets).DoIf(!o.Shoot.HibernationEnabled),
```

**Review by stoyanr — COMMENTED** [review]
I tested this and it seems to work well, I have one additional suggestion.

**Comment by voelzmo** [comment]
Now that I'm thinking about this more: Do we need additional safeguarding for the case where the Shoot is called `gardener`? Given the origin of this fix, there would always exist the secret `gardener-internal` and we would delete it. So I'll add some condition to CleanupOrphanedDNSRecordSecret to do nothing for Shoots with name `gardener`, WDYT?

**Comment by stoyanr** [comment]
> Now that I'm thinking about this more: Do we need additional safeguarding for the case where the Shoot is called gardener? Given the origin of this fix, there would always exist the secret gardener-internal and we would delete it. So I'll add some condition to CleanupOrphanedDNSRecordSecret to do nothing for Shoots with name gardener, WDYT?

This is a good point, but I don't like the direction in which this is going. If we do this, we should then figure out what other secrets we could be deleting that should not be deleted, and check for them as well. I think this is a bit too much.

Besides, there is another, much more serious issue. During my testing with `UseDNSRecords` enabled everything worked ok while I was creating / deleting new shoots or reconciling an existing shoot (created with an older version). But deleting this last shoot after it has been reconciled with the version from this PR fails with:

```
Failed to delete DNSRecord shoot--dev--i500152-gcp/i500152-gcp-owner: Error deleting dnsrecord: could not get AWS credentials: Secret "i500152-gcp-internal" not found'
```

The reason is that owner DNS records are (by design) only reconciled when they are created (and deleted). So, reconciling the shoot with the version from the PR doesn't update this DNS record, but it deletes its secret. This doesn't cause any issues until the shoot is finally deleted, but then it fails.

Having all this in mind, I would actually recommend **not to delete the orphaned secret**s, it seems it causes much more issues than it solves. I am really sorry for this back and forth.

**Comment by ialidzhikov** [comment]
Nice finding about the owner DNSRecord, @stoyanr .

> The reason is that owner DNS records are (by design) only reconciled when they are created (and deleted).

Out of context of this PR, how we would handle cases where we have to update the owner DNSRecord spec (for example if we want to change its ttls or add/remove a field)? It seems like it is a question of time to hit similar issue with the owner DNSOwner and its "create/delete only" behaviour.

> So, reconciling the shoot with the version from the PR doesn't update this DNS record, but it deletes its secret. This doesn't cause any issues until the shoot is finally deleted, but then it fails.

This sounds like yet another issue (or point for improvement). If this is the case, then it means that the dnsrecord controller removes the finalizer from the DNSRecord secret without considering whether it is the last DNSRecord that references this Secret. IIUC, currently both the owner and internal DNSRecord point to the `<shoot-name>-internal` Secret. I would expect the finalizer of the `<shoot-name>-internal` Secret to be removed only when the last DNSRecord is deleted.

> Having all this in mind, I would actually recommend **not to delete the orphaned secret**s, it seems it causes much more issues than it solves.

I think it is still important to clean up the orphaned Secrets. There are components that list/watch the controlplane Secrets and 2 no longer used Secrets per control plane will only increase the network traffic costs (and the memory usage of components that use watches).

To workaround this issue that you reported, would it be possible to trigger a reconciliation for the owner DNSRecord once for the Secret name update?

**Comment by stoyanr** [comment]
@ialidzhikov I am skipping questions that are "out of context of this PR", let's discuss them separately.

> then it means that the dnsrecord controller removes the finalizer from the DNSRecord secret without considering whether it is the last DNSRecord that references this Secret

There is currently simply no such finalizer, it was never implemented like this. The secret referenced by the `DNSRecord` is similar to the `cloudprovider` secret referenced by other extension resources (except that it may contain different credentials), and the corresponding extension controllers also don't add finalizers to this secret (nor to any other secret as far as I can tell). I am not sure whether adding such a finalizer is good idea in general (and if yes, should it be added only to this secret and not to others). However, I really don't think it should be added just in order to address the issue we are having here.

> There are components that list/watch the controlplane Secrets and 2 no longer used Secrets per control plane will only increase the network traffic costs (and the memory usage of components that use watches).

There are currently ~90 secrets in a fully reconciled test shoot (more on shoots with more workers, etc.). I believe the added impact of 2 more secrets is therefore negligible. 

> To workaround this issue that you reported, would it be possible to trigger a reconciliation for the owner DNSRecord once for the Secret name update?

Yes, this could be possible perhaps but I really don't like the added complexity for something I consider a really small issue. Besides, as I replied to some of the suggestions to @voelzmo above, I really don't like the general direction in which this is going - adding even more complexity in order to "safeguard" we are not deleting secrets we shouldn't be deleting.

Long story short, please let's drop this secrets cleanup and save ourselves the added complexity and effort.

File: pkg/gardenlet/controller/shoot/shoot_control_reconcile.go (hunk 8 above)
Comment (voelzmo) [reply pkg/gardenlet/controller/shoot/shoot_control_reconcile.go]: done.

File: pkg/operation/botanist/dnsrecord_test.go [hunk 9]
```diff
@@ -457,4 +460,86 @@ var _ = Describe("dnsrecord", func() {
 			Expect(b.MigrateInternalDNSRecord(ctx)).To(MatchError(testErr))
 		})
 	})
+
+	// TODO (voelzmo) remove this when all DNSRecord secrets have migrated to a prefixed version
+	Describe("#CleanupOrphanedDNSRecordSecrets", func() {
+		var orphanedInternalSecret *corev1.Secret
+		var regularInternalSecret *corev1.Secret
+		var orphanedExternalSecret *corev1.Secret
+		var regularExternalSecret *corev1.Secret
```
Comment (ialidzhikov) [inline pkg/operation/botanist/dnsrecord_test.go]:
```suggestion
		var (
			orphanedInternalSecret *corev1.Secret
			regularInternalSecret  *corev1.Secret
			orphanedExternalSecret *corev1.Secret
			regularExternalSecret  *corev1.Secret
		)
```

File: pkg/operation/botanist/dnsrecord_test.go [hunk 10]
```diff
@@ -457,4 +460,86 @@ var _ = Describe("dnsrecord", func() {
...
+
+			// create a regular internal secret which is prefixed with 'dnsrecord-'
+			regularInternalSecret = &corev1.Secret{ObjectMeta: metav1.ObjectMeta{
+				Name:      DNSRecordSecretPrefix + "-" + shootName + "-" + DNSInternalName,
+				Namespace: seedNamespace,
+			}}
+			err = c.Create(ctx, regularInternalSecret)
+			Expect(err).ToNot(HaveOccurred())
+
+			// create an internal secret which is not prefixed with 'dnsrecord-' and is of the form '<shootName>-internal'
```
Comment (ialidzhikov) [inline pkg/operation/botanist/dnsrecord_test.go]:
```suggestion
			// create an external secret which is not prefixed with 'dnsrecord-' and is of the form '<shootName>-external'
```

File: pkg/operation/botanist/dnsrecord_test.go [hunk 11]
```diff
@@ -457,4 +460,86 @@ var _ = Describe("dnsrecord", func() {
...
+			orphanedExternalSecret = &corev1.Secret{ObjectMeta: metav1.ObjectMeta{
+				Name:      shootName + "-" + DNSExternalName,
+				Namespace: seedNamespace,
+			}}
+			err = c.Create(ctx, orphanedExternalSecret)
+			Expect(err).ToNot(HaveOccurred())
+
+			// create a regular internal secret which is prefixed with 'dnsrecord-'
```
Comment (ialidzhikov) [inline pkg/operation/botanist/dnsrecord_test.go]:
```suggestion
			// create a regular external secret which is prefixed with 'dnsrecord-'
```

File: pkg/operation/botanist/dnsrecord_test.go [hunk 12]
```diff
@@ -457,4 +460,86 @@ var _ = Describe("dnsrecord", func() {
...
+		})
+
+		Context("When the Shoot name is 'gardener'", func() {
+			BeforeEach(func() {
+				shootName = "gardener"
+				seedNamespace = "shoot--gardener--bar"
+			})
+
+			It("should clean up the external orphaned secret, but keep the internal orphaned secret", func() {
+
```
Comment (ialidzhikov) [inline pkg/operation/botanist/dnsrecord_test.go]:
```suggestion
```

File: pkg/operation/botanist/dnsrecord_test.go [hunk 13]
```diff
@@ -457,4 +460,86 @@ var _ = Describe("dnsrecord", func() {
...
+				Expect(b.CleanupOrphanedDNSRecordSecrets(ctx)).To(Succeed())
+				Expect(c.Get(ctx, client.ObjectKey{Name: orphanedExternalSecret.Name, Namespace: seedNamespace}, &corev1.Secret{})).To(BeNotFoundError())
+
+				internalSecret := &corev1.Secret{}
+				Expect(c.Get(ctx, client.ObjectKey{Name: orphanedInternalSecret.Name, Namespace: seedNamespace}, internalSecret)).To(Succeed())
+				Expect(internalSecret).To(DeepDerivativeEqual(orphanedInternalSecret))
+
```
Comment (ialidzhikov) [inline pkg/operation/botanist/dnsrecord_test.go]:
```suggestion
```

File: pkg/operation/botanist/dnsrecord_test.go [hunk 14]
```diff
@@ -457,4 +460,86 @@ var _ = Describe("dnsrecord", func() {
...
+			})
+		})
+
+		It("should not fail the clean up of orphaned Secret when there are none", func() {
+			Expect(b.CleanupOrphanedDNSRecordSecrets(ctx)).To(Succeed())
+			Expect(c.Get(ctx, client.ObjectKey{Name: orphanedExternalSecret.Name, Namespace: seedNamespace}, &corev1.Secret{})).To(BeNotFoundError())
+			Expect(b.CleanupOrphanedDNSRecordSecrets(ctx)).To(Succeed())
+
```
Comment (ialidzhikov) [inline pkg/operation/botanist/dnsrecord_test.go]:
```suggestion
```

File: pkg/operation/botanist/dnsrecord.go [hunk 15]
```diff
@@ -206,3 +211,21 @@ func (b *Botanist) deployOrRestoreDNSRecord(ctx context.Context, dnsRecord compo
 	}
 	return dnsRecord.Deploy(ctx)
 }
+
+// CleanupOrphanedDNSRecordSecrets cleans up secrets related to DNSRecords which may be orphaned after introducing the 'dnsrecord-' prefix
+func (b *Botanist) CleanupOrphanedDNSRecordSecrets(ctx context.Context) error {
+	// TODO (voelzmo) remove this when all DNSRecord secrets have migrated to a prefixed version
```
Comment (ialidzhikov) [inline pkg/operation/botanist/dnsrecord.go]:
```suggestion
	// TODO (voelzmo): remove this when all DNSRecord secrets have migrated to a prefixed version
```

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go [hunk 16]
```diff
@@ -180,6 +182,11 @@ func (c *dnsRecord) deploy(ctx context.Context, operation string) (extensionsv1a
 				// If the DNSRecord is not yet Succeeded, reconcile it again.
 				_ = mutateFn()
 			} else {
+				// TODO (voelzmo) remove this when all DNSRecord secrets have migrated to a prefixed version
+				// Check if we need to migrate the referenced secret
+				if !strings.HasPrefix(c.dnsRecord.Spec.SecretRef.Name, "dnsrecord-") {
+					c.dnsRecord.Spec.SecretRef.Name = fmt.Sprintf("dnsrecord-%s", c.dnsRecord.Spec.SecretRef.Name)
+				}
```
Comment (ialidzhikov) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: I tested locally the migration but it didn't work:

```
{"error":"observed generation outdated (1/2)","level":"error","msg":"DNSRecord shoot--foo--bar/bar-owner did not get ready yet","operation":"reconcile","shoot":"garden-foo/bar","time":"2021-11-23T10:47:26+02:00"}
```

I think you have to also add the `gardener.cloud/operation=reconcile` annotation to the dnsrecord in this case to trigger its reconciliation.

Can you check whether something like will do the trick?

```suggestion
				if !strings.HasPrefix(c.dnsRecord.Spec.SecretRef.Name, "dnsrecord-") {
					c.dnsRecord.Spec.SecretRef.Name = fmt.Sprintf("dnsrecord-%s", c.dnsRecord.Spec.SecretRef.Name)

					metav1.SetMetaDataAnnotation(&c.dnsRecord.ObjectMeta, v1beta1constants.GardenerOperation, operation)
				}
```

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go [hunk 17]
```diff
@@ -180,6 +182,11 @@ func (c *dnsRecord) deploy(ctx context.Context, operation string) (extensionsv1a
 				// If the DNSRecord is not yet Succeeded, reconcile it again.
 				_ = mutateFn()
 			} else {
+				// TODO (voelzmo) remove this when all DNSRecord secrets have migrated to a prefixed version
```
Comment (ialidzhikov) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]:
```suggestion
				// TODO (voelzmo): remove this when all DNSRecord secrets have migrated to a prefixed version
```

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go (hunk 16 above)
Comment (stoyanr) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: I would propose something slightly different:
```suggestion
				if c.dnsRecord.Spec.SecretRef.Name != c.secret.Name {
					metav1.SetMetaDataAnnotation(&c.dnsRecord.ObjectMeta, v1beta1constants.GardenerOperation, operation)
					c.dnsRecord.Spec.SecretRef.Name = c.secret.Name
				}
```
In essence, if the secret name is not what it should be, set it to the right one. We don't need to check prefixes etc. here. Or simply (but then make sure this is in `else if` on its own):
```suggestion
				if c.dnsRecord.Spec.SecretRef.Name != c.secret.Name {
					_ = mutateFn()
				}
```

I would even go a bit further and propose something like (again in its own `else if`):
```suggestion
				if !c.dnsRecordMachesValues() {
					_ = mutateFn()
				}
```
Above, `c.dnsRecordMachesValues()` should check not only the secret name but everything else that might be different in `c.dnsRecord` compared to the desired state in `c.values` and `c.secret` and that `mutateFn` would correct. This would prevent similar changes in the future (to the secret name or anything) to go "unnoticed". Such changes should be very rare, and so I judge the possibility for them to affect the CPM bad case as very low.

**Review by stoyanr — CHANGES_REQUESTED** [review]

**Comment by voelzmo** [comment]
Hey @stoyanr thanks for the additional comments! Can you help me understand what the purpose of `ReconcileOnce` is when we now decide to reconcile all the values? Is there anything that we're trying to avoid compared to just reconciling on every run?

I guess I didn't really understand the implications of doing this all the time and therefore chose the more conservative approach of only updating what we really want to have changed here: the `secretRef`. If it makes sense, I'm happy to switch it to just applying the `mutateFn`.

**Comment by stoyanr** [comment]
> what the purpose of `ReconcileOnce` is when we now decide to reconcile all the values

Basically with `ReconcileOnce`, so far we avoided reconciling the owner DNSRecord except when it was initially created. This is "bulletproof" from CPM "bad case" perspective but also inherently problematic, exactly because of the case you encountered in this PR - its "desired state" may change (the secret name in this case), and the change will go unnoticed.

What I am proposing is to change this behavior to reconcile upon initial creation, and also every time the desired state also changed. Note that the desired state changing is actually a very rare event - we will not be frequently introducing changes that e.g. rename secrets, change seed identities, DNS domains, or TTL values (and some of these changes are impossible because the corresponding fields are immutable). However, when we **do** introduce them, like in this case, we would most of the time want the change to be propagated to the owner `DNSRecord` resource, as we do now.

This is still very different from what happens with other extension resources - they are mostly reconciled **every time** the shoot is reconciled, independently if anything in their desired state changed or not. This makes sense in general, but is definitely not something we want to do with the owner `DNSRecord`, as it would break the CPM "bad case" concept.

We may want to rename `ReconcileOnce` to something else, e.g. `ReconcileOnChange`, to reflect this change.

@timebertt As you initially reviewed and commented on this, do you see issues with the change I am proposing?

One potential issue is of course that a rare change to the desired state may coincide with a shoot being in the CPM "bad case" scenario (not cooperating so it's being forcefully moved to a different seed, also a rare situation), where we don't want it to touch the owner DNS record. I consider the odds of such an event however rather miniscule. So what I am proposing is less "bulletproof", but still pragmatically better because it could save us some future hassles.

**Comment by stoyanr** [comment]
> what the purpose of ReconcileOnce is when we now decide to reconcile all the values

A side comment: from what you commented above it seems that you confuse "reconcile" with "update". We don't "reconcile" the values - we update the resource with its desired state and add the `reconcile` annotation so that its respective controller will eventually reconcile it (bring the world in sync with this desired state). We may end up not updating anything (the desired state hasn't changed), yet the `reconcile` annotation would still cause the controller to reconcile, and update any external state that deviated from the desired state because of "entropy" (manual changes, etc.).

From my perspective your confusion is understandable, as the term "reconcile" is used in our codebase to mean both "reconcile an object desired state with the actual state of the world" and "act upon objects (create, update, delete them) as part of a reconciliation". I myself find this naming deeply confusing and questionable.

/cc @timebertt @timuthy

**Comment by stoyanr** [comment]
> If it makes sense, I'm happy to switch it to just applying the mutateFn.

From my perspective, unless there are serious objections, I would definitely prefer to see my last suggestion implemented instead of my first one, for the reasons I explained above.

**Comment by timebertt** [comment]
> @timebertt As you initially reviewed and commented on this, do you see issues with the change I am proposing?

Nope, I don't see any problems with it.

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go (hunk 16 above)
Comment (ialidzhikov) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: @stoyanr , I see the point in your proposal. Adapting the owner DNSRecord from `ReconcileOnce` to `ReconcileOnChange` would definitely help with dealing with such spec changes in the future.
I was rather wondering whether this requested change must be a blocker for this PR or is the current state "good enough" to deal with the issue and the requested change can be done as improvement in separate PR?
I am fine with the current state of the PR and with the hardcoded check for the secret prefix or for secret name (as you  suggested). WDYT, can the suggested improvement be implemented in separate PR or do you insist to happen in this PR?

**Comment by voelzmo** [comment]
Hey @stoyanr and @timebertt, thanks for your perspective here! 

I'm still kind of hesitant to make the change and converge all values in the OwnerDNSRecord to a new desired state. It seems to draw away from the focus of this PR for a purpose that may or may not arise in the future. At the same time, this piece of code is meant to be temporary: It's only there until all existing secrets have been migrated to the prefix and the old ones have been cleaned up. After a few releases with this code, we can remove these parts again and go back to the `ReconcileOnce` behavior how it was initially designed. 

Does this make sense?

**Comment by stoyanr** [comment]
@voelzmo As discussed, let's fix the code as it should have been written in the first place, instead of introducing a temporary fix.

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go [hunk 18]
```diff
@@ -275,3 +279,13 @@ func (c *dnsRecord) SetRecordType(recordType extensionsv1alpha1.DNSRecordType) {
...
 }
+
+func (c *dnsRecord) ValuesHaveChanged() bool {
+	return c.values.DNSName != c.dnsRecord.Spec.Name ||
+		!pointer.StringEqual(c.values.Zone, c.dnsRecord.Spec.Zone) ||
+		c.values.RecordType != c.dnsRecord.Spec.RecordType ||
+		!pointer.Int64Equal(c.values.TTL, c.dnsRecord.Spec.TTL) ||
+		!reflect.DeepEqual(c.values.Values, c.dnsRecord.Spec.Values) ||
+		c.secret.Name != c.dnsRecord.Spec.SecretRef.Name ||
+		c.values.Type != c.dnsRecord.Spec.Type
```
Comment (stoyanr) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: * I am a bit torn if we should really check for changes to all these fields, or only for the ones that are not treated immutable by the `DNSRecord` validation (`Spec.Type`, `Spec.Name`, and `Spec.RecordType` are treated as immutable). If `gardenlet` attempts to change an immutable field, this will be denied by the seed admission controller (and it's considered a bug in `gardenlet`). If we ever find ourselves in a situation where this should be allowed, we would anyway need to do a code change. So I would prefer not to check for changes to immutable fields, it's more consistent with the rest of the code.
* Nit: Could these checks follow some existing ordering, e.g. of the fields in `Values`? Currently it looks pretty randomly ordered.
* I really like `pointer.StringEqual`, we should use this more.

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go [hunk 19]
```diff
@@ -275,3 +279,13 @@ func (c *dnsRecord) SetRecordType(recordType extensionsv1alpha1.DNSRecordType) {
...
 	c.values.Values = values
 }
+
+func (c *dnsRecord) ValuesHaveChanged() bool {
+	return c.values.DNSName != c.dnsRecord.Spec.Name ||
+		!pointer.StringEqual(c.values.Zone, c.dnsRecord.Spec.Zone) ||
+		c.values.RecordType != c.dnsRecord.Spec.RecordType ||
+		!pointer.Int64Equal(c.values.TTL, c.dnsRecord.Spec.TTL) ||
+		!reflect.DeepEqual(c.values.Values, c.dnsRecord.Spec.Values) ||
+		c.secret.Name != c.dnsRecord.Spec.SecretRef.Name ||
```
Comment (stoyanr) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: This is equivalent, but perhaps slightly better since it's more consistent with the other checks.
```suggestion
		c.values.SecretName != c.dnsRecord.Spec.SecretRef.Name ||
```

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go [hunk 20]
```diff
@@ -62,10 +64,10 @@ type Values struct {
...
 	// SecretName is the name of the secret referenced by the DNSRecord resource.
 	SecretName string
-	// ReconcileOnce specifies that the DNSRecord resource should only be created and never reconciled after that again.
-	// However, on Deploy it is still updated with the timestamp annotation.
-	// This mode is used for owner DNS records.
-	ReconcileOnce bool
+	// ReconcileOnValueChangeOnly specifies that the DNSRecord resource should only be created and only reconciled when Values are changed.
+	// If Values didn't change, it is still updated with the timestamp annotation on Deploy.
+	// This mode is used for owner DNS records to avoid competing reconciliations during controlplane migrations.
+	ReconcileOnValueChangeOnly bool
```
Comment (stoyanr) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: I would really prefer a shorter name such as `ReconcileOnChange` (open to suggestions but ideally no longer than 3 words). Also, the current name is inaccurate - we want to reconcile when the desired state has changed compared to the current one. The `Values` struct is an implementation detail and it's always newly created (so it can't really "change").
```suggestion
	// ReconcileOnChange specifies that the DNSRecord resource should only be reconciled when first created or if its desired state has changed compared to the current one.
	// This mode is used for owner DNS records to avoid competing reconciliations during the control plane migration "bad case" scenario.
	ReconcileOnChange bool
```

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go [hunk 21]
```diff
@@ -275,3 +279,13 @@ func (c *dnsRecord) SetRecordType(recordType extensionsv1alpha1.DNSRecordType) {
 func (c *dnsRecord) SetValues(values []string) {
 	c.values.Values = values
 }
+
+func (c *dnsRecord) ValuesHaveChanged() bool {
```
Comment (stoyanr) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: This method should not be exported and the name could better reflect what it does.
```suggestion
func (c *dnsRecord) valuesDontMatchDNSRecord() bool {
```

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go [hunk 22]
```diff
@@ -219,105 +223,459 @@ var _ = Describe("DNSRecord", func() {
...
+							Name:       dnsName,
+							RecordType: extensionsv1alpha1.DNSRecordTypeA,
+							Values:     []string{address},
+							TTL:        pointer.Int64(ttl),
+						},
+					}))
+				})
+			})
+			Context("when dnsrecord values change", func() {
+				It("should reconcile when DNSName changes", func() {
```
Comment (stoyanr) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go]: This context contains a lot of different test cases for the different `Values` fields that may have changed. While it's extensive, most of the code is heavily duplicated. Could we perhaps eliminate this duplication by either capturing some of it in variables or functions, using `DescribeTable`, or both?

**Review by stoyanr — CHANGES_REQUESTED** [review]

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go (hunk 18 above)
Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: done.

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go (hunk 22 above)
Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go]: done.

**Comment by ialidzhikov** [comment]
Apart from the @stoyanr, generally looks good to me. I tested the "migration" to the new secret names locally and it worked well.

PS. I would also appreciate if you can also rebase to latest master. While testing this PR, I hit an issue with the Shoot deletion that is already fixed in the master branch with https://github.com/gardener/gardener/pull/5062.

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go (hunk 19 above)
Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: done.

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go (hunk 21 above)
Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: done.

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go (hunk 20 above)
Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: done.

**Comment by voelzmo** [comment]
Thanks for all the comments! Just rebased on current `master` and pushed the remaining changes – this is ready for the next round from my point of view.

**Review by ialidzhikov — DISMISSED** [review]
/lgtm
/squash

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go [hunk 23]
```diff
@@ -219,105 +221,108 @@ var _ = Describe("DNSRecord", func() {
...
+
+				deployedDNS := &extensionsv1alpha1.DNSRecord{}
+				err := c.Get(ctx, client.ObjectKey{Name: name, Namespace: namespace}, deployedDNS)
+				Expect(err).NotTo(HaveOccurred())
+				Expect(deployedDNS).To(DeepEqual(expectedDNSRecord))
+			},
+				table.Entry("secretName changes", func() { values.SecretName = "new-secret-name" }, func() { expectedDNSRecord.Spec.SecretRef.Name = "new-secret-name" }),
+				table.Entry("zone changes", func() { values.Zone = pointer.String("new-zone") }, func() { expectedDNSRecord.Spec.Zone = pointer.String("new-zone") }),
+				table.Entry("DNSName changes", func() { values.DNSName = "new-dnsname" }, func() { expectedDNSRecord.Spec.Name = "new-dnsname" }),
+				table.Entry("DNSNameRecord values change", func() { values.Values = []string{"8.8.8.8"} }, func() { expectedDNSRecord.Spec.Values = []string{"8.8.8.8"} }),
```
Comment (stoyanr) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go]:
```suggestion
				table.Entry("values changes", func() { values.Values = []string{"8.8.8.8"} }, func() { expectedDNSRecord.Spec.Values = []string{"8.8.8.8"} }),
```

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go [hunk 24]
```diff
@@ -275,3 +278,11 @@ func (c *dnsRecord) SetRecordType(recordType extensionsv1alpha1.DNSRecordType) {
 func (c *dnsRecord) SetValues(values []string) {
 	c.values.Values = values
 }
+
+func (c *dnsRecord) valuesDontMatchDNSRecord() bool {
+	return c.values.SecretName != c.dnsRecord.Spec.SecretRef.Name ||
+		!pointer.StringEqual(c.values.Zone, c.dnsRecord.Spec.Zone) ||
+		c.values.DNSName != c.dnsRecord.Spec.Name ||
```
Comment (stoyanr) [inline pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: `Spec.Name` is also immutable.
```suggestion
```

**Review by stoyanr — COMMENTED** [review]
Thanks for addressing my suggestions! Looks very good, just 2 minor things you may want to fix (although it could also be merged as it is).

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go (hunk 24 above)
Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord.go]: Ah, totally missed this. Thanks for being thorough!

File: pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go (hunk 23 above)
Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/dnsrecord/dnsrecord_test.go]: done

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/squash

**Review by stoyanr — APPROVED** [review]
/lgtm
