### PR TITLE
Deflake `Seed` controller integration test

### LINKED ISSUE #6933: [Flaky Test] Seed Controller Integration Test Suite
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
Seed controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:38
  when seed namespace exists
  /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:95
    when internal domain secret exists
    /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:129
      when global monitoring secret exists
      /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:166
        [It] should properly maintain the Bootstrapped condition
        /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:190
```

**CI link**:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6873/pull-gardener-integration/1586620335078248448

**Reason for failure**:
```
Timed out after 5.003s.
  Expected
      <[]v1beta1.Condition | len:1, cap:1>: [
          {
              Type: "Bootstrapped",
              Status: "False",
              LastTransitionTime: {
                  Time: 2022-10-30T07:27:58Z,
              },
              LastUpdateTime: {
                  Time: 2022-10-30T07:27:58Z,
              },
              Reason: "GardenSecretsError",
              Message: "need an internal domain secret but found none",
              Codes: nil,
          },
      ]
  to contain element matching
      <*matchers.AndMatcher | 0xc004a11d10>: {
          Matchers: [
              <*gstruct.FieldsMatcher | 0xc004a11c80>{
                  Fields: {
                      "Type": <*matchers.EqualMatcher | 0xc002e01510>{
                          Expected: <v1beta1.ConditionType>"Bootstrapped",
                      },
                  },
                  IgnoreExtras: true,
                  IgnoreMissing: false,
                  failures: nil,
              },
              <*gstruct.FieldsMatcher | 0xc004a11ce0>{
                  Fields: {
                      "Status": <*matchers.EqualMatcher | 0xc002e01530>{
                          Expected: <v1beta1.ConditionStatus>"Progressing",
                      },
                  },
                  IgnoreExtras: true,
                  IgnoreMissing: false,
                  failures: [
                      <*errors.NestedError | 0xc0025a3440>{
                          Path: ".Status",
                          Err: <*errors.errorString | 0xc003[166](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6873/pull-gardener-integration/1586620335078248448#1:build-log.txt%3A166)770>{
                              s: "Expected\n    <v1beta1.ConditionStatus>: False\nto equal\n    <v1beta1.ConditionStatus>: Progressing",
                          },
                      },
                  ],
              },
          ],
          firstFailedMatcher: <*gstruct.FieldsMatcher | 0xc004a11ce0>{
              Fields: {
                  "Status": <*matchers.EqualMatcher | 0xc002e01530>{
                      Expected: <v1beta1.ConditionStatus>"Progressing",
                  },
              },
              IgnoreExtras: true,
              IgnoreMissing: false,
              failures: [
                  <*errors.NestedError | 0xc0025a3440>{
                      Path: ".Status",
                      Err: <*errors.errorString | 0xc003166770>{
                          s: "Expected\n    <v1beta1.ConditionStatus>: False\nto equal\n    <v1beta1.ConditionStatus>: Progressing",
                      },
                  },
              ],
          },
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:[201](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6873/pull-gardener-integration/1586620335078248448#1:build-log.txt%3A201)
```

### LINKED ISSUE #7124: [Flaky Test] Seed Controller Integration Test Suite
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
Seed controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:44
  when seed namespace exists
  /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:109
    when internal domain secret exists
    /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:143
      when global monitoring secret exists
      /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:180
        [It] should properly maintain the Bootstrapped condition and deploy all seed system components
        /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:357
```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7089/pull-gardener-integration/1597967667161993216

**Reason for failure**:
```

  Timed out after 5.001s.
  Error: Assertion in callback at /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:339 failed:
  Expected success, but got an error:
      <*errors.StatusError | 0xc0013ed7c0>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "the server could not find the requested resource (get managedresources.resources.gardener.cloud)",
              Reason: "NotFound",
              Details: {
                  Name: "",
                  Group: "resources.gardener.cloud",
                  Kind: "managedresources",
                  UID: "",
                  Causes: [
                      {
                          Type: "UnexpectedServerResponse",
                          Message: "404 page not found",
                          Field: "",
                      },
                  ],
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
      the server could not find the requested resource (get managedresources.resources.gardener.cloud)
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/seed/seed/seed_test.go:341
```

**Anything else we need to know**:
First assumption: in the test we delete the Seed, the Seed deletion destroys the GRM, the Destroy func of GRM deletes managedresources.resources.gardener.cloud CRD, while in the test we try to list all ManagedResources.

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
The test errors with,
```
  Reason: "GardenSecretsError",
              Message: "need an internal domain secret but found none",
              Codes: nil,
```
This PR adds a check to wait until the manager cache has observed the created secrets.
I hope this will solve the flake.

**Which issue(s) this PR fixes**:
Fixes #6933
Fixes #7124

**Special notes for your reviewer**:
I was unable to reproduce this locally, because running against an actual cluster, the tests won't pass at all because the deployment controller is running and it doesn't allow manually patching the deployment.

I tried to wait for the pod to get ready, but the image tag from the component-base version ([ref](https://github.com/gardener/gardener/blob/b4df8668a47e3c68be00a55a9692b60242ab7fbb/pkg/gardenlet/controller/seed/seed/components.go#L179)),was not proper because we don't set the ldflags in the integration tests. Added ba7b8fc4cda24ccedf7a11a652c4e456b394bded to solve this, still the timeouts were too low, so the test never succeeded. But thought there is no harm in keeping this change.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: hack/test-integration.sh [hunk 1]
```diff
@@ -42,4 +44,4 @@ if [ -n "${CI:-}" -a -n "${ARTIFACTS:-}" ] ; then
   test_flags="--ginkgo.junit-report=junit.xml"
 fi
 
-GO111MODULE=on go test -timeout=5m -mod=vendor $@ $test_flags | grep -v 'no test files'
+GO111MODULE=on go test -timeout=5m -mod=vendor -ldflags "$LD_FLAGS" $@ $test_flags | grep -v 'no test files'
```
Comment (timebertt) [inline hack/test-integration.sh]: > I was unable to reproduce this locally, because running against an actual cluster, the tests won't pass at all because the deployment controller is running and it doesn't allow manually patching the deployment.

In my opinion, this is not the right solution to the problem.
Setting `ldflags` to inject the current version does not help if the corresponding image has not been built yet.
We should rather look into improving the test so that we can run it both against envtest and an existing cluster.
We would need to fake the `Deployment` readiness check in another way.

**Review by timebertt — CHANGES_REQUESTED** [review]

File: hack/test-integration.sh (hunk 1 above)
Comment (shafeeqes) [reply hack/test-integration.sh]: > Setting ldflags to inject the current version does not help if the corresponding image has not been built yet.

Without this, this is defaulted to https://github.com/gardener/gardener/blob/616b60a84b74624228d275d40462ebb22fc6ecb5/vendor/k8s.io/client-go/pkg/version/base.go#L58
So keeping this change doesn't hurt, right?

> We would need to fake the Deployment readiness check in another way.

Do you have something in mind?

Comment (timebertt) [reply hack/test-integration.sh]: > So keeping this change doesn't hurt, right?

I'm rather saying it doesn't help to solve any problem, so let's not introduce it.

> Do you have something in mind?

You could fake this on the client side, e.g., by overwriting a function for checking deployment readiness.

File: test/integration/gardenlet/seed/seed/seed_test.go [hunk 2]
```diff
@@ -234,17 +248,19 @@ var _ = Describe("Seed controller tests", func() {
...
-						g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(testNamespace), testNamespace)).To(Succeed())
-						g.Expect(testNamespace.Labels).To(And(
-							HaveKeyWithValue("role", "garden"),
-							HaveKeyWithValue("high-availability-config.resources.gardener.cloud/consider", "true"),
-						))
-						g.Expect(testNamespace.Annotations).To(And(
-							HaveKeyWithValue("high-availability-config.resources.gardener.cloud/zones", "a,b,c"),
-						))
-					}).Should(Succeed())
+					if !seedIsGarden {
```
Comment (shafeeqes) [inline test/integration/gardenlet/seed/seed/seed_test.go:251]: Made this change, because https://github.com/gardener/gardener/blob/555bb9874d0507d2bd382e8a2657569f6a80e530/pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go#L300-L304

File: test/integration/gardenlet/seed/seed/seed_test.go [hunk 3]
```diff
@@ -333,25 +364,27 @@ var _ = Describe("Seed controller tests", func() {
 					By("Delete Seed")
 					Expect(testClient.Delete(ctx, seed)).To(Succeed())
 
-					By("Verify that the seed system components have been deleted")
-					Eventually(func(g Gomega) []resourcesv1alpha1.ManagedResource {
-						managedResourceList := &resourcesv1alpha1.ManagedResourceList{}
-						g.Expect(testClient.List(ctx, managedResourceList, client.InNamespace(testNamespace.Name))).To(Succeed())
-						return managedResourceList.Items
-					}).Should(BeEmpty())
+					if seedIsGarden {
```
Comment (shafeeqes) [inline test/integration/gardenlet/seed/seed/seed_test.go:362]: This is already ensured by the controller if the seed is not garden,
https://github.com/gardener/gardener/blob/9634d37e9ba8fd8ef54be9fa7dd997856f335b54/pkg/gardenlet/controller/seed/seed/reconciler_delete.go#L297-L330
Trying to assert this fails sometimes because the CRD is already gone, eg: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7080/pull-gardener-integration/1596078462827761664#1:build-log.txt%3A270-302, https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7062/pull-gardener-integration/1595693472789041152#1:build-log.txt%3A257-290 etc

File: test/integration/gardenlet/seed/seed/seed_test.go [hunk 4]
```diff
@@ -333,25 +364,27 @@ var _ = Describe("Seed controller tests", func() {
...
 							return testClient.Get(ctx, client.ObjectKeyFromObject(deployment), deployment)
-						}).Should(BeNotFoundError())
+						}).WithTimeout(10 * time.Second).Should(BeNotFoundError())
 					}
 
 					By("Ensure Seed is gone")
 					Eventually(func() error {
 						return testClient.Get(ctx, client.ObjectKeyFromObject(seed), seed)
-					}).Should(BeNotFoundError())
+					}).WithTimeout(10 * time.Second).Should(BeNotFoundError())
```
Comment (shafeeqes) [inline test/integration/gardenlet/seed/seed/seed_test.go]: Without increasing the timeout, the test doesn't seem to pass against an actual cluster.

File: test/integration/gardenlet/seed/seed/seed_test.go [hunk 5]
```diff
@@ -35,13 +36,15 @@ import (
...
+	"github.com/gardener/gardener/pkg/operation/botanist/component/resourcemanager"
 	gutil "github.com/gardener/gardener/pkg/utils/gardener"
+	"github.com/gardener/gardener/pkg/utils/retry"
 	secretutils "github.com/gardener/gardener/pkg/utils/secrets"
 	"github.com/gardener/gardener/pkg/utils/test"
 	. "github.com/gardener/gardener/pkg/utils/test/matchers"
 )
 
-var _ = Describe("Seed controller tests", func() {
+var _ = Describe("Seed controller tests", Ordered, func() {
```
Comment (shafeeqes) [inline test/integration/gardenlet/seed/seed/seed_test.go]: The controller decides if the seed is garden too, by this logic here:
https://github.com/gardener/gardener/blob/ab9b4f181a2038c7ee1df3bb724243925eb9caed/pkg/gardenlet/controller/seed/seed/reconciler.go#L99-L105
Running the `It`s in parallel causes flakes due to this.

**Review by shafeeqes — COMMENTED** [review]
I still can't stress test this test, because,
MRs from parallel tests cause issues here, https://github.com/gardener/gardener/blob/9634d37e9ba8fd8ef54be9fa7dd997856f335b54/pkg/gardenlet/controller/seed/seed/reconciler_delete.go#L310-L323

Injecting labels for these resources is a bit hard. Open to suggestions for working around this.
Also I had to increase the timeouts for some `Eventually`s to make the test pass against an actual cluster.

I can change the title of the PR to `Make it possible to test `Seed Controller` against an actual cluster` too if this improvements may not really "deflake" the tests.

**Comment by shafeeqes** [comment]
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7044/pull-gardener-integration/1597825527501033472 is another occurence of #6928 

/test pull-gardener-integration

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 4 above)
Comment (timebertt) [reply test/integration/gardenlet/seed/seed/seed_test.go]: Let's remove the hardcoded timeouts here that are required for running against an actual cluster.
When running against an actual cluster, you can overwrite the timeouts by setting `GOMEGA_DEFAULT_EVENTUALLY_TIMEOUT` as needed.

File: pkg/operation/botanist/component/resourcemanager/resource_manager.go [hunk 6]
```diff
@@ -1772,14 +1772,16 @@ var (
 	// TimeoutWaitForDeployment is the timeout used while waiting for the Deployments to become healthy
 	// or deleted.
 	TimeoutWaitForDeployment = 5 * time.Minute
+	// WaitForDeployment is an alias for retry.Until. Exposed for tests.
+	WaitForDeployment = retry.Until
```
Comment (timebertt) [inline pkg/operation/botanist/component/resourcemanager/resource_manager.go]: This alias should rather be called something like `Until`, as it doesn't do anything with deployments in particular

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 5 above)
Comment (timebertt) [reply test/integration/gardenlet/seed/seed/seed_test.go]: `It`s are never executed in parallel in one suite execution. `Ordered` switches from executing test specs in random order (default behavior) to executing test specs in the order they are listed in in the code.

File: test/integration/gardenlet/seed/seed/seed_test.go [hunk 7]
```diff
@@ -115,6 +118,11 @@ var _ = Describe("Seed controller tests", func() {
 			seedNamespace = &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: gutil.ComputeGardenNamespace(seed.Name)}}
 			Expect(testClient.Create(ctx, seedNamespace)).To(Succeed())
 
+			By("wait till the manager obeserves seed namespace")
```
Comment (timebertt) [inline test/integration/gardenlet/seed/seed/seed_test.go]: Can you keep the `By` message consistent with the others?
```suggestion
			By("Wait until the manager obeserves seed namespace")
```

File: test/integration/gardenlet/seed/seed/seed_test.go [hunk 8]
```diff
@@ -277,6 +303,11 @@ var _ = Describe("Seed controller tests", func() {
 							g.Expect(testClient.Delete(ctx, mutatingWebhookConfiguration)).To(Succeed())
 							g.Expect(testClient.Delete(ctx, validatingWebhookConfiguration)).To(Succeed())
 						}).Should(Succeed())
+
+						Eventually(func(g Gomega) {
```
Comment (timebertt) [inline test/integration/gardenlet/seed/seed/seed_test.go]: Why did you add this `Eventually` block?

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 3 above)
Comment (timebertt) [reply test/integration/gardenlet/seed/seed/seed_test.go:362]: I'm confused why you added this `if` block.
Shouldn't the controller cleanup all created `ManagedResources` in both cases?

**Review by timebertt — COMMENTED** [review]
Generally, if the test can't be stress-tested against an existing cluster but we can still deflake it for CI, that's already valuable.
So, if it's too hard to make this one stress-testable, you can skip it if you want.

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 3 above)
Comment (shafeeqes) [reply test/integration/gardenlet/seed/seed/seed_test.go:362]: Because if `seedIsGarden`, `resourcemanager.Destroy` is not called, and this function cleans up the CRDs.
When we try to assert the same when `seedIsNotGarden`, then before we check for the `ManagedResourceList` to be empty, the controller has already cleanedup the CRDs and it gives,
```
              Message: "the server could not find the requested resource (get managedresources.resources.gardener.cloud)",
```
like in the prow logs above.

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 8 above)
Comment (shafeeqes) [reply test/integration/gardenlet/seed/seed/seed_test.go]: Sometimes, I saw that the webhookConfig is not deleted yet and the apply of resources fail because the webhook endpoints are not served.

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 5 above)
Comment (timebertt) [reply test/integration/gardenlet/seed/seed/seed_test.go]: What about this comment?

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 8 above)
Comment (timebertt) [reply test/integration/gardenlet/seed/seed/seed_test.go]: Ok got it. However, the `Eventually` block will not help solve this case. 
It doesn't matter if the manager's client has observed that the webhooks have been deleted. It only matters whether the API server's informers in the admission plugins have observed the deletion, and you can't wait for that / check that in the test (there is simply no way). So intermittent failures are always expected in such cases.

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 3 above)
Comment (timebertt) [reply test/integration/gardenlet/seed/seed/seed_test.go:362]: Got it, thanks for explaining. Can you add a corresponding code comment to explain this to others reading the code?

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 5 above)
Comment (shafeeqes) [reply test/integration/gardenlet/seed/seed/seed_test.go]: The Ordered prevents the flake, maybe because the garden test is the very last one.
Then, maybe we can make sure the `garden` resource is not present in the other `It`s before asserting stuff?

Comment (timebertt) [reply test/integration/gardenlet/seed/seed/seed_test.go]: Yes, we should make sure that all test cases leave a clean environment for the next test cases, i.e. by properly cleaning up using `DeferCleanup` and `AfterEach`.

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 3 above)
Comment (shafeeqes) [reply test/integration/gardenlet/seed/seed/seed_test.go:362]: Done with https://github.com/gardener/gardener/pull/7044/commits/c1baa147dff6213c967c605277fc12f80fc6bfe9, PTAL!

**Comment by shafeeqes** [comment]
> @shafeeqes: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-integration	[c1baa14](https://github.com/gardener/gardener/commit/c1baa147dff6213c967c605277fc12f80fc6bfe9)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7044/pull-gardener-integration/1598233026121175040)	true	`/test pull-gardener-integration`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=7044). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Ashafeeqes). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

```
 STEP: Create Garden 12/01/22 08:35:06.927
    {"level":"info","ts":"2022-12-01T08:35:06.935Z","logger":"seed-controller-test","msg":"Created Garden for test","garden":"garden-swl2c"}
    STEP: Wait until the manager cache observes the garden 12/01/22 08:35:06.935
    STEP: Wait for Seed to have finalizer 12/01/22 08:35:06.935
    STEP: Wait for Bootstrapped condition to be set to Progressing 12/01/22 08:35:06.938
    STEP: Verify that CA secret was generated 12/01/22 08:35:06.94
    STEP: Verify that kube-system namespace was labeled appropriately 12/01/22 08:35:06.941
    STEP: Verify that global monitoring secret was replicated 12/01/22 08:35:06.942
    STEP: Create CustomResourceDefinition for ManagedResources 12/01/22 08:35:06.943
    STEP: Verify that the seed system components have been deployed 12/01/22 08:35:06.947
    {"level":"info","ts":"2022-12-01T08:35:07.138Z","msg":"Deploying and waiting for gardener-resource-manager to be healthy","controller":"seed","object":{"name":"seed-garden-trp68"},"namespace":"","name":"seed-garden-trp68","reconcileID":"feef2768-c457-436e-bdfc-f4ae2ec7fec3"}
    STEP: Delete Garden 12/01/22 08:35:16.948
    STEP: Delete Seed 12/01/22 08:35:16.956
```
The controller thinks the seed is garden, and waits for the GRM deployment readiness 😕

**Comment by shafeeqes** [comment]
> The controller thinks the seed is garden, and waits for the GRM deployment readiness

The 500ms SyncPeriod seems to be too low, reverted it back to default sync period: https://github.com/gardener/gardener/pull/7044/commits/704781fe5572637aaa3073f50a369c96433a0de7

File: test/integration/gardenlet/seed/seed/seed_test.go [hunk 9]
```diff
@@ -196,12 +215,27 @@ var _ = Describe("Seed controller tests", func() {
...
+					// Make sure there are no garden resources present before proceeding to the test, since the controller takes the
+					// decision whether the seed is garden or not based on this.
+					if !seedIsGarden {
+						Eventually(func(g Gomega) []operatorv1alpha1.Garden {
+							gardenList := &operatorv1alpha1.GardenList{}
+							g.Expect(mgrClient.List(ctx, gardenList)).To(Succeed())
+							return gardenList.Items
+						}).Should(BeEmpty())
+					}
+
```
Comment (rfranzke) [inline test/integration/gardenlet/seed/seed/seed_test.go]: Do we still need this after the recent changes?

File: test/integration/gardenlet/seed/seed/seed_suite_test.go [hunk 10]
```diff
@@ -171,7 +175,8 @@ var _ = BeforeSuite(func() {
 		Config: config.GardenletConfiguration{
 			Controllers: &config.GardenletControllerConfiguration{
 				Seed: &config.SeedControllerConfiguration{
-					SyncPeriod: &metav1.Duration{Duration: time.Minute},
+					// This controller is pretty heavy-weight, so use DefaultControllerSyncPeriod
+					SyncPeriod: &gardenletconfigv1alpha1.DefaultControllerSyncPeriod,
```
Comment (rfranzke) [inline test/integration/gardenlet/seed/seed/seed_suite_test.go]: Let's rather keep it like before (not using this variable but `time.Minute` directly).

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 2 above)
Comment (rfranzke) [reply test/integration/gardenlet/seed/seed/seed_test.go:251]: Great catch, thanks!

File: test/integration/gardenlet/seed/seed/seed_test.go [hunk 11]
```diff
@@ -333,12 +369,18 @@ var _ = Describe("Seed controller tests", func() {
...
+						// ManagedResourceList is empty, the CRDs are already gone. Since the gardener-resource-manager is deleted only after all the managedresources
+						// are gone, we don't need to assert it seperately. In case the seed is garden, the Destroy is called by the gardener-operator and since it's
+						// not running in this test, we can safely assert the below-mentioned.
+						By("Verify that the seed system components have been deleted")
+						Eventually(func(g Gomega) []resourcesv1alpha1.ManagedResource {
+							managedResourceList := &resourcesv1alpha1.ManagedResourceList{}
+							g.Expect(testClient.List(ctx, managedResourceList, client.InNamespace(testNamespace.Name))).To(Succeed())
+							return managedResourceList.Items
+						}).Should(BeEmpty())
+					}
```
Comment (rfranzke) [inline test/integration/gardenlet/seed/seed/seed_test.go]: Can you use `} else {` here and replace L384-L385?

File: test/integration/gardenlet/seed/seed/seed_test.go [hunk 12]
```diff
@@ -333,12 +369,18 @@ var _ = Describe("Seed controller tests", func() {
...
-					By("Verify that the seed system components have been deleted")
-					Eventually(func(g Gomega) []resourcesv1alpha1.ManagedResource {
-						managedResourceList := &resourcesv1alpha1.ManagedResourceList{}
-						g.Expect(testClient.List(ctx, managedResourceList, client.InNamespace(testNamespace.Name))).To(Succeed())
-						return managedResourceList.Items
-					}).Should(BeEmpty())
+					if seedIsGarden {
+						// The CRDs are cleaned up by the Destroy function of GRM, in case the seed is not garden. So It might happen that, before we fetch the
+						// ManagedResourceList is empty, the CRDs are already gone. Since the gardener-resource-manager is deleted only after all the managedresources
+						// are gone, we don't need to assert it seperately. In case the seed is garden, the Destroy is called by the gardener-operator and since it's
```
Comment (rfranzke) [inline test/integration/gardenlet/seed/seed/seed_test.go]:
```suggestion
						// are gone, we don't need to assert it separately. In case the seed is garden, the Destroy is called by the gardener-operator and since it's
```

File: test/integration/gardenlet/seed/seed/seed_test.go [hunk 13]
```diff
@@ -333,12 +369,18 @@ var _ = Describe("Seed controller tests", func() {
...
 					Expect(testClient.Delete(ctx, seed)).To(Succeed())
 
-					By("Verify that the seed system components have been deleted")
-					Eventually(func(g Gomega) []resourcesv1alpha1.ManagedResource {
-						managedResourceList := &resourcesv1alpha1.ManagedResourceList{}
-						g.Expect(testClient.List(ctx, managedResourceList, client.InNamespace(testNamespace.Name))).To(Succeed())
-						return managedResourceList.Items
-					}).Should(BeEmpty())
+					if seedIsGarden {
+						// The CRDs are cleaned up by the Destroy function of GRM, in case the seed is not garden. So It might happen that, before we fetch the
```
Comment (rfranzke) [inline test/integration/gardenlet/seed/seed/seed_test.go]: I find this comment confusing to talk about "the seed is not garden" while L372 has `if seedIsGarden`. Can you re-arrange this a bit to make it easier understandable?

File: test/integration/gardenlet/seed/seed/seed_test.go (hunk 9 above)
Comment (shafeeqes) [reply test/integration/gardenlet/seed/seed/seed_test.go]: Hmm, this might not be useful, but we can still wait in the `garden` test `BeforeEach` for the garden resource to be gone. Will make the changes.

**Review by rfranzke — COMMENTED** [review]
Thanks @shafeeqes, this looks promising now. Let's go.

/lgtm
/approve
