### PR TITLE
Do not Require Running DNS Extension for `unmanaged` Provider

### LINKED ISSUE #910: Local development setup doesn't work with external dns provider
After introducing the external DNS Provider, the local setup fails to create a shoot.

The Controller reflects the following error message:
```
Could not initialize a new operation: unable to figure out which secret should be used for dns
```

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**:
Do not require running DNS extension for `unmanaged` provider.
Also, I propose fixes for health check and hibernation for the local provider.

**Which issue(s) this PR fixes**:
Fixes #910 

**Special notes for your reviewer**:
/cc @ialidzhikov @pablochacin 

I will squash the commits once we agree how the change will look like.

**Release note**:

```improvement operator
Gardener does now respect the `unmanaged` DNS provider and does not deploy DNS records for it.
```

### CODE REVIEW

File: pkg/operation/botanist/dns.go [hunk 1]
```diff
@@ -86,6 +87,10 @@ func (b *Botanist) DestroyExternalDomainDNSRecord(ctx context.Context) error {
 }
 
 func (b *Botanist) deployDNSProvider(ctx context.Context, name, provider string, secretData map[string][]byte, includedDomains ...string) error {
+	if provider == v1beta1.DNSUnmanaged {
```
Comment (timuthy) [inline pkg/operation/botanist/dns.go]: Can we let `shoot_control_reconcile` rather skip the complete steps of deploying the internal dns entry? https://github.com/gardener/gardener/blob/b6e614486c3f72818592eb060592f2ec604ae3b8/pkg/controllermanager/controller/shoot/shoot_control_reconcile.go#L109.

like we do it for:
https://github.com/gardener/gardener/blob/b6e614486c3f72818592eb060592f2ec604ae3b8/pkg/controllermanager/controller/shoot/shoot_control_reconcile.go#L114

File: pkg/operation/botanist/dns.go [hunk 2]
```diff
@@ -144,6 +149,10 @@ func (b *Botanist) deleteDNSProvider(ctx context.Context, name string) error {
 }
 
 func (b *Botanist) deployDNSEntry(ctx context.Context, name, dnsName, target string) error {
+	if strings.HasSuffix(dnsName, ".nip.io") {
```
Comment (timuthy) [inline pkg/operation/botanist/dns.go]: See above.

File: pkg/operation/botanist/botanist.go [hunk 3]
```diff
@@ -199,10 +199,13 @@ func (b *Botanist) RequiredExtensionsExist() error {
 func (b *Botanist) computeRequiredExtensions() map[string]string {
 	requiredExtensions := map[string]string{
 		extensionsv1alpha1.OperatingSystemConfigResource: string(b.Shoot.GetMachineImageName()),
-		dnsv1alpha1.DNSProviderKind:                      b.Garden.InternalDomain.Provider,
 	}
 
-	if b.Shoot.ExternalDomain != nil {
+	if b.Garden.InternalDomain.Provider != gardenv1beta1.DNSUnmanaged {
+		requiredExtensions[dnsv1alpha1.DNSProviderKind] = b.Garden.InternalDomain.Provider
```
Comment (timuthy) [inline pkg/operation/botanist/botanist.go:205]: BTW, shouldn't the key-value-mapping the other way around, i.e. `map[type]kind` since the cardinality of `kind:type` is `1:n`?

I know this is not addressed by this PR but I just noticed it incidentally. /cc @rfranzke

**Review by timuthy — CHANGES_REQUESTED** [review]

File: pkg/operation/shoot/shoot.go [hunk 4]
```diff
@@ -237,9 +237,12 @@ func (s *Shoot) ComputeAPIServerURL(runsInSeed, useInternalClusterDomain bool) s
 	if runsInSeed {
 		return common.KubeAPIServerDeploymentName
 	}
-
+	apiServerPortSuffix := ""
+	if s.CloudProvider == gardenv1beta1.CloudProviderLocal {
+		apiServerPortSuffix = ":31443"
+	}
 	if dnsProvider := s.Info.Spec.DNS.Provider; dnsProvider != nil && *dnsProvider == gardenv1beta1.DNSUnmanaged {
```
Comment (pablochacin) [inline pkg/operation/shoot/shoot.go]: I would expect that instead of having to check for the DNS provider, `useInternaClusterDomain` should be set to true when DNS provider is `DNSUnmanaged`

File: pkg/operation/cloudbotanist/localbotanist/localbotanist.go [hunk 5]
```diff
@@ -32,7 +32,7 @@ func New(o *operation.Operation) (*LocalBotanist, error) {
 		CloudProviderName: "",
 	}
 	vb.APIServerAddress = *o.Shoot.Info.Spec.DNS.Domain
-	vb.Shoot.InternalClusterDomain = *o.Shoot.Info.Spec.DNS.Domain + ":31443"
+	vb.Shoot.InternalClusterDomain = *o.Shoot.Info.Spec.DNS.Domain
```
Comment (pablochacin) [inline pkg/operation/cloudbotanist/localbotanist/localbotanist.go]: Not sure why moving the logic of adding the port to the shoot instead of leaving here in the local botanist

Comment (vpnachev) [reply pkg/operation/cloudbotanist/localbotanist/localbotanist.go]: Valid domain name does not contain port number.

**Comment by vpnachev** [comment]
@timuthy thank for the review!
Please, take a look again.

**Comment by vpnachev** [comment]
@mvladev I am migrating `local` provider to use port 443 for the `kube-apiserver` NodePort service.
Any comments, feedback or objections?

File: pkg/operation/botanist/botanist.go (hunk 3 above)
Comment (rfranzke) [reply pkg/operation/botanist/botanist.go:205]: Good catch, yes, let's address this separately

**Review by rfranzke — DISMISSED** [review]
/lgtm

File: pkg/operation/shoot/shoot.go (hunk 4 above)
Comment (timuthy) [reply pkg/operation/shoot/shoot.go]: I think the intention behind this is to have a "stable" fallback because the internal domain is in Gardener's responsibility.

**Review by timuthy — DISMISSED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
> @mvladev I am migrating `local` provider to use port 443 for the `kube-apiserver` NodePort service.
> Any comments, feedback or objections?

For minikube it is trivial to pass apiserver flag. For Docker Edge you have only a single `Enable Kubernetes` button and according the [docs](https://docs.docker.com/docker-for-mac/kubernetes/):
> The Kubernetes server runs locally within your Docker instance, is not configurable, and is a single-node cluster.

I would rather prefer to revert the port change and to preserve the docker scenario.

**Comment by rfranzke** [comment]
@vpnachev what's the plan, will you revert it?

**Comment by vpnachev** [comment]
I will revert local provider to use port `31443`.

File: docs/development/local_setup.md [hunk 6]
```diff
@@ -191,10 +191,10 @@ The commands below will configure your `minikube` with the absolute minimum reso
 
 #### Start minikube
 
-First, start `minikube` with at least Kubernetes v1.11.x. The default CPU and memory settings of the minikube machine are not sufficient to host the control plane of a shoot cluster, thus the minimal resources should be 3 CPUs and 4096 MB memory, while the recommended are 4 CPUs and 8192 MB memory.
+First, start `minikube` with at least Kubernetes v1.11.x. The default CPU and memory settings of the minikube machine are not sufficient to host the control plane of a shoot cluster, thus the minimal resources should be 3 CPUs and 4096 MB memory, while the recommended are 4 CPUs and 8192 MB memory. If you are going to use the `local` provider, then the minikube cluster must be able to create `NodePort` service on port `443`
```
Comment (pablochacin) [inline docs/development/local_setup.md]: What's the rationale for changing the port? This may be very limitative as this port may already be used.

File: pkg/operation/shoot/shoot.go (hunk 4 above)
Comment (pablochacin) [reply pkg/operation/shoot/shoot.go]: Yes, but as there's already the `useInternalClusterDomain` we could reuse it instead of introducing additional logic.

**Comment by vpnachev** [comment]
@rfranzke @timuthy , please take a look again.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by timuthy — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]
/lgtm
