### PR TITLE
[GEP-28] Attempt to reduce the amount of end-to-end test flakes in the `gardenadm` scenario

### LINKED ISSUE #13811: [Flaky Test] `pull-gardener-e2e-kind-gardenadm` is flaky
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
`pull-gardener-e2e-kind-gardenadm` flakes because of unready `gardener-resource-manager` and `provider-local` instances.

```
[err] [shoot--garden--root-control-plane-5d965-bkx5k] 	* task "Deploying shoot worker pools" failed: Internal error occurred: failed calling webhook "validation.extensions.workers.resources.gardener.cloud": failed to call webhook: Post "[https://gardener-resource-manager.garden.svc:443/validate-extensions-gardener-cloud-v1alpha1-worker?timeout=10s](https://gardener-resource-manager.garden.svc/validate-extensions-gardener-cloud-v1alpha1-worker?timeout=10s)": dial tcp 10.3.0.10:10250: connect: connection refused
  [err] [shoot--garden--root-control-plane-5d965-bkx5k]
```

```
[err] [shoot--garden--root-control-plane-5d965-8jbl6] 	* task "Deploying machine-controller-manager" failed: retry failed with context deadline exceeded, last error: Internal error occurred: failed calling webhook "controlplane.local.extensions.gardener.cloud": failed to call webhook: Post "[https://gardener-extension-provider-local.extension-provider-local.svc:443/controlplane?timeout=10s](https://gardener-extension-provider-local.extension-provider-local.svc/controlplane?timeout=10s)": no endpoints available for service "gardener-extension-provider-local"
```
**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/13784/pull-gardener-e2e-kind-gardenadm/2013180062525820928
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/13720/pull-gardener-e2e-kind-gardenadm/2013226974280945664
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/13783/pull-gardener-e2e-kind-gardenadm/2012494359571730432

**Reason for failure**:
N/A

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area ipcei
/area robustness
/area quality
/kind flake

**What this PR does / why we need it**:

Attempt to reduce the amount of end-to-end test flakes in the `gardenadm` scenario.

When transitioning from the bootstrap `etcd` to the ordinary `etcd`, `kube-apiserver` is temporarily not available because `etcd` goes down. This can lead to a number of controllers to crash and go in backoff.

Considering the increase in end-to-end test flakes reported in #13811, it seems obvious that the runtime `gardener-resource-manager` needs to be health-checked. In addition to that, we also need to ensure that `kube-controller-manager` is active as many health checks rely on the status of managed resources being properly maintained. Before the `etcd` update everything may have been running flawlessly. Hence, if `kube-controller-manager` was not able to update the state we may believe the old status values. Hence, we check that `kube-controller-manager` is active as well.

**Which issue(s) this PR fixes**:
Fixes #13811

**Special notes for your reviewer**:

/cc @tobschli @rfranzke 

/hold

Let's wait for multiple test runs.

**Release note**:

```other operator

```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Review by timebertt — APPROVED** [review]
Thanks for improving this check!

**Comment by ScheererJ** [comment]
Found another issue that sometimes causes flakes.
PTAL.

File: pkg/gardenadm/cmd/init/init.go [hunk 1]
```diff
@@ -357,7 +357,7 @@ func run(ctx context.Context, opts *Options) error {
 					b.Shoot.Components.ControlPlane.ResourceManager.Wait,
 				),
 				b.WaitUntilExtensionControllerInstallationsHealthy,
-			),
+			).Timeout(5 * time.Minute),
```
Comment (timebertt) [inline pkg/gardenadm/cmd/init/init.go]: I'm not sure if this change yields the desired effect. In the called functions, there are hard-coded timeouts ignoring the timeout of the passed context.
E.g., in `WaitUntilExtensionControllerInstallationsHealthy` the `TimeoutManagedResourceHealthCheck` is `2m`.

File: pkg/gardenadm/cmd/init/init.go [hunk 2]
```diff
@@ -336,16 +336,29 @@ func run(ctx context.Context, opts *Options) error {
...
 			Fn: flow.Sequential(
-				b.Shoot.Components.ControlPlane.ResourceManager.Wait,
+				flow.Parallel(
+					b.Components.RuntimeResourceManager.Wait,
+					b.Shoot.Components.ControlPlane.ResourceManager.Wait,
+				),
 				b.WaitUntilExtensionControllerInstallationsHealthy,
-			),
-			Dependencies: flow.NewTaskIDs(waitUntilControlPlaneDeploymentsReady),
+			).Timeout(5 * time.Minute),
```
Comment (timebertt) [inline pkg/gardenadm/cmd/init/init.go]: Should we increase the timeout in `KubeControllerManager.WaitForControllerToBeActive` as well?

File: pkg/gardenadm/cmd/init/init.go (hunk 1 above)
Comment (ScheererJ) [reply pkg/gardenadm/cmd/init/init.go]: Good point.
I do not really understand why the timeout looks like `3min` in https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/13863/pull-gardener-e2e-kind-gardenadm/2014362978396147712, though.
Nevertheless, the problem should be solved by using `RetryUntilTimeout` function or am I missing something?

File: pkg/gardenadm/cmd/init/init.go (hunk 2 above)
Comment (ScheererJ) [reply pkg/gardenadm/cmd/init/init.go]: I did not see the issue for `KubeControllerManager.WaitForControllerToBeActive`, but I applied the same fix now there as well.
PTAL.

**Review by timebertt — APPROVED** [review]
Thanks, this should work :)
