### PR TITLE
Ensure new osc name for different cri configuration

### LINKED ISSUE #4254: Changing `cri.name=containerd` to `cri=nil` still leaves `containerd` running on the node as systemd service
**How to categorize this issue?**
/kind bug
/priority 3

**What happened**:
When changing a worker pool from using `containerd` as a container runtime to `docker`, the new nodes still run `containerd` as systemd service
```
$ systemctl list-units | grep containerd
  containerd.service   loaded    active     running      containerd container runtime
```

The kubelet is correctly configured to not use `containerd` as external container runtime
```
$ ps -aux | grep kubelet
root        3962  4.7  1.5 1967744 116840 ?      SLsl 15:18   0:14 /opt/bin/kubelet --bootstrap-kubeconfig=/var/lib/kubelet/kubeconfig-bootstrap --config=/var/lib/kubelet/config/kubelet --cni-bin-dir=/opt/cni/bin/ --cni-conf-dir=/etc/cni/net.d/ --image-pull-progress-deadline=1m0s --kubeconfig=/var/lib/kubelet/kubeconfig-real --network-plugin=cni --pod-infra-container-image=<redacted> --v=2 --cloud-provider=external --enable-controller-attach-detach=true
```

The node is correctly reported to use the `docker` runtime
 ```
$ kubectl get nodes -o wide
NAME                                                      STATUS   ROLES    AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION        CONTAINER-RUNTIME
shoot--d058546--cri-migrate-worker-docke-z1-f8f48-c6bq2   Ready    <none>   5m24s   v1.20.6   10.250.0.8    <none>        Garden Linux 184.0   5.4.0-5-cloud-amd64   docker://19.3.13
```

**What you expected to happen**:
Only docker is started on the new nodes. There should be no signs of `containerd`

**How to reproduce it (as minimally and precisely as possible)**:
* Create a cluster with `cri.name=containerd`. This gets you a node using `containerd` as container runtime
* Remove the `cri` and `cri.name` properties from your worker pool. This gets you a node using `docker` as container runtime, as this is the current default when `cri==nil`
* Look at the output of `kubectl get nodes -o wide` to verify you're getting a new node with `docker` as container runtime while the old node with `containerd` container runtime is drained and deleted
* ssh into the new node and look at the started systemd units

**Anything else we need to know?**:
* This really is a new node
```
$ uptime
 15:28:09 up 10 min,  0 users,  load average: 0.34, 0.64, 0.52
```

* The `userData` for the new node seems to incorrectly contain `containerd` (thanks @prashanth26) 

```
kubectl get secret -n shoot--d058546--cri-migrate shoot--d058546--cri-migrate-worker-docke-z1-7c48e  -o json | jq -r .data.userData | base64 -d
#!/bin/bash
mkdir -p /etc/systemd/system/containerd.service.d
cat <<EOF > /etc/systemd/system/containerd.service.d/11-exec_config.conf
[Service]
ExecStart=
ExecStart=/usr/bin/containerd --config=/etc/containerd/config.toml
EOF
chmod 0644 /etc/systemd/system/containerd.service.d/11-exec_config.conf
[...]
systemctl daemon-reload
systemctl enable containerd && systemctl restart containerd
systemctl enable docker && systemctl restart docker
systemctl enable 'cloud-config-downloader.service' && systemctl restart 'cloud-config-downloader.service'
```

* `operatingsystemconfig`-original is older than the `machineset` and has `spec.criconfig.name=containerd`
* However, it does _not_ contain `containerd` as a unit. `status.units` has 
```
updatecacerts.service                                                                                                                                                                                                                                                             
docker-monitor.service                                                                                                                                                                                                                                                            
docker-logrotate.service                                                                                                                                                                                                                                                          
docker-logrotate.timer                                                                                                                                                                                                                                                            
systemd-sysctl.service                                                                                                                                                                                                                                                            
kubelet.service                                                                                                                                                                                                                                                                   
kubelet-monitor.service                                                                                                                                                                                                                                                           
gardener-user.service
```

* @vpnachev points out: seems like the `operatingsystemconfig` is re-used for the new `machineset` du to the fact how we compute the name: https://github.com/gardener/gardener/blob/2e0ba2a8efba0ce61c67fe09155bf41b04f2f0e7/pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L330. With #4171 allowing changing `cri.name` on existing worker pools, we also need to consider this property in the name computation.

**Environment**:

- Gardener version: 1.25.0
- Kubernetes version (use `kubectl version`): 1.21.0
- Cloud provider or hardware configuration: GCP
- Others:

### PR DESCRIPTION
**Pull request by voelzmo**
**How to categorize this PR?**

/area os
/kind bug

**What this PR does / why we need it**:
Changing `cri.name=containerd` to `cri=nil` doesn't work as expected: A node rollout happens, but the new node still starts `containerd`, which shouldn't be the case. Because the `operatingsystemconfig` name stays the same for the nodes in the new worker pool (it is currently only depending on k8s major.minor version and worker.name), the same `osc.spec.criconfig` is applied to new and old nodes. Therefore, we cannot simply update this property, but have to ensure that a new `operatingsystemconfig` is created.

**Which issue(s) this PR fixes**:
Fixes #4254

**Special notes for your reviewer**:
With this implementation, `cri=nil` and `cri.name=docker` will get different `operatingsystemconfig` names. Will this be an issue in our efforts to prevent a node rollout from happening when users switch from `cri=nil` to `cri.name=docker`?

**Release note**:

```bug user
Switching an existing worker pool from `containerd` to `docker` no longer starts `containerd` on the new node
```

### CODE REVIEW

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 1]
```diff
@@ -592,13 +592,18 @@ func (d *deployer) deploy(ctx context.Context, operation string) (extensionsv1al
 }
 
 // Key returns the key that can be used as secret name based on the provided worker name and Kubernetes version.
```
Comment (BeckerMax) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: comment is outdated

**Comment by rfranzke** [comment]
> With this implementation, cri=nil and cri.name=docker will get different operatingsystemconfig names. Will this be an issue in our efforts to prevent a node rollout from happening when users switch from cri=nil to cri.name=docker?

Good question, did you try this out?

Also, what happens to existing clusters that already have specified containerd? The OSC name will be different now, does this have any effect?

**Comment by voelzmo** [comment]
>> With this implementation, cri=nil and cri.name=docker will get different operatingsystemconfig names. Will this be an issue in our efforts to prevent a node rollout from happening when users switch from cri=nil to cri.name=docker?

> Good question, did you try this out?

When trying it out, it seemed fine. I think @vpnachev argued on slack that for consistency reasons we should have a behavior similar to the worker hash: treat an explicit cri.name=docker and cri=nil in the same way. This is also how it is implemented now.

> Also, what happens to existing clusters that already have specified containerd? The OSC name will be different now, does this have any effect?

I don't think anything changes for cri.name=containerd – I also didn't need to adapt the hashes in the test for the containerd case, so this should be fine, I think.

**Review by rfranzke — DISMISSED** [review]
Thanks for the explanations!

/lgtm then
/needs second-opinion
/invite @vpnachev

**Review by vpnachev — COMMENTED** [review]
Looks good to me. Please, just update the documentation for `Key` method as suggested by Max.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go (hunk 1 above)
Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: done

**Review by rfranzke — APPROVED** [review]
/lgtm
