### PR TITLE
Explicitly delete metrics-server on Shoot deletion

### LINKED ISSUE #5979: Explicitly delete `metrics-server` on Shoot deletion
**How to categorize this issue?**

/area usability
/kind enhancement

**What would you like to be added**:

We could explicitly delete the `metrics-server` including its `APIServices` early on in shoot deletion.

**Why is this needed**:

If there are no nodes to run `metrics-server` pods, the `APIService` is undiscoverable and can therefore block `Namespace` deletion in step `Cleaning shoot namespaces`.

It's not really a bug but an enhancement, because eventually everything works fine. Here are some steps to trigger this though:

1. Create a Shoot
2. Create a new Namespace in the Shoot
3. Hibernate the Shoot
4. Delete the Shoot
5. Observe that the step `Cleaning shoot namespaces` will be unnecessarily prolonged because the namespace is stuck in `Terminating` with 

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-05-16T09:26:24Z"
    message: 'Discovery failed for some groups, 1 failing: unable to retrieve the
      complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently
      unable to handle the request'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
```

### PR DESCRIPTION
**Pull request by krgostev**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
This PR adds additional step in the shoot deletion flow called `Deleting metrics-server`. This step explicitly deletes the metrics server before the `Cleaning shoot namespaces` step.
**Which issue(s) this PR fixes**:
Fixes #5979

**Special notes for your reviewer**:
You can find more information in the issue.
**Release note**:

```other operator
Additional step in the shoot deletion flow called `Deleting metrics-server`. This step explicitly deletes the metrics server before the `Cleaning shoot namespaces` step.
```

### CODE REVIEW

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 1]
```diff
@@ -49,7 +49,7 @@ const (
 	serviceAccountName  = "metrics-server"
 	containerName       = "metrics-server"
 	secretNameServer    = "metrics-server"
-	managedResourceName = "shoot-core-metrics-server"
+	ManagedResourceName = "shoot-core-metrics-server"
```
Comment (rfranzke) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]: doc string is missing

edit: in the light of the second comment, probably this change should be reverted

File: pkg/operation/botanist/metricsserver.go [hunk 2]
```diff
@@ -44,3 +49,15 @@ func (b *Botanist) DefaultMetricsServer() (component.DeployWaiter, error) {
 		kubeAPIServerHost,
 	), nil
 }
+
+// DeleteMetricsServer deletes the shoot-core-metrics-server managed resource.
+func (b *Botanist) DeleteMetricsServer(ctx context.Context) error {
```
Comment (rfranzke) [inline pkg/operation/botanist/metricsserver.go]: Why do we need this? Just call `MetricsServer.Destroy`  ?

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
