### PR TITLE
Ensure `node-agent-authorizer` webhook configuration is added exactly once

### LINKED ISSUE #11280: Duplicate entries for `node-agent-authorizer` webhook configuration in kube-apiserver
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:
If `gardener-resource-manager` is temporary unavailable when the [shoot reconciliation starts](https://github.com/gardener/gardener/blob/d5d3c638c9092efcb68b030da49edc7d953f61f6/pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go#L133) and becomes available again until the [deployment of kube-apiserver starts](https://github.com/gardener/gardener/blob/d5d3c638c9092efcb68b030da49edc7d953f61f6/pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go#L314-L324), the configuration of `node-agent-authorizer` webhook can be duplicated.
```
apiVersion: v1
data:
  config.yaml: |
    apiVersion: apiserver.config.k8s.io/v1beta1
    authorizers:
    - name: node
      type: Node
    - name: rbac
      type: RBAC
    - name: node-agent-authorizer
      type: Webhook
      webhook:
        authorizedTTL: 1ns
        connectionInfo:
          kubeConfigFile: /etc/kubernetes/structured/authorization-kubeconfigs/node-agent-authorizer-kubeconfig.yaml
          type: KubeConfigFile
        failurePolicy: Deny
        matchConditionSubjectAccessReviewVersion: v1
        matchConditions:
        - expression: '''gardener.cloud:node-agents'' in request.groups'
        subjectAccessReviewVersion: v1
        timeout: 10s
        unauthorizedTTL: 1ns
    - name: node-agent-authorizer
      type: Webhook
      webhook:
        authorizedTTL: 1ns
        connectionInfo:
          kubeConfigFile: /etc/kubernetes/structured/authorization-kubeconfigs/node-agent-authorizer-kubeconfig.yaml
          type: KubeConfigFile
        failurePolicy: Deny
        matchConditionSubjectAccessReviewVersion: v1
        matchConditions:
        - expression: '''gardener.cloud:node-agents'' in request.groups'
        subjectAccessReviewVersion: v1
        timeout: 10s
        unauthorizedTTL: 1ns
    kind: AuthorizationConfiguration
immutable: true
kind: ConfigMap
metadata:
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
  name: kube-apiserver-authorization-config-d8c48c47
  namespace: shoot--<...>
```

This leads to a crash-loop of kube-apiserver.

```
task "Waiting until Kubernetes API server rolled out" failed: retry failed with context deadline exceeded, last error: ReplicaSet "kube-apiserver-6bb864b687" has timed out progressing., logs of newest pod:
I0203 07:33:14.586279       1 flags.go:64] FLAG: --tls-private-key-file="/srv/kubernetes/apiserver/tls.key"
I0203 07:33:14.586314       1 flags.go:64] FLAG: --tls-sni-cert-key="[/srv/kubernetes/tls-sni/0/tls.crt,/srv/kubernetes/tls-sni/0/tls.key:api.shoot-domain]"
I0203 07:33:14.586326       1 flags.go:64] FLAG: --token-auth-file="/srv/kubernetes/token/static_tokens.csv"
I0203 07:33:14.586331       1 flags.go:64] FLAG: --tracing-config-file=""
I0203 07:33:14.586336       1 flags.go:64] FLAG: --v="2"
I0203 07:33:14.586342       1 flags.go:64] FLAG: --version="false"
I0203 07:33:14.586540       1 flags.go:64] FLAG: --vmodule=""
I0203 07:33:14.586551       1 flags.go:64] FLAG: --watch-cache="true"
I0203 07:33:14.586556       1 flags.go:64] FLAG: --watch-cache-sizes="[]"
E0203 07:33:14.592045       1 run.go:74] "command failed" err="authorizers[3].name: Duplicate value: \"node-agent-authorizer\""
```

The next reconciliation should fix the configuration, assuming the state of `gardener-resource-manager` does not flip over and over again.

The same could happen the other way round, if `gardener-resource-manager` is available first and then becomes unavailable. This leads to a missing configuration for the webhook.

**What you expected to happen**:
`node-agent-authorizer` webhook configuration should be added exactly one time.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.110.4
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area robustness
/kind bug

**What this PR does / why we need it**:
In the current implementation there is a race in `gardenlet` shoot reconciler which can lead to duplicate kube-apiserver config entry for `node-agent-authorizer` webhook.
This happens when `gardener-resource-manager` is temporary unavailable when a shoot reconciliation is starting and is healthy again before the reconciliation reaches the deployment step of kube-apiserver.

This issue is fixed in this PR. Additionally, controlplane migration flow and deletion flow are adapted that they use the same logic as the reconciliation flow.

**Which issue(s) this PR fixes**:
Fixes #11280 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
A bug which might lead to duplicate config entries for `node-agent-authorizer` webhook has been fixed.
```

### CODE REVIEW

**Review by marc1404 — COMMENTED** [review]
Thank you for fixing the issue! ⛔ 🐛 
The unification of the logic with the migration and deletion flow is a good change too.

/lgtm

File: pkg/gardenlet/operation/botanist/kubeapiserver.go [hunk 1]
```diff
@@ -156,7 +155,7 @@ func (b *Botanist) computeKubeAPIServerSNIConfig() kubeapiserver.SNIConfig {
 }
 
 // DeployKubeAPIServer deploys the Kubernetes API server.
-func (b *Botanist) DeployKubeAPIServer(ctx context.Context) error {
+func (b *Botanist) DeployKubeAPIServer(ctx context.Context, enableNodeAgentAuthorizer bool) error {
```
Comment (timuthy) [inline pkg/gardenlet/operation/botanist/kubeapiserver.go:158]: Could you enhance the [unit tests](https://github.com/gardener/gardener/blob/master/pkg/gardenlet/operation/botanist/kubeapiserver_test.go) for this case?

**Review by tobschli — COMMENTED** [review]
/lgtm

**Review by LucaBernstein — APPROVED** [review]
Thank you!
/lgtm
