### PR TITLE
Fixes restoration of multi-node etcds during control plane migration of HA `Shoot`s

### LINKED ISSUE #11525: [Flaky Test] `pull-gardener-e2e-kind-migration-ha-single-zone`: `Wait for Shoot to be deleted` stuck at `Scaling up etcd main and event`
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:

`pull-gardener-e2e-kind-migration-ha-single-zone` is flaking in step `Wait for Shoot to be deleted` because shoot deletion is stuck at `Scaling up etcd main and event`:

```
• [TIMEDOUT] [1200.002 seconds]
Shoot Tests Hibernated Shoot [It] Wait for Shoot to be deleted [Shoot, control-plane-migration, hibernated]
...
  2025-02-25T22:33:46.513Z	INFO	Waiting for deletion	{"shoot": {"name":"e2e-mgr-hib","namespace":"garden-local"}, "lastOperation": "&LastOperation{Description:Scaling up etcd main and event,LastUpdateTime:2025-02-25 22:33:36 +0000 UTC,Progress:14,State:Processing,Type:Delete,}"}
  [TIMEDOUT] in [It] - /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_migrate_delete.go:89 @ 02/25/25 22:34:16.242
  [FAILED] in [It] - /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/internal/shoot.go:136 @ 02/25/25 22:34:16.244
```

**CI link**:

- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11523/pull-gardener-e2e-kind-migration-ha-single-zone/1894505853755592704
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11503/pull-gardener-e2e-kind-migration-ha-single-zone/1894418081820708864
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11376/pull-gardener-e2e-kind-migration-ha-single-zone/1894411453910224896
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11536/pull-gardener-e2e-kind-migration-ha-single-zone/1894976654799802368

**Reason for failure**:

Related gardenlet logs:
```
2025-02-25T22:35:07.668606496Z stderr F {"level":"error","ts":"2025-02-25T22:35:07.668Z","msg":"Error","controller":"shoot","namespace":"garden-local","name":"e2e-mgr-hib","reconcileID":"a7fc017a-3e39-49a4-9127-8b15286f0710","operation":"delete","flow":"Shoot cluster deletion","task":"Scaling up etcd main and event","error":"retry failed with context deadline exceeded, last error: etcd object still has operation annotation set","stacktrace":"github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2\n\tgithub.com/gardener/gardener/pkg/utils/flow/flow.go:239"}
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
With https://github.com/gardener/gardener/pull/7626 support for migrating hibernated shoots with HA control planes was added. The special handling is necessary because to restore a clustered etcd the following steps have to be done:
1. Scale etcd from 0 to 1 replica to restore from backup
2. Scale etcd from 1 to 3 replicas to restore the etcd cluster
3. Scale etcd from 3 replicas back to 0 in https://github.com/gardener/gardener/blob/0f728f88f1fe3fe623437bfc545f0c221ee62387/pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go#L896-L901
4. Future scaling from 0 to 3 replicas (e.g. when cluster is woken up or deleted) work as expected

However, with https://github.com/gardener/gardener/pull/9462 the flow was changed slightly to speed up control plane migration by only scaling etcd to 3 replicas after the kube-apiserver is deployed. This scale-up was only done for non hibernated clusters. For control plane migration of hibernated clusters the flow was ended up like this:
1. Scale etcd from 0 to 1 replica to restore from backup
2. Scale etcd from 1 to 0 replicas in https://github.com/gardener/gardener/blob/0f728f88f1fe3fe623437bfc545f0c221ee62387/pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go#L896-L901
3. Future scaling from 0 to 3 replicas (e.g. when cluster is woken up or deleted) do not work as the etcd cluster was never restored and scale from 0 is not supported.

This PR modifies the restoration flow to ensure that steps occur in the same order as from https://github.com/gardener/gardener/pull/7626:
1. Scale etcd from 0 to 1 replica to restore from backup
2. Scale etcd from 1 to 3 replicas to restore the etcd cluster
3. Scale etcd from 3 replicas back to 0

This should also fix the flakiness of the `e2e-kind-migration-ha-single-zone` e2e test.

**Which issue(s) this PR fixes**:
Fixes #11525

**Special notes for your reviewer**:
Cheers to @rfranzke @LucaBernstein @shreyas-s-rao @unmarshall @ishan16696 for discovering and investigating this bug as part of the effort to deflake our e2e tests.

**Release note**:

```bugfix operator
Fixed a bug that caused multi-node etcd clusters to not be properly restored when performing control plane migration for hibernated HA `Shoot`s.
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go [hunk 1]
```diff
@@ -292,7 +293,7 @@ func (r *Reconciler) runReconcileShootFlow(ctx context.Context, o *operation.Ope
 		waitUntilEtcdReady = g.Add(flow.Task{
 			Name:         "Waiting until main and event etcd report readiness",
 			Fn:           botanist.WaitUntilEtcdsReady,
-			SkipIf:       o.Shoot.HibernationEnabled || skipReadiness,
+			SkipIf:       !isRestoringHAControlPlane && o.Shoot.HibernationEnabled || skipReadiness,
```
Comment (rfranzke) [inline pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go]: Can you add `()` here to make it more clear what the conditions are?

**Review by rfranzke — COMMENTED** [review]
/cc @LucaBernstein

**Review by LucaBernstein — COMMENTED** [review]
/lgtm
Thank you for looking into this issue further. 👍

**Review by rfranzke — COMMENTED** [review]
/approve

**Comment by rfranzke** [comment]
https://github.com/gardener/gardener/pull/11586#issuecomment-2703560835 :) 🚤
