### PR TITLE
Fix ManagedSeed update / deletion issue on soil clusters

### LINKED ISSUE #3890: Deletion of managed seeds fails
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:
I tried to delete a `seed` created by a `ManagedSeed` resource by deleting the `ManagedSeed` resource again. The seed itself gets deleted, but deletion of the `ManagedSeed` resource hangs with the error message
```
Could not unregister shoot garden/aws seed: could not delete gardenlet from shoot garden/aws: render error in "gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml": template: gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml:15:17: executing "gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml" at <required ".Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig is required" .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig>: error calling required: .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig is required
```

This happens independently of whether `ServiceAccount` or `BootstrapToken` is set in `spec.gardenlet.bootstrap` in the `ManagedSeed` resource manifest.

**What you expected to happen**:
Deletion of the `ManagedSeed` resource should delete the corresponding seed (which it does) and run through without errors (which it currently does not).

**How to reproduce it (as minimally and precisely as possible)**:
Create a `ManagedSeed` resource and then delete it again.

**Anything else we need to know?**:

**Environment**:

- Gardener version: `v1.20.3`
- Kubernetes version (use `kubectl version`): `1.18.6` (client) and `1.18.3` (cluster)
- Cloud provider or hardware configuration: AWS
- Others: landscape created with garden-setup

### LINKED ISSUE #4002: Shooted seed is not getting updated when updating soil seed (1.15.5 -> 1.18.1)
**How to categorize this issue?**
/area operations
/kind bug
/priority 3

**What happened**:
I updated my gardener landscape from 1.15.5 to 1.18.1 via [garden-setup](https://github.com/gardener/garden-setup).
I have a shooted seed `eval-euc-1` created via the [`use-as-seed` annotation](https://github.com/gardener/gardener/blob/77e09dd522d7bfb682cc35d0be437201b606061b/docs/usage/shooted_seed.md)

```
    shoot.gardener.cloud/use-as-seed: >-
      true,shootDefaults.pods=100.96.0.0/11,shootDefaults.services=100.64.0.0/13,disable-capacity-reservation,loadBalancerServices.annotations.service.beta.kubernetes.io/aws-load-balancer-internal="true",with-secret-ref,backup.provider=aws,backup.region=eu-central-1,backup.secretRef.name=aws-seed-evaluation,backup.secretRef.namespace=garden,featureGates.APIServerSNI=false,featureGates.ManagedIstio=false

```

The update of all the gardener components including the soil seed was properly performed but the shooted seed was not updated.

```
➜  workspace gardenctl kubectl get seeds
NAME         STATUS   PROVIDER   REGION         AGE     VERSION   K8S VERSION
eval-euc-1   Ready    aws        eu-central-1   13d     v1.15.5   v1.19.7
soil         Ready    aws        eu-central-1   13d     v1.18.1   v1.19.10
```

Furtermore the newly introduced managedseed object is also not getting registered properly:

```
➜  workspace gardenctl kubectl get managedseeds --all-namespaces
NAMESPACE   NAME         STATUS          SHOOT        GARDENLET   AGE
garden      eval-euc-1   NotRegistered   eval-euc-1   True        13d
```

Error message of the managedseed object:
```
Events:
  Type     Reason          Age                 From       Message
  ----     ------          ----                ----       -------
  Normal   Reconciling     11m (x861 over 9d)  gardenlet  Shoot garden/eval-euc-1 is reconciled
  Warning  ReconcileError  11m (x861 over 9d)  gardenlet  Could not register shoot garden/eval-euc-1 as seed: could not deploy gardenlet into shoot garden/eval-euc-1: render error in "gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml": template: gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml:15:17: executing "gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml" at <required ".Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig is required" .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig>: error calling required: .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig is required
```

**What you expected to happen**:
Once I update the soil seed the shooted seed is getting updated properly.
Furthermore I would expected that the newly introduced managed seed is getting registered properly.

**How to reproduce it (as minimally and precisely as possible)**:
- create a gardener landscape with gardener version 1.15.5 using garden-setup (version [3.4.0](https://github.com/gardener/garden-setup/releases/tag/3.4.0)
- create a shooted seed with the annotation posted above
- update gardener landscape with gardender version 1.18.1 using garden-setup (version [3.7.0](https://github.com/gardener/garden-setup/releases/tag/3.7.0)

**Anything else we need to know?**:
Slack conversation: https://kubernetes.slack.com/archives/CB57N0BFG/p1619125155320100?thread_ts=1619006099.311900&cid=CB57N0BFG
Just as a remark: I am aware that the garden-setup project is not intended to use for updates but this issue should not be caused by using garden-setup as the update is getting performed properly and the shooted seed is created separately from the infrastructure garden-setup is creating.

Furthermore: new shooted seeds are getting rolled out properly with version 1.18.1 but the managedseed object is not getting registered as well with the same error as shown above:

```
➜  workspace gardenctl kubectl get seeds
NAME         STATUS   PROVIDER   REGION         AGE     VERSION   K8S VERSION
eval-euc-1   Ready    aws        eu-central-1   13d     v1.15.5   v1.19.7
eval-usw-2   Ready    aws        us-west-2      2d10h   v1.18.1   v1.19.7
soil         Ready    aws        eu-central-1   13d     v1.18.1   v1.19.10
```

**Environment**:

- Gardener version: 1.15.5 -> 1.18.1
- Kubernetes version (use `kubectl version`): 1.19.7 and 1.19.10
- Cloud provider or hardware configuration: aws
- Others: let me know if you need some more context :)

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
Fixes the `ManagedSeed` update / deletion issue on soil clusters described in #3890, #4002.

**Which issue(s) this PR fixes**:
Fixes #3890
Fixes #4002

**Special notes for your reviewer**:

**Release note**:

```other operator
Fixed an issue that prevented the update and deletion of managed seeds on soil clusters.
```

### CODE REVIEW

**Comment by stoyanr** [comment]
/cc @timebertt 

@Diaphteiros I tested this locally, let's validate it on your test landscape as well before merging.

File: pkg/gardenlet/controller/managedseed/managedseed_valueshelper.go [hunk 1]
```diff
@@ -106,7 +106,11 @@ func (vp *valuesHelper) MergeGardenletConfiguration(config *configv1alpha1.Garde
 		return nil, err
 	}
 
-	// Delete seedClientConnection.kubeconfig and seedConfig in parent config values
+	// Delete gardenClientConnection.bootstrapKubeconfig, seedClientConnection.kubeconfig, and seedConfig in parent config values
+	parentConfigValues, err = utils.DeleteFromValuesMap(parentConfigValues, "gardenClientConnection", "bootstrapKubeconfig")
+	if err != nil {
+		return nil, err
+	}
```
Comment (ialidzhikov) [inline pkg/gardenlet/controller/managedseed/managedseed_valueshelper.go:113]: Can you please add unit tests?

**Review by ialidzhikov — APPROVED** [review]
/lgtm

for second opinion
/invite @timebertt

**Review by timebertt — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
@stoyanr , can you file cherry-picks against `release-v1.22`, `release-v1.21` and `release-v1.20` branches?
It would be nice to backport this fix as we had 2 issue reports for older versions (v1.20.x and v1.18.x)?

**Comment by stoyanr** [comment]
@ialidzhikov Done, see above. BTW, @Diaphteiros tested the fix on his local soil setup and confirmed that it works.
