### PR TITLE
Scale kube-apiserver after switching to node-agent-authorizer

### LINKED ISSUE #11396: gardenlet panics when deleting hibernated shoot if `NodeAgentAuthorizer` feature gate is enabled
**How to categorize this issue?**

/kind bug

**What happened**:

In [this test run](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11380/pull-gardener-e2e-kind-ipv6/1890333868502814720) of `pull-gardener-e2e-kind-ipv6`, gardenlet panicked:

```
gardenlet-6cb5b7b577-znxpj gardenlet panic: runtime error: invalid memory address or nil pointer dereference
gardenlet-6cb5b7b577-znxpj gardenlet [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1ead204]
gardenlet-6cb5b7b577-znxpj gardenlet
gardenlet-6cb5b7b577-znxpj gardenlet goroutine 53910 [running]:
gardenlet-6cb5b7b577-znxpj gardenlet github.com/gardener/gardener/pkg/gardenlet/operation/botanist.(*Botanist).CleanWebhooks(0x400064cb68, {0x32ce2e8, 0x4000640930})
gardenlet-6cb5b7b577-znxpj gardenlet 	github.com/gardener/gardener/pkg/gardenlet/operation/botanist/cleanup.go:151 +0x34
gardenlet-6cb5b7b577-znxpj gardenlet github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot.(*Reconciler).runDeleteShootFlow.TaskFn.Timeout.func60({0x32ce240?, 0x40032f6300?})
gardenlet-6cb5b7b577-znxpj gardenlet 	github.com/gardener/gardener/pkg/utils/flow/taskfn.go:35 +0x54
gardenlet-6cb5b7b577-znxpj gardenlet github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2()
gardenlet-6cb5b7b577-znxpj gardenlet 	github.com/gardener/gardener/pkg/utils/flow/flow.go:234 +0x11c
gardenlet-6cb5b7b577-znxpj gardenlet created by github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode in goroutine 1016
gardenlet-6cb5b7b577-znxpj gardenlet 	github.com/gardener/gardener/pkg/utils/flow/flow.go:231 +0x4d8
```

Judging by the previous log, this happened in the `Cleaning up webhooks` step for shoot `e2e-hib-wl`.

**What you expected to happen**:

gardenlet should not panic.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy gardenlet with `NodeAgentAuthorizer` feature gate enabled (enabled in the local setup by default).
2. Create a hibernated shoot (workerless or non-workerless).
3. Delete the shoot.
4. Observe the gardenlet panic in the first deletion attempt.
5. After a gardenlet restart, the second deletion attempt succeeds.

**Anything else we need to know?**:

https://github.com/gardener/gardener/pull/11281 added a second `DeployKubeAPIServer` task in case the `NodeAgentAuthorizer` feature gate is enabled.
When deleting a hibernated shoot, the `Deploying Kubernetes API server` task deploys the API server with 0 replicas, then `Scaling up Kubernetes API server` task scales it up to 1 replica, and then the `Deploying Kubernetes API server with node-agent-authorizer` task scales it back to 0 replicas after deploying gardener-resource-manager.

This causes a panic when accessing `b.ShootClientSet.Client()` in `Botanist.CleanWebhooks`, because the `InitializeDesiredShootClients` has previously skipped the initialization if the API server has 0 replicas.

On the second deletion attempt, the `Deploying Kubernetes API server` task deploys the API server with 0 replica and then `Scaling up Kubernetes API server` task scales it up to 1 replica again. However, the `Deploying Kubernetes API server with node-agent-authorizer` task is skipped now, because the gardener-resource-manager is already available (after the first deletion attempt).
In this case, the client initialization is successful and the cleanup tasks succeed as well.

cc @oliver-goetz 

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by Wieneo**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR adds a scale-up step for the kube-apiserver after the node-agent-authorizer was deployed.
This is needed as otherwise the step "deployKubeAPIServerWithNodeAgentAuthorizer" scales the kube-apiserver back to 0, when the shoot is hibernated, which breaks steps that need the ShootClientSet (as it will be uninitialized).

For a more detailed description, see https://github.com/gardener/gardener/issues/11396

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/11396

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fixed a bug that caused the Gardenlet to crash when deleting a hibernated shoot if the NodeAgentAuthorizer feature gate was enabled
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go [hunk 1]
```diff
@@ -316,11 +316,21 @@ func (r *Reconciler) runDeleteShootFlow(ctx context.Context, o *operation.Operat
...
 			Dependencies: flow.NewTaskIDs(waitUntilGardenerResourceManagerReady),
 		})
+		// if the shoot is hibernated, the step "deployKubeAPIServerWithNodeAgentAuthorizer" scales the kube-apiserver back to 0,
+		//   which breaks steps that need the ShootClientSet (as it will be uninitialized)
+		//
+		// scale the kube-apiserver server back up, just like the first time we deploy it
+		scaleUpKubeAPIServerWithNodeAgentAuthorizer = g.Add(flow.Task{
+			Name:         "Scaling up Kubernetes API server with node-agent-authorizer",
+			Fn:           flow.TaskFn(botanist.ScaleKubeAPIServerToOne).RetryUntilTimeout(defaultInterval, defaultTimeout),
+			SkipIf:       !cleanupShootResources || kubeAPIServerDeploymentReplicas != 0,
```
Comment (timebertt) [inline pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go]: I believe this task should have the same `SkipIf` conditions as the previous task.

**Review by timebertt — CHANGES_REQUESTED** [review]

File: pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go (hunk 1 above)
Comment (Wieneo) [reply pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go]: good spot!
Didn't break anything in my tests but I will align it with the other steps 😊

**Review by timebertt — COMMENTED** [review]
Thanks!
/lgtm
but waiting for more feedback

**Review by oliver-goetz — COMMENTED** [review]
Couldn't we add something like 
```
b.Shoot.Components.ControlPlane.KubeAPIServer.SetAutoscalingReplicas(ptr.To[int32](1))
```
to [`ScaleKubeAPIServerToOne`](https://github.com/gardener/gardener/blob/a691df2cc583920c0d30ec486bfd6a0e87640b9a/pkg/gardenlet/operation/botanist/kubeapiserver.go#L329) instead?

It feels a bit strange if kube-apiserver is scaled up and a subsequent deployment implicitly scales it down again.
Additionally, we could avoid to scale kube-apiserver up, down and up again.

**Comment by Wieneo** [comment]
@oliver-goetz 
tested your recommendation locally and it seemed to work fine 👍 

I've updated this PR

**Comment by oliver-goetz** [comment]
Awesome, thanks 😄 

/lgtm

**Review by timebertt — APPROVED** [review]
Also a nice solution. Thanks for the suggestion @oliver-goetz :)
