### PR TITLE
Fix regex for service discovery of vpn-seedserver.

### LINKED ISSUE #9958: `Reversed VPN OpenVPN Server (HA)` and `Reversed VPN Envoy Proxy` dashboards show no data
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:
Screenshot 2024-06-11 at 17 17 34

Screenshot 2024-06-11 at 17 18 18

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an HA cluster
2. Make sure that the `Reversed VPN OpenVPN Server (HA)` dashboards don't show any data

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.96.3
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by axel7born**
**How to categorize this PR?**

/area networking
/kind bug

**What this PR does / why we need it**:
Fixes a regex in the scrape config for vpn-seed-server for HA case.
The dashboard `Reversed VPN Envoy Proxy` will not be deployed in the HA case.
**Which issue(s) this PR fixes**:
Fixes #9958

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fix a bug where the Reversed VPN OpenVPN Server (HA) doesn't display any data.
```

### CODE REVIEW

File: pkg/component/networking/vpn/seedserver/seedserver.go [hunk 1]
```diff
@@ -758,7 +758,7 @@ func (v *vpnSeedServer) deployScrapeConfig(ctx context.Context) error {
 	)
 
 	if v.values.HighAvailabilityEnabled {
-		jobName, serviceNameRegexSuffix = "openvpn-server-exporter", "[0-2]"
+		jobName, serviceNameRegexSuffix = "openvpn-server-exporter", "-[0,1]"
```
Comment (ScheererJ) [inline pkg/component/networking/vpn/seedserver/seedserver.go]: Great catch to find the missing `-`.

Please leave the range as is, though. @MartinWeindel intentionally made it bigger so that it would be easier to have a larger `StatefulSet` if required.

@MartinWeindel WDYT?

File: pkg/component/observability/plutono/plutono.go [hunk 2]
```diff
@@ -425,6 +425,9 @@ func (p *plutono) getDashboardConfigMap(ctx context.Context, suffix string) (*co
 			if !p.values.VPNHighAvailabilityEnabled {
 				ignorePaths.Insert("ha-vpn")
 			}
+			if p.values.VPNHighAvailabilityEnabled {
+				ignorePaths.Insert("envoy-proxy")
+			}
```
Comment (ScheererJ) [inline pkg/component/observability/plutono/plutono.go]: Why not simply use an `else` block if the inverse condition is already checked above?

**Review by ScheererJ — COMMENTED** [review]
Thanks for looking into the broken HA VPN dashboards.

File: pkg/component/observability/plutono/plutono.go [hunk 3]
```diff
@@ -422,7 +422,9 @@ func (p *plutono) getDashboardConfigMap(ctx context.Context, suffix string) (*co
 			if !p.values.IncludeIstioDashboards {
 				ignorePaths.Insert("istio")
 			}
-			if !p.values.VPNHighAvailabilityEnabled {
+			if p.values.VPNHighAvailabilityEnabled {
+				ignorePaths.Insert("envoy-proxy")
```
Comment (acumino) [inline pkg/component/observability/plutono/plutono.go:426]: ignorePath ignores the respective directory to not include for deployment, you should create a new folder called `envoy-proxy` and keep `envoy-proxy-dashboard.json` in that, for below logic to work.
```
				ignorePaths.Insert("envoy-proxy")
```

**Review by acumino — CHANGES_REQUESTED** [review]

File: pkg/component/observability/plutono/plutono.go (hunk 3 above)
Comment (axel7born) [reply pkg/component/observability/plutono/plutono.go:426]: I've done that. 
Github shows it as as `File renamed without changes`.

Comment (ScheererJ) [reply pkg/component/observability/plutono/plutono.go:426]: https://github.com/gardener/gardener/pull/10035/commits/c23b2b770e262f680bef24916b14a42324efb524

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve

**Review by DockToFuture — APPROVED** [review]
/lgtm
