### PR TITLE
Use Addon Resizer for scaling the Metrics Server

### LINKED ISSUE #4018: Use non-VPA/HPA autoscaling for metrics-server
**How to categorize this issue?**

/area control-plane auto-scaling
/kind enhancement
/priority 2

**What would you like to be added**:

Use non-VPA/HPA autoscaling for metrics-server

**Why is this needed**:

We are using VPA to scale `metrics-server`. But VPA relies on metrics API to recommend scaling. If for any reason `metrics-server` goes into a `CrashloopBackoff`, then metrics API also will be down and VPA will be powerless to scale up the `metrics-server`.

We should avoid this cycling dependency by using something like the [addon-resizer](https://github.com/kubernetes/autoscaler/blob/master/addon-resizer/README.md#addon-resizer) or the [cluster-proportiona-autoscaler](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler) both of which scales based on the number nodes rather than resource usage metrics.

### PR DESCRIPTION
**Pull request by harishmanasa**
**What this PR does / why we need it**:
Instead of using VPA to scale the metrics server, addon resizer is used. This is necessary to remove the circular dependency that exists between the metrics server and the VPA.

**Which issue(s) this PR fixes**:
[This](https://github.com/gardener/gardener/issues/4018) is the issue addressed [Fixes #4018]

**Special notes for your reviewer**:
As the GRM was reverting the recommendations by the addon resizer, it has been enhanced to include annotations from the metrics server. So, this can be merged once the [GRM ](https://github.com/gardener/gardener-resource-manager/pull/122)is tested.

**Release note**:
NONE

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @harishmanasa for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by amshuman-kr — CHANGES_REQUESTED** [review]
@harishmanasa Can you please squash all the commits? They are too granular.

**Comment by amshuman-kr** [comment]
@harishmanasa Can you please link #4018 in the _Which issue(s) this PR fixes_ section according to the PR template? Unfortunately, I do not have the rights to edit the PR description.

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 1]
```diff
@@ -262,6 +266,9 @@ func (m *metricsServer) computeResourcesData() (map[string][]byte, error) {
 					managedresources.LabelKeyOrigin: managedresources.LabelValueGardener,
 					v1beta1constants.GardenRole:     v1beta1constants.GardenRoleSystemComponent,
 				}),
+				Annotations: map[string]string{
+					"gardener-resource-manager.gardener.cloud/preserveResources": "true",
```
Comment (rfranzke) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]: Can you use an exported constant from the `github.com/gardener/gardener-resource-manager` repository instead?

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 2]
```diff
@@ -358,6 +365,47 @@ func (m *metricsServer) computeResourcesData() (map[string][]byte, error) {
 								Name:      volumeMountNameServer,
 								MountPath: volumeMountPathServer,
 							}},
+						}, {
+							Name:            sideCarName,
+							Image:           "k8s.gcr.io/addon-resizer:1.8.11",
```
Comment (rfranzke) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]: Please don't hard-code the image here - use the image vector like it is done for all other images.

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 3]
```diff
@@ -382,37 +428,6 @@ func (m *metricsServer) computeResourcesData() (map[string][]byte, error) {
...
-							MinAllowed: corev1.ResourceList{
-								corev1.ResourceCPU:    resource.MustParse("50m"),
-								corev1.ResourceMemory: resource.MustParse("150Mi"),
-							},
-						},
-					},
-				},
-			},
-		}
-	}
```
Comment (rfranzke) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go:414]: You would need to pro-actively delete the VPA object (it will still exist in the system for existing shoot clusters).

**Review by rfranzke — CHANGES_REQUESTED** [review]
Also, please adapt the unit tests.

File: pkg/operation/botanist/component/metricsserver/metrics_server.go (hunk 3 above)
Comment (amshuman-kr) [reply pkg/operation/botanist/component/metricsserver/metrics_server.go:414]: @rfranzke Wouldn't the old resources be [cleaned up](https://github.com/gardener/gardener-resource-manager/blob/4d38c292feea2ad3d653f824ea659fb81bded192/pkg/controller/managedresource/reconciler.go#L284) by GRM?

Comment (rfranzke) [reply pkg/operation/botanist/component/metricsserver/metrics_server.go:414]: Yes, true, please ignore above comment

File: pkg/operation/botanist/component/metricsserver/metrics_server_test.go [hunk 4]
```diff
@@ -101,27 +102,27 @@ spec:
...
+		//         cpu: 50m
+		//         memory: 150Mi
+		//   targetRef:
+		//     apiVersion: apps/v1
+		//     kind: Deployment
+		//     name: metrics-server
+		//   updatePolicy:
+		//     updateMode: Auto
+		// status: {}
+		// `
```
Comment (amshuman-kr) [inline pkg/operation/botanist/component/metricsserver/metrics_server_test.go]:
```suggestion
```
Could you please delete the commented lines?

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 5]
```diff
@@ -423,7 +441,7 @@ func (m *metricsServer) computeResourcesData() (map[string][]byte, error) {
 		service,
 		apiService,
 		deployment,
-		vpa,
+		// vpa,
```
Comment (amshuman-kr) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]:
```suggestion
```
Could you please delete the commented lines?

File: pkg/operation/botanist/component/metricsserver/metrics_server_test.go [hunk 6]
```diff
@@ -271,6 +272,35 @@ spec:
...
+          - /pod_nanny
+          - --cpu=20m
+          - --extra-cpu=1m
+          - --memory=15Mi
+          - --extra-memory=2Mi
+          - --threshold=5
+          - --deployment=metrics-server
+          - --container=metrics-server
+          - --poll-period=300000
+          - --use-metrics=true
```
Comment (amshuman-kr) [inline pkg/operation/botanist/component/metricsserver/metrics_server_test.go]:
```suggestion
          - --use-metrics=false
```
Shouldn't this be `false` if it is `false` in `metrics_server.go`?

File: pkg/operation/botanist/component/metricsserver/metrics_server_test.go [hunk 7]
```diff
@@ -364,6 +394,35 @@ spec:
...
```
Comment (amshuman-kr) [inline pkg/operation/botanist/component/metricsserver/metrics_server_test.go]: Same as [above](https://github.com/gardener/gardener/pull/4216/files#diff-30c0460eedf4444226edf21dfeb1b8ffbe759e30107789bb04addab8334da4aaR303)

File: pkg/operation/botanist/component/metricsserver/metrics_server_test.go [hunk 8]
```diff
@@ -486,11 +545,11 @@ status: {}
 			})
 
 			It("should successfully deploy all resources (w/ VPA, w/ host env)", func() {
-				metricsServer = New(c, namespace, image, true, &kubeAPIServerHost)
+				metricsServer = New(c, namespace, image, true, &kubeAPIServerHost, sideCar)
 				metricsServer.SetSecrets(secrets)
 
 				managedResourceSecret.Data["deployment__kube-system__metrics-server.yaml"] = []byte(deploymentYAMLWithHostEnv)
-				managedResourceSecret.Data["verticalpodautoscaler__kube-system__metrics-server.yaml"] = []byte(vpaYAML)
+				// managedResourceSecret.Data["verticalpodautoscaler__kube-system__metrics-server.yaml"] = []byte(vpaYAML)
```
Comment (amshuman-kr) [inline pkg/operation/botanist/component/metricsserver/metrics_server_test.go]:
```suggestion
```
Could you please delete the commented lines?

**Review by amshuman-kr — COMMENTED** [review]
Thanks for the change @harishmanasa. Some small changes below.

Could you please squash the commits?

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 9]
```diff
@@ -52,6 +50,7 @@ const (
 	serviceName        = "metrics-server"
 	serviceAccountName = "metrics-server"
 	containerName      = "metrics-server"
+	sideCarName        = "metrics-server-nanny"
```
Comment (ialidzhikov) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]:
```suggestion
	addonResizerName   = "metrics-server-nanny"
```

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 10]
```diff
@@ -76,13 +75,15 @@ func New(
 	image string,
 	vpaEnabled bool,
 	kubeAPIServerHost *string,
+	sideCar string,
```
Comment (ialidzhikov) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]: You can give better name.

```suggestion
	addonResizerImage string,
```

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 11]
```diff
@@ -92,8 +93,8 @@ type metricsServer struct {
 	image             string
 	vpaEnabled        bool
```
Comment (ialidzhikov) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]: With the new approach the `vpaEnabled` seems to be no longer used. You can clean it up.

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 12]
```diff
@@ -262,6 +268,9 @@ func (m *metricsServer) computeResourcesData() (map[string][]byte, error) {
 					managedresources.LabelKeyOrigin: managedresources.LabelValueGardener,
 					v1beta1constants.GardenRole:     v1beta1constants.GardenRoleSystemComponent,
 				}),
+				Annotations: map[string]string{
+					resourcesv1alpha1.PreserveResources: true,
```
Comment (ialidzhikov) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]:
```
$ make install
> Install
# github.com/gardener/gardener/pkg/operation/botanist/component/metricsserver
pkg/operation/botanist/component/metricsserver/metrics_server.go:272:6: undefined: "github.com/gardener/gardener-resource-manager/pkg/apis/resources/v1alpha1".PreserveResources
pkg/operation/botanist/component/metricsserver/metrics_server.go:272:23: cannot use true (type untyped bool) as type string in map value
make: *** [install] Error 2
```

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 13]
```diff
@@ -358,6 +367,48 @@ func (m *metricsServer) computeResourcesData() (map[string][]byte, error) {
 								Name:      volumeMountNameServer,
 								MountPath: volumeMountPathServer,
 							}},
+						}, {
+							Name:            sideCarName,
+							Image:           m.sideCar,
```
Comment (ialidzhikov) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]:
```suggestion
							Image:           m.addonResizerImage,
```

**Review by ialidzhikov — DISMISSED** [review]
A release note in the PR description is missing.
If this PR is targeting to close https://github.com/gardener/gardener/issues/4018, then update the PR description with `Fixes #4018`.

File: pkg/operation/botanist/component/metricsserver/metrics_server.go (hunk 12 above)
Comment (rfranzke) [reply pkg/operation/botanist/component/metricsserver/metrics_server.go]: I guess we need a new release (and revendoring afterwards) of `github.com/gardener/gardener-resource-manager`, right?

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 14]
```diff
@@ -358,6 +364,48 @@ func (m *metricsServer) computeResourcesData() (map[string][]byte, error) {
...
+							Image:           m.addonResizerImage,
+							ImagePullPolicy: corev1.PullIfNotPresent,
+							Command: []string{
+								"/pod_nanny",
+								"--cpu=20m",
+								"--extra-cpu=1m",
+								"--memory=15Mi",
+								"--extra-memory=2Mi",
+								"--threshold=5",
+								"--deployment=metrics-server",
```
Comment (rfranzke) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]: Use https://github.com/gardener/gardener/blob/48883df339a261e60fe8ab8463fff17c45d27273/pkg/operation/botanist/component/metricsserver/metrics_server.go#L51

File: pkg/operation/botanist/component/metricsserver/metrics_server.go [hunk 15]
```diff
@@ -358,6 +364,48 @@ func (m *metricsServer) computeResourcesData() (map[string][]byte, error) {
...
+								"--container=metrics-server",
```
Comment (rfranzke) [inline pkg/operation/botanist/component/metricsserver/metrics_server.go]: Use https://github.com/gardener/gardener/blob/48883df339a261e60fe8ab8463fff17c45d27273/pkg/operation/botanist/component/metricsserver/metrics_server.go#L54

**Comment by amshuman-kr** [comment]
> I guess we need a new release (and revendoring afterwards) of github.com/gardener/gardener-resource-manager, right?

Yes. I and @ashwani2k gave it a try yesterday based on the head commit on GRM master branch. But it proved tricky. The use of api module doesn't fully mitigate the circular dependency between GRM and gardener (gardener is importing `pkg/health` from GRM). And GRM doesn't build with latest gardener revendored because of some breaking changes in a couple of functions (in gardener and controller-runtime).

**Comment by ashwani2k** [comment]
Currently the GRM is working with `github.com/gardener/gardener v1.17.1-0.20210223090907-928a806b2a30` 
To be of some help to @amshuman-kr, I tried to update the gardener version to  v1.26.0 in GRM and resolve the install issues. 

`make install` failed with errors due identify
``` 
        k8s.io/api/batch/v2alpha1: module k8s.io/api@latest found (v0.21.2), but does not contain package k8s.io/api/batch/v2alpha1
        k8s.io/api/discovery/v1alpha1: module k8s.io/api@latest found (v0.21.2), but does not contain package k8s.io/api/discovery/v1alpha1
        k8s.io/api/settings/v1alpha1: module k8s.io/api@latest found (v0.21.2), but does not contain package k8s.io/api/settings/v1alpha1
make: *** [revendor] Error 1 
```
This was fixed  by replacing the client-go from v0.19.6 to v0.21.2 in go.mod
```
replace (
	github.com/gardener/gardener-resource-manager/api => ./api
	k8s.io/client-go => k8s.io/client-go v0.21.2 -
)
``` 

The make install was failing now still with more errors now but just to highlight - 
1. Manager unable to create a client using NewClientBuilder interface. 
```
 # github.com/gardener/gardener-resource-manager/pkg/cmd
pkg/cmd/target.go:183:9: undefined: manager.NewClientBuilder
``` 
This is happening because the controller-runtime used earlier was v0.7.1 which is now upgraded to v0.9.1. 
With 0.9.1  NewClientBuilder interface is deprecated with  [:warning: Allow setting NewClientFunc w/o implementing an interface](https://github.com/kubernetes-sigs/controller-runtime/pull/1409). 

This change is already adapted by Gardener a month back with [Upgrade sigs.k8s.io/controller-runtime to v0.9, k8s.io/\* to v0.21](https://github.com/gardener/gardener/issues/4174). 
Looking at the PR's raised for the issue the change didn't look trivial. 

2. The other big change we saw was with the health.go with signature mismatch with cascading effects in other invocations and test-suites as well. 
```
pkg/health/health.go:279:44: not enough arguments in call to “github.com/gardener/gardener/pkg/utils/kubernetes”.FetchEventMessages
        have (context.Context, client.Client, *“k8s.io/api/core/v1".Service, string, number)
        want (context.Context, *“k8s.io/apimachinery/pkg/runtime”.Scheme, client.Reader,
```
Given the context it looked like vendoring GRM to latest g/g didn't seem trivial and required more context then we had. wdyt?

**Comment by timebertt** [comment]
> I guess we need a new release (and revendoring afterwards) of github.com/gardener/gardener-resource-manager, right?

Yes. Let's put this PR back in draft until we have a new release including https://github.com/gardener/gardener-resource-manager/pull/122.


> Yes. I and @ashwani2k gave it a try yesterday based on the head commit on GRM master branch. But it proved tricky. The use of api module doesn't fully mitigate the circular dependency between GRM and gardener (gardener is importing `pkg/health` from GRM). And GRM doesn't build with latest gardener revendored because of some breaking changes in a couple of functions (in gardener and controller-runtime).

Yeah, I also stumbled upon this a week ago and recognized that this will hurt us somewhen soon. I was thinking about getting rid of the dependency towards `grm/pkg/manager` in `g/g` and moving the (anyways not too helpful) helper funcs that we use into `g/pkg/utils/managedresources`.

For now, we should revendor g/g, k/* and ks/cr in g/grm and then we should be able to cut a new release in g/grm, that we can vendor in g/g (I think).

**Comment by rfranzke** [comment]
FYI: I'm looking into revendoring g/grm.

**Comment by rfranzke** [comment]
Here is the PR: https://github.com/gardener/gardener-resource-manager/pull/126

**Comment by rfranzke** [comment]
After https://github.com/gardener/gardener-resource-manager/pull/127 is merged (hopefully tomorrow), I'll open a PR for g/g to update the image + revendor the latest version. Afterwards, you can rebase your PR on top of it and then we should be able to merge it.

**Comment by rfranzke** [comment]
https://github.com/gardener/gardener/pull/4373 was merged yesterday, kindly
/rebase
your PR on `master` and mark it as "ready for review" afterwards so that we can get it in.
/unhold

**Review by rfranzke — DISMISSED** [review]
/ready
/lgtm

**Review by amshuman-kr — DISMISSED** [review]
Thanks @rfranzke for the rebase! /lgtm

**Review by amshuman-kr — APPROVED** [review]

**Review by rfranzke — APPROVED** [review]
