### PR TITLE
Drop `operation.*CheckSum` functions

### LINKED ISSUE #5865: Shoot fails to be reconciled with error `missing DH secret information`
/area control-plane
/kind bug
/kind regression

**What happened**:
See below.

**What you expected to happen**:
Existing Shoot to be reconciled successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with gardener/gardener@v1.45.0

2. Update to gardener/gardener@v1.46.0-dev-052739856f9f90110d81c97791ee0bf4d9fcf434

3. Reconcile the existing Shoot

4. Make sure that the reconciliation fails with:
```yaml
  lastErrors:
    - description: >-
        task "Deploying vpn-seed-server" failed: retry failed with context
        deadline exceeded, last error: missing DH secret information
      taskID: Deploying vpn-seed-server
      lastUpdateTime: '2022-04-27T14:40:16Z'
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: 052739856f9f90110d81c97791ee0bf4d9fcf434
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind bug

**What this PR does / why we need it**:
This PR drops the `operation.*CheckSum` functions since the `operation.checkSums` map is no longer used after #5790.

**Which issue(s) this PR fixes**:
Fixes #5865

**Special notes for your reviewer**:
/cc @ialidzhikov 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/operation/botanist/vpnseedserver.go [hunk 1]
```diff
@@ -27,24 +27,37 @@ import (
...
 func init() {
-	diffieHellmanKeyChecksum = utils.ComputeChecksum(map[string][]byte{"dh2048.pem": []byte(DefaultDiffieHellmanKey)})
+	diffieHellmanKeyChecksum = utils.ComputeChecksum(diffieHellmanKeyData)
+}
+
+func (b *Botanist) getDiffieHellmanSecret() component.Secret {
+	data, checksum := diffieHellmanKeyData, diffieHellmanKeyChecksum
+	if secret := b.LoadSecret(v1beta1constants.GardenRoleOpenVPNDiffieHellman); secret != nil {
+		data, checksum = secret.Data, utils.ComputeSecretChecksum(secret.Data)
+	}
```
Comment (ialidzhikov) [inline pkg/operation/botanist/vpnseedserver.go:54]: Will this work? I don't see `StoreSecret` being called anywhere. If I am not missing something, similar `LoadSecret` call will always return `nil`.

File: pkg/operation/botanist/vpnseedserver.go [hunk 2]
```diff
@@ -27,24 +27,37 @@ import (
...
-
 // init calculates the checksum of the default diffie hellman key
 func init() {
-	diffieHellmanKeyChecksum = utils.ComputeChecksum(map[string][]byte{"dh2048.pem": []byte(DefaultDiffieHellmanKey)})
+	diffieHellmanKeyChecksum = utils.ComputeChecksum(diffieHellmanKeyData)
+}
+
+func (b *Botanist) getDiffieHellmanSecret() component.Secret {
+	data, checksum := diffieHellmanKeyData, diffieHellmanKeyChecksum
+	if secret := b.LoadSecret(v1beta1constants.GardenRoleOpenVPNDiffieHellman); secret != nil {
```
Comment (ialidzhikov) [inline pkg/operation/botanist/vpnseedserver.go:52]: We also have other `LoadSecret` usages.

https://github.com/gardener/gardener/blob/8aba4c3d091c37caea38e71ca37409d55040af72/pkg/operation/botanist/botanist.go#L69

https://github.com/gardener/gardener/blob/8aba4c3d091c37caea38e71ca37409d55040af72/pkg/operation/botanist/monitoring.go#L317

https://github.com/gardener/gardener/blob/8aba4c3d091c37caea38e71ca37409d55040af72/pkg/operation/botanist/monitoring.go#L390

https://github.com/gardener/gardener/blob/8aba4c3d091c37caea38e71ca37409d55040af72/pkg/operation/botanist/monitoring.go#L551

Don't they need fixing as well?

File: pkg/operation/botanist/vpnseedserver.go (hunk 1 above)
Comment (ialidzhikov) [reply pkg/operation/botanist/vpnseedserver.go:54]: Ah, okay. Looks like the `secrets` field is set when the operation is build:

https://github.com/gardener/gardener/blob/8aba4c3d091c37caea38e71ca37409d55040af72/pkg/operation/operation.go#L231-L235

And `gardenSecrets` are passed when new operation is created:

https://github.com/gardener/gardener/blob/8aba4c3d091c37caea38e71ca37409d55040af72/pkg/gardenlet/controller/shoot/shoot_control.go#L350

File: pkg/operation/botanist/vpnseedserver.go (hunk 2 above)
Comment (rfranzke) [reply pkg/operation/botanist/vpnseedserver.go:52]: `LoadSecret` should be fine as you outlined in https://github.com/gardener/gardener/pull/5866#discussion_r860005126, just the `*CheckSum` functions were problematic and are fixed in this PR

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Review by ialidzhikov — COMMENTED** [review]
/approve
