### PR TITLE
Fix debootstrap of Seed

### LINKED ISSUE #3676: Debootstrap of Seed no longer works
**How to categorize this issue?**

/kind regression
/priority normal

**What happened**:

Debootstrap of Seed fails with:

```
time="2021-03-08T13:04:55+02:00" level=error msg="cannot use OptimisticLock, from object \"&Secret{ObjectMeta:{seed-azure-local  garden    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,}\" does not have any resource version we can use" seed=seed-local-azure
time="2021-03-08T13:04:58+02:00" level=info msg="[SEED RECONCILE] seed-local-aws" seed=seed-local-aws
time="2021-03-08T13:05:10+02:00" level=info msg="No Shoots, ControllerInstallations or BackupBuckets are referencing the Seed. Deletion accepted." seed=seed-local-azure
time="2021-03-08T13:05:11+02:00" level=error msg="cannot use OptimisticLock, from object \"&Secret{ObjectMeta:{seed-azure-local  garden    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,}\" does not have any resource version we can use" seed=seed-local-azure
time="2021-03-08T13:05:26+02:00" level=info msg="No Shoots, ControllerInstallations or BackupBuckets are referencing the Seed. Deletion accepted." seed=seed-local-azure
time="2021-03-08T13:05:27+02:00" level=error msg="cannot use OptimisticLock, from object \"&Secret{ObjectMeta:{seed-azure-local  garden    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,}\" does not have any resource version we can use" seed=seed-local-azure
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Seed
2. Delete a Seed

3. Make sure that the debootstrap fails with:

```
time="2021-03-08T13:06:16+02:00" level=error msg="cannot use OptimisticLock, from object \"&Secret{ObjectMeta:{seed-azure-local  garden    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,}\" does not have any resource version we can use" seed=seed-local-azure
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
/kind bug
/kind regression

Fixes https://github.com/gardener/gardener/issues/3676

**Release note**:

```bugfix operator
An issue causing gardenlet to fail to remove the finalizer of the Seed Secret (`.spec.secretRef`) is now fixed.
```

### CODE REVIEW

File: pkg/gardenlet/controller/seed/seed_control.go [hunk 1]
```diff
@@ -266,14 +266,19 @@ func (c *defaultControl) ReconcileSeed(obj *gardencorev1beta1.Seed, key string)
...
 					},
 				}
-				if err := controllerutils.PatchRemoveFinalizers(ctx, gardenClient.Client(), secret, gardencorev1beta1.ExternalGardenerName); err != nil {
-					seedLogger.Error(err.Error())
-					return err
+				err = gardenClient.Client().Get(ctx, client.ObjectKeyFromObject(secret), secret)
+				if err == nil {
+					if err2 := controllerutils.PatchRemoveFinalizers(ctx, gardenClient.Client(), secret, gardencorev1beta1.ExternalGardenerName); err2 != nil {
+						seedLogger.Error(err.Error())
+						return fmt.Errorf("failed to remove finalizer from Seed secret '%s/%s': %w", seed.Spec.SecretRef.Namespace, seed.Spec.SecretRef.Name, err2)
```
Comment (vpnachev) [inline pkg/gardenlet/controller/seed/seed_control.go]:
```suggestion
					if err2 := controllerutils.PatchRemoveFinalizers(ctx, gardenClient.Client(), secret, gardencorev1beta1.ExternalGardenerName); err2 != nil {
						seedLogger.Error(err2.Error())
						return fmt.Errorf("failed to remove finalizer from Seed secret '%s/%s': %w", seed.Spec.SecretRef.Namespace, seed.Spec.SecretRef.Name, err2)
```



PS. You can simply rename `err2` to `err` -> it will be new variable inside the local scope.
```suggestion
					if err := controllerutils.PatchRemoveFinalizers(ctx, gardenClient.Client(), secret, gardencorev1beta1.ExternalGardenerName); err != nil {
						seedLogger.Error(err.Error())
						return fmt.Errorf("failed to remove finalizer from Seed secret '%s/%s': %w", seed.Spec.SecretRef.Namespace, seed.Spec.SecretRef.Name, err)
```

**Review by vpnachev — CHANGES_REQUESTED** [review]

File: pkg/gardenlet/controller/seed/seed_control.go (hunk 1 above)
Comment (ialidzhikov) [reply pkg/gardenlet/controller/seed/seed_control.go]: Thanks for the catch!

**Review by vpnachev — DISMISSED** [review]
/lgtm

**Review by rfranzke — DISMISSED** [review]

**Comment by ialidzhikov** [comment]
/hold

I see more wrong usage of `PatchRemoveFinalizers` after https://github.com/gardener/gardener/commit/7f0ae078d09fe5927d01a4df0821c2bf0d98332a

**Review by vpnachev — APPROVED** [review]
/lgtm
