### PR TITLE
Enhance etcd deploy flow to consider existing peer secrets when setting peer secrets

### LINKED ISSUE #7497: `peerUrlTls` removed from etcd CR when shoot hibernated
**How to categorize this issue?**

/area control-plane high-availability
/kind bug

**What happened**:
We noticed an issue that `etcd.Spec.Etcd.PeerUrlTls` was removed from the ETCD CR when shoot is hibernated and is re added when the shoot is then woken up. 
This causes an issue that when a shoot is marked for deletion while hibernated, etcd is scaled up without adding `etcd.Spec.Etcd.PeerUrlTls` and etcd members throw up the following error
```
2023-02-15 14:20:31.492960 W | rafthttp: health check for peer dda1e1b5de5194a3 could not connect: tls: first record does not look like a TLS handshake
```

**What you expected to happen**:
`etcd.Spec.Etcd.PeerUrlTls` to always be present in the ETCD CR

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an HA shoot with failure tolerance `zone`
2. Hibernate the shoot
3. Mark the shoot for deletion while the shoot is hibernated

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.64.0
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by aaronfern**
**How to categorize this PR?**

/area control-plane high-availability
/kind bug

**What this PR does / why we need it**:
This PR updates the etcd deploy flow to considers existing peer secrets while computing the peer secrets to be used in the etcd spec
Essentially it now checks for `etcd.Spec.Etcd.PeerUrlTls` in the etcd spec and does not unset this field if already set

**Which issue(s) this PR fixes**:
Fixes #7497 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fix a bug in the etcd deploy flow that erroneously unsets `etcd.Spec.Etcd.PeerUrlTls` in the ETCD CRs of high available shoots when marked for hibernation.
Before this change, high availability clusters failed to be deleted while being hibernated.
```

### CODE REVIEW

File: pkg/operation/botanist/component/etcd/etcd.go [hunk 1]
```diff
@@ -461,7 +461,7 @@ func (e *etcd) Deploy(ctx context.Context) error {
 		}
 
 		// TODO(timuthy): Once https://github.com/gardener/etcd-backup-restore/issues/538 is resolved we can enable PeerUrlTLS for all remaining clusters as well.
-		if pointer.Int32Deref(e.values.Replicas, 0) > 1 {
+		if pointer.Int32Deref(e.values.Replicas, 0) > 1 || (existingEtcd != nil && existingEtcd.Spec.Etcd.PeerUrlTLS != nil) {
```
Comment (timuthy) [inline pkg/operation/botanist/component/etcd/etcd.go]: I'd recommend to use a self expressive var that you can (re)use in the code like:
```
peerTLSAlreadyEnabled := existingEtcd != nil && existingEtcd.Spec.Etcd.PeerUrlTLS != nil
```

**Review by timuthy — COMMENTED** [review]
Thanks for the fix 🙏 

In addition to the inline comment can you please:
- Add a test that covers the said scenario
- Describe the symptom this PR fixes in the release notes, like "Before this change, high availability clusters failed to be deleted while being hibernated."

**Comment by timuthy** [comment]
FYI: This bug was introduced by https://github.com/gardener/gardener/commit/a89ca663f0ba4c6f576db6f06258e627bd5c56f4, i.e. no cherry-pick is required for v1.62

File: pkg/operation/botanist/component/etcd/etcd_test.go [hunk 2]
```diff
@@ -1491,6 +1491,94 @@ var _ = Describe("Etcd", func() {
 				})
 			})
 		})
+
+		Context("When etcd cluster is hibernated", func() {
```
Comment (acumino) [inline pkg/operation/botanist/component/etcd/etcd_test.go]: Nit
```suggestion
		Context("when etcd cluster is hibernated", func() {
```

File: pkg/operation/botanist/component/etcd/etcd_test.go [hunk 3]
```diff
@@ -1491,6 +1491,94 @@ var _ = Describe("Etcd", func() {
...
+					Class:                   class,
+					Replicas:                pointer.Int32(0),
+					StorageCapacity:         storageCapacity,
+					StorageClassName:        &storageClassName,
+					DefragmentationSchedule: &defragmentationSchedule,
+					CARotationPhase:         gardencorev1beta1.RotationCompleted,
+					PriorityClassName:       priorityClassName,
+				})
+			})
+			It("Should not remove peer URL secrets", func() {
```
Comment (acumino) [inline pkg/operation/botanist/component/etcd/etcd_test.go]: Nit
```suggestion
			It("should not remove peer URL secrets", func() {
```

**Comment by aaronfern** [comment]
Thanks for your review @timuthy 
I made the requested changes, PTAL

File: pkg/operation/botanist/component/etcd/etcd_test.go (hunk 3 above)
Comment (acumino) [inline pkg/operation/botanist/component/etcd/etcd_test.go]: Can you also add a test that if the Peer URL is nil, and etcd is hibernated then it should remain nil?

Comment (aaronfern) [reply pkg/operation/botanist/component/etcd/etcd_test.go]: Added a new test case
PTAL

**Review by acumino — COMMENTED** [review]
/lgtm

**Review by timuthy — COMMENTED** [review]
Nice, thank you! 🙂 
/lgtm
/approve

**Comment by shafeeqes** [comment]
/rebase
You need to rebase and adapt the changes from #7515 .

**Review by acumino — COMMENTED** [review]
/lgtm
