### PR TITLE
Generate an ULA as services range for worker-less IPv6 shoots

### LINKED ISSUE #13198: Workerless shoot deletion fails if it uses `IPv6` for `IPFamilies`
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
Create a workerless shoot with `IPFamilies` set to `IPv6` and no service CIDR ranges set. Delete the shoot, and it will fail to get deleted due to KAPI failing to start with error - 

KAPI logs - 
```
W1014 18:32:55.447454       1 options.go:355] No CIDR for service cluster IPs specified. Default value which was 10.0.0.0/24 is deprecated and will be removed in future releases. Please specify it using --service-cluster-ip-range on kube-apiserver.
E1014 18:32:55.463235       1 run.go:72] "command failed" err="service IP family \"10.0.0.0/24\" must match public address family \"x:x:x::x:x\""

Key observation: API server is falling back to IPv4 default service CIDR (10.0.0.0/24) instead of using an IPv6 CIDR, causing mismatch with the IPv6 public address.
```

**What you expected to happen**:
Shoot should get deleted successfully.

/cc @axel7born 

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by axel7born**
**How to categorize this PR?**

/area networking
/kind bug

**What this PR does / why we need it**:
Generate a ULA as services CIDR for worker-less IPv6 shoots, when no service range is specified.
In general, the IPv6 ranges are provided by the infrastructure provider. As we don't create infrastructure resources for worker-less shoots, but need a valid CIDR to configure kube-apiservers we generate an ULA range.  

**Which issue(s) this PR fixes**:
Fixes #13198

**Special notes for your reviewer**:

**Release note**:

```other user
It is possible now to create IPv6 workerless shoots without specifying a service range.
```

### CODE REVIEW

File: plugin/pkg/shoot/validator/admission.go [hunk 1]
```diff
@@ -2241,3 +2246,20 @@ func getDefaultDomainsForSeed(seed *gardencorev1beta1.Seed) []string {
...
+	var globalID [5]byte
+	if _, err := rand.Read(globalID[:]); err != nil {
+		// Fallback to a deterministic value if random generation fails
+		return "fd00:10:2::/112"
+	}
+
+	// Format as fd + 5 bytes of Global ID + 2 bytes of Subnet ID (using 0000 for services)
+	return fmt.Sprintf("fd%02x:%02x%02x:%02x%02x::/112",
+		globalID[0], globalID[1], globalID[2], globalID[3], globalID[4])
+}
```
Comment (ScheererJ) [inline plugin/pkg/shoot/validator/admission.go]: As we only every use one subnet, should we also randomly assign the subnet ID?
WDYT?

File: plugin/pkg/shoot/validator/admission.go [hunk 2]
```diff
@@ -940,6 +941,10 @@ func (c *validationContext) validateShootNetworks(a admission.Attributes, worker
 			} else if slices.Contains(c.shoot.Spec.Networking.IPFamilies, core.IPFamilyIPv4) {
 				allErrs = append(allErrs, field.Required(path.Child("services"), "services is required"))
 			}
+			if workerless && c.shoot.Spec.Networking.Services == nil && slices.Contains(c.shoot.Spec.Networking.IPFamilies, core.IPFamilyIPv6) {
+				ulaCIDR := generateULAServicesCIDR()
+				c.shoot.Spec.Networking.Services = &ulaCIDR
+			}
```
Comment (ScheererJ) [inline plugin/pkg/shoot/validator/admission.go]: While it solves the problem, it feels a bit weird to set `.spec.networking.services` in a `validate...` function. I would have expected a validator to be side-effect-free. This is not completely the case already, but this would be an even more direct side-effect. Not sure what would be a better way or if I do not see the precedent, though.

**Review by ScheererJ — COMMENTED** [review]
Thanks for addressing the issue of worker-less IPv6-only/dual-stack clusters.

**Review by rfranzke — CHANGES_REQUESTED** [review]
Let's move this code to the static defaulting: https://github.com/gardener/gardener/blob/05296a2b9593b4ebba4718fe44d1432e3efcd3c2/pkg/apis/core/v1beta1/defaults_shoot.go#L218-L223

**Comment by acumino** [comment]
> Let's move this code to the static defaulting:
> 
> https://github.com/gardener/gardener/blob/05296a2b9593b4ebba4718fe44d1432e3efcd3c2/pkg/apis/core/v1beta1/defaults_shoot.go#L218-L223

This is not right place as we have to proritize defualing based on the shoot deafults set in the seed spec.
So plugin is the correct place to do defaulting.

File: plugin/pkg/shoot/validator/admission.go (hunk 2 above)
Comment (acumino) [reply plugin/pkg/shoot/validator/admission.go]: This is the exact problem being solved in https://github.com/gardener/gardener/issues/2158 issue.
Since the mutator plugin is added now in this https://github.com/gardener/gardener/pull/13156 PR, these type of changes can be moved there.

File: plugin/pkg/shoot/validator/admission_test.go [hunk 3]
```diff
@@ -2528,6 +2529,30 @@ var _ = Describe("validator", func() {
 
 			})
 
+			It("should not reject because shoot services network is nil for IPv6 (workerless Shoot)", func() {
```
Comment (acumino) [inline plugin/pkg/shoot/validator/admission_test.go]: Add another test, which doesn't set the the network ranges to random value, instead set it to shoot defaults from seed, if shoot default specifies IPv6 network ranges.

**Comment by rfranzke** [comment]
> > Let's move this code to the static defaulting:
> > https://github.com/gardener/gardener/blob/05296a2b9593b4ebba4718fe44d1432e3efcd3c2/pkg/apis/core/v1beta1/defaults_shoot.go#L218-L223
> 
> This is not right place as we have to proritize defualing based on the shoot deafults set in the seed spec. So plugin is the correct place to do defaulting.

IIUC, for workerless shoots, the default networks specified in the `SeedSpec` are irrelevant/not used or useful, especially for IPv6. We were talking with @ScheererJ about augmenting the `SeedSpec` to allow specifying default pod/service IPv6 CIDRs for Shoots. However, he shared that these CIDRs should come from the infrastructure.
In this light, there is no dependency on the `Seed` a workerless `Shoot` got scheduled to, hence static defaulting works well. Nevertheless, I can understand that having this CIDR defaulting at two distinct places can be confusing for future maintenance, so I'd be fine if we moved it close to where the IPv4 defaulting happens, even if not technically needed.

File: plugin/pkg/shoot/validator/admission.go (hunk 2 above)
Comment (axel7born) [reply plugin/pkg/shoot/validator/admission.go]: Maybe, we should wait until https://github.com/gardener/gardener/pull/13207 is merged?

Comment (ialidzhikov) [reply plugin/pkg/shoot/validator/admission.go]: @ScheererJ , thanks for raising this question. I am happy to see other maintainers notice and acknowledge the problem with the `ShootValidator` admission plugin! As Sonu shared, we are working on addressing this as part of our efforts in the validation topic.

---

@acumino , thanks for joining the discussion by linking the existing issue and suggesting that mutations should happen in the `ShootMutator` admission plugin.

---

https://github.com/gardener/gardener/pull/13207 is ready for review now. I don't have problems to rebase if this PR gets merged meanwhile. I will make sure to rebase and move the changes from this PR from the `ShootValidator` to the `ShootMutator` admission plugin. 
Feel free to proceed as you see fit!

Comment (acumino) [reply plugin/pkg/shoot/validator/admission.go]: cc @axel7born, This PR can be rebased now.

File: plugin/pkg/shoot/validator/admission.go (hunk 1 above)
Comment (ScheererJ) [reply plugin/pkg/shoot/validator/admission.go]: As discussed offline, we keep it as is for now.

**Review by ScheererJ — APPROVED** [review]
Thanks for adapting to the new admission structure.

/lgtm
/approve

**Comment by ialidzhikov** [comment]
Let's get this PR in so that I can rebase my PRs from https://github.com/gardener/gardener/issues/2158.
cc @dimitar-kostadinov 

/retest

**Comment by dimitar-kostadinov** [comment]
occurrence of #13072

/test pull-gardener-unit
/test pull-gardener-e2e-kind-upgrade
