### PR TITLE
Set `minDomains` for TopologySpreadConstraints

### LINKED ISSUE #7690: Set topology spread constraint `minDomains` to number of zones
**What would you like to be added**:

When the scheduler doesn't see a zone (e.g. during a zone outage or because of worker pool scale to zero), TSCs will be interpreted "wrongly", if [`minDomains`](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition) is not set. I believe we should amend https://github.com/gardener/gardener/blob/master/docs/development/high-availability.md and start setting `minDomains` based on the number of zones for seed and shoot components alike.

**Why is this needed**:

We saw during "rolling zone outage simulations" with clusters with only 2 zones that e.g. `coredns` gets scheduled to the second zone while the first zone is struck and that DNS fails then completely once the second zone is struck (long after the first zone recovered). That is just an example and it shows that our TSCs don't work as expected, if the scheduler lacks "the full picture"/zone topology information.

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area high-availability
/kind enhancement

**What this PR does / why we need it**:
With this PR, the [High-Availability Webhook](https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#high-availability-config) configures TopologySpreadConstraints with `minDomains: >= number-of- zones`. This configuration only takes effect for clusters which enabled feature gate `MinDomainsInPodTopologySpread` (default as of `v1.27`).

**Which issue(s) this PR fixes**:
Fixes #7690

**Special notes for your reviewer**:
/cc @vlerenc @RaphaelVogel @rfranzke 

**Release note**:

```feature operator
The [`highavailabilityconfig` webhook](https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#high-availability-config) configures topology spread constraints with `minDomains=<number-of- zones>`. This configuration only takes effect for clusters which enabled feature gate `MinDomainsInPodTopologySpread` (default as of Kubernetes `v1.27`). Please note, this configuration will require at least one worker node per registered availability zone so that Kubernetes can spread the respective seed, shoot and control-plane pods across zones.
```
```breaking user
Gardener sets [`minDomains`](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition) for shoot system components to the number of zones configured in the system component worker pool(s). 
⚠️ It is strongly recommended to place at least one worker node per availability zone for system component workers in order to ensure hitch-free rolling updates and scheduling of pods. You may need to adjust the `maximum: <number-of-zones>` values of your system component worker pool(s).
This configuration only takes effect for clusters which enabled feature gate `MinDomainsInPodTopologySpread` (enabled by default as of Kubernetes `v1.27`).
```

### CODE REVIEW

File: test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_suite_test.go [hunk 1]
```diff
@@ -71,6 +74,10 @@ var _ = BeforeSuite(func() {
 		},
 	}
 
+	// TODO(timuthy): `MinDomainsInPodTopologySpread` feature gate is enabled by default as of Kubernetes v1.27. The following lines can be dropped as soon as `envtest` is updated.
+	args := testEnv.ControlPlane.APIServer.Configure()
+	args.Set("feature-gates", "MinDomainsInPodTopologySpread=true")
```
Comment (rfranzke) [inline test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_suite_test.go:79]: Why is this needed? IIUC, the `minDomains` can also be set when the feature gate is disabled - it will only not be respected?

**Comment by rfranzke** [comment]
The release note states

> This requires the worker pools to have at least one free node per zone.

Can you enhance this with more information what I need to do as user to ensure all this works?

File: test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_suite_test.go (hunk 1 above)
Comment (timuthy) [reply test/integration/resourcemanager/highavailabilityconfig/highavailabilityconfig_suite_test.go:79]: Yes, it'll be ignored but I wanted to enhance the integration tests 👀

**Comment by timuthy** [comment]
/hold

I want to bring up one concern that came into my mind while I was having a second thought about this change: The linked issue describes the `minDomains` value should be set to the number of availability zones.

Many of our components are deployed with 2 replicas and having a cluster with three zones {A, B, C} -> `minDomains: 3` requires the cluster to have:
- node(s) in two zones at all times, e.g. in **A, B**
- node(s) in zone **C** only occasionally, e.g. when a rolling update happens

Setting `minDomains: 3` isn't very beneficial, setting `minDomains: 2` should already be sufficient. Hence, I think we should slightly improve this value:

```golang
minDomains: math.Min(zoneLen, maxReplicas)
```

Any thoughts @rfranzke @vlerenc?

**Comment by vlerenc** [comment]
@timuthy Very true. I over-focussed on the "3 zones example", which is wrong for the components deployed with 2 replicas. In the end, `minDomains` should match what we want to achieve. If we want 2 replicas, we need `minDomains` to be 2. If we want 3 replicas, we need `minDomains` to be 3. If we need more replicas, it's still 3 in a 3 zone cluster (or less with fewer zones). That's exactly what you suggest:

`minDomains: math.Min(zoneLen, maxReplicas)`

👍 

Thank you for spotting that!

**Comment by timuthy** [comment]
PR has been adjusted with the revised logic discussed in https://github.com/gardener/gardener/pull/7826#issuecomment-1520032343.
/unhold

**Review by rfranzke — COMMENTED** [review]
/lgtm

Thanks @timuthy 👏🏻
