### PR TITLE
Fix `MCM` replica count during shoot hibernation

### LINKED ISSUE #7151: `Shoot` cluster can get stuck during creation if it is being hibernated at the same time
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:
If a `Shoot` cluster is created and the creation is interrupted right after a `Machine` is deployed and hibernation is triggered at the same time, the operation will get stuck with
```
task "Waiting until shoot worker nodes have been reconciled" failed: Error while waiting for Worker shoot--prj-hxm--cilium-noenc/cilium-noenc to become ready: error during reconciliation: Error reconciling Worker: Failed while waiting for all machine deployments to be ready: retry failed with context deadline exceeded, last error: Waiting until all machines have been hibernated (2 still awake)...
```

**What you expected to happen**:
MCM to be scaled to 1 if there are machines that were deployed to the cluster, even if the cluster is getting hibernated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a `Shoot` and interrupt the creation right after a machine has been deployed, but before its status has been updated to success. To do that you can insert a dummy step in the flow that always returns an error.
2. Hibernate the `Shoot` cluster
3. Observe that MCM is scaled down and that hibernation and creation gets stuck.

**Anything else we need to know?**:

The `machine-controller-manager` is scaled to 0 in this case so there is nothing to destroy the `Machine`s that were already created so that the cluster can be hibernated. This scale to 0 happens because of
https://github.com/gardener/gardener/blob/219d828fcdea81fb3edf13de2736daf81e137923/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go#L59-L74
The `extensionscontroller.IsHibernationEnabled(cluster) && extensionscontroller.IsCreationInProcess(cluster)` condition is evaluated to true here, so the returned replicas are 0.

Before #6054 the current number of replicas for MCM was always preserved: 
https://github.com/gardener/gardener/blob/debfabc71d52d1848febe5174274e1bc819a3668/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go#L56-L61

/cc @unmarshall 

**Environment**:

- Gardener version: 6a0fea86850ffec8937d1956bdf1a8ca6d074f3b
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rishabh-11**
**How to categorize this PR?**

/area control-plane
/area robustness
/kind enhancement

**What this PR does / why we need it**:
This PR fixes the `MCM` replica count function to scale up `MCM` when hibernation is enabled during creation, and machines are present in the cluster.

**Which issue(s) this PR fixes**:
Fixes #7151 

**Special notes for your reviewer**:
The testing for this was done using the local gardener kind cluster setup.

**Release note**:

```other operator
The generic Worker actuator will scale up machine-controller-manager Deployment when Shoot hibernates with `.status.lastOperationType=Create` or `.status.lastOperationType=nil` and a machine deployment exists with `.status.Replicas` > 0.
```

### CODE REVIEW

File: extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go [hunk 1]
```diff
@@ -528,6 +528,15 @@ func getExistingMachineDeployment(existingMachineDeployments *machinev1alpha1.Ma
 	return nil
 }
 
+func isExistingMachineDeploymentWithPositiveReplicaCountPresent(existingMachineDeployments *machinev1alpha1.MachineDeploymentList) int32 {
```
Comment (rfranzke) [inline extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go]: The function name suggests that it returns a `bool` but it returns an `int32` 😕

Comment (rishabh-11) [reply extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go]: changed it to return `bool`

**Comment by rishabh-11** [comment]
cc @himanshu-kun

**Review by himanshu-kun — APPROVED** [review]
/lgtm

**Comment by plkokanov** [comment]
@rishabh-11 @himanshu-kun should we open hotfix PRs for previous releases

**Comment by himanshu-kun** [comment]
Yes @plkokanov , we'll open the PRs
