### PR TITLE
Separate the Seeds and the Shoots loggins stack deleteion

### LINKED ISSUE #3433: Deletion of Shoot Level Logging Resources Deletes Cluster Level Role and Rolebinding
**How to categorize this issue?**

/area logging
/kind bug
/priority normal
/assign @vlvasilev 

**What happened**:
Each reconciliation of shoot with `testing` purpose ensures that the logging resources in the shoot namespace in the seed are deleted:
https://github.com/gardener/gardener/blob/24121a7c7b3cd0180ff871fca54e995c4d0b9178/pkg/operation/botanist/logging.go#L42-L44

However, this method lists and deletes clusterrole and clusterrolebinding matching `gardener.cloud/role=logging`
https://github.com/gardener/gardener/blob/24121a7c7b3cd0180ff871fca54e995c4d0b9178/pkg/operation/common/utils.go#L331-L358
The effect is that the `fluent-bit-read` [clusterrole](https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-role.yaml) and [clusterrolebinding](https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-role-binding.yaml) are deleted which brakes the cluster controller in the fluent-bit plugin:
```
E0120 10:27:20.049653       1 reflector.go:153] github.com/gardener/gardener/pkg/client/extensions/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Cluster: clusters.extensions.gardener.cloud is forbidden: User "system:serviceaccount:garden:fluent-bit" cannot list
resource "clusters" in API group "extensions.gardener.cloud" at the cluster scope
```

**What you expected to happen**:
The cluster level resources to not be deleted on shoot reconciliation

**How to reproduce it (as minimally and precisely as possible)**:
Reconcile a shoot with testing purpose. Use the following gardenlet feature gate settings
```yaml
Logging: true
CachedRuntimeClients: false
```

**Anything else we need to know?**:
cc @timebertt 
It is not reproducible with
```yaml
CachedRuntimeClients: true
```

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by vlvasilev**
**How to categorize this PR?**

/area logging
/kind enhancement
/priority normal

**What this PR does / why we need it**:
With this PR we separate the seed and shoot logging stack deletion in two different functions.
This is needed because when we delete the logging stack of a shoot we delete a cluster scoped resources like [Clusterolebindings](https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-role-binding.yaml) and [Clusterroles](https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-role.yaml) which are needed for the Seed logging stack.
   
**Which issue(s) this PR fixes**:
Fixes [#3433](https://github.com/gardener/gardener/issues/3433#)

**Special notes for your reviewer**:

**Release note**:

```bugfix developer
The Seed and Shoot logging stack deletion is separated in two functions to avoid accidental deletion of cluster scoped resources.  
```

### CODE REVIEW

File: pkg/operation/botanist/logging.go [hunk 1]
```diff
@@ -40,7 +40,7 @@ func (b *Botanist) DeploySeedLogging(ctx context.Context) error {
 	}
 
 	if b.Shoot.Purpose == gardencorev1beta1.ShootPurposeTesting || !gardenletfeatures.FeatureGate.Enabled(features.Logging) {
-		return common.DeleteLoggingStack(ctx, b.K8sSeedClient.Client(), b.Shoot.SeedNamespace)
+		return common.DeleteShootLoggingStack(ctx, b.K8sSeedClient.Client(), b.Shoot.SeedNamespace)
```
Comment (vpnachev) [inline pkg/operation/botanist/logging.go:33]: You can remove the vpa deletion above now.

File: pkg/operation/common/utils.go [hunk 2]
```diff
@@ -318,56 +317,47 @@ func DeleteVpa(ctx context.Context, c client.Client, namespace string, isShoot b
...
-	}
-
-	for _, list := range lists {
-		if err := k8sClient.List(ctx, list,
-			client.InNamespace(namespace),
-			client.MatchingLabels{v1beta1constants.GardenRole: v1beta1constants.GardenRoleLogging}); err != nil {
-			return err
-		}
+// DeleteShootLoggingStack deletes all shoot resource of the logging stack in the given namespace.
+func DeleteShootLoggingStack(ctx context.Context, k8sClient client.Client, namespace string) error {
```
Comment (vpnachev) [inline pkg/operation/common/utils.go:321]: Some naming suggestions as it:
- deletes only loki related resources
- is used to delete them also in the `garden` namespace

```suggestion
// DeleteLoki  deletes all resources of the Loki in a given namespace.
func DeleteLoki(ctx context.Context, k8sClient client.Client, namespace string) error {
```

File: pkg/operation/common/utils.go [hunk 3]
```diff
@@ -318,56 +317,47 @@ func DeleteVpa(ctx context.Context, c client.Client, namespace string, isShoot b
...
 	}
+	return nil
+}
 
-	pvc := &corev1.PersistentVolumeClaim{
-		ObjectMeta: metav1.ObjectMeta{
-			Name:      "loki-loki-0",
-			Namespace: namespace,
-		},
+// DeleteSeedLoggingStack deletes all seed resource of the logging stack in the given garden namespace.
```
Comment (vpnachev) [inline pkg/operation/common/utils.go]:
```suggestion
// DeleteSeedLoggingStack deletes all seed resource of the logging stack in the garden namespace.
```

File: pkg/operation/common/utils_test.go [hunk 4]
```diff
@@ -810,4 +814,53 @@ var _ = Describe("common", func() {
 			Expect(err).NotTo(HaveOccurred())
 		})
 	})
+
+	Describe("#DeleteSeedLoggingStack", func() {
```
Comment (vpnachev) [inline pkg/operation/common/utils_test.go:818]: Add similar test only for the shoot level resources.

**Review by vpnachev — CHANGES_REQUESTED** [review]
Thanks.
Overall looks good. I have a few minor suggestions.

**Review by vpnachev — APPROVED** [review]
/lgtm
