### PR TITLE
🐛 secretsrotation: tolerate partial API discovery failures during ETCD encryption key rotation

### LINKED ISSUE #14676: Credential Rotation fails when any APIService is unavailable
<!-- Please ensure that you do not include company internal information. -->

**How to categorize this issue?**
<!--
Please select area, kind, and priority for this issue. This helps the community categorizing it.
Replace below TODOs or exchange the existing identifiers with those that fit best in your opinion.
If multiple identifiers make sense you can also state the commands multiple times, e.g.
  /area control-plane
  /area security
  ...

"/area" identifiers:     audit-logging|auto-scaling|backup|certification|control-plane-migration|control-plane|cost|delivery|dev-productivity|disaster-recovery|documentation|high-availability|logging|metering|monitoring|networking|open-source|ops-productivity|os|performance|quality|robustness|scalability|security|storage|testing|usability|user-management
"/kind" identifiers:     api-change|bug|cleanup|discussion|enhancement|epic|impediment|poc|post-mortem|question|regression|task|technical-debt|test
-->
/area control-plane
/area security
/kind bug

**What happened**:
When a cluster has an APIService which is not available, the credential rotation for the etcd fails.
```text
Flow "Shoot cluster reconciliation" encountered task errors: [task "Labeling resources after modification of encryption config or to encrypt them with new ETCD encryption key" failed: retry failed with context deadline exceeded, last error: error discovering server preferred resources: unable to retrieve the complete list of server APIs: acme.stackit.de/v1alpha1: stale GroupVersion discovery: acme.stackit.de/v1alpha1] Operation will be retried.
```

**What you expected to happen**:
Credential rotation should succeed, as long as the APIService is not critical for it.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new shoot
```bash
helm install \                                                                                                                                                                                                                                         
  cert-manager oci://quay.io/jetstack/charts/cert-manager \
  --version v1.20.2 \
  --namespace cert-manager \
  --create-namespace \
  --set crds.enabled=true
helm repo add stackit-cert-manager-webhook https://stackitcloud.github.io/stackit-cert-manager-webhook
helm install stackit-cert-manager-webhook --namespace cert-manager stackit-cert-manager-webhook/stackit-cert-manager-webhook
kubectl delete service -n cert-manager stackit-cert-manager-webhook
```
Start a credential rotation

**Anything else we need to know?**:
I already prepared a fix for this and will create a PR.

### PR DESCRIPTION
**Pull request by robinschneider**
**How to categorize this PR?**

/area control-plane
/area security
/kind bug

**What this PR does / why we need it**:
This PR fixes a bug that prevents the credential rotation to successfully complete when an `APIService` is not available.
It tolerates partial API discovery failures during ETCD encryption key rotation for unrelated resources.

**Which issue(s) this PR fixes**:
Fixes #14676

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Rotating the etcd encryption key tolerates unavailable `APIServices`.
```

### CODE REVIEW

**Comment by robinschneider** [comment]
cc: @timebertt

File: pkg/utils/gardener/secretsrotation/etcd_test.go [hunk 1]
```diff
@@ -360,6 +362,64 @@ var _ = Describe("ETCD", func() {
...
+
+				defaultGVKs = []schema.GroupVersionKind{corev1.SchemeGroupVersion.WithKind("Secret")}
+			)
+
+			fakeDiscoveryClient.err = &discovery.ErrGroupDiscoveryFailed{
+				Groups: map[schema.GroupVersion]error{
+					{Group: "acme.stackit.de", Version: "v1alpha1"}: fmt.Errorf("stale GroupVersion discovery: acme.stackit.de/v1alpha1"),
+				},
+			}
+			DeferCleanup(func() { fakeDiscoveryClient.err = nil })
```
Comment (shafeeqes) [inline pkg/utils/gardener/secretsrotation/etcd_test.go]: Nit: we are resetting `fakeDiscoveryClient` in `BeforeEach`
```suggestion
```

Comment (robinschneider) [reply pkg/utils/gardener/secretsrotation/etcd_test.go]: Thanks, I removed it

File: pkg/utils/gardener/secretsrotation/etcd.go [hunk 2]
```diff
@@ -265,7 +265,17 @@ func GetResourcesForRewrite(
 
 	resourceLists, err := discoveryClient.ServerPreferredResources()
 	if err != nil {
-		return encryptedGVKs.UnsortedList(), "", fmt.Errorf("error discovering server preferred resources: %w", err)
+		failedGroups, isPartialFailure := discovery.GroupDiscoveryFailedErrorGroups(err)
+		if !isPartialFailure {
+			return encryptedGVKs.UnsortedList(), "", fmt.Errorf("error discovering server preferred resources: %w", err)
+		}
+		for failedGV := range failedGroups {
+			for _, gr := range groupResourcesToEncrypt {
```
Comment (timebertt) [inline pkg/utils/gardener/secretsrotation/etcd.go]: Can you use `slices.ContainsFunc` similar to below (line 311)?

File: pkg/utils/gardener/secretsrotation/etcd_test.go [hunk 3]
```diff
@@ -394,6 +451,8 @@ var _ = Describe("ETCD", func() {
 
 type fakeDiscoveryWithServerPreferredResources struct {
 	*fakediscovery.FakeDiscovery
```
Comment (timebertt) [inline pkg/utils/gardener/secretsrotation/etcd_test.go:453]: Can you check the linter errors in CI? You can use `make check` to run them locally.

**Review by timebertt — COMMENTED** [review]
Nice PR. Thanks for the fix!
/assign

**Review by timebertt — COMMENTED** [review]
Thanks!
/lgtm

**Comment by shafeeqes** [comment]
Thank you!
/approve
