### PR TITLE
Wait for clean cluster state before hibernating control plane

### LINKED ISSUE #1630: Incorrect state on cluster hibernation
**What happened**:
When Gardener hibernates Shoot clusters, it sometimes happens that the objects in the Shoot's etcd don't reflect the correct state of the cluster. 
The current logic is more or less: scale down the workers, wait for all Node objects to be deleted and then hibernate the control plane.

This can lead to the following state:
All Nodes removed, but Pods still having the state `Running` and Endpoints still containing the Pods' IPs (which is incorrect).
On wakeup the garbage collector in the `kube-controller-manager` cleans up all "orphaned" Pods and cleans the IPs from the corresponding Endpoints.
Because this runs in parallel to i.e. the ReplicaSet controller, kcm tries to create new Pods which will then go through configured admission webhooks.

Together with @schrodit I discovered the following issue:
If the Shoot has `ValidatingWebhookConfigurations` or `MutatingWebhookConfigurations` with rules for `CREATE pods` and `failurePolicy=Ignore` and `timeout=30s` (for example the default `vpa-webhook`) the Shoot might not get woken up correctly.
This is because `kube-apiserver` tries to connect to the Webhook but will timeout after the configured `30s` because the Pod's IP is not reachable. In this time, the request from `kube-controller-manager` will timeout on the client side and the request will be cancelled and therefore the Pod will not be created. The ReplicaSet controller somehow does not retry to create the Pod in this case. Therefore the Shoot cannot be woken up, if the `vpn-shoot` Deployment is affected by this issue.

**What you expected to happen**:
Shoot cluster should be hibernated with a "clean state"

**How to reproduce it (as minimally and precisely as possible)**:
(Hard to reproduce because this is somewhat of a race condition on wakeup between the garbage collector and the other Controllers. Sometimes it will work completely, sometimes a few Pods will be created and a few don't...)
1. Create a Shoot
1. `ValidatingWebhookConfigurations` or `MutatingWebhookConfigurations` with rules for `CREATE pods` and `failurePolicy=Ignore` and `timeout=30s` (i.e. vpa-webhooks)
1. Hibernate the Shoot
1. Wake it up again

**Anything else we need to know?**:
This issue might be the root cause of karydia/karydia#235
The current solution is to restart `kube-controller-manager` of the Shoot, if this issue occurs.

**Environment**:

- Gardener version: 0.31.2, extensions: 0.14.4/1.0.0
- Kubernetes version (use `kubectl version`): Shoot: 1.16.2, Seed: 1.15.5
- Cloud provider or hardware configuration: aws
- Others:

### PR DESCRIPTION
**Pull request by timebertt**
**What this PR does / why we need it**:
Gardener now waits for a "clean" cluster state before hibernating the Shoot's control plane. Now it does not only wait for all `Node` objects to be deleted, but additionally waits for all `Pods` to not be in state `Running` anymore and all `Endpoints` objects to not contain any IPs from the Shoot Cluster's Pod CIDR. 
See #1630 for further details.

**Which issue(s) this PR fixes**:
Fixes #1630 

**Special notes for your reviewer**:
cc @schrodit 

**Release note**:

```improvement user
Gardener now waits for a "clean" cluster state before hibernating the Shoot's control plane.
```

### CODE REVIEW

File: pkg/operation/botanist/waiter.go [hunk 1]
```diff
@@ -325,6 +326,67 @@ func (b *Botanist) WaitUntilNodesDeleted(ctx context.Context) error {
...
+		return fmt.Errorf("unable to check if there are still Endpoints containing Pod IPs in the shoot cluster. Shoot's Pods network is empty")
+	}
+
+	return retry.Until(ctx, 5*time.Second, func(ctx context.Context) (done bool, err error) {
+		endpointsList := &corev1.EndpointsList{}
+		if err := b.K8sShootClient.Client().List(ctx, endpointsList); err != nil {
+			return retry.SevereError(err)
+		}
+
+		for _, endpoints := range endpointsList.Items {
```
Comment (timuthy) [inline pkg/operation/botanist/waiter.go]: It probably makes sense to check the endpoints in parallel, i.e. one go routine per endpoint. WDYT?

**Review by timuthy — APPROVED** [review]
/lgtm
