### PR TITLE
Keep track of the last maintenance operation in the shoot status

### LINKED ISSUE #6592: The maintenance controller in GCM to keep track of the last maintenance operation in the shoot status
**How to categorize this issue?**

/area ops-productivity robustness usability
/kind enhancement

**What would you like to be added**:
The maintenance controller in GCM to keep track of the last maintenance operation in the shoot status - it could be either a condition or a new field similar to `lastOperation`. 

**Why is this needed**:
1. To have the timestamp of the last maintenance operation.
2. Any failed maintenance operations to be made visible to the shoot owner and gardener operators with reason/error message.
3. It would be nice to have summary of what was changed in the shoot spec during the last maintenance, e.g. OS/k8s version.

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
Shoot status now has a new field lastMaintenanceOperations which holds the information about the time when maintenance was triggered and changes in shoot in that maintenance cycle.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/6592

**Special notes for your reviewer**:

Shoot status will look something like this if maintenance can proceed:
```
lastMaintenance:
      description: 'Machine image of worker-pool "sonu-shoot3" upgraded from "suse-chost"
        version "15.4.20220620" to version "15.4.20220818". Reason: AutoUpdate of
        MachineImage configured, For "Shoot": Kubernetes version upgraded "1.24.3"
        to version "1.24.7". Reason: AutoUpdate of Kubernetes version configured,
        For "Worker Pool-sonu-shoot3": Kubernetes version upgraded "1.24.3" to version
        "1.24.7". Reason: AutoUpdate of Kubernetes version configured'
      state: Succeeded
      triggeredTime: "2022-12-09T10:05:37Z"
```
Shoot status will look something like this if maintenance can't proceed:
```
 lastMaintenance:
      description: 'For "Shoot": Kubernetes version upgraded "1.24.3" to version "1.25.4".
        Reason: Kubernetes version expired - force update required, For "Worker Pool-sonu-shoot3":
        Kubernetes version upgraded "1.24.3" to version "1.25.4". Reason: Kubernetes
        version expired - force update required'
      failureReason: 'Maintenance failed: Shoot.core.gardener.cloud "arm-shoot4" is
        invalid: [spec.kubernetes.allowPrivilegedContainers: Forbidden: for Kubernetes
        versions >= 1.25, allowPrivilegedContainers field should not be set, please
        see https://github.com/gardener/gardener/blob/master/docs/usage/pod-security.md#speckubernetesallowprivilegedcontainers-in-the-shoot-spec,
        spec.kubernetes.version: Forbidden: admission plugin "PodSecurityPolicy" should
        be disabled for Kubernetes versions >=1.25, please check https://github.com/gardener/gardener/blob/master/docs/usage/pod-security.md#migrating-from-podsecuritypolicys-to-podsecurity-admission-controller]'
      state: Failed
      triggeredTime: "2022-12-09T10:15:59Z"
```

**Release note**:

```feature user
From now on, summary of what was changed in the last maintenance time window in `Shoot` specification is kept in `Shoot`'s `.status.lastMaintenance` field.
```

### CODE REVIEW

**Review by timebertt — CHANGES_REQUESTED** [review]
TBH, I don't like the API design at all and I'm confused that there was no proposal to discuss it.

So here is my proposal:

- let's make this a single value instead of a field in a field
- put all version upgrades relevant to users (k8s/os upgrades) into a nice description
- exclude internal operations from the status (e.g. shoot reconciliation, `Infrastructure`/`DNSRecord` reconciliation)

```yaml
status:
  lastMaintenance:
    state: Succeeded
    timestamp: 2022-11-18T10:14:38Z
    description: "Kubernetes version was upgraded to 1.24.5. OS image versioin of worker pool 123 was upgraded to 987.6.5"
```

**Comment by acumino** [comment]
> let's make this a single value instead of a field in a field

Keeping changes in the list seems better for readability/simplicity reasons.
> exclude internal operations from the status (e.g. shoot reconciliation, Infrastructure/DNSRecord reconciliation)

It was suggested here https://github.com/gardener/gardener/pull/6725#discussion_r978803082, to keep this information also.

Apart from the above I have made `state` a string variable cause, there should be a proper description of why the update failed, just keeping the value that the last maintenance failed doesn't help much, also it was one of the requirements in the open issue :
`Any failed maintenance operations to be made visible to the shoot owner and gardener operators with reason/error message.`.

**Comment by timebertt** [comment]
> Keeping changes in the list seems better for readability/simplicity reasons.

In my opinion, a single value is much more readable and simple. It also fits the `lastOperation` semantics – here, we also keep one last operation only instead of a full history.
Keeping a history might get confusing. E.g., if there are some intermittent failures and then the maintenance succeeds, the user will be unsure what the current state is if only looking at the status section.

> exclude internal operations from the status (e.g. shoot reconciliation, Infrastructure/DNSRecord reconciliation)

I would only put information into the `status.lastMaintenance` section, which is also configured by the `spec.maintenance` section.
Internal operations like shoot reconciliation and Infrastructure/DNSRecord reconciliation are internal operations (implementation details) and are not configured by the user.

> Apart from the above I have made `state` a string variable cause, there should be a proper description of why the update failed, just keeping the value that the last maintenance failed doesn't help much, also it was one of the requirements in the open issue :
> `Any failed maintenance operations to be made visible to the shoot owner and gardener operators with reason/error message.`.

Apart from what I mentioned above, the maintenance operation "reconcile shoot" and "reconcile Infra/DNS" will never fail. The maintenance controller only adds annotations to the shoot, which will never fail with a failure that is meaningful to the shoot owner.
The reconciliation as such might fail, but then the error is presented in `status.lastOperation`. 

Hence, I strongly vote for excluding these internal operations from `status.lastMaintenance` and make it a single value field only.

File: pkg/controllermanager/controller/shoot/add.go [hunk 1]
```diff
@@ -45,6 +46,7 @@ func AddToManager(mgr manager.Manager, cfg config.ControllerManagerConfiguration
 
 	if err := (&maintenance.Reconciler{
 		Config: cfg.Controllers.ShootMaintenance,
+		Clock:  clock.RealClock{},
```
Comment (shafeeqes) [inline pkg/controllermanager/controller/shoot/add.go]: Please default this inside `AddToManager` function.
ref: https://github.com/gardener/gardener/pull/7062/commits/7b2ccf86aed92e42cce2109759a0abc5df8babe3

File: pkg/apis/core/types_shoot.go [hunk 2]
```diff
@@ -154,6 +154,18 @@ type ShootStatus struct {
 	MigrationStartTime *metav1.Time
 	// Credentials contains information about the shoot credentials.
 	Credentials *ShootCredentials
+	// LastMaintenance holds information about the last maintenance operations on the Shoot.
+	LastMaintenance *LastMaintenance
```
Comment (rfranzke) [inline pkg/apis/core/types_shoot.go:158]: Please enhance https://github.com/gardener/gardener/blob/master/docs/usage/shoot_maintenance.md with information about this new field.

File: pkg/apis/core/types_shoot.go [hunk 3]
```diff
@@ -154,6 +154,18 @@ type ShootStatus struct {
 	MigrationStartTime *metav1.Time
 	// Credentials contains information about the shoot credentials.
 	Credentials *ShootCredentials
+	// LastMaintenance holds information about the last maintenance operations on the Shoot.
```
Comment (rfranzke) [inline pkg/apis/core/types_shoot.go:157]:
```suggestion
	// LastMaintenance holds information about the last maintenance operation on the Shoot.
```

Same for other API packages

File: pkg/controllermanager/controller/shoot/maintenance/add.go [hunk 4]
```diff
@@ -63,7 +69,7 @@ func (r *Reconciler) ShootPredicate() predicate.Predicate {
 				return false
 			}
 
-			return hasMaintainNowAnnotation(shoot) ||
+			return (hasMaintainNowAnnotation(shoot) && !hasMaintainNowAnnotation(oldShoot)) ||
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/add.go:72]: Enhance the unit test to cover this

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 5]
```diff
@@ -93,44 +96,53 @@ func requeueAfterDuration(shoot *gardencorev1beta1.Shoot) (time.Duration, time.T
...
-		shoot.Spec.Kubernetes.Version = v
+	reasonForKubernetesUpdate, err := maintainKubernetesVersion(log, maintainedShoot.Spec.Kubernetes.Version, maintainedShoot.Spec.Maintenance.AutoUpdate.KubernetesVersion, cloudProfile, func(v string) error {
+		maintainedShoot.Spec.Kubernetes.Version = v
 		return nil
 	})
 	if err != nil {
 		// continue execution to allow the machine image version update
 		log.Error(err, "Failed to maintain Shoot kubernetes version")
 	}
+	if reasonForKubernetesUpdate != "" {
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: You don't have this `if` condition above for `reasonForImageUpdatePerPool`. Why here? Can we harmonize this?

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 6]
```diff
@@ -93,44 +96,53 @@ func requeueAfterDuration(shoot *gardencorev1beta1.Shoot) (time.Duration, time.T
...
+		operations = append(operations, "Shoot "+reasonForKubernetesUpdate)
+	}
 
-	shootSemver, err := semver.NewVersion(shoot.Spec.Kubernetes.Version)
+	shootSemver, err := semver.NewVersion(maintainedShoot.Spec.Kubernetes.Version)
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
	shootVersion, err := semver.NewVersion(maintainedShoot.Spec.Kubernetes.Version)
```

Nit

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 7]
```diff
@@ -150,12 +162,58 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
 		reasonsForWorkerPoolKubernetesUpdate[w.Name] = reasonForWorkerPoolKubernetesUpdate
 	}
 
-	maintainOperation(shoot)
+	for workerPool, reason := range reasonsForWorkerPoolKubernetesUpdate {
+		if reason != "" {
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: Same question here

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 8]
```diff
@@ -150,12 +162,58 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+			operation := fmt.Sprintf("For worker pool %s: %s", workerPool, reason)
+			operations = append(operations, operation)
+		}
+	}
+
+	operation := maintainOperation(maintainedShoot)
+	if operation != "" {
+		operations = append(operations, "Other task started during maintenance time - "+operation)
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
		operations = append(operations, fmt.Sprintf("Added %q operation annotation", operation))
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 9]
```diff
@@ -150,12 +162,58 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+	}
+
+	if operations != nil {
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: This is more intuitive here, I think:

```suggestion
	if len(operations) > 0 {
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 10]
```diff
@@ -150,12 +162,58 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+
+		// First dry run the update call to check if it can be executed successfully.
+		// If not shoot maintenance is marked as failed and is retried only in
+		// next maintenance window.
+		if err := r.Client.Update(ctx, maintainedShoot, &client.UpdateOptions{
+			DryRun: []string{metav1.DryRunAll},
+		}); err != nil {
+			if hasMaintainNowAnnotation(shoot) {
+				delete(shoot.Annotations, v1beta1constants.GardenerOperation)
+			}
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go:189]: Why do we do this when we don't update the shoot but return in L200? This would not be reflected in the system, would it?

File: pkg/apis/core/types_shoot.go [hunk 11]
```diff
@@ -154,6 +154,18 @@ type ShootStatus struct {
...
+}
+
+// LastMaintenance holds information about a maintenance operation on the Shoot.
+type LastMaintenance struct {
+	// A human-readable message containing details about the operations performed in the last maintenance.
+	Description string
+	// TriggeredTime is the time when maintenance was triggered.
+	TriggeredTime metav1.Time
+	// Status holds details of last maintenance failure.
+	Status *string
```
Comment (rfranzke) [inline pkg/apis/core/types_shoot.go]: Let's rename this to `State` (like in `LastOperation`).

Also, I'm wondering whether we should use `LastOperationState` type here to have only `Error`/`Succeeed`/etc. For the error message in case maintenance fails, maybe we should add a `Reason` or `FailureReason` field?
Alternatively, we keep it as `string` (why a pointer, btw?) and only use "short messages" like `Succeeded` or `Failed: <error>`?

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 12]
```diff
@@ -150,12 +162,58 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+			shoot.Status.LastMaintenance.Status = pointer.String(fmt.Sprintf("Maintenance failed: %s", err.Error()))
+			if err := r.Client.Status().Patch(ctx, shoot, patch); err != nil {
+				log.Error(err, "Failed to patch shoot status")
+				return err
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
				return err
```

From https://github.com/gardener/gardener/blob/master/docs/development/logging.md#reconciler-loggers:

> Hence, don't log an error that you are returning.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 13]
```diff
@@ -150,12 +162,58 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+			}
+
+			log.Info("Shoot maintenance failed", "error", err)
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
			log.Info("Shoot maintenance failed", "reason", err)
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 14]
```diff
@@ -150,12 +162,58 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+			return nil
+		}
+
+		if err := r.Client.Status().Patch(ctx, shoot, patch); err != nil {
+			log.Error(err, "Failed to patch shoot status")
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: same here

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 15]
```diff
@@ -150,12 +162,58 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+
+	// update shoot spec changes in maintenance call
+	shoot.Spec = *maintainedShoot.Spec.DeepCopy()
+	_ = maintainOperation(shoot)
 	maintainTasks(shoot, r.Config)
 
 	// try to maintain shoot, but don't retry on conflict, because a conflict means that we potentially operated on stale
 	// data (e.g. when calculating the updated k8s version), so rather return error and backoff
-	if err := gardenClient.Update(ctx, shoot); err != nil {
+	if err := r.Client.Update(ctx, shoot); err != nil {
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go:212]: Shouldn't we update the state to `Succeeded` in the `.status.lastMaintenance` now?

**Review by rfranzke — CHANGES_REQUESTED** [review]

File: pkg/apis/core/types_shoot.go (hunk 3 above)
Comment (acumino) [reply pkg/apis/core/types_shoot.go:157]: I kept it as operations, cause there can be multiple changes on a shoot, shoot like Kubernetes version, worker machine image, or worker Kubernetes version.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 5 above)
Comment (acumino) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: There a list is returned so if the list is empty nothing will be appended but here if I don't check if the string is nil i.e. shoot Kubernetes version was not upgraded, it will append an empty string to the list.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 10 above)
Comment (acumino) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go:189]: > This would not be reflected in the system, would it?

Yes, patch call on status updates the annotation.

>Why do we do this when we don't update the shoot but return in L200? 

Removing the annotation is required. For ex- if the maintenance fails and later the reason for failure is fixed and if maintenance is triggered again with annotation it will fail with the reason that annotation is already present.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 15 above)
Comment (acumino) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go:212]: > Shouldn't we update the state to Succeeded in the .status.lastMaintenance now?

Update call will not update the status. If we patch the shoot status after the update call there is a chance that it can fail and if it fails we can' return the error cause it will lead to another reconciliation which we don't want and patching without returning an error is not right cause it can be inconsistent.

File: pkg/apis/core/types_shoot.go (hunk 11 above)
Comment (acumino) [reply pkg/apis/core/types_shoot.go]: I have kept only one field cause we can't populate if the maintenance succeded successfully in a consistent way. 
The `status` is a pointer cause it can be nil if the dry run of maintenance doesn't fail as there will be nothing to put in it.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 5 above)
Comment (rfranzke) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: OK, but it seems not necessary for `reasonForImageUpdatePerPool`. Can we harmonize this?

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 10 above)
Comment (rfranzke) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go:189]: > Yes, patch call on status updates the annotation.

Well, then please add a comment. This is not quite obvious/intuitive. I am not even sure if this isn't a bug.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 15 above)
Comment (rfranzke) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go:212]: We can still try to update it here. If it fails, it should be requeued (error should be returned). The next reconciliation should not do anything since `len(operations)` would be `nil` and the `shoot` would already be updated by this line.

File: pkg/apis/core/types_shoot.go (hunk 11 above)
Comment (rfranzke) [reply pkg/apis/core/types_shoot.go]: OK, then let's keep it (but perhaps still rename to `State`). 

> The `status` is a pointer cause it can be nil if the dry run of maintenance doesn't fail as there will be nothing to put in it.

Hm, why? I can't follow. If there is nothing to do then we should not report any "last maintenance" operation here. So, in all cases when we update this field, there was something that we changed in the `Shoot`, and then  we should always have a state.

File: pkg/apis/core/types_shoot.go (hunk 2 above)
Comment (acumino) [reply pkg/apis/core/types_shoot.go:158]: I guess this is not the right place this is more about how/what can be configured in maintenance.

File: pkg/apis/core/types_shoot.go (hunk 11 above)
Comment (acumino) [reply pkg/apis/core/types_shoot.go]: I have updated the PR accordingly PTAL d61810532444c44d112305fd85262f5e16b255f2.

File: pkg/apis/core/types_shoot.go (hunk 2 above)
Comment (rfranzke) [reply pkg/apis/core/types_shoot.go:158]: I can't follow. This document explains everything about maintenance for users. Please add some explanation that the `Shoot` status contains information about the last operation.

File: test/integration/controllermanager/shoot/maintenance/maintenance_test.go [hunk 16]
```diff
@@ -342,6 +342,10 @@ var _ = Describe("Shoot Maintenance controller tests", func() {
 				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(shoot), shoot)).To(Succeed())
 				g.Expect(*shoot.Spec.Provider.Workers[0].Machine.Image).To(Equal(gardencorev1beta1.ShootMachineImage{Name: highestAMD64MachineImage.Name, Version: highestAMD64MachineImage.Version}))
 				g.Expect(*shoot.Spec.Provider.Workers[1].Machine.Image).To(Equal(gardencorev1beta1.ShootMachineImage{Name: highestARM64MachineImage.Name, Version: highestARM64MachineImage.Version}))
+				g.Expect(shoot.Status.LastMaintenance).NotTo(BeNil())
+				g.Expect(shoot.Status.LastMaintenance.Description).To(Equal(
+					"Machine image of worker-pool \"cpu-worker1\" upgraded from \"foo-image\" version \"0.0.1-beta\" to version \"1.1.1\". Reason: AutoUpdate of MachineImage configured" + ", " +
+						"Machine image of worker-pool \"cpu-worker2\" upgraded from \"foo-image\" version \"0.0.1-beta\" to version \"1.2.0\". Reason: AutoUpdate of MachineImage configured"))
```
Comment (rfranzke) [inline test/integration/controllermanager/shoot/maintenance/maintenance_test.go]: Why do you only assert the `Description` field? The test could become more accurate by also asserting some other fields of the `LastMaintenance` struct. Same below.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 17]
```diff
@@ -93,99 +96,151 @@ func requeueAfterDuration(shoot *gardencorev1beta1.Shoot) (time.Duration, time.T
...
-	shootSemver, err := semver.NewVersion(shoot.Spec.Kubernetes.Version)
+	shootKubernetesVersion, err := semver.NewVersion(maintainedShoot.Spec.Kubernetes.Version)
 	if err != nil {
 		return err
 	}
 
 	// Now it's time to update worker pool kubernetes version if specified
-	var reasonsForWorkerPoolKubernetesUpdate = make(map[string]string)
-	for i, w := range shoot.Spec.Provider.Workers {
+	for i, w := range maintainedShoot.Spec.Provider.Workers {
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
	for i, pool := range maintainedShoot.Spec.Provider.Workers {
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 18]
```diff
@@ -93,99 +96,151 @@ func requeueAfterDuration(shoot *gardencorev1beta1.Shoot) (time.Duration, time.T
...
 	}
+	operations = append(operations, reasonForImageUpdatePerPool...)
 
-	reasonForKubernetesUpdate, err := maintainKubernetesVersion(log, shoot.Spec.Kubernetes.Version, shoot.Spec.Maintenance.AutoUpdate.KubernetesVersion, cloudProfile, func(v string) error {
-		shoot.Spec.Kubernetes.Version = v
+	reasonForKubernetesUpdate, err := maintainKubernetesVersion(log, maintainedShoot.Spec.Kubernetes.Version, maintainedShoot.Spec.Maintenance.AutoUpdate.KubernetesVersion, cloudProfile, func(v string) error {
+		maintainedShoot.Spec.Kubernetes.Version = v
 		return nil
-	})
+	}, "Shoot")
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
	}, "Control Plane")
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 19]
```diff
@@ -195,9 +250,16 @@ func maintainOperation(shoot *gardencorev1beta1.Shoot) {
...
+		operation = getOperation(shoot)
+		metav1.SetMetaDataAnnotation(&shoot.ObjectMeta, v1beta1constants.GardenerOperation, operation)
 		delete(shoot.Annotations, v1beta1constants.GardenerMaintenanceOperation)
 	}
+
+	if operation != "" && operation != v1beta1constants.GardenerOperationReconcile {
+		return operation
+	}
+
+	return ""
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
	if operation == v1beta1constants.GardenerOperationReconcile {
		return ""
	}

	return operation
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 20]
```diff
@@ -93,99 +96,151 @@ func requeueAfterDuration(shoot *gardencorev1beta1.Shoot) (time.Duration, time.T
...
+
+		// First dry run the update call to check if it can be executed successfully.
+		// If not shoot maintenance is marked as failed and is retried only in
+		// next maintenance window.
+		if err := r.Client.Update(ctx, maintainedShoot, &client.UpdateOptions{
+			DryRun: []string{metav1.DryRunAll},
+		}); err != nil {
+			// If shoot maintenance is triggerd by `gardener.cloud/operation=maintain` annotation and if it fails in dry run
+			// maintain operation annotation need to be removed so that if reason for failure is fixed and maintenance is triggerd
+			// again using maintain operation annotation then it should not fail with the reason that annotation is already present
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
			// If shoot maintenance is triggered by `gardener.cloud/operation=maintain` annotation and if it fails in dry run,
			// then 'maintain' operation annotation needs to be removed so that if reason for failure is fixed and maintenance is triggered
			// again via 'maintain' operation annotation then it should not fail with the reason that annotation is already present
```

I'm missing some explanation that we are using the `shoots/status` subresource here but can still remove the annotation (even though this is in `metadata` and not `status`).

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 21]
```diff
@@ -93,99 +96,151 @@ func requeueAfterDuration(shoot *gardencorev1beta1.Shoot) (time.Duration, time.T
...
-	if err := gardenClient.Update(ctx, shoot); err != nil {
+	if err := r.Client.Update(ctx, shoot); err != nil {
 		r.Recorder.Event(shoot, corev1.EventTypeWarning, gardencorev1beta1.ShootMaintenanceFailed, err.Error())
 		return err
 	}
 
+	if shoot.Status.LastMaintenance != nil && shoot.Status.LastMaintenance.State == gardencorev1beta1.LastOperationStateProcessing {
+		patch := client.MergeFrom(shoot.DeepCopy())
+		shoot.Status.LastMaintenance.State = gardencorev1beta1.LastOperationStateSucceeded
+		if err := r.Client.Status().Patch(ctx, shoot, patch); err != nil {
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go:220]: Do we have to set `FailureReason` to `nil` here in case it was set before and the issue preventing maintenance got fixed meanwhile?

**Review by rfranzke — COMMENTED** [review]
Thanks, a few small comments left.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 20 above)
Comment (acumino) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: Yes, here on status update only `ShootSpec` is kept in its original form.
https://github.com/gardener/gardener/blob/a2f7de0badaae6170d7b9b84c163b8cab43a84d2/pkg/registry/core/shoot/strategy.go#L258-L267

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 21 above)
Comment (acumino) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go:220]: No, For a reconciliation to reach this point, it should succeed in previous steps, i.e. for the case, if the failure reason is set, the next reconciliation will reach this point with shoot status having a new last maintenance value in which the failure reason will be nil.

**Comment by shafeeqes** [comment]
I don't have any further comments. lgtm.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 20 above)
Comment (rfranzke) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: Yes, but I asked you to enhance this comment here because it was not obvious (at least to me) that this is possible (updating metadata with `status` subresource).

**Comment by rfranzke** [comment]
Please add a release note for end users.

**Review by rfranzke — COMMENTED** [review]
No further suggestions except for the above.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 20 above)
Comment (acumino) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: Done PTAL.

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Comment by rfranzke** [comment]
/milestone v1.62

cc @oliver-goetz

**Comment by acumino** [comment]
> @acumino: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-apidiff	[0218655](https://github.com/gardener/gardener/commit/02186557fff10ab66d4111d37667ca5fc110dfe3)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7035/pull-gardener-apidiff/1602585415175376896)	false	`/test pull-gardener-apidiff`
> pull-gardener-integration	[0218655](https://github.com/gardener/gardener/commit/02186557fff10ab66d4111d37667ca5fc110dfe3)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7035/pull-gardener-integration/1602607380611207168)	unknown	`/test pull-gardener-integration`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=7035). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Aacumino). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

Not related to this PR. Opened issue https://github.com/gardener/gardener/issues/7200
/test pull-gardener-integration
