### PR TITLE
Use managed resource for shoot cluster's envoy filter resource.

### LINKED ISSUE #8982: Shoot-specific `EnvoyFilter` Remains in Old Ingress Namespace when Upgrading `Shoot` to Zone-HA
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:

A Shoot runs on a zonal-HA Seed, but is itself not highly available. This means it uses an ingress namespace like `istio-ingress--az-1`, i.e. a "zonal" ingress namespace for the zone its control plane is in. When converting this `Shoot` to Zone-HA (`controlPlane.highAvailability.failureTolerance.type: zone`), its ingress namespace changes (to `istio-ingress`). With this change, a Shoot -specific `EnvoyFilter` is created in the `istio-ingress` namespace. In our environment, we're observing that the shoot-specific `EnvoyFilter` in the previous (non-HA) ingress namespace remains after converting the `Shoot` to HA. This is not bad per se (no traffic is routed via this ingress anymore for the Shoot in question), but it seems like something that should be removed to fully complete the switch.

**What you expected to happen**:

After the conversion of the `Shoot` to zonal HA, I expect the non-HA ingress namespace (for the single zone the `Shoot`s control plane used to be in) to have no leftovers from this particular `Shoot`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy a non-HA `Shoot` on an HA `Seed`, so that it uses a zonal ingress namespace (let's say `istio-ingress--az-1` for clarity).
2. Confirm that Gardener has created an `Envoyfilter` object in that ingress namespace, called `shoot-<projectID>-<shootName>`.
4. Upgrade the `Shoot` to zone-HA by setting `controlPlane.highAvailability.failureTolerance.type: zone` and wait for the `Shoot` to be converted.
5. Observe the newly created `EnvoyFilter` object in the HA ingress namespace (`istio-ingress`) with the same name as in the old namespace (`shoot-<projectID>-<shootName>`).
6. In the old ingress namespace `istio-ingress--az-1`, the `shoot-<projectID>-<shootName>` `EnvoyFilter` still exists (unnecessarily).

**Anything else we need to know?**:

This issue has been opened based on [this slack thread](https://gardener-cloud.slack.com/archives/C047S4N9NTV/p1702906700265569).

**Environment**:

- Gardener version: current (`v1.86.0`)
- Cloud provider or hardware configuration: OpenStack

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/area high-availability
/area ops-productivity
/kind cleanup

**What this PR does / why we need it**:
Use managed resource for shoot cluster's envoy filter resource.

To implement `kubernetes.default.svc.cluster.local` the SNI approach uses `apiserver-proxy` component in the shoot cluster and an envoy filter on the seed. Unfortunately, istio requires the envoy filter to be deployed in the istio ingress gateway namespace even though it semantically belongs to the shoot cluster control plane.
With the high-availability support in Gardener, the istio ingress gateway responsible for shoot cluster control plane may change when it is upgraded to be multi-zonal. Previously, the necessary envoy filter was created in the new target namespace, but the old one was left as is. (It would be deleted eventually when the shoot cluster would be deleted due to an owner reference.)
This could be confusing. Therefore, this change moves the envoy filter into a managed resource thereby ensuring that a move will automatically delete the old resource. The result will be that only the current version will be there for new clusters.
(This change does not handle existing envoy filters that could be deleted. Operators are expected to delete them eventually or wait for the shoot clusters to be deleted, which also cleans up the envoy filters.)

**Which issue(s) this PR fixes**:
Fixes #8982 

**Special notes for your reviewer**:
This change does not handle existing envoy filters that could be deleted. Operators are expected to delete them eventually or wait for the shoot clusters to be deleted, which also cleans up the envoy filters.

Feel free to comment if you think this is not sufficient.

**Release note**:

```other operator
When upgrading a shoot control plane to multi-zonal high-availability there will no longer be an envoy filter left in the old istio ingress namespace
```

### CODE REVIEW

File: pkg/component/kubeapiserverexposure/kube_apiserver_sni.go [hunk 1]
```diff
@@ -38,9 +38,13 @@ import (
 	kubeapiserverconstants "github.com/gardener/gardener/pkg/component/kubeapiserver/constants"
 	"github.com/gardener/gardener/pkg/controllerutils"
 	kubernetesutils "github.com/gardener/gardener/pkg/utils/kubernetes"
+	"github.com/gardener/gardener/pkg/utils/managedresources"
 	netutils "github.com/gardener/gardener/pkg/utils/net"
 )
 
+// ManagedResourceName is the name of the managed resource for the envoy filter.
+const ManagedResourceName = "kube-apiserver-sni"
```
Comment (plkokanov) [inline pkg/component/kubeapiserverexposure/kube_apiserver_sni.go]: Minor nit: does this have to be exported, I don't see it being used in other packages apart from the test and I think for tests we specify the name of the resources directly instead of reusing the expected variable name.

File: pkg/component/kubeapiserverexposure/kube_apiserver_sni.go [hunk 2]
```diff
@@ -144,7 +145,11 @@ func (s *sni) Deploy(ctx context.Context) error {
 		}); err != nil {
 			return err
 		}
-		if err := s.applier.ApplyManifest(ctx, kubernetes.NewManifestReader(envoyFilterSpec.Bytes()), kubernetes.DefaultMergeFuncs); err != nil {
+
+		filename := fmt.Sprintf("envoyfilter__%s__%s.yaml", envoyFilter.Namespace, s.namespace)
```
Comment (plkokanov) [inline pkg/component/kubeapiserverexposure/kube_apiserver_sni.go]: Nit since I find it a bit less confusing:
```suggestion
		filename := fmt.Sprintf("envoyfilter__%s__%s.yaml", envoyFilter.Namespace, envoyFilter.Name)
```

File: pkg/component/kubeapiserverexposure/kube_apiserver_sni_test.go [hunk 3]
```diff
@@ -234,8 +244,22 @@ var _ = Describe("#SNI", func() {
...
+				managedResourceSecret := &corev1.Secret{}
+				Expect(c.Get(ctx, kubernetesutils.Key(expectedManagedResource.Namespace, expectedManagedResource.Spec.SecretRefs[0].Name), managedResourceSecret)).To(Succeed())
+				Expect(managedResourceSecret.Type).To(Equal(corev1.SecretTypeOpaque))
+				Expect(managedResourceSecret.Data).To(HaveLen(1))
+				Expect(managedResourceSecret.Immutable).To(Equal(pointer.Bool(true)))
+				Expect(managedResourceSecret.Labels["resources.gardener.cloud/garbage-collectable-reference"]).To(Equal("true"))
+
+				managedResourceEnvoyFilter, _, err := kubernetes.ShootCodec.UniversalDecoder().Decode(managedResourceSecret.Data["envoyfilter__istio-foo__test-namespace.yaml"], nil, &istionetworkingv1alpha3.EnvoyFilter{})
+				Expect(err).ToNot(HaveOccurred())
+				actualEnvoyFilter := managedResourceEnvoyFilter.(*istionetworkingv1alpha3.EnvoyFilter)
```
Comment (plkokanov) [inline pkg/component/kubeapiserverexposure/kube_apiserver_sni_test.go:263]: Does it make sense to add an additional check if `managedResourceEnvoyFilter` actually is of type `*istionetworkingv1alpha3.EnvoyFilter` to avoid a potential nil ptr on line 264?

**Review by plkokanov — CHANGES_REQUESTED** [review]
We had a joint look at this PR with @Kostov6 and saw only some nits.

Additionally, do you think it makes sense/is possible to add an additional check in our `e2e` test for changing shoots from non-ha  to ha (e.g. [here](https://github.com/gardener/gardener/blob/9dc89fe827ae2c3a4948d85df3b7a8da1c816e86/test/utils/shoots/update/highavailability/upgrade.go#L41)) that verifies this functionality?

File: pkg/component/kubeapiserverexposure/kube_apiserver_sni.go (hunk 1 above)
Comment (ScheererJ) [reply pkg/component/kubeapiserverexposure/kube_apiserver_sni.go]: Good point. Adapted with https://github.com/gardener/gardener/pull/9005/commits/ebe0798b278ea2d255b4fd244e1a6305e8fb8091.

File: pkg/component/kubeapiserverexposure/kube_apiserver_sni.go (hunk 2 above)
Comment (ScheererJ) [reply pkg/component/kubeapiserverexposure/kube_apiserver_sni.go]: Included in https://github.com/gardener/gardener/pull/9005/commits/ebe0798b278ea2d255b4fd244e1a6305e8fb8091.

File: pkg/component/kubeapiserverexposure/kube_apiserver_sni_test.go (hunk 3 above)
Comment (ScheererJ) [reply pkg/component/kubeapiserverexposure/kube_apiserver_sni_test.go:263]: Added another check with https://github.com/gardener/gardener/pull/9005/commits/ebe0798b278ea2d255b4fd244e1a6305e8fb8091.

**Comment by ScheererJ** [comment]
> We had a joint look at this PR with @Kostov6 and saw only some nits.
> 
> Additionally, do you think it makes sense/is possible to add an additional check in our `e2e` test for changing shoots from non-ha to ha (e.g. [here](https://github.com/gardener/gardener/blob/9dc89fe827ae2c3a4948d85df3b7a8da1c816e86/test/utils/shoots/update/highavailability/upgrade.go#L41)) that verifies this functionality?

Thanks for the feedback.

I added checks to the end-to-end upgrade tests as suggested.

PTAL.

File: test/utils/shoots/update/highavailability/upgrade.go [hunk 4]
```diff
@@ -172,3 +175,22 @@ func DeployZeroDownTimeValidatorJob(ctx context.Context, c client.Client, testNa
...
+	envoyFilters := &istionetworkingv1alpha3.EnvoyFilterList{}
+	Expect(seedClient.Client().List(ctx, envoyFilters)).To(Succeed(), "trying to list envoy filters, but did not succeed.")
+	filteredList := []*istionetworkingv1alpha3.EnvoyFilter{}
+	for _, filter := range envoyFilters.Items {
+		if filter.Name != shootName {
+			continue
+		}
+		filteredList = append(filteredList, filter)
+	}
+	Expect(filteredList).To(HaveLen(1))
```
Comment (plkokanov) [inline test/utils/shoots/update/highavailability/upgrade.go]: I saw that the test fails here because this returns a list with length of 2. Could it be due to caching or a delay in GRM to clean up the old resource? Maybe you could try putting this check in an `Eventually` block?

Comment (ScheererJ) [reply test/utils/shoots/update/highavailability/upgrade.go]: Thanks for looking into it. I tried to resolve this with https://github.com/gardener/gardener/pull/9005/commits/5a3055444637785137d4b7d1e6be553330cd7a54 and also fixed my incorrect assumptions concerning the istio namespace names (single zone seeds do not have special zonal namespaces for obvious reasons).

**Comment by ScheererJ** [comment]
Apparently, `pull-gardener-e2e-kind` failed as the shoot could not be scheduled to the local seed:

`gardener-scheduler` logs:

```
2024-01-24T13:24:24.142469652Z stderr F {"level":"error","ts":"2024-01-24T13:24:24.142Z","msg":"Reconciler error","controller":"shoot","controllerGroup":"core.gardener.cloud","controllerKind":"Shoot","Shoot":{"name":"e2e-invalid-dns","namespace":"garden-local"},"namespace":"garden-local","name":"e2e-invalid-dns","reconcileID":"1c56fe9f-aab3-4efb-8048-ef7d80924f27","error":"failed to determine seed for shoot: none of the 1 seeds is valid for scheduling (not deleting, visible and ready)","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```

Corresponding event:

```
33s         Warning   SchedulingFailed       shoot/e2e-invalid-dns                                                              Failed to schedule Shoot: none of the 1 seeds is valid for scheduling (not deleting, visible and ready)
```

/retest

**Review by plkokanov — COMMENTED** [review]
Sorry for the delay and thanks for updating the tests.
/approve
