### PR TITLE
Fix `gardenadm` e2e test flakes by waiting for static pods to be rolled out

### LINKED ISSUE #12332: [Flaky Test] `e2e-kind-gardenadm`: `should ensure that extension webhooks on control plane components are functioning`
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:

`Test E2E gardenadm Suite: [It] gardenadm high-touch scenario tests Single-node control plane should ensure that extension webhooks on control plane components are functioning [gardenadm, high-touch, single]`

**CI link**:

- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/12267/pull-gardener-e2e-kind-gardenadm/1934601371655344129
- https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind-gardenadm/1934500043293724672

**Reason for failure**:

The `kube-scheduler-machine-0` pod does not have the `injected-by=provider-local` label.
```
  [FAILED] A spec timeout occurred and then the following failure was recorded in the timedout node before it exited:
  Context was cancelled (cause: spec timeout occurred) after 60.001s.
  Expected
      <map[string]string | len:7>: {
          "networking.gardener.cloud/to-dns": "allowed",
          "networking.resources.gardener.cloud/to-kube-apiserver-tcp-443": "allowed",
          "role": "scheduler",
          "static-pod": "true",
          "app": "kubernetes",
          "gardener.cloud/role": "controlplane",
          "maintenance.gardener.cloud/restart": "true",
      }
  to have {key: value}
      <map[interface {}]interface {} | len:1>: {
          <string>"injected-by": <string>"provider-local",
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardenadm/hightouch/gardenadm.go:185 @ 06/16/25 13:31:20.005
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
- Static pod translator computes a hash of the desired static pod and puts it as annotation to the static pod manifest
- Additionally, this hash is stored in the autonomous botanist
- Later, we compare this hash with the actual hash on the mirror pod
- If it is equal, we know that our desired state has been rolled out

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/12332

**Special notes for your reviewer**:
/cc @timebertt 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/gardenadm/staticpod/translator_test.go [hunk 1]
```diff
@@ -60,14 +60,20 @@ var _ = Describe("Translator", func() {
 			})
 
 			It("should successfully translate a deployment w/o volumes", func() {
-				Expect(Translate(ctx, fakeClient, deployment, nil)).To(HaveExactElements(extensionsv1alpha1.File{
+				expectedHash := "fcb8535b78ef1f7dedef28177099bd7824a14188b75e13a79f1c24c7df7d2b68"
+
+				files, hash, err := Translate(ctx, fakeClient, deployment, nil)
+				Expect(err).NotTo(HaveOccurred())
+				Expect(hash).To(Equal(expectedHash))
```
Comment (timebertt) [inline pkg/gardenadm/staticpod/translator_test.go]: When changing the translator logic, one would need to run the tests and update all expected hashes. This seems tedious to me.
You can ensure that the returned hash value is not empty and expect the annotation value to match the returned hash value. That should be good enough to verify this functionality.

File: pkg/gardenadm/botanist/controlplane.go [hunk 2]
```diff
@@ -128,7 +131,40 @@ func (b *AutonomousBotanist) DeployControlPlaneDeployments(ctx context.Context)
...
 	}
 
-	return managedresources.WaitUntilHealthyAndNotProgressing(ctx, b.SeedClientSet.Client(), b.Shoot.ControlPlaneNamespace, botanist.GardenerNodeAgentManagedResourceName)
+	return nil
+}
+
+// WaitUntilControlPlaneDeploymentsReady waits until the control plane deployments are ready. It checks that the
+// operating system config has been updated for all worker pools. In addition, it verifies that the static pod hashes
+// match the desired hashes.
+func (b *AutonomousBotanist) WaitUntilControlPlaneDeploymentsReady(ctx context.Context) error {
```
Comment (timebertt) [inline pkg/gardenadm/botanist/controlplane.go:140]: Can you add unit tests for this function?

**Review by timebertt — COMMENTED** [review]
Very nice PR. Thanks for tackling this flake!
Only some testing nits from my side.

**Review by timebertt — APPROVED** [review]
Very nice, thanks!
