### PR TITLE
Deflake `Renew gardenlet kubeconfig` e2e test

### LINKED ISSUE #8954: [Flaky Test] Seed Tests Renew gardenlet kubeconfig
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
Seed Tests Renew gardenlet kubeconfig [It] should renew the gardenlet garden kubeconfig when triggered by annotation
```
 [FAILED] in [It] - /home/prow/go/src/github.com/gardener/gardener/test/utils/rotation/gardenlet_kubeconfig.go:121 @ 12/05/23 11:14:42.037
  < Exit [It] should renew the gardenlet garden kubeconfig when triggered by annotation @ 12/05/23 11:14:42.037 (5m26.823s)
  << Timeline
  [FAILED] Timed out after 300.000s.
  Expected success, but got an error:
      <*errors.errorString | 0xc00097bb70>: 
      kubeconfig secret has not yet been renewed, timeBeforeRotation: 2023-12-05 11:09:15.213976419 +0000 UTC, newClientCertificateIssuedAt: 2023-12-05 10:55:37 +0000 UTC
      {
          s: "kubeconfig secret has not yet been renewed, timeBeforeRotation: 2023-12-05 11:09:15.213976419 +0000 UTC, newClientCertificateIssuedAt: 2023-12-05 10:55:37 +0000 UTC",
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/utils/rotation/gardenlet_kubeconfig.go:121 @ 12/05/23 11:14:42.037
```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8869/pull-gardener-e2e-kind/1731988540067155968
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8906/pull-gardener-e2e-kind/1732023885148196864
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8897/pull-gardener-e2e-kind/1732238516160565248
https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1732244661927415808

**Reason for failure**:

**Anything else we need to know**:
In all the case which is mentioned, the selected seed is `e2e-managedseed`.
/cc @oliver-goetz

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
`Renew gardenlet kubeconfig` e2e test is flaking when it runs on `e2e-managedseed`. I found two possible reasons for this behavior:
1. The same functionality is already tested in the managedseed e2e test ([ref](https://github.com/gardener/gardener/blob/e14f57ac4c652f2aefc0b2b90ef74e91e6ff05ac/test/e2e/gardener/managedseed/create_rotate_delete.go#L121-L146)) which might interfere with the `Renew gardenlet kubeconfig` e2e test.
2. `e2e-managedseed` seed is created and deleted in its e2e test. Thus, it can happen that the seed is deleted while `Renew gardenlet kubeconfig` e2e test is still running

This PR ensures that `Renew gardenlet kubeconfig` e2e test does not run on `e2e-managedseed` to avoid these potential side effects.

**Which issue(s) this PR fixes**:
Fixes #8954

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ary1992 — COMMENTED** [review]
Thanks for the fix!
/lgtm

File: test/e2e/gardener/seed/renew_gardenlet_kubeconfig.go [hunk 1]
```diff
@@ -30,10 +30,18 @@ var _ = Describe("Seed Tests", Label("Seed", "default"), func() {
...
+			// Find the first seed which is not "e2e-managedseed". Seed name differs between test scenarios, e.g., non-ha/ha.
+			// However, this test should not use "e2e-managedseed", because it is created and deleted in a separate e2e test.
+			// This e2e test already includes tests for the "Renew gardenlet kubeconfig" functionality. Additionally,
+			// it might be already gone before the kubeconfig was renewed.
 			seedList := &gardencorev1beta1.SeedList{}
-			Expect(testClient.List(ctx, seedList, client.Limit(1))).To(Succeed())
-			seed = seedList.Items[0].DeepCopy()
+			Expect(testClient.List(ctx, seedList)).To(Succeed())
+			for _, s := range seedList.Items {
+				if s.Name != "e2e-managedseed" {
```
Comment (shafeeqes) [inline test/e2e/gardener/seed/renew_gardenlet_kubeconfig.go]: Should we define a constant in `test/e2e/gardener/managedseed/create_rotate_delete.go` and use it here and https://github.com/gardener/gardener/blob/f00fed7fb29ae98661e7d004adec198068a8452e/test/e2e/gardener/managedseed/create_rotate_delete.go#L56
as well?

**Review by shafeeqes — COMMENTED** [review]
Thanks a lot for the fix, just one minor question.

File: test/e2e/gardener/seed/renew_gardenlet_kubeconfig.go (hunk 1 above)
Comment (oliver-goetz) [reply test/e2e/gardener/seed/renew_gardenlet_kubeconfig.go]: good idea 😄 
While changing that, I found the same issue in `Garden Cluster Access For Seed Components` e2e test and applied the logic here as well

**Comment by shafeeqes** [comment]
Thanks!
/lgtm
/approve
