### PR TITLE
Skip problematic webhook check for Gardener-managed webhooks

### LINKED ISSUE #6562: Problematic webhook reported for provider local
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
When creating a shoot with `provider-local`, e.g. `example/provider-loca/shoot.yaml`, the following constraints are reported:

```
    constraints:
    - codes:
      - ERR_PROBLEMATIC_WEBHOOK
      lastTransitionTime: "2022-08-22T19:10:36Z"
      lastUpdateTime: "2022-08-22T19:00:05Z"
      message: 'MutatingWebhookConfiguration "gardener-extension-provider-local-shoot"
        is problematic: webhook "node-shoot.local.extensions.gardener.cloud" with
        failurePolicy "Fail" and 1s timeout might prevent worker nodes from properly
        joining the shoot cluster'
      reason: ProblematicWebhooks
      status: Progressing
      type: HibernationPossible
    - codes:
      - ERR_PROBLEMATIC_WEBHOOK
      lastTransitionTime: "2022-08-22T19:10:36Z"
      lastUpdateTime: "2022-08-22T19:00:05Z"
      message: 'MutatingWebhookConfiguration "gardener-extension-provider-local-shoot"
        is problematic: webhook "node-shoot.local.extensions.gardener.cloud" with
        failurePolicy "Fail" and 1s timeout might prevent worker nodes from properly
        joining the shoot cluster'
      reason: ProblematicWebhooks
      status: Progressing
      type: MaintenancePreconditionsSatisfied
```

This unfortunately forbids to hibernate the cluster which is extremely useful when testing locally 😄 

**What you expected to happen**:
The webhook to be skipped (?!) from the checks and not to be reported as problematic.

**How to reproduce it (as minimally and precisely as possible)**:
Follow https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md#creating-a-shoot-cluster to create a shoot cluster with provider local.

**Anything else we need to know?**:
It's not yet clear why the [hibernation e2e test](https://github.com/gardener/gardener/blob/master/test/e2e/shoot/create_hibernate_wakeup_delete.go) does not fail.

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area ops-productivity dev-productivity
/kind enhancement

**What this PR does / why we need it**:
- Gardener-managed webhooks are no longer considered by the shoot care controller when it comes to find problematic webhooks.
- The `node-shoot` webhook was using `Fail` failure policy, but `Ignore` is good enough and is more relaxed which is fine for the local setup.

**Which issue(s) this PR fixes**:
Fixes #6562 

**Release note**:

```other operator
Gardener-managed webhooks are no longer considered by the shoot care controller when it comes to finding problematic webhooks.
```

### CODE REVIEW

File: pkg/operation/care/constraints.go [hunk 1]
```diff
@@ -252,6 +253,10 @@ func (c *Constraint) CheckForProblematicWebhooks(ctx context.Context) (gardencor
 	}
 
 	for _, webhookConfig := range validatingWebhookConfigs {
+		if strings.Contains(webhookConfig.Annotations[resourcesv1alpha1.OriginAnnotation], c.shoot.SeedNamespace) {
```
Comment (acumino) [inline pkg/operation/care/constraints.go]: Should we use the label selector here to select based on `resources.gardener.cloud/managed-by` label which was introduced with https://github.com/gardener/gardener/pull/6393?

**Comment by oliver-goetz** [comment]
Apart from @acumino comment to `resources.gardener.cloud/managed-by` label, lgtm

File: pkg/operation/care/constraints.go [hunk 2]
```diff
@@ -252,6 +254,10 @@ func (c *Constraint) CheckForProblematicWebhooks(ctx context.Context) (gardencor
...
+			continue
+		}
```
Comment (acumino) [inline pkg/operation/care/constraints.go]: This is not required as we will get only that webhook here that doesn't have `resources.gardener.cloud/managed-by` label.

File: pkg/operation/care/constraints.go [hunk 3]
```diff
@@ -278,6 +284,10 @@ func (c *Constraint) CheckForProblematicWebhooks(ctx context.Context) (gardencor
 	}
 
 	for _, webhookConfig := range mutatingWebhookConfigs {
+		if strings.Contains(webhookConfig.Annotations[resourcesv1alpha1.OriginAnnotation], c.shoot.SeedNamespace) {
+			continue
+		}
```
Comment (acumino) [inline pkg/operation/care/constraints.go]: Same here.

**Review by acumino — CHANGES_REQUESTED** [review]

**Review by acumino — COMMENTED** [review]
/lgtm
