### PR TITLE
resource-manager: Ignore the `ToBeDeletedByClusterAutoscaler` taint in the system-components-config webhook

### LINKED ISSUE #8154: GRM's system-components-config webhook should not add the `ToBeDeletedByClusterAutoscaler` toleration (maintained by the cluster-autoscaler)
**How to categorize this issue?**

/area ops-productivity
/kind bug

**What happened**:
With @rishabh-11 we found the following issue:
Key logs from the event logger:
```
2023-06-22 03:38:39	{"_entry":"Scale-down: removing node shoot--foo--bar-worker-opt-z3-56ccb-k9rzq, utilization: {0.00859322033898305 0.0032986741384152035 0 cpu 0.00859322033898305}, pods to reschedule: vpn-shoot-0","count":1,"firstTimestamp":"2023-06-22T03:38:39Z","lastTimestamp":"2023-06-22T03:38:39Z","namespace":"kube-system","object":"ConfigMap/cluster-autoscaler-status","origin":"shoot","reason":"ScaleDown","source":"cluster-autoscaler","type":"Normal"}
2023-06-22 03:38:39	{"_entry":"deleting pod for node scale down","count":1,"firstTimestamp":"2023-06-22T03:38:39Z","lastTimestamp":"2023-06-22T03:38:39Z","namespace":"kube-system","object":"Pod/vpn-shoot-0","origin":"shoot","reason":"ScaleDown","source":"cluster-autoscaler","type":"Normal"}

2023-06-22 03:39:11	{"_entry":"Successfully assigned kube-system/vpn-shoot-0 to shoot--foo--bar-worker-opt-z3-56ccb-k9rzq","eventTime":"2023-06-22T03:39:11.984938Z","namespace":"kube-system","object":"Pod/vpn-shoot-0","origin":"shoot","reason":"Scheduled","type":"Normal"}
```

You can see that the kube-system/vpn-shoot-0 Pod was successfully evicted. But the issue is that then it got scheduled to the same Node.
This is a cluster with the following cluster-autoscaler config:
```yaml
spec:
  kubernetes:
    clusterAutoscaler:
      maxGracefulTerminationSeconds: 129600 # 36h
```

We see that currently the vpn-shoot-0 Pod (and my other gardener Pods) tolerate the cluster-autoscaler taints:
```yaml
% k -n kube-system get po vpn-shoot-0 -o yaml | yq '.spec.tolerations'
- effect: PreferNoSchedule
  key: DeletionCandidateOfClusterAutoscaler
  operator: Equal
  value: "1687320358"
- effect: NoSchedule
  key: ToBeDeletedByClusterAutoscaler
  operator: Equal
  value: "1687448378"
- effect: PreferNoSchedule
  key: DeletionCandidateOfClusterAutoscaler
  operator: Equal
  value: "1687404718"
- effect: NoSchedule
  key: ToBeDeletedByClusterAutoscaler
  operator: Equal
  value: "1687448388"
- effect: NoExecute
  key: node.kubernetes.io/not-ready
  operator: Exists
  tolerationSeconds: 60
- effect: NoExecute
  key: node.kubernetes.io/unreachable
  operator: Exists
  tolerationSeconds: 60
```

You can see that the vpn-shoot-0 is tolerating the ToBeDeletedByClusterAutoscaler taint. Hence, such evicted Pod can be scheduled on a Node that is being scaled down by cluster-autoscaler. The component causing the troubles is the GRM's system-components-config webhook (introduced with https://github.com/gardener/gardener/pull/7204).

In the corresponding webhook in gardener-resource-manager we have to make sure that the cluster-autoscaler taint(s) are not messed up because it breaks cluster-autoscaler handling.

Because of this, cluster-autoscaler enters in https://github.com/gardener/autoscaler/blob/c127763a4529d7d07961102856afe0ba8781f8ee/cluster-autoscaler/core/scaledown/actuation/drain.go#L133-L155 and waits for `maxGracefulTerminationSeconds` (36h) in this case until it drains the Node.

**What you expected to happen**:
GRM's system-components-config webhook should not add the `ToBeDeletedByClusterAutoscaler` taint. It simply breaks cluster-autoscaler's internal drain/eviction for Node scale down.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.73.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area quality ops-productivity
/kind bug

**What this PR does / why we need it**:
See https://github.com/gardener/gardener/issues/8154

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/8154

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
`gardener-resource-manager`'s `system-components-config` webhook no longer adds the toleration for the `ToBeDeletedByClusterAutoscaler` taint to system components in shoot clusters. The `ToBeDeletedByClusterAutoscaler` taint is maintained by the `cluster-autoscaler`. This was breaking `cluster-autoscaler`'s drain mechanism when scaling down an under-utilized node. It was causing just evicted system components from to be deleted node to be scheduled again on the to be deleted node.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
I need to add a test.

File: pkg/resourcemanager/webhook/systemcomponentsconfig/handler.go [hunk 1]
```diff
@@ -102,9 +102,8 @@ func (h *Handler) handleTolerations(ctx context.Context, log logr.Logger, pod *c
 	// Add required tolerations for existing system component nodes.
 	for _, node := range nodeList.Items {
 		for _, taint := range node.Spec.Taints {
-			// Kubernetes reserved taints must not be added which would circumvent taint based evictions, see https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions.
-			if kubernetesReservedTaint(taint) {
-				log.Info("Kubernetes reserved taint is skipped for toleration calculation", "node", client.ObjectKeyFromObject(&node), "taint", taint.Key)
+			if shouldIgnoreTaint(taint) {
+				log.Info("Taint is ignored for toleration calculation", "node", client.ObjectKeyFromObject(&node), "taint", taint.Key)
```
Comment (rfranzke) [inline pkg/resourcemanager/webhook/systemcomponentsconfig/handler.go]: Should we set this to `V(1)`?

**Review by ScheererJ — COMMENTED** [review]
Thanks a lot for the change.

/lgtm

**Comment by ialidzhikov** [comment]
```

  [FAILED] Expected success, but got an error:
      <*errors.errorString | 0xc00059e400>: 
      failed to verify no running pods after hibernation: found pods in namespace shoot--local--e2e-upg-hib: [etcd-events-2]
      {
          s: "failed to verify no running pods after hibernation: found pods in namespace shoot--local--e2e-upg-hib: [etcd-events-2]",
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/upgrade/upgrade.go:222 @ 06/26/23 09:00:53.1
------------------------------
[ReportAfterSuite] PASSED [630.646 seconds]
```

Seem to be occurrence of https://github.com/gardener/gardener/issues/7266

---

/test pull-gardener-e2e-kind-ha-multi-zone-upgrade

**Comment by ialidzhikov** [comment]
> No tags found for the previous minor version (v1.75.0-dev) to upgrade Gardener.
> make: *** [Makefile:431: ci-e2e-kind-ha-multi-zone-upgrade] Error 1

😕
