### PR TITLE
Protect `Secret`s/`ConfigMap`s referenced in `.spec.resources` of `Shoot`s with finalizer

### LINKED ISSUE #7846: Missing secret audit-secret should not block reconciliation
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

- Some clusters that were marked for deletion could not be deleted because of infrastructure dependencies.
- During the deletion process, the associated `audit-secret` got deleted as well.
- At some point the infrastructure dependencies got resolved
- The clusters are now in a broken state with `lastOperation`:
```
description: 'Flow "Shoot cluster deletion" encountered task errors: [task "Deploying
  referenced resources" failed: retry failed with context deadline exceeded, last
  error: object not found {Secret audit-secret-539-9e-haas v1}]'
lastUpdateTime: '2023-04-25T22:46:01Z'
progress: 13
state: Failed
type: Delete
```
It is not possible anymore to trigger reconciliation for these shoots because of the error.
- I was told by @rfranzke to simply create an empty secret with the referenced name to enable the flow to continue.

If no actual secret is needed to continue here, then why does the controller fail at all? It could simply ignore the missing secret and continue without manual interaction.

**What you expected to happen**:

I expect that it is possible to trigger reconciliation for a shoot in this state.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`): 1.24.10
- Cloud provider or hardware configuration: Azure
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area usability
/kind enhancement

**What this PR does / why we need it**:
Similar to other `Secret`/`ConfigMap` references in the `Shoot`, with this PR we are now also protecting those referenced in `.spec.resources` of `Shoot`s with a finalizer. This makes sure that such resources do not disappear from the system as long as they are still referenced somewhere.

**Which issue(s) this PR fixes**:
Fixes #7846

**Special notes for your reviewer**:
/cc @timuthy 

**Release note**:

```feature user
`Secret`s/`ConfigMap`s referenced in `.spec.resources` of `Shoot`s are now protected with a finalizer to ensure they do not disappear from the system as long as they are still referenced somewhere.
```

### CODE REVIEW

**Review by shafeeqes — COMMENTED** [review]
/lgtm

File: pkg/controllermanager/controller/shoot/reference/reconciler.go [hunk 1]
```diff
@@ -155,29 +158,44 @@ func (r *Reconciler) handleReferencedSecrets(ctx context.Context, log logr.Logge
...
-		if !controllerutil.ContainsFinalizer(configMap, FinalizerName) {
-			log.Info("Adding finalizer to ConfigMap", "configMap", client.ObjectKeyFromObject(configMap))
-			if err := controllerutils.AddFinalizers(ctx, r.Client, configMap, FinalizerName); err != nil {
-				return true, fmt.Errorf("failed to add finalizer to ConfigMap: %w", err)
+	for _, configMapName := range configMapNames {
+		name := configMapName
+		fns = append(fns, func(ctx context.Context) error {
+			configMap := &corev1.ConfigMap{}
+			s := shoot
+			if err := c.Get(ctx, kubernetesutils.Key(s.Namespace, name), configMap); err != nil {
```
Comment (timuthy) [inline pkg/controllermanager/controller/shoot/reference/reconciler.go]:
```suggestion
			if err := c.Get(ctx, kubernetesutils.Key(shoot.Namespace, name), configMap); err != nil {
```
I think you can drop this.

File: pkg/controllermanager/controller/shoot/reference/reconciler.go [hunk 2]
```diff
@@ -124,13 +124,16 @@ func (r *Reconciler) Reconcile(ctx context.Context, request reconcile.Request) (
...
+		)
 	)
 
-	for _, dnsSecretName := range dnsSecretNames {
-		name := dnsSecretName
+	for _, secretName := range secretNames {
+		name := secretName
 		fns = append(fns, func(ctx context.Context) error {
 			secret := &corev1.Secret{}
 			s := shoot
```
Comment (timuthy) [inline pkg/controllermanager/controller/shoot/reference/reconciler.go]: Same here.

**Review by timuthy — COMMENTED** [review]
One nit, rest looks good 🙂

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve
