### PR TITLE
Deflake ExtensionsCheck test and BackupBucketsCheck test

### LINKED ISSUE #6679: [Flaky Test] ExtensionsCheck Integration Test Suite
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
• [FAILED] [5.302 seconds]
Seed ExtensionsCheck controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go:29
  when one ControllerInstallation becomes not valid
  /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go:152
    [It] should set ExtensionsReady to Progressing and eventually to False when condition threshold expires
    /home/prow/go/src/github.com/gardener/gardener/test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go:125

```

**CI link**: 
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6585/pull-gardener-integration/1570059944915374080

**Reason for failure**:

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
Deflakes the seed ExtensionsCheck and BackupBucketsCheck controllers integration tests.

I think that the reason for the latest flake https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6705/pull-gardener-integration/1572124710328602624 is that the check whether the `ExtensionReady` condition is `True` gets evaluated too fast after the creation of the 2nd `ControllerInstallation` [here](https://github.com/gardener/gardener/blob/24dc519d70c664bb64ebe46808320ae9595d3cfc/test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go#L109-L113). That can happen because after creating and updating the conditions of the 1st `ControllerInstallation` the `ExtensionsReady` condition will be set to `True`. Then when the 2nd `ControllerInstallation` is created, the condition is set to `Progressing` and when the 2nd `ControllerInstallation` is updated with successful conditions, the `ExtensionsReady` condition is set to `True` again. However, the test can miss the transition from `True` -> `Progressing` -> `True` and only notice the first `True` condition, which then leads to incorrect expects during the rest of the tests.
However, during local testing I could not reproduce the flake reported in the issue.

I've restructured the tests and the logging, a bit so that hopefully if a flake happens again it is more clear why it is happening.

Theoretically there is one more flake that can happen because of this check here: https://github.com/gardener/gardener/blob/24dc519d70c664bb64ebe46808320ae9595d3cfc/pkg/controllermanager/controller/seed/utils/utils.go#L84-L85
Because the clock [here](https://github.com/gardener/gardener/blob/24dc519d70c664bb64ebe46808320ae9595d3cfc/test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go#L153-L154) can be stepped after line 84, but before line 85, thus the current condition could still be evaluated to `Progressing` as it will be within the threshold, but then its timestamp will be updated as part of the `UpdatedCondition()` call. 

This PR 
**Which issue(s) this PR fixes**:
Fixes #6679

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go [hunk 1]
```diff
@@ -91,34 +95,17 @@ var _ = Describe("Seed ExtensionsCheck controller tests", func() {
...
-
-			By("Wait until ExtensionsReady condition is set to True")
-			Eventually(func(g Gomega) {
-				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(seed), seed)).To(Succeed())
-				g.Expect(seed.Status.Conditions).To(ContainCondition(OfType(gardencorev1beta1.SeedExtensionsReady), WithStatus(gardencorev1beta1.ConditionTrue), WithReason("AllExtensionsReady")))
-			}).Should(Succeed(), "after creation and update of "+controllerInstallation.Name)
-		}
+	JustBeforeEach(func() {
+		createAndUpdateControllerInstallation(ci1, seed, gardencorev1beta1.ConditionFalse)
+		createAndUpdateControllerInstallation(ci2, seed, gardencorev1beta1.ConditionProgressing)
```
Comment (acumino) [inline test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go:102]: Seed `ConditionFalse` will happen here also? or not? in the second case line 102.

Comment (plkokanov) [reply test/integration/controllermanager/seed/extensionscheck/extensionscheck_test.go:102]: Nope. It will become `True` after the first `createAndUpdateControllerInstallation(...)` function finishes. When a second `ControllerInstallation` (that has no conditions) is deployed as part of the second function the condition will transition from `True` to `Progressing` as there is a conditionThreshold that has not expired. Then when the second `ControllerInstallation` conditions are updated to be successful, the `ExtensionsReady` will transition from `Progressing` to `True`

**Review by acumino — APPROVED** [review]
/lgtm
/approve
