### PR TITLE
Prevent updates of existing nodes when CRI name in `ShootSpec` gets changed

### LINKED ISSUE #4415: Nodes which are removed in a rolling update still apply new cloud-config
**How to categorize this issue?**

/area control-plane
/kind bug
/priority 3

**What happened**:

When a rolling node update is triggered, a new worker pool is created and the nodes in the old worker pool are marked as `preferNoSchedule` by the MCM, then drained and in the end removed, once the new nodes are ready. In this process, any changes in the cloud-config are still applied to the old nodes.
This isn't really what we want, because this interferes with draining the node. If the downloader script finds any delta in the hypercube images or the cloud-config, it will reload `systemd` and restart all of our systemd units (kubelet, container runtime, watchers, etc).
Note this does not apply to changes in the k8s `major.minor` version, [as this creates a cloud-config secret with a different name](https://github.com/gardener/gardener/blob/da556e69b265796e7b31f07b58f0b77ef66553c4/pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L625)

**What you expected to happen**:

Nodes which are about to be removed should not apply the new cloud-config – unless we have specific reason for this?

**How to reproduce it (as minimally and precisely as possible)**:
* Create a cluster with a single worker pool
* Change the worker pool configuration, such that a node rollout is triggered
* Observe the old worker download and apply the new configuration

**Anything else we need to know?**:

Discovered in the context of #4254. Just changing the logic on how the cloud config secret name is computed isn't really feasible, as we saw in #4390. If this would be the direction we're going for, we would need some logic to have two secrets (one with the old name, one with the new name) for some period of time, such that we don't break existing clusters, which have the secret-to-be-downloaded in their downloader script on disk. While this script kind of updates itself, we would still need the old secret for at least one successful cloud-config update cycle for each node. 

**Environment**:
- Gardener version: 1.27
- Kubernetes version (use `kubectl version`): 1.20.6
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area os
/kind enhancement

**What this PR does / why we need it**:
Earlier, when the `cri.name` of a worker pool in the `ShootSpec` was changed, existing nodes were updated (i.e., the container runtime was exchanged "in-place") which caused significant disruption to running workload. See https://github.com/gardener/gardener/issues/4415 for the details.

This PR contains two commits:
1. Cherry-pick of #4289
2. Logic for backwards-compatibility to prevent regressions like #4390

The basic idea is outlined in https://github.com/gardener/gardener/issues/4415#issuecomment-1111036368 and https://github.com/gardener/gardener/issues/4415#issuecomment-1111048061. With the next release (v1.48) after this PR got released (v1.46), the second commit as well as #5791 will both be reverted which then will allow "smooth" container runtime updates as initially desired.

**Which issue(s) this PR fixes**:
Fixes #4415

**Special notes for your reviewer**:
Follow-up of #5273
/cc @vpnachev @voelzmo @BeckerMax 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by vlerenc** [comment]
Nice, thanks @rfranzke!

cc @dguendisch If I am not mistaken, this will resolve https://github.tools.sap/kubernetes/landscape-issues/issues/6.

File: pkg/operation/botanist/operatingsystemconfig.go [hunk 1]
```diff
@@ -269,13 +270,23 @@ func (b *Botanist) generateCloudConfigExecutorResourcesForWorker(
...
-		return "", nil, err
+	if err := registry.Add(executor.Secret(secretName, metav1.NamespaceSystem, worker.Name, executorScript)); err != nil {
+		return nil, nil, err
+	}
+
+	// TODO(rfranzke): Remove this legacySecretName in a future release.
+	// Since we changed the logic of the Key function to incorporate the CRI name for
+	// https://github.com/gardener/gardener/issues/4415, the name of the secret changes. To make existing nodes
+	// update to the new secret name, we need to also create the legacy secret name and point it to the new secret.
+	if legacySecretName := operatingsystemconfig.Key(worker.Name, kubernetesVersion, nil); legacySecretName != secretName {
```
Comment (BeckerMax) [inline pkg/operation/botanist/operatingsystemconfig.go:284]: I don't understand this if check.
Isn't this always `true` if any cri is configured? So also for newly created worker pools we create a second cloud-config downloader secret with the old name?
Or what am I missing here?

**Review by BeckerMax — COMMENTED** [review]
For now just a question. I need a bit more time to understand how all the different parts play together to confidently review this PR.

Can someone else please also take a look cc @vpnachev or @voelzmo - so we get a second opinion?

File: pkg/operation/botanist/operatingsystemconfig.go (hunk 1 above)
Comment (rfranzke) [reply pkg/operation/botanist/operatingsystemconfig.go:284]: The `legacySecretName` is different from `secretName` only when the worker pool does use `containerd`. If the worker pool has `.cri=nil` or `.cri.name=docker` then `legacySecretName=secretName`. This is check is to prevent adding the same secret twice to the `ManagedResource`.

File: pkg/gardenlet/controller/shoot/shoot_control_reconcile.go [hunk 2]
```diff
@@ -74,6 +78,14 @@ func (r *shootReconciler) runReconcileShootFlow(ctx context.Context, o *operatio
 				return retryutils.Ok()
 			})
 		}),
+		errors.ToExecute("Check whether control plane exists and is succeeded", func() error {
+			cp := &extensionsv1alpha1.ControlPlane{}
+			if err := o.K8sSeedClient.Client().Get(ctx, kutil.Key(o.Shoot.SeedNamespace, o.Shoot.GetInfo().Name), cp); client.IgnoreNotFound(err) != nil {
+				return err
+			}
+			controlPlaneExistsAndSucceeded = !apierrors.IsNotFound(err) && cp.Status.LastOperation != nil && cp.Status.LastOperation.State == gardencorev1beta1.LastOperationStateSucceeded
+			return nil
```
Comment (ialidzhikov) [inline pkg/gardenlet/controller/shoot/shoot_control_reconcile.go]: At first look with @oliver-goetz we had small confusion with the usages of the multiple not found checks. Maybe a more verbose way that is one idea easier to comprehend at first look:

```suggestion
			cp := &extensionsv1alpha1.ControlPlane{}
			if err := o.K8sSeedClient.Client().Get(ctx, kutil.Key(o.Shoot.SeedNamespace, o.Shoot.GetInfo().Name), cp); err != nil {
				if apierrors.IsNotFound(err) {
					controlPlaneExistsAndSucceeded = false
					return nil
				}

				return err
			}

			controlPlaneExistsAndSucceeded = cp.Status.LastOperation != nil && cp.Status.LastOperation.State == gardencorev1beta1.LastOperationStateSucceeded
			return nil
```

**Review by ialidzhikov — COMMENTED** [review]
I am not done with the review but have to interrupt for now. I am only adding 1 minor inline comment.

**Review by voelzmo — APPROVED** [review]
/lgtm

Here's what I tested:
* created a Shoot from `master` with worker pools having `cri.name: docker` and `cri.name: containerd`. Each pool has its own cc secret.
* switched to this change and saw that the `containerd` pool gets two cloud-config secrets with identical content. The important bit here is that the 'old' secret contains the new downloader script which switches next cc update cycles to the new secret
* reverted the compatibility commit(s) and the commit preventing CRI updates for existing worker pools, saw that there's now only one cc secret per worker pool
* changed the cri from `docker` to `containerd`

All works nicely, thanks!
From my POV, there are two caveats now going forward
* how to be sure that we can revert the compatibility change? We must wait until all nodes (at least the ones on `containerd`) have switched to the new secret – do we have a good way to do this?
* Allowing changes to `cri.name` can only happen again when the compatibility change is removed as well, otherwise updating a worker pool from `nil/docker` to `containerd` will suffer from the same issue. This is covered by @rfranzke's statement in the PR, I just wanted to lay this out one more time explicitly, so we don't miss this!

As an aside: @vpnachev mentioned the Garbage Collection mechanism for secrets/cloud-configs a few times, which I now very little about. Is this a thing that we need to be concerned about, or is this taken care of by the fact that the ManagedResource knows both cc secrets?

**Comment by rfranzke** [comment]
> All works nicely, thanks!

Thanks for testing it!

> how to be sure that we can revert the compatibility change? We must wait until all nodes (at least the ones on containerd) have switched to the new secret – do we have a good way to do this?

I hoped to have covered this with https://github.com/gardener/gardener/pull/5870/commits/f8478ef63b533f2f9df109deb4209ea9bbb62337#diff-b08cfdfda24a4eb57a4f1f324e3747cb5b65932440624fbf7e2403b76e8c26b5R174-R193. This ensures that the OSC as well as the `cloud-config` secrets are regenerated as early as possible in the flow.
Hence, everybody by following https://github.com/gardener/gardener/blob/master/docs/deployment/version_skew_policy.md#supported-component-upgrade-order we can revert the changes with the next Gardener release and be sure that all existing nodes have been updated.
Do you have concerns with this approach or any idea of corner cases that I might have missed?

> As an aside: @vpnachev mentioned the Garbage Collection mechanism for secrets/cloud-configs a few times, which I now very little about. Is this a thing that we need to be concerned about, or is this taken care of by the fact that the ManagedResource knows both cc secrets?

`gardener-resource-manager` will delete the old `cloud-config` secrets once we removed them from the `ManagedResource`, I don't think we need to do anything special here.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 3]
```diff
@@ -693,14 +693,22 @@ func (d *deployer) deploy(ctx context.Context, operation string) (extensionsv1al
...
 	}
 
-	kubernetesMajorMinorVersion := fmt.Sprintf("%d.%d", kubernetesVersion.Major(), kubernetesVersion.Minor())
-	return fmt.Sprintf("cloud-config-%s-%s", workerName, utils.ComputeSHA256Hex([]byte(kubernetesMajorMinorVersion))[:5])
+	var (
+		kubernetesMajorMinorVersion = fmt.Sprintf("%d.%d", kubernetesVersion.Major(), kubernetesVersion.Minor())
+		criName                     gardencorev1beta1.CRIName
+	)
+
+	if criConfig != nil && criConfig.Name != gardencorev1beta1.CRINameDocker {
```
Comment (oliver-goetz) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go:707]: Wouldn't it make sense to change that to?
```go 
	if criConfig != nil {
		criName = criConfig.Name
	}
```
By doing so we could still add the legacy configuration and for the future docker and containerd secrets would share the same secret name scheme.

Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go:707]: The goal of checking `cri.Name != docker` is to avoid any changes happening when people switch from the implicit configuration of `docker` (having `cri: nil`) to the explicit configuration (by specifying `cri.name: docker`. This isn't really changing anything on the nodes, therefore we don't want any node rollout or other disruptive stuff happening.
You're right that this is still the case with your proposed change – as long as the compatibility code in `https://github.com/gardener/gardener/pull/5870/files/3f584e4380ba1fecca393194a6c3329047413fa4#diff-78a67ae80f891c299fbd162c192ef1fe19663c5db0bef7e1a42bb04eb70a6335` is present. Once we remove this compatibility code, nodes will no longer find their old secret when configuring `docker` explicitly moves to a new secret name.
We could achieve a similar thing with a slightly different change, though:
```
if criConfig == nil {
		criName = gardencorev1beta1.CRINameDocker
	}
```

This would move all `cri: nil` clusters to the new cloud-config secret and after removing the compatibility code, switching from `cri: nil` to `cri.name: docker` still works without any sideeffects.

**Comment by voelzmo** [comment]
> Do you have concerns with this approach or any idea of corner cases that I might have missed?

I don't know enough about potential issues that we might not have covered here which in the end could prevent a successful migration to the new cc-secret for all nodes. In the end, I was wondering if we have means (with justifiable effort) that would allow us to find out if all nodes really switched to the new secret. It's not about a concrete change to the code here, so this is good to go from my perspective.

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go (hunk 3 above)
Comment (oliver-goetz) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go:707]: Avoiding unneeded rollouts when changing from docker to nil and vice versa definitely makes sense.

For my understanding, I'm pretty new to this stuff 😄 
- the current approach would roll every containerd node as a side effect when this PR is applied, because the secret name is changing in this case. Docker nodes (implicit and explicit) would not roll.
-  In your proposal every node would roll initially, because all secret names are changing

Is this correct?

Comment (voelzmo) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go:707]: We're not rolling nodes as an effect of this PR – nodes would be rolled when people update the CRI configuration in their worker pools. This change is aimed at removing an effect we saw when this node rollout happens: the "old nodes" still apply a cloud-config that wasn't meant for them, because it contains the new configuration.

What the compatibility part of this change does is that it adds a second cloud-config secret for existing nodes which are already configured with `cri.name: containerd` – to avoid [the problem we experienced when we tried introducing cloud-configs with names based on the CRI](https://github.com/gardener/gardener/issues/4390): you cannot simply change the name of a cloud-config for a running node, because each node runs a script constantly checking the cloud-config secret for new content (you can see how these components interact [in a diagram included in the bootstrap documentation](https://github.com/gardener/gardener/blob/master/docs/extensions/operatingsystemconfig.md#detailed-bootstrap-flow-with-a-worker-generated-bootstrap-token)). There's a tricky self-updating mechanism in place here where the downloaded script can contain an updated version of the updater script, such that in the next run, the new secret name will be checked for updated content.

What I was proposing above changes @rfranzke's approach slightly in the sense that we not only do this for existing nodes configured with `containerd`, but also for the ones with `docker`, such that the computation of the cloud-config-secret name will not contain any "special if-else magic" for particular runtimes, but just computes a hash. I guess this is also where your simplification proposal on top of this thread came from?

Comment (rfranzke) [reply pkg/operation/botanist/component/extensions/operatingsystemconfig/operatingsystemconfig.go:707]: I would propose to proceed as is and live with this "special magic". I haven't checked, but we probably have other places where we assume that `cri=nil` is the same as `cri.name=docker`. "Simplifying" this now would require me to re-validate this PR for all the various cases and I would rather spend the time on something else.

**Review by ialidzhikov — COMMENTED** [review]
During my testing I noticed the following issue - being based on this PR and revert of https://github.com/gardener/gardener/pull/5791, migration from `cri=nil` to `cri.name=containerd` was not graceful (for K8s 1.21.12 Shoot). I can see that in the `/var/lib/cloud-config-downloader/download-cloud-config.sh` script of the old Node the Secret name is updated and points to the new cloud-config Secret - sounds like https://github.com/gardener/gardener/issues/4415. I guess the Secret name update for the old Node is unexpected in this case, right?

**Comment by rfranzke** [comment]
@ialidzhikov Yes, you also have to revert f8478ef63b533f2f9df109deb4209ea9bbb62337 and 3f584e4380ba1fecca393194a6c3329047413fa4, otherwise this won't work and we are back to #4415

**Review by ialidzhikov — COMMENTED** [review]
/lgtm
