### PR TITLE
Fix flaky `ControllerInstallation` controller integration test suite

### LINKED ISSUE #6786: [Flaky Test] ControllerInstallation Controller tests
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
• [FAILED] [6.690 seconds]
ControllerInstallation controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go:37
  responsible
  /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go:128
    [It] should create a namespace and deploy the chart
    /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go:141
```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6750/pull-gardener-integration/1579353349046669312

**Reason for failure**:
```
  Expected
      <string>: "...ls:
            controllerinstallation-controller-test: "628249e0"
            provider.extensions.gardener.cloud..."
  to equal                                                            |
      <string>: "...ls:
            controllerinstallation-controller-test: 628249e0
            provider.extensions.gardener.cloud/p..."
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_test.go:164
```
**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind flake

**What this PR does / why we need it**:
Fix flaky `ControllerInstallation` controller integration test suite by preventing the `testRunID` from becoming a number.

Before:

```
stress -ignore "unable to grab random port" -p 32 ./controllerinstallation.test
...
32 runs so far, 1 failures
```

Now:

```
stress -ignore "unable to grab random port" -p 32 ./controllerinstallation.test
...
248 runs so far, 0 failures
```

**Which issue(s) this PR fixes**:
Fixes #6786

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
> @rfranzke: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-check-vulnerabilities	[2a9691d](https://github.com/gardener/gardener/commit/2a9691da18273cea2001e3f6d562034ecba09e62)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6814/pull-gardener-check-vulnerabilities/1579853890885521408)	false	`/test pull-gardener-check-vulnerabilities`
> pull-gardener-integration	[2a9691d](https://github.com/gardener/gardener/commit/2a9691da18273cea2001e3f6d562034ecba09e62)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6814/pull-gardener-integration/1579853891246231552)	true	`/test pull-gardener-integration`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=6814). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Arfranzke). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

Flake which is going to be fixed with https://github.com/gardener/gardener/pull/6813

/test pull-gardener-integration

File: test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go [hunk 1]
```diff
@@ -106,7 +105,10 @@ var _ = BeforeSuite(func() {
 	testClient, err = client.New(restConfig, client.Options{Scheme: kubernetes.GardenScheme})
 	Expect(err).NotTo(HaveOccurred())
 
-	testRunID = utils.ComputeSHA256Hex([]byte(uuid.NewUUID()))[:8]
+	// Prevent testRunID from being able to be interpreted as number, see https://github.com/gardener/gardener/issues/6786
```
Comment (ialidzhikov) [inline test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go]: Is it possible to use 

```suggestion
	testRunID = testID + "-" utils.ComputeSHA256Hex([]byte(uuid.NewUUID()))[:8]
```

?

Some example from existing tests https://github.com/gardener/gardener/blob/9444417324f2843d3389a28a918239558bd69fb7/test/integration/controllermanager/seed/backupbucketscheck/backupbucketscheck_suite_test.go#L57 https://github.com/gardener/gardener/blob/9444417324f2843d3389a28a918239558bd69fb7/test/integration/controllermanager/seed/extensionscheck/extensionscheck_suite_test.go#L62

Comment (rfranzke) [reply test/integration/gardenlet/controllerinstallation/controllerinstallation/controllerinstallation_suite_test.go]: Sure, should be possible

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/approve
