### PR TITLE
Fix availability of Gardener `APIService`s

### LINKED ISSUE #11385: [Flaky Test] `pull-gardener-e2e-kind-operator` (unavailable Gardener APIs)
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
`pull-gardener-e2e-kind-operator` via `make operator-seed-up`,  even before the actual `e2e` tests are started.

**CI link**:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11381/pull-gardener-e2e-kind-operator-seed/1890100805755736064
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11383/pull-gardener-e2e-kind-operator-seed/1890082402257080320
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11381/pull-gardener-e2e-kind-operator-seed/1890068335878475776

**Reason for failure**:
During local testing it turned out that the Gardener `APIService`s get unready for a short period of time (until GRM re-applies the `Endpoint`)

```
v1alpha1.security.gardener.cloud         kube-system/gardener-apiserver   False (MissingEndpoints)   6m2s
v1alpha1.seedmanagement.gardener.cloud   kube-system/gardener-apiserver   False (MissingEndpoints)   6m2s
v1alpha1.operations.gardener.cloud       kube-system/gardener-apiserver   False (MissingEndpoints)   6m2s
v1.core.gardener.cloud                   kube-system/gardener-apiserver   False (MissingEndpoints)   6m2s
v1beta1.core.gardener.cloud              kube-system/gardener-apiserver   False (MissingEndpoints)   6m2s
v1alpha1.settings.gardener.cloud         kube-system/gardener-apiserver   False (MissingEndpoints)   6m2s
```

`Endpoint` in Cluster:
```
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-02-13T21:57:34Z"
    resources.gardener.cloud/description: |-
      DO NOT EDIT - This resource is managed by gardener-resource-manager.
      Any modifications are discarded and the resource is returned to the original state.
    resources.gardener.cloud/origin: garden/gardener-apiserver-virtual
  creationTimestamp: "2025-02-13T21:57:34Z"
  labels:
    app: gardener
    resources.gardener.cloud/managed-by: gardener
    role: apiserver
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener-apiserver
  namespace: kube-system
  resourceVersion: "2018"
```

`Endpoint` in MR secret:
```
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    app: gardener
    role: apiserver
  name: gardener-apiserver
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.2.252.44
  ports:
  - port: 443
    protocol: TCP
```

It is not yet clear why the addresses are removed from the `Endpoint` object.

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
Disables `endpoint` controller in virtual clusters. Especially in the virtual garden cluster this caused issues because very time the KCM was rolled (or another leader was elected) the `endpoint` controller removed the IPs from the operator managed `gardener-apiserver` endpoint. As a consequence Gardener APIs were unreachable up to `1m`, until the `gardener-resource-manager` re-applied the endpoints object (see #11385).

The `persistentvolumeclaim-protection` and `ephemeral-volume` controllers are disabled along the way. Also, the `discovery/v1` API group is now disabled by default for virtual (or workerless) clusters since we don't see any use-case for `EndpointSlice`s  for those.

**Which issue(s) this PR fixes**:
Fixes #11385
Part of https://github.com/gardener/gardener/issues/11386

**Special notes for your reviewer**:
/cc @rfranzke @shafeeqes

**Release note**:

```bugfix operator
An issue was fixed that caused a downtime of Gardener API services up to `1m` every time the `virtual-garden-kube-controller-manager` changed its leader. 
```

### CODE REVIEW

**Review by shafeeqes — COMMENTED** [review]
Thanks!
/lgtm

**Comment by shafeeqes** [comment]
The KCM is panicking with a nil pointer error:
```
2025-02-16T12:38:25.802873446Z stderr F E0216 12:38:25.802216       1 panic.go:261] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
2025-02-16T12:38:25.802916596Z stderr F 	goroutine 1098 [running]:
2025-02-16T12:38:25.802926896Z stderr F 	k8s.io/apimachinery/pkg/util/runtime.logPanic({0x38483f0, 0x554eb20}, {0x2d9c260, 0x54897b0})
2025-02-16T12:38:25.802933546Z stderr F 		k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xbc
2025-02-16T12:38:25.802939806Z stderr F 	k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x38483f0, 0x554eb20}, {0x2d9c260, 0x54897b0}, {0x554eb20, 0x0, 0x43d945?})
2025-02-16T12:38:25.802945786Z stderr F 		k8s.io/apimachinery/pkg/util/runtime/runtime.go:82 +0x5e
2025-02-16T12:38:25.802951736Z stderr F 	k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc001ccb880?})
2025-02-16T12:38:25.802957026Z stderr F 		k8s.io/apimachinery/pkg/util/runtime/runtime.go:59 +0x108
2025-02-16T12:38:25.802962336Z stderr F 	panic({0x2d9c260?, 0x54897b0?})
2025-02-16T12:38:25.802967806Z stderr F 		runtime/panic.go:770 +0x132
2025-02-16T12:38:25.802973496Z stderr F 	k8s.io/cloud-provider/controllers/service.(*Controller).needsUpdate(0xc00178cea0, 0xc0035edb88, 0xc0043bb188)
2025-02-16T12:38:25.802979336Z stderr F 		k8s.io/cloud-provider/controllers/service/controller.go:606 +0xcbb
2025-02-16T12:38:25.802984936Z stderr F 	k8s.io/cloud-provider/controllers/service.New.func2({0x32711e0?, 0xc0035edb88?}, {0x32711e0, 0xc0043bb188?})
2025-02-16T12:38:25.802990426Z stderr F 		k8s.io/cloud-provider/controllers/service/controller.go:144 +0x74
2025-02-16T12:38:25.802996126Z stderr F 	k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
2025-02-16T12:38:25.803001736Z stderr F 		k8s.io/client-go/tools/cache/controller.go:253
2025-02-16T12:38:25.803007346Z stderr F 	k8s.io/client-go/tools/cache.(*processorListener).run.func1()
2025-02-16T12:38:25.803012336Z stderr F 		k8s.io/client-go/tools/cache/shared_informer.go:976 +0xea
2025-02-16T12:38:25.803017436Z stderr F 	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
2025-02-16T12:38:25.803022516Z stderr F 		k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
2025-02-16T12:38:25.803027996Z stderr F 	k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0022d3f70, {0x38135c0, 0xc001c8a7e0}, 0x1, 0xc001c8f320)
2025-02-16T12:38:25.803033036Z stderr F 		k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
2025-02-16T12:38:25.803037936Z stderr F 	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0022d3f70, 0x3b9aca00, 0x0, 0x1, 0xc001c8f320)
2025-02-16T12:38:25.803043196Z stderr F 		k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
2025-02-16T12:38:25.803048226Z stderr F 	k8s.io/apimachinery/pkg/util/wait.Until(...)
2025-02-16T12:38:25.803053246Z stderr F 		k8s.io/apimachinery/pkg/util/wait/backoff.go:161
2025-02-16T12:38:25.803058146Z stderr F 	k8s.io/client-go/tools/cache.(*processorListener).run(0xc001a16990)
2025-02-16T12:38:25.803063816Z stderr F 		k8s.io/client-go/tools/cache/shared_informer.go:972 +0x69
2025-02-16T12:38:25.803068726Z stderr F 	k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
2025-02-16T12:38:25.803073595Z stderr F 		k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x52
2025-02-16T12:38:25.803079035Z stderr F 	created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start in goroutine 1063
2025-02-16T12:38:25.803083726Z stderr F 		k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0x73
2025-02-16T12:38:25.803088315Z stderr F  >
2025-02-16T12:38:25.804865065Z stderr F panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2025-02-16T12:38:25.804911594Z stderr F 	panic: runtime error: invalid memory address or nil pointer dereference
2025-02-16T12:38:25.804919485Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x212043b]
2025-02-16T12:38:25.804935654Z stderr F 
2025-02-16T12:38:25.804939085Z stderr F goroutine 1098 [running]:
2025-02-16T12:38:25.804942074Z stderr F k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x38483f0, 0x554eb20}, {0x2d9c260, 0x54897b0}, {0x554eb20, 0x0, 0x43d945?})
2025-02-16T12:38:25.804944734Z stderr F 	k8s.io/apimachinery/pkg/util/runtime/runtime.go:89 +0xee
2025-02-16T12:38:25.804947165Z stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc001ccb880?})
2025-02-16T12:38:25.804950065Z stderr F 	k8s.io/apimachinery/pkg/util/runtime/runtime.go:59 +0x108
2025-02-16T12:38:25.804952465Z stderr F panic({0x2d9c260?, 0x54897b0?})
2025-02-16T12:38:25.804954914Z stderr F 	runtime/panic.go:770 +0x132
2025-02-16T12:38:25.805385534Z stderr F k8s.io/cloud-provider/controllers/service.(*Controller).needsUpdate(0xc00178cea0, 0xc0035edb88, 0xc0043bb188)
2025-02-16T12:38:25.805407764Z stderr F 	k8s.io/cloud-provider/controllers/service/controller.go:606 +0xcbb
2025-02-16T12:38:25.805415374Z stderr F k8s.io/cloud-provider/controllers/service.New.func2({0x32711e0?, 0xc0035edb88?}, {0x32711e0, 0xc0043bb188?})
2025-02-16T12:38:25.805420604Z stderr F 	k8s.io/cloud-provider/controllers/service/controller.go:144 +0x74
2025-02-16T12:38:25.805426304Z stderr F k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
2025-02-16T12:38:25.805433164Z stderr F 	k8s.io/client-go/tools/cache/controller.go:253
2025-02-16T12:38:25.805439924Z stderr F k8s.io/client-go/tools/cache.(*processorListener).run.func1()
2025-02-16T12:38:25.805466234Z stderr F 	k8s.io/client-go/tools/cache/shared_informer.go:976 +0xea
2025-02-16T12:38:25.805473144Z stderr F k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
2025-02-16T12:38:25.805478914Z stderr F 	k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
2025-02-16T12:38:25.805484734Z stderr F k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0028cdf70, {0x38135c0, 0xc001c8a7e0}, 0x1, 0xc001c8f320)
2025-02-16T12:38:25.805492634Z stderr F 	k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
2025-02-16T12:38:25.805499644Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0022d3f70, 0x3b9aca00, 0x0, 0x1, 0xc001c8f320)
2025-02-16T12:38:25.805504784Z stderr F 	k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
2025-02-16T12:38:25.805525114Z stderr F k8s.io/apimachinery/pkg/util/wait.Until(...)
2025-02-16T12:38:25.805531734Z stderr F 	k8s.io/apimachinery/pkg/util/wait/backoff.go:161
2025-02-16T12:38:25.805537544Z stderr F k8s.io/client-go/tools/cache.(*processorListener).run(0xc001a16990)
2025-02-16T12:38:25.805543654Z stderr F 	k8s.io/client-go/tools/cache/shared_informer.go:972 +0x69
2025-02-16T12:38:25.805550224Z stderr F k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
2025-02-16T12:38:25.805555464Z stderr F 	k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x52
2025-02-16T12:38:25.805561004Z stderr F created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start in goroutine 1063
2025-02-16T12:38:25.805566814Z stderr F 	k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0x73
```
Ref: https://gcsweb.prow.gardener.cloud/gcs/gardener-prow/pr-logs/pull/gardener_gardener/11400/pull-gardener-e2e-kind-operator/1891100227838939136/artifacts/gardener-operator-local/gardener-operator-local-control-plane/containers/kube-controller-manager-gardener-operator-local-control-plane_kube-system_kube-controller-manager-a056cbdafd1520728b378d23cffcf26793d1b5057ccbb64c84e51a70cfa09563.log

**Comment by shafeeqes** [comment]
> @timuthy: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-e2e-kind	[eb4d58a](https://github.com/gardener/gardener/commit/eb4d58aaee3b02b3cdc8e7ee2db9bab60fc88e89)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11400/pull-gardener-e2e-kind/1891659158881570816)	true	`/test pull-gardener-e2e-kind`
> pull-gardener-e2e-kind-ipv6	[eb4d58a](https://github.com/gardener/gardener/commit/eb4d58aaee3b02b3cdc8e7ee2db9bab60fc88e89)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11400/pull-gardener-e2e-kind-ipv6/1891659158680244224)	true	`/test pull-gardener-e2e-kind-ipv6`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=11400). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Atimuthy). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

We need to adapt the shoot-create-update test to use a different resource in the encryption config 😅 
https://github.com/gardener/gardener/blob/ea1128116886136bbde5a5e28b4d8566abc01420/test/e2e/gardener/shoot/create_update_delete.go#L37-L39

File: test/e2e/gardener/shoot/create_update_delete.go [hunk 1]
```diff
@@ -35,7 +35,7 @@ var _ = Describe("Shoot Tests", Label("Shoot", "default"), func() {
 		f := defaultShootCreationFramework()
 		f.Shoot = shoot
 		f.Shoot.Spec.Kubernetes.KubeAPIServer.EncryptionConfig = &gardencorev1beta1.EncryptionConfig{
-			Resources: []string{"services", "endpointslices.discovery.k8s.io"},
+			Resources: []string{"services", "clusterroles.rbac.authorization.k8s.io"},
```
Comment (shafeeqes) [inline test/e2e/gardener/shoot/create_update_delete.go:38]: Might need to adapt Line 84, where we try to list this resource as well.
