### PR TITLE
Recover panic in `flow.Task`

### LINKED ISSUE #14495: Panic in `flow.Task` is not recovered
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:

If one `Task` in the [`flow`](https://github.com/gardener/gardener/tree/master/pkg/utils/flow) library panics the complete program panics, as the `Tasks` are run in go routines.

Example: The provider extensions use the `flow` library in the infrastructure controller. In case one of the flow tasks panics the complete `gardener-extension-provider-*` panics and influences other cluster reconciles on the same seed. 

**What you expected to happen**:

The panic should be recoverd (somewhere [here](https://github.com/gardener/gardener/blob/09d35a30058de3b7d7962d857e5c492f71b5c086/pkg/utils/flow/flow.go#L231)), to limit the issue to a flow/reconcile.

This could be done per default or optionally. WDYT?

**How to reproduce it (as minimally and precisely as possible)**:

```go
package main

import (
	"context"
	"fmt"

	"github.com/gardener/gardener/pkg/utils/flow"
)

func main() {
	defer func() {
		// is not used in the task as the task runs in a go routine.
		if r := recover(); r != nil {
			fmt.Println("Recovered in f", r)
		}
	}()

	g := flow.NewGraph("test")
	task := flow.Task{
		Name: "panic test",
		Fn: func(_ context.Context) error {
			panic("hello world")
			return nil
		},
	}

	g.Add(task)
	_ = g.Compile().Run(context.TODO(), flow.Opts{})
}
```
```bash
❯ go run main.go
panic: hello world

goroutine 18 [running]:
main.main.func2({0xae6d70?, 0x37457e3ba2c0?})
        /tmp/flow/main.go:22 +0x25
github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2()
        /go/pkg/mod/github.com/gardener/gardener@v1.139.0/pkg/utils/flow/flow.go:234 +0x184
created by github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode in goroutine 1
       /go/pkg/mod/github.com/gardener/gardener@v1.139.0/pkg/utils/flow/flow.go:231 +0x6a9
exit status 2
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.139.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by dergeberl**
**How to categorize this PR?**

/area robustness
/kind bug

**What this PR does / why we need it**:

Recover panic in `flow.Task` to avoid a panic of the complete controller which uses the flow package. Some extensions already have a "own" panic recovery (like [gardener-extension-provider-aws](https://github.com/gardener/gardener-extension-provider-aws/blob/25bad6cbd08d3105c4a9a47fc620c32e81382667/pkg/controller/infrastructure/infraflow/shared/basic_context.go#L125)) but I think it still makes sense to recover them globally. I also tested that the behavior will not change if a extension has already panic recovery (see example below).

**Which issue(s) this PR fixes**:
Fixes #14495

**Special notes for your reviewer**:

To test this you can use this small example:

```go
package main

import (
	"context"
	"fmt"

	"github.com/gardener/gardener/pkg/logger"
	"github.com/gardener/gardener/pkg/utils/flow"
)

func main() {
	log, _ := logger.NewZapLogger(logger.DebugLevel, logger.FormatText)
	g := flow.NewGraph("test")

	task1 := flow.Task{
		Name: "no panic test",
		Fn: func(_ context.Context) error {
			return nil
		},
	}

	task2 := flow.Task{
		Name: "own panic recover test",
		Fn: func(_ context.Context) error {
			defer func() {
				if r := recover(); r != nil {
					// just log panic but successful finish task
					log.Info("panic recovered", "panic", r)
				}
			}()
			panic("test2")
			return nil
		},
		Dependencies: make(flow.TaskIDs).Insert(g.Add(task1)),
	}

	task3 := flow.Task{
		Name: "panic test",
		Fn: func(_ context.Context) error {
			panic("test3")
			return nil
		},
		Dependencies: make(flow.TaskIDs).Insert(g.Add(task2)),
	}

	g.Add(task3)

	fmt.Println(g.Compile().Run(context.TODO(), flow.Opts{Log: log}))
}
```

This outputs:
```
 go run main.go
2026-04-16T15:01:44.703+0200    INFO    Starting        {"flow": "test"}
2026-04-16T15:01:44.703+0200    DEBUG   Started {"flow": "test", "task": "no panic test"}
2026-04-16T15:01:44.703+0200    DEBUG   Finished        {"flow": "test", "task": "no panic test", "duration": "29.976�s"}
2026-04-16T15:01:44.703+0200    INFO    Succeeded       {"flow": "test", "task": "no panic test"}
2026-04-16T15:01:44.704+0200    DEBUG   Started {"flow": "test", "task": "own panic recover test"}
2026-04-16T15:01:44.704+0200    INFO    panic recovered {"panic": "test2"}
2026-04-16T15:01:44.704+0200    DEBUG   Finished        {"flow": "test", "task": "own panic recover test", "duration": "34.715�s"}
2026-04-16T15:01:44.704+0200    INFO    Succeeded       {"flow": "test", "task": "own panic recover test"}
2026-04-16T15:01:44.704+0200    DEBUG   Started {"flow": "test", "task": "panic test"}
2026-04-16T15:01:44.704+0200    ERROR   Error   {"flow": "test", "task": "panic test", "error": "task \"panic test\" recovered panic: test3"}
github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2.1
        /git/github/gardener/gardener/pkg/utils/flow/flow.go:235
runtime.gopanic
       /sdk/go1.26.1/src/runtime/panic.go:860
main.main.func3
        /tmp/flow/main.go:39
github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2
        /git/github/gardener/gardener/pkg/utils/flow/flow.go:242
2026-04-16T15:01:44.704+0200    INFO    Finished        {"flow": "test"}
flow "test" encountered task errors: [task "panic test" recovered panic: test3]
```

**Release note**:

```noteworthy developer
Added panic recovery to `flow.Task` to prevent a single task failure from crashing the entire controller. If you previously implemented custom panic recovery within your tasks, you  can consider removing that custom panic recovery.
```

### CODE REVIEW

File: pkg/utils/flow/flow.go [hunk 1]
```diff
@@ -229,6 +229,14 @@ func (e *execution) runNode(ctx context.Context, id TaskID) {
 	e.stats.Running.Insert(id)
 
 	go func() {
+		defer func() {
+			if r := recover(); r != nil {
+				err := fmt.Errorf("task %q recovered panic: %v", id, r)
+				log.Error(err, "Error")
```
Comment (Kostov6) [inline pkg/utils/flow/flow.go:235]: Isn't `log.Error(err, "Error")` redundant as I'd expect the error from `e.done <- &nodeResult{TaskID: id, Error: err}` to get logged by the handler of that structure?

Comment (dergeberl) [reply pkg/utils/flow/flow.go:235]: The error is no logged directly from the flow package. The controllers which use this package could log it as the `panic` is also in the error which is returned by `g.Compile().Run()`.


With the current code the log of a panic looks like this:

```
2026-04-17T14:01:37.039+0200    INFO    Starting        {"flow": "test"}
2026-04-17T14:01:37.039+0200    ERROR   Error   {"flow": "test", "task": "panic test", "error": "task \"panic test\" recovered panic: test"}
github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2.1
        /git/github/gardener/gardener/pkg/utils/flow/flow.go:235
runtime.gopanic
        /sdk/go1.26.1/src/runtime/panic.go:860
main.main.func3
        /tmp/flow/main.go:41
github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2
        /git/github/gardener/gardener/pkg/utils/flow/flow.go:242
2026-04-17T14:01:37.039+0200    INFO    Finished        {"flow": "test"}
flow "test" encountered task errors: [task "panic test" recovered panic: test] // this is the error from g.Compile().Run(context.TODO(), flow.Opts{Log: log})
```

If I remove the `log.Error()` it looks like this:
```
2026-04-17T14:00:51.573+0200    INFO    Starting        {"flow": "test"}
2026-04-17T14:00:51.573+0200    INFO    Finished        {"flow": "test"}
flow "test" encountered task errors: [task "panic test" recovered panic: test] // this is the error from g.Compile().Run(context.TODO(), flow.Opts{Log: log})
```


I also think this helps to find the error as `/tmp/flow/main.go:41` is the line which causes the panic.
