### PR TITLE
Fix ControllerInstallation required calculation

### LINKED ISSUE #2519: Last responsible extension controller remains on seed after getting obsolete
**How to categorize this issue?**

/area quality
/area cost
/kind bug
/priority normal

**What happened**:
Gardener offers on-demand `ControllerRegistration`s which are only deployed to the seed cluster if a related extension Kind/Type is found on the seed. Likewise, once extensions are gone, Gardener checks if the extension controller is still required and deletes it if necessary.

Unfortunately, this hehavior doesn't work for the very last extension Kind/Type that is deleted from the seed, i.e. the infrastructure resource.

**What you expected to happen**:
The provider extension to be deleted.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a cluster on a seed w/o backup configuration
- Delete the cluster again
- `ControllerInstallation` for the provider extension is not gone

**Anything else we need to know?**:
You can find the related exit condition here: https://github.com/gardener/gardener/blob/f120f2c74a503ab4a388aa055cd08d4081eaf5ed/pkg/gardenlet/controller/federatedseed/extensions/controllerinstallation_control.go#L174-L177

The comment correctly says that it cannot decide if the extension is required or not but unfortunately it misses the following case:
- The controller registration is responsible for resources which are **not required** at all by the shoot, e.g. because you disabled the backup feature (`controllerRegistration.Spec.Resources`)
```
resources:
  - kind: BackupBucket     <--- not required in this scenario
    primary: true
    type: gcp
  - kind: BackupEntry        <--- not required in this scenario
    primary: true
    type: gcp
  - kind: ControlPlane
    primary: true
    type: gcp
  - kind: Infrastructure
    primary: true
    type: gcp
  - kind: Worker
    primary: true
    type: gcp
```
- `c.kindToRequiredTypes` has no required types **after** the `Infrastructure` extension is deleted, hence we never enter this block https://github.com/gardener/gardener/blob/f120f2c74a503ab4a388aa055cd08d4081eaf5ed/pkg/gardenlet/controller/federatedseed/extensions/controllerinstallation_control.go#L166-L169
- Eventually the early exit is taken because `required == nil`

/cc @rfranzke

**Environment**:

- Gardener version: `master` with #2517

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area robustness
/kind bug
/priority normal

**What this PR does / why we need it**:
This PR fixes the calculation of ControllerInstallations. Earlier ControllerInstallations were still considered as required even though no corresponding extension resources or Shoot clusters existed. Please look at #2519 for more information.

We also added the validation for known extension kinds in ControllerRegistrations along the way.

Thanks to @rfranzke for collaborating on this PR.

**Which issue(s) this PR fixes**:
Fixes #2519 #2572

**Release note**:

```improvement operator
An issue has been fixed which prevented not required ControllerInstallations from being deleted. As a side effect, it also blocked the deletion of Seed resources.
```
```improvement operator
Gardener now validates the extension kinds configured in `.spec.resources[].kind` in ControllerRegistrations. 
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]
/lgtm
/needs second-opinion

File: pkg/apis/extensions/v1alpha1/types.go [hunk 1]
```diff
@@ -68,3 +69,16 @@ type Object interface {
 	// GetExtensionStatus retrieves the object's status.
 	GetExtensionStatus() Status
 }
+
+// ExtensionKinds contains all supported extension kinds.
+var ExtensionKinds = sets.NewString(
```
Comment (vpnachev) [inline pkg/apis/extensions/v1alpha1/types.go:76]: Is the `DNSProvider` still working?

Comment (rfranzke) [reply pkg/apis/extensions/v1alpha1/types.go:76]: Oh, indeed, that's a nice catch, thanks @vpnachev.
@timuthy we should add `DNSProvider`, `DNSEntry`, and `DNSOwner` to this list as well.
/needs changes
/status author-action

Comment (timuthy) [reply pkg/apis/extensions/v1alpha1/types.go:76]: Thanks a lot for noticing this.

File: pkg/apis/extensions/v1alpha1/types.go [hunk 2]
```diff
@@ -68,3 +71,17 @@ type Object interface {
...
+	BackupBucketResource,
+	BackupEntryResource,
+	ContainerRuntimeResource,
+	ControlPlaneResource,
+	dnsv1alpha1.DNSProviderKind,
```
Comment (rfranzke) [inline pkg/apis/extensions/v1alpha1/types.go:81]: What about `DNSEntry` and `DNSOwner`?

**Review by rfranzke — CHANGES_REQUESTED** [review]

File: pkg/apis/extensions/v1alpha1/types.go (hunk 2 above)
Comment (timuthy) [reply pkg/apis/extensions/v1alpha1/types.go:81]: Are these really extension Kinds we use for registration? Because we don't consider them [here](https://github.com/gardener/gardener/blob/8359e1ae278c1f121d1d3db69a96c1fa6e0ce4a5/pkg/operation/shoot/shoot.go#L465-L481) either.

Comment (rfranzke) [reply pkg/apis/extensions/v1alpha1/types.go:81]: Yes, thanks, you're right!

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm
