### PR TITLE
Delete MCM before deleting the MCM resources in the Shoot force deletion flow

### LINKED ISSUE #8861: The Shoot force deletion flow hangs in the `Waiting until machine resources have been deleted` step
**How to categorize this issue?**

/kind bug

**What happened**:
We see many flakes in the Shoot force deletion e2e tests in the registry-cache and shoot-rsyslog-relp extensions.

Logs from a failure:
```
  {"level":"info","ts":"2023-11-13T07:35:15.292Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:35:15.292Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Shoot cluster has been successfully reconciled.,LastUpdateTime:2023-11-13 07:33:36 +0000 UTC,Progress:100,State:Succeeded,Type:Reconcile,}"}
  {"level":"info","ts":"2023-11-13T07:35:45.297Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:35:45.297Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:36:15.301Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:36:15.301Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:36:45.307Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:36:45.307Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:37:15.337Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:37:15.337Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:37:45.341Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:37:45.341Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:38:15.345Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:38:15.345Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:38:45.350Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:38:45.350Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:39:15.354Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:39:15.354Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:39:45.358Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:39:45.358Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:40:15.362Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:40:15.362Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:40:45.367Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:40:45.367Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:41:15.372Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:41:15.372Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:41:45.376Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:41:45.376Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:42:15.380Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:42:15.380Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:42:45.385Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:42:45.385Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:43:15.389Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:43:15.389Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:43:45.393Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:43:45.393Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:44:15.398Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:44:15.398Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 UTC,Progress:50,State:Processing,Type:Delete,}"}
  {"level":"info","ts":"2023-11-13T07:44:45.402Z","logger":"test","msg":"Shoot is not yet deleted","shoot":{"name":"e2e-force-delete","namespace":"garden-local"}}
  {"level":"info","ts":"2023-11-13T07:44:45.402Z","logger":"test","msg":"Last Operation","shoot":{"name":"e2e-force-delete","namespace":"garden-local"},"lastOperation":"&LastOperation{Description:Waiting until machine resources have been deleted,LastUpdateTime:2023-11-13 07:35:26 +0000 
```

The Shoot deletion hangs in the following step:
https://github.com/gardener/gardener/blob/745643d3cbc3debcf0870d919fcd18bcf6330799/pkg/gardenlet/controller/shoot/shoot/reconciler_force_delete.go#L101-L105

There are 2 issues:
1. The first issue is that in https://github.com/gardener/gardener/blob/699d4ebaa548202681e5eeeed7ca0c1edc407ca9/pkg/gardenlet/controller/shoot/shoot/cleaner.go#L105C1-L111C2 the deletion of the Machine CRDs is unordered and in parallel. So, it is the case that Machines are finalized, then MCM Pod sees that MachineSet needs a new replica and creates a new Machine. Then, the `Waiting until machine resources have been deleted` step hangs forever because there is a Machine object left from the previous step.
2. There isn't any timeout in `Waiting until machine resources have been deleted` step

I used the following diff to reproduce the issue:
```diff
diff --git a/pkg/gardenlet/controller/shoot/shoot/cleaner.go b/pkg/gardenlet/controller/shoot/shoot/cleaner.go
index dd65f99dd..092f01b48 100644
--- a/pkg/gardenlet/controller/shoot/shoot/cleaner.go
+++ b/pkg/gardenlet/controller/shoot/shoot/cleaner.go
@@ -104,10 +104,27 @@ func (c *cleaner) WaitUntilExtensionObjectsDeleted(ctx context.Context) error {
 
 // DeleteMachineResources deletes all MachineControllerManager resources in the shoot namespace.
 func (c *cleaner) DeleteMachineResources(ctx context.Context) error {
+	foo := map[string]client.ObjectList{
+		"Machine": &machinev1alpha1.MachineList{},
+	}
+	err := utilclient.ApplyToObjectKinds(ctx, func(kind string, objectList client.ObjectList) flow.TaskFn {
+		c.log.Info("Deleting all machine resources in namespace", "namespace", c.seedNamespace, "kind", kind)
+		return utilclient.ForceDeleteObjects(c.seedClient, c.seedNamespace, objectList)
+	}, foo)
+	if err != nil {
+		return err
+	}
+
+	bar := map[string]client.ObjectList{
+		"MachineDeployment": &machinev1alpha1.MachineDeploymentList{},
+		"MachineSet":        &machinev1alpha1.MachineSetList{},
+		"MachineClass":      &machinev1alpha1.MachineClassList{},
+	}
 	return utilclient.ApplyToObjectKinds(ctx, func(kind string, objectList client.ObjectList) flow.TaskFn {
 		c.log.Info("Deleting all machine resources in namespace", "namespace", c.seedNamespace, "kind", kind)
 		return utilclient.ForceDeleteObjects(c.seedClient, c.seedNamespace, objectList)
-	}, machineKindToObjectList)
+	}, bar)
 }
 
 // WaitUntilMachineResourcesDeleted waits until all MachineControllerManager resources in the shoot namespace have been deleted.

```

Otherwise I don't manage to reproduce it locally.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind bug

**What this PR does / why we need it**:
This PR eletes MCM before deleting the MCM resources in the Shoot force deletion flow.
In this way we prevent cases where Machines are force deleted first and then machine-controller-manager Pod creates a new Machine as replacement. For more datails, see https://github.com/gardener/gardener/issues/8861.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/8861

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/shoot/cleaner.go [hunk 1]
```diff
@@ -103,11 +103,15 @@ func (c *cleaner) WaitUntilExtensionObjectsDeleted(ctx context.Context) error {
...
 // DeleteMachineResources deletes all MachineControllerManager resources in the shoot namespace.
+// The resources are force deleted sequentially in the order MachineDeployment, MachineSet, Machine, MachineClass to prevent cases
+// where Machines are force deleted first and then machine-controller-manager Pod creates a new Machine as replacement.
 func (c *cleaner) DeleteMachineResources(ctx context.Context) error {
-	return utilclient.ApplyToObjectKinds(ctx, func(kind string, objectList client.ObjectList) flow.TaskFn {
-		c.log.Info("Deleting all machine resources in namespace", "namespace", c.seedNamespace, "kind", kind)
-		return utilclient.ForceDeleteObjects(c.seedClient, c.seedNamespace, objectList)
-	}, machineKindToObjectList)
+	return flow.Sequential(
+		utilclient.ForceDeleteObjects(c.seedClient, c.seedNamespace, &machinev1alpha1.MachineDeploymentList{}),
```
Comment (acumino) [inline pkg/gardenlet/controller/shoot/shoot/cleaner.go]: Should we include the wait here? For resources to be gone. 
Can it happen if the deployment has deletion time stamp still machines can be created for it? (Mostly not). If not then it's fine.

Comment (acumino) [reply pkg/gardenlet/controller/shoot/shoot/cleaner.go]: Also, please adapt https://github.com/gardener/gardener/blob/c29e9754aaea33814d74447601702e5f1a9740b9/pkg/gardenlet/controller/shoot/shoot/cleaner.go#L56-L61 list in same as new order.

Comment (ialidzhikov) [reply pkg/gardenlet/controller/shoot/shoot/cleaner.go]: > Should we include the wait here? For resources to be gone.
> Can it happen if the deployment has deletion time stamp still machines can be created for it? (Mostly not). If not then it's fine.

In the flows, we seem to do actions in tasks and then wait for conditions in other tasks. You rather prefer the force deletion and wait to be sequential - for example first force delete MachineDeployments, then wait for them to be gone, only then proceed with the MachineSets?
If you want, I can change the implementation but I assume that If MachineDeployment (or MachineSet) has a deletionTimestamp, then it will only try to delete (and not create) the corresponding MachineSet (or Machine). MCM folks (@himanshu-kun , @rishabh-11), can you  confirm?

**Comment by plkokanov** [comment]
Juts a quick question - now that gardener manages MCM, shouldn't we also make sure that MCM is deleted before removing the machine resources? Otherwise we need to verify that there is no chance for a reconciliation to be running in MCM at the same time we try to force delete the resource resulting in the resource being recreated.

File: pkg/gardenlet/controller/shoot/shoot/cleaner.go (hunk 1 above)
Comment (himanshu-kun) [reply pkg/gardenlet/controller/shoot/shoot/cleaner.go]: yes it'll try to delete the child machinesets https://github.com/gardener/machine-controller-manager/blob/1b57e16c5c3df14588a88399406d57a2a7ab3008/pkg/controller/deployment.go#L495-L506

**Comment by himanshu-kun** [comment]
> shouldn't we also make sure that MCM is deleted before removing the machine resources? 
yes sounds like a good idea

**Comment by ialidzhikov** [comment]
> Juts a quick question - now that gardener manages MCM, shouldn't we also make sure that MCM is deleted before removing the machine resources? Otherwise we need to verify that there is no chance for a reconciliation to be running in MCM at the same time we try to force delete the resource resulting in the resource being recreated.

I adapted the PR to delete MCM before finalizing the MCM resources. Theoretically, you are right but the probability of that to happen is too low. I don't think during a reconciliation of a resource, it could get recreated. Rather if a reconciliation of MachineSet is already ongoing in MCM, it might create a new Machine after we finalize the Machines. Anyways, we have a wait step that times out in 30s, so worst case this will be resolved in the next retry.
Anyways, I added steps to delete MCM and wait for the deletion. I also revereted the logic for the sequential deletion. We can finalize in parallel after MCM is deleted.

**Review by acumino — COMMENTED** [review]
/approve

**Comment by plkokanov** [comment]
Thanks for the change, can you also adapt the description of the PR?
/lgtm
