### PR TITLE
Fix handling of debugging fields in ManagedSeed

### LINKED ISSUE #4654: ManagedSeed sets `debugging.*=false`
**How to categorize this issue?**

/area dev-productivity ops-productivity
/kind bug

**What happened**:

When creating a simple `ManagedSeed` object like this
```yaml
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
  name: gcp
  namespace: garden # Must be garden
spec:
  shoot:
    name: seed-gcp
  gardenlet: {}
```

the newly added `debugging` fields (see https://github.com/gardener/gardener/issues/4567, https://github.com/gardener/gardener/pull/4568) in the gardenlet config will be set to `false,false`:
```yaml
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
  name: gcp
  namespace: garden
spec:
  gardenlet:
    config:
      apiVersion: gardenlet.config.gardener.cloud/v1alpha1
      debugging:
        enableContentionProfiling: false
        enableProfiling: false
      kind: GardenletConfiguration
# ...
    mergeWithParent: true
  shoot:
    name: seed-gcp
```

Because of this, the gardenlet that is deployed for the `ManagedSeed` will be configured with profiling handlers disabled even though the parent gardenlet has profiling handlers enabled and `mergeWithParent=true`.
Config of parent gardenlet:
```yaml
debugging:
  enableProfiling: true
  enableContentionProfiling: true
```

Config of `ManagedSeed` gardenlet:
```yaml
debugging:
  enableProfiling: false
  enableContentionProfiling: false
```

**What you expected to happen**:

I expected that if I create a `ManagedSeed` object without setting the `debugging` fields, the settings in the parent gardenlet are propagated down to the child gardenlet.

**Environment**:

- Gardener version: `v1.31.0`

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area ops-productivity
/kind bug

**What this PR does / why we need it**:

This PR fixes a bug caused by missing pointers in the gardenlet config API. We missed this scenario while discussing the API in https://github.com/gardener/gardener/pull/4568#discussion_r701893959.
For the sake of consistency, it performs the same changes to the other component configs.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/4654

**Special notes for your reviewer**:

Note: With this PR, the bug is only fixed for new `ManagedSeed` objects. If `ManagedSeed` objects were created before or with `g/g@v1.31.3`, gardener-apiserver has already persisted the `false` values in etcd. Hence, upgrading to a newer gardener version including this PR, will not remove the wrongly added `false` values.
If operators want to remove the wrongly added values, they can simply patch the `ManagedSeed` objects using:
```bash
kubectl -n garden patch ms my-seed -p '{"spec":{"gardenlet":{"config":{"debugging":null}}}}'
```

**Release note**:

```bugfix operator
A bug has been fixed, which caused the `ManagedSeed.spec.gardenlet.config.debugging.*` fields to be wrongly set to `false`.
Note: if you have been running gardener version `v1.31.[0-3]` already, upgrading to this version will not remove the wrongly added fields. If you want to remove the fields in order to rely on the defaults (settings from the parent gardenlet) please use the following `kubectl` command: `kubectl -n garden patch ms my-seed -p '{"spec":{"gardenlet":{"config":{"debugging":null}}}}'`.
```

### CODE REVIEW

**Comment by timebertt** [comment]
/invite @stoyanr @rfranzke 

> Note: With this PR, the bug is only fixed for new `ManagedSeed` objects. If `ManagedSeed` objects were created before or with `g/g@v1.31.3`, gardener-apiserver has already persisted the `false` values in etcd. Hence, upgrading to a newer gardener version including this PR, will not remove the wrongly added `false` values.
> If operators want to remove the wrongly added values, they can simply patch the `ManagedSeed` objects using:

In order to make the life of landscape operators easier, who have not been running `g/g@v1.31.[0-3]` before upgrading to this version, I think it should definitely be included in v1.32 and even backported to v1.31.

/milestone v1.32

File: pkg/gardenlet/apis/config/v1alpha1/types.go [hunk 1]
```diff
@@ -64,7 +64,8 @@ type GardenletConfiguration struct {
 	// +optional
 	Server *ServerConfiguration `json:"server,omitempty"`
 	// Debugging holds configuration for Debugging related features.
-	Debugging componentbaseconfigv1alpha1.DebuggingConfiguration `json:"debugging"`
+	// +optional
+	Debugging *componentbaseconfigv1alpha1.DebuggingConfiguration `json:"debugging,omitempty"`
```
Comment (ialidzhikov) [inline pkg/gardenlet/apis/config/v1alpha1/types.go:68]: I think we have to adapt the usages of this field with checks for non-nil. Currently we have 

https://github.com/gardener/gardener/blob/238c4c04c38be9acc82e408674a0c858b07963f7/cmd/gardenlet/app/gardenlet.go#L499-L504

and when `debugging` field is not set in the component config, this will result in nil pointer dereference. The same applies also for the other components.

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

File: pkg/gardenlet/apis/config/v1alpha1/types.go (hunk 1 above)
Comment (timebertt) [reply pkg/gardenlet/apis/config/v1alpha1/types.go:68]: Well, of course. I was too fast...

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/needs second-opinion

**Review by stoyanr — APPROVED** [review]
/lgtm
