### PR TITLE
Use `CreateOrGetAndStrategicMergePatch` for BackupBucket generated secret in garden

### LINKED ISSUE #7705: Cannot create an azure BackupBucket (BackupBucket with `generatedSecretRef`)
**How to categorize this issue?**

/area quality
/kind bug
/kind regression

**What happened**:
It looks like after https://github.com/gardener/gardener/pull/6837, it is no longer possible to create an azure BackupBucket (or a BackupBucket that uses `generatedSecretRef` flow).

https://github.com/gardener/gardener/blob/2ed36e5654a64892a2ef361d47dbde8bf00a3c7b/pkg/gardenlet/controller/backupbucket/reconciler.go#L352 seems to have the following issue:
1. We first try to `GetAndCreateOrMergePatch` the `gardenGeneratedSecret` in the garden cluster
2. The above operation is denied by the SeedAuthorizer with:
```
{"level":"error","ts":"2023-03-23T15:49:24.948Z","msg":"Reconciler error","controller":"backupbucket","namespace":"","name":"foo","reconcileID":"dac854ea-3609-4850-839c-d728c14317c8","error":"secrets \"generated-bucket-foo\" is forbidden: User \"gardener.cloud:system:seed:bar-ha-eu1\" cannot get resource \"secrets\" in API group \"\" in the namespace \"garden\": no relationship found between seed 'bar-ha-eu1' and this object","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235"}
```

The SeedAuthorizer would only add entry in its graph when the BackupBucket status is populated with the generatedSecretRef:
https://github.com/gardener/gardener/blob/8d53342ddcf0112209ce85662d7ba6bbcf2890aa/pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_backupbucket.go#L93-L96

But in the `syncGeneratedSecretToGarden` flow currently the `generatedSecretRef` is updated after the `GetAndCreateOrMergePatch` call.
So, obviously any Get request for such Secret would fail because the Secret name is not updated in the BackupBucket status and the SeedAuthorizer cannot update its graph according to the BackupBucket status.

**What you expected to happen**:
No such deadlock as above.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new azure Seed. Make sure the admission controller is running and `SeedAuthorizer` is turned on.

3. Make sure that the BackupBucket in the garden cluster stays in `Processing`
```yaml
  status:
    lastOperation:
      description: Reconciliation of BackupBucket state initialized.
      lastUpdateTime: "2023-03-24T05:35:46Z"
      progress: 0
      state: Processing
      type: Create
    observedGeneration: 1
```

Even the BackupBucket status is not updated with the failure reason.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.66.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area backup
/kind bug

**What this PR does / why we need it**:
After https://github.com/gardener/gardener/pull/6837, While syncing the backupbucket generated secret from seed to garden, the controller is using `GetAndCreateOrMergePatch`, Previously this was `CreateOrGetAndStrategicMergePatch`, ref: 
https://github.com/gardener/gardener/blob/c3e2599f43a86565194e44066b28614b3b7262dd/pkg/gardenlet/controller/backupbucket/backup_bucket_actuator.go#L244

Due to this, the entry for this Secret is not added to the `seed-authorizer-graph` and while doing Get, 
```
{"level":"info","ts":"2023-03-24T11:05:05.651+0530","logger":"webhook.seedauthorizer","msg":"Denying authorization because no relationship is found between seed and object","seedName":"seed-foo","attributes":"authorizer.AttributesRecord{User:(*user.DefaultInfo)(0x14000992c40), Verb:\"get\", Namespace:\"garden\", APIGroup:\"\", APIVersion:\"v1\", Resource:\"secrets\", Subresource:\"\", Name:\"generated-bucket-4fdsd98sd98sdc-40ef-9b93-899dd3eadbd6 \", ResourceRequest:true, Path:\"\"}"}
```

This PR fixes this and switches the controller back to use `CreateOrGetAndStrategicMergePatch`, this way at https://github.com/gardener/gardener/blob/9c3976a0674469b4282dac537ab2d8e33cc5f5f1/pkg/gardenlet/controller/backupbucket/reconciler.go#L388-L390, when the Update call for BackupBucket is done, the graph is correctly populated.
```
{"level":"info","ts":"2023-03-24T11:09:17.185+0530","logger":"seed-authorizer-graph","msg":"Added","vertex":"Secret:garden/generated-bucket-4fdsd98sd98sdc-40ef-9b93-899dd3eadbd6 (43)"}
{"level":"info","ts":"2023-03-24T11:09:17.185+0530","logger":"seed-authorizer-graph","msg":"Added edge","from":"Secret:garden/generated-bucket-4fdsd98sd98sdc-40ef-9b93-899dd3eadbd6  (43)","to":"BackupBucket:4fdsd98sd98sdc-40ef-9b93-899dd3eadbd6 (47)"}
```

Also we now patch the `BackupBucket` status to have the secretRef before going for the `CreateOrGetAndStrategicMergePatch`, so that the case of gardenlet restart mentioned in https://github.com/gardener/gardener/pull/7708#issuecomment-1482425134 is also covered.

**Which issue(s) this PR fixes**:
Fixes #7705

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
A bug causing the gardenlet to be unable to access the BackupBucket generated secret in garden namespace is now fixed.
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
There is also an edge case, where the gardenlet restarts right after the creation of the secret, so that the Patch call in https://github.com/gardener/gardener/blob/9c3976a0674469b4282dac537ab2d8e33cc5f5f1/pkg/gardenlet/controller/backupbucket/reconciler.go#L388-L390 is not made.
Then in the next reconciliation, the Get call at https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/pkg/controllerutils/patch.go#L116 will fail.

Maybe we can think about updating the BackupBucket status at the very beginning of `syncGeneratedSecretToGarden`.

**Comment by ialidzhikov** [comment]
/lgtm

I guess it is not possible to cover this scenario in controller envtest. Maybe we should look into direction of e2e test to cover this.

**Comment by rfranzke** [comment]
> Maybe we should look into direction of e2e test to cover this.

Yes, we could make [`provider-local`'s `BackupBucket` controller](https://github.com/gardener/gardener/blob/master/pkg/provider-local/controller/backupbucket/actuator.go) "just" create an empty dummy `Secret` and add the reference to it in the `generatedSecretRef` like in https://github.com/gardener/gardener-extension-provider-azure/blob/13dc62e8178c0aefd554e8151bbed5b3a2e0676b/pkg/controller/backupbucket/secret.go#L31-L55. This should cover it, I assume.

**Comment by shafeeqes** [comment]
Will adapt the e2e test. But since we don't have a distinction between the `garden` namespaces in seed and garden in the local kind setup, we can hit what I mentioned in https://github.com/gardener/gardener/pull/7708#issuecomment-1482295433.
Any thoughts?

**Comment by rfranzke** [comment]
> Will adapt the e2e test. But since we don't have a distinction between the `garden` namespaces in seed and garden in the local kind setup, we can hit what I mentioned above. Any thoughts on [#7708 (comment)](https://github.com/gardener/gardener/pull/7708#issuecomment-1482295433)?

Nice catch! We had a chat about this with @timuthy and agree that your proposal makes sense. We should at least update https://github.com/gardener/gardener/blob/9c3976a0674469b4282dac537ab2d8e33cc5f5f1/pkg/gardenlet/controller/backupbucket/reconciler.go#L386 before creating the secret: https://github.com/gardener/gardener/blob/9c3976a0674469b4282dac537ab2d8e33cc5f5f1/pkg/gardenlet/controller/backupbucket/reconciler.go#L369

**Comment by shafeeqes** [comment]
Tests will fail for now, Will adapt according to https://github.com/gardener/gardener/pull/7708#issuecomment-1482425134.

**Comment by shafeeqes** [comment]
> @shafeeqes: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-e2e-kind-migration	[ed5299f](https://github.com/gardener/gardener/commit/ed5299fed868d2dcf640a9a85083f60b59f07b08)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7708/pull-gardener-e2e-kind-migration/1639183147365044224)	true	`/test pull-gardener-e2e-kind-migration`
> pull-gardener-e2e-kind-ha-multi-zone	[ed5299f](https://github.com/gardener/gardener/commit/ed5299fed868d2dcf640a9a85083f60b59f07b08)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7708/pull-gardener-e2e-kind-ha-multi-zone/1639183147251798016)	true	`/test pull-gardener-e2e-kind-ha-multi-zone`
> pull-gardener-e2e-kind-ha-single-zone	[ed5299f](https://github.com/gardener/gardener/commit/ed5299fed868d2dcf640a9a85083f60b59f07b08)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7708/pull-gardener-e2e-kind-ha-single-zone/1639183147323101184)	true	`/test pull-gardener-e2e-kind-ha-single-zone`
> pull-gardener-e2e-kind	[ed5299f](https://github.com/gardener/gardener/commit/ed5299fed868d2dcf640a9a85083f60b59f07b08)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7708/pull-gardener-e2e-kind/1639183147516039168)	true	`/test pull-gardener-e2e-kind`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=7708). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Ashafeeqes). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

This failure is expected.
From the gardenlet [logs](https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/7708/pull-gardener-e2e-kind/1639183147516039168/artifacts/gardener-local/gardener-local-control-plane/pods/garden_gardenlet-6c5d4697f6-xpczr_669ac3ab-3caf-47d4-8568-5e10a51dc2ca/gardenlet/0.log) in the artefacts,
```
2023-03-24T08:38:26.247383286Z stderr F {"level":"error","ts":"2023-03-24T08:38:26.247Z","msg":"Reconciler error","controller":"backupbucket","namespace":"","name":"8589d682-6d15-48cb-acb8-e71e0320a518","reconcileID":"65fc325b-4007-42a7-b155-f7f4f1b5ed4a","error":"secrets \"generated-bucket-8589d682-6d15-48cb-acb8-e71e0320a518\" is forbidden: User \"gardener.cloud:system:seed:local\" cannot get resource \"secrets\" in API group \"\" in the namespace \"garden\": no relationship found between seed 'local' and this object","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}
```
https://github.com/gardener/gardener/pull/7708/commits/4b7be82fa5ba809d208c26f766b1766c259691ff should fix this.

**Comment by shafeeqes** [comment]
PTAL @rfranzke @ialidzhikov

File: pkg/gardenlet/controller/backupbucket/reconciler.go [hunk 1]
```diff
@@ -364,31 +362,31 @@ func (r *Reconciler) syncGeneratedSecretToGarden(ctx context.Context, backupBuck
...
+		// Update the BackupBucket status here before going for the CreateOrGetAndStrategicMergePatch call, so that the SeedAuthorizer
+		// can add the entry for this secret in the graph. See https://github.com/gardener/gardener/issues/7705 for more details.
+		patch := client.MergeFrom(backupBucket.DeepCopy())
+		backupBucket.Status.GeneratedSecretRef = &corev1.SecretReference{
 			Name:      gardenGeneratedSecret.Name,
 			Namespace: gardenGeneratedSecret.Namespace,
 		}
-	}
-
-	if gardenGeneratedSecretRef != nil || extensionBackupBucket.Status.ProviderStatus != nil {
```
Comment (rfranzke) [inline pkg/gardenlet/controller/backupbucket/reconciler.go:384]: Don't we still need this

```golang
if extensionBackupBucket.Status.ProviderStatus != nil {
```

condition here?

File: pkg/provider-local/controller/backupbucket/actuator.go [hunk 2]
```diff
@@ -66,3 +76,28 @@ func (a *actuator) Delete(_ context.Context, log logr.Logger, bb *extensionsv1al
...
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      v1beta1constants.SecretPrefixGeneratedBackupBucket + backupBucket.Name,
+			Namespace: v1beta1constants.GardenNamespace,
+		},
+	}
+
+	if _, err := controllerutil.CreateOrUpdate(ctx, a.client, generatedSecret, func() error {
+		generatedSecret.Data = map[string][]byte{
+			"foo": []byte("bar"),
+		}
```
Comment (rfranzke) [inline pkg/provider-local/controller/backupbucket/actuator.go]:
```suggestion
```

You could even leave this empty

File: pkg/provider-local/controller/backupbucket/actuator.go [hunk 3]
```diff
@@ -66,3 +76,28 @@ func (a *actuator) Delete(_ context.Context, log logr.Logger, bb *extensionsv1al
 	log.Info("Deleting directory", "path", path)
 	return os.RemoveAll(path)
 }
+
+func (a *actuator) createBackupBucketGeneratedSecret(ctx context.Context, backupBucket *extensionsv1alpha1.BackupBucket) error {
+	var generatedSecret = &corev1.Secret{
```
Comment (rfranzke) [inline pkg/provider-local/controller/backupbucket/actuator.go]:
```suggestion
	generatedSecret := &corev1.Secret{
```

File: pkg/gardenlet/controller/backupbucket/reconciler.go (hunk 1 above)
Comment (shafeeqes) [reply pkg/gardenlet/controller/backupbucket/reconciler.go:384]: Good catch, adapted.

File: pkg/gardenlet/controller/backupbucket/reconciler.go [hunk 4]
```diff
@@ -350,45 +350,52 @@ func (r *Reconciler) reconcileBackupBucketExtensionSecret(ctx context.Context, e
...
+			gardenGeneratedSecret.OwnerReferences = []metav1.OwnerReference{
+				*metav1.NewControllerRef(backupBucket, gardencorev1beta1.SchemeGroupVersion.WithKind("BackupBucket")),
+			}
+			controllerutil.AddFinalizer(gardenGeneratedSecret, finalizerName)
+			gardenGeneratedSecret.Data = seedGeneratedSecret.DeepCopy().Data
+			return nil
+		}); err != nil {
+			return err
+		}
+	}
```
Comment (rfranzke) [inline pkg/gardenlet/controller/backupbucket/reconciler.go]:
```suggestion
	if extensionBackupBucket.Status.GeneratedSecretRef != nil {
		gardenGeneratedSecretRef = &corev1.SecretReference{
			Name:      gardenGeneratedSecret.Name,
			Namespace: gardenGeneratedSecret.Namespace,
		}

		patch := client.MergeFrom(backupBucket.DeepCopy())
		// Update the BackupBucket status here before going for the CreateOrGetAndStrategicMergePatch call, so that the SeedAuthorizer
		// can add the entry for this secret in the graph. See https://github.com/gardener/gardener/issues/7705 for more details.
		backupBucket.Status.GeneratedSecretRef = gardenGeneratedSecretRef
		if err := r.GardenClient.Status().Patch(ctx, backupBucket, patch); err != nil {
			return err
		}

		seedGeneratedSecret, err := kubernetesutils.GetSecretByReference(ctx, r.SeedClient, extensionBackupBucket.Status.GeneratedSecretRef)
		if err != nil {
			return err
		}

		if _, err := controllerutils.CreateOrGetAndStrategicMergePatch(ctx, r.GardenClient, gardenGeneratedSecret, func() error {
			gardenGeneratedSecret.OwnerReferences = []metav1.OwnerReference{
				*metav1.NewControllerRef(backupBucket, gardencorev1beta1.SchemeGroupVersion.WithKind("BackupBucket")),
			}
			controllerutil.AddFinalizer(gardenGeneratedSecret, finalizerName)
			gardenGeneratedSecret.Data = seedGeneratedSecret.DeepCopy().Data
			return nil
		}); err != nil {
			return err
		}
	}
	
	if extensionBackupBucket.Status.ProviderStatus != nil {
		patch := client.MergeFrom(backupBucket.DeepCopy())
		backupBucket.Status.ProviderStatus = extensionBackupBucket.Status.ProviderStatus
		if err := r.GardenClient.Status().Patch(ctx, backupBucket, patch); err != nil {
			return err
		}
	}
```

This way, we'll have two status patches, but I think it's easier to read/more clear what happens.

File: pkg/provider-local/controller/backupbucket/actuator.go [hunk 5]
```diff
@@ -66,3 +76,26 @@ func (a *actuator) Delete(_ context.Context, log logr.Logger, bb *extensionsv1al
...
+func (a *actuator) createBackupBucketGeneratedSecret(ctx context.Context, backupBucket *extensionsv1alpha1.BackupBucket) error {
+	generatedSecret := &corev1.Secret{
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      v1beta1constants.SecretPrefixGeneratedBackupBucket + backupBucket.Name,
+			Namespace: v1beta1constants.GardenNamespace,
+		},
+	}
+
+	if _, err := controllerutil.CreateOrUpdate(ctx, a.client, generatedSecret, func() error {
+		generatedSecret.Data = map[string][]byte{}
```
Comment (rfranzke) [inline pkg/provider-local/controller/backupbucket/actuator.go]: Do you need this line?

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
