### PR TITLE
Fix Shoot deletion on Seeds with non-tolerated taints

### LINKED ISSUE #4889: Control planes on protected Seed cannot be deleted
**How to categorize this issue?**
/kind bug
/priority 3

**What happened**:
We have a Seed which was marked via the `Seed` resource as invisible (`.spec.settings.scheduling.visible=false`) and protected (`.spec.taints[0].key=seed.gardener.cloud/protected`) to prevent that new control planes can be scheduled to the Seed.

The existing control planes (also hibernated ones) hosted on the Seed can't be deleted anymore due to the following error which occurs during the deletion flow:

```
Error from server (Forbidden): shoots.core.gardener.cloud "shoot-xyz" is forbidden: forbidden to use a seeds whose taints are not tolerated by the shoot
```

**What you expected to happen**:
Shoot deletion to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Mark a non-empty Seed as protected
2. Trigger the deletion of a Shoot cluster whose control plane is hosted on the protected Seed
3. Observe the deletion flow of the Shoot

**Anything else we need to know?**:
Removing the `seed.gardener.cloud/protected` taint from the Seed unblock the deletion.

**Environment**:

- Gardener version: `v1.33.0`
- Kubernetes version (use `kubectl version`): Seed: `1.19.15`, cluster hosting Gardener: `v1.19.13-gke.1200`
- Cloud provider or hardware configuration: aws
- Others:

cc @vpnachev, @ScheererJ, @mliepold

### PR DESCRIPTION
**Pull request by voelzmo**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
With the changes done in #4521, we started to use the variable `oldShoot` inside `validateScheduling` to decide if looking at taints is necessary – even in the `action.Delete` scenario. Previously, this decision was explicitly filtered by looking at the action itself. Turns out `oldShoot` wasn't populated in the `action.Delete` case.

We now have the same 3 lines in the `delete` and `update` case – should we even extract this?

**Which issue(s) this PR fixes**:
Fixes #4889

**Special notes for your reviewer**:
Tested with local dev setup in addition to unit-test.

**Release note**:

```bugfix operator
Fixed a bug which prevented Shoot deletion on Seeds with non-tolerated taints.
```

### CODE REVIEW

File: plugin/pkg/shoot/validator/admission.go [hunk 1]
```diff
@@ -163,6 +163,11 @@ func (v *ValidateShoot) Admit(ctx context.Context, a admission.Attributes, o adm
 
 	if a.GetOperation() == admission.Delete {
 		shoot, convertIsSuccessful = a.GetOldObject().(*core.Shoot)
+		old, ok := a.GetOldObject().(*core.Shoot)
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission.go]: The doc string of `GetOldObject` says that:

```
// GetOldObject is the existing object. Only populated for UPDATE requests.
```

Do we have oldObject for DELETE requests?

Comment (voelzmo) [reply plugin/pkg/shoot/validator/admission.go]: I think it seems that `oldObject` is populated for `DELETE` as well. If I'm understanding https://github.com/gardener/gardener/blob/master/vendor/k8s.io/apiserver/pkg/registry/rest/delete.go#L176-L189 correctly, it seems that `object` isn't populated for `DELETE`.
Line 165 already had this assignment for the `shoot` variable and I guess if this returned `nil`, we would have seen crashes already somewhere? The change here just meant to also populate the `oldShoot` variable (with the same value for the `DELETE` case), such that the checks further down can successfully be executed.

Comment (voelzmo) [reply plugin/pkg/shoot/validator/admission.go]: While writing this, I realized that were now getting the old object twice in a row. It probably makes sense to set shoot and oldShoot both to oldObject at the same time.

**Review by timebertt — DISMISSED** [review]
Thanks!
/lgtm

File: plugin/pkg/shoot/validator/admission_test.go [hunk 2]
```diff
@@ -879,6 +880,20 @@ var _ = Describe("validator", func() {
 						Expect(err).To(HaveOccurred())
 					})
 
+					It("update should pass because the Seed stays the same, even if it has non-tolerated taints", func() {
+						oldShoot.Spec.SeedName = pointer.String("seed")
+						shoot.Spec.Provider.Workers[0].Maximum = 10
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission_test.go]: Do we need to set Shoot workers field as part of this test?
I guess it is rather a leftover, the test seems to be passing without it.

```suggestion
```

File: plugin/pkg/shoot/validator/admission.go (hunk 1 above)
Comment (ialidzhikov) [reply plugin/pkg/shoot/validator/admission.go]: Hmm, that's strange. Thanks for checking.
Then the conclusion is that the doc string of GetOldObject is misleading/wrong, right?

Comment (ialidzhikov) [reply plugin/pkg/shoot/validator/admission.go]: I now checked and can also confirm that OldObject is populated for `Delete` requests as well. Thanks for double-checking and sorry for bothering you with this. I created https://github.com/kubernetes/kubernetes/pull/105976 to fix this wrong/outdated doc string.

**Comment by ialidzhikov** [comment]
lgtm apart from the nit comment in https://github.com/gardener/gardener/pull/4911#discussion_r737491950.

I was able to verify in my local setup that deletion of Shoot on protected Seed is forbidden with the `master` branch and allowed with this PR.

File: plugin/pkg/shoot/validator/admission_test.go (hunk 2 above)
Comment (voelzmo) [reply plugin/pkg/shoot/validator/admission_test.go]: This is a change in the Shoot's spec to avoid an [early-exit optimization in the admission controller](https://github.com/gardener/gardener/blob/35e2bcf9916cea58bdedaac1231f9b521051df02/plugin/pkg/shoot/validator/admission.go#L180-L192). Probably  I should have added a comment to clarify this or chosen a better change indicating that this is just to really trigger running through the logic?

Comment (ialidzhikov) [reply plugin/pkg/shoot/validator/admission_test.go]: Ah, I see. Thanks for clarifying. +1 for adding a comment about this - it definitely makes sense (and would also prevent someone to delete this statement as at first look it looks unrelated to what we are testing in this test).

Comment (voelzmo) [reply plugin/pkg/shoot/validator/admission_test.go]: done, thanks!

**Review by ialidzhikov — DISMISSED** [review]
/lgtm

**Review by stoyanr — APPROVED** [review]
/lgtm

**Comment by stoyanr** [comment]
@timebertt @danielfoehrKn Do you have additional feedback or should we merge this?

**Review by timebertt — APPROVED** [review]
/lgtm
