### PR TITLE
Clear GRM secret finalizer from hibernated or broken clusters

### LINKED ISSUE #8882: GRM secret finalizer not removed for hibernated clusters
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
Because already hibernated clusters don't have a shoot GRM that will run the changed reconciliation logic from https://github.com/gardener/gardener/pull/8745 there will be shoot MR secrets that will still have GRM finalizer

**What you expected to happen**:
GRM finalizer to be removed on hibernated clusters

### PR DESCRIPTION
**Pull request by Kostov6**
**How to categorize this PR?**

/area quality
/kind cleanup

**What this PR does / why we need it**:
GRM secret reconciler was unable to clean up secret finalizers when a cluster was hibernated or broken
This PR makes gardenlet responsible to remove GRM secret finalizer on all managed resources.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/8882

**Release note**:

```other developer
On startup, `gardenlet` now removes the `resources.gardener.cloud/gardener-resource-manager` finalizer from `Secret`s related to `ManagedResource`s.
```

### CODE REVIEW

File: cmd/gardenlet/app/app.go [hunk 1]
```diff
@@ -460,6 +467,30 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+				log.Error(err, "Failed to get secret while cleaing up GRM finalizers")
+			}
+			for _, finalizer := range secret.Finalizers {
+				if strings.HasPrefix(finalizer, predicate.FinalizerName) {
+					if err := controllerutils.RemoveFinalizers(ctx, seedClient, secret, finalizer); err != nil {
+						log.Error(err, "Failed to remove finalizer while cleaing up GRM finalizers")
+					}
+				}
+			}
+		}
```
Comment (rfranzke) [inline cmd/gardenlet/app/app.go]: Please do this in parallel with `flow.Parallel`

File: cmd/gardenlet/app/app.go [hunk 2]
```diff
@@ -460,6 +467,30 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+func (g *garden) cleanupGRMSecretFinalizers(ctx context.Context, seedClient client.Client, log logr.Logger) error {
+	mrs := &resourcesv1alpha1.ManagedResourceList{}
+	if err := seedClient.List(ctx, mrs); err != nil {
+		log.Error(err, "Failed to list ManagedResources while cleaing up GRM finalizers")
+	}
+	secret := &corev1.Secret{}
+	for _, mr := range mrs.Items {
+		for _, ref := range mr.Spec.SecretRefs {
+			if err := g.mgr.GetClient().Get(ctx, client.ObjectKey{Namespace: mr.Namespace, Name: ref.Name}, secret); err != nil {
+				log.Error(err, "Failed to get secret while cleaing up GRM finalizers")
```
Comment (rfranzke) [inline cmd/gardenlet/app/app.go]: return error instead of logging

File: cmd/gardenlet/app/app.go [hunk 3]
```diff
@@ -460,6 +467,30 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
 	return flow.Parallel(taskFns...)(ctx)
 }
 
+// TODO(Kostov6): Remove this code after v1.89 has been released.
+func (g *garden) cleanupGRMSecretFinalizers(ctx context.Context, seedClient client.Client, log logr.Logger) error {
+	mrs := &resourcesv1alpha1.ManagedResourceList{}
+	if err := seedClient.List(ctx, mrs); err != nil {
+		log.Error(err, "Failed to list ManagedResources while cleaing up GRM finalizers")
```
Comment (rfranzke) [inline cmd/gardenlet/app/app.go]: return error instead of logging

File: cmd/gardenlet/app/app.go [hunk 4]
```diff
@@ -460,6 +467,30 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+	secret := &corev1.Secret{}
+	for _, mr := range mrs.Items {
+		for _, ref := range mr.Spec.SecretRefs {
+			if err := g.mgr.GetClient().Get(ctx, client.ObjectKey{Namespace: mr.Namespace, Name: ref.Name}, secret); err != nil {
+				log.Error(err, "Failed to get secret while cleaing up GRM finalizers")
+			}
+			for _, finalizer := range secret.Finalizers {
+				if strings.HasPrefix(finalizer, predicate.FinalizerName) {
+					if err := controllerutils.RemoveFinalizers(ctx, seedClient, secret, finalizer); err != nil {
+						log.Error(err, "Failed to remove finalizer while cleaing up GRM finalizers")
```
Comment (rfranzke) [inline cmd/gardenlet/app/app.go]: return error instead of logging

**Review by rfranzke — CHANGES_REQUESTED** [review]

File: cmd/gardenlet/app/app.go (hunk 2 above)
Comment (Kostov6) [reply cmd/gardenlet/app/app.go]: I wasn't sure how to handle the error and decided to log the error instead of throwing it because if the cleanup logic fails it will put gardenlet in CrashLoopBackOff and prevent doing it's intended work. Can you explain why returning the error is the preferred way because I don't well understand when to use one or the other?

Comment (rfranzke) [reply cmd/gardenlet/app/app.go]: Returning the error is always the preferred way. There are just a few exceptional cases when this is not done, and such cases are those that should be justified.
In this specific case, an error will probably only happen when the seed's API server is down or has problems. Then `gardenlet` will have other issues anyways and will fail eventually.

File: cmd/gardenlet/app/app.go [hunk 5]
```diff
@@ -460,6 +467,30 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
 	return flow.Parallel(taskFns...)(ctx)
 }
 
+// TODO(Kostov6): Remove this code after v1.89 has been released.
+func (g *garden) cleanupGRMSecretFinalizers(ctx context.Context, seedClient client.Client, log logr.Logger) error {
+	mrs := &resourcesv1alpha1.ManagedResourceList{}
+	if err := seedClient.List(ctx, mrs); err != nil {
+		log.Error(err, "Failed to list ManagedResources while cleaing up GRM finalizers")
+	}
+	secret := &corev1.Secret{}
```
Comment (plkokanov) [inline cmd/gardenlet/app/app.go]: A new secret should be created for each iteration otherwise you will always `Get` data fields into the same object and potentially keep data from the previous iteration in it. This could lead to potential issues when calling `Patch`.
You will anyway have to use separate secret objects when removing the finalizers in parallel.

**Review by plkokanov — CHANGES_REQUESTED** [review]

File: cmd/gardenlet/app/app.go [hunk 6]
```diff
@@ -460,6 +467,36 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+	var taskFns []flow.TaskFn
+
+	mrs := &resourcesv1alpha1.ManagedResourceList{}
+	if err := seedClient.List(ctx, mrs); err != nil {
+		return fmt.Errorf("failed to list ManagedResources while cleaing up GRM finalizers: %w", err)
+	}
+	for _, mr := range mrs.Items {
+		mr := mr
+		taskFns = append(taskFns, func(ctx context.Context) error {
+			secret := &corev1.Secret{}
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go:488]: As discussed, you could move this to L483.

File: cmd/gardenlet/app/app.go [hunk 7]
```diff
@@ -460,6 +467,36 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+			for _, ref := range mr.Spec.SecretRefs {
+				if err := g.mgr.GetClient().Get(ctx, client.ObjectKey{Namespace: mr.Namespace, Name: ref.Name}, secret); err != nil {
+					return fmt.Errorf("failed to get secret while cleaing up GRM finalizers: %w", err)
+				}
+				for _, finalizer := range secret.Finalizers {
+					if strings.HasPrefix(finalizer, predicate.FinalizerName) {
+						if err := controllerutils.RemoveFinalizers(ctx, seedClient, secret, finalizer); err != nil {
+							return fmt.Errorf("failed to remove finalizer while cleaing up GRM finalizers: %w", err)
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]:
```suggestion
							return fmt.Errorf("failed to remove finalizer while cleaning up GRM finalizers: %w", err)

```

File: cmd/gardenlet/app/app.go [hunk 8]
```diff
@@ -460,6 +467,36 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
 
+// TODO(Kostov6): Remove this code after v1.91 has been released.
+func (g *garden) cleanupGRMSecretFinalizers(ctx context.Context, seedClient client.Client, log logr.Logger) error {
+	var taskFns []flow.TaskFn
+
+	mrs := &resourcesv1alpha1.ManagedResourceList{}
+	if err := seedClient.List(ctx, mrs); err != nil {
+		return fmt.Errorf("failed to list ManagedResources while cleaning up GRM finalizers: %w", err)
+	}
+	for _, mr := range mrs.Items {
```
Comment (plkokanov) [inline cmd/gardenlet/app/app.go]: You could try to reuse https://github.com/gardener/gardener/blob/0af0b2209fd9c12f7534aef97384e52c8d00c1a3/pkg/utils/kubernetes/client/client.go#L408

**Review by plkokanov — CHANGES_REQUESTED** [review]

File: cmd/gardenlet/app/app.go [hunk 9]
```diff
@@ -73,10 +74,12 @@ import (
 	"github.com/gardener/gardener/pkg/gardenlet/controller"
 	gardenerhealthz "github.com/gardener/gardener/pkg/healthz"
 	"github.com/gardener/gardener/pkg/resourcemanager/controller/garbagecollector/references"
+	"github.com/gardener/gardener/pkg/resourcemanager/predicate"
 	"github.com/gardener/gardener/pkg/utils"
 	"github.com/gardener/gardener/pkg/utils/flow"
 	gardenerutils "github.com/gardener/gardener/pkg/utils/gardener"
 	kubernetesutils "github.com/gardener/gardener/pkg/utils/kubernetes"
+	clientutils "github.com/gardener/gardener/pkg/utils/kubernetes/client"
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]: Nit: for consistency with the other import aliases for the same import>

```suggestion
	utilclient "github.com/gardener/gardener/pkg/utils/kubernetes/client"
```

File: cmd/gardenlet/app/app.go [hunk 10]
```diff
@@ -460,6 +468,38 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
 	return flow.Parallel(taskFns...)(ctx)
 }
 
+// TODO(Kostov6): Remove this code after v1.91 has been released.
+func (g *garden) cleanupGRMSecretFinalizers(ctx context.Context, seedClient client.Client) error {
+	mrs := &resourcesv1alpha1.ManagedResourceList{}
+	if err := seedClient.List(ctx, mrs); err != nil {
+		if meta.IsNoMatchError(err) {
+			// resources.gardener.cloud/v1alpha1 CRD not yet applied
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]: You can add a log entry with proper explanation instead of comment that does not explain much (why the CRD is not yet applied for example).

```suggestion
			log.Info("Received a 'no match error' while trying to list managed resources. Will assume that the managed resources CRD is not yet installed (for example new Seed creation) and will skip cleaning up GRM finalizers.")

```

File: cmd/gardenlet/app/app.go [hunk 11]
```diff
@@ -460,6 +468,38 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+			return nil
+		}
+		return fmt.Errorf("failed to list ManagedResources while cleaning up GRM finalizers: %w", err)
+	}
+	return clientutils.ApplyToObjects(ctx, mrs, func(ctx context.Context, obj client.Object) error {
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]:
```suggestion

	return clientutils.ApplyToObjects(ctx, mrs, func(ctx context.Context, obj client.Object) error {
```

File: cmd/gardenlet/app/app.go [hunk 12]
```diff
@@ -460,6 +468,38 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+		mr, ok := obj.(*resourcesv1alpha1.ManagedResource)
+		if !ok {
+			return fmt.Errorf("expected *resourcesv1alpha1.ManagedResource but got %T", obj)
+		}
+		for _, ref := range mr.Spec.SecretRefs {
+			secret := &corev1.Secret{}
+			if err := g.mgr.GetClient().Get(ctx, client.ObjectKey{Namespace: mr.Namespace, Name: ref.Name}, secret); err != nil {
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]: You already have the `seedClient` var, no need to use `g.mgr.GetClient()`.
```suggestion
			if err := seedClient.Get(ctx, client.ObjectKey{Namespace: mr.Namespace, Name: ref.Name}, secret); err != nil {
```

File: cmd/gardenlet/app/app.go [hunk 13]
```diff
@@ -460,6 +468,38 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
 	return flow.Parallel(taskFns...)(ctx)
 }
 
+// TODO(Kostov6): Remove this code after v1.91 has been released.
+func (g *garden) cleanupGRMSecretFinalizers(ctx context.Context, seedClient client.Client) error {
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]: Instead of `g.mgr.GetClient()` you can use the `seedClient`.

```suggestion
func cleanupGRMSecretFinalizers(ctx context.Context, seedClient client.Client) error {
```

File: cmd/gardenlet/app/app.go [hunk 14]
```diff
@@ -460,6 +468,38 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+			// resources.gardener.cloud/v1alpha1 CRD not yet applied
+			return nil
+		}
+		return fmt.Errorf("failed to list ManagedResources while cleaning up GRM finalizers: %w", err)
+	}
+	return clientutils.ApplyToObjects(ctx, mrs, func(ctx context.Context, obj client.Object) error {
+		mr, ok := obj.(*resourcesv1alpha1.ManagedResource)
+		if !ok {
+			return fmt.Errorf("expected *resourcesv1alpha1.ManagedResource but got %T", obj)
+		}
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go:485]:
```suggestion
		}

```

File: cmd/gardenlet/app/app.go [hunk 15]
```diff
@@ -460,6 +468,38 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+		for _, ref := range mr.Spec.SecretRefs {
+			secret := &corev1.Secret{}
+			if err := g.mgr.GetClient().Get(ctx, client.ObjectKey{Namespace: mr.Namespace, Name: ref.Name}, secret); err != nil {
+				return fmt.Errorf("failed to get secret while cleaning up GRM finalizers: %w", err)
+			}
+			for _, finalizer := range secret.Finalizers {
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]: You can split the different logical parts of the code with a new line

```suggestion
			}

			for _, finalizer := range secret.Finalizers {
```

File: cmd/gardenlet/app/app.go [hunk 16]
```diff
@@ -460,6 +468,38 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+				if strings.HasPrefix(finalizer, predicate.FinalizerName) {
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]: There is already the const `grmFinalizer`:

```suggestion
				if strings.HasPrefix(finalizer, grmFinalizer) {
```

File: cmd/gardenlet/app/app.go [hunk 17]
```diff
@@ -460,6 +468,38 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+					if err := controllerutils.RemoveFinalizers(ctx, seedClient, secret, finalizer); err != nil {
+						return fmt.Errorf("failed to remove finalizer while cleaning up GRM finalizers: %w", err)
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]: You don't need the `while cleaning up GRM finalizers` part. This information can be added when error is wrapped from the called. For example `failed to clean up GRM finalizers: failed to remove finalizer: <other-error>`.

```suggestion
						return fmt.Errorf("failed to remove finalizer from secret '%s': %w", client.ObjectKeyFromObject(secret), err)
```

File: cmd/gardenlet/app/app.go [hunk 18]
```diff
@@ -460,6 +468,38 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
+	}
+	return clientutils.ApplyToObjects(ctx, mrs, func(ctx context.Context, obj client.Object) error {
+		mr, ok := obj.(*resourcesv1alpha1.ManagedResource)
+		if !ok {
+			return fmt.Errorf("expected *resourcesv1alpha1.ManagedResource but got %T", obj)
+		}
+		for _, ref := range mr.Spec.SecretRefs {
+			secret := &corev1.Secret{}
+			if err := g.mgr.GetClient().Get(ctx, client.ObjectKey{Namespace: mr.Namespace, Name: ref.Name}, secret); err != nil {
+				return fmt.Errorf("failed to get secret while cleaning up GRM finalizers: %w", err)
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]:
```suggestion
				return fmt.Errorf("failed to get secret '%s': %w", client.ObjectKeyFromObject(secret), err)
```

File: cmd/gardenlet/app/app.go [hunk 19]
```diff
@@ -460,6 +468,38 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
...
 
+// TODO(Kostov6): Remove this code after v1.91 has been released.
+func (g *garden) cleanupGRMSecretFinalizers(ctx context.Context, seedClient client.Client) error {
+	mrs := &resourcesv1alpha1.ManagedResourceList{}
+	if err := seedClient.List(ctx, mrs); err != nil {
+		if meta.IsNoMatchError(err) {
+			// resources.gardener.cloud/v1alpha1 CRD not yet applied
+			return nil
+		}
+		return fmt.Errorf("failed to list ManagedResources while cleaning up GRM finalizers: %w", err)
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]:
```suggestion
		return fmt.Errorf("failed to list managed resources: %w", err)
```

File: cmd/gardenlet/app/app.go [hunk 20]
```diff
@@ -381,6 +384,11 @@ func (g *garden) Start(ctx context.Context) error {
 		return err
 	}
 
+	log.Info("Cleaning up GRM secret finalizers")
+	if err := g.cleanupGRMSecretFinalizers(ctx, g.mgr.GetClient()); err != nil {
+		return err
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]:
```suggestion
		return fmt.Errorf("failed to clean up GRM secret finalizers: %w", err)
```

File: cmd/gardenlet/app/app.go [hunk 21]
```diff
@@ -73,10 +74,12 @@ import (
 	"github.com/gardener/gardener/pkg/gardenlet/controller"
 	gardenerhealthz "github.com/gardener/gardener/pkg/healthz"
 	"github.com/gardener/gardener/pkg/resourcemanager/controller/garbagecollector/references"
+	"github.com/gardener/gardener/pkg/resourcemanager/predicate"
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]: This import should be removed once you use the `grmFinalizer` const.

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

File: cmd/gardenlet/app/app.go [hunk 22]
```diff
@@ -460,6 +467,41 @@ func (g *garden) cleanupOrphanedExtensionsServiceAccounts(ctx context.Context, g
 	return flow.Parallel(taskFns...)(ctx)
 }
 
+// TODO(Kostov6): Remove this code after v1.91 has been released.
+func cleanupGRMSecretFinalizers(ctx context.Context, seedClient client.Client, log logr.Logger) error {
+	mrs := &resourcesv1alpha1.ManagedResourceList{}
+	if err := seedClient.List(ctx, mrs); err != nil {
+		if meta.IsNoMatchError(err) {
+			log.Info("Received a 'no match error' while trying to list managed resources. Will assume that the managed resources CRD is not yet installed (for example new Seed creation) and will skip cleaning up GRM finalizers.")
```
Comment (ialidzhikov) [inline cmd/gardenlet/app/app.go]:
```
Executing golangci-lint
cmd/gardenlet/app/app.go:475:13: structured logging message should not end with punctuation mark: "Received a 'no match error' while trying to list managed resources. Will assume that the managed resources CRD is not yet installed (for example new Seed creation) and will skip cleaning up GRM finalizers." (logcheck)
			log.Info("Received a 'no match error' while trying to list managed resources. Will assume that the managed resources CRD is not yet installed (for example new Seed creation) and will skip cleaning up GRM finalizers.")
```

Ups, I missed this when suggesting the change.

```suggestion
			log.Info("Received a 'no match error' while trying to list managed resources. Will assume that the managed resources CRD is not yet installed (for example new Seed creation) and will skip cleaning up GRM finalizers")
```

**Review by ialidzhikov — COMMENTED** [review]
/approve

**Comment by ialidzhikov** [comment]
```
  [FAILED] in [It] - /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/seed/renew_gardenlet_kubeconfig.go:63 @ 01/08/24 09:39:56.208
  < Exit [It] should renew the gardenlet garden kubeconfig when triggered by annotation @ 01/08/24 09:39:56.208 (30.013s)
  << Timeline
  [FAILED] Timed out after 30.001s.
  The function passed to Eventually failed at /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/seed/renew_gardenlet_kubeconfig.go:62 with:
  Expected
      <map[string]string | len:2>: {
          "gardener.cloud/operation": "renew-kubeconfig",
          "provider-local-e2e-test-garden-access": "2024-01-08T09:29:03Z",
      }
  not to have key
      <string>: gardener.cloud/operation
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/seed/renew_gardenlet_kubeconfig.go:63 @ 01/08/24 09:39:56.208
```

Occurrence of https://github.com/gardener/gardener/issues/8954.

---

/test pull-gardener-e2e-kind
