### PR TITLE
Deflake integration tests

### LINKED ISSUE #7990: [Flaky Test] Garden controller tests
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
• [FAILED] [17.344 seconds]
Garden controller tests [It] should properly maintain the Reconciled condition
/home/prow/go/src/github.com/gardener/gardener/test/integration/operator/garden/garden_test.go:236
```

**CI link**:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7981/pull-gardener-integration/1662033418336079872
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7981/pull-gardener-integration/1661805577690419200
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7961/pull-gardener-integration/1661664314173427712

**Reason for failure**:

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
- Gardenlet Shoot Care Suite.
We need to create the seed and project only once. This PR moves the seed and project creation from BeforeEach to BeforeSuite.

  - https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7989/pull-gardener-integration/1662050474792062976
  - https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7981/pull-gardener-integration/1661805577690419200
  - https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7973/pull-gardener-integration/1661259252641042432

Before:
```
$ stress -p 32 ./test/integration/gardenlet/shoot/care/care.test
...
10m55s: 622 runs so far, 2 failures (0.32%)
11m0s: 628 runs so far, 2 failures (0.32%)
11m5s: 628 runs so far, 2 failures (0.32%)
11m10s: 638 runs so far, 2 failures (0.31%)
```
After:
```
$ stress -p 32 ./test/integration/gardenlet/shoot/care/care.test
...
17m50s: 1016 runs so far, 0 failures
17m55s: 1016 runs so far, 0 failures
18m0s: 1025 runs so far, 0 failures
18m5s: 1026 runs so far, 0 failures
```

- Garden controller tests:
Fake waiting for components to be healthy by faking the `until` function in tests.

Before:
```
❯ stress -p 16 ./test/integration/operator/garden/garden.test
...
13m25s: 565 runs so far, 6 failures (1.06%)
13m30s: 565 runs so far, 6 failures (1.06%)
13m35s: 575 runs so far, 6 failures (1.04%)
13m40s: 580 runs so far, 6 failures (1.03%)
```
After
```
❯ stress -p 16 ./test/integration/operator/garden/garden.test
...
11m25s: 563 runs so far, 0 failures
11m30s: 568 runs so far, 0 failures
11m35s: 577 runs so far, 0 failures
11m40s: 577 runs so far, 0 failures
11m45s: 578 runs so far, 0 failures
```

**Which issue(s) this PR fixes**:
Fixes #7990 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
Pod scheduling timeout. 
/retest

File: test/integration/operator/garden/garden_test.go [hunk 1]
```diff
@@ -251,8 +258,6 @@ var _ = Describe("Garden controller tests", func() {
 		Expect(garden.Status.Gardener).NotTo(BeNil())
 
 		By("Verify that the custom resource definitions have been created")
-		// When the controller succeeds then it deletes the `ManagedResource` CRD, so we only need to ensure here that
-		// the `ManagedResource` API is no longer available.
```
Comment (ialidzhikov) [inline test/integration/operator/garden/garden_test.go:255]: With @acumino we got curious about this change and we dig into it. 
In short, we think that we can apply the following diff (not strictly related to this PR):
```diff
diff --git a/test/integration/operator/garden/garden_test.go b/test/integration/operator/garden/garden_test.go
index 6e9a69255..2099b0743 100644
--- a/test/integration/operator/garden/garden_test.go
+++ b/test/integration/operator/garden/garden_test.go
@@ -264,7 +264,9 @@ var _ = Describe("Garden controller tests", func() {
 			return crdList.Items
 		}).Should(ContainElements(
 			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("hvpas.autoscaling.k8s.io")})}),
+			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("managedresources.resources.gardener.cloud")})}),
 			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("verticalpodautoscalers.autoscaling.k8s.io")})}),
+			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("verticalpodautoscalercheckpoints.autoscaling.k8s.io")})}),
 			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("authorizationpolicies.security.istio.io")})}),
 			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("destinationrules.networking.istio.io")})}),
 			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("envoyfilters.networking.istio.io")})}),
@@ -625,8 +627,6 @@ var _ = Describe("Garden controller tests", func() {
 		}).Should(BeNotFoundError())
 
 		By("Verify that the custom resource definitions have been deleted")
-		// When the controller succeeds then it deletes the `ManagedResource` CRD, so we only need to ensure here that
-		// the `ManagedResource` API is no longer available.
 		Eventually(func(g Gomega) []apiextensionsv1.CustomResourceDefinition {
 			crdList := &apiextensionsv1.CustomResourceDefinitionList{}
 			g.Expect(testClient.List(ctx, crdList)).To(Succeed())
@@ -634,6 +634,9 @@ var _ = Describe("Garden controller tests", func() {
 		}).ShouldNot(ContainElements(
 			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("hvpas.autoscaling.k8s.io")})}),
 			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("etcds.druid.gardener.cloud")})}),
+			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("managedresources.resources.gardener.cloud")})}),
+			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("verticalpodautoscalers.autoscaling.k8s.io")})}),
+			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("verticalpodautoscalercheckpoints.autoscaling.k8s.io")})}),
 			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("authorizationpolicies.security.istio.io")})}),
 			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("destinationrules.networking.istio.io")})}),
 			MatchFields(IgnoreExtras, Fields{"ObjectMeta": MatchFields(IgnoreExtras, Fields{"Name": Equal("envoyfilters.networking.istio.io")})}),
```

**Review by ialidzhikov — COMMENTED** [review]
We had a joint look with @acumino. Only one suggestion, otherwise lgtm.

/approve

**Review by ialidzhikov — APPROVED** [review]
/lgtm
