### PR TITLE
Deploy `cluster-identity` managed resource on the seed conditionally

### LINKED ISSUE #6896: Gardenlet might fail to delete seed when runs in a combined garden/seed clusters
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:
Deleting the seed cluster in `garden-local` setup failed ([test ref](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6865/pull-gardener-e2e-kind/1584815215726301184)), because gardenlet panicked ([ref](https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/6865/pull-gardener-e2e-kind/1584815215726301184/artifacts/gardener-local-control-plane/pods/garden_gardenlet-9844b75fc-qc85r_1b0fbd55-2f50-4e93-8715-9cb5de39c476/gardenlet/4.log)).

`gardenlet` panicked because `cluster-identity` configmap was not found, when it was restarting during the deletion process.
It might have been restarted by VPA when `cluster-identity` was already deleted.

There is a migration scenario which includes three steps.
- [x] 1. Annotate the content of `cluster-identity`  managed resource of the seed with `resources.gardener.cloud/mode: Ignore` if `cluster-identity` config map is already existing. Switch `cluster-identity` config maps originated by the shoots to immutable. https://github.com/gardener/gardener/pull/7436
- [x] 2. Delete `cluster-identity` config map in the same case. Switch `cluster-identity` config maps originated by gardener-apiserver and the seeds to immutable. https://github.com/gardener/gardener/pull/7569
- [x] 3. https://github.com/gardener/gardener/pull/7851

**What you expected to happen**:
Seed deletion to work robustly in combined garden/seed clusters too.
On seed creation `cluster-identity` configmap could be created only, if it is not existing yet. This should prevent it from being deleted too early. 

**How to reproduce it (as minimally and precisely as possible)**:
Could be reproduced in `garden-local` setup.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.59-dev
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area robustness
/kind technical-debt

**What this PR does / why we need it**:
With this PR the `cluster-identity` config map in the `kube-system` namespace of the seed is deployed only if it is not existing yet.
This prevents that this config map is deleted on seed deletion even if it was created by a different origin. 
Additionally, `cluster-identity` config map now becomes immutable as it should not change in the clusters lifetime. 

There is a migration scenario which includes three steps.
1. Annotate the content of `cluster-identity`  managed resource of the seed with `resources.gardener.cloud/mode: Ignore` if `cluster-identity` config map is already existing.
  Switch `cluster-identity` config maps originated by the shoots to immutable.
2. Delete `cluster-identity` config map in the same case.
    Switch `cluster-identity` config maps originated by gardener-apiserver and the seeds to immutable. 
3. Remove the migration code.

This PR represents step 1.

**Which issue(s) this PR fixes**:
Part of #6896

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
When deleting a seed the `cluster-identity` config map in `kube-system` namespace is not deleted anymore if it was already existing on seed creation.
```

### CODE REVIEW

File: pkg/apis/core/v1beta1/constants/types_constants.go [hunk 1]
```diff
@@ -648,6 +648,14 @@ const (
 
 	// ClusterIdentity is a constant equal to the name and data key (that stores the identity) of the cluster-identity ConfigMap
 	ClusterIdentity = "cluster-identity"
+	// ClusterIdentityOrigin is a constant equal to the data key that stores the identity origin of the cluster-identity ConfigMap
+	ClusterIdentityOrigin = "cluster-identity-origin"
+	// ClusterIdentityOriginGardenerApiServer defines a cluster-identity ConfigMap originated from gardener-apiserver
+	ClusterIdentityOriginGardenerApiServer = "gardener-apiserver"
```
Comment (rfranzke) [inline pkg/apis/core/v1beta1/constants/types_constants.go]:
```suggestion
	ClusterIdentityOriginGardenerAPIServer = "gardener-apiserver"
```

File: pkg/apis/core/v1beta1/constants/types_constants.go [hunk 2]
```diff
@@ -648,6 +648,14 @@ const (
 
 	// ClusterIdentity is a constant equal to the name and data key (that stores the identity) of the cluster-identity ConfigMap
 	ClusterIdentity = "cluster-identity"
+	// ClusterIdentityOrigin is a constant equal to the data key that stores the identity origin of the cluster-identity ConfigMap
+	ClusterIdentityOrigin = "cluster-identity-origin"
```
Comment (rfranzke) [inline pkg/apis/core/v1beta1/constants/types_constants.go]:
```suggestion
	ClusterIdentityOrigin = "origin"
```

File: pkg/gardenlet/controller/seed/seed/reconciler_delete.go [hunk 3]
```diff
@@ -296,6 +295,20 @@ func (r *Reconciler) runDeleteSeedFlow(
 		})
 	)
 
+	// Use the managed resource for cluster-identity only if there is no cluster-identity config map in kube-system namespace from a different origin than seed.
+	// This prevents gardenlet from deleting the config map accidently on seed deletion when it was created by a different party (gardener-apiserver or shoot).
```
Comment (rfranzke) [inline pkg/gardenlet/controller/seed/seed/reconciler_delete.go]:
```suggestion
	// This prevents gardenlet from deleting the config map accidentally on seed deletion when it was created by a different party (gardener-apiserver or shoot).
```

File: pkg/operation/botanist/component/clusteridentity/clusteridentity.go [hunk 4]
```diff
@@ -150,3 +155,17 @@ func (c *clusterIdentity) WaitCleanup(ctx context.Context) error {
...
+	clusterIdentity := &corev1.ConfigMap{}
+	if err := c.Get(ctx, kubernetesutils.Key(metav1.NamespaceSystem, v1beta1constants.ClusterIdentity), clusterIdentity); err != nil {
+		if apierrors.IsNotFound(err) {
+			return true, nil
+		}
+		return false, err
+	}
+	// TODO(oliver-goetz): do not treat an empty origin as foreign origin anymore in a future release when shoot clusters have been reconciled at least once
+	sameOrigin := clusterIdentity.Data[v1beta1constants.ClusterIdentityOrigin] == origin
+	return sameOrigin, nil
```
Comment (rfranzke) [inline pkg/operation/botanist/component/clusteridentity/clusteridentity.go]:
```suggestion
	return clusterIdentity.Data[v1beta1constants.ClusterIdentityOrigin] == origin, nil
```

File: pkg/operation/botanist/component/clusteridentity/clusteridentity_test.go [hunk 5]
```diff
@@ -284,4 +289,54 @@ metadata:
 			Expect(clusterIdentity.WaitCleanup(ctx)).To(Succeed())
 		})
 	})
+
+	Describe("CheckNonSeedClusterIdentityExists", func() {
```
Comment (rfranzke) [inline pkg/operation/botanist/component/clusteridentity/clusteridentity_test.go]:
```suggestion
	Describe("#IsClusterIdentityEmptyOrFromOrigin", func() {
```

**Comment by rfranzke** [comment]
Let's keep https://github.com/gardener/gardener/issues/6896 open to track the other steps.

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
