### PR TITLE
Suppress the event-logger `nest` filter's warnings

### LINKED ISSUE #7672: fluent-bit sometimes throws warnings because of the event-logger
**How to categorize this issue?**

/area logging
/kind bug

**What happened**:
Currently, the event-logger component has `nest` fluent-bit filter which lifts the JSON properties under the `log`:
```
    [FILTER]
        Name                nest
        Match               kubernetes.*event-logger*event-logger*
        Operation           lift
        Nested_under        log
```
This works fine for the way the event-logger dumps its events on the stdout, example:
```
{"origin":"seed","namespace":"shoot--i355448--local-shoot","type":"Normal","count":1,"eventTime":null,"firstTimestamp":"2023-03-20T12:43:11Z","lastTimestamp":"2023-03-20T12:43:11Z","reason":"ScalingReplicaSet","object":"Deployment/gardener-resource-manager","_entry":"Scaled up replica set gardener-resource-manager-7b88dffcd6 to 1","source":"deployment-controller"}
```
But if for any reason there is an error in the event-logger, example:
```
E0320 12:43:10.589412       1 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Event: Unauthorized
```

Then the fluent-bit filter will fail which will cause warnings in the fluent-bit:
```
[2023/03/20 12:41:31] [ warn] [filter:nest:nest.42] Value of key 'log' is not a map. Will not attempt to lift from here
```

**What you expected to happen**:
The fluent-bit should handle such cases when the event-logger fails.

### PR DESCRIPTION
**Pull request by vlvasilev**
**How to categorize this PR?**

/area logging
/kind enhancement

**What this PR does / why we need it**:
When `event-logger` pod gets an error during its work with the `go-client` library it writes a log in non-JSON format.
This non-JSON can't be `lifted` by the event-logger `nest` filter in the `fluent-bit`. This triggers warning which flood the fluent-bit logs with meaningless warnings. This PR changes the log level of this `nest` filter to error in order to suppress the redundant warning messages

**Which issue(s) this PR fixes**:
Fixes [#7672](https://github.com/gardener/gardener/issues/7672)

**Special notes for your reviewer**:

**Release note**:

```other operator
Suppress the event-logger `nest` filter's warnings in the fluent-bit.
```

### CODE REVIEW

File: pkg/operation/botanist/component/logging/eventlogger/logging.go [hunk 1]
```diff
@@ -25,6 +25,7 @@ const (
     Match               kubernetes.*` + v1beta1constants.DeploymentNameEventLogger + `*` + name + `*
     Operation           lift
     Nested_under        log
+    log_level           error
```
Comment (acumino) [inline pkg/operation/botanist/component/logging/eventlogger/logging.go]: Will it be like below, or it work in any format?
```suggestion
    Log_Level           error
```

**Comment by acumino** [comment]
Can you please check the failing unit test?

**Review by acumino — APPROVED** [review]
/lgtm
