### PR TITLE
Best-effort wait time for infrastructure resource cleanup

### LINKED ISSUE #1311: AliCloud Regression: Loadbalancers can't be deleted in shoot cluster
**What happened**:
After deletion of shoot cluster, SLBs  are not deleted.
**What you expected to happen**:
External resources should be deleted successfully
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Gardener should wait for SLBs to be deleted in Shoot Deletion loop. I also found some disks leftovers, but it seems that they were left during the unstable development phase. Anyway, will keep an eye on it.
**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: AliCloud
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
Services (and other objects that have a footprint in the infrastructure) still don't have finalizers yet. There is no way to determine whether all the resources have been deleted successfully yet, whether there was an error, or whether they are still pending. While most providers have implemented custom clean up already (basically, duplicated the code in the CCM) not everybody
has, especially not for all objects.
Until service finalizers are enabled by default with Kubernetes 1.16 and our minimum supported shoot version is raised to 1.16 we can not do much more than best-effort waiting until everything has been cleaned up. That's what the following task is doing.

**Which issue(s) this PR fixes**:
Fixes #1311 
gardener/gardener-extensions#257

**Release note**:

```noteworthy operator
Due to lack of possibilities to check whether all infrastructure resources have been cleaned up Gardener now waits on a best-effort base before continuing the shoot deletion flow.
```

### CODE REVIEW

**Review by zanetworker — DISMISSED** [review]
/lgtm

File: pkg/controllermanager/controller/shoot/shoot_control_delete.go [hunk 1]
```diff
@@ -288,18 +295,23 @@ func (c *Controller) runDeleteShootFlow(o *operation.Operation) *gardencorev1alp
...
+		// Services (and other objects that have a footprint in the infrastructure) still don't have finalizers yet. There is no way to
+		// determine whether all the resources have been deleted successfully yet, whether there was an error, or whether they are still
+		// pending. While most providers have implemented custom clean up already (basically, duplicated the code in the CCM) not everybody
+		// has, especially not for all objects.
+		// Until service finalizers are enabled by default with Kubernetes 1.16 and our minimum supported seed version is raised to 1.16 we
+		// can not do much more than best-effort waiting until everything has been cleaned up. That's what the following task is doing.
+		timeForInfrastructureResourceCleanup = g.Add(flow.Task{
+			Name: "Waiting until time for infrastructure resource cleanup has elapsed",
+			Fn: flow.TaskFn(func(_ context.Context) error {
+				time.Sleep(5 * time.Minute)
```
Comment (timuthy) [inline pkg/controllermanager/controller/shoot/shoot_control_delete.go]: Another option would be to use the context of the flow:

```
ctx, cancel := context.WithTimeout(ctx, 5 * time.Minute)
defer cancel()
ctxDone := ctx.Done()

select {
  case <-ctxDone:
    return nil
  }
}

```

**Review by timuthy — APPROVED** [review]
/lgtm

**Comment by jia-jerry** [comment]
Thank you @rfranzke  Would you please cherry-pick to hotfix? e2e tests will generate too many leftover elbs

**Comment by rfranzke** [comment]
Yes, we'll need a few other things and then will create a hotfix (probably tomorrow).
