### PR TITLE
[operator] Cleanup virtual-garden `ManagedResources` before destroying `virtual-garden-kube-apiserver`

### LINKED ISSUE #8367: `operator` e2e tests flake because virtual-garden managed resources are not always cleaned up
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
`operator` tests are flaky, because not all managed resources of virtual-garden could be cleaned up when deleting `garden`.
`virtual-gardener-kube-apiserver` might be deleted too early.

**What you expected to happen**:
`garden` to be deleted reliably.

**How to reproduce it (as minimally and precisely as possible)**:
occurrences:
https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind-operator/1689170227515887616
https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind-operator/1688868234310193152
https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind-operator/1688264041316749312
https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind-operator/1686391184026505216

**Anything else we need to know?**:
Error message from `operator` log:
```
2023-08-09T07:26:27.911307468Z stderr F {"level":"info","ts":"2023-08-09T07:26:27.911Z","msg":"Service DNS name lookup of virtual-garden-kube-apiserver failed, falling back to external kubeconfig","clientmap":"GardenClientMap","error":"lookup virtual-garden-kube-apiserver.garden.svc.cluster.local on 10.2.0.10:53: no such host"}
2023-08-09T07:26:27.911482378Z stderr F {"level":"info","ts":"2023-08-09T07:26:27.911Z","msg":"Updating garden status conditions","controller":"garden-care","namespace":"","name":"garden-5tehj","reconcileID":"291dd244-14bc-43f8-99ff-c22dc0183bb8"}
2023-08-09T07:27:27.938195569Z stderr F {"level":"info","ts":"2023-08-09T07:27:27.938Z","msg":"Service DNS name lookup of virtual-garden-kube-apiserver failed, falling back to external kubeconfig","clientmap":"GardenClientMap","error":"lookup virtual-garden-kube-apiserver.garden.svc.cluster.local on 10.2.0.10:53: no such host"}
2023-08-09T07:27:27.938465309Z stderr F {"level":"info","ts":"2023-08-09T07:27:27.938Z","msg":"Updating garden status conditions","controller":"garden-care","namespace":"","name":"garden-5tehj","reconcileID":"b903e030-d368-4171-8b85-aa8378fd94a9"}
2023-08-09T07:27:54.125071993Z stderr F {"level":"error","ts":"2023-08-09T07:27:54.124Z","msg":"Error","controller":"garden","controllerGroup":"operator.gardener.cloud","controllerKind":"Garden","Garden":{"name":"garden-5tehj"},"namespace":"","name":"garden-5tehj","reconcileID":"eca67760-2181-43f7-ba7d-7e35976cbba0","flow":"Garden deletion","task":"Destroying gardener-resource-manager for virtual garden","error":"error while waiting for all resources to be deleted: retry failed with context deadline exceeded, last error: resource garden/shoot-core-gardener-resource-manager still exists:\nCould not clean all old resources: 2 errors occurred: [deletion of old resource \"admissionregistration.k8s.io/v1/MutatingWebhookConfiguration/default/virtual-garden-gardener-resource-manager-shoot\" is still pending: Get \"https://virtual-garden-kube-apiserver/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/virtual-garden-gardener-resource-manager-shoot\": dial tcp: lookup virtual-garden-kube-apiserver on 10.2.0.10:53: no such host, deletion of old resource \"rbac.authorization.k8s.io/v1/ClusterRoleBinding/default/gardener.cloud:target:resource-manager\" is still pending: Get \"https://virtual-garden-kube-apiserver/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/gardener.cloud:target:resource-manager\": dial tcp: lookup virtual-garden-kube-apiserver on 10.2.0.10:53: no such host]","stacktrace":"github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func1\n\tgithub.com/gardener/gardener/pkg/utils/flow/flow.go:217"}
2023-08-09T07:27:54.136711594Z stderr F {"level":"info","ts":"2023-08-09T07:27:54.136Z","msg":"Finished","controller":"garden","controllerGroup":"operator.gardener.cloud","controllerKind":"Garden","Garden":{"name":"garden-5tehj"},"namespace":"","name":"garden-5tehj","reconcileID":"eca67760-2181-43f7-ba7d-7e35976cbba0","flow":"Garden deletion"}
2023-08-09T07:27:54.145773935Z stderr F {"level":"error","ts":"2023-08-09T07:27:54.145Z","msg":"Reconciler error","controller":"garden","controllerGroup":"operator.gardener.cloud","controllerKind":"Garden","Garden":{"name":"garden-5tehj"},"namespace":"","name":"garden-5tehj","reconcileID":"eca67760-2181-43f7-ba7d-7e35976cbba0","error":"failed updating last operation to state 'Error' (due to 1 error occurred:\n\t* task \"Destroying gardener-resource-manager for virtual garden\" failed: error while waiting for all resources to be deleted: retry failed with context deadline exceeded, last error: resource garden/shoot-core-gardener-resource-manager still exists:\nCould not clean all old resources: 2 errors occurred: [deletion of old resource \"admissionregistration.k8s.io/v1/MutatingWebhookConfiguration/default/virtual-garden-gardener-resource-manager-shoot\" is still pending: Get \"https://virtual-garden-kube-apiserver/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/virtual-garden-gardener-resource-manager-shoot\": dial tcp: lookup virtual-garden-kube-apiserver on 10.2.0.10:53: no such host, deletion of old resource \"rbac.authorization.k8s.io/v1/ClusterRoleBinding/default/gardener.cloud:target:resource-manager\" is still pending: Get \"https://virtual-garden-kube-apiserver/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/gardener.cloud:target:resource-manager\": dial tcp: lookup virtual-garden-kube-apiserver on 10.2.0.10:53: no such host]\n\n): %!w(<nil>)","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
```

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area quality
/kind flake

**What this PR does / why we need it**:
When deleting a `garden` there is a race between the deletion of managed-resources deployed in the virtual-garden and the deletion of `virtual-garden-kube-apiserver`. When the later is deleted first, this results in the MRs not being cleaned up.
You can see it in the examples attached to issue #8367.

This PR introduces more sync points the deletion flow of `operator`.
1. Destroy managed resources deployed to the virtual-garden
2. Destroy `virtual-garden-resource-manager`
3. Destroy `virtual-garden-kube-apiserver`

**Which issue(s) this PR fixes**:
Fixes #8367

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
`operator` now deletes `ManagedResources` deployed to the virtual-garden before deleting `virtual-garden-kube-apiserver`.
```

### CODE REVIEW

File: pkg/operator/controller/garden/garden/reconciler_delete.go [hunk 1]
```diff
@@ -67,29 +67,36 @@ func (r *Reconciler) delete(
 		})
 		destroyVirtualGardenGardenerAccess = g.Add(flow.Task{
 			Name: "Destroying Gardener virtual garden access resources",
-			Fn:   c.virtualGardenGardenerAccess.Destroy,
-		})
-		destroyVirtualGardenGardenerResourceManager = g.Add(flow.Task{
-			Name:         "Destroying gardener-resource-manager for virtual garden",
-			Fn:           component.OpDestroyAndWait(c.virtualGardenGardenerResourceManager).Destroy,
-			Dependencies: flow.NewTaskIDs(destroyVirtualGardenGardenerAccess),
+			Fn:   component.OpDestroyAndWait(c.virtualGardenGardenerAccess).Destroy,
```
Comment (ScheererJ) [inline pkg/operator/controller/garden/garden/reconciler_delete.go:70]: Could you please enlighten me what this change does? As far as I can tell, `virtualGardenGardenerAccess` has no `Wait` or `WaitCleanup` functions.

**Review by ScheererJ — COMMENTED** [review]
Thanks for the change. Looks good overall. I just have one question for my understanding.

File: pkg/operator/controller/garden/garden/reconciler_delete.go (hunk 1 above)
Comment (oliver-goetz) [reply pkg/operator/controller/garden/garden/reconciler_delete.go:70]: Good point, I did not add these functions to `gardeneraccess` yet. Here they are 😄

**Review by ScheererJ — COMMENTED** [review]
/lgtm

File: pkg/component/gardeneraccess/access.go [hunk 2]
```diff
@@ -122,6 +123,26 @@ func (g *gardener) Destroy(ctx context.Context) error {
 	return managedresources.DeleteForShoot(ctx, g.client, g.namespace, ManagedResourceName)
 }
 
+var (
+	// TimeoutWaitForManagedResource is the timeout used while waiting for the ManagedResources to become healthy
+	// or deleted.
+	TimeoutWaitForManagedResource = 1 * time.Minute
```
Comment (acumino) [inline pkg/component/gardeneraccess/access.go]: Almost every where in our code base we have used time out of 2 minutes and in some special cases 5 minutes. Any specific reason to keep timeout 1 minute here?
```suggestion
	TimeoutWaitForManagedResource = 2 * time.Minute
```

File: pkg/component/gardeneraccess/access.go [hunk 3]
```diff
@@ -122,6 +123,26 @@ func (g *gardener) Destroy(ctx context.Context) error {
...
+)
```
Comment (acumino) [inline pkg/component/gardeneraccess/access.go]: Nit
```suggestion
// TimeoutWaitForManagedResource is the timeout used while waiting for the ManagedResources to become healthy
// or deleted.
var TimeoutWaitForManagedResource = 1 * time.Minute
```

**Review by acumino — CHANGES_REQUESTED** [review]

**Review by acumino — COMMENTED** [review]
Thanks
/lgtm
/approve
