### PR TITLE
Remove resource-manager's secret reconciler

### LINKED ISSUE #8190: Possibility to leak secret `extension-controlplane-shoot` and prevent shoot deletion
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
https://github.com/gardener/gardener/blob/445ba3d395704755bb2a0c5719d1a0ec47f1023d/pkg/resourcemanager/controller/secret/reconciler.go#L81-L86
On shoot deletion if a slowdown happens when removing finalizer of secret `extension-controlplane-shoot`
shoot might fail to get deleted. That's because shoot's GRM can get terminated before the removal of GRM's finalizer for secret `extension-controlplane-shoot`. Secret can remain with a remaining GRM finalizer that prevents it's deletion and therefore interrupts shoot deletion

From a gardenlet logs for the corresponding Shoot:
```
2023-06-20 14:23:30	{"log":{"controller":"shoot","flow":"Shoot cluster deletion","level":"info","msg":"Succeeded","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"11727ea7-7808-4f12-bbf4-d64ee28e9fa1","task":"Destroying shoot control plane","ts":"2023-06-20T14:23:30.759Z"}}

2023-06-20 14:23:32	{"log":{"controller":"shoot","flow":"Shoot cluster deletion","level":"info","msg":"Succeeded","name":"bar","namespace":"garden-foo","object":{"name":"bar","namespace":"garden-foo"},"operation":"delete","reconcileID":"11727ea7-7808-4f12-bbf4-d64ee28e9fa1","task":"Destroying gardener-resource-manager","ts":"2023-06-20T14:23:32.672Z"}}
```

We can see that GRM has around 2 seconds to remove `extension-controlplane-shoot` Secrets's finalizer before GRM gets deleted.

In the geneticactuator we have:
https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/extensions/pkg/controller/controlplane/genericactuator/actuator.go#L479-L493

It waits the ManagedResource to be deleted, but it doesn't wait the Secret to be deleted.

**What you expected to happen**:
Shoot to be deleted successfully

**How to reproduce it (as minimally and precisely as possible)**:
In the local setup we can reproduce the issue by putting `time.Sleep(10 * time.Second)` for this `extension-controlplane-shoot` Secret before the finalizer release:
https://github.com/gardener/gardener/blob/dff43d99d2128c99f6d09116145ee48aebfd97f4/pkg/resourcemanager/controller/secret/reconciler.go#L83-L85

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.73.1
- Kubernetes version (use `kubectl version`):

### PR DESCRIPTION
**Pull request by Kostov6**
**How to categorize this PR?**

/area quality
/kind cleanup

**What this PR does / why we need it**:
`gardenlet` has been removing on startup the `resources.gardener.cloud/gardener-resource-manager` finalizer from `Secret`s related to `ManagedResource`s since https://github.com/gardener/gardener/pull/8912 .
If one want to check if there are remaining secrets with the given finalizer the following command can be used
```
 k get secrets -A -o json | jq -r '.items[] | select(.metadata.finalizers[]? | contains("resources.gardener.cloud/gardener-resource-manager")) | "\(.metadata.namespace) \(.metadata.name)"'
```

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/8190

**Special notes for your reviewer**:

**Release note**:

```noteworthy operator
resource-manager's secret reconciler that removed `resources.gardener.cloud/gardener-resource-manager` finalizer has been removed.
```

### CODE REVIEW

File: pkg/resourcemanager/controller/add.go [hunk 1]
```diff
@@ -86,13 +85,6 @@ func AddToManager(ctx context.Context, mgr manager.Manager, sourceCluster, targe
 		}
 	}
 
-	if err := (&secret.Reconciler{
-		Config:      cfg.Controllers.Secret,
```
Comment (ialidzhikov) [inline pkg/resourcemanager/controller/add.go:90]: You could also drop https://github.com/gardener/gardener/blob/1e606831ba69b3da38a39b448643f12c905cc5a4/pkg/resourcemanager/apis/config/v1alpha1/types.go#L203-L208, https://github.com/gardener/gardener/blob/1e606831ba69b3da38a39b448643f12c905cc5a4/example/resource-manager/10-componentconfig.yaml#L69-L70, https://github.com/gardener/gardener/blob/1e606831ba69b3da38a39b448643f12c905cc5a4/charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml#L132-L135, https://github.com/gardener/gardener/blob/1e606831ba69b3da38a39b448643f12c905cc5a4/charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml#L132-L135

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

File: pkg/resourcemanager/controller/secret/add.go [hunk 2]
```diff
@@ -1,88 +0,0 @@
...
-		r.SourceClient = sourceCluster.GetClient()
-	}
-
-	return builder.
-		ControllerManagedBy(mgr).
-		Named(ControllerName).
-		For(&corev1.Secret{}, builder.WithPredicates(
-			// Only requeue secrets from create/update events with the controller's finalizer to not flood the controller
-			// with too many unnecessary requests for all secrets in cluster/namespace.
-			resourcemanagerpredicate.HasFinalizer(r.ClassFilter.FinalizerName()),
```
Comment (ialidzhikov) [inline pkg/resourcemanager/controller/secret/add.go:52]: The `HasFinalizer` func seems to be no longer used: https://github.com/gardener/gardener/blob/bf7bd5ba0914524ca5a04252b4d4f23cc892047d/pkg/resourcemanager/predicate/has_finalizer.go#L28-L49

You could remove it as well.

File: pkg/resourcemanager/controller/add.go (hunk 1 above)
Comment (ialidzhikov) [reply pkg/resourcemanager/controller/add.go:90]: You could also adapt secret controller references such as https://github.com/gardener/gardener/blob/f9050291893c1ff1b6ba46f497a7296d6cb5df82/docs/concepts/resource-manager.md#L27.

**Review by ialidzhikov — APPROVED** [review]
/lgtm
