### PR TITLE
Fix calculation of overlapping CIDR ranges.

### LINKED ISSUE #7110: NetworkPolicy `allow-to-private-networks` doesn't exclude pod network range.
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:
The NetworkPolicy `allow-to-private-networks` allows traffic to private networks, but should exclude traffic to the pod network.
In a seed cluster, I observed that the `except` clause for the pod network (10.64.0.0/12) is missing:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: Allows Egress from pods labeled with 'networking.gardener.cloud/to-private-networks=allowed'
      to the Private networks (RFC1918), Carrier-grade NAT (RFC6598) except for (1)
      CloudProvider's specific metadata service IP, (2) Seed networks, (3) Shoot networks
  creationTimestamp: "2022-11-29T15:07:09Z"
  generation: 1
  name: allow-to-private-networks
  namespace: shoot--dev--d046309-shoot-ha
  resourceVersion: "17699649"
  uid: 9debff3a-af2d-402e-83d7-a2bf298ca8a3
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
        except:
        - 10.180.0.0/16
    - ipBlock:
        cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
    - ipBlock:
        cidr: 100.64.0.0/10
        except:
        - 100.104.0.0/13
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-private-networks: allowed
  policyTypes:
  - Egress
```

**What you expected to happen**:
I expect, that an `except` for  the pod network range is added.

**How to reproduce it (as minimally and precisely as possible)**:
This will happen with every cluster, where the pod network range starts right at the beginning of a private IP range.

**Anything else we need to know?**:
The reason is a wrong calculation for overlapping CIRD ranges [here](https://github.com/gardener/gardener/blob/7c55e6cd5f5258998d9f3963b2ecc60f541955c8/pkg/operation/botanist/component/networkpolicies/peers.go#L102).

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by axel7born**
**How to categorize this PR?**

/area networking
/kind bug

**What this PR does / why we need it**:
Due to the wrong overlap test, NetworkPolicy `allow-private-networks` doesn't contain a `except` clauses for networks that are includes in the subnet but have the same start address. 

**Which issue(s) this PR fixes**:
Fixes #7110

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fixed a bug where service, pod or node CIDRs that are private network (RFC1918) or carrier-grade NAT (RFC6598) IPv4 blocks would not be added as except clause to `allow-to-private-networks` networkpolicy.
```

### CODE REVIEW

File: pkg/operation/botanist/component/networkpolicies/peers.go [hunk 1]
```diff
@@ -98,8 +98,10 @@ func excludeBlock(parentBlock *net.IPNet, cidrs ...string) ([]string, error) {
 		if err != nil {
 			return matchedCIDRs, err
 		}
+		parentBlockMaskLength, _ := parentBlock.Mask.Size()
+		ipNetMaskLength, _ := ipNet.Mask.Size()
 
-		if parentBlock.Contains(ip) && !ipNet.Contains(parentBlock.IP) {
+		if parentBlock.Contains(ip) && (parentBlockMaskLength < ipNetMaskLength) {
```
Comment (ScheererJ) [inline pkg/operation/botanist/component/networkpolicies/peers.go]:
```suggestion
		if parentBlock.Contains(ip) && parentBlockMaskLength < ipNetMaskLength {
```

Comment (ScheererJ) [inline pkg/operation/botanist/component/networkpolicies/peers.go]: With this change we will exclude all blocks if they are in the parent block AND smaller.
What about equal size blocks? Should they be excluded?
If the parent block is indeed smaller what should happen then?

Comment (axel7born) [reply pkg/operation/botanist/component/networkpolicies/peers.go]: Equal size blocks can't be excluded. This would result in an invalid NetworkPolicy.
If the parent block is smaller, the creation would also fail.
The current logic is, that we don't add the `except` clause in that case.
Actually, it would be correct not to allow the parent block in such a case. 
But I fear, that could break existing clusters with such configuration.

**Review by ScheererJ — CHANGES_REQUESTED** [review]
Could you please remove the unnecessary parentheses? Apart from that, the change looks fine.

**Review by ScheererJ — APPROVED** [review]
/lgtm
