### PR TITLE
Fix K8s Dashbord defaulting

### LINKED ISSUE #1845: Wrong defaulting for K8s Dashboard Authentication Method
**What happened**:
When trying to create a shoot cluster with a kubernetes version < 1.16 and disable basic auth on the api-server; gardener defaults the K8s Authentication method to basic auth.

Gardener wrongly defaults the K8s Dashboard authentication method.
`Shoot.core.gardener.cloud "shoot-xxx" is invalid: spec.addons.kubernetes-dashboard.authenticationMode: Invalid value: "basic": cannot use basic auth mode when basic auth is not enabled in kube-apiserver configuration`

**What you expected to happen**:
gardener defaults the k8s dashboard based on the apiserver authentication not on the k8s version.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a shoot with: `K8s Version < 1.16` `.spec.kubernetes. kubeAPIServer. enableBasicAuthentication: false` `spec.addons. kubernetesDashboard.enabled: true`

**Anything else we need to know?**:

**Environment**:

- Gardener version: 0.35.1

### PR DESCRIPTION
**Pull request by schrodit**
**What this PR does / why we need it**:
Fixed defaulting for k8s dashboard based on the kube-apiserver authentication method.

**Which issue(s) this PR fixes**:
Fixes #1845 

**Special notes for your reviewer**:

**Release note**:

```improvement user
Fixed a bug in the defaulting of the kubernetes dashboard authentication method to now default based on the api-server authentication method
```

### CODE REVIEW

File: pkg/apis/core/v1beta1/defaults.go [hunk 1]
```diff
@@ -120,7 +120,7 @@ func SetDefaults_Shoot(obj *Shoot) {
 	}
 	if obj.Spec.Addons.KubernetesDashboard.AuthenticationMode == nil {
 		var defaultAuthMode string
-		if k8sVersionLessThan116 {
+		if *obj.Spec.Kubernetes.KubeAPIServer.EnableBasicAuthentication {
```
Comment (rfranzke) [inline pkg/apis/core/v1beta1/defaults.go:123]: Please do the defaulting also for `core/v1alpha1` and `garden/v1beta1`.

**Review by rfranzke — CHANGES_REQUESTED** [review]

**Review by rfranzke — DISMISSED** [review]

**Review by rfranzke — APPROVED** [review]
