### PR TITLE
Adjust Quotas for increased resources post-Gardener update

### LINKED ISSUE #12805: Prevent failing `Shoot` reconciliations due to impossible `ResourceQuota`s
The PR https://github.com/gardener/gardener/pull/11916 lead to projects using `n` more `ConfigMaps` of their quota, with `n` being number of `Shoot`s.
This can lead to hitting `ResourceQuota` limits in `Project` namespaces, which in turn leads to failing `Shoot` reconciliations, as those `ConfigMap`s can not be created.

In `g/g@v1.130.0`, we have the following automatically created `ConfigMaps` / `Secrets`:
| Phase                                  | `Secret`s |  `ConfigMap`s |
| -------------------------  | --------- | -------------- |
| Creation                               | 3         | 2              |
| After `CredentialRotation` preparation | 4         | 2              |
| After `CredentialRotation` completion | 4         | 2              |

<details>
<summary>

#### Reconciler approach - does not solve our problem ([ref](https://github.com/gardener/gardener/pull/13355#issuecomment-3497873457))
</summary>

As a solution, we can implement a controller to circumvent these scenarios.
It should:

**"Statically" increase `ResourceQuota`s that depict a 'soft' limit for creating `Shoot`s**

For `ResourceQuota`s that **have** a `Shoot` limit, but have limits for other resources that do not match the amount of `Shoot`s, this controller should automatically increase these limits. E.g.:

Initial `ResourceQuota`:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gardener
  namespace: garden-foo
spec:
  hard:
    count/shoots.core.gardener.cloud: "10"
    count/configmaps: "5"
    count/secrets: "5"
```
should be modified to:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gardener
  namespace: garden-foo
spec:
  hard:
    count/shoots.core.gardener.cloud: "10"
    count/configmaps: "20" # Shoot limit * max. Gardener created ConfigMaps = 10 * 2
    count/secrets: "40" # Shoot limit * max. Gardener created Secrets = 10 * 4
```

**"Dynamically"  increase `ResourceQuota`s that do not have `Shoot` limits**

For `ResourceQuota`s that **do not have** a `Shoot` limit, Gardener should still be able to create resources during `Shoot` reconciliation. E.g.:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gardener
  namespace: garden-foo
spec:
  hard:
    count/configmaps: "5"
    count/secrets: "5"
```
and `10` `Shoot`s present in the namespace, it should be modified to:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gardener
  namespace: garden-foo
spec:
  hard:
    count/shoots.core.gardener.cloud: "10"
    count/configmaps: "20" # Current Shoots * max. Gardener created ConfigMaps = 10 * 2
    count/secrets: "40" # Current Shoots * max. Gardener created Secrets = 10 * 4
```
---

In case there is a change in how many `Secret`s / `ConfigMap`s are created through Gardener, a developer has to configure this controller, so that it's calculation matches the actual amount.

</details>
<details>
<summary>

#### Bootstrapper approach - does not scale very nice ([ref](https://github.com/gardener/gardener/pull/13658#pullrequestreview-3660754065))
</summary>

- Annotating all ResourceQuotas in project namespaces with the amount of resources gardener needs to create per shoot
- A bootstrapping component is added to the gardener-controller-manager that runs once at start
- When a new gardener version is rolled out that increases these values (difference between value known in code vs. annotation on resourcequota), it increases the quota once and then updates the annotation once done
- We specify this on every ResourceQuota, instead of just one central place, because the bootstrapper could die in the process of updating all quotas

</details>

The alternative solution, which we will also implement moving forward is:
- Implement the logic of the Bootstrapper approach, but as a controller / reconciler

### PR DESCRIPTION
**Pull request by tobschli**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:

This PR adds a controller to the `gardener-controller-manager` that adds annotations to all `ResourceQuota`s in project namespaces, containing information about how many resources Gardener creates per shoot in them.

When a Gardener update contains a change, e.g. now creating `5` instead of `4` `Secret`s in the project namespace per shoot, the reconciler will increase all applicable `ResourceQuota`s by `(new amount - old amount) * max. shoots in Project`.
`max. shoots in Project` is either determined by the `ResourceQuota` itself, if it exists, or by the amount of shoots already in the project.

The following cases exist for each ResourceQuota:

| Annotations differ from expected | bigger / smaller value | expected behavior |
| ---- | --- | --- |
| no | N/A | do nothing |
| yes | bigger | bump by `diff * max. shootcount` |
| yes | smaller | do nothing (no decrease) |

When the Annotations are not present:

| applicable Quota keys exist | is enough | expected behavior |
| --- | --- | --- |
| yes | yes | just set the annotation |
| yes | no | bump quota to fit shoots; set the annotation |
| no | N/A | just set the annotation |

**Which issue(s) this PR fixes**:
Fixes #12805 

**Special notes for your reviewer**:

**Release note**:

```feature operator
The `gardener-controller-manager` now increases all `ResourceQuota`s in project namespaces when a Gardener update leads to Gardener creating more resources in them. This was introduced to prevent failing Shoot reconciliations when `ResourceQuota`s of projects are near their limit.
```

### CODE REVIEW

**Comment by tobschli** [comment]
/invite @marc1404 @rfranzke @timuthy because of your review on the other PR(s) 😅

File: pkg/controllermanager/controller/project/resourcequota/add.go [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+
+// ObjectInProjectNamespace returns a predicate that filters objects that are in Project namespaces.
+func (r *Reconciler) ObjectInProjectNamespace(ctx context.Context, log logr.Logger) predicate.Predicate {
+	return predicate.NewPredicateFuncs(func(object client.Object) bool {
+		namespace := object.GetNamespace()
+		project, err := gardenerutils.ProjectForNamespaceFromReader(ctx, r.Client, namespace)
+		if err != nil {
+			log.Error(err, "Unable to find gardener project", "namespace", namespace)
+		}
+		return err == nil && project != nil
```
Comment (marc1404) [inline pkg/controllermanager/controller/project/resourcequota/add.go]: nit: I understand why you combined the return-case, I'd find it slightly easier to read when clearly distinguishing between the error case and the happy-path :) 
```suggestion
		if err != nil {
			log.Error(err, "Unable to find gardener project", "namespace", namespace)
			return false
		}
		return project != nil
```

**Review by marc1404 — COMMENTED** [review]
Thank you for converting the implementation to a controller and adding documentation for the new reconciler to the controller manager documentation! 🙏 

/lgtm

File: pkg/controllermanager/controller/project/resourcequota/add.go (hunk 1 above)
Comment (tobschli) [reply pkg/controllermanager/controller/project/resourcequota/add.go]: Sounds good, will do 😊

**Review by marc1404 — COMMENTED** [review]
/lgtm

File: docs/concepts/controller-manager.md [hunk 2]
```diff
@@ -291,6 +291,16 @@ Since the other two reconcilers are unable to actively monitor the relevant obje
 
 The `Project Activity Reconciler` is implemented to take care of such cases. An event handler will notify the reconciler for any activity and then it will update the `status.lastActivityTimestamp`. This update will also trigger the `Stale Project Reconciler`.
 
+#### [`ResourceQuota` Reconciler](../../pkg/controllermanager/controller/project/resourcequota)
+
+The `ResourceQuota` reconciler only reconciles `ResourceQuota`s in `Project` namespaces and ensures that the specified quotas do not interfere with Gardener's operations.
+
+In the lifecycle of a `Shoot`, Gardener also creates some resources (`Secret`s and `ConfigMap`s) e.g. for certain CAs of the `Shoot`s in the `Project` namespace. This means that the `ResourceQuota` must allow for the creation of these resources, otherwise the `Shoot` reconciliation would fail due to quota violations.
+
+The reconciler ensures this by adding annotations to the `ResourceQuota`s as to how many resources (`Secret`s, `ConfigMap`s, etc.) Gardener itself will create in the `Project` namespace.
```
Comment (rfranzke) [inline docs/concepts/controller-manager.md]:
```suggestion
The reconciler ensures this by adding annotations to the `ResourceQuota`s specifying how many resources (`Secret`s, `ConfigMap`s, etc.) Gardener itself will create in the `Project` namespace.
```

File: pkg/controllermanager/controller/project/resourcequota/add.go [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+// ControllerName is the name of this controller.
+const ControllerName = "project-resourcequota"
+
+// AddToManager adds a controller with the given Options to the given manager.
+func (r *Reconciler) AddToManager(ctx context.Context, mgr manager.Manager) error {
+	if r.Client == nil {
+		r.Client = mgr.GetClient()
+	}
+
+	log := mgr.GetLogger().WithValues("controller", ControllerName)
```
Comment (rfranzke) [inline pkg/controllermanager/controller/project/resourcequota/add.go]: Nit: You could inline this (as usual)

File: pkg/controllermanager/controller/project/resourcequota/add.go [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+		Complete(r)
+}
+
+// ObjectInProjectNamespace returns a predicate that filters objects that are in Project namespaces.
+func (r *Reconciler) ObjectInProjectNamespace(ctx context.Context, log logr.Logger) predicate.Predicate {
+	return predicate.NewPredicateFuncs(func(object client.Object) bool {
+		namespace := object.GetNamespace()
+		project, err := gardenerutils.ProjectForNamespaceFromReader(ctx, r.Client, namespace)
+		if err != nil {
+			log.Error(err, "Unable to find gardener project", "namespace", namespace)
```
Comment (rfranzke) [inline pkg/controllermanager/controller/project/resourcequota/add.go]:
```suggestion
			log.Error(err, "Unable to find project for namespace", "namespaceName", namespace)
```

File: test/integration/controllermanager/project/resourcequota/resourcequota_test.go [hunk 5]
```diff
@@ -0,0 +1,446 @@
...
+
+				By("Wait for Project to be gone")
+				Eventually(func() error {
+					return testClient.Get(ctx, client.ObjectKeyFromObject(project), project)
+				}).Should(BeNotFoundError())
+			})
+		})
+
+		Context("Annotations do not exist", func() {
+			Context("Quota is enough", func() {
```
Comment (rfranzke) [inline test/integration/controllermanager/project/resourcequota/resourcequota_test.go]: Nit: Use `When`?

Check other occurrences

File: pkg/controllermanager/controller/project/resourcequota/reconciler.go [hunk 6]
```diff
@@ -0,0 +1,173 @@
...
+		return reconcile.Result{}, fmt.Errorf("failed updating resource quota %q in namespace %q: %w", resourceQuota.Name, resourceQuota.Namespace, err)
+	}
+
+	return reconcile.Result{}, nil
+}
+
+func (r *Reconciler) handleMissingAnnotation(ctx context.Context, log logr.Logger, resourceQuota *corev1.ResourceQuota, usageAnnotation string, usageSpecKey corev1.ResourceName, expectedCount int) error {
+	maximumShootsInProject, err := r.getMaximumShootsInProject(ctx, *resourceQuota)
+	if err != nil {
+		return err
```
Comment (rfranzke) [inline pkg/controllermanager/controller/project/resourcequota/reconciler.go]: Nit: Use `fmt.Errorf`?

Check also other occurrences

File: pkg/controllermanager/controller/project/resourcequota/reconciler.go [hunk 7]
```diff
@@ -0,0 +1,173 @@
...
+	"sigs.k8s.io/controller-runtime/pkg/reconcile"
+
+	gardencorev1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
+	controllermanagerconfigv1alpha1 "github.com/gardener/gardener/pkg/controllermanager/apis/config/v1alpha1"
+	gardenerutils "github.com/gardener/gardener/pkg/utils/gardener"
+)
+
+const (
+	annotationKeyConfigMapsPerShoot = "quota.gardener.cloud/configmaps-per-shoot"
+	annotationKeySecretsPerShoot    = "quota.gardener.cloud/secrets-per-shoot"
```
Comment (rfranzke) [inline pkg/controllermanager/controller/project/resourcequota/reconciler.go]: I only see those consts being used once, inline them?

File: pkg/controllermanager/controller/project/resourcequota/reconciler.go [hunk 8]
```diff
@@ -0,0 +1,173 @@
...
+
+	shootCountResource = "count/shoots.core.gardener.cloud"
```
Comment (rfranzke) [inline pkg/controllermanager/controller/project/resourcequota/reconciler.go]: Same here

File: pkg/controllermanager/controller/project/resourcequota/reconciler.go [hunk 9]
```diff
@@ -0,0 +1,173 @@
...
+
+func (r *Reconciler) handleMissingAnnotation(ctx context.Context, log logr.Logger, resourceQuota *corev1.ResourceQuota, usageAnnotation string, usageSpecKey corev1.ResourceName, expectedCount int) error {
+	maximumShootsInProject, err := r.getMaximumShootsInProject(ctx, *resourceQuota)
+	if err != nil {
+		return err
+	}
+
+	currentQuotaResource, ok := resourceQuota.Spec.Hard[usageSpecKey]
+	if !ok {
+		metav1.SetMetaDataAnnotation(&resourceQuota.ObjectMeta, usageAnnotation, strconv.Itoa(expectedCount))
```
Comment (rfranzke) [inline pkg/controllermanager/controller/project/resourcequota/reconciler.go]: Why do we add the annotation when (e.g. configmaps) are not part of the `ResourceQuota`?

File: pkg/controllermanager/controller/project/resourcequota/reconciler.go [hunk 10]
```diff
@@ -0,0 +1,173 @@
...
+				return reconcile.Result{}, fmt.Errorf("error aligning resource quota %q in namespace %q: %w", resourceQuota.Name, resourceQuota.Namespace, err)
+			}
+		}
+	}
+
+	if err := r.Client.Patch(ctx, resourceQuota, patch); err != nil {
+		return reconcile.Result{}, fmt.Errorf("failed updating resource quota %q in namespace %q: %w", resourceQuota.Name, resourceQuota.Namespace, err)
+	}
+
+	return reconcile.Result{}, nil
```
Comment (rfranzke) [inline pkg/controllermanager/controller/project/resourcequota/reconciler.go]:
```suggestion
	return reconcile.Result{}, r.Client.Patch(ctx, resourceQuota, patch)
```

File: pkg/controllermanager/controller/project/resourcequota/reconciler.go (hunk 9 above)
Comment (tobschli) [reply pkg/controllermanager/controller/project/resourcequota/reconciler.go]: Uh!
This is a relic from the bootstrapper approach.
I added this there because the `ResourceQuota` might have added configmaps after the bootstrapper ran.
When Gardener then rolls out an update where the usage of configmaps increases, it _would not have been_ (😅) bumped, potentially leading to the same error as before.

With the reconciler approach this should not matter anymore, thank you for pointing it out! 🤗

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
