### PR TITLE
Make yaml serialization in `controllerinstallation.mutateObjects` deterministic

### LINKED ISSUE #10092: `controllerinstallation.mutateObjects` uses unstable yaml marshalling in some cases
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
https://github.com/gardener/gardener/issues/10081

The unstable marshalling seems to stem from here
https://github.com/gardener/gardener/blob/efba3eafc3d0119d55903dcf8cf967707395a940/pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go#L522-L524

**What you expected to happen**:
controllerinstallation not to create secrets that differ on permutation order of their annotations

**How to reproduce it (as minimally and precisely as possible)**:
The following unit test should not fail
```
$ cat pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler_export_test.go 
package controllerinstallation

var MutateObjects = mutateObjects
```
and
```
// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package controllerinstallation_test

import (
	"github.com/gardener/gardener/pkg/gardenlet/controller/controllerinstallation/controllerinstallation"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

var _ = FDescribe("MutateObjects", func() {
	It("passes on some cases", func() {
		for range 20 {
			content := `
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    reference.resources.gardener.cloud/configmap-7324b8b3: gardener-extension-provider-local-imagevector-overwrite
    reference.resources.gardener.cloud/secret-795f7ca6: garden-access-extension
    reference.resources.gardener.cloud/secret-d5f5a834: generic-garden-kubeconfig-81fb3a88
  creationTimestamp: null
  name: foo
  namespace: bar

---
`
			secret := map[string][]byte{
				"foo": []byte(content),
			}
			err := controllerinstallation.MutateObjects(secret, func(obj *unstructured.Unstructured) error {
				return nil
			})
			Expect(err).NotTo(HaveOccurred())
			Expect(string(secret["foo"])).To(Equal(content))
		}
	})

	It("fails on others", func() {
		for range 20 {
			content := `
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    reference.resources.gardener.cloud/configmap-32c4dfab: oidc-apps-controller-imagevector-overwrite
    reference.resources.gardener.cloud/secret-795f7ca6: garden-access-extension
    reference.resources.gardener.cloud/secret-83438e60: generic-garden-kubeconfig-a1b02908
    reference.resources.gardener.cloud/secret-8d3ae69b: oidc-apps-controller
  creationTimestamp: null
  name: foo
  namespace: bar

---
`
			secret := map[string][]byte{
				"foo": []byte(content),
			}
			err := controllerinstallation.MutateObjects(secret, func(obj *unstructured.Unstructured) error {
				return nil
			})
			Expect(err).NotTo(HaveOccurred())
			Expect(string(secret["foo"])).To(Equal(content))
		}
	})

})

```

**Anything else we need to know?**:
Related to https://github.com/gardener/gardener/pull/8312 and https://github.com/go-yaml/yaml/issues/194

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by Kostov6**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
This PR utilises `forkedyaml` for deterministic yaml parsing in `controllerinstallation.mutateObjects`

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/10092

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
`controllerinstallation` controller should not recreate MR secrets that differ just in the order of annotations.
```

### CODE REVIEW

File: pkg/gardenlet/controller/controllerinstallation/controllerinstallation/yaml_consistency_test.go [hunk 1]
```diff
@@ -0,0 +1,59 @@
+// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
```
Comment (ialidzhikov) [inline pkg/gardenlet/controller/controllerinstallation/controllerinstallation/yaml_consistency_test.go]: You could rename to `reconciler_test.go` to make it possible to add other unit tests for other funcs from the `reconciler.go`.

File: pkg/gardenlet/controller/controllerinstallation/controllerinstallation/yaml_consistency_test.go [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+import (
+	. "github.com/onsi/ginkgo/v2"
+	. "github.com/onsi/gomega"
+	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
+
+	"github.com/gardener/gardener/pkg/gardenlet/controller/controllerinstallation/controllerinstallation"
+)
+
+var _ = Describe("Ensuring MutateObjects makes deterministic yaml serialization ", func() {
```
Comment (ialidzhikov) [inline pkg/gardenlet/controller/controllerinstallation/controllerinstallation/yaml_consistency_test.go]:
```suggestion
var _ = Describe("Reconciler", func() {
```

File: pkg/gardenlet/controller/controllerinstallation/controllerinstallation/yaml_consistency_test.go [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+	It("serializes yaml in a deterministic way", func() {
```
Comment (ialidzhikov) [inline pkg/gardenlet/controller/controllerinstallation/controllerinstallation/yaml_consistency_test.go]:
```suggestion
	Describe("#mutateObjects", func() {
		It("serializes yaml with stable key ordering, func() {
```

File: pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go [hunk 4]
```diff
@@ -496,7 +496,7 @@ func injectGardenAccessSecrets(secretData map[string][]byte, namespace, genericG
 }
 
 // mutateObject iterates over the given rendered secret data and calls the given mutator for each of them. It marshals
-// the objects back after mutation and updates the secret data.
+// the objects back in a deterministic way after mutation and updates the secret data.
```
Comment (ialidzhikov) [inline pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go]:
```suggestion
// the objects back (with stable key ordering) after mutation and updates the secret data.
```

File: pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go [hunk 5]
```diff
@@ -519,9 +519,9 @@ func mutateObjects(secretData map[string][]byte, mutate func(obj *unstructured.U
 				return err
 			}
 
-			// serialize unstructured back to secret data
+			// serialize unstructured back to secret data in a deterministic way
```
Comment (ialidzhikov) [inline pkg/gardenlet/controller/controllerinstallation/controllerinstallation/reconciler.go]:
```suggestion
			// serialize unstructured back to secret data (with stable key ordering)
```

**Review by ialidzhikov — COMMENTED** [review]
Very nice catch!

**Review by ialidzhikov — APPROVED** [review]
/lgtm
