### PR TITLE
Fix race conditions occurring when removing finalizers from resources watched by multiple controllers

### LINKED ISSUE #13036: Race condition between secret and credentials binding controllers
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
A `SecretBinding` and a `CredentialsBinding` both reference the same `Secret`. All of the resources are deleted. The `SecretBinding`and the `CredentialsBinding` are removed from the cluster, but the `Secret` remains as the "gardener.cloud/gardener" finalizer is not removed.

This is observed probably due to a race condition between https://github.com/gardener/gardener/blob/8de2f6eb764d2ec30be389764e2b62cbad52b872/pkg/controllermanager/controller/credentialsbinding/reconciler.go#L178-L183 and https://github.com/gardener/gardener/blob/485c25124ea536e4610c627109017dd34d434921/pkg/controllermanager/controller/secretbinding/reconciler.go#L94-L99. Both controllers fail to remove the finalizer because other binding is referencing the credential, leaving the credential orphaned.

I propose the following two actions:
- We change the controllers to use their own unique finalizer. This would remove this race condition as each controller will act on their own finalizer.
- Optional: There is another potential race https://github.com/gardener/gardener/blob/29c4dba9f9e217539de34d805068a8c0e9192882/pkg/controllermanager/controller/credentialsbinding/reconciler.go#L146 when two of the same kind reference the same credentials and are deleted in the same time. Then two reconciliations fail to release the credential leaving it orphaned. In order to mitigate this we can implement a garbage collection logic removing finalizers from credentials that are no longer referenced. This logic should handle backup credentials as well.

**What you expected to happen**:
The `Secret` to be removed from the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
Various controllers now use their own unique finalizers to prevent race conditions when removing them from a resource in deletion.

/invite @vpnachev 

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/13036

**Special notes for your reviewer**:

**Release note**:

```bugfix user
A bug causing finalizers to not be removed from `Secret`s when such are deleted and referenced by both a `CredentialsBinding` and a `SecretBinding` is fixed.
```

### CODE REVIEW

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go [hunk 1]
```diff
@@ -131,6 +153,28 @@ func (r *Reconciler) delete(ctx context.Context, credentialsBinding *securityv1a
 		return nil
 	}
 
+	kind := credentialsBinding.CredentialsRef.Kind
+	credential, errCredentials := kubernetesutils.GetCredentialsByObjectReference(ctx, r.Client, credentialsBinding.CredentialsRef)
+	if errCredentials != nil && !apierrors.IsNotFound(errCredentials) {
```
Comment (vpnachev) [inline pkg/controllermanager/controller/credentialsbinding/reconciler.go:156]: Shouldn't you handle the `NotFound` error and return nil?

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go [hunk 2]
```diff
@@ -131,6 +153,28 @@ func (r *Reconciler) delete(ctx context.Context, credentialsBinding *securityv1a
...
+		return errCredentials
+	} else if errCredentials == nil {
+		// TODO(dimityrmirchev): remove this handling in a future release, the finalizer should be added by the reconcile function
+		// ensure the new finalizer is present on the referenced secret/workload identity before removing the old finalizer
+		if !controllerutil.ContainsFinalizer(credential, finalizerName) {
+			log.Info("Adding finalizer", kind, client.ObjectKeyFromObject(credential)) //nolint:logcheck
+			if err := controllerutils.AddFinalizers(ctx, r.Client, credential, finalizerName); err != nil {
```
Comment (vpnachev) [inline pkg/controllermanager/controller/credentialsbinding/reconciler.go:163]: If the credential already has a deletion timestamp, it is not allowed to add new finalizer.

```bash
$ k create secret generic finalizer-removal 
secret/finalizer-removal created
$ k patch secrets finalizer-removal -p '{"metadata": {"finalizers": ["gardener.cloud/credentialsbinding"]}}'
secret/finalizer-removal patched
$ k delete secrets finalizer-removal --wait=false
secret "finalizer-removal" deleted from default namespace
$ k patch secrets finalizer-removal  --type='json' -p='[{"op": "add", "path": "/metadata/finalizers/-", "value":"gardener.cloud/secretbinding"}]'
The Secret "finalizer-removal" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{"gardener.cloud/secretbinding"}
```

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go [hunk 3]
```diff
@@ -78,25 +82,43 @@ func (r *Reconciler) reconcile(ctx context.Context, credentialsBinding *security
...
 		log.Info("Adding finalizer", kind, client.ObjectKeyFromObject(credential)) //nolint:logcheck
-		if err := controllerutils.AddFinalizers(ctx, r.Client, credential, gardencorev1beta1.ExternalGardenerName); err != nil {
+		if err := controllerutils.AddFinalizers(ctx, r.Client, credential, finalizerName); err != nil {
 			return fmt.Errorf("could not add finalizer to %s: %w", kind, err)
 		}
 	}
 
+	// TODO(dimityrmirchev): Remove the ExternalGardenerName finalizer handling in a future release
+	if controllerutil.ContainsFinalizer(credential, gardencorev1beta1.ExternalGardenerName) {
+		log.Info("Removing finalizer", kind, client.ObjectKeyFromObject(credential)) //nolint:logcheck
```
Comment (vpnachev) [inline pkg/controllermanager/controller/credentialsbinding/reconciler.go]: Now when the controller handles two finalizers, it would be nice to log the finalizer name.

```suggestion
		log.Info("Removing finalizer", "finalizer", gardencorev1beta1.ExternalGardenerName, kind, client.ObjectKeyFromObject(credential)) //nolint:logcheck
```

File: pkg/gardenlet/controller/backupbucket/reconciler.go [hunk 4]
```diff
@@ -330,9 +337,9 @@ func (r *Reconciler) deleteBackupBucket(
 
 	log.Info("Successfully deleted")
 
-	if controllerutil.ContainsFinalizer(backupCredentials, gardencorev1beta1.ExternalGardenerName) {
+	if controllerutil.ContainsFinalizer(backupCredentials, gardencorev1beta1.ExternalGardenerName) || controllerutil.ContainsFinalizer(backupCredentials, finalizerName) {
```
Comment (vpnachev) [inline pkg/gardenlet/controller/backupbucket/reconciler.go:341]: Add todo statement to clean-up usage of the old finalizer

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go (hunk 2 above)
Comment (dimityrmirchev) [reply pkg/controllermanager/controller/credentialsbinding/reconciler.go:163]: Oh, that I missed. Thank you for spotting!

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go (hunk 1 above)
Comment (dimityrmirchev) [reply pkg/controllermanager/controller/credentialsbinding/reconciler.go:156]: If there is a not found error we want to continue with the function execution

Comment (vpnachev) [reply pkg/controllermanager/controller/credentialsbinding/reconciler.go:156]: Ok, on a deeper look usage of `credentials` seems to be protected by the condition `errCredentials == nil` which is fine.

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go [hunk 5]
```diff
@@ -78,25 +82,43 @@ func (r *Reconciler) reconcile(ctx context.Context, credentialsBinding *security
...
 		patch := client.MergeFrom(credential.DeepCopyObject().(client.Object))
-		if !hasProviderKeyLabel {
+		if secretNeedsLabel {
 			credential.SetLabels(utils.MergeStringMaps(credential.GetLabels(), map[string]string{
 				providerTypeLabelKey: "true",
 			}))
+		} else if workloadIdentityNeedsLabelRemoval {
+			// TODO(dimityrmirchev): remove this handling in a future release
+			// workload identities do not need the provider shoot label
+			// they rely on the provider.extensions.gardener.cloud/<provider> label set by the extensionlabels admission plugin
```
Comment (timuthy) [inline pkg/controllermanager/controller/credentialsbinding/reconciler.go:114]: Is the label also not needed by any extension admission?

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go [hunk 6]
```diff
@@ -29,6 +29,10 @@ import (
 	kubernetesutils "github.com/gardener/gardener/pkg/utils/kubernetes"
 )
 
+const (
+	finalizerName = "gardener.cloud/credentialsbinding"
+)
```
Comment (timuthy) [inline pkg/controllermanager/controller/credentialsbinding/reconciler.go]:
```suggestion
const finalizerName = "gardener.cloud/credentialsbinding"
```

Nit

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go [hunk 7]
```diff
@@ -131,6 +153,28 @@ func (r *Reconciler) delete(ctx context.Context, credentialsBinding *securityv1a
 		return nil
 	}
 
+	kind := credentialsBinding.CredentialsRef.Kind
+	credential, errCredentials := kubernetesutils.GetCredentialsByObjectReference(ctx, r.Client, credentialsBinding.CredentialsRef)
+	if errCredentials != nil && !apierrors.IsNotFound(errCredentials) {
+		return errCredentials
+	} else if errCredentials == nil {
```
Comment (timuthy) [inline pkg/controllermanager/controller/credentialsbinding/reconciler.go:158]:
```suggestion
	} else {
```

Nit: Else should be sufficient in this case?!

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go [hunk 8]
```diff
@@ -131,6 +153,28 @@ func (r *Reconciler) delete(ctx context.Context, credentialsBinding *securityv1a
...
+		// TODO(dimityrmirchev): remove this handling in a future release, the finalizer should be added by the reconcile function
+		// ensure the new finalizer is present on the referenced secret/workload identity before removing the old finalizer
+		if !controllerutil.ContainsFinalizer(credential, finalizerName) && credential.GetDeletionTimestamp() == nil {
+			log.Info("Adding finalizer", "finalizer", finalizerName, kind, client.ObjectKeyFromObject(credential)) //nolint:logcheck
```
Comment (timuthy) [inline pkg/controllermanager/controller/credentialsbinding/reconciler.go:162]: What's wrong with the lint check in this line?

File: pkg/controllermanager/controller/secretbinding/reconciler.go [hunk 9]
```diff
@@ -26,6 +26,10 @@ import (
 	"github.com/gardener/gardener/pkg/controllerutils"
 )
 
+const (
+	finalizerName = "gardener.cloud/secretbinding"
+)
```
Comment (timuthy) [inline pkg/controllermanager/controller/secretbinding/reconciler.go]:
```suggestion
const finalizerName = "gardener.cloud/secretbinding"
```

Nit

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go (hunk 5 above)
Comment (dimityrmirchev) [reply pkg/controllermanager/controller/credentialsbinding/reconciler.go:114]: I am not sure that I get the question. The label is used by the extensions https://github.com/gardener/gardener-extension-provider-gcp/blob/d4d3d43e7b3e6590e5f21c6f3d05ae0322ce3d83/pkg/admission/validator/webhook.go#L87

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go (hunk 7 above)
Comment (dimityrmirchev) [reply pkg/controllermanager/controller/credentialsbinding/reconciler.go:158]: What if it is a not found error?

File: pkg/controllermanager/controller/credentialsbinding/reconciler.go (hunk 8 above)
Comment (dimityrmirchev) [reply pkg/controllermanager/controller/credentialsbinding/reconciler.go:162]: The linter complains with the following
```
structured logging key should be a constant string expression (logcheck)
```

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve

**Review by ialidzhikov — COMMENTED** [review]
/hold

Could you add a release note?

**Review by ialidzhikov — COMMENTED** [review]
> Adressing https://github.com/gardener/gardener/issues/13036

Is this PR supposed to close https://github.com/gardener/gardener/issues/13036? `Adressing` is not a keyword which will close the referenced PR. I would suggest to use `Fixes #` if the PR is supposed to close the issue or `Part of #` if the PR partially fixes https://github.com/gardener/gardener/issues/13036.

**Comment by dimityrmirchev** [comment]
> /hold
> 
> Could you add a release note?

I forgot that, thanks! The release note is added.

**Comment by dimityrmirchev** [comment]
> > Adressing #13036
> 
> Is this PR supposed to close #13036? `Adressing` is not a keyword which will close the referenced PR. I would suggest to use `Fixes #` if the PR is supposed to close the issue or `Part of #` if the PR partially fixes #13036.

I changed to Fixes as I do not plan to implement any GC logic for now.

**Comment by ialidzhikov** [comment]
Thanks! I put the the PR on hold to prevent cherry-picks from being created with a release note. ;) 

/hold cancel

**Comment by ialidzhikov** [comment]
@dimityrmirchev , could you elaborate why cherry-picks are initiated for v1.128 and v1.129 only? Aren't v1.127 and v1.126 affected as well?

**Comment by dimityrmirchev** [comment]
> @dimityrmirchev , could you elaborate why cherry-picks are initiated for v1.128 and v1.129 only? Aren't v1.127 and v1.126 affected as well?

I was not sure how many past releases should include the fix. Now I read https://github.com/gardener/gardener/blob/master/docs/development/process.md which states 
```
The release responsible is the main contact person for coordinating new feature PRs for the next minor versions or cherry-pick PRs for the last three minor versions.
```
which would mean v1.127, v1.128 and v1.129 if I understand correctly.

I do not mind cherry picking it also to v1.126

**Comment by ialidzhikov** [comment]
v1.129.0 is not yet released. Hence, the versions we support at the moment are v1.128, v1.127, v1.126.
