### PR TITLE
Fix SSH-keypair rotation

### LINKED ISSUE #9966: SSH Key Pair Rotation for Worker Nodes Fails to Update `authorized_keys`
**How to categorize this issue?**

/area security
/kind bug

**What happened**:
When triggering the SSH Key Pair rotation for Worker Nodes once, the file `/home/gardener/.ssh/authorized_keys` on the node only contains the old SSH key (which can now be found in Secret `<shootname>.ssh-keypair.old`). The new SSH key in `<shootname>.ssh-keypair` is not added to the `authorized_keys` list. When rotating again, you are not able to access the node anymore via SSH (as the initial SSH key is still in the file but not anymore accessible via the `.ssh-keypair` secrets).

**What you expected to happen**:
The new SSH key should be added to the `authorized_keys` file on the node during the first rotation, ensuring continued SSH access.

**How to reproduce it (as minimally and precisely as possible)**:
1. Trigger SSH Key Pair rotation for Worker Nodes.
2. Check the `/home/gardener/.ssh/authorized_keys` file on the node.
3. Observe that only the old SSH key is present.
4. Rotate the SSH Key Pair again.
5. Attempt to access the node via SSH and observe the failure.

**Anything else we need to know?**:
N/A

**Environment**:
- Gardener version: v1.96.3
- Kubernetes version (use `kubectl version`): 1.29.3
- Cloud provider or hardware configuration: `aws`
- Others: N/A

### PR DESCRIPTION
**Pull request by tobschli**
**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:

Currently, when only the SSH keypairs of a shoot are rotated, the correct keys are written to `/var/lib/gardener-user-ssh.key`, but the `gardener-user.service` systemd unit that copies the keys to `/home/gardener/.ssh/authorized_keys` is not executed because the systemd unit itself has not changed.
Only when the nodes are rolled will the correct keys be written to the `authorized_keys` file.

This PR adds a path unit that watches the `/var/lib/gardener-user-ssh.key` file for changes and runs the `gardener-user.service` unit, setting the correct keys, without the nodes needing to be rolled.

**Which issue(s) this PR fixes**:
Fixes #9966

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Fixed a bug where SSH key rotations for `Shoot`s did not properly update the authorized keys on the worker nodes (hence, the new key was unusable until a node restart or rollout).
```

### CODE REVIEW

File: test/e2e/gardener/shoot/create_rotate_delete.go [hunk 1]
```diff
@@ -105,62 +165,13 @@ var _ = Describe("Shoot Tests", Label("Shoot", "default"), func() {
...
-			}).Should(Succeed())
-
-			Expect(f.WaitForShootToBeReconciled(ctx, f.Shoot)).To(Succeed())
-
-			Eventually(func(g Gomega) {
-				g.Expect(f.GardenClient.Client().Get(ctx, client.ObjectKeyFromObject(f.Shoot), f.Shoot)).To(Succeed())
-			}).Should(Succeed())
-
-			v.AfterCompleted(ctx)
+			// test ssh key rotation without node rolling
```
Comment (rfranzke) [inline test/e2e/gardener/shoot/create_rotate_delete.go]:
```suggestion
			// isolated test for ssh key rotation (does not trigger node rolling update)
```

File: test/e2e/gardener/shoot/create_rotate_delete.go [hunk 2]
```diff
@@ -22,10 +22,70 @@ import (
 	gardenerutils "github.com/gardener/gardener/pkg/utils/gardener"
 	e2e "github.com/gardener/gardener/test/e2e/gardener"
 	"github.com/gardener/gardener/test/e2e/gardener/shoot/internal/rotation"
+	"github.com/gardener/gardener/test/framework"
 	"github.com/gardener/gardener/test/utils/access"
 	rotationutils "github.com/gardener/gardener/test/utils/rotation"
 )
 
+func testCredentialRotation(ctx context.Context, v rotationutils.Verifiers, f *framework.ShootCreationFramework) {
```
Comment (rfranzke) [inline test/e2e/gardener/shoot/create_rotate_delete.go]: Please change to `...WithOffset` now that expectations are in this separate function (read https://github.com/gardener/gardener/blob/master/docs/development/testing.md for more info)

**Review by rfranzke — COMMENTED** [review]
Very nice :) I like the `.path` approach.

**Comment by timuthy** [comment]
Just to be sure: Changing the `gardeneruser` component doesn't trigger a node rollout, right @rfranzke?

**Comment by rfranzke** [comment]
> Just to be sure: Changing the `gardeneruser` component doesn't trigger a node rollout, right @rfranzke?

No component change triggers a node rollout. This is solely controlled by fields in the `Shoot` spec.

**Comment by oliver-goetz** [comment]
/lgtm cancel
Apparently, there is still an issue with credentials rotation e2e test 🐛

**Comment by tobschli** [comment]
> Apparently, there is still an issue with credentials rotation e2e test 🐛

Yeah, right now, I am not sure if refactoring this e2e test has any benefit.

Especially with keeping in mind that the introduction of the `Path` unit fixes the described issue.

The adaption of the e2e test was solely because I wanted to adapt it to reproduce the bug, whilst at the same time fixing it with this PR.

Any ideas on how to move forward from here?

File: test/e2e/gardener/shoot/create_rotate_delete.go [hunk 3]
```diff
@@ -105,62 +165,13 @@ var _ = Describe("Shoot Tests", Label("Shoot", "default"), func() {
...
-			}).Should(Succeed())
-
-			Expect(f.WaitForShootToBeReconciled(ctx, f.Shoot)).To(Succeed())
-
-			Eventually(func(g Gomega) {
-				g.Expect(f.GardenClient.Client().Get(ctx, client.ObjectKeyFromObject(f.Shoot), f.Shoot)).To(Succeed())
-			}).Should(Succeed())
-
-			v.AfterCompleted(ctx)
+			// isolated test for ssh key rotation (does not trigger node rolling update)
```
Comment (oliver-goetz) [inline test/e2e/gardener/shoot/create_rotate_delete.go]: I'm not sure whether you are testing the intended thing here. 
For ssh key rotation only, you have to annotate the shoot with [`gardener.cloud/operation=rotate-ssh-keypair`](https://github.com/gardener/gardener/blob/master/docs/usage/shoot-operations/shoot_credentials_rotation.md#ssh-key-pair-for-worker-nodes) while `testCredentialsRotation` function is triggering a complete credentials rotation.

I'm not entirely sure about the reason for the failing tests, but the second rotation might be related. During credentials rotation kube-apiserver is restarting a couple of times. When you do it two times in a row, it can end in a crashloop backoff.

Comment (tobschli) [reply test/e2e/gardener/shoot/create_rotate_delete.go]: Oh, yeah!
I completely oversaw the triggering of the credential rotation [here](https://github.com/gardener/gardener/pull/10671/files#diff-8754abb9e4269533fe6255890ad26eff40d799ea5fe08b9f40329394052541f1R38) using the `v1beta1constants.OperationRotateCredentialsStart`...

I will refactor this and try to reproduce locally.
Thank you very much for the insight🚀

Comment (tobschli) [reply test/e2e/gardener/shoot/create_rotate_delete.go]: I refactored it locally, but the e2e test still fails.

~Contrary to expectation, it fails during the full credential rotation, not in the second one.~

_Edit_: The test actually fails in the `Before` step of the `SSHKeypairVerifier`, will look into it

**Comment by timuthy** [comment]
Any update @tobschli?

**Comment by tobschli** [comment]
> Any update

Unfortunately not. I tried several refactorings, but I cannot get to the root cause.

The bug fix itself works, but only the refactoring of the test that tries to provoke it is unsuccessful.

**Comment by timuthy** [comment]
@oliver-goetz do you think you can assist @tobschli with the e2e test?

File: test/e2e/gardener/shoot/create_rotate_delete.go [hunk 4]
```diff
@@ -22,10 +22,71 @@ import (
...
+
+	v.AfterPrepared(ctx)
+
+	if rotationAnnotation == v1beta1constants.OperationRotateCredentialsStart {
+		By("Complete credentials rotation")
+		ctx, cancel = context.WithTimeout(ctx, 20*time.Minute)
+		defer cancel()
+
+		patch = client.MergeFrom(f.Shoot.DeepCopy())
+		metav1.SetMetaDataAnnotation(&f.Shoot.ObjectMeta, v1beta1constants.GardenerOperation, v1beta1constants.OperationRotateCredentialsComplete)
```
Comment (rfranzke) [inline test/e2e/gardener/shoot/create_rotate_delete.go]: This is very confusing. If "annotation is start, then complete it". Can you improve this, please?

**Review by rfranzke — COMMENTED** [review]
Cool, just one thing FMPOV

File: test/e2e/gardener/shoot/create_rotate_delete.go (hunk 4 above)
Comment (tobschli) [reply test/e2e/gardener/shoot/create_rotate_delete.go]: How about additionally passing a boolean, like `twoStepCredentialRotation`?
Therefore this would become:

```golang
if twoStepCredentialRotation {
By("Complete credentials rotation")
...
```

Comment (oliver-goetz) [reply test/e2e/gardener/shoot/create_rotate_delete.go]: How about two parameters `startRotationAnnotation` and `completeRotationAnnotation`?
If one is empty, this step can be skipped.

Comment (oliver-goetz) [reply test/e2e/gardener/shoot/create_rotate_delete.go]: Btw. the [`AfterCompleted` check](https://github.com/gardener/gardener/pull/10671/files#diff-8754abb9e4269533fe6255890ad26eff40d799ea5fe08b9f40329394052541f1R74-R80) could run conditionally too.

Comment (tobschli) [reply test/e2e/gardener/shoot/create_rotate_delete.go]: > How about two parameters `startRotationAnnotation` and `completeRotationAnnotation`? If one is empty, this step can be skipped.

And the check for the credential completion would look like:
```golang
if completeRotationAnnotation != "" {
...
```

Or did you have something else in mind?
