### PR TITLE
Remove validation for expired `Kubernetes` and `MachineImage` versions in the `CloudProfile`, drop expired versions on creation

### LINKED ISSUE #8229: It is not possible to deploy cloud profiles with expired Kubernetes and operating system versions
**How to categorize this issue?**

/area TODO
/kind bug

**What happened**:

When adding additional infrastructure (in my case VMware vSphere) I often see failures when deploying cloud profiles due to expired operating system and Kubernetes versions. From my point of view this is not a feature but a bug.

To mitigate this I added some coding to filter out expired versions when generating the cloud profile. While this mitigates the deployment failures for initial deployment it is problematic later on and I will remove that code again. The problem is that an expired version must remain in the cloud profile until all clusters / operating systems are upgraded to non-expired versions (at least I do assume that this is the case). My "fix" would however remove the version from the cloud profile although there might still be instances deployed.

Of course, the landscape setup (whatever it might look like) could check whether this is an initial deployment of a cloud profile (remote expired versions) or an update (don't remove them) but this adds another level of complexity. I would therefore appreciate if one could deploy cloud profiles with expired versions (up to 4 weeks would probably be a good compromise).

In contrast to the large cloud providers where one cloud profile is required for each of them, there is one cloud profile required for each vSphere cluster.

**What you expected to happen**:

Cloud profiles with expired versions can be deployed. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
The `gardener-apiserver` now drops expired `Kubernetes` and `MachineImage` versions from cloudprofiles on creation.
This is done silently, and no error is thrown.
See https://github.com/gardener/gardener/issues/8229 for the detailed motivation.

**Which issue(s) this PR fixes**:
Fixes #8229

**Special notes for your reviewer**:

**Release note**:

```feature operator
The `gardener-apiserver` now drops expired `Kubernetes` and `MachineImage` versions from `Cloudprofile`s during creation.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
So far it was forbidden to remove an expired version from the CloudProfile when there is Shoot using that version. Is it still the case or is this restriction now dropped?

**Comment by shafeeqes** [comment]
> So far it was forbidden to remove an expired version from the CloudProfile when there is Shoot using that version. Is it still the case or is this restriction now dropped?

This is only for creation.

**Comment by rfranzke** [comment]
TBH, I don't know whether this PR fixes much. How often are new `CloudProfile`s created where this code would take effect? Isn't the more practical issue that you have `CloudProfile` YAMLs in your git repos and deploy them via GitOps-style pipelines to your landscapes, and suddenly your pipeline fails the next day just because some version expired?

I would vote for simply removing the validation that forbids expired versions in `CloudProfile`s. There is not much benefit in this code (of course, it is semantically useless to have them as explained by @danielfoehrKn in https://github.com/gardener/gardener/issues/8229#issuecomment-1634565776, but it also doesn't harm).

File: pkg/registry/core/cloudprofile/strategy.go [hunk 1]
```diff
@@ -31,6 +32,11 @@ type cloudProfileStrategy struct {
 	names.NameGenerator
 }
 
+// NewStrategy returns a new storage strategy for CloudProfiles.
+func NewStrategy() cloudProfileStrategy {
+	return cloudProfileStrategy{api.Scheme, names.SimpleNameGenerator}
```
Comment (ary1992) [inline pkg/registry/core/cloudprofile/strategy.go]: Can't we simply return `Strategy` here as it is already defined below

File: pkg/registry/core/cloudprofile/strategy_test.go [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+						},
+					},
+				},
+			},
+		}
+
+		cloudprofileregistry.NewStrategy().PrepareForCreate(context.TODO(), cloudProfile)
+
+		Expect(cloudProfile.Spec.Kubernetes.Versions).To(ConsistOf(
+			MatchFields(IgnoreExtras, Fields{
```
Comment (ary1992) [inline pkg/registry/core/cloudprofile/strategy_test.go:118]: It would be better to not use `IgnoreExtras` here as we need to make sure that the expired versions are not present and only the valid cloudprofiles are present. 
Same holds true for machineimage case as well

**Review by ary1992 — COMMENTED** [review]
Nice!

**Comment by shafeeqes** [comment]
> Isn't the more practical issue that you have CloudProfile YAMLs in your git repos and deploy them via GitOps-style pipelines to your landscapes, and suddenly your pipeline fails the next day just because some version expired?

I don't get this, for `UPDATE`, we do not deny updating the cloudprofile if it already contains some expired version, but only adding new expired versions to the existing cloudprofile. 
So if you update the cloudprofile with a new version (with and expiration date) and then have not run the deployment for a very long time and in the meanwhile, the expiration date passes, the deployment will not fail. Is that the case we want to tackle?

File: pkg/registry/core/cloudprofile/strategy_test.go (hunk 2 above)
Comment (shafeeqes) [reply pkg/registry/core/cloudprofile/strategy_test.go:118]: IgnoreExtras is only for the `MatchFields` function, where I am ignoring other fields than "Version". The elements of the array are however checked correctly because of `ConsistOf`

**Comment by rfranzke** [comment]
> > Isn't the more practical issue that you have CloudProfile YAMLs in your git repos and deploy them via GitOps-style pipelines to your landscapes, and suddenly your pipeline fails the next day just because some version expired?
> 
> I don't get this, for `UPDATE`, we do not deny updating the cloudprofile if it already contains some expired version, but only adding new expired versions to the existing cloudprofile. So if you update the cloudprofile with a new version (with and expiration date) and then have not run the deployment for a very long time and in the meanwhile, the expiration date passes, the deployment will not fail. Is that the case we want to tackle?

Maybe, I'm not very sure either. I read https://github.com/gardener/gardener/issues/8229 again, but it didn't help much. Anyways, my proposal was just to remove the validation code and be fine for all potential/weird/special cases. As motivated above - this validation does not have much benefits at all.

**Comment by shafeeqes** [comment]
Isn't it just polluting the cloudprofile, adding expired versions which will never be used since shoots cannot be created with expired versions?! I think this should be taken care of by the operators configuring the cloudprofile. The validation today is just fine.

**Comment by rfranzke** [comment]
Sure, such practice is "polluting" them, but obviously there are some real-world scenarios where it would make things more convenient, especially when using GitOps. Combined with the fact that one cannot remove a version that is still in use, this can lead to problems. Otherwise, we wouldn't have this discussion in the first place :).
My main argument is that this validation does not prevent anything other than this "pollution". It is has no functional benefit whatsoever. And there are many other ways to "pollute" the resources. I would leave this in the responsibility of the user/operator.

**Comment by shafeeqes** [comment]
Fair enough, I removed the validation for expired versions. PTAL! @rfranzke

**Review by rfranzke — COMMENTED** [review]
Thanks, I'm fine with it this way 👍🏻 Maybe we can wait for some others to also provide feedback

File: pkg/registry/core/cloudprofile/strategy.go [hunk 3]
```diff
@@ -76,3 +80,29 @@ func (cloudProfileStrategy) WarningsOnCreate(ctx context.Context, obj runtime.Ob
 func (cloudProfileStrategy) WarningsOnUpdate(ctx context.Context, obj, old runtime.Object) []string {
 	return nil
 }
+
+func dropExpiredVersions(cloudProfile *core.CloudProfile) {
```
Comment (timuthy) [inline pkg/registry/core/cloudprofile/strategy.go:84]: Why is the drop logic still part of the PR?

**Review by timuthy — COMMENTED** [review]
/hold

File: pkg/registry/core/cloudprofile/strategy.go (hunk 3 above)
Comment (timuthy) [reply pkg/registry/core/cloudprofile/strategy.go:84]: If I'm not mistaken, @rfranzke proposed to just remove the validation?!

Comment (shafeeqes) [reply pkg/registry/core/cloudprofile/strategy.go:84]: Does it not still make sense to drop these versions during creation? It anyways cannot be used to create any shoots; why should we have them?

Comment (timuthy) [reply pkg/registry/core/cloudprofile/strategy.go:84]: Fair enough. I wanted to make sure that this is not a leftover, thank you 🙂

**Review by timuthy — COMMENTED** [review]
/unhold
