### PR TITLE
Use lock file as mutex to only write imagevector override patch file sequentially

### LINKED ISSUE #11075: [Flaky Tests] Skaffold post-build hook running `generate-kustomize-patch-gardenlet.sh` can fail due to malformed YAML
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:

All test suites building the `gardenlet` through Skaffold.

**CI link**:

* https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11073/pull-gardener-e2e-kind-ipv6/1869678759502680064
* https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11111/pull-gardener-e2e-kind/1876642357219168256
* https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11145/pull-gardener-e2e-kind/1877718095179550720
* https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11045/pull-gardener-e2e-kind-ha-multi-zone-upgrade/1884958674313547776#1:build-log.txt%3A453
* https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11431/pull-gardener-e2e-kind/1891848295219728384#1:build-log.txt%3A230
* https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11435/pull-gardener-e2e-kind-migration-ha-single-zone/1891863395632680960#1:build-log.txt%3A621
* ... _(more to be added when observed)_

**Reason for failure**:

End-to-end tests on Prow fail sometimes due to Skaffold executing the post-build hook [`generate-kustomize-patch-gardenlet.sh`](https://github.com/gardener/gardener/blob/master/hack/generate-kustomize-patch-gardenlet.sh). The script generates a Kustomize patch file `patch-imagevector-overwrite.yaml` which is not checked into Git that contains the references to the locally built Skaffold artifacts.

Extract of the error log:
```shell
Publishing garden.local.gardener.cloud:5001/local-skaffold_gardenlet:v1.111.0-dev-068caf5cf
Published garden.local.gardener.cloud:5001/local-skaffold_gardenlet:v1.111.0-dev-068caf5cf@sha256:70f956dd7db588c2a16a7c4524245b46c19d50d6f61d809da06f21cd59fc6757
Starting post-build hooks...
Error: bad file 'hack/../example/gardener-local/gardenlet/operator/patch-imagevector-overwrite.yaml': yaml: line 13: could not find expected ':'
Build [local-skaffold/gardenlet] failed: exit status 1
```

This does not happen consistently hence the flaky report.

**Anything else we need to know**:

Assumptions/observations:
* It seems to happen when executing E2E tests on Prow. Not observed locally yet.
* The post-build hook fails because the script expects certain values to be passed from Skaffold either as arguments or environment variables. These values need to be present and fit the format that the script expects. There are no strict checks within the script to assert format and structure.

Through the temporary logging output introduced with we can see the following:
```shell
Error: bad file 'hack/../example/gardener-local/gardenlet/operator/patch-imagevector-overwrite.yaml': yaml: line 13: could not find expected ':'
An error occurred on line 59.
garden.local.gardener.cloud:5001/local-skaffold_gardenlet:v1.111.1-39dac5eea
59 image gardenlet
```

L59 in `generate-kustomize-patch-gardenlet.sh`:
https://github.com/gardener/gardener/blob/2d0d9df48da962a90fd4c7aa048874fbb6d2767d/hack/generate-kustomize-patch-gardenlet.sh#L59

This indicates that `yq` is not able to parse the `patch-imagevector-overwrite.yaml` file.
I'll add a `cat` of the `$patch_file` right before L59 so that we can observe its content.

The new debug logging output reveals what the patch file looks like before running into the error:
```terminal
Starting post-build hooks...
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: Gardenlet
metadata:
  name: local
  namespace: garden
spec:
  deployment:
    imageVectorOverwrite: |-
      images:
        - name: gardener-node-agent
          repository: garden.local.gardener.cloud:5001/local-skaffold_gardener-node-agent
          tag: v1.113.0-dev-7e4a870bf2
-7e4a870bf2
Error: bad file 'hack/../example/gardener-local/gardenlet/operator/patch-imagevector-overwrite.yaml': yaml: line 13: could not find expected ':'
```

Extracting only the YAML content:

```yaml
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: Gardenlet
metadata:
  name: local
  namespace: garden
spec:
  deployment:
    imageVectorOverwrite: |-
      images:
        - name: gardener-node-agent
          repository: garden.local.gardener.cloud:5001/local-skaffold_gardener-node-agent
          tag: v1.113.0-dev-7e4a870bf2
-7e4a870bf2
```

Two observations:
* The suffix of the image tag hash is repeated: `-7e4a870bf2`
* Somehow a newline character `\n` is introduced

Hence `yq` fails at parsing the YAML input on L13.

### PR DESCRIPTION
**Pull request by LucaBernstein**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
We build our Skaffold image artifacts in parallel ([ref](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11431/pull-gardener-e2e-kind/1891848295219728384#1:build-log.txt%3A163)) and thus it can happen, that the after-hook(s) to execute `hack/generate-kustomize-patch-gardenlet.sh` with the `image` parameter run in parallel, leading to conflicting writes and [partial overrides](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11431/pull-gardener-e2e-kind/1891848295219728384#1:build-log.txt%3A216-230).
To fix this problem, this PR creates a lock file to ensure that the generate script is only running once at a time.

Example flakes:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11431/pull-gardener-e2e-kind/1891848295219728384#1:build-log.txt%3A230
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/11435/pull-gardener-e2e-kind-migration-ha-single-zone/1891863395632680960#1:build-log.txt%3A621

**Which issue(s) this PR fixes**:
Fixes #11075

**Special notes for your reviewer**:
/cc @rfranzke @marc1404 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: hack/generate-kustomize-patch-gardenlet.sh [hunk 1]
```diff
@@ -5,6 +5,24 @@
...
+  LOCKFILE_DEST=$(readlink $LOCKFILE)
+  if [[ $OLD_LOCKFILE_DEST == $LOCKFILE_DEST ]]; then
+    echo "Lock file ($LOCKFILE) has not changed recently. Proceeding..."
+    break
+  fi
+  echo "Another instance ($LOCKFILE_DEST, lock file $LOCKFILE) is running. Waiting..."
+  sleep 1  # Wait before retrying
+done
+# Ensure lock is removed on exit
+trap 'rm -f "$LOCKFILE"' EXIT
```
Comment (rfranzke) [inline hack/generate-kustomize-patch-gardenlet.sh]: Can you move this into a function and make it reusable for the other `hack/generate-kustomize-*.sh` scripts as well? They are only called once/not in parallel as of today, but who knows whether it will stay like this. We don't wanna run into the same flake in the future :)

**Review by marc1404 — COMMENTED** [review]
Awesome, thanks for implementing the locking mechanism!

Could you remove my debug output in L66?
https://github.com/gardener/gardener/pull/11447/files#diff-5ff30e202d2bafa8c65edaf619ebc9eb04c653e9bef7e1f54379898089b47c1cR66

We know what the fault pattern in the file looks like so I don't think it'll yield new information.

**Comment by LucaBernstein** [comment]
@marc1404 @rfranzke Thank you for your suggestions. I addressed your comments. Feel free to recheck.

**Review by rfranzke — COMMENTED** [review]
Thank you!

/approve

**Review by marc1404 — APPROVED** [review]
/lgtm

🤞
