### PR TITLE
gardener-apiserver: Enforce the CloudProfile's `.spec.seedSelector` when validating the scheduling constraints of a Shoot

### LINKED ISSUE #6654: control plane migration does not respect seedSelector in cloud profile
**How to categorize this issue?**

/area control-plane-migration
/kind bug

**What happened**:
Control plane migration does not respect `seedSelector.matchLabels` defined in cloud profile. Control plane migration to a destination seed which does not have the corresponding label should not work.
**What you expected to happen**:
When a control plane is migrated it should be checked, if the destination seed has the required label which is defined in the cloud profile. If this is not the case, no migration should be executed 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
This PR modifies the `ShootValidator` admission plugin to validate that the CloudProfile's `.spec.seedSelector` is matching the Seed. The validation is performed when Shoot's seedName is set or updated.

**Which issue(s) this PR fixes**:
Fixes #6654

**Special notes for your reviewer**:
Currently the `ShootValidator` and `ShootBinding` admission plugins duplicate similar code for validating scheduling constraints. @plkokanov shared that it is not required to add the new validation to the `ShootBinding` plugin as `ShootValidator` is already invoked for a binding subresource update

https://github.com/gardener/gardener/blob/3749db49b33e32e2d73c63213f0ea8c94dfba18e/plugin/pkg/shoot/validator/admission.go#L190-L195

**Release note**:

```bugfix operator
gardener-apiserver now validates that the CloudProfile's `.spec.seedSelector` is matching Shoot's Seed when the `.spec.seedName` field of the Shoot is set or modified.
```

### CODE REVIEW

File: plugin/pkg/shoot/validator/admission_test.go [hunk 1]
```diff
@@ -1310,6 +1310,185 @@ var _ = Describe("validator", func() {
...
+						Expect(coreInformerFactory.Core().InternalVersion().Seeds().Informer().GetStore().Add(&seed)).To(Succeed())
+						Expect(coreInformerFactory.Core().InternalVersion().SecretBindings().Informer().GetStore().Add(&secretBinding)).To(Succeed())
+
+						attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, userInfo)
+						err := admissionHandler.Admit(ctx, attrs, nil)
+
+						Expect(err).NotTo(HaveOccurred())
+					})
+
+					It("should reject shoot creation on seed that does not match none of the provider types in the cloud profile's seed selector", func() {
```
Comment (shafeeqes) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
					It("should reject shoot creation on seed that does not match any of the provider types in the cloud profile's seed selector", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 2]
```diff
@@ -1310,6 +1310,185 @@ var _ = Describe("validator", func() {
...
+						Expect(coreInformerFactory.Core().InternalVersion().SecretBindings().Informer().GetStore().Add(&secretBinding)).To(Succeed())
+
+						attrs := admission.NewAttributesRecord(&shoot, nil, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "", admission.Create, &metav1.CreateOptions{}, false, userInfo)
+						err := admissionHandler.Admit(ctx, attrs, nil)
+
+						Expect(err).To(HaveOccurred())
+						Expect(err.Error()).To(ContainSubstring("cannot schedule shoot '%s' on seed '%s' because none of the provider types in the seed selector of cloud profile '%s' is matching the provider type of the seed", shoot.Name, seed.Name, cloudProfile.Name))
+					})
+
+					It("should allow seedName update to seed that matches the cloud profile's seed selector (w/ shoots/binding subresource)", func() {
```
Comment (shafeeqes) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
					It("should allow updating the seedName to a seed that matches the cloud profile's seed selector (w/ shoots/binding subresource)", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 3]
```diff
@@ -1310,6 +1310,185 @@ var _ = Describe("validator", func() {
...
+						Expect(coreInformerFactory.Core().InternalVersion().Seeds().Informer().GetStore().Add(&seed)).To(Succeed())
+						Expect(coreInformerFactory.Core().InternalVersion().SecretBindings().Informer().GetStore().Add(&secretBinding)).To(Succeed())
+
+						attrs := admission.NewAttributesRecord(&shoot, oldShoot, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "binding", admission.Update, &metav1.UpdateOptions{}, false, userInfo)
+						err := admissionHandler.Admit(ctx, attrs, nil)
+
+						Expect(err).NotTo(HaveOccurred())
+					})
+
+					It("should reject seedName update to seed that does not match the cloud profile's seed selector (w/ shoots/binding subresource)", func() {
```
Comment (shafeeqes) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
					It("should reject updating the seedName to a seed that does not match the cloud profile's seed selector (w/ shoots/binding subresource)", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 4]
```diff
@@ -1310,6 +1310,185 @@ var _ = Describe("validator", func() {
...
+						Expect(coreInformerFactory.Core().InternalVersion().SecretBindings().Informer().GetStore().Add(&secretBinding)).To(Succeed())
+
+						attrs := admission.NewAttributesRecord(&shoot, oldShoot, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "binding", admission.Update, &metav1.UpdateOptions{}, false, userInfo)
+						err := admissionHandler.Admit(ctx, attrs, nil)
+
+						Expect(err).To(HaveOccurred())
+						Expect(err.Error()).To(ContainSubstring("cannot schedule shoot '%s' on seed '%s' because the seed selector of cloud profile '%s' is not matching the labels of the seed", shoot.Name, seed.Name, cloudProfile.Name))
+					})
+
+					It("should allow seedName update to seed that matches one of the provider types in the cloud profile's seed selector (w/ shoots/binding subresource)", func() {
```
Comment (shafeeqes) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
					It("should allow updating the seedName to a seed that matches one of the provider types in the cloud profile's seed selector (w/ shoots/binding subresource)", func() {
```

File: plugin/pkg/shoot/validator/admission_test.go [hunk 5]
```diff
@@ -1310,6 +1310,185 @@ var _ = Describe("validator", func() {
...
+						Expect(coreInformerFactory.Core().InternalVersion().Seeds().Informer().GetStore().Add(&seed)).To(Succeed())
+						Expect(coreInformerFactory.Core().InternalVersion().SecretBindings().Informer().GetStore().Add(&secretBinding)).To(Succeed())
+
+						attrs := admission.NewAttributesRecord(&shoot, oldShoot, core.Kind("Shoot").WithVersion("version"), shoot.Namespace, shoot.Name, core.Resource("shoots").WithVersion("version"), "binding", admission.Update, &metav1.UpdateOptions{}, false, userInfo)
+						err := admissionHandler.Admit(ctx, attrs, nil)
+
+						Expect(err).NotTo(HaveOccurred())
+					})
+
+					It("should reject seedName update to seed that does not match none of the provider types in the cloud profile's seed selector (w/ shoots/binding subresource)", func() {
```
Comment (shafeeqes) [inline plugin/pkg/shoot/validator/admission_test.go]:
```suggestion
					It("should reject updating the seedName to a seed that does not match any of the provider types in the cloud profile's seed selector (w/ shoots/binding subresource)", func() {
```

**Review by shafeeqes — COMMENTED** [review]
Overall looks good.
Few nits.

File: plugin/pkg/shoot/validator/admission.go [hunk 6]
```diff
@@ -448,6 +449,24 @@ func (c *validationContext) validateScheduling(ctx context.Context, a admission.
...
+			}
+			if !selector.Matches(labels.Set(c.seed.Labels)) {
+				return admission.NewForbidden(a, fmt.Errorf("cannot schedule shoot '%s' on seed '%s' because the seed selector of cloud profile '%s' is not matching the labels of the seed", c.shoot.Name, c.seed.Name, c.cloudProfile.Name))
+			}
+
+			if seedSelector.ProviderTypes != nil {
+				if !sets.NewString(seedSelector.ProviderTypes...).HasAny(c.seed.Spec.Provider.Type, "*") {
+					return admission.NewForbidden(a, fmt.Errorf("cannot schedule shoot '%s' on seed '%s' because none of the provider types in the seed selector of cloud profile '%s' is matching the provider type of the seed", c.shoot.Name, c.seed.Name, c.cloudProfile.Name))
+				}
+			}
```
Comment (shafeeqes) [inline plugin/pkg/shoot/validator/admission.go:466]: Just something I noticed during testing, Can we add these to an `ErrorList` and return instead of returning at the first occurence? Both of them can happen parallely.

Comment (ialidzhikov) [reply plugin/pkg/shoot/validator/admission.go:466]: You are right that both the the errors can occur at the same time.

If we decide to use the `ErrorList` approach only for the newly introduced checks, it would look like:
```diff
@@ -455,15 +455,26 @@ func (c *validationContext) validateScheduling(ctx context.Context, a admission.
 			if err != nil {
 				return apierrors.NewInternalError(fmt.Errorf("label selector conversion failed: %v for seedSelector: %w", seedSelector.LabelSelector, err))
 			}
+
+			var (
+				allErrs field.ErrorList
+				path    = field.NewPath("spec", "seedName")
+			)
 			if !selector.Matches(labels.Set(c.seed.Labels)) {
-				return admission.NewForbidden(a, fmt.Errorf("cannot schedule shoot '%s' on seed '%s' because the seed selector of cloud profile '%s' is not matching the labels of the seed", c.shoot.Name, c.seed.Name, c.cloudProfile.Name))
+				detail := fmt.Sprintf("cannot schedule shoot '%s' on seed '%s' because the seed selector of cloud profile '%s' is not matching the labels of the seed", c.shoot.Name, c.seed.Name, c.cloudProfile.Name)
+				allErrs = append(allErrs, field.Invalid(path, c.shoot.Spec.SeedName, detail))
 			}

 			if seedSelector.ProviderTypes != nil {
 				if !sets.NewString(seedSelector.ProviderTypes...).HasAny(c.seed.Spec.Provider.Type, "*") {
-					return admission.NewForbidden(a, fmt.Errorf("cannot schedule shoot '%s' on seed '%s' because none of the provider types in the seed selector of cloud profile '%s' is matching the provider type of the seed", c.shoot.Name, c.seed.Name, c.cloudProfile.Name))
+					detail := fmt.Sprintf("cannot schedule shoot '%s' on seed '%s' because none of the provider types in the seed selector of cloud profile '%s' is matching the provider type of the seed", c.shoot.Name, c.seed.Name, c.cloudProfile.Name)
+					allErrs = append(allErrs, field.Invalid(path, c.shoot.Spec.SeedName, detail))
 				}
 			}
+
+			if len(allErrs) > 0 {
+				return admission.NewForbidden(a, fmt.Errorf("%+v", allErrs))
+			}
 		}
 	}
```

The new checks would be inconsistent with the other ones in the `validateScheduling` func. I rather think that the `validateScheduling` func has to be adapted to return `ErrorList`. I would vote to keep the current checks as they are for the score of this PR. If you want, I can try to prepare a new PR that adapts the `validateScheduling` func to return `ErrorList`. WDYT?

Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission.go:466]: Yes, I noticed that as well. You can keep it like this, I have already prepared a PR on top of this to cleanup binding plugin, I could make the changes.

Comment (ialidzhikov) [reply plugin/pkg/shoot/validator/admission.go:466]: WIP commit that I prepared locally - https://github.com/ialidzhikov/gardener/commit/cb724fc01798d9983af6c5a86eb9126eefafa034.

> You can keep it like this, I have already prepared a PR on top of this to cleanup binding plugin, I'll make the changes.

Thanks, I had an item in my list to open issue about it.

Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission.go:466]: Then please go ahead and open the PR. :)
