### PR TITLE
Fix deletion of shoots with invalid DNS provider credentials

### LINKED ISSUE #4778: Deletion sometimes stuck for Shoots with invalid DNS Credentials
**How to categorize this issue?**

/kind bug
/priority 3

**What happened**:
I created several clusters for which I configured DNS providers with invalid credentials. Sometimes those clusters can no longer be deleted. Deletion fails and cluster gets stuck in `Delete Failed` state. Retry operation also does not solve the problem.

```
Flow "Shoot cluster deletion" encountered task errors: [task "Deploying additional DNS providers" failed: retry failed with context deadline exceeded, last error: 1 error occurred:
	* Error while waiting for DNSProvider shoot--lukas--test1/aws-route53-other-secret to become ready: state Error: cannot get hosted zones: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: d4f0a8d9-b24c-4c58-b038-74fc2216df13

]
```

```
task "Deploying additional DNS providers" failed: retry failed with context deadline exceeded, last error: 1 error occurred:
	* Error while waiting for DNSProvider shoot--lukas--test1/aws-route53-other-secret to become ready: state Error: cannot get hosted zones: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: d4f0a8d9-b24c-4c58-b038-74fc2216df13

Delete Failed
Invalid cloud provider credentials.
```

**What you expected to happen**:
Deletion should not fail as there are no resources that require cleanup (credentials have been invalid all the time, so no DNS records have been created).

**How to reproduce it (as minimally and precisely as possible)**:
Create invalid DNS credentials. Use them for a new shoot. Delete shoot. However, the issue does not occur always but most of the time.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.33.0-dev
- Kubernetes version (use `kubectl version`): 1.21.3
- Cloud provider or hardware configuration: aws
- Others:

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area networking
/kind bug

**What this PR does / why we need it**:
Fixes deletion of shoots with invalid DNS provider credentials by avoiding the deployment of additional DNS providers in the deletion flow for which there are no `DNSEntry` resources with non-empty `Status.Targets` in the shoot namespace (for example, if the `DNSProvider` has never been created successfully in the first place). 

Note that if there are `DNSEntry` resources with non-empty `Status.Targets` for a `DNSProvider` it will still be deployed and the shoot deletion will still fail if this fails (e.g. due to invalid credentials). In such situations, it is mandatory to fix the credentials (or whatever error is preventing the successful `DNSProvider` deployment) in order to ensure that actual DNS records will be deleted.

**Which issue(s) this PR fixes**:
Fixes #4778

**Special notes for your reviewer**:

**Release note**:

```bugfix user
It should now be possible to delete shoots with invalid DNS provider credentials if there are no DNSEntry resources with non-empty `Status.Targets` for the corresponding provider in the shoot namespace.
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/shoot_control_delete.go [hunk 1]
```diff
@@ -144,6 +146,19 @@ func (r *shootReconciler) runDeleteShootFlow(ctx context.Context, o *operation.O
 			controlPlaneDeploymentNeeded, err = needsControlPlaneDeployment(ctx, o, kubeAPIServerDeploymentFound, infrastructure)
 			return err
 		}),
+		errors.ToExecute("Check if there are DNSEntry resources in the shoot namespace in the seed cluster", func() error {
+			dnsEntryList := &dnsv1alpha1.DNSEntryList{}
+			if err := botanist.K8sSeedClient.APIReader().List(ctx, dnsEntryList, client.InNamespace(o.Shoot.SeedNamespace)); err != nil {
+				return err
+			}
+			for _, dnsEntry := range dnsEntryList.Items {
+				if len(dnsEntry.Status.Targets) > 0 {
```
Comment (timuthy) [inline pkg/gardenlet/controller/shoot/shoot_control_delete.go]: Ideally, we would check if the `DNSEntry` has any associated `DNSProvider` and only exclude those from `deployAdditionalDNSProviders` which don't manage any `DNSEntries`.

The reasons are:
- There will always be `DNSEntries` if the feature gate `UseDNSRecords` is off.
- One can have multiple provider under which only one or a few have an issue.

**Review by timuthy — CHANGES_REQUESTED** [review]
Thanks for the PR. I have one doubt about querying the `DNSEntries`.

File: pkg/gardenlet/controller/shoot/shoot_control_delete.go (hunk 1 above)
Comment (stoyanr) [reply pkg/gardenlet/controller/shoot/shoot_control_delete.go]: Hm, yes, you are right. This would make the check a bit more complex though. Let me have another try.

Comment (stoyanr) [reply pkg/gardenlet/controller/shoot/shoot_control_delete.go]: Changed as suggested, PTAL.

**Review by MartinWeindel — APPROVED** [review]
/lgtm

**Review by timuthy — APPROVED** [review]
/lgtm
Thanks a lot @stoyanr
