### PR TITLE
Properly select CA secrets by labels

### LINKED ISSUE #5847: shoots/adminkubeconfig signs client cert with wrong ca
**How to categorize this issue?**
/area security
/kind bug

**What happened**:
I have created a new shoot cluster with a gardener version `v1.45.0-dev-fa7ad84e4f7bf7a6a378f85aa58bdd3edb55e365`

Running the following gets me an adminkubeconfig for my Shoot
```bash
export NAMESPACE=my-namespace
export SHOOT_NAME=my-shoot
kubectl create \
    -f example/shoot-kubeconfig/kubeconfig-request.json \
    --raw /apis/core.gardener.cloud/v1beta1/namespaces/${NAMESPACE}/shoots/${SHOOT_NAME}/adminkubeconfig | jq -r ".status.kubeconfig" | base64 -d
```
When using this kubeconfig I get 
```bash
k get ns
error: You must be logged in to the server (Unauthorized)
```

The `kube-apiserver` logs show
```bash
E0422 09:14:41.123364       1 authentication.go:63] "Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=124488920684317941043728821992975984632, SKID=, AKID=45:6C:28:A7:3A:E7:58:37:B4:DE:74:C2:6B:B2:B3:8C:89:D6:B5:EE failed: x509: certificate signed by unknown authority]"
```

The client-certificate in my kubeconfig was issued by `CN=kubernetes` with AKID `45:6C:28:A7:3A:E7:58:37:B4:DE:74:C2:6B:B2:B3:8C:89:D6:B5:EE` which I can find in the ShootState under `.spec.gardener` as  item with name `ca`.

`ca` (v1beta1constants.SecretNameCACluster) is obviously the wrong ca as for new shoot clusters there a dedicated client ca is used https://github.com/gardener/gardener/pull/5779. 
`ca` is the fallback if `ca-client` (`v1beta1constants.SecretNameCAClient`) is not found in the gardener resource data list
https://github.com/gardener/gardener/blob/fa7ad84e4f7bf7a6a378f85aa58bdd3edb55e365/pkg/registry/core/shoot/storage/admin_kubeconfig.go#L122-L124

However there is no such entry with name `ca-client`. Instead there is an entry with name `ca-client-58f8e9ac` and that's why it can't be found and it takes the fallback.
```
{
  "data": {
    "ca.crt": "LS0t<redacted>",
    "ca.key": "LS0t<redacted>"
  },
  "labels": {
    "name": "ca-client"
  },
  "name": "ca-client-58f8e9ac",
  "type": "secret"
},
```
**What you expected to happen**:
I should be able to authenticate using the shoots/adminkubeconfig

**How to reproduce it (as minimally and precisely as possible)**:
Create a new shoot. Try to authenticate using the shoots/adminkubeconfig as described here https://github.com/gardener/gardener/blob/master/example/shoot-kubeconfig/README.md

**Anything else we need to know?**:
There is already an issue to have e2e tests for the shoots/adminkubeconfig feature which would have prevented / found this regression earlier
https://github.com/gardener/gardener/issues/5586

**Environment**:

- Gardener version: `v1.45.0-dev-fa7ad84e4f7bf7a6a378f85aa58bdd3edb55e365`
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind regression

**What this PR does / why we need it**:
The client CA introduced with #5779 does never have a constant name (`ca-client`) but always a name including the config checksum (`ca-client-<some-hash>`). Hence, the code trying to retrieve the client CA for the `shoots/adminkubeconfig` subresource is failing and falls back to the cluster CA (`ca`). Consequently, client certificate are issued by the wrong CA since the cluster CA is no longer used for verifying client certificates.

Now, we properly select the client CA via the secrets manager labels. If this fails we try the same with the cluster CA, and only if this fails as well we fall back to the constant cluster CA name (`ca`).

**Which issue(s) this PR fixes**:
Fixes #5847

**Special notes for your reviewer**:
/milestone v1.45
/cc @acumino 

This is basically a modified cherry-pick of https://github.com/gardener/gardener/pull/5790/commits/b9ffff2baf3b9e36b331c060dbf2a0f4b967791a.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/registry/core/shoot/storage/admin_kubeconfig.go [hunk 1]
```diff
@@ -117,16 +122,34 @@ func (r *AdminKubeconfigREST) Create(ctx context.Context, name string, obj runti
...
+	if err != nil {
+		return nil, errors.NewInternalError(fmt.Errorf("could not find CA certificate for %s: %w", nameCAClientReq, err))
+	}
+
+	// fall back to cluster CA since not all clusters might have a client CA yet
 	if ca == nil {
-		ca = resourceDataList.Get(v1beta1constants.SecretNameCACluster)
-		if ca == nil {
-			return nil, errors.NewInternalError(fmt.Errorf("certificate authority not yet provisioned"))
+		ca, err = getCAFromResourceDataList(resourceDataList, nameCAClusterReq)
```
Comment (acumino) [inline pkg/registry/core/shoot/storage/admin_kubeconfig.go:137]: Q- Why are we trying to get cluster ca at two places? here and line 146

Comment (rfranzke) [reply pkg/registry/core/shoot/storage/admin_kubeconfig.go:137]: Here we try to get it via the `labels`, in L146 we get it via the `name` as fall-back for backwards-compatibility (the `ShootState` for some clusters might not yet contain the labels). The L146-related code will be dropped in the next Gardener version.

Comment (acumino) [reply pkg/registry/core/shoot/storage/admin_kubeconfig.go:137]: Thanks, I guessed since we are already one version ahead every cluster's `ShootState` must have updated.

**Review by acumino — COMMENTED** [review]
/lgtm
/approve
