### PR TITLE
Fix machine image defaulting

### LINKED ISSUE #2569: Machine Image downgraded during apply
**How to categorize this issue?**

/area quality
/kind bug
/priority normal

**What happened**:
We have some Shoots that are applied without a machine image version and were previously defaulted to a preview version. This was fixed in #2534.

But now that the Shoots are applied again without a machine image version, they are defaulted to the non-preview version which means a machine image version downgrade, which should never happen.

**What you expected to happen**:
Shoot versions not to be downgraded for existing cluster, even though a new apply doesn't specify the version.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a new Shoot with a preview machine image version
- Apply the Shoot without any version
- See the machine image version get downgraded to a non-preview version.

/cc @danielfoehrKn 

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.7.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area quality
/kind bug
/priority normal

**What this PR does / why we need it**:
This PR fixes the machine image defaulting in the case, that the Shoot is updated with a machine image name set but version unset.
I also restructured the Shoot validator test along the way (first commit) to make it a bit more easy to overlook.

**Which issue(s) this PR fixes**:
Fixes #2569

**Special notes for your reviewer**:
/invite @ialidzhikov 
/cc @vpnachev @danielfoehrKn 

**Release note**:

```improvement operator
A bug was fixed that caused the machine image version to be overwritten in case a Shoot was updated with a specified image name but with an unspecified image version.
```

### CODE REVIEW

File: plugin/pkg/shoot/validator/admission.go [hunk 1]
```diff
@@ -772,9 +772,26 @@ func ensureMachineImage(oldWorkers []core.Worker, worker core.Worker, images []c
...
+	oldWorker := helper.FindWorkerByName(oldWorkers, worker.Name)
+	if oldWorker != nil && oldWorker.Machine.Image != nil {
+		// worker is already existing -> keep the machine image if name/version is unspecified
+		if worker.Machine.Image == nil {
+			// machine image completely unspecified in new shoot -> keep the old one
+			return oldWorker.Machine.Image, nil
+		}
+
+		if oldWorker.Machine.Image.Name == worker.Machine.Image.Name {
+			// image name was not changed -> keep version from new shoot if specified, otherwise use
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission.go]:
```suggestion
			// image name was not changed -> keep version from the new worker if specified, otherwise use the old worker image version
```

File: plugin/pkg/shoot/validator/admission.go [hunk 2]
```diff
@@ -772,9 +772,26 @@ func ensureMachineImage(oldWorkers []core.Worker, worker core.Worker, images []c
...
 	// shoot maintenance controller.
 
-	name := worker.Name
-	if oldWorker := helper.FindWorkerByName(oldWorkers, name); worker.Machine.Image == nil && oldWorker != nil && oldWorker.Machine.Image != nil {
-		return oldWorker.Machine.Image, nil
+	oldWorker := helper.FindWorkerByName(oldWorkers, worker.Name)
+	if oldWorker != nil && oldWorker.Machine.Image != nil {
+		// worker is already existing -> keep the machine image if name/version is unspecified
+		if worker.Machine.Image == nil {
+			// machine image completely unspecified in new shoot -> keep the old one
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission.go]:
```suggestion
			// machine image completely unspecified in new worker -> keep the old one
```

File: plugin/pkg/shoot/validator/admission.go [hunk 3]
```diff
@@ -772,9 +772,26 @@ func ensureMachineImage(oldWorkers []core.Worker, worker core.Worker, images []c
...
+		}
+
+		if oldWorker.Machine.Image.Name == worker.Machine.Image.Name {
+			// image name was not changed -> keep version from new shoot if specified, otherwise use
+			if len(worker.Machine.Image.Version) != 0 {
+				return worker.Machine.Image, nil
+			}
+			return oldWorker.Machine.Image, nil
+		} else {
+			// image name was changed -> keep version from new shoot if specified, otherwise default the image version
```
Comment (ialidzhikov) [inline plugin/pkg/shoot/validator/admission.go]:
```suggestion
			// image name was changed -> keep version from new worker if specified, otherwise default the image version
```

**Review by ialidzhikov — COMMENTED** [review]
Thank you for this PR!

**Comment by timebertt** [comment]
@ialidzhikov thanks, addressed your comment! PTAL :)

**Review by ialidzhikov — APPROVED** [review]
/lgtm
