### PR TITLE
Enhance shoot validation error message

### LINKED ISSUE #9030: wrong error message for missing min/max count in shoot worker spec
**How to categorize this issue?**

/area usability
/kind bug

**What happened**:
I was experimenting with programmatic generation of minimal shoot manifests and my manifest
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: my-shoot
  namespace: my-project
spec:
  cloudProfileName: gcp
  kubernetes:
    version: '1.27'
  networking:
    nodes: 10.180.0.0/16
    type: calico
  provider:
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west1-b
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.180.0.0/16
    type: gcp
    workers:
    - machine:
        image:
          name: gardenlinux
        type: n1-standard-2
      name: my-worker
      volume:
        size: 50Gi
        type: pd-balanced
      zones:
      - europe-west1-b
  purpose: evaluation
  region: europe-west1
  secretBindingName: my-secret
```
gave me this validation error when trying to apply it:
```
The Shoot "my-shoot" is invalid: spec.provider.workers: Forbidden: at least one active worker pool with allowSystemComponents=true needed
```

Adding
```yaml
allowSystemComponents: true
```
to the worker's spec leads to
```
Shoot in version "v1beta1" cannot be handled as a Shoot: strict decoding error: unknown field "spec.provider.workers[0].allowSystemComponents"
```

I checked an existing shoot and found that the actual syntax looks like this:
```yaml
systemComponents:
  allow: true
```

However, with that added to the worker's spec, I still got the original error message.
I then noticed that my shoot spec was missing the `minimum`, `maximum`, and `maxSurge` fields of the worker spec. With these added, it worked (even without the `systemComponents` part).

**What you expected to happen**:
I would expect the error message to hint to the missing `minimum`, `maximum`, and `maxSurge` fields instead of the `systemComponents` field (which seems to not be a problem if missing).
If the missing `systemComponents` field was a problem, I would expect the error message to use `systemComponents.allow=true` instead of `allowSystemComponents=true`.

**How to reproduce it (as minimally and precisely as possible)**:
Adapt name, namespace, and secret binding name and apply the above manifest.

**Environment**:

- Gardener version: v1.86.0
- Kubernetes version (use `kubectl version`):
  - Client Version: v1.27.3
  - Server Version: v1.26.10

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area usability
/kind bug

**What this PR does / why we need it**:
This PR fixes issue #9030 and by enhancing the shoot validation error message and making it more explanatory.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/9030

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/apis/core/validation/shoot.go [hunk 1]
```diff
@@ -1992,10 +1998,11 @@ func ValidateSystemComponentWorkers(workers []core.Worker, kubernetesVersion str
 			continue
 		}
 
+		atLeastOnePoolWithAllowedSystemComponents = true
```
Comment (plkokanov) [inline pkg/apis/core/validation/shoot.go]: I'm not sure that this is correct. We need the worker pool that has `sysemComponents.allow: true` to also have `worker.maximum` > `0`. Otherwise, I can create a shoot which has two pools: one with `worker.maximum` = `1` and `sysemComponents.allow`: `false`, and one with `worker.maximum` = `0` and `systemComponents.allow` = `true`.
I'm guessing that this is also what the `active` keyword in the `at least one active worker pool with systemComponents.allow=true needed` message refers to. 
This behaviour was also represented in one of the unit tests which was changed in this PR, however I don't think we should change it.

Note that `systemComponents.allow` is defaulted to true if it is not specified. That is why @Diaphteiros was able to create the shoot when he did not specify `systemComponents.allow`

**Review by plkokanov — CHANGES_REQUESTED** [review]

**Review by ialidzhikov — APPROVED** [review]
/lgtm
