### PR TITLE
Fix make target `test-e2e-local-operator-seed` for local execution

### LINKED ISSUE #10468: `USE_PROVIDER_LOCAL_COREDNS_SERVER` is not reliably working
**How to categorize this issue?**
/area dev-productivity testing 
/kind bug

**What happened**:
The `gardener-extension-provider-local-coredns/coredns` service is exposed via NodePort on the port `30053` on the k8s node. The kind cluster is mapping this port to the host port 5353 only for the `gardener-operator-local-control-plane` node. However, the coredns pod are not guaranteed to be scheduled on this node and when they run on `gardener-operator-local-worker` or `gardener-operator-local-worker2` resolving via dns server `127.0.0.1:5353` fails (which usually leads to failed execution of e2e tests).     

**What you expected to happen**:
`gardener-extension-provider-local-coredns/coredns` to be always available on 127.0.0.1:5353

**How to reproduce it (as minimally and precisely as possible)**:

1. Create local garden environment with

    ```bash
    $ make kind-operator-up operator-seed-up
    ```

1. Check the coredns pod is not running on the node `gardener-operator-local-control-plane`

    ```bash
    $ k -n gardener-extension-provider-local-coredns get pod -owide
    NAME                      READY   STATUS    RESTARTS   AGE   IP             NODE                             NOMINATED NODE   READINESS GATES
    coredns-746969c56-g9j7q   1/1     Running   0          12s   10.1.254.111   gardener-operator-local-worker   <none>           <none>
    ```

1. Check that the dns server cannot be connected from the host

    ```
    $ dig @127.0.0.1 -p 5353 api.e2e-managedseed.garden.internal.local.gardener.cloud +tcp
    
    ; <<>> DiG 9.10.6 <<>> @127.0.0.1 -p 5353 api.e2e-managedseed.garden.internal.local.gardener.cloud +tcp
    ; (1 server found)
    ;; global options: +cmd
    ;; connection timed out; no servers could be reached```
    ```

**Anything else we need to know?**:
Because of the above issue, e2e tests execution fails due to inability to resolve garden landscape hostnames.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by MartinWeindel**
**How to categorize this PR?**

/area dev-productivity
/kind bug

**What this PR does / why we need it**:
Local execution of the makefile target `test-e2e-local-operator-seed` fails (at least on MacOS), because the DNS lookup enabled with `USE_PROVIDER_LOCAL_COREDNS_SERVER` does not work.
The fix contains two parts:
- ensure that the additional coredns server deployed by the provider-local is reachable at IP `172.18.255.1` to resolve forwarding issue with Docker Desktop on Mac
- rename the seed name to avoid precedence of entry in `/etc/hosts`, if the managedseed e2e test is run from the `test-e2e-local-operator-seed` 

**Which issue(s) this PR fixes**:
Fixes #10468

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by marc1404 — COMMENTED** [review]
/lgtm

Thank you for addressing this issue! 🧙‍♂️ 

I have one small suggestion but it's not important.

File: test/e2e/gardener/managedseed/create_rotate_delete.go [hunk 1]
```diff
@@ -34,8 +34,12 @@ import (
...
 )
 
-// SeedName is the name of the managed seed used in this e2e test
-const SeedName = "e2e-managedseed"
+const (
+	// SeedName is the name of the managed seed used in this e2e test
+	SeedName = "e2e-managedseed"
+	// SeedNameOperator is the name of the managed seed used in this e2e test with the gardener-operator
+	SeedNameOperator = "e2e-mngdseed-op"
+)
```
Comment (marc1404) [inline test/e2e/gardener/managedseed/create_rotate_delete.go]: Minor suggestion: What about changing `SeedName` to a function?
```go
func SeedName() string { // or GetSeedName()
	if os.Getenv("OPERATOR_SEED") == "true" {
		return "e2e-mngdseed-op"
	}
	return "e2e-managedseed"
}
```

It would encapsulate the dynamic nature introduced by the environment variable as well as avoid the need for the tests to read/compare two values.
I've also thought about changing `SeedName` from a `const` to a `var` but felt that a function might be a bit _'cleaner'_.

What do you think?

**Review by marc1404 — APPROVED** [review]
/lgtm

Thanks! 🫶
