### PR TITLE
Ensure gardenlet deployment has properly set env KUBERNETES_SERVICE_HOST

### LINKED ISSUE #3717: Network policy allow-to-seed-apiserver is not updated on time when APIServerSNI is enabled
**How to categorize this issue?**

/kind bug
/priority normal
/assign @mvladev 

**What happened**:
The APIServerSNI feature gate was enabled for a seed cluster that hosts managed seeds.
When this has happened the managed seed was not in its maintenance time window, thus it did not get a shoot reconciliations, just the SHOOTEDSEED controller has reconciled it, i.e. re-deployed and re-configured the gardenlet. 
Later, during the maintenance time window, the managed seed got the mutating webhook `apiserver-proxy.networking.gardener.cloud` and its kube-apiserver deployment was extended with a sidecar `apiserver-proxy-pod-mutator` which will be responsible to inject `KUBERNETES_SERVICE_HOST` in the pods of the managed seed, i.e. in the gardenlet pod. However, there is nothing to re-restart the gardenlet and it did not get the environment variable, hence the 
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: Allows Egress from pods labeled with 'networking.gardener.cloud/to-seed-apiserver=allowed'
      to Seed's Kubernetes API Server endpoints in the default namespace.
  name: allow-to-seed-apiserver
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.0.12.241/32 # the address of the default/kubernetes endpoint
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-seed-apiserver: allowed
  policyTypes:
  - Egress
```

While, it must be extended also with the address of the SNI ingress LoadBalancer 
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: Allows Egress from pods labeled with 'networking.gardener.cloud/to-seed-apiserver=allowed'
      to Seed's Kubernetes API Server endpoints in the default namespace.
  name: allow-to-seed-apiserver
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.0.12.241/32
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 1.2.3.4/32 # this is the IP address of the SNI Ingress LB. It is set by the gardenlet based on the KUBERNETES_SERVICE_HOST env var
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-seed-apiserver: allowed
  policyTypes:
  - Egress
```

Due to the misconfigured network policy, a lot of control plane components of normal shoots hosted in the managed seed cannot connect to the API of the seed as they have been injected with `KUBERNETES_SERVICE_HOST`.

**What you expected to happen**:
The gardenlet pods to be updated on time when the SNI is enabled/disabled.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a seed and managed seed initially with APIServerSNI=false.
1. Enable APIServerSNI while the managed seed is outside of its maintenance time window.
1. Create a shoot scheduled on the managed seed.
1. Check that some of the controllers are failing to connect to the API of the managed seed, for example the Gardener Resource Manager.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.18.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area networking  ops-productivity 
/kind bug

**What this PR does / why we need it**:
With this PR the gardenlet deployment is always ensured to have the env var `KUBERNETES_SERVICE_HOST` which is used to update the network policy `allow-to-seed-apiserver` here:
https://github.com/gardener/gardener/blob/e44fd5e8c99af94ccea411a79fad0522e85131ef/pkg/gardenlet/controller/federatedseed/networkpolicy/hostnameresolver/resolver.go#L162-L208

**Which issue(s) this PR fixes**:
Fixes #3717, I wanted to inject the internal domain, but I cannot find easy way to get it from the managed seed controller.

**Special notes for your reviewer**:
/invite @mvladev 

**Release note**:

```bugfix operator
Fix a bug where the `gardenlet` was not updating the `allow-to-seed-apiserver` network policy with the IP address of the seed's API server when the `APIServerSNI` feature gate is just enabled.
```

### CODE REVIEW

File: pkg/gardenlet/controller/managedseed/managedseed_actuator.go [hunk 1]
```diff
@@ -525,7 +548,52 @@ func (a *actuator) prepareGardenletChartValues(
...
+
+	if len(shootDomain) != 0 {
+		deployment.Env = append(
+			deployment.Env,
+			corev1.EnvVar{
+				Name:  kubernetesServiceHost,
+				Value: shootDomain,
+			},
+		)
+	}
```
Comment (mvladev) [inline pkg/gardenlet/controller/managedseed/managedseed_actuator.go]: I think its better to change the implementation to one where you don't overwrite the `KUBERNETES_SERVICE_HOST` if it already exists. End-users might want to set it in the first place.

```suggestion
	if dns != nil && dns.Domain != nil && len(*dns.Domain) != 0 {
		shootDomain = fmt.Sprintf("api.%s", *dns.Domain)
	}

	if len(shootDomain) == 0 {
		return deployment
	}

	if deployment.Env == nil {
		deployment.Env = []corev1.EnvVar{}
	}

	for _, env := range deployment.Env {
		if env.Name == kubernetesServiceHost {
			// value is already set.
			return deployment
		}
	}

	deployment.Env = append(
		deployment.Env,
		corev1.EnvVar{
			Name:  kubernetesServiceHost,
			Value: shootDomain,
		},
	)
```

File: pkg/gardenlet/controller/managedseed/managedseed_actuator.go [hunk 2]
```diff
@@ -274,8 +274,20 @@ func (a *actuator) deployGardenlet(ctx context.Context, shootClient kubernetes.I
...
+		shootClient,
+		managedSeed.Spec.Gardenlet.Deployment,
+		gardenletConfig,
+		managedSeed.Name,
+		v1alpha1helper.GetBootstrap(
+			managedSeed.Spec.Gardenlet.Bootstrap,
+		),
+		utils.IsTrue(
+			managedSeed.Spec.Gardenlet.MergeWithParent,
+		),
```
Comment (rfranzke) [inline pkg/gardenlet/controller/managedseed/managedseed_actuator.go]:
```suggestion
		v1alpha1helper.GetBootstrap(managedSeed.Spec.Gardenlet.Bootstrap),
		utils.IsTrue(managedSeed.Spec.Gardenlet.MergeWithParent),
```

File: pkg/gardenlet/controller/managedseed/managedseed_actuator.go [hunk 3]
```diff
@@ -297,8 +309,19 @@ func (a *actuator) deleteGardenlet(ctx context.Context, shootClient kubernetes.I
...
+		shootClient,
+		managedSeed.Spec.Gardenlet.Deployment,
+		gardenletConfig,
+		managedSeed.Name,
+		v1alpha1helper.GetBootstrap(
+			managedSeed.Spec.Gardenlet.Bootstrap,
+		),
+		utils.IsTrue(
+			managedSeed.Spec.Gardenlet.MergeWithParent,
+		), shoot,
```
Comment (rfranzke) [inline pkg/gardenlet/controller/managedseed/managedseed_actuator.go]:
```suggestion
		v1alpha1helper.GetBootstrap(managedSeed.Spec.Gardenlet.Bootstrap),
		utils.IsTrue(managedSeed.Spec.Gardenlet.MergeWithParent),
		shoot,
```

File: pkg/gardenlet/controller/managedseed/managedseed_actuator.go [hunk 4]
```diff
@@ -525,7 +548,52 @@ func (a *actuator) prepareGardenletChartValues(
 	gardenletConfig.SeedSelector = nil
 
 	// Get gardenlet chart values
-	return a.vp.GetGardenletChartValues(deployment, gardenletConfig, bootstrapKubeconfig)
+	return a.vp.GetGardenletChartValues(
+		ensureGardenletEnvironment(
+			deployment,
+			shoot.Spec.DNS,
+		),
```
Comment (rfranzke) [inline pkg/gardenlet/controller/managedseed/managedseed_actuator.go]:
```suggestion
		ensureGardenletEnvironment(deployment, shoot.Spec.DNS),
```

File: pkg/gardenlet/controller/managedseed/managedseed_actuator.go [hunk 5]
```diff
@@ -525,7 +548,52 @@ func (a *actuator) prepareGardenletChartValues(
...
+// ensureGardenletEnvironment sets the KUBERNETES_SERVICE_HOST to the API of the ManagedSeed cluster.
+// This is needed so that the deployed gardenlet can properly set the network policies
+// allowing access of control plane components of the hosted shoots to the API server of the (managed) seed.
+func ensureGardenletEnvironment(deployment *seedmanagementv1alpha1.GardenletDeployment, dns *gardencorev1beta1.DNS) *seedmanagementv1alpha1.GardenletDeployment {
+	const (
+		kubernetesServiceHost = "KUBERNETES_SERVICE_HOST"
+	)
+	var (
+		shootDomain = ""
+	)
```
Comment (rfranzke) [inline pkg/gardenlet/controller/managedseed/managedseed_actuator.go]:
```suggestion
	const kubernetesServiceHost = "KUBERNETES_SERVICE_HOST"
	var shootDomain = ""
```

**Review by rfranzke — COMMENTED** [review]
Just a few nit styling comments to reduce verbosity :)

File: pkg/gardenlet/controller/managedseed/managedseed_actuator.go (hunk 1 above)
Comment (vpnachev) [reply pkg/gardenlet/controller/managedseed/managedseed_actuator.go]: Done.

**Review by mvladev — APPROVED** [review]
