### PR TITLE
Reset shoot rate limiting on deletion

### LINKED ISSUE #3050: Faster requeueing when exponentially backoffed shoot shall be deleted
**How to categorize this issue?**

/area usability
/kind enhancement
/priority normal

**What would you like to be added**:
When a shoot that fails to be created or reconciled for a long time then it is exponentially backoffed. When it is later deleted by the user, then it might still take the full backoff time (~16m) until the deletion flow starts (because we only use one queue and only differentiate which flow to start when we pick it up).
The same applies for other operation types like migration and restoration.

Let's enhance our event handlers in the shoot controller and enqueue shoots faster when the operation type changes.

/cc @timebertt @vlerenc @dguendisch 

**Why is this needed**:
Faster reaction time of Gardener, improved user experience

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area usability
/kind enhancement
/priority normal

**What this PR does / why we need it**:
The gardenlet's shoot controller does now forget about the rate limiting when a shoot's deletion timestamp is set. This is to make starting deletion operations faster.

**Which issue(s) this PR fixes**:
Fixes #3050

**Release note**:

```improvement user
The gardenlet's shoot controller does now forget about the rate limiting when a shoot's deletion timestamp is set. This is to make starting deletion operations faster.
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/shoot_control.go [hunk 1]
```diff
@@ -52,12 +52,16 @@ import (
...
-func (c *Controller) shootAdd(obj interface{}) {
+func (c *Controller) shootAdd(obj interface{}, resetRateLimiting bool) {
 	key, err := cache.MetaNamespaceKeyFunc(obj)
 	if err != nil {
 		logger.Logger.Errorf("Couldn't get key for object %+v: %v", obj, err)
 		return
 	}
+
+	if resetRateLimiting {
+		c.getShootQueue(obj).Forget(key)
```
Comment (timuthy) [inline pkg/gardenlet/controller/shoot/shoot_control.go:63]: Is resetting really necessary? IIUC, `.Add(key)` adds the element immediately to the queue and `.AddRateLimited(key)` with a delay.

Comment (rfranzke) [reply pkg/gardenlet/controller/shoot/shoot_control.go:63]: Hm, I haven't studied all the internals of these queues, but if this would be true then this PR would be unnecessary.
The doc string of `Forget` states:

```golang
// Forget indicates that an item is finished being retried.  Doesn't matter whether it's for perm failing
// or for success, we'll stop the rate limiter from tracking it.  This only clears the `rateLimiter`, you
// still have to call `Done` on the queue.
```

I'm not calling `Done()` because a worker might be in the process of reconciling the shoot (my understanding is that if I'd be calling `Done()` then it might happen that two workers can simultaneously process a shoot). `Forget()` is doing exactly what I want - clearing the rate limiter.

**Review by timuthy — APPROVED** [review]
Okay, thanks for explaining. I tried to reproduce it:

- `Add()` adds the element immediately to the queue w/o rate limits due to the object composition:

  -- [rateLimitingType](https://github.com/kubernetes/client-go/blob/bef66adadf9a6371b5c114db0b95c12412c2414b/util/workqueue/rate_limiting_queue.go#L52) with [AddRateLimited()](https://github.com/kubernetes/client-go/blob/bef66adadf9a6371b5c114db0b95c12412c2414b/util/workqueue/rate_limiting_queue.go#L59) and [Forget()](https://github.com/kubernetes/client-go/blob/bef66adadf9a6371b5c114db0b95c12412c2414b/util/workqueue/rate_limiting_queue.go#L67), --> no `Add()` override
  ---- [delayingType](https://github.com/kubernetes/client-go/blob/master/util/workqueue/delaying_queue.go#L73) with [AddAfter()](https://github.com/kubernetes/client-go/blob/bef66adadf9a6371b5c114db0b95c12412c2414b/util/workqueue/delaying_queue.go#L160), --> no `Add()` override
  ------ [Type](https://github.com/kubernetes/client-go/blob/bef66adadf9a6371b5c114db0b95c12412c2414b/util/workqueue/queue.go#L65) with [Add()](https://github.com/kubernetes/client-go/blob/bef66adadf9a6371b5c114db0b95c12412c2414b/util/workqueue/queue.go#L108)



- I suspect in #3050, the first delete operation failed again and thus it was added by `AddRateLimited()` which already got an effective high rate limit.

/lgtm

**Review by timebertt — APPROVED** [review]
/lgtm
