### PR TITLE
Fixes token invalidation in cloud-config-downloader

### LINKED ISSUE #5674: Cloud-config-downloader can invalidate its own token and stop working
**How to categorize this issue?**

/area ops-productivity quality 
/kind bug

**What happened**:
A shoot cluster node has temporary issue with its root filesystem, i.e. there was no space left on the device. At this time, the `cloud-config-downloader` may try to update the token value on the filesystem https://github.com/gardener/gardener/blob/d4ab9bfc38133473741eae930f379f1082adf35e/pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/templates/scripts/download-cloud-config.tpl.sh#L61

But this fails with
```
/var/lib/cloud-config-downloader/download-cloud-config.sh: line 61: echo: write error: No space left on device
```

Since then, the `cloud-config-downloader` is failing to connect to the API of the shoot with
```
Could not retrieve the shoot access secret with name cloud-config-downloader with existing token
```

Probably the write attempt corrupted/deleted the content of the token file which prevented `cloud-config-downloader` to do its job.

**What you expected to happen**:
The `cloud-config-downloader` should be more cautious when it is writing to critical files, like the token file. It could write it to a second file (eventually on `tmpfs` filesystem) and then move it to the token file only if the content differs.

**How to reproduce it (as minimally and precisely as possible)**:
I have not tried, but it should be possible to reproduce the `no space left on device`, e.g. with `dd` a large file can be created.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.42
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

cc @vlerenc

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area robustness
/kind bug

**What this PR does / why we need it**:
Fixes a possible issue that could cause the cloud-config-downloader token to be invalidated if there any problems with the root file system of the node. 
Basically instead of directly trying to write the token data into the file specified for the token, the data will first be written to a temporary file. If that succeeds and the contents of the temporary file differ from the token file or the token file has still not been created, the temporary file will be `mv`-ed to the token file. Otherwise (if the contents are the same) the temporary file will be removed.

I managed to reproduce the error locally by writing creating a very large file and then trying to `echo` some content into another file. The `echo` commands fills the file until there is not enough space on the device and then exists before filling in the entire data. Echoing to a temp file and then using `mv` as suggested in the issue prevents this.

**Which issue(s) this PR fixes**:
Fixes #5674 

**Special notes for your reviewer**:
I have not yet tested this with an actual shoot yet.

**Release note**:

```bugfix operator
Fixed an issue that could cause the cloud-config-downloader to invalidate its credentials token if the node that it is currently running on has issues with the file system where the credentials token is stored (for example when the node runs out of disk space).
```

### CODE REVIEW

File: pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/downloader_test.go [hunk 1]
```diff
@@ -235,6 +235,17 @@ function extractDataKeyFromSecret() {
   echo "$1" | sed -rn "s/  $2: (.*)/\1/p" | base64 -d
 }
 
+function saveToDiskSafely() {
```
Comment (BeckerMax) [inline pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/downloader_test.go]:
```suggestion
function writeToDiskSafely() {
```

**Review by BeckerMax — COMMENTED** [review]
I am unsure about this fix.
Having a disk running out of space creates undefined behaviour. I am not sure if we should complicate our code for this corner case. Worst case we need to replace the node. WDYT?
Also: What if the [move operation](https://github.com/gardener/gardener/pull/5719/files#diff-41c32c3f006c6621520fcf088ecf032ecc55e2699c68c78955a82547f9ba5a14R288) corrupts the file. Meaning we were able to write to file_path.tmp but then the disk got full. At least I am not sure what is the defined behaviour of move if the disk runs full while a move operation is executed or is already full.

**Comment by plkokanov** [comment]
> Also: What if the [move operation](https://github.com/gardener/gardener/pull/5719/files#diff-41c32c3f006c6621520fcf088ecf032ecc55e2699c68c78955a82547f9ba5a14R288) corrupts the file. Meaning we were able to write to file_path.tmp but then the disk got full.

The mv operation  calls rename() as the file in this case is not moved between disks so it should not cause an issue if the discs fills up right before (or during) the call to mv. I'm not sure how much this differs between Linux implementations though.

As for the complexity - it's just a few lines of code after all and I think that is why we decided to address this issue in #5674
