### PR TITLE
Fix blocked `Shoot` operations if `spec.dns.providers.type` is omitted

### LINKED ISSUE #13490: Insufficient validation of shoot.spec.dns.provider
**How to categorize this issue?**

/area usability
/kind bug

**What happened**:
When creating a shoot with a custom domain but missing the provider type (`spec.dns.provider.type`), Gardener tries to create the shoot. Then, when the cluster is marked for deletion, it also fails to delete the cluster for the same reason:

```
log	{"controller":"shoot","error":"extension controllers missing or unready: map[DNSRecord/:{}]","level":"error","msg":"Waiting until all the required extension controllers are ready","name":"shoot-name","namespace":"garden-project-name","operation":"delete","
```

**What you expected to happen**:
Expect the Gardener API server to reject the malformed shoot spec.

**How to reproduce it (as minimally and precisely as possible)**:
see above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.132.1
- Kubernetes version (use `kubectl version`): n/a
- Cloud provider or hardware configuration: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by LucaBernstein**
**How to categorize this PR?**

/area usability
/kind bug

**What this PR does / why we need it**:
Remove `patchMergeKey` and `patchStrategy` from `shoot.spec.dns.providers` to unblock API server from finalizing if `type` is not set.  
Also, don't include `DNSRecord`s in the required extensions if their type is empty.

Having `type` as merge key anyway does not make too much sense as this prevents from configuring multiple providers of the same type.

Error with merge key set: `{"level":"error","ts":"2026-01-26T16:18:30.858Z","msg":"Waiting until all the required extension controllers are ready","controller":"shoot","namespace":"garden-local","name":"local","reconcileID":"88e0ac93-0a06-4055-a128-9fefa8d94ec4","operation":"delete","error":"extension controllers missing or unready: map[DNSRecord/:{} Extension/shoot-dns-service:{} Network/calico:{}]"...}`

**Which issue(s) this PR fixes**:
Fixes #13490

**Special notes for your reviewer**:
/cc @MartinWeindel @timuthy
FYI @rickardsjp 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/utils/gardener/shoot.go [hunk 1]
```diff
@@ -722,11 +722,11 @@ func ComputeRequiredExtensionsForShoot(shoot *gardencorev1beta1.Shoot, seed *gar
 		}
 	}
 
-	if internalDomain != nil && internalDomain.Provider != core.DNSUnmanaged {
+	if internalDomain != nil && internalDomain.Provider != core.DNSUnmanaged && internalDomain.Provider != "" {
```
Comment (timuthy) [inline pkg/utils/gardener/shoot.go]: This shouldn't be a valid use-case and is excluded by earlier functions in the call stack. It doesn't harm to check it here but a corresponding unit test would be confusing IMO. I would drop it.

File: pkg/utils/gardener/shoot.go [hunk 2]
```diff
@@ -722,11 +722,11 @@ func ComputeRequiredExtensionsForShoot(shoot *gardencorev1beta1.Shoot, seed *gar
...
 		requiredExtensions.Insert(ExtensionsID(extensionsv1alpha1.DNSRecordResource, internalDomain.Provider))
 	}
 
-	if externalDomain != nil && externalDomain.Provider != core.DNSUnmanaged {
+	if externalDomain != nil && externalDomain.Provider != core.DNSUnmanaged && externalDomain.Provider != "" {
```
Comment (timuthy) [inline pkg/utils/gardener/shoot.go:729]: Can you add a unit test pls?

**Review by timuthy — COMMENTED** [review]
Thanks for taking care!

File: pkg/apis/core/v1beta1/types_shoot.go [hunk 3]
```diff
@@ -542,10 +542,8 @@ type DNS struct {
 	//
 	// Deprecated: Configuring multiple DNS providers is deprecated and will be forbidden in a future release.
 	// Please use the DNS extension provider config (e.g. shoot-dns-service) for additional providers.
-	// +patchMergeKey=type
-	// +patchStrategy=merge
 	// +optional
-	Providers []DNSProvider `json:"providers,omitempty" patchStrategy:"merge" patchMergeKey:"type" protobuf:"bytes,2,rep,name=providers"`
+	Providers []DNSProvider `json:"providers,omitempty" protobuf:"bytes,2,rep,name=providers"`
```
Comment (tobschli) [inline pkg/apis/core/v1beta1/types_shoot.go:546]: I do not really understand how the `patchStrategy` is the blocker here.
Instead of `merge`, to which strategy does this default then?

**Review by tobschli — COMMENTED** [review]
Thank you for the PR!
Just one question, otherwise `lgtm`

File: pkg/apis/core/v1beta1/types_shoot.go (hunk 3 above)
Comment (LucaBernstein) [reply pkg/apis/core/v1beta1/types_shoot.go:546]: With the `patchStrategy` + the `patchMergeKey` the API server interprets the list as a map with the `type` as the key. The problem: `type` is optional, so if it is empty, the merge fails (see also the error log excerpt in the PR description).

Without the `merge` the list will be replaced.

**Comment by MartinWeindel** [comment]
lgtm
Thanks for taking care!

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve

File: pkg/apis/core/v1beta1/types_shoot.go (hunk 3 above)
Comment (tobschli) [reply pkg/apis/core/v1beta1/types_shoot.go:546]: Ahhh, got it! Thank you very much for the explanation ❤️
