### PR TITLE
Enhance SeedAuthorizer to allow `DELETE` requests if resource does not exist in the system

### LINKED ISSUE #5082: SeedAuthorizer: Do not allow `DELETE` for BackupBuckets unconditionally
**How to categorize this issue?**

/area quality security
/kind bug

**What happened**:
From the current handling in the SeedAuthorizer, it seems that it always allows `DELETE` verbs and does not perform relationship checks.

https://github.com/gardener/gardener/blob/3678f65531c172e56fffc65d7c27d82559203513/pkg/admissioncontroller/webhooks/auth/seed/authorizer.go#L107

**What you expected to happen**:
TO do not allow `DELETE` verb unconditionally.

**How to reproduce it (as minimally and precisely as possible)**:
(I haven't tried myself but the following steps would do the trick)

1. With the identity of gardenlet `gardener.cloud:system:seed:foo` try to delete a BackupBucket that belongs to another Seed (`spec.seedName=bar`)

2. Make sure that the above deletion is not rejected with `no relationship found between seed 'foo' and this object`

**Environment**:

- Gardener version: v1.36.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### LINKED ISSUE #5083: SeedAuthorizer: Do not reject `DELETE` requests if the obj is not found (?)
**How to categorize this issue?**

/area security
/kind enhancement

**What would you like to be added**:
In many places in our code we use the strategy "delete and ignore not found errors". But such delete request can be denied by the SeedAuthorizer with reason `no relationship found between seed 'foo' and this object`. That's why to prevent this issue we have to switch to a strategy "get and delete if found". As the "get and delete if found" strategy is not intuitive, we were wondering whether the SeedAuthorizer can be improved to do not fail such requests. (If applicable, we can also check the handling of the NodeAuthorizer and kubelet for such cases).

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind enhancement
/squash

**What this PR does / why we need it**:
With this PR, the SeedAuthorizer is enhanced to allow `DELETE` requests if resource does not exist in the system. This is to prevent special client handling (as introduced in https://github.com/gardener/gardener/pull/5066, for example) which anyways would not necessarily work in all cases.

Hence, apart from above, the PR reverts such special handling that was introduced in the `backupentry` component.

Additionally, unconditional `DELETE`s are no longer allowed for `BackupBucket`s (which only were introduced to work around #5083).

**Which issue(s) this PR fixes**:
Fixes #5082
Fixes #5083

**Release note**:

```bugfix operator
A bug in the SeedAuthorizer has been fixed which allowed gardenlets to unconditionally delete `BackupBucket`s.
```
```improvement developer
The SeedAuthorizer does now allow `DELETE` requests if the resource does not exist in the system.
```

### CODE REVIEW

File: pkg/operation/botanist/component/backupentry/backupentry_test.go [hunk 1]
```diff
@@ -293,13 +293,12 @@ var _ = Describe("BackupEntry", func() {
 
 	Describe("#Destroy", func() {
 		It("should not return error when it's not found", func() {
-			Expect(defaultDepWaiter.Destroy(ctx)).To(BeNil())
+			Expect(defaultDepWaiter.Destroy(ctx)).To(Succeed())
 		})
 
 		It("should not return error when it's deleted successfully", func() {
 			Expect(c.Create(ctx, expected)).ToNot(HaveOccurred(), "creating infrastructure succeeds")
```
Comment (stoyanr) [inline pkg/operation/botanist/component/backupentry/backupentry_test.go]: Nit: Not really related to this PR, but still ...
```suggestion
			Expect(c.Create(ctx, expected)).ToNot(HaveOccurred(), "creating BackupEntry succeeds")
```

File: pkg/admissioncontroller/webhooks/auth/seed/authorizer_test.go [hunk 2]
```diff
@@ -660,7 +674,7 @@ var _ = Describe("Seed", func() {
 				}
 			})
 
-			DescribeTable("should allow without consulting the graph because verb is get, list, watch, create",
+			DescribeTable("should allow without consulting the graph because verb is get, list, watch, create, delete",
```
Comment (stoyanr) [inline pkg/admissioncontroller/webhooks/auth/seed/authorizer_test.go]: Why add `delete` if it's actually being removed?
```suggestion
			DescribeTable("should allow without consulting the graph because verb is get, list, watch, create",
```

**Review by stoyanr — CHANGES_REQUESTED** [review]
Looks quite good, only few minor comments.

@rfranzke Ideally I would also test this locally but this is not yet possible due to an issue with the current dev environment, correct?

**Comment by rfranzke** [comment]
@stoyanr There is #5086 that you could potentially rebase on to try it out locally. Though, this only works if you use the nodeless dev setup (if you use kind/minikube then there is no support for SeedAuthorizer at all).

**Review by timuthy — APPROVED** [review]
/lgtm

**Review by stoyanr — APPROVED** [review]
/lgtm
