### PR TITLE
Forbid specifying an extension of same type more than once

### LINKED ISSUE #8446: gardener-apiserver: Consider forbidding specifying more than 1 extension from the same type for a Shoot
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
Currently the gardener-apiserver allows to specify 2 extensions from the same type:
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot

spec:
  extensions:
  - type: registry-cache
    providerConfig:
      apiVersion: registry.extensions.gardener.cloud/v1alpha1
      kind: RegistryConfig
      caches:
      - upstream: docker.io
        size: 500Mi
  - type: registry-cache
    providerConfig:
      apiVersion: registry.extensions.gardener.cloud/v1alpha1
      kind: RegistryConfig
      caches:
      - upstream: quay.io
        garbageCollectionEnabled: false
```

gardenlet set the Extension name to the extension type. See https://github.com/gardener/gardener/blob/2e4617c3de1a4491a6287788266d45a7fc8044e2/pkg/operation/botanist/extension.go#L90-L104

The above Shoot spec actually was created successfully. It deployed a single Extension to the Seed with the providerConfig of the 2nd extension from the Shoot spec:

```
% k -n shoot--local--local get extensions.extensions.gardener.cloud registry-cache -o yaml

spec:
  providerConfig:
    apiVersion: registry.extensions.gardener.cloud/v1alpha1
    caches:
    - garbageCollectionEnabled: false
      upstream: quay.io
    kind: RegistryConfig
  type: registry-cache
```

The part that makes possible the 2nd extension to overwrite the 1st one:
https://github.com/gardener/gardener/blob/809fd994e01455eb9f67af35f195bab76ebade2f/pkg/component/extensions/extension/extension.go#L396-L426

**What you expected to happen**:
I would say that we should rather forbid specifying the same extension more than once instead of having one of the configs overwriting the other one.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.79.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
This PR enhances shoot validation to forbid specifying an extension of the same type more than once. 
For more details - https://github.com/gardener/gardener/issues/8446

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/8446

**Special notes for your reviewer**:

**Release note**:

```bugfix user
A bug has been fixed which was allowing users to specify an extension of the same type in `.spec.extensions[].type` more than once in the `Shoot` API.
```

### CODE REVIEW

**Review by shafeeqes — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
For existing `Shoot`s, should we patch out all but the last occurrence of duplicate types?

File: pkg/registry/core/shoot/strategy.go [hunk 1]
```diff
@@ -80,6 +82,9 @@ func (shootStrategy) PrepareForUpdate(_ context.Context, obj, old runtime.Object
 	if mustIncreaseGeneration(oldShoot, newShoot) {
 		newShoot.Generation = oldShoot.Generation + 1
 	}
+
+	// TODO(acumino): Drop this in gardener v1.84 release.
+	removeDuplicateExtension(newShoot)
```
Comment (shafeeqes) [inline pkg/registry/core/shoot/strategy.go]: Nit
```suggestion
	removeDuplicateExtensions(newShoot)
```

File: pkg/registry/core/shoot/strategy.go [hunk 2]
```diff
@@ -166,6 +171,25 @@ func removeForbiddenFinalizers(shoot *core.Shoot) {
 	shoot.Finalizers = finalizers
 }
 
+func removeDuplicateExtension(shoot *core.Shoot) {
+	if len(shoot.Spec.Extensions) > 1 {
```
Comment (shafeeqes) [inline pkg/registry/core/shoot/strategy.go:177]:
```
	if len(shoot.Spec.Extensions) < 2 {
            return
         }
```
to avoid nesting

File: pkg/registry/core/shoot/strategy.go [hunk 3]
```diff
@@ -166,6 +171,25 @@ func removeForbiddenFinalizers(shoot *core.Shoot) {
...
+		extensionsType := map[string]core.Extension{}
```
Comment (shafeeqes) [inline pkg/registry/core/shoot/strategy.go]:
```suggestion
		extensionsType := make(map[string]core.Extension, len(shoot.Spec.Extensions))
```
Maybe call it `typeToExtension` map, or set?

File: pkg/registry/core/shoot/strategy.go (hunk 2 above)
Comment (acumino) [reply pkg/registry/core/shoot/strategy.go:177]: This doesn't reduce anything. I will keep the current implementation.

Comment (rfranzke) [reply pkg/registry/core/shoot/strategy.go:177]: It's not very important, but it does, right? All the L176-L189 will be indented one level less.

File: pkg/registry/core/shoot/strategy.go [hunk 4]
```diff
@@ -80,6 +82,9 @@ func (shootStrategy) PrepareForUpdate(_ context.Context, obj, old runtime.Object
 	if mustIncreaseGeneration(oldShoot, newShoot) {
 		newShoot.Generation = oldShoot.Generation + 1
 	}
+
+	// TODO(acumino): Drop this in gardener v1.84 release.
```
Comment (rfranzke) [inline pkg/registry/core/shoot/strategy.go]:
```suggestion
	// TODO(acumino): Drop this after v1.83 has been released.
```

File: pkg/registry/core/shoot/strategy.go (hunk 2 above)
Comment (acumino) [reply pkg/registry/core/shoot/strategy.go:177]: My idea is that we `if` will be executed once in either of the cases.  Also, it's not like indenting it in other ways increases the readability of code or any other improvement. That is why I am a bit hesitant to change it.

Comment (rfranzke) [reply pkg/registry/core/shoot/strategy.go:177]: 🤷🏻

File: pkg/registry/core/shoot/strategy.go [hunk 5]
```diff
@@ -80,6 +82,9 @@ func (shootStrategy) PrepareForUpdate(_ context.Context, obj, old runtime.Object
 	if mustIncreaseGeneration(oldShoot, newShoot) {
 		newShoot.Generation = oldShoot.Generation + 1
 	}
+
+	// TODO(acumino): Drop this after v1.83 has been released.
+	removeDuplicateExtensions(newShoot)
```
Comment (shafeeqes) [inline pkg/registry/core/shoot/strategy.go:89]: How about, 
```suggestion
	if len(shoot.Spec.Extensions) > 1 {
        	removeDuplicateExtensions(newShoot)
        }
```
😉

**Review by shafeeqes — COMMENTED** [review]
Although mentioning the extensions twice is a mistake since we allowed it in the past, Is there a chance that this could break some shoot creation setups of users? Should we also call this function in `PrepareForCreate` for a few releases, similar to `removeFinalizersOnCreation` function?

File: pkg/registry/core/shoot/strategy.go (hunk 5 above)
Comment (acumino) [reply pkg/registry/core/shoot/strategy.go:89]: The current one is fine 😄

**Comment by acumino** [comment]
> Although mentioning the extensions twice is a mistake since we allowed it in the past, Is there a chance that this could break some shoot creation setups of users? Should we also call this function in `PrepareForCreate` for a few releases, similar to `removeFinalizersOnCreation` function?

Probably not If somebody would have done it consciously then it is wrong from the user's end and they should adapt it ASAP and the gardener should not clean it silently.

**Comment by shafeeqes** [comment]
I agree it's wrong, but it could still be breaking for them. WDYT @rfranzke ?

**Comment by rfranzke** [comment]
I understand the concerns, but I'm fine with both approaches. If @acumino as author prefers to not include it in `PrepareForCreate` (whilst arguing that such `Shoot` resources should be fixed ASAP to prevent misconfiguration), I think it's fair to proceed like this as this issue is probably rather theoretical (I don't expect many affected shoots). It would be a different story if we changed validation for a more prominent field.
So, should we proceed then @shafeeqes ?

**Comment by acumino** [comment]
> I understand the concerns, but I'm fine with both approaches. If @acumino as author prefers to not include it in `PrepareForCreate` (whilst arguing that such `Shoot` resources should be fixed ASAP to prevent misconfiguration), I think it's fair to proceed like this as this issue is probably rather theoretical (I don't expect many affected shoots). It would be a different story if we changed validation for a more prominent field. So, should we proceed then @shafeeqes ?

I added `removeDuplicateExtensions` in `PrepareForCreate` also.

**Comment by shafeeqes** [comment]
Thanks!
/lgtm
/approve
