### PR TITLE
Fix DNS lookup for exisiting records

### LINKED ISSUE #511: Perform Terraform DNS job reconciliation only if needed
When we create/reconcile DNS records we already have code that should check whether we actually have to start the Terraform DNS job or not (if a "`nslookup <host>`" already results in the desired record name we don't want to do anything):

(From: https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/dns.go#L65-L83)
```golang
	// If the DNS record is already registered properly then we skip the reconciliation to avoid running into
	// cloud provider rate limits.
	switch targetType {
	case "hostname":
		if utils.LookupDNSHostCNAME(name) == fmt.Sprintf("%s.", target) {
			b.Logger.Infof("Skipping DNS record registration because '%s' already points to '%s'", name, target)
			// Clean up possible existing Terraform job/pod artifacts from previous runs
			return tf.EnsureCleanedUp()
		}
	case "ip":
		values := utils.LookupDNSHost(name)
		for _, v := range values {
			if v == target {
				b.Logger.Infof("Skipping DNS record registration because '%s' already points to '%s'", name, target)
				// Clean up possible existing Terraform job/pod artifacts from previous runs
				return tf.EnsureCleanedUp()
			}
		}
	}
```

However, this piece of code seems not do work properly/reliable. Let's improve it to reduce the number of calls we do against the cloud API of the DNS provider.

### PR DESCRIPTION
**Pull request by zanetworker**
**What this PR does / why we need it**:
Previously Terraform validation was executed for every external-dns
lookup even though the DNS records were already available. This commit
fixes this issue.

**Which issue(s) this PR fixes**:
Fixes #511.

**Special notes for your reviewer**:

**Release note**:
```improvement operator
Terraform DNS validation is now executed only when necessary in order to reduce API calls to the cloud APIs.
```

### CODE REVIEW

File: pkg/operation/botanist/dns.go [hunk 1]
```diff
@@ -66,13 +66,24 @@ func (b *Botanist) DeployDNSRecord(terraformerPurpose, name, target string, purp
...
+		}
+		if cname == fmt.Sprintf("%s.", target) {
 			b.Logger.Infof("Skipping DNS record registration because '%s' already points to '%s'", name, target)
 			// Clean up possible existing Terraform job/pod artifacts from previous runs
 			return tf.EnsureCleanedUp()
 		}
 	case "ip":
-		values := utils.LookupDNSHost(name)
+		values, err := utils.LookupDNSHost(name)
+		b.Logger.Infof("IP DNS Values for %s are: %s", name, values)
```
Comment (rfranzke) [inline pkg/operation/botanist/dns.go]: As discussed: Let's remove this log message

File: pkg/utils/dns.go [hunk 2]
```diff
@@ -15,47 +15,109 @@
...
+	addr := net.ParseIP(record)
+
+	var nsRecords []string
+	if addr != nil {
+		// the records does not need a look query, it is already in its final form
+		nsRecords = []string{record}
+	} else {
+		lookupResult, err := lookUPDNSRecord(record, dns.TypeA)
+		if err != nil {
+			return []string{}, err
```
Comment (rfranzke) [inline pkg/utils/dns.go]: `return nil, err`

File: pkg/utils/dns.go [hunk 3]
```diff
@@ -15,47 +15,109 @@
...
 
 // LookupDNSHost performs a DNS lookup for the given <domain>. In case of success, it will return the list
 // of records. If the domain is not resolvable, it will return nil.
-func LookupDNSHost(domain string) []string {
-	if nsRecords, err := net.LookupHost(domain); err == nil {
+func LookupDNSHost(record string) ([]string, error) {
+	addr := net.ParseIP(record)
+
+	var nsRecords []string
+	if addr != nil {
```
Comment (rfranzke) [inline pkg/utils/dns.go]: Let's completely remove this check.

File: pkg/utils/dns.go [hunk 4]
```diff
@@ -15,47 +15,109 @@
...
+		// the records does not need a look query, it is already in its final form
+		nsRecords = []string{record}
+	} else {
```
Comment (rfranzke) [inline pkg/utils/dns.go]: Not needed anymore (see suggestion above).

File: pkg/utils/dns.go [hunk 5]
```diff
@@ -15,47 +15,109 @@
...
+		}
+		if r == nil || r.Rcode == dns.RcodeNameError || r.Rcode == dns.RcodeSuccess {
+			return r, err
+		}
+	}
+	return nil, errors.New("No name server to answer the question")
+}
+
+// lookUPDNSRecord filters results from a dnsQuery and returns a slice of valid RR records or error in case of failure
+func lookUPDNSRecord(domain string, qtype uint16) (*[]string, error) {
```
Comment (rfranzke) [inline pkg/utils/dns.go]:
```suggestion
func lookUPDNSRecord(domain string, qtype uint16) ([]string, error) {
```

File: pkg/utils/dns.go [hunk 6]
```diff
@@ -15,47 +15,109 @@
...
+	r, err := dnsQuery(dns.Fqdn(domain), qtype)
+	if err != nil || r == nil {
+		return nil, fmt.Errorf("cannot retrieve the list of name servers for %s: %s", dns.Fqdn(domain), err.Error())
```
Comment (rfranzke) [inline pkg/utils/dns.go]:
```suggestion
		return nil, fmt.Errorf("cannot retrieve the list of name servers for %s: %+v", dns.Fqdn(domain), err)
```

File: pkg/utils/dns.go [hunk 7]
```diff
@@ -15,47 +15,109 @@
...
+	}
+
+	if qtype == dns.TypeCNAME {
+		if r.Rcode == dns.RcodeNameError {
```
Comment (rfranzke) [inline pkg/utils/dns.go]:
```suggestion
		if if qtype == dns.TypeCNAME && r.Rcode == dns.RcodeNameError {
```

File: pkg/utils/dns.go [hunk 8]
```diff
@@ -15,47 +15,109 @@
...
-			if nsRecords := LookupDNSHost(domain); len(nsRecords) > 0 {
-				nsRecord = nsRecords[0]
-				return true, nil
-			}
-			logger.Logger.Infof("Waiting for DNS name %s to be resolvable...", domain)
-			return false, nil
-		})
-	)
-	return nsRecord, err
+// dnsQuery initializes the client as well as the message for DNS and initiates the DNS Query and
```
Comment (rfranzke) [inline pkg/utils/dns.go]: and?

File: pkg/utils/dns.go [hunk 9]
```diff
@@ -15,47 +15,109 @@
...
+		Question: make([]dns.Question, 1),
+	}
+
+	localClient := &dns.Client{
+		ReadTimeout: 5 * time.Second,
+	}
+
+	conf, err := dns.ClientConfigFromFile("/etc/resolv.conf")
+	if err != nil || conf == nil {
+		return nil, fmt.Errorf("config file might be empty, or something went wront with initiating client: %s", err.Error())
```
Comment (rfranzke) [inline pkg/utils/dns.go]: typo

```suggestion
		return nil, fmt.Errorf("config file might be empty, or something went wrong with initiating client: %+v", err)
```

File: pkg/utils/dns.go [hunk 10]
```diff
@@ -15,47 +15,109 @@
...
+	}
+
+	localMessage.SetQuestion(queryName, queryType)
+
+	for _, server := range conf.Servers {
+		r, _, err := localClient.Exchange(localMessage, server+":"+conf.Port)
```
Comment (rfranzke) [inline pkg/utils/dns.go]: `fmt.Sprintf`?

**Review by rfranzke — CHANGES_REQUESTED** [review]

**Review by rfranzke — APPROVED** [review]
/lgtm
