### PR TITLE
gardenlet: Prevent CA bundle on the Nodes to contain wrong certificates when worker pool specifies custom CA bundle

### LINKED ISSUE #12140: The `caBundle` in `operatingsystemconfig` component is not generated correctly
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
It seems that the source of the problem is here:

https://github.com/gardener/gardener/blob/7e4fae78e422121bea35d931a80a012a60d313a8/pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L674-L681

Tow go routines concurrently update the `caBundle` and the number of `worker.CABundle` varies between 1 and 2.

**What you expected to happen**:
The `caBundle` to contain the expected certificates.

**How to reproduce it (as minimally and precisely as possible)**:

Start local setup and create a Shoot with `spec.provider.workers[].caBundle` defined.
Then check the `/var/lib/ca-certificates-local/ROOTcerts.crt` file in `gardener-node-agent-local` OSC. 
It contains worker `caBundle` once or twice.
Repeated shoot reconciliations cause the worker caBundle count to fluctuate between 1 and 2.

The situation gets worse if there are multiple worker pools with `caBundle` defined.

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version: v1.119.0
- Kubernetes version (use `kubectl version`): v1.32.4
- Cloud provider or hardware configuration: local
- Others: N/A

### PR DESCRIPTION
**Pull request by dimitar-kostadinov**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
If the [Worker.CABundle](https://github.com/gardener/gardener/blob/5cfbb5b1b195e60f9080c9eb09811764f1810bc4/pkg/apis/core/v1beta1/types_shoot.go#L1595)  is set in the Shoot spec, the generation of the `CABundle` in the `operatingsystemconfig` is incorrect. This PR solves the problem by using a new local variable, so concurrent modifications are no longer possible.

**Which issue(s) this PR fixes**:
Fixes #12140 

**Special notes for your reviewer**:
N/A

**Release note**:

```bugfix user
gardenlet: An issue causing the CA bundle on the Nodes to contain wrong certificates when a worker specifies a custom CA bundle (`spec.provider.workers[].caBundle`) is now fixed.
```

### CODE REVIEW

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go [hunk 1]
```diff
@@ -671,12 +671,15 @@ func (o *operatingSystemConfig) newDeployer(version int, osc *extensionsv1alpha1
 		criName = extensionsv1alpha1.CRIName(worker.CRI.Name)
 	}
 
-	caBundle := o.values.CABundle
+	var caBundle *string
+	if o.values.CABundle != nil {
```
Comment (ialidzhikov) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: The `CABundle` value is of type `*string`. https://github.com/gardener/gardener/issues/12140 is caused by reuse of the same pointer for all OSCs.

The fix would be more elegant if we could make the `CABundle` value of type `string`.

The `CABundle` value is set by the corresponding setter func: https://github.com/gardener/gardener/blob/43aefc1b1b14854845ffccf55acdf9693fba1a34/pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L644-L647

The single usage of this func is in: https://github.com/gardener/gardener/blob/63cb5ea67f7e3882851d76db111816ed32b04ec7/pkg/gardenlet/operation/botanist/operatingsystemconfig.go#L97

`getOperatingSystemConfigCABundle` is being used to set the  `CABundle`.

The func accept `clusterCASecret.Data[secretsutils.DataKeyCertificateBundle])` where `clusterCASecret` is the `ca` Secret fetched by the secrets manager: https://github.com/gardener/gardener/blob/63cb5ea67f7e3882851d76db111816ed32b04ec7/pkg/gardenlet/operation/botanist/operatingsystemconfig.go#L91-L94

`getOperatingSystemConfigCABundle` looks as follows: https://github.com/gardener/gardener/blob/63cb5ea67f7e3882851d76db111816ed32b04ec7/pkg/gardenlet/operation/botanist/operatingsystemconfig.go#L143-L159

`clusterCABundle` will be always non-empty.  There are many places where we fetch the `bundle.crt` key from the `ca` Secret unconditionally across the code-base:
- caBundle which get set in the vpa-webhook webhookClientConfig: https://github.com/gardener/gardener/blob/2e5ee0343e812d15ae2101459d7e50d3a6c5365c/pkg/component/autoscaling/vpa/vpa.go#L110-L115 and https://github.com/gardener/gardener/blob/e284b443596d258077b264d33511de5365c5da42/pkg/component/autoscaling/vpa/general.go#L183-L185
- usage in kube-proxy: https://github.com/gardener/gardener/blob/fa0bd21f02d1548dff84df6ac830a4ac4d2a18f3/pkg/gardenlet/operation/botanist/kubeproxy.go#L52-L64
- ...

The `getOperatingSystemConfigCABundle` will always return a non-empty string. 

Hence, I don't see a reason why the `CABundle` value has to be of type `*string`.

I would suggest to make the `CABundle` value of type `string` and in this way avoid these pointer workarounds that we did to prevent the reuse of the same pointer for all OSCs.

@rfranzke could you confirm my observations from above? Thanks in advance!

Comment (ialidzhikov) [reply pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: A diff that I build against the master branch:

```diff
diff --git a/pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go b/pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
index c2534ba4fa..dd176b3cab 100644
--- a/pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
+++ b/pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
@@ -84,7 +84,7 @@ type Interface interface {
 	// SetAPIServerURL sets the APIServerURL value.
 	SetAPIServerURL(string)
 	// SetCABundle sets the CABundle value.
-	SetCABundle(*string)
+	SetCABundle(string)
 	// SetCredentialsRotationStatus sets the credentials rotation status
 	SetCredentialsRotationStatus(*gardencorev1beta1.ShootCredentialsRotation)
 	// SetSSHPublicKeys sets the SSHPublicKeys value.
@@ -123,7 +123,7 @@ type InitValues struct {
 // OriginalValues are configuration values required for the 'reconcile' OperatingSystemConfigPurpose.
 type OriginalValues struct {
 	// CABundle is the bundle of certificate authorities that will be added as root certificates.
-	CABundle *string
+	CABundle string
 	// ClusterDNSAddresses are the addresses for in-cluster DNS.
 	ClusterDNSAddresses []string
 	// ClusterDomain is the Kubernetes cluster domain.
@@ -642,7 +642,7 @@ func (o *operatingSystemConfig) SetAPIServerURL(apiServerURL string) {
 }
 
 // SetCABundle sets the CABundle value.
-func (o *operatingSystemConfig) SetCABundle(val *string) {
+func (o *operatingSystemConfig) SetCABundle(val string) {
 	o.values.CABundle = val
 }
 
@@ -673,11 +673,7 @@ func (o *operatingSystemConfig) newDeployer(version int, osc *extensionsv1alpha1
 
 	caBundle := o.values.CABundle
 	if worker.CABundle != nil {
-		if caBundle == nil {
-			caBundle = worker.CABundle
-		} else {
-			*caBundle = fmt.Sprintf("%s\n%s", *caBundle, *worker.CABundle)
-		}
+		caBundle = fmt.Sprintf("%s\n%s", caBundle, *worker.CABundle)
 	}
 
 	clusterCASecret, found := o.secretsManager.Get(v1beta1constants.SecretNameCACluster)
@@ -816,7 +812,7 @@ type deployer struct {
 	apiServerURL string
 
 	// original values
-	caBundle                                    *string
+	caBundle                                    string
 	clusterCASecretName                         string
 	clusterCABundle                             []byte
 	clusterDNSAddresses                         []string
diff --git a/pkg/component/extensions/operatingsystemconfig/original/components/components.go b/pkg/component/extensions/operatingsystemconfig/original/components/components.go
index a71de89d0d..db39a0e4d7 100644
--- a/pkg/component/extensions/operatingsystemconfig/original/components/components.go
+++ b/pkg/component/extensions/operatingsystemconfig/original/components/components.go
@@ -24,7 +24,7 @@ type Component interface {
 // Context contains configuration for the components.
 type Context struct {
 	Key                     string
-	CABundle                *string
+	CABundle                string
 	ClusterDNSAddresses     []string
 	ClusterDomain           string
 	CRIName                 extensionsv1alpha1.CRIName
diff --git a/pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go b/pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
index c5aeb36919..1524111c55 100644
--- a/pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
+++ b/pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/component.go
@@ -57,10 +57,7 @@ func (component) Name() string {
 }
 
 func (component) Config(ctx components.Context) ([]extensionsv1alpha1.Unit, []extensionsv1alpha1.File, error) {
-	var caBundle []byte
-	if ctx.CABundle != nil {
-		caBundle = []byte(*ctx.CABundle)
-	}
+	caBundle := []byte(ctx.CABundle)
 
 	var additionalTokenSyncConfigs []nodeagentconfigv1alpha1.TokenSecretSyncConfig
 	if ctx.ValitailEnabled {
diff --git a/pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go b/pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
index 271e03ea58..0aeba08b0a 100644
--- a/pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
+++ b/pkg/component/extensions/operatingsystemconfig/original/components/rootcertificates/component.go
@@ -56,17 +56,13 @@ func (component) Name() string {
 }
 
 func (component) Config(ctx components.Context) ([]extensionsv1alpha1.Unit, []extensionsv1alpha1.File, error) {
-	if ctx.CABundle == nil {
-		return nil, nil, nil
-	}
-
 	updateLocalCaCertificatesScriptFile, err := updateLocalCACertificatesScriptFile()
 	if err != nil {
 		return nil, nil, err
 	}
 
 	const pathEtcSSLCerts = "/etc/ssl/certs"
-	var caBundleBase64 = utils.EncodeBase64([]byte(*ctx.CABundle))
+	var caBundleBase64 = utils.EncodeBase64([]byte(ctx.CABundle))
 
 	updateCACertsFiles := []extensionsv1alpha1.File{
 		updateLocalCaCertificatesScriptFile,
diff --git a/pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go b/pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
index 90b3295db8..2218685ba4 100644
--- a/pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
+++ b/pkg/component/extensions/operatingsystemconfig/original/components/valitail/config.go
@@ -69,10 +69,7 @@ func getValitailConfigurationFile(ctx components.Context) (extensionsv1alpha1.Fi
 }
 
 func getValitailCAFile(ctx components.Context) extensionsv1alpha1.File {
-	var cABundle []byte
-	if ctx.CABundle != nil {
-		cABundle = []byte(*ctx.CABundle)
-	}
+	caBundleBase64 := utils.EncodeBase64([]byte(ctx.CABundle))
 
 	return extensionsv1alpha1.File{
 		Path:        PathCACert,
@@ -80,7 +77,7 @@ func getValitailCAFile(ctx components.Context) extensionsv1alpha1.File {
 		Content: extensionsv1alpha1.FileContent{
 			Inline: &extensionsv1alpha1.FileContentInline{
 				Encoding: "b64",
-				Data:     utils.EncodeBase64(cABundle),
+				Data:     caBundleBase64,
 			},
 		},
 	}
diff --git a/pkg/gardenlet/operation/botanist/operatingsystemconfig.go b/pkg/gardenlet/operation/botanist/operatingsystemconfig.go
index d37ba1b88b..7a89d9210d 100644
--- a/pkg/gardenlet/operation/botanist/operatingsystemconfig.go
+++ b/pkg/gardenlet/operation/botanist/operatingsystemconfig.go
@@ -92,9 +92,13 @@ func (b *Botanist) DeployOperatingSystemConfig(ctx context.Context) error {
 	if !found {
 		return fmt.Errorf("secret %q not found", v1beta1constants.SecretNameCACluster)
 	}
+	clusterCABundle, found := clusterCASecret.Data[secretsutils.DataKeyCertificateBundle]
+	if !found {
+		return fmt.Errorf("key %q not found in secret %q", secretsutils.DataKeyCertificateBundle, v1beta1constants.SecretNameCACluster)
+	}
 
 	b.Shoot.Components.Extensions.OperatingSystemConfig.SetAPIServerURL(fmt.Sprintf("https://%s", b.Shoot.ComputeOutOfClusterAPIServerAddress(true)))
-	b.Shoot.Components.Extensions.OperatingSystemConfig.SetCABundle(b.getOperatingSystemConfigCABundle(clusterCASecret.Data[secretsutils.DataKeyCertificateBundle]))
+	b.Shoot.Components.Extensions.OperatingSystemConfig.SetCABundle(b.getOperatingSystemConfigCABundle(clusterCABundle))
 
 	shoot := b.Shoot.GetInfo()
 	if shoot.Status.Credentials != nil {
@@ -140,22 +144,16 @@ func (b *Botanist) DeployOperatingSystemConfig(ctx context.Context) error {
 	return b.Shoot.Components.Extensions.OperatingSystemConfig.Deploy(ctx)
 }
 
-func (b *Botanist) getOperatingSystemConfigCABundle(clusterCABundle []byte) *string {
+func (b *Botanist) getOperatingSystemConfigCABundle(clusterCABundle []byte) string {
 	var caBundle string
 
 	if cloudProfileCaBundle := b.Shoot.CloudProfile.Spec.CABundle; cloudProfileCaBundle != nil {
 		caBundle = *cloudProfileCaBundle
 	}
 
-	if len(clusterCABundle) != 0 {
-		caBundle = fmt.Sprintf("%s\n%s", caBundle, clusterCABundle)
-	}
-
-	if caBundle == "" {
-		return nil
-	}
+	caBundle = fmt.Sprintf("%s\n%s", caBundle, clusterCABundle)
 
-	return &caBundle
+	return caBundle
 }
 
 // exposed for testing

```

Comment (rfranzke) [reply pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go]: Sounds reasonable, thank you @ialidzhikov

**Review by ialidzhikov — COMMENTED** [review]
```
make generate needs to be run:
 M pkg/component/extensions/operatingsystemconfig/mock/mocks.go
make: *** [Makefile:1[5](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/12150/pull-gardener-unit/1925475627566108672#1:build-log.txt%3A5)1: check-generate] Error 1
```

@dimitar-kostadinov , could you address?

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go [hunk 2]
```diff
@@ -782,6 +787,65 @@ var _ = Describe("OperatingSystemConfig", func() {
...
+					}
+					return nil
+				}
+
+				BeforeEach(func() {
+					values.OriginalValues.CABundle = "foo"
+					values.Workers[0].CABundle = ptr.To("bar")
+					values.Workers[1].CABundle = ptr.To("baz")
+				})
+				JustBeforeEach(func() {
```
Comment (ialidzhikov) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]:
```suggestion
				})

				JustBeforeEach(func() {
```

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go [hunk 3]
```diff
@@ -782,6 +787,65 @@ var _ = Describe("OperatingSystemConfig", func() {
...
+						Expect(content).NotTo(BeNil())
+						if worker == "worker1" {
+							Expect(*content).To(Equal("foo\nbar"))
+						} else {
+							Expect(*content).To(Equal("foo\nbaz"))
+						}
+					}
+				})
+
+				When("only original values CABundle is set", func() {
```
Comment (ialidzhikov) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]: Can this be the first test in the Context as it is the simpler test case (when no worker CA bundle is set)?

Comment (ialidzhikov) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]:
```suggestion
				When("worker CA bundle is not set", func() {
```

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go [hunk 4]
```diff
@@ -782,6 +787,65 @@ var _ = Describe("OperatingSystemConfig", func() {
...
+					BeforeEach(func() {
+						values.Workers[0].CABundle = nil
+						values.Workers[1].CABundle = nil
+					})
+					It("should contains only original CABundle value", func() {
```
Comment (ialidzhikov) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]:
```suggestion
					It("should contain only the provided CA bundle", func() {
```

File: pkg/gardenlet/operation/botanist/operatingsystemconfig.go [hunk 5]
```diff
@@ -93,8 +93,13 @@ func (b *Botanist) DeployOperatingSystemConfig(ctx context.Context) error {
 		return fmt.Errorf("secret %q not found", v1beta1constants.SecretNameCACluster)
 	}
```
Comment (ialidzhikov) [inline pkg/gardenlet/operation/botanist/operatingsystemconfig.go]: IMO, we could combine them as they are related logically and the final goal of this block is to fetch the `clusterCABundle`.

```suggestion
```

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go [hunk 6]
```diff
@@ -782,6 +787,65 @@ var _ = Describe("OperatingSystemConfig", func() {
...
+				BeforeEach(func() {
+					values.OriginalValues.CABundle = "foo"
+					values.Workers[0].CABundle = ptr.To("bar")
+					values.Workers[1].CABundle = ptr.To("baz")
+				})
+				JustBeforeEach(func() {
+					Expect(defaultDepWaiter.Deploy(ctx)).To(Succeed())
+				})
+
+				It("should successfully generate caBundle when Worker.CABundle is provided", func() {
```
Comment (ialidzhikov) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]:
```suggestion
				When("worker CA bundle is set", func() {
					It("should append worker CA bundle to the CA bundle", func() {
```

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go [hunk 7]
```diff
@@ -782,6 +787,65 @@ var _ = Describe("OperatingSystemConfig", func() {
 					Expect(actual).To(Equal(obj))
 				}
 			})
+
+			Context("CABundle generation", func() {
```
Comment (ialidzhikov) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]: Strictly speaking, we are not generating anything.

```suggestion
			Context("CA bundle computation", func() 
```

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go [hunk 8]
```diff
@@ -782,6 +787,65 @@ var _ = Describe("OperatingSystemConfig", func() {
...
+					It("should contains only original CABundle value", func() {
+						for _, e := range expected {
+							if e.Spec.Purpose != extensionsv1alpha1.OperatingSystemConfigPurposeReconcile {
+								continue
+							}
+							actual := &extensionsv1alpha1.OperatingSystemConfig{}
+							Expect(c.Get(ctx, client.ObjectKey{Name: e.Name, Namespace: e.Namespace}, actual)).To(Succeed())
+							content := getROOTcertsFileContent(actual)
+							Expect(content).NotTo(BeNil())
+							Expect(*content).To(Equal("foo"))
```
Comment (ialidzhikov) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]:
```suggestion
							if e.Spec.Purpose != extensionsv1alpha1.OperatingSystemConfigPurposeReconcile {
								continue
							}

							actual := &extensionsv1alpha1.OperatingSystemConfig{}
							Expect(c.Get(ctx, client.ObjectKey{Name: e.Name, Namespace: e.Namespace}, actual)).To(Succeed())

							content := getROOTcertsFileContent(actual)
							Expect(content).NotTo(BeNil())
							Expect(*content).To(Equal("foo"))
```

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go [hunk 9]
```diff
@@ -782,6 +787,65 @@ var _ = Describe("OperatingSystemConfig", func() {
...
+						actual := &extensionsv1alpha1.OperatingSystemConfig{}
+						Expect(c.Get(ctx, client.ObjectKey{Name: e.Name, Namespace: e.Namespace}, actual)).To(Succeed())
+						worker := actual.Labels["worker.gardener.cloud/pool"]
+						content := getROOTcertsFileContent(actual)
+						Expect(content).NotTo(BeNil())
+						if worker == "worker1" {
+							Expect(*content).To(Equal("foo\nbar"))
+						} else {
+							Expect(*content).To(Equal("foo\nbaz"))
+						}
```
Comment (ialidzhikov) [inline pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]:
```suggestion
							if e.Spec.Purpose != extensionsv1alpha1.OperatingSystemConfigPurposeReconcile {
								continue
							}

							actual := &extensionsv1alpha1.OperatingSystemConfig{}
							Expect(c.Get(ctx, client.ObjectKey{Name: e.Name, Namespace: e.Namespace}, actual)).To(Succeed())

							content := getROOTcertsFileContent(actual)
							Expect(content).NotTo(BeNil())
							worker := actual.Labels["worker.gardener.cloud/pool"]
							if worker == "worker1" {
								Expect(*content).To(Equal("foo\nbar"))
							} else {
								Expect(*content).To(Equal("foo\nbaz"))
							}
```

**Review by ialidzhikov — COMMENTED** [review]
Thanks for the fix!

**Comment by dimitar-kostadinov** [comment]
```
Summarizing 1 Failure:
  [FAIL] Extension Required Runtime controller tests [It] should report dns extension as not required during garden deletion
  /home/prow/go/src/github.com/gardener/gardener/test/integration/operator/extension/required/runtime/runtime_test.go:307
Ran 8 of 9 Specs in 34.061 seconds
FAIL! -- 7 Passed | 1 Failed | 0 Pending | 1 Skipped
--- FAIL: TestExtensionRequiredRuntime (34.06s)
```

/test pull-gardener-integration

```
Summarizing 5 Failures:
  [INTERRUPTED] Shoot Tests Create Shoot, Rotate Credentials and Delete Shoot Shoot with workers with workers rollout [It] Wait for Shoot to be deleted [Shoot, default, credentials-rotation, basic, with-workers-rollout]
  /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_rotate_delete.go:342
  [INTERRUPTED] Shoot Tests Create Shoot, Rotate Credentials and Delete Shoot Shoot with workers with workers rollout, in-place update strategy [It] Wait for Shoot to be deleted [Shoot, default, credentials-rotation, basic, with-workers-rollout, in-place]
  /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_rotate_delete.go:342
  [TIMEDOUT] Shoot Tests Update from non-HA to HA with failure tolerance type 'node' Shoot with workers in-cluster access to API server [It] should access the API server via the kubernetes service's hostname [Shoot, high-availability, update-to-node]
  /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/internal/inclusterclient/inclusterclient.go:143
  [INTERRUPTED] Shoot Tests Create Shoot, Rotate Credentials and Delete Shoot Shoot with workers without workers rollout [It] Wait for Shoot to be reconciled [Shoot, default, credentials-rotation, basic, without-workers-rollout]
  /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_rotate_delete.go:231
  [INTERRUPTED] Shoot Tests Update from non-HA to HA with failure tolerance type 'node' Workerless Shoot [It] Wait for Shoot to be reconciled [Shoot, high-availability, update-to-node, workerless]
  /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/update-to-ha.go:33
Ran 285 of 833 Specs in 2004.540 seconds
FAIL! - Interrupted by Other Ginkgo Process -- 280 Passed | 5 Failed | 0 Pending | 548 Skipped
Ginkgo ran 1 suite in 34m2.76354665s
```

/test pull-gardener-e2e-kind-ha-single-zone

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go (hunk 8 above)
Comment (ialidzhikov) [reply pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]: This comment does not seem to be applied. Could you check?

File: pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go (hunk 9 above)
Comment (ialidzhikov) [reply pkg/component/extensions/operatingsystemconfig/operatingsystemconfig_test.go]: This comment does not seem to be applied. Could you check?

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Comment by dimitar-kostadinov** [comment]
```
Summarizing 1 Failure:
  [FAIL] Garbage collector tests [It] should only garbage collect unreferenced resources
  /home/prow/go/src/github.com/gardener/gardener/test/integration/resourcemanager/garbagecollector/garbagecollector_test.go:208
Ran 2 of 2 Specs in 15.521 seconds
FAIL! -- 1 Passed | 1 Failed | 0 Pending | 0 Skipped
```
/test pull-gardener-integration

```
Error: UPGRADE FAILED: update: failed to update: Internal error occurred: failed calling webhook "validate-kubeconfig-secrets.gardener.cloud": failed to call webhook: Post "[https://gardener-admission-controller.garden.svc:443/webhooks/validate-kubeconfig-secrets?timeout=10s](https://gardener-admission-controller.garden.svc/webhooks/validate-kubeconfig-secrets?timeout=10s)": dial tcp 10.2.2.10:443: connect: connection refused
```
/test pull-gardener-e2e-kind-ha-multi-zone-upgrade

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
