### PR TITLE
Fix Seed deletion deadlock

### LINKED ISSUE #1555: Deadlock on Seed deletion
**What happened**:
When a Seed is deleted that is still used by at least one Shoot (which is not marked for deletion), a deadlock will occur, so that neither Seed nor Shoots can be deleted and require manual cleanup.

The problem is that the `metadata.generation` of the Seed object is increased on deletion (here: `vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:761`) and the `status.observedGeneration` will not be updated by gcm to match the generation. The deletion process of the Seed is blocked until all referencing Shoots and BackupBuckets are deleted. If you then try to delete the Shoot, the deletion process is also blocked, because it is waiting for the Seed to get ready (waiting for observedGeneration to equal generation).
The same problem occurs for other gardener resources, for example BackupBuckets.

**What you expected to happen**:
The deletion of a Seed which is still used by Shoots should not block the deletion of the Shoots and therefore cause a deadlock.
That means that:
- either the observedGeneration should be updated accordingly in gcm on deletion of the Seed object
- or the generation should not be increased on deletion in the first place

**How to reproduce it (as minimally and precisely as possible)**:
1. create a Seed
1. create a Shoot using that Seed
1. delete the Seed
    - this will increase the generation field
    - this will wait for Shoots and BackupBucket (and transitively BackupEntries) to get deleted
1. delete the Shoot
    - this will wait for the seed to get ready
1. result: deadlock

**Anything else we need to know?**:
According to comments in the apiserver library the generation is increased because "the object has pending finalizers but does not supporting graceful deletion" (ShootStrategy does not implement the RESTGracefulDeleteStrategy interface).

**Environment**:

- Gardener version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timebertt**
**What this PR does / why we need it**:
This PR fixes the issue that prevented a Seed to be properly cleaned up before deletion and blocked the deletion of any left over Shoots on this Seed.

**Which issue(s) this PR fixes**:
Fixes #1555

**Special notes for your reviewer**:

**Release note**:

```improvement operator
An issue was fixed which prevented a Seed to be properly cleaned up before deletion and blocked the deletion of any left over Shoots on this Seed.
```

### CODE REVIEW

File: pkg/controllermanager/controller/controllerinstallation/controllerinstallation_control.go [hunk 1]
```diff
@@ -338,7 +338,7 @@ func (c *defaultControllerInstallationControl) delete(controllerInstallation *ga
 	)
 
 	defer func() {
-		if _, err := c.updateConditions(controllerInstallation, conditionValid, conditionInstalled); err != nil {
+		if _, err := c.updateConditions(controllerInstallation, conditionValid, conditionInstalled); err != nil && !apierrors.IsNotFound(err) {
```
Comment (rfranzke) [inline pkg/controllermanager/controller/controllerinstallation/controllerinstallation_control.go]:
```suggestion
		if _, err := c.updateConditions(controllerInstallation, conditionValid, conditionInstalled); client.IgnoreNotFound(err) != nil {
```

File: pkg/controllermanager/controller/shoot/shoot_control_delete.go [hunk 2]
```diff
@@ -507,14 +507,22 @@ func (c *Controller) updateShootStatusDeleteSuccess(o *operation.Operation) erro
 	}
 	o.Shoot.Info = newShoot
 
-	// Remove finalizer
-	finalizers := sets.NewString(o.Shoot.Info.Finalizers...)
-	finalizers.Delete(gardencorev1alpha1.GardenerName)
-	o.Shoot.Info.Finalizers = finalizers.List()
-	newShoot, err = c.k8sGardenClient.GardenCore().CoreV1alpha1().Shoots(o.Shoot.Info.Namespace).Update(o.Shoot.Info)
+	// Remove finalizer with retry on conflict
+	newShoot, err = kutil.TryUpdateShoot(c.k8sGardenClient.GardenCore(), retry.DefaultBackoff, o.Shoot.Info.ObjectMeta, func(curShoot *gardencorev1alpha1.Shoot) (*gardencorev1alpha1.Shoot, error) {
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/shoot_control_delete.go]: Can we re-use https://github.com/gardener/gardener/blob/master/pkg/controllermanager/controller/utils/finalizers.go#L51?

File: plugin/pkg/shoot/validator/admission.go [hunk 3]
```diff
@@ -574,6 +590,40 @@ func (v *ValidateShoot) Admit(a admission.Attributes, o admission.ObjectInterfac
...
+		if newHasConfirmation {
+			if oldMeta.Annotations == nil {
+				oldMeta.Annotations = make(map[string]string)
+			}
+			oldMeta.Annotations[common.ConfirmationDeletion] = newConfirmation
+		}
+
+		if !reflect.DeepEqual(newMeta.Annotations, oldMeta.Annotations) {
+			// something else than the confirmation annotation has changed -> deny the update
+			return errors.New("")
```
Comment (rfranzke) [inline plugin/pkg/shoot/validator/admission.go]: Can we provide a proper error message here?

Comment (timebertt) [reply plugin/pkg/shoot/validator/admission.go]: No, actually not, because shoot and seed names would have to be passed down just for constructing the error message.
But anyways a valid point. I changed the function to return a bool indicating, if the update should be admitted, which might indeed be better style than returning an empty error, which the calling function acts upon.
Please take another look :)

Comment (plkokanov) [reply plugin/pkg/shoot/validator/admission.go]: Can't we still return an error which contains the comment and just add the shoot and seed names in the calling code. 
```
if err := validateMetaUpdateOnDeletedSeed(&shoot.ObjectMeta, &oldShoot.ObjectMeta); err != nil {
   return admission.NewForbidden(a, fmt.Errorf("cannot update shoot '%s' on seed '%s' already marked for deletion: %v",  shoot.Name, seed.Name, err)
}
```

This way whoever calls the update knows why the validation failed -> `Only the confirmation.garden.sapcloud.io/deletion annotation can be changed`

File: plugin/pkg/shoot/validator/admission.go [hunk 4]
```diff
@@ -240,8 +243,9 @@ func (v *ValidateShoot) Admit(a admission.Attributes, o admission.ObjectInterfac
 	}
 
 	// We don't allow shoot to be created on the seed which is already marked to be deleted.
-	if seed != nil && seed.DeletionTimestamp != nil {
-		return admission.NewForbidden(a, fmt.Errorf("cannot create or update shoot '%s' on seed '%s' already marked for deletion", shoot.Name, seed.Name))
+	// Still allow removal of finalizers as last step of deletion flow (happens via Update request)
+	if seed != nil && seed.DeletionTimestamp != nil && a.GetOperation() != admission.Update {
```
Comment (timuthy) [inline plugin/pkg/shoot/validator/admission.go]:
```suggestion
	if seed != nil && seed.DeletionTimestamp != nil && a.GetOperation() == admission.Create {
```

File: plugin/pkg/shoot/validator/admission.go [hunk 5]
```diff
@@ -574,6 +590,41 @@ func (v *ValidateShoot) Admit(a admission.Attributes, o admission.ObjectInterfac
 	return nil
 }
 
+// validateMetaUpdateOnDeletedSeed validates updates to a Shoot's metadata in the case that the referenced Seed is
+// already marked for deletion. In this case it should not be allowed to modify any annotations except adding the
+// deletion confirmation annotation and to modify the Finalizers array. These operations are required to delete
+// Shoots to cleanup a Seed which is marked for deletion
+// It returns true, if the metadata update can be admitted, otherwise false.
+func validateMetaUpdateOnDeletedSeed(newMeta, oldMeta *metav1.ObjectMeta) bool {
```
Comment (timuthy) [inline plugin/pkg/shoot/validator/admission.go]: Actually the function has no knowledge of a `seed` object. Please adjust the doc string and the function name to the job it does.

**Review by timuthy — CHANGES_REQUESTED** [review]

**Comment by timebertt** [comment]
@rfranzke @timuthy @plkokanov Thanks for your reviews and comments.
I think I just made it too complicated. I simplified my code, removed the additional function and moved my logic to the main `Admit` function. There isn't that much code for this logic, anyways.
PTAL :)

**Review by rfranzke — APPROVED** [review]

**Review by plkokanov — APPROVED** [review]

**Review by timuthy — APPROVED** [review]
