### PR TITLE
Fix flaky `ManagedSeed` e2e test

### LINKED ISSUE #6766: [Flaky Test] Gardenlet kubeconfig rotation test suite
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
  Timed out after 300.001s.
  Expected success, but got an error:
      <*errors.errorString | 0xc000000ea0>: {
          s: "kubeconfig secret has not yet been renewed, timeBeforeRotation: 2022-10-02 17:03:07.218670959 +0000 UTC, newClientCertificateIssuedAt: 2022-10-02 17:02:44 +0000 UTC",
      }
      kubeconfig secret has not yet been renewed, timeBeforeRotation: 2022-10-02 17:03:07.218670959 +0000 UTC, newClientCertificateIssuedAt: 2022-10-02 17:02:44 +0000 UTC
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/managedseed/create_rotate_delete.go:408
```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6727/pull-gardener-e2e-kind/1576612816863891456

**Reason for failure**:
Mentioned above.
**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind flake

**What this PR does / why we need it**:
See https://github.com/gardener/gardener/issues/6766#issuecomment-1268393109 for details. Basically, we now scale down the gardenlet deployment before waiting for the auto-rotation to prevent that intermittently restarted old gardenlet pods (not respecting the new configuration) interfere with the expected behaviour of the test.

**Which issue(s) this PR fixes**:
Fixes #6766

**Special notes for your reviewer**:
On the way, I added a second commit which prevents creating an intermediate `ReplicaSet` by causing two subsequent gardenlet rollouts. Now, only one rollout is triggered which creates less noise.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: test/e2e/managedseed/create_rotate_delete.go [hunk 1]
```diff
@@ -348,6 +343,7 @@ func patchGardenletKubeconfigValiditySettings(
 
 	patch := client.MergeFrom(managedSeed.DeepCopy())
 	managedSeed.Spec.Gardenlet.Config = *gardenletConfigRaw
+	metav1.SetMetaDataAnnotation(&managedSeed.ObjectMeta, "gardener.cloud/operation", "renew-kubeconfig")
```
Comment (shafeeqes) [inline test/e2e/managedseed/create_rotate_delete.go]:
```suggestion
	metav1.SetMetaDataAnnotation(&managedSeed.ObjectMeta, v1beta1constants.GardenerOperation, v1beta1constants.GardenerOperationRenewKubeconfig)
```
