### PR TITLE
Ignore nodes not managed by MCM from GNA lease check

### LINKED ISSUE #14503: `EveryNodeReady` should skip nodes not managed by MCM
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:
`CheckNodeAgentLeases()`in does not skip nodes annotated with `node.machine.sapcloud.io/not-managed-by-mcm: "1"`. When a node appears in the cluster that was not provisioned by MCM (and therefore has no gardener-node-agent running), the health check fails with:
```
gardener-node-agent is not running on node "<node-name>"
```
This causes the `EveryNodeReady` shoot condition to report `NodeAgentUnhealthy` with a node condition on the dashboard, even though the node is intentionally not managed by MCM and is not expected to have gardener-node-agent. `CheckClusterNodes` already skips such nodes.

**What you expected to happen**:
The `EveryNodeReady` condition should not become unhealthy due to non-MCM-managed nodes lacking a gardener-node-agent lease.

**How to reproduce it (as minimally and precisely as possible)**:
- Have a shoot cluster where a node joins that is not provisioned via MCM (e.g., a manually created VM instance joining the cluster).
- The health check returns an error, setting EveryNodeReady to False with reason NodeAgentUnhealthy.
- MCM eventually annotates the node with `node.machine.sapcloud.io/not-managed-by-mcm: "1"`

**Anything else we need to know?**:
There is still a window between when the node appears and when MCM anotates it with `not-managed-by-mcm`.  During that window, the health check will still fail.

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/kind bug

**What this PR does / why we need it**:
This PR ignores nodes not managed by MCM from GNA lease check. For more details check - #14503

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/14503

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Fixed `EveryNodeReady` shoot condition incorrectly reporting `NodeAgentUnhealthy` for nodes not managed by MCM.
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/care/health.go [hunk 1]
```diff
@@ -708,7 +708,7 @@ func (h *Health) CheckClusterNodes(
 }
 
 // CheckNodeAgentLeases checks if all nodes in the shoot cluster have a corresponding Lease object maintained by gardener-node-agent
-func CheckNodeAgentLeases(nodeList *corev1.NodeList, leaseList *coordinationv1.LeaseList, clock clock.Clock) error {
+func CheckNodeAgentLeases(nodeList []*corev1.Node, leaseList *coordinationv1.LeaseList, clock clock.Clock) error {
```
Comment (tobschli) [inline pkg/gardenlet/controller/shoot/care/health.go:711]: nit: Do we also want to change this for consitency?
```suggestion
func CheckNodeAgentLeases(nodeList []*corev1.Node, leaseList []*coordinationv1.Lease, clock clock.Clock) error {
```

File: pkg/gardenlet/controller/shoot/care/health.go
Comment (tobschli) [inline pkg/gardenlet/controller/shoot/care/health.go:1]: What about the case:
- Node not managed by mcm
- User / operator decides to leverage GNA on their self-managed node?

Or is this something that is node in scope?

**Review by tobschli — COMMENTED** [review]
Thank you for the PR ❤️

File: pkg/gardenlet/controller/shoot/care/health.go (hunk 1 above)
Comment (acumino) [reply pkg/gardenlet/controller/shoot/care/health.go:711]: Probably not, otherwise I will have to first create a lease list where this function is called, which is overhead and not required also.

File: pkg/gardenlet/controller/shoot/care/health.go
Comment (acumino) [reply pkg/gardenlet/controller/shoot/care/health.go:1]: > User / operator decides to leverage GNA on their self-managed node?

This feature is not there yet, we can think about it when the feature comes. Or can it be?
But in any case gardener should only be checking nodes mangaed by it.

Comment (plkokanov) [reply pkg/gardenlet/controller/shoot/care/health.go:1]: I would keep the scope small for now. 
If we want to do something like this, we probably need to introduce a new label that MCM puts on the nodes and operators can also put on their own "custom" nodes when they manually install GNA.
Also, shoot operators might not configure GNA properly and such a feature would generate additional noise for gardener operators.

File: pkg/gardenlet/controller/shoot/care/health.go (hunk 1 above)
Comment (tobschli) [reply pkg/gardenlet/controller/shoot/care/health.go:711]: Ah, because `leaseList.Items` is of type `[]coordinationv1.Lease` and not `[]*coordinationv1.Lease`.
Sure, okay :)

File: pkg/gardenlet/controller/shoot/care/health.go
Comment (tobschli) [reply pkg/gardenlet/controller/shoot/care/health.go:1]: Sounds reasonable to me!
Then let us keep it as is

**Review by tobschli — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
/approve

**Comment by plkokanov** [comment]
Just fyi, we had a short chat about this with @acumino and @timuthy because the nodes list that is used in these checks is created in https://github.com/acumino/gardener/blob/58e62e36d260fd3cb0f8575ca2a96c4375604050/pkg/gardenlet/operation/botanist/worker.go#L88-L92 and only includes nodes that do not have the `worker.gardener.cloud/pool`. 

We were generally wondering if it is a valid or even expected scenario to have both the `worker.gardener.cloud/pool` label and `node.machine.sapcloud.io/not-managed-by-mcm` annotation at the same time on a node that is added by users, as the former label is used as a node selector for some system components.

We decided to proceed with the PR as it is (it got approved meanwhile), since the logic that checks for the `node.machine.sapcloud.io/not-managed-by-mcm` annotation was present even from before, but we should maybe look into this wrt the `worker.gardener.cloud/pool` label and write a doc whether it is expected to be added to such nodes or not.
