### PR TITLE
[operator] Fix Structured Authn for Dashboard

### LINKED ISSUE #10951: Dashboard OIDC setup fails when using `StructuredAuthentication`
**How to categorize this issue?**

/area security
/kind bug

**What happened**:

When configuring the `Garden` resource to use `structuredAuthentication` in `kubeAPIServer`, it's not possible to set up OIDC settings for the Gardener Dashboard. The Gardener Operator expects OIDC settings from `virtualCluster.kubernetes.kubeAPIServer.oidcConfig`, but this field is deprecated and incompatible with `structuredAuthentication`. As a result, the following validation error occurs:

```
must set .spec.virtualCluster.kubernetes.kubeAPIServer.oidcConfig when configuring OIDC config for dashboard
```

**What you expected to happen**:

I expected to configure OIDC settings for the Gardener Dashboard independently of `kubeAPIServer.oidcConfig`, especially when using `structuredAuthentication`. The Gardener Operator should allow setting up OIDC for the dashboard without requiring the deprecated `oidcConfig` field in the `kubeAPIServer`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a `Garden` resource with `structuredAuthentication` in `virtualCluster.kubernetes.kubeAPIServer`, omitting `oidcConfig`.
2. Configure the Gardener Dashboard's OIDC settings in `virtualCluster.gardener.gardenerDashboard.oidcConfig`.
3. Apply the `Garden` resource.
4. Observe the validation error stating that `.spec.virtualCluster.kubernetes.kubeAPIServer.oidcConfig` must be set.

Example `Garden` resource YAML:

```yaml
apiVersion: operator.gardener.cloud/v1alpha1
kind: Garden
metadata:
  name: local
spec:
  virtualCluster:
    kubernetes:
      kubeAPIServer:
        structuredAuthentication:
          configMapName: virtual-garden-auth-config
        # oidcConfig is omitted because it's deprecated
    gardener:
      gardenerDashboard:
        enableTokenLogin: false
        oidcConfig:
          secretRef:
            name: gardener-dashboard-oidc
          sessionLifetime: 12h
```

**Anything else we need to know?**:

The issue stems from validation logic in the Gardener Operator that requires `kubeAPIServer.oidcConfig` when OIDC is configured for the dashboard, conflicting with the deprecation of `oidcConfig` in favor of `structuredAuthentication`.

Relevant code snippets:

- **Validation forbidding `oidcConfig` when using `structuredAuthentication`**:
https://github.com/gardener/gardener/blob/e458bc02e5acbc06c736f60337efcd32b729f3bb/pkg/apis/core/validation/shoot.go#L1371-L1386

- **Validation requiring `oidcConfig` for dashboard OIDC configuration**:
https://github.com/gardener/gardener/blob/e458bc02e5acbc06c736f60337efcd32b729f3bb/pkg/apis/operator/v1alpha1/validation/validation.go#L410-L423

- **Operator reading OIDC settings from the deprecated `oidcConfig`** :
https://github.com/gardener/gardener/blob/e458bc02e5acbc06c736f60337efcd32b729f3bb/pkg/operator/controller/garden/garden/components.go#L1082-L1088

**Environment**:

- Gardener version: v1.108.1
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area security
/kind bug

**What this PR does / why we need it**:
Makes it possible to configure Structured Authentication with Gardener Dashboard OIDC configuration (see #10951).

**Which issue(s) this PR fixes**:
Fixes #10951

**Special notes for your reviewer**:
@petersutter thanks for reporting and suggesting a solution

**Release note**:

```bugfix operator
An issue was fixed in `gardener-operator` that prevented configuring OIDC for `gardener-dashboard` while using Structured Authentication.
```
```other operator
The `gardener-dashboard` configuration was enhanced in the `garden` API with fields `gardenerDashboard.oidcConfig.clientIDPublic` and `gardenerDashboard.oidcConfig.issuerURL`.
Those are required to switch from the deprecated `kubeAPIServer.oidcConfig` to `kubeAPIServer.structuredAuthentication`.
```

### CODE REVIEW

File: pkg/apis/operator/v1alpha1/validation/validation.go [hunk 1]
```diff
@@ -418,8 +418,29 @@ func validateGardenerDashboardConfig(config *operatorv1alpha1.GardenerDashboardC
...
+		oidcPath := fldPath.Child("oidc")
+
+		if kubeAPIServerConfig == nil || (kubeAPIServerConfig.OIDCConfig == nil && kubeAPIServerConfig.StructuredAuthentication == nil) {
+			allErrs = append(allErrs, field.Invalid(oidcPath, config.OIDC, "must set OIDC configuration in .spec.virtualCluster.kubernetes.kubeAPIServer when configuring OIDC config for dashboard"))
+		}
+		if oidc.IssuerURL == nil && (kubeAPIServerConfig == nil || kubeAPIServerConfig.OIDCConfig == nil || kubeAPIServerConfig.OIDCConfig.IssuerURL == nil) {
+			allErrs = append(allErrs, field.Required(oidcPath.Child("issuerURL"), "must provide Issuer URL"))
+		}
+		if oidc.ClientID == nil && (kubeAPIServerConfig == nil || kubeAPIServerConfig.OIDCConfig == nil || kubeAPIServerConfig.OIDCConfig.ClientID == nil) {
+			allErrs = append(allErrs, field.Required(oidcPath.Child("clientID"), "must provide ClientID URL"))
```
Comment (petersutter) [inline pkg/apis/operator/v1alpha1/validation/validation.go]:
```suggestion
			allErrs = append(allErrs, field.Required(oidcPath.Child("clientID"), "must provide ClientID"))
```

File: pkg/apis/core/validation/shoot_test.go [hunk 2]
```diff
@@ -7063,6 +7044,32 @@ var _ = Describe("Shoot Validation Tests", func() {
 			))
 		})
 	})
+
+	Describe("#ValidateOIDCIssuerURL", func() {
+		DescribeTable("test  valid and invalid issuer URLs", func(issuerURL string, detail string) {
```
Comment (marc1404) [inline pkg/apis/core/validation/shoot_test.go]: Nit: I cannot unsee the extra whitespace 👀 
```suggestion
		DescribeTable("test valid and invalid issuer URLs", func(issuerURL string, detail string) {
```

File: pkg/apis/operator/v1alpha1/types_garden.go [hunk 3]
```diff
@@ -623,6 +623,16 @@ type DashboardGitHub struct {
 
 // DashboardOIDC contains configuration for the OIDC settings.
 type DashboardOIDC struct {
+	// ClientIDPublic is the public client ID.
+	// Falls back to the API server's OIDC configuration if not set here.
+	// +kubebuilder:validation:MinLength=1
+	// +optional
+	ClientID *string `json:"clientID,omitempty"`
```
Comment (marc1404) [inline pkg/apis/operator/v1alpha1/types_garden.go]: Nit: I think it should be one of the two versions below to be consistent:
```suggestion
	// ClientID is the public client ID.
	// Falls back to the API server's OIDC configuration if not set here.
	// +kubebuilder:validation:MinLength=1
	// +optional
	ClientID *string `json:"clientID,omitempty"`
```

or

```suggestion
	// ClientIDPublic is the public client ID.
	// Falls back to the API server's OIDC configuration if not set here.
	// +kubebuilder:validation:MinLength=1
	// +optional
	ClientIDPublic *string `json:"clientIDPublic,omitempty"`
```

☝️ this version would be consistent with the dashboard's [`OIDCValues`](https://github.com/gardener/gardener/blob/bad9f34c55be9ddff98e5b4abfe8d2f71ef74cea/pkg/component/gardener/dashboard/dashboard.go#L80).

**Review by marc1404 — COMMENTED** [review]
/lgtm

Thanks for tackling this! 👏

File: pkg/apis/operator/v1alpha1/types_garden.go (hunk 3 above)
Comment (timuthy) [reply pkg/apis/operator/v1alpha1/types_garden.go]: I prefer `ClientID` which is also the value used in the Dashboard repo ([ref](https://github.com/gardener/dashboard/blob/c79afc80b9e6e189e1ce77c9b79011ce4db77f9e/charts/gardener-dashboard/values.yaml#L123)).

Comment (petersutter) [reply pkg/apis/operator/v1alpha1/types_garden.go]: > I prefer ClientID which is also the value used in the Dashboard repo ([ref](https://github.com/gardener/dashboard/blob/c79afc80b9e6e189e1ce77c9b79011ce4db77f9e/charts/gardener-dashboard/values.yaml#L123)).

This is the dashboard's clientID, not the public client ID, which would be this one here: [oidc.public.clientId](https://github.com/gardener/dashboard/blob/c79afc80b9e6e189e1ce77c9b79011ce4db77f9e/charts/gardener-dashboard/values.yaml#L142-L144)
These are the oidc helm chart values of the dashboard (some fields omitted)
```yaml
oidc:
  # well-known URL for OpenID Provider Issuer Discovery
  issuerUrl: ~
  # clientId is the public identifier of the gardener-dashboard aplication
  clientId: dashboard
  # clientSecret is the private secret of the gardener-dashboard aplication
  clientSecret: ~
  # configuration for kubeconfig download required by kubelogin
  public:
    # clientId is the identifier of the public oidc client use by kubelogin
    clientId: kube-kubectl
    # clientSecret is the public client secret use by kubelogin and all users
    clientSecret: ~
    # force PKCE usage (automatically enabled if no clientSecret is given)
    usePKCE: true
```

So I would also vote for `clientIDPublic`, otherwise it is confusing which clientId is used for which purpose.

Comment (timuthy) [reply pkg/apis/operator/v1alpha1/types_garden.go]: Thanks for clarifying @petersutter. I will adapt the PR.

**Comment by timuthy** [comment]
Thanks for your reviews @petersutter and @marc1404. PTAL.

**Review by marc1404 — COMMENTED** [review]
/lgtm

Thanks for addressing the feedback :)
