### PR TITLE
Enhance validation for `issuerURL`

### LINKED ISSUE #10864: Kube apiserver  fails to get deployed if issuer URL has fragment
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
```
  kubernetes:
      oidcConfig:
        issuerURL: 'https://test.html# '
```

If `issuerURL` has fragment then KAPI fails to get deployed and throw following error - 

```
E1115 03:29:46.930763       1 run.go:74] "command failed" err="jwt[0].issuer.url: Invalid value: \"https://test.html# \": URL must not contain a fragment"
```

**What you expected to happen**:
KAPIs should be deployed successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot cluster with the issuerURL having `#<text>` at the end. The KAPIs pod will in error state.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.107
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR adds validation to the issuerURL field in the OIDC configuration to ensure that URLs with fragments (e.g., #fragment) are rejected. This prevents the Kubernetes API server (KAPI) from failing to deploy when such URLs are provided.
Also it add few other validation for issuerURL to inline it with valid OIDC URL.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/10864

**Special notes for your reviewer**:

**Release note**:

```other operator
Added validation for `issuerURL` in the OIDC configuration to reject URLs containing fragments.
```

### CODE REVIEW

File: pkg/apis/core/validation/shoot.go [hunk 1]
```diff
@@ -1307,6 +1307,9 @@ func ValidateKubeAPIServer(kubeAPIServer *core.KubeAPIServerConfig, version stri
 			if err != nil || (issuer != nil && len(issuer.Host) == 0) {
 				allErrs = append(allErrs, field.Invalid(oidcPath.Child("issuerURL"), oidc.IssuerURL, "must be a valid URL and have https scheme"))
 			}
+			if issuer != nil && issuer.Fragment != "" {
```
Comment (dimityrmirchev) [inline pkg/apis/core/validation/shoot.go:1310]: I think that the validation can be further enhanced.

Kubernetes also validate that RawQuery and User are empty https://github.com/kubernetes/kubernetes/blob/776fb24e066d54cf84a52366aeea121fa5748e27/staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation.go#L169-L180

The[ OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html) says:
>  Issuer Identifier
Verifiable Identifier for an Issuer. An Issuer Identifier is a case-sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components.

**Review by dimityrmirchev — COMMENTED** [review]
One note from my side

File: pkg/apis/core/validation/shoot.go (hunk 1 above)
Comment (acumino) [reply pkg/apis/core/validation/shoot.go:1310]: Updated the PR, PTAL.

**Review by dimityrmirchev — APPROVED** [review]
/lgtm
