### PR TITLE
Do not skip KCM deployment in Shoot deletion flow if controlplane is deployed

### LINKED ISSUE #11283: Deletion of a Shoot that failed to create due to a `kube-apiserver` error is unsuccessful
**How to categorize this issue?**

/area ops-productivity
/kind bug

**What happened**:
If a shoot creation fails at the step of deploying kube-apiserver, for eg:
```
2025-02-01 01:56:41 | {"log":{"controller":"shoot","error":"Flow \"Shoot cluster reconciliation\" encountered task errors: [task \"Waiting until Kubernetes API server rolled out\" failed: retry failed with context deadline exceeded, last error: ReplicaSet \"kube-apiserver-5ddd4d694c\" has timed out progressing., 
``` 
and a shoot deletion is triggered right after, during deletion, we deploy controlplane after running through some checks, concretely:
https://github.com/gardener/gardener/blob/b8d6368461f7fb95b610e97b78a44cc0d33c1b75/pkg/gardenlet/controller/shoot/shoot/reconciler.go#L967-L996
which returns true since `kubeAPIServerDeploymentFound` is true and `infrastructure.Status.ProviderStatus != nil`.
But the deployment of `kube-controller-manager` is skipped since the deployment is not found, https://github.com/gardener/gardener/blob/2c445773fc3f34681e2b755f5c2c74fbee86933c/pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go#L328-L333

And a later part of the flow, `destroyControlPlane` is called, and this gets stuck with
```
Last Message
Flow "Shoot cluster deletion" encountered task errors: [task "Waiting until shoot control plane has been destroyed" failed: Failed to delete ControlPlane shoot--local--local/local: Error deleting ControlPlane: error while waiting for managed resource containing shoot chart for controlplane 'shoot--local--local/local' to be deleted: error while waiting for all resources to be deleted: retry failed with context deadline exceeded, last error: resource shoot--local--local/extension-controlplane-shoot still exists:
Could not clean all old resources: 1 error occurred: deletion of old resource "apps/v1/DaemonSet/kube-system/csi-driver-node" is still pending] Operation will be retried.
```

This is because there is no KCM to cleanup the finalizer `foregroundDeletion` which is added by GRM during the deletion of the Daemonset,
https://github.com/gardener/gardener/blob/bd43935120bd6cd7a8da6bc07197f09377ccf71c/pkg/resourcemanager/controller/managedresource/reconciler.go#L701-L709

**What you expected to happen**:
Shoot deletion to be successful.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a local shoot, after replacing this step in the `reconciler_delete.go` with a fake error, eg.
```
		waitUntilKubeAPIServerIsReady = g.Add(flow.Task{
			Name:         "Waiting until Kubernetes API server rolled out",
			Fn:           func(ctx context.Context) error { return fmt.Errorf("fake error") },
			SkipIf:       o.Shoot.HibernationEnabled || skipReadiness,
			Dependencies: flow.NewTaskIDs(deployKubeAPIServer),
		})
```
2. Wait for shoot creation to fail.
3. Add a dummy `providerStatus` to Infra resource to make the above condition return `true`.
4. Delete the shoot.
5. Observe that the deletion is stuck in the `Waiting until shoot control plane has been destroyed` step with similar error for some daemonset.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area ops-productivity
/kind bug

**What this PR does / why we need it**:
This PR unskips KCM deployment in the Shoot deletion flow if controlplane deployment is deployed before.

**Which issue(s) this PR fixes**:
Fixes #11283

**Special notes for your reviewer**:
~This doesn't fix the existing shoots stuck in deletion though since the controlplane already has a `deletionTimestamp`, so `controlPlaneDeploymentNeeded` is not true anymore.~

**Release note**:

```bugfix operator
A bug preventing the deletion of Shoots that previously failed to create due to an erroneous `kube-apiserver` has been fixed.
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go [hunk 1]
```diff
@@ -328,13 +328,13 @@ func (r *Reconciler) runDeleteShootFlow(ctx context.Context, o *operation.Operat
...
 			Fn:           flow.TaskFn(botanist.DeployKubeControllerManager).RetryUntilTimeout(defaultInterval, defaultTimeout),
-			SkipIf:       !cleanupShootResources || !kubeControllerManagerDeploymentFound,
+			SkipIf:       !cleanupShootResources || (!kubeControllerManagerDeploymentFound && !controlPlaneDeploymentNeeded),
 			Dependencies: flow.NewTaskIDs(initializeSecretsManagement, deployCloudProviderSecret, waitUntilControlPlaneReady, initializeShootClients),
 		})
 		_ = g.Add(flow.Task{
 			Name:         "Scaling up Kubernetes controller manager",
 			Fn:           botanist.ScaleKubeControllerManagerToOne,
-			SkipIf:       !cleanupShootResources || !kubeControllerManagerDeploymentFound,
+			SkipIf:       !cleanupShootResources || (!kubeControllerManagerDeploymentFound && !controlPlaneDeploymentNeeded),
```
Comment (timuthy) [inline pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go]:
```suggestion
			SkipIf:       !cleanupShootResources,
```

Do you think this will be sufficient?

Comment (shafeeqes) [reply pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go]: I tested it and it works also for previously stuck shoots.

Does it make sense to still keep the `kubeControllerManagerDeploymentFound` bool in
https://github.com/gardener/gardener/blob/f92e17b046bcb9460da8161120cab90988b52f75/pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go#L370-L375
since this bool also deals with the KCM deployment in deletion?

Comment (timuthy) [reply pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go]: Sounds good to me👍

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve
