### PR TITLE
Fixes incorrect `Machine` duplication when persisting the machine state in the `ShootState`

### LINKED ISSUE #12579: `ShootState` could get too large and cause the `migrate` phase of control plane migration to fail
**How to categorize this issue?**

/area control-plane-migration
/kind bug

**What happened**:
An error occurred during the `migrate` phase of control plane migration due to the `ShootState` being too large to be persisted:

```
2025-07-19 13:02:27 | {"log":{"controller":"shoot","error":"Request entity too large: limit is 3145728","flow":"Shoot cluster preparation for migration","level":"error","msg":"Error","name":"cluster1","namespace":"garden-project","operation":"migrate","reconcileID":"0e032913-0833-4adf-98ae-8bb36f8594cc","stacktrace":"github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:239","task":"Persisting ShootState in garden cluster","ts":"2025-07-19T13:02:27.143Z"}}
```

Oddly enough, the size of the `ShootState` was not consistent, as later on the size was less than `3145728`, however, the following error appeared:
```
2025-07-19 13:03:05 | {"log":{"controller":"shoot","error":"rpc error: code = ResourceExhausted desc = trying to send message larger than max (3062371 vs. 2097152)","flow":"Shoot cluster preparation for migration","level":"error","msg":"Error","name":"cluster1","namespace":"garden-project","operation":"migrate","reconcileID":"660af8fd-9c4f-453c-ba71-9b14021eb90f","stacktrace":"github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:239","task":"Persisting ShootState in garden cluster","ts":"2025-07-19T13:03:05.762Z"}}
```

For a different cluster: 
```
2025-07-19 13:02:08 | {"log":{"controller":"shoot","error":"rpc error: code = ResourceExhausted desc = trying to send message larger than max (2287987 vs. 2097152)","flow":"Shoot cluster preparation for migration","level":"error","msg":"Error","name":"cluster2","namespace":"garden-project","operation":"migrate","reconcileID":"40c1578c-8aea-44d8-9aa2-d405c947b9b4","stacktrace":"github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:239","task":"Persisting ShootState in garden cluster","ts":"2025-07-19T13:02:08.954Z"}}
```
Here the size of the `ShootState` is `2287987`. Later on it also fluctuates:

```
2025-07-19 13:02:22	
{"log":{"controller":"shoot","error":"rpc error: code = ResourceExhausted desc = trying to send message larger than max (2198035 vs. 2097152)","flow":"Shoot cluster preparation for migration","level":"error","msg":"Error","name":"cluster2","namespace":"garden-project","operation":"migrate","reconcileID":"4d9ac4a4-eaeb-4ad6-8cbb-1ca5ab6640c5","stacktrace":"github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:239","task":"Persisting ShootState in garden cluster","ts":"2025-07-19T13:02:22.386Z"}}
```

```
2025-07-19 13:03:09 | {"log":{"controller":"shoot","error":"rpc error: code = ResourceExhausted desc = trying to send message larger than max (2485683 vs. 2097152)","flow":"Shoot cluster preparation for migration","level":"error","msg":"Error","name":"cluster2","namespace":"garden-project","operation":"migrate","reconcileID":"059794b2-4fc6-4e71-818d-7124695eecff","stacktrace":"github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func2\n\t/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:239","task":"Persisting ShootState in garden cluster","ts":"2025-07-19T13:03:09.813Z"}}
```

These shoots had a large number of machine resource:
For `cluster1` which had the larger `ShootState`:
```❯ kubectl -n shoot--project--cluster1 get machines | wc -l
208
❯ kubectl -n shoot--project--cluster1 get machinesets | wc -l
439
❯ kubectl -n shoot--project--cluster1 get machinedeployments | wc -l
439
```

For `cluster2` which had the smaller `ShootState`:
```
❯ kubectl -n shoot--project--cluster2 get machine | wc -l
131
❯ kubectl -n shoot--project--cluster2 get machineset | wc -l
439
❯ kubectl -n shoot--project--cluster2 get machinedeployments.machine.sapcloud.io | wc -l
439
```

**What you expected to happen**:
The size of the `ShootState` to not be larger than the max allowed size and `migrate` phase to succeed. Alternatively, there should be a constraint or admission that checks the potential size of the `ShootState` and forbid control plane migrations.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a shoot with a large number of machine resources (~450 machinesets, machiendeployments and machines each)
2. Attempt to perform control plane migration for the cluster

**Anything else we need to know?**:
We have had similar issues in the past due to the large number of machines, machinesets and machinedeployments that have to be persisted: https://github.com/gardener/gardener/issues/8488. 

To resolve this, the required state to restore machines is compressed before it is saved in the `ShootState` ([ref to PR that adds this feature](https://github.com/gardener/gardener/pull/8618)). However, it seems that this could not be enough.

Some potential ways to fix this issue are:
1. Increase the allowed resource size for the gardener-apiserver, etcd and kube-apiserver for the garden virtual cluster
2. Compress also the `Infrastructure` state data and the persisted secrets' data which also seem to be a large contributor to the resulting size.
3. Separate the `ShootState` in multiple resources
4. Optimise the way that machine resources are preserved - potentially only active machines (with active replicas), machinesets and machinedeploymnets could be saved. Only persist the required data for machinesets and machines instead of the full resources.

It would also be good to add a constraint or admission that can prevent starting control plane migration in cases that would result in too large `ShootState`.

Additionally, the fluctuation of the `ShootState` size should be investigated further.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
This PR fixes an issue that caused `Machines` to be duplicated when being saved in the `ShootState`. In clusters with a large number of `MachineDeployment`s the following error could be observed when trying to create the `ShootState`:
```
rpc error: code = ResourceExhausted desc = trying to send message larger than max (2485683 vs. 2097152)
```

There are actually two issues that caused `Machine`s to be duplicated: 
- The main reason the duplication happens is because the [array variable](https://github.com/gardener/gardener/blob/91e2131d31e1c892f3b67ac42f5c4c44cb1cfa26/pkg/utils/gardener/shootstate/machines.go#L54) in which `Machine`s are collected, is reused while iterating over all `MachineDeployment`s, causing it to grow after each iteration. On each iteration this array is added to a corresponding `MachineDeploymentState`.

- The other issue happens because `Machine`s that do not have a `MachineSet` as an owner reference are mapped to `MachineDeployments` by using their `name` label (name corresponds to the name of the `MachineDeployment`). Then [the same machine is appended multiple times](https://github.com/gardener/gardener/blob/91e2131d31e1c892f3b67ac42f5c4c44cb1cfa26/pkg/utils/gardener/shootstate/machines.go#L72) - for each `MachineSet` that belongs to the same `MachineDeployment` 

With this fix, a ShootState that was originally around 3.2 MiB is reduced to 140KiB 

---

I was also wondering whether to add a check if the `ShootState` exceeds some hard-coded limits of the `kube-apiserver` and `etcd` before allowing the migration to start. 
However, this size might not be exactly equal to the size with which the `ShootState` is created as this happens [much later in the migrate flow](https://github.com/gardener/gardener/blob/78034a9659fff5372a6d2f5ccab83fa956e3922c/pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go#L243-L249). Anyway, this could be handled with a follow-up PR.

--- 

**Which issue(s) this PR fixes**:
Fixes #12579

**Special notes for your reviewer**:
In the first commit I have modified the unit test to demonstrate the issue. Below you can see the uncompressed machine states:

<Details>
<Summary>Expected machine state</Summary>

```
machineDeployments:
  deploy1:
    replicas: 3
    machineSets:
      - metadata:
          name: deploy1-set1
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          annotations:
            some: annotation
        spec:
          machineClass: {}
          template:
            metadata:
              creationTimestamp: null
            spec:
              class: {}
              nodeTemplate:
                metadata:
                  creationTimestamp: null
                spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
      - metadata:
          name: deploy1-set2
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy1
          annotations:
            some: annotation
        spec:
          machineClass: {}
          template:
            metadata:
              creationTimestamp: null
            spec:
              class: {}
              nodeTemplate:
                metadata:
                  creationTimestamp: null
                spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
    machines:
      - metadata:
          name: deploy1-set1-machine1
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            node: nodename
          annotations:
            some: annotation
        spec:
          class: {}
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
      - metadata:
          name: deploy1-set2-machine2
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy1
          annotations:
            some: annotation
        spec:
          class: {}
          providerID: provider-id
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
      - metadata:
          name: deploy1-set2-machine2
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy1
          annotations:
            some: annotation
        spec:
          class: {}
          providerID: provider-id
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
  deploy2:
    replicas: 3
    machineSets:
      - metadata:
          name: deploy2-set3
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          annotations:
            some: annotation
        spec:
          machineClass: {}
          template:
            metadata:
              creationTimestamp: null
            spec:
              class: {}
              nodeTemplate:
                metadata:
                  creationTimestamp: null
                spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
      - metadata:
          name: deploy2-set4
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy2
          annotations:
            some: annotation
        spec:
          machineClass: {}
          template:
            metadata:
              creationTimestamp: null
            spec:
              class: {}
              nodeTemplate:
                metadata:
                  creationTimestamp: null
                spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
    machines:
      - metadata:
          name: deploy2-set3-machine4
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            node: nodename
          annotations:
            some: annotation
        spec:
          class: {}
          providerID: provider-id
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
```

</Details>

<Details>
<Summary>Incorrect machine state </Summary>

```
machineDeployments:
  deploy1:
    replicas: 3
    machineSets:
      - metadata:
          name: deploy1-set1
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          annotations:
            some: annotation
        spec:
          machineClass: {}
          template:
            metadata:
              creationTimestamp: null
            spec:
              class: {}
              nodeTemplate:
                metadata:
                  creationTimestamp: null
                spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
      - metadata:
          name: deploy1-set2
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy1
          annotations:
            some: annotation
        spec:
          machineClass: {}
          template:
            metadata:
              creationTimestamp: null
            spec:
              class: {}
              nodeTemplate:
                metadata:
                  creationTimestamp: null
                spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
    machines:
      - metadata:
          name: deploy1-set1-machine1
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            node: nodename
          annotations:
            some: annotation
        spec:
          class: {}
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
      - metadata:
          name: deploy1-set2-machine2
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy1
          annotations:
            some: annotation
        spec:
          class: {}
          providerID: provider-id
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
      - metadata:
          name: deploy1-set2-machine2
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy1
          annotations:
            some: annotation
        spec:
          class: {}
          providerID: provider-id
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
  deploy2:
    replicas: 3
    machineSets:
      - metadata:
          name: deploy2-set3
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          annotations:
            some: annotation
        spec:
          machineClass: {}
          template:
            metadata:
              creationTimestamp: null
            spec:
              class: {}
              nodeTemplate:
                metadata:
                  creationTimestamp: null
                spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
      - metadata:
          name: deploy2-set4
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy2
          annotations:
            some: annotation
        spec:
          machineClass: {}
          template:
            metadata:
              creationTimestamp: null
            spec:
              class: {}
              nodeTemplate:
                metadata:
                  creationTimestamp: null
                spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
    machines:
      - metadata:
          name: deploy1-set1-machine1
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            node: nodename
          annotations:
            some: annotation
        spec:
          class: {}
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
      - metadata:
          name: deploy1-set2-machine2
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy1
          annotations:
            some: annotation
        spec:
          class: {}
          providerID: provider-id
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
      - metadata:
          name: deploy1-set2-machine2
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy1
          annotations:
            some: annotation
        spec:
          class: {}
          providerID: provider-id
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
      - metadata:
          name: deploy2-set3-machine4
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            node: nodename
          annotations:
            some: annotation
        spec:
          class: {}
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
      - metadata:
          name: deploy2-set4-machine5
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy2
          annotations:
            some: annotation
        spec:
          class: {}
          providerID: provider-id
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
      - metadata:
          name: deploy2-set4-machine5
          namespace: shoot--my-project--my-shoot
          creationTimestamp: null
          labels:
            name: deploy2
          annotations:
            some: annotation
        spec:
          class: {}
          providerID: provider-id
          nodeTemplate:
            metadata:
              creationTimestamp: null
            spec: {}
        status:
          lastOperation:
            lastUpdateTime: null
          currentStatus:
            lastUpdateTime: null
```

</Details>

To summarise the above
- In the expected macine state: 
    - `MachineDeploymentState` for `deploy1` contains the following machines 
        - `deploy1-set1-machine1` and `deploy1-set2-machine2`
    -  `MachineDeploymentState` for `deploy2` contains the following machines
        -  `deploy2-set3-machine4` and `deploy2-set4-machine5` 

- In the incorrect machine state:
    - `MachineDeploymentState` for `deploy1` contains the following machines 
        - `deploy1-set1-machine1`, `deploy1-set2-machine2` and `deploy1-set2-machine2` (duplicated) 
    -  `MachineDeploymentState` for `deploy2` contains the following machines
        -  `deploy1-set1-machine1` (duplicated), `deploy1-set2-machine2` (duplicated), `deploy1-set2-machine2` (duplicated) `deploy2-set3-machine4`, `deploy2-set4-machine5`, `deploy2-set4-machine5` (duplicated)

**Release note**:

```bugfix operator
Fixed an issue that caused `Machine`s to be duplicated when being saved in the `ShootState`. This caused the `ShootState` to grow exponentially large and fail to be created. The issue could occur when there are multiple `MachineDeployments` created for the `Shoot`.
```

### CODE REVIEW

File: pkg/utils/gardener/shootstate/shootstate_test.go [hunk 1]
```diff
@@ -386,8 +386,73 @@ func createMachineObjects(
...
+	ExpectWithOffset(1, fakeSeedClient.Create(ctx, machine5)).To(Succeed())
+
+	machineDeployment3 := &machinev1alpha1.MachineDeployment{
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      "deploy3",
+			Namespace: namespace,
+		},
+		Spec: machinev1alpha1.MachineDeploymentSpec{Replicas: 3},
+	}
+	ExpectWithOffset(1, fakeSeedClient.Create(ctx, machineDeployment3)).To(Succeed())
```
Comment (Kostov6) [inline pkg/utils/gardener/shootstate/shootstate_test.go:452]: Do we need `machineDeployment3`?

**Review by Kostov6 — COMMENTED** [review]
I think this does the same and is more concise:
```golang
		// get machines that have a machine deployment as owner
		machinesForMachineDeployment := machineSetOrDeploymentToMachines[machineDeployment.Name]

		for i, machineSet := range machineSets {
			removeIrrelevantDataFromObject(&machineSets[i])
			// get machines that have a machine set as owner
			machinesForMachineSet := machineSetOrDeploymentToMachines[machineSet.Name]
			machinesForMachineDeployment = append(machinesForMachineDeployment, machinesForMachineSet...)
		}

		for i := range machinesForMachineDeployment {
			removeIrrelevantDataFromObject(&machinesForMachineDeployment[i])
		}
```

File: pkg/utils/gardener/shootstate/shootstate_test.go (hunk 1 above)
Comment (plkokanov) [reply pkg/utils/gardener/shootstate/shootstate_test.go:452]: Yeah, we want to ensure that no entry is added to the state for it because it does not have any machines.

**Comment by plkokanov** [comment]
> I think this does the same and is more concise:
> 
> ```go
> 		// get machines that have a machine deployment as owner
> 		machinesForMachineDeployment := machineSetOrDeploymentToMachines[machineDeployment.Name]
> 
> 		for i, machineSet := range machineSets {
> 			removeIrrelevantDataFromObject(&machineSets[i])
> 			// get machines that have a machine set as owner
> 			machinesForMachineSet := machineSetOrDeploymentToMachines[machineSet.Name]
> 			machinesForMachineDeployment = append(machinesForMachineDeployment, machinesForMachineSet...)
> 		}
> 
> 		for i := range machinesForMachineDeployment {
> 			removeIrrelevantDataFromObject(&machinesForMachineDeployment[i])
> 		}
> ```

Thanks for the great suggestion! I'll try it out.

**Comment by plkokanov** [comment]
@Kostov6 I applied your suggestion, PTAL when you can :)

**Review by Kostov6 — COMMENTED** [review]
/lgtm

File: pkg/utils/gardener/shootstate/machines.go [hunk 2]
```diff
@@ -46,58 +46,69 @@ func computeMachineState(ctx context.Context, seedClient client.Client, namespac
...
-					Annotations: machine.Annotations,
-					Labels:      machine.Labels,
-				}
-				machines[j].Status = machinev1alpha1.MachineStatus{}
+			for j := range machinesForMachineSet {
+				removeIrrelevantDataFromObject(&machinesForMachineSet[j])
 			}
 
-			allMachines = append(allMachines, machines...)
+			machinesForMachineDeployment = append(machinesForMachineDeployment, machinesForMachineSet...)
```
Comment (ialidzhikov) [inline pkg/utils/gardener/shootstate/machines.go:67]: Not related to this PR but I was wondering in which cases a Machine has ownerReference to the MachineSet and in which cases the ownerReference is missing and the Machine has a `name` label to the machine? It would be helpful if this is somewhere documented in the code.

Looking into the [`BuildOwnerToMachinesMap` func](https://github.com/gardener/gardener/blob/485c25124ea536e4610c627109017dd34d434921/pkg/utils/gardener/machines.go#L33-L50), a Machine is added to the map either by MachineSet key or MachineDeployment key. This is how we make sure that Machine is not added twice in the final result, right?

---

> - The other issue happens because `Machine`s that do not have a `MachineSet` as an owner reference are mapped to `MachineDeployments` by using their `name` label (name corresponds to the name of the `MachineDeployment`). Then [the same machine is appended multiple times](https://github.com/gardener/gardener/blob/91e2131d31e1c892f3b67ac42f5c4c44cb1cfa26/pkg/utils/gardener/shootstate/machines.go#L72) - for each `MachineSet` that belongs to the same `MachineDeployment` 

I was not able to follow that part. Is it really an issue in the master branch? As far as I understand, a Machine is either added by MachineSet key or MachineDeployment key.
Let me know if I miss something. What was the fix for the 2nd issue?

File: pkg/utils/gardener/shootstate/machines.go [hunk 3]
```diff
@@ -46,58 +46,61 @@ func computeMachineState(ctx context.Context, seedClient client.Client, namespac
...
+			// get machines that have a machine set as owner
+			machinesForMachineSet := machineSetOrDeploymentToMachines[machineSet.Name]
+			machinesForMachineDeployment = append(machinesForMachineDeployment, machinesForMachineSet...)
+		}
+
+		for i := range machinesForMachineDeployment {
+			removeIrrelevantDataFromObject(&machinesForMachineDeployment[i])
 		}
 
 		state.MachineDeployments[machineDeployment.Name] = &MachineDeploymentState{
```
Comment (ialidzhikov) [inline pkg/utils/gardener/shootstate/machines.go:74]: Not introduced with this PR but we could create the `state.MachineDeployments` map with the correct size since the beginning to save some memory allocations.

Suggestion:
```diff
diff --git a/pkg/utils/gardener/shootstate/machines.go b/pkg/utils/gardener/shootstate/machines.go
index aec26ef76f..28a5079b8d 100644
--- a/pkg/utils/gardener/shootstate/machines.go
+++ b/pkg/utils/gardener/shootstate/machines.go
@@ -34,13 +34,13 @@ type MachineState struct {
 }
 
 func computeMachineState(ctx context.Context, seedClient client.Client, namespace string) (*MachineState, error) {
-	state := &MachineState{MachineDeployments: make(map[string]*MachineDeploymentState)}
-
 	machineDeployments := &machinev1alpha1.MachineDeploymentList{}
 	if err := seedClient.List(ctx, machineDeployments, client.InNamespace(namespace)); err != nil {
 		return nil, err
 	}
 
+	state := &MachineState{MachineDeployments: make(map[string]*MachineDeploymentState, len(machineDeployments.Items))}
+
 	machineDeploymentToMachineSets, err := getMachineDeploymentToMachineSetsMap(ctx, seedClient, namespace)
 	if err != nil {
 		return nil, err

```

**Review by ialidzhikov — COMMENTED** [review]
Thanks for describing in details the issue(s)! 1 question and 1 minor suggestion inline. Otherwise lgtm.

File: pkg/utils/gardener/shootstate/machines.go (hunk 2 above)
Comment (plkokanov) [reply pkg/utils/gardener/shootstate/machines.go:67]: > Not related to this PR but I was wondering in which cases a Machine has ownerReference to the MachineSet and in which cases the ownerReference is missing and the Machine has a name label to the machine? It would be helpful if this is somewhere documented in the code.

I also do not know, but did not want to change this logic. It was present since the beginning of CPM. Perhaps someone from MCM team could answer?  @aaronfern @takoverflow @elankath 

---

> Looking into the [BuildOwnerToMachinesMap func](https://github.com/gardener/gardener/blob/485c25124ea536e4610c627109017dd34d434921/pkg/utils/gardener/machines.go#L33-L50), a Machine is added to the map either by MachineSet key or MachineDeployment key. This is how we make sure that Machine is not added twice in the final result, right?

That is correct, the issue with the duplication comes with the way the elements of the map are used in the following for loops.

The [for loop in the old code](https://github.com/gardener/gardener/blob/c22c7d34c08625888481772d16d47917ba6e8fc0/pkg/utils/gardener/shootstate/machines.go#L61) was iterating over all MachineSets, and for each MachineSet it was [appending the machine that points directly to a MachineDeployment to the resulting array](https://github.com/gardener/gardener/blob/c22c7d34c08625888481772d16d47917ba6e8fc0/pkg/utils/gardener/shootstate/machines.go#L72)

So the issue happens when you have something like the following dependency (old MachineSet, could be the one that was left after a rollout) :

```
                      old MachineSet ---owner-ref---> MachineDeployment
                                                             ^
                                                             |
Machine1 ---owner-ref---> MachineSet ---owner-ref------------+
                                                             |
Machine2 ----------------------label-------------------------+
```


This would result in Machine2 being present 2 times (once for each `MachineSet` that belongs to the same MachineDeployment)
This scenario is present in the tests to reproduce the error.

--- 

With this PR `Machine2` is handled outside of this loop: https://github.com/gardener/gardener/blob/4f1e3b579c060f44e4030c16b8ed209f2782813e/pkg/utils/gardener/shootstate/machines.go#L61-L65

Btw, now that I look at it again, I should create an entirely new array for machines instead of reusing the `machineSetOrDeploymentToMachines[machineDeployment.Name]` slice. If it still has capacity we would be indirectly mutating it here:
https://github.com/gardener/gardener/blob/4f1e3b579c060f44e4030c16b8ed209f2782813e/pkg/utils/gardener/shootstate/machines.go#L67
This doesn't cause any issues now, because the `machineDeployment.Name` is never reused, but it's not ideal.

File: pkg/utils/gardener/shootstate/machines.go (hunk 3 above)
Comment (plkokanov) [reply pkg/utils/gardener/shootstate/machines.go:74]: There could be `MachineDeployments` without any `MachineSets` or `Machines` associated with them, then we want to avoid adding these in the `ShootState`. The following check was also present in the old code;
https://github.com/gardener/gardener/blob/4f1e3b579c060f44e4030c16b8ed209f2782813e/pkg/utils/gardener/shootstate/machines.go#L55-L58

Let me sync this offline with MCM folks, about when such cases could occur.

File: pkg/utils/gardener/shootstate/machines.go [hunk 4]
```diff
@@ -46,58 +46,61 @@ func computeMachineState(ctx context.Context, seedClient client.Client, namespac
...
 
-	var allMachines []machinev1alpha1.Machine
 	for _, machineDeployment := range machineDeployments.Items {
 		machineSets, ok := machineDeploymentToMachineSets[machineDeployment.Name]
 		if !ok {
 			continue
 		}
 
+		// get machines that have a machine deployment as owner
+		machinesForMachineDeployment := append([]machinev1alpha1.Machine{}, machineSetOrDeploymentToMachines[machineDeployment.Name]...)
```
Comment (ialidzhikov) [inline pkg/utils/gardener/shootstate/machines.go]: VS code suggests:
> Replace append with slices.Clone modernize [slicesclone](https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize#slicesclone)

```suggestion
		machinesForMachineDeployment := slices.Clone(machineSetOrDeploymentToMachines[machineDeployment.Name])
```

**Review by ialidzhikov — APPROVED** [review]
/lgtm
