### PR TITLE
Don't delete tunnel secrets on deletion

### LINKED ISSUE #2458: Failed to delete hibernated cluster w/ KAS network proxy
**How to categorize this issue?**

/area control-plane
/kind bug
/priority normal

**What happened**:
A 1.18.x shoot which had been created and hibernated could not be deleted after the `KonnectivityTunnel` feature gate was activated.

The Kube-Apiserver hung in the init state because of the following events:

```
  Warning  FailedMount  1s (x6 over 17s)  kubelet, ip-10-242-20-136.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "vpn-seed-tlsauth" : secret "vpn-seed-tlsauth" not found
  Warning  FailedMount  1s (x6 over 17s)  kubelet, ip-10-242-20-136.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "vpn-seed" : secret "vpn-seed" not found
```

**What you expected to happen**:
The shoot is deleted successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Disable `KonnectivityTunnel` (https://github.com/gardener/gardener/pull/2251)
1. Create 1.18.x shoot
1. Hibernate shoot
1. Activate `KonnectivityTunnel`
1. Reconcile shoot
1. Delete shoot

**Environment**:

- Gardener version: v1.6.1

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area networking
/kind bug
/priority normal

**What this PR does / why we need it**:
If the `KonnectivityTunnel` was enabled while a Shoot was hibernated, it can't be deleted without being reconciled first.

**Which issue(s) this PR fixes**:
Fixes #2458 

**Special notes for your reviewer**:
/invite @zanetworker 
@rfranzke and I decided to not redeploy the API server on deletion, as we are not sure about all the consequences and rather just not delete the vpn secrets on deletion, so the API server can get ready again.

**Release note**:

```improvement operator
An issue has been fixed, which caused the deletion of hibernated Shoots to be blocked if the `KonnectivityTunnel` has been enabled while the Shoot was hibernated.
```

### CODE REVIEW

**Review by zanetworker — DISMISSED** [review]
> @rfranzke and I decided to not redeploy the API server on deletion, as we are not sure about all the consequences and rather just not delete the VPN secrets on deletion, so the API server can get ready again. 

That's another way to do it but we anyway need to redeploy instead of scale for #1240 right? 

But regardless it fixes the issue at hand, so /lgtm

**Comment by rfranzke** [comment]
@zanetworker yes, but we can't overlook the implications/side-effects this has now in a short period of time. Given that @tim-ebert is currently working on a new release candidate we preferred to discuss #1240 after the release was made. I can't remember anymore exactly why we had postponed #1240 but it's already open a long time and probably there was a reason.

**Comment by timebertt** [comment]
> That's another way to do it but we anyway need to redeploy instead of scale for #1240 right?

Yes, exactly. As we two already discussed, we also have to think about all the other components we should redeploy.
So let's take some time somewhen after the release to figure out a proper way to solve the #1240 in a general sense.

**Review by rfranzke — DISMISSED** [review]

**Review by rfranzke — APPROVED** [review]

File: pkg/operation/botanist/secrets.go [hunk 1]
```diff
@@ -90,13 +90,15 @@ func (b *Botanist) GenerateAndSaveSecrets(ctx context.Context) error {
...
 	}
 
-	if b.Shoot.KonnectivityTunnelEnabled {
-		if err := b.cleanupTunnelSecrets(ctx, &gardenerResourceDataList, "vpn-seed", "vpn-seed-tlsauth", "vpn-shoot"); err != nil {
-			return err
-		}
-	} else {
-		if err := b.cleanupTunnelSecrets(ctx, &gardenerResourceDataList, common.KonnectivityServerKubeconfig, common.KonnectivityServerCertName); err != nil {
-			return err
+	if b.Shoot.Info.DeletionTimestamp != nil {
```
Comment (timuthy) [inline pkg/operation/botanist/secrets.go:93]: Shouldn't it be
```
b.Shoot.Info.DeletionTimestamp == nil
```
?
/cc @tim-ebert

Comment (timebertt) [reply pkg/operation/botanist/secrets.go:93]: Indeed. Nice catch!

Comment (timuthy) [reply pkg/operation/botanist/secrets.go:93]: Are you going to fix it in another PR?

Comment (timebertt) [reply pkg/operation/botanist/secrets.go:93]: Yep, done: #2562
