### PR TITLE
`ManagedResource` controller should recreate `ConfigMap`s/`Secret`s on invalid update

### LINKED ISSUE #7452: `ManagedResource` controller should re-create immutable `ConfigMap`s/`Secret`s when update is denied
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What would you like to be added**:
`gardenlet` and extensions create immutable `ConfigMap`s/`Secret`s via `ManagedResource`s in the shoot cluster. Sometimes, end-users delete and re-create them while modifying their content. Eventually, `gardener-resource-manager` fails to reconcile those, e.g. 

```
error during apply of object "v1/ConfigMap/kube-system/node-local-dns-835fb0a6": ConfigMap "node-local-dns-835fb0a6" is invalid: data: Forbidden: field is immutable when `immutable` is set
```

This situation does not self-heal today.

Instead, `gardener-resource-manager` should re-create such resources so that it can reconcile its desired state.

**Why is this needed**:
Improve ops productivity.

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
ManagedResource controller now recreates immutable resources on invalid update error.
Read the issue description for more details.

**Which issue(s) this PR fixes**:
Fixes #7452

**Special notes for your reviewer**:

**Release note**:

```other operator
The resource-manager now recreates immutable Secrets/ConfigMaps on invalid update error.
```

### CODE REVIEW

File: test/integration/resourcemanager/managedresource/resource_suite_test.go [hunk 1]
```diff
@@ -123,8 +123,9 @@ var _ = BeforeSuite(func() {
 
 	Expect((&managedresource.Reconciler{
 		Config: config.ManagedResourceControllerConfig{
-			ConcurrentSyncs:     pointer.Int(5),
-			SyncPeriod:          &metav1.Duration{Duration: 500 * time.Millisecond},
+			ConcurrentSyncs: pointer.Int(5),
+			// Higher sync period is used since we don't want the changes in the test to be reconciled back quickly.
+			SyncPeriod:          &metav1.Duration{Duration: time.Minute},
```
Comment (rfranzke) [inline test/integration/resourcemanager/managedresource/resource_suite_test.go]: Why is this suddenly necessary? The comment is not quite helpful 👀 (at least I didn't understand the reason).

File: pkg/resourcemanager/controller/managedresource/reconciler.go [hunk 2]
```diff
@@ -515,12 +517,27 @@ func (r *Reconciler) applyNewResources(ctx context.Context, log logr.Logger, ori
 				return err
 			}
 
-			if apierrors.IsInvalid(err) && operationResult == controllerutil.OperationResultUpdated && deleteOnInvalidUpdate(current) {
```
Comment (rfranzke) [inline pkg/resourcemanager/controller/managedresource/reconciler.go:518]: Would it be possible to rather extend the `deleteOnInvalidUpdate` function instead of hard-coding the ConfigMap/Secret handling here?

File: test/integration/resourcemanager/managedresource/resource_suite_test.go (hunk 1 above)
Comment (shafeeqes) [reply test/integration/resourcemanager/managedresource/resource_suite_test.go]: In the test case, we need to delete, recreate it with different data and immutable, then reconcile the managedresource to assert that it is recreated. If the sync period is `500ms`, immediately after deletion the resource would be recreated.

File: test/integration/resourcemanager/managedresource/resource_test.go [hunk 3]
```diff
@@ -985,6 +985,49 @@ var _ = Describe("ManagedResource controller tests", func() {
 			})
 		})
 	})
+
+	Describe("Immutable resources", func() {
+		It("should fail to apply the resource if the update is invalid", func() {
+			newData := map[string]string{
+				"foo": "bar",
+			}
```
Comment (ialidzhikov) [inline test/integration/resourcemanager/managedresource/resource_test.go]: Nit: You could declare `newDate` right before its usage.

```golang
			newData := map[string]string{
				"foo": "bar",
			}

			oldData := configMap.Data
			configMap.Data = newData
```

File: test/integration/resourcemanager/managedresource/resource_test.go [hunk 4]
```diff
@@ -985,6 +985,49 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(Succeed())
+				return managedResource.Status.Conditions
+			}).Should(
+				ContainCondition(OfType(resourcesv1alpha1.ResourcesApplied), WithStatus(gardencorev1beta1.ConditionTrue), WithReason(resourcesv1alpha1.ConditionApplySucceeded)),
+			)
+
+			Expect(testClient.Delete(ctx, configMap)).To(Succeed())
+
+			configMap.Data = newData
+			configMap.Immutable = pointer.Bool(true)
```
Comment (ialidzhikov) [inline test/integration/resourcemanager/managedresource/resource_test.go]: Nit: We know that for reproducing the issue it is not required the initial ConfigMap to be immutable. But does it make sense to make it immutable to be closer to the real world?

File: test/integration/resourcemanager/managedresource/resource_test.go [hunk 5]
```diff
@@ -985,6 +985,49 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+			}
+
+			Eventually(func(g Gomega) []gardencorev1beta1.Condition {
+				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(managedResource), managedResource)).To(Succeed())
+				return managedResource.Status.Conditions
+			}).Should(
+				ContainCondition(OfType(resourcesv1alpha1.ResourcesApplied), WithStatus(gardencorev1beta1.ConditionTrue), WithReason(resourcesv1alpha1.ConditionApplySucceeded)),
+			)
+
+			Expect(testClient.Delete(ctx, configMap)).To(Succeed())
```
Comment (ialidzhikov) [inline test/integration/resourcemanager/managedresource/resource_test.go:1009]: Nit: We could wait for the ConfigMap deletion to complete before creating the new ConfigMap:
```suggestion
			Expect(testClient.Delete(ctx, configMap)).To(Succeed())

			Eventually(func() error {
				return testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)
			}).Should(BeNotFoundError())
```

**Review by ialidzhikov — COMMENTED** [review]
We had a look together with @acumino. Minor comments inline. We were also able to verify that the change works as expected.

File: test/integration/resourcemanager/managedresource/resource_test.go [hunk 6]
```diff
@@ -977,6 +985,58 @@ var _ = Describe("ManagedResource controller tests", func() {
...
+			Eventually(func() error {
+				return testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)
+			}).Should(BeNotFoundError())
+
+			newData := map[string]string{
+				"foo": "bar",
+			}
+			oldData := configMap.Data
+			configMap.Data = newData
+			configMap.Immutable = pointer.Bool(true)
```
Comment (acumino) [inline test/integration/resourcemanager/managedresource/resource_test.go]: Now that the immutable field is set at the start. I just wanted to let you know that this line is not needed.
```suggestion
```

**Review by acumino — CHANGES_REQUESTED** [review]

**Review by acumino — COMMENTED** [review]
/lgtm

File: test/integration/resourcemanager/managedresource/resource_suite_test.go (hunk 1 above)
Comment (rfranzke) [reply test/integration/resourcemanager/managedresource/resource_suite_test.go]: Sorry, that didn't help me to understand how this is related to this PR and why it wasn't causing problems before it.

Comment (shafeeqes) [reply test/integration/resourcemanager/managedresource/resource_suite_test.go]: Only in this test, we are trying to assert an intermediate state. (The user tries to delete the secret and recreates it with their data and as immutable). If the controller acts every 500ms, then this would not be possible.
All other tests are fine since they expect an end state only.

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

File: test/integration/resourcemanager/managedresource/resource_suite_test.go (hunk 1 above)
Comment (rfranzke) [reply test/integration/resourcemanager/managedresource/resource_suite_test.go]: OK, thanks. Well, let's go ahead then.
