### PR TITLE
Reintroduce `compare-k8s-feature-gates.sh`

### LINKED ISSUE #11198: Fix broken `compare-k8s-feature-gates.sh` script for Kubernetes versions >= v1.32
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What would you like to be added**:

Re-add the `compare-k8s-feature-gates.sh` script that has been removed with the PR for supporting Kubernetes version v1.32:
https://github.com/gardener/gardener/pull/11197/commits/bb15d84ba5bba68268b0e90c38acc3c479b63cc8#diff-2a2430d81164a51d4de9ddf73b7dbb285793003eef6baad874b77f0808a73919

The script was removed because it produced false output when comparing the feature gates between Kubernetes versions `v1.31` and `v1.32` (see the _Expected_ and _Actual_ examples below).

The root cause of the script's behavior is upstream changes in the Kubernetes repository.
The repository already contained the [`versioned_kube_features.go`](https://github.com/kubernetes/kubernetes/blob/release-1.31/pkg/features/versioned_kube_features.go) in `v1.31`.

However, with `v1.32` some (not all) feature gates have been moved to [`versioned_kube_features.go`](https://github.com/kubernetes/kubernetes/blob/release-1.32/pkg/features/versioned_kube_features.go).
Hence, our script reports too many feature gates to be removed when their code definition has just been moved to `versioned_kube_features.go`.

**Expected:**

<details>

<summary>Comparing v1.30 with v1.31</summary>

```shell
./hack/compare-k8s-feature-gates.sh 1.30 1.31
Feature gates added in 1.31 compared to 1.30:
AllowDNSOnlyNodeCSR
AllowInsecureKubeletCertificateSigningRequests
AnonymousAuthConfigurableEndpoints
AuthorizeNodeWithSelectors
AuthorizeWithSelectors
ConcurrentWatchObjectDecode
CoordinatedLeaderElection
DRAControlPlaneController
DisableAllocatorDualWrite
ImageVolume
ReloadKubeletServerCertificateFile
ResilientWatchCacheInitialization
ResourceHealthStatus
SupplementalGroupsPolicy
WatchCacheInitializationPostStartHook

Feature gates removed in 1.31 compared to 1.30:
APIPriorityAndFairness
CSIMigrationRBD
CSINodeExpandSecret
ConsistentHTTPGetHandlers
CustomResourceValidationExpressions
DefaultHostNetworkHostPortsInPodTemplates
InTreePluginAWSUnregister
InTreePluginAzureDiskUnregister
InTreePluginAzureFileUnregister
InTreePluginGCEUnregister
InTreePluginOpenStackUnregister
InTreePluginRBDUnregister
InTreePluginvSphereUnregister
JobReadyPods
ReadWriteOncePod
ServiceNodePortStaticSubrange
SkipReadOnlyValidationGCE

Feature gates locked to default in 1.31 compared to 1.30:
AppArmor                                 Default:  true
AppArmorFields                           Default:  true
DevicePluginCDIDevices                   Default:  true
DisableCloudProviders                    Default:  true
DisableKubeletCloudCredentialProviders   Default:  true
ElasticIndexedJob                        Default:  true
JobPodFailurePolicy                      Default:  true
KubeProxyDrainingTerminatingNodes        Default:  true
LogarithmicScaleDown                     Default:  true
PDBUnhealthyPodEvictionPolicy            Default:  true
PersistentVolumeLastPhaseTransitionTime  Default:  true
PodDisruptionConditions                  Default:  true
StatefulSetStartOrdinal                  Default:  true
```

</details>

**Actual:**

<details>

<summary>Comparing v1.31 with v1.32</summary>

```shell
./hack/compare-k8s-feature-gates.sh 1.31 1.32
Feature gates added in 1.32 compared to 1.31:
ClientsAllowCBOR
ClientsPreferCBOR

Feature gates removed in 1.32 compared to 1.31:
APIListChunking
APIResponseCompression
APIServerIdentity
APIServerTracing
APIServingWithRoutine
AdmissionWebhookMatchConditions
AggregatedDiscoveryEndpoint
AllowDNSOnlyNodeCSR
AllowInsecureKubeletCertificateSigningRequests
AllowServiceLBStatusOnNonLB
AnonymousAuthConfigurableEndpoints
AnyVolumeDataSource
AppArmor
AppArmorFields
AuthorizeNodeWithSelectors
AuthorizeWithSelectors
CPUManager
CPUManagerPolicyAlphaOptions
CPUManagerPolicyBetaOptions
CPUManagerPolicyOptions
CRDValidationRatcheting
CSIMigrationPortworx
CSIVolumeHealth
CloudControllerManagerWebhook
CloudDualStackNodeIPs
ClusterTrustBundle
ClusterTrustBundleProjection
ComponentSLIs
ConcurrentWatchObjectDecode
ConsistentListFromCache
ContainerCheckpoint
CoordinatedLeaderElection
CronJobsScheduledAnnotation
CrossNamespaceVolumeDataSource
CustomCPUCFSQuotaPeriod
CustomResourceFieldSelectors
DRAControlPlaneController
DevicePluginCDIDevices
DisableAllocatorDualWrite
DisableCloudProviders
DisableKubeletCloudCredentialProviders
DisableNodeKubeProxyVersion
DynamicResourceAllocation
EfficientWatchResumption
ElasticIndexedJob
EventedPLEG
ExecProbeTimeout
GracefulNodeShutdown
GracefulNodeShutdownBasedOnPodPriority
HPAContainerMetrics
HPAScaleToZero
HonorPVReclaimPolicy
ImageMaximumGCAge
ImageVolume
InPlacePodVerticalScaling
InTreePluginPortworxUnregister
JobBackoffLimitPerIndex
JobManagedBy
JobPodFailurePolicy
JobPodReplacementPolicy
JobSuccessPolicy
KMSv1
KMSv2
KMSv2KDF
KubeProxyDrainingTerminatingNodes
KubeletCgroupDriverFromCRI
KubeletInUserNamespace
KubeletPodResourcesDynamicResources
KubeletPodResourcesGet
KubeletSeparateDiskGC
KubeletTracing
LegacyServiceAccountTokenCleanUp
LoadBalancerIPMode
LocalStorageCapacityIsolationFSQuotaMonitoring
LogarithmicScaleDown
MatchLabelKeysInPodAffinity
MatchLabelKeysInPodTopologySpread
MaxUnavailableStatefulSet
MemoryManager
MemoryQoS
MinDomainsInPodTopologySpread
MultiCIDRServiceAllocator
MutatingAdmissionPolicy
NFTablesProxyMode
NewVolumeManagerReconstruction
NodeInclusionPolicyInPodTopologySpread
NodeLogQuery
NodeOutOfServiceVolumeDetach
NodeSwap
OpenAPIEnums
PDBUnhealthyPodEvictionPolicy
PersistentVolumeLastPhaseTransitionTime
PodAndContainerStatsFromCRI
PodDeletionCost
PodDisruptionConditions
PodHostIPs
PodIndexLabel
PodLifecycleSleepAction
PodReadyToStartContainersCondition
PodSchedulingReadiness
PortForwardWebsockets
ProcMountType
QOSReserved
RecoverVolumeExpansionFailure
RecursiveReadOnlyMounts
RelaxedEnvironmentVariableValidation
ReloadKubeletServerCertificateFile
RemainingItemCount
ResilientWatchCacheInitialization
ResourceHealthStatus
RetryGenerateName
RotateKubeletServerCertificate
RuntimeClassInImageCriApi
SELinuxMount
SELinuxMountReadWriteOncePod
SchedulerQueueingHints
SeparateCacheWatchRPC
SeparateTaintEvictionController
ServerSideApply
ServerSideFieldValidation
ServiceAccountTokenJTI
ServiceAccountTokenNodeBinding
ServiceAccountTokenNodeBindingValidation
ServiceAccountTokenPodNodeInfo
ServiceTrafficDistribution
SidecarContainers
SizeMemoryBackedVolumes
StableLoadBalancerNodeSet
StatefulSetAutoDeletePVC
StatefulSetStartOrdinal
StorageNamespaceIndex
StorageVersionAPI
StorageVersionHash
StorageVersionMigrator
StrictCostEnforcementForVAP
StrictCostEnforcementForWebhooks
StructuredAuthenticationConfiguration
StructuredAuthorizationConfiguration
SupplementalGroupsPolicy
TopologyAwareHints
TopologyManagerPolicyAlphaOptions
TopologyManagerPolicyBetaOptions
TopologyManagerPolicyOptions
TranslateStreamCloseWebsocketRequests
UnauthenticatedHTTP2DOSMitigation
UnknownVersionInteroperabilityProxy
UserNamespacesPodSecurityStandards
UserNamespacesSupport
ValidatingAdmissionPolicy
VolumeAttributesClass
VolumeCapacityPriority
WatchBookmark
WatchCacheInitializationPostStartHook
WatchFromStorageWithoutResourceVersion
WatchList
WinDSR
WinOverlay
WindowsHostNetwork
ZeroLimitedNominalConcurrencyShares

Feature gates locked to default in 1.32 compared to 1.31:
```

</details>

**Why is this needed**:

The script eases the process of supporting a new Kubernetes version in Gardener drastically and was referenced in the corresponding guide:
https://github.com/gardener/gardener/blob/ada2f4810f4a964c93ff36f74c23a39af8dd43a9/docs/development/new-kubernetes-version.md#:~:text=To%20maintain%20this%20list%20for%20new%20Kubernetes%20versions%2C%20run%20hack/compare%2Dk8s%2Dfeature%2Dgates.sh%20%3Cold%2Dversion%3E%20%3Cnew%2Dversion%3E%20(e.g.%20hack/compare%2Dk8s%2Dfeature%2Dgates.sh%20v1.26%20v1.27).

### PR DESCRIPTION
**Pull request by Kostov6**
**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:
This PR reintroduces `compare-k8s-feature-gates.sh` 

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/11198

**Special notes for your reviewer**:
```bash
out_dir=$(mktemp -d)
function cleanup_output {
    rm -rf "$out_dir"
}
trap cleanup_output EXIT
```
can be replaced with
```bash
mkdir debug
out_dir=debug
```
to observe generated files when testing

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: hack/compare-k8s-feature-gates.sh [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+  # TODO Drop this when Kubernetes v1.34 gets released
+  if [ "$version" == "1.32" ]; then
+    versions_dir="test/featuregates_linter/test_data"
+  fi
+
+  wget -q -O - "https://raw.githubusercontent.com/kubernetes/kubernetes/release-${version}/${versions_dir}/versioned_feature_list.yaml" > "${out_dir}/versioned_featuregates_${version}.yaml"
+  wget -q -O - "https://raw.githubusercontent.com/kubernetes/kubernetes/release-${version}/${versions_dir}/unversioned_feature_list.yaml" > "${out_dir}/unversioned_featuregates_${version}.yaml"
+
+  yq eval '.[] | .name' "${out_dir}/versioned_featuregates_${version}.yaml" > "${out_dir}/featuregates_list_${version}.yaml"
+  yq eval '.[] | .name' "${out_dir}/unversioned_featuregates_${version}.yaml" >> "${out_dir}/featuregates_list_${version}.yaml"
```
Comment (RadaBDimitrova) [inline hack/compare-k8s-feature-gates.sh]: Is `eval` really needed here? I think we can skip it, same for other occurrences.

**Review by RadaBDimitrova — COMMENTED** [review]
Small nit, otherwise lgtm.

**Review by RadaBDimitrova — COMMENTED** [review]
/lgtm

File: hack/compare-k8s-feature-gates.sh [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+#
+# SPDX-License-Identifier: Apache-2.0
+
+set -e
+
+usage() {
+  echo "Usage:"
+  echo "> compare-k8s-feature-gates.sh [ -h | <old version> <new version> ]"
+  echo
+  echo ">> For example: compare-k8s-feature-gates.sh 1.26 1.27"
```
Comment (ialidzhikov) [inline hack/compare-k8s-feature-gates.sh]: The example doesn't work. For which K8s versions exactly this script works? Could you please properly document it? For me the script only works for the versions `1.32 1.33`.

File: hack/compare-k8s-feature-gates.sh [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+}
+trap cleanup_output EXIT
+
+for version in "${versions[@]}"; do
+  versions_dir=test/compatibility_lifecycle/reference
+  
+  # TODO Drop this when Kubernetes v1.34 gets released
+  if [ "$version" == "1.32" ]; then
+    versions_dir="test/featuregates_linter/test_data"
+  fi
```
Comment (ialidzhikov) [inline hack/compare-k8s-feature-gates.sh]: 1. Why we have to drop the handling for K8s 1.32 when K8s 1.34 gets released? Theoretically, we want such script to work for any available K8s versions and not only for the K8s versions that we are about to add support for.

2. From https://github.com/gardener/gardener/blob/v1.118.2/docs/development/process.md#todo-statements:
> Each TODO statement should have an associated person and state when it can be removed.

I don't see associated person with this TODO. Anyways, let's remove this TODO if possible so that the script can support also old K8s versions.

File: hack/compare-k8s-feature-gates.sh [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+
+ # Get the list of versioned and unversioned feature gates. After v1.34+ unversioned_feature_list.yaml should most likely be dropped
```
Comment (ialidzhikov) [inline hack/compare-k8s-feature-gates.sh]:
```suggestion
  # Get the list of versioned and unversioned feature gates. After v1.34+ unversioned_feature_list.yaml should most likely be dropped
```

File: hack/compare-k8s-feature-gates.sh [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+  wget -q -O - "https://raw.githubusercontent.com/kubernetes/kubernetes/release-${version}/${versions_dir}/versioned_feature_list.yaml" > "${out_dir}/versioned_featuregates_${version}.yaml"
+  wget -q -O - "https://raw.githubusercontent.com/kubernetes/kubernetes/release-${version}/${versions_dir}/unversioned_feature_list.yaml" > "${out_dir}/unversioned_featuregates_${version}.yaml"
```
Comment (ialidzhikov) [inline hack/compare-k8s-feature-gates.sh]: What is the purpose of unversioned feature gates? After https://github.com/kubernetes/kubernetes/commit/088daf472b7d1ed4502aef211efca6653b05ff59 it is obsolete and no longer generated/updated?

Does it contain feature gates which are not bound to any K8s version? I am confused about this file.

File: hack/compare-k8s-feature-gates.sh [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+echo
+echo "Feature gates locked to default true:"
+# Get all feature gate names that have a version spec containing $2, are locked to default with default value of true
+yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == true)) | .name' "${out_dir}/versioned_featuregates_${version}.yaml"
+yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == true)) | .name' "${out_dir}/unversioned_featuregates_${version}.yaml"
+echo
+echo "Feature gates locked to default false:"
+# Get all feature gate names that have a version spec containing $2, are locked to default with default value of false
+yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == false)) | .name' "${out_dir}/versioned_featuregates_${version}.yaml"
+yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == false)) | .name' "${out_dir}/unversioned_featuregates_${version}.yaml"
```
Comment (ialidzhikov) [inline hack/compare-k8s-feature-gates.sh]: Are these all the features gates locked to default true/false? Don't we need only the feature gates which are locked to default true/false compared to the old version?

Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh]: For reference, the old revision of the script was reporting only the locked to default feature gates compared to the old version. Ref https://github.com/gardener/gardener/blob/d4d2c39b9f50fc414210213885cf7d24d7fb4351/hack/compare-k8s-feature-gates.sh#L74-L76

File: hack/compare-k8s-feature-gates.sh [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+
+versions=("$1" "$2")
+out_dir=$(mktemp -d)
+function cleanup_output {
+    rm -rf "$out_dir"
+}
+trap cleanup_output EXIT
+
+for version in "${versions[@]}"; do
+  versions_dir=test/compatibility_lifecycle/reference
```
Comment (plkokanov) [inline hack/compare-k8s-feature-gates.sh]: Why did you chose to use generated files for tests instead of:
https://github.com/kubernetes/kubernetes/blob/release-1.31/pkg/features/kube_features.go for k8s <= `v1.31` and k8s >= `1.33` (although with different parsing for >= `1.33`)
https://github.com/kubernetes/kubernetes/blob/release-1.32/pkg/features/versioned_kube_features.go for k8s == `v1.32` 

When parsing the versioned features, maybe you can only check if there is an entry wrt the new version (second argument that is passed to the script). There should be listed if anything was locked to default, etc ... Example:
https://github.com/kubernetes/kubernetes/blob/76747b4eed8b04f3ceaf8d393bf77fdbcb561979/pkg/features/kube_features.go#L1030
If something was removed in the new k8s version, then it would be completely missing from the list.

I still haven't gone through the entire [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/4330-compatibility-versions/README.md) that proposed this change, but it seems that versioned kube features is the way to go forward, with the main idea being that you can now "emulate" features from older versions in newer versions to ease upgrades.

**Review by plkokanov — CHANGES_REQUESTED** [review]
Thanks for the PR 🚀 !

File: hack/compare-k8s-feature-gates.sh (hunk 5 above)
Comment (Kostov6) [reply hack/compare-k8s-feature-gates.sh]: Yes and v1.32 contains unversioned feature gates
```
❯ cat debug/unversioned_featuregates_1.32.yaml 
- name: ContextualLogging
  versionedSpecs:
  - default: true
    lockToDefault: false
    preRelease: Beta
    version: ""
- name: LoggingAlphaOptions
  versionedSpecs:
  - default: false
    lockToDefault: false
    preRelease: Alpha
    version: ""
- name: LoggingBetaOptions
  versionedSpecs:
  - default: true
    lockToDefault: false
    preRelease: Beta
    version: ""
```

As you suggested we support old versions this seems nessesary

File: hack/compare-k8s-feature-gates.sh (hunk 6 above)
Comment (Kostov6) [reply hack/compare-k8s-feature-gates.sh]: `select(.version == "'$2'" and .lockToDefault == true and .default == true)` selects feature gates that have a version spec containing the new version that has `lockedToDefault` set to true or false. Example:
```go
	TopologyAwareHints: {
		{Version: version.MustParse("1.21"), Default: false, PreRelease: featuregate.Alpha},
		{Version: version.MustParse("1.23"), Default: false, PreRelease: featuregate.Beta},
		{Version: version.MustParse("1.24"), Default: true, PreRelease: featuregate.Beta},
		{Version: version.MustParse("1.33"), Default: true, PreRelease: featuregate.GA, LockToDefault: true},
	},
```
and 
```go
	AllowServiceLBStatusOnNonLB: {
		{Version: version.MustParse("1.0"), Default: true, PreRelease: featuregate.GA},
		{Version: version.MustParse("1.29"), Default: false, PreRelease: featuregate.Deprecated},
		{Version: version.MustParse("1.32"), Default: false, PreRelease: featuregate.Deprecated, LockToDefault: true}, // remove in 1.35
	},

	AnyVolumeDataSource: {
		{Version: version.MustParse("1.18"), Default: false, PreRelease: featuregate.Alpha},
		{Version: version.MustParse("1.24"), Default: true, PreRelease: featuregate.Beta},
		{Version: version.MustParse("1.33"), Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // GA in 1.33 -> remove in 1.36
	},
```

File: hack/compare-k8s-feature-gates.sh [hunk 8]
```diff
@@ -0,0 +1,61 @@
+#!/usr/bin/env bash
+#
+# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
```
Comment (LucaBernstein) [inline hack/compare-k8s-feature-gates.sh]:
```suggestion
# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
```
as we've decided to go without year number from now on.

File: hack/compare-k8s-feature-gates.sh (hunk 7 above)
Comment (plkokanov) [reply hack/compare-k8s-feature-gates.sh]: In an internal discussion we decided to proceed with the PR as it is now - by comparing the generated files, so that it is easier to add new k8s versions. 

In the future we will further check if we can reuse the validation that already exists in the [`kube_features.go`](https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go) file. The major blocker for that approach is that k8s only supports 3 minor releases at a time and there is no information about feature gates that have been removed in previous k8s versions which might still be supported by gardener.

**Review by RadaBDimitrova — APPROVED** [review]
/lgtm

File: hack/compare-k8s-feature-gates.sh (hunk 2 above)
Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh]: This comment is marked as resolved but I don't see any changes related to it.

The minimum I can request is a diff such as
```diff
diff --git a/hack/compare-k8s-feature-gates.sh b/hack/compare-k8s-feature-gates.sh
index d578474db6..329ff3a14d 100755
--- a/hack/compare-k8s-feature-gates.sh
+++ b/hack/compare-k8s-feature-gates.sh
@@ -10,7 +10,9 @@ usage() {
   echo "Usage:"
   echo "> compare-k8s-feature-gates.sh [ -h | <old version> <new version> ]"
   echo
-  echo ">> For example: compare-k8s-feature-gates.sh 1.26 1.27"
+  echo ">> For example: compare-k8s-feature-gates.sh 1.32 1.33"
+  echo
+  echo ">> Note: The script only works for Kubernetes versions 1.32+"
 
   exit 0
 }

```

File: hack/compare-k8s-feature-gates.sh (hunk 3 above)
Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh]: This comment is not resolved but it is marked as resolved. As explained above, I suggest to remove the TODO:

```diff
diff --git a/hack/compare-k8s-feature-gates.sh b/hack/compare-k8s-feature-gates.sh
index d578474db6..3eb98a17a9 100755
--- a/hack/compare-k8s-feature-gates.sh
+++ b/hack/compare-k8s-feature-gates.sh
@@ -28,8 +28,6 @@ trap cleanup_output EXIT
 
 for version in "${versions[@]}"; do
   versions_dir=test/compatibility_lifecycle/reference
-  
-  # TODO Drop this when Kubernetes v1.34 gets released
   if [ "$version" == "1.32" ]; then
     versions_dir="test/featuregates_linter/test_data"
   fi

```

File: hack/compare-k8s-feature-gates.sh [hunk 9]
```diff
@@ -0,0 +1,61 @@
+#!/usr/bin/env bash
```
Comment (ialidzhikov) [inline hack/compare-k8s-feature-gates.sh:1]: Shouldn't we bring back the instructions in `docs/development/new-kubernetes-version.md` how to use this script? Right now, we have a script but the guide doesn't include a step that makes use of the script.

This is the commit that removed the old script: https://github.com/gardener/gardener/commit/bb15d84ba5bba68268b0e90c38acc3c479b63cc8#diff-2a2430d81164a51d4de9ddf73b7dbb285793003eef6baad874b77f0808a73919

File: hack/compare-k8s-feature-gates.sh (hunk 7 above)
Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh]: > In an internal discussion we decided to proceed with the PR as it is now - by comparing the generated files, so that it is easier to add new k8s versions.

What was the agreement back then? Do we continue with the PR as it is (checking the upstream test files) or do we want before proceeding to run the generators ourselves and compare the generated files?

Should we add as TODO something that has to be improved in future wrt to the script?

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

File: hack/compare-k8s-feature-gates.sh (hunk 6 above)
Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh]: OK, I got it. The structure in https://github.com/kubernetes/kubernetes/blob/v1.33.0/test/compatibility_lifecycle/reference/versioned_feature_list.yaml is such that it contains information in which version the feature gate was promoted to default. OK, this will work and indeed only shows the feature gates which have are locked to default in version X compared to version X-1.

To make it obvious I suggest the following diff:
```diff
diff --git a/hack/compare-k8s-feature-gates.sh b/hack/compare-k8s-feature-gates.sh
index d578474db6..21c17632c5 100755
--- a/hack/compare-k8s-feature-gates.sh
+++ b/hack/compare-k8s-feature-gates.sh
@@ -50,12 +50,12 @@ echo
 echo "Feature gates removed in $2 compared to $1:"
 diff "${out_dir}/featuregates_list_${1}.yaml" "${out_dir}/featuregates_list_${2}.yaml" | grep '<' | awk '{print $2}'
 echo
-echo "Feature gates locked to default true:"
+echo "Feature gates locked to default true in $2 compared to $1:"
 # Get all feature gate names that have a version spec containing $2, are locked to default with default value of true
 yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == true)) | .name' "${out_dir}/versioned_featuregates_${version}.yaml"
 yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == true)) | .name' "${out_dir}/unversioned_featuregates_${version}.yaml"
 echo
-echo "Feature gates locked to default false:"
+echo "Feature gates locked to default false in $2 compared to $1:"
 # Get all feature gate names that have a version spec containing $2, are locked to default with default value of false
 yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == false)) | .name' "${out_dir}/versioned_featuregates_${version}.yaml"
 yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == false)) | .name' "${out_dir}/unversioned_featuregates_${version}.yaml"

```

Because I was confused whether it shows all locked to default true feature gates in general or only the ones which are locked to default true in version X compared to version X-1.

File: hack/compare-k8s-feature-gates.sh (hunk 5 above)
Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh]: My comment is that the features  in `unversioned_feature_list.yaml` don't have any associated version.

We have the following select statements based on the version field on `L56` and `L61` :
```
yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == true)) | .name' "${out_dir}/unversioned_featuregates_${version}.yaml"
```

```
yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == false)) | .name' "${out_dir}/unversioned_featuregates_${version}.yaml"
```

These don't make much sense because the version field seems to be always empty for the unversioned feature gates. And we expect the version field to be non-empty.

I think we can only decide if such unversioned feature gate is added/removed by comparing the list in the previous version (tag) and in the current version.

File: hack/compare-k8s-feature-gates.sh (hunk 7 above)
Comment (plkokanov) [reply hack/compare-k8s-feature-gates.sh]: Imho we should continue with the PR as it is. The generators are also part of the `test` folder and they require the whole k8s repository to be downloaded. They search the k8s repository for files that contain feature gates and parse them to generate the yaml files. Additionally, the generators aren't built as separate modules and are instead called via `go run test/compatibility_lifecycle/main.go feature-gates verify` and `go run test/compatibility_lifecycle/main.go feature-gates update` from the following scripts: [verify-featuregates.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-featuregates.sh) and [update-featuregates.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/update-featuregates.sh)

The scripts are part of the `make verify` target and the generated yaml files should always be up-to-date so it seems easier, and safe enough, that we use the generated files directly.

File: hack/compare-k8s-feature-gates.sh (hunk 5 above)
Comment (plkokanov) [reply hack/compare-k8s-feature-gates.sh]: I also think that this check: 
```
yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == true)) | .name' "${out_dir}/unversioned_featuregates_${version}.yaml"
```
does not make sense for features in the unversioned featuregates file.

The versioned features file contains enough information to decide if a feature was locked to default in the new k8s release. I think that unversioned featuregates will not be added in the future, and this file is just a left-over from the migration from unversioned to versioned feature gates.

File: hack/compare-k8s-feature-gates.sh (hunk 2 above)
Comment (plkokanov) [reply hack/compare-k8s-feature-gates.sh]: What about also introducing a check for the minimum supported version, similar to `hack/compute-k8s-controllers.sh`, eg: 
https://github.com/gardener/gardener/blob/a1898ec38fb075cdf1c6622a9039686ed7963c08/hack/compute-k8s-controllers.sh#L83-L87

Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh]: I like the suggestion!

Comment (Kostov6) [reply hack/compare-k8s-feature-gates.sh]: @ialidzhikov suggested 1.32+. Should we adapt the suggestion like this?
```bash
 for version in "${versions[@]}"; do 
   if [ "$version" \< "1.32" ]; then 
     echo "Versions less than 1.32 are not supported." 
     exit 1 
   fi 
```

File: hack/compare-k8s-feature-gates.sh (hunk 9 above)
Comment (Kostov6) [reply hack/compare-k8s-feature-gates.sh:1]: Added in https://github.com/gardener/gardener/pull/12216/files:
```
See [this](https://github.com/gardener/gardener/pull/9689/commits) example PR how it handles feature gate maintenance by using `compare-k8s-feature-gates.sh`
```

File: hack/compare-k8s-feature-gates.sh (hunk 5 above)
Comment (Kostov6) [reply hack/compare-k8s-feature-gates.sh]: If we expect for the script to be run for the next added support v1.34 and onwards what do you think about dropping `unversioned_featuregates`? This will also simplify the script and it's maintenance effort as 
```
  if [ "$version" == "1.32" ]; then
    versions_dir="test/featuregates_linter/test_data"
  fi
```
will not be needed. wdyt?

File: hack/compare-k8s-feature-gates.sh (hunk 2 above)
Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh]: Great! Let's keep the note in the usage docs and enforce it with the above suggested validation.
Thanks!

**Review by RadaBDimitrova — APPROVED** [review]
/lgtm

File: docs/development/new-kubernetes-version.md [hunk 10]
```diff
@@ -105,21 +105,7 @@ There is a CI/CD job that runs periodically and releases a new `hyperkube` image
...
-    - **Graduated & Deprecated Feature Gates:**
-      - Open: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features
-      - Search the page for the new Kubernetes version, e.g. "1.32".
-      - Change `LockedToDefaultInVersion` for GA and Deprecated feature gates that have been graduated/deprecated "Since" the new Kubernetes version.
-    - **Removed Feature Gates:**
-      - Open: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/#feature-gates-that-are-removed
-      - Search the page for the **current** Kubernetes version, e.g. if the new version is "1.32", search for "1.31".
-      - Set `RemovedInVersion` to the **new** Kubernetes version for feature gates that have been removed after the **current** Kubernetes version according to the "To" column.
-  - See [this](https://github.com/gardener/gardener/pull/5255/commits/97923b0604300ff805def8eae981ed388d5e4a83) example commit.
+  - See [this](https://github.com/gardener/gardener/pull/9689/commits) example PR how it handles feature gate maintenance by using `compare-k8s-feature-gates.sh`
```
Comment (plkokanov) [inline docs/development/new-kubernetes-version.md:112]: Why didn't you also add the full explanation like it was before ([ref to PR that removed it](https://github.com/gardener/gardener/commit/bb15d84ba5bba68268b0e90c38acc3c479b63cc8#diff-2a2430d81164a51d4de9ddf73b7dbb285793003eef6baad874b77f0808a73919)):
```
  - The feature gates are maintained in [this](../../pkg/utils/validation/features/featuregates.go) file.
  - To maintain this list for new Kubernetes versions, run `hack/compare-k8s-feature-gates.sh <old-version> <new-version>` (e.g. `hack/compare-k8s-feature-gates.sh v1.26 v1.27`).
  - It will present 3 lists of feature gates: those added and those removed in `<new-version>` compared to `<old-version>` and feature gates that got locked to default in `<new-version>`.
  - Add all added feature gates to the map with `<new-version>` as `AddedInVersion` and no `RemovedInVersion`.
  - For any removed feature gates, add `<new-version>` as `RemovedInVersion` to the already existing feature gate in the map.
  - For feature gates locked to default, add `<new-version>` as `LockedToDefaultInVersion` to the already existing feature gate in the map.
```

Also [`featuregates.go`](https://github.com/gardener/gardener/blob/d14dd1e6ac71d2901edcbe8ef4380746d467fb8f/pkg/utils/validation/features/featuregates.go#L15-L35) should be updated accordingly

File: hack/compare-k8s-feature-gates.sh (hunk 5 above)
Comment (plkokanov) [reply hack/compare-k8s-feature-gates.sh]: > If we expect for the script to be run for the next added support v1.34 and onwards what do you think about dropping unversioned_featuregates?

That sounds ok to me, https://github.com/kubernetes/kubernetes/commit/088daf472b7d1ed4502aef211efca6653b05ff59 drops generation of the unversioned file.

When you do the change could you also adapt the check at the start of the script so that the min supported version is 1.33: 
```
  if [ "$version" \< "1.33" ]; then 
    echo "Versions less than 1.33 are not supported." 
    exit 1 
  fi 
```

**Review by plkokanov — CHANGES_REQUESTED** [review]

File: hack/compare-k8s-feature-gates.sh (hunk 5 above)
Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh]: > [kubernetes/kubernetes@088daf4](https://github.com/kubernetes/kubernetes/commit/088daf472b7d1ed4502aef211efca6653b05ff59) drops generation of the unversioned file.

This was also my observation. I now created https://github.com/kubernetes/kubernetes/pull/132809 to clean up this file in the upstream so that we are no longer confused.

> When you do the change could you also adapt the check at the start of the script so that the min supported version is 1.33:

Sounds reasonable. This script could support only 1.33+ and in this way we could drop the handling for the unversioned feature gates.

File: hack/compare-k8s-feature-gates.sh [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+
+echo "Feature gates added in $2 compared to $1:"
+diff "${out_dir}/featuregates_list_${1}.yaml" "${out_dir}/featuregates_list_${2}.yaml" | grep '>' | awk '{print $2}'
+echo
+echo "Feature gates removed in $2 compared to $1:"
+diff "${out_dir}/featuregates_list_${1}.yaml" "${out_dir}/featuregates_list_${2}.yaml" | grep '<' | awk '{print $2}'
+echo
+echo "Feature gates locked to default true in $2 compared to $1:"
+# Get all feature gate names that have a version spec containing $2, are locked to default with default value of true
+yq '.[] | select(.versionedSpecs[] | select(.version == "'$2'" and .lockToDefault == true and .default == true)) | .name' "${out_dir}/versioned_featuregates_${version}.yaml"
```
Comment (plkokanov) [inline hack/compare-k8s-feature-gates.sh:61]: The previous script allowed developers to call it for non-consecutive versions, e.g. `hack/compute-k8s-feature-gates.sh 1.24 1.27` and this would return a list of feature gates that are still lockedToDefault in `1.27` even though they were actually locked to default in e.g. `1.26`. 

In such cases, the current script will skip reporting a feature gate that was locked to default in a previous version (a version that is between the first and second argument).

Tbh I'm not sure if there was ever a case to call the script for such version differences, so for the sake of simplicity, I would recommend to only allow comparing subsequent versions.
@marc1404 @LucaBernstein @shafeeqes @ialidzhikov wdyt?

**Review by plkokanov — CHANGES_REQUESTED** [review]
One final comment on my side.

File: hack/compare-k8s-feature-gates.sh (hunk 11 above)
Comment (marc1404) [reply hack/compare-k8s-feature-gates.sh:61]: In my opinion, it's fine if the script is only capable of dealing with subsequent versions.

Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh:61]: > I would recommend to only allow comparing subsequent versions.

+1. Good point.
Can we add a check for this? If not possible, let's at least add docs about it.

**Review by plkokanov — COMMENTED** [review]
Thanks for addressing all of my comments 🚀 
/lgtm

File: hack/compare-k8s-feature-gates.sh [hunk 12]
```diff
@@ -0,0 +1,66 @@
...
+fi
+
+versions=("$1" "$2")
+out_dir=$(mktemp -d)
+function cleanup_output {
+    rm -rf "$out_dir"
+}
+trap cleanup_output EXIT
+
+versions_dir=test/compatibility_lifecycle/reference
```
Comment (ialidzhikov) [inline hack/compare-k8s-feature-gates.sh]: Cosmetic nit: We could drop this var. It was previously needed because the path for K8s 1.32 and 1.33 was different. However, we decided the script to support only K8s 1.33+, hence this var is obsolete now and we can inline it.

```diff
diff --git a/hack/compare-k8s-feature-gates.sh b/hack/compare-k8s-feature-gates.sh
index bbf02d50ca..86475bd48f 100755
--- a/hack/compare-k8s-feature-gates.sh
+++ b/hack/compare-k8s-feature-gates.sh
@@ -39,13 +39,12 @@ function cleanup_output {
 }
 trap cleanup_output EXIT
 
-versions_dir=test/compatibility_lifecycle/reference
 for version in "${versions[@]}"; do
   if [ "$version" \< "1.33" ]; then 
     echo "Versions less than 1.33 are not supported." 
     exit 1 
   fi 
-  wget -q -O - "https://raw.githubusercontent.com/kubernetes/kubernetes/release-${version}/${versions_dir}/versioned_feature_list.yaml" > "${out_dir}/versioned_featuregates_${version}.yaml"
+  wget -q -O - "https://raw.githubusercontent.com/kubernetes/kubernetes/release-${version}/test/compatibility_lifecycle/reference/versioned_feature_list.yaml" > "${out_dir}/versioned_featuregates_${version}.yaml"
   yq '.[] | .name' "${out_dir}/versioned_featuregates_${version}.yaml" > "${out_dir}/featuregates_list_${version}.yaml"
   # Sort feature gate list for the diff to function correctly
   sort -o "${out_dir}/featuregates_list_${version}.yaml" "${out_dir}/featuregates_list_${version}.yaml"

```

File: pkg/utils/validation/features/featuregates.go [hunk 13]
```diff
@@ -17,22 +17,12 @@ import (
 // - https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
```
Comment (ialidzhikov) [inline pkg/utils/validation/features/featuregates.go]: We could update with:
```diff
diff --git a/pkg/utils/validation/features/featuregates.go b/pkg/utils/validation/features/featuregates.go
index 250369d187..2508666756 100644
--- a/pkg/utils/validation/features/featuregates.go
+++ b/pkg/utils/validation/features/featuregates.go
@@ -13,9 +13,7 @@ import (
 )

 // featureGateVersionRanges contains the version ranges for all Kubernetes feature gates.
-// Extracted from:
-// - https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
-// - https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/
+// Extracted from https://raw.githubusercontent.com/kubernetes/kubernetes/release-${version}/test/compatibility_lifecycle/reference/versioned_feature_list.yaml.
 // To maintain this list for each new Kubernetes version:
 //   - Run `hack/compare-k8s-feature-gates.sh <old-version> <new-version>` (e.g. `hack/compare-k8s-feature-gates.sh v1.33 v1.34`).
 //     It will present 3 lists of feature gates: those added and those removed in `<new-version>` compared to `<old-version>` and
```

See https://github.com/gardener/gardener/commit/3606c99e8e19de1d3a12f07d2fd5df7ce29da4ef#diff-81136865f4bd7a1313a9b25446c6abc89f76cc72b01e6000f1c71f97ce620683L16-R18

**Comment by ialidzhikov** [comment]
I pushed 37a1dca23df8510dfea8153c49b1a34fe05341de to address my last cosmetic suggestions in order to speed up this PR and to do not contribute more to the saga of this PR. :) 
I hope this is fine. Let me know if you see something you want to change.

File: pkg/utils/validation/features/featuregates.go (hunk 13 above)
Comment (ialidzhikov) [reply pkg/utils/validation/features/featuregates.go]: Addressed with https://github.com/gardener/gardener/pull/12109/commits/37a1dca23df8510dfea8153c49b1a34fe05341de.

File: hack/compare-k8s-feature-gates.sh (hunk 12 above)
Comment (ialidzhikov) [reply hack/compare-k8s-feature-gates.sh]: Addressed with https://github.com/gardener/gardener/pull/12109/commits/37a1dca23df8510dfea8153c49b1a34fe05341de.

**Review by ialidzhikov — APPROVED** [review]
/lgtm
