### PR TITLE
Maintenance controller now respects workers CRI configuration

### LINKED ISSUE #4305: MaintenanceController doesn't check if currently used container runtime is supported by new image
**How to categorize this issue?**

/kind bug
/priority 3

**What happened**:
The maintenance controller selected a new `MachineImageVersion` during maintenance which doesn't list the cluster's container runtime in the `CloudProfile`

**What you expected to happen**:
When picking a new version, support for the currently used container runtime is taken into account. It could happen, for example, that future versions of an image drop support for the `docker` runtime. In this case, these versions must not be selected for clusters which use the `docker` container runtime.

**How to reproduce it (as minimally and precisely as possible)**:
* Deploy a `Shoot` using `containerd` using `gardenLinux` v184.0
* adapt the `CloudProfile`:
  *  set `gardenLinux` v184.0 to `deprecated` with an expirationDate in the past (e.g. `2021-06-30T23:59:59Z`)
  * set `gardenLinux` v318.8.0 to `supported`
  * Remove `containerd` support for `v318.8.0`
* trigger shoot maintenance immediately with `./hack/usage/shoot-operation <shoot-name> <namespace-name> maintain`

**Anything else we need to know?**:
Right now this is probably not that big of an issue, as we haven't seen events of container runtime support being removed. This is likely to happen in the future, though, if we e.g. decide to drop support for `docker` at some point in time.

**Environment**:

- Gardener version: 1.26.0
- Kubernetes version (use `kubectl version`): 1.21.0
- Cloud provider or hardware configuration: gcp
- Others:

### PR DESCRIPTION
**Pull request by BeckerMax**
**How to categorize this PR?**
/area control-plane
/kind bug

**What this PR does / why we need it**:
Without this fix the maintenance controller did not respect the `worker.cri` configuration when selecting a new machineImageVersion.

This change will especially become relevant when an MachineImageVersion deprecates the support for a certain containerruntime (like docker).

**Which issue(s) this PR fixes**:
Fixes #4305

**Special notes for your reviewer**:
See the commit messages for the reasoning behind the changes, for example the reasoning behind the refactoring.
As a follow-up we would open an issue to also refactor maintaining the K8s version similar to 584ef1a

**Release note**:

```bug user
The maintenance controller now respects the CRI configuration when selecting a new MachineImageVersion.
```
```noteworthy operator
All MachineImageVersions in the Cloud Profile must have set an accurate set of supported Container Runtimes! Previously, support for the `docker` runtime was implicit, it now needs to be set explicitly. See our [dockershim removal document](https://github.com/gardener/gardener/blob/master/docs/usage/docker-shim-removal.md#what-should-i-do) for more information. To ease this transition this release adds adds `docker` to  the list of supported container runtimes for all MachineImageVersions in your Cloud Profile see #4500.
```

cc @voelzmo

### CODE REVIEW

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go [hunk 1]
```diff
@@ -142,11 +142,15 @@ func (r *shootMaintenanceReconciler) reconcile(ctx context.Context, shoot *garde
 		return err
 	}
 
-	updatedMachineImages, reasonForImageUpdatePerPool, err := MaintainMachineImages(shootLogger, shoot, cloudProfile)
+	reasonForImageUpdatePerPool, err := MaintainMachineImages(shootLogger, shoot, cloudProfile)
 	if err != nil {
 		// continue execution to allow the kubernetes version update
 		shootLogger.Error(fmt.Sprintf("Could not maintain machine image version: %s", err.Error()))
 	}
+	for _, reason := range reasonForImageUpdatePerPool {
```
Comment (timuthy) [inline pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: I would prefer to only record the events if the shoot update was really successful, i.e. after [this](https://github.com/gardener/gardener/pull/4438/commits/584ef1a9689fa4746666a858c2162d433982dbce#diff-e47f920e88ba14e5a3d1c8913346259b3e7a1d7241ac2954333db920a7e6aebcR204) point.

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go [hunk 2]
```diff
@@ -142,11 +142,15 @@ func (r *shootMaintenanceReconciler) reconcile(ctx context.Context, shoot *garde
...
+		r.recorder.Eventf(shoot, corev1.EventTypeNormal, gardencorev1beta1.ShootEventImageVersionMaintenance, "%s",
+			fmt.Sprintf("Updated %s.", reason))
+	}
 
 	updatedKubernetesVersion, reasonForKubernetesUpdate, err := MaintainKubernetesVersion(shoot, cloudProfile, shootLogger)
```
Comment (timuthy) [inline pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: Does it make sense to apply the same refactoring to `MaintainKubernetesVersion`, to be more consistent?

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go [hunk 3]
```diff
@@ -312,7 +312,7 @@ func hasMaintainNowAnnotation(shoot *gardencorev1beta1.Shoot) bool {
 	return ok && operation == v1beta1constants.ShootOperationMaintain
 }
 
-func filterForCRIName(machineImageFromCloudProfile *gardencorev1beta1.MachineImage, workerCRI *gardencorev1beta1.CRI) *gardencorev1beta1.MachineImage {
+func filterForCRI(machineImageFromCloudProfile *gardencorev1beta1.MachineImage, workerCRI *gardencorev1beta1.CRI) *gardencorev1beta1.MachineImage {
```
Comment (timuthy) [inline pkg/controllermanager/controller/shoot/shoot_maintenance_control.go:316]: I wonder what will happen in the following case:
1. No CRI is configured for worker (-> Docker for K8s <= 1.21).
2. CloudProfile contains machine images only supporting non Docker CRIs.

IIUC, this means that images which don't support Docker will be considered as valid updates. Can you double check this?

**Review by timuthy — CHANGES_REQUESTED** [review]
Thanks for your PR :) Looks good in general, just a few suggestions and a doubt about a use-case.

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 2 above)
Comment (voelzmo) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: absolutely, as pointed out in the PR comment
> As a follow-up we would open an issue to also refactor maintaining the K8s version similar to 584ef1a

However, I think this is beyond the scope of this change, to keep things separate, does this make sense?

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 3 above)
Comment (voelzmo) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go:316]: This is very much correct. Our current situation is such that we can only start producing images without docker support once there are no longer any clusters with `cri: nil` configuration anymore.

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 1 above)
Comment (voelzmo) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: this link doesn't work for me, I assume you mean [this](https://github.com/gardener/gardener/blob/c71c50b53bb7de36a441d9d4df43cb1dd6ac89ae/pkg/controllermanager/controller/shoot/shoot_maintenance_control.go#L203) point, just like the k8s version upgrade reasons are recorded?

Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: Yep, that's what I meant.

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 2 above)
Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: Okay, must have overlooked it. I just thought the change will be small and fast, so that you can also include it here (boy scout rule 😄)

Comment (voelzmo) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: TBH, while the code looks pretty neat now, it took us a day to refactor it into this state. I'm all for improving things while you're working on it, but also for separating concerns – I wouldn't want to block this PR for this. I'm happy to open a separate PR for the k8s version updating, though.

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 3 above)
Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go:316]: I see. What do you think about adding a validation for this constraint to the [admission plugin](https://github.com/gardener/gardener/blob/master/plugin/pkg/global/resourcereferencemanager/admission.go#L381)?

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 2 above)
Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: Sure, fine for me 👍

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 1 above)
Comment (voelzmo) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: I've moved the entire block down, event  recording as well as logging. BTW: does it make sense to have the same string logged *and* event recorded?

Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: > BTW: does it make sense to have the same string logged and event recorded?

Hm, events are volatile while we save the Gardenlet logs for a longer period. So if we ran a Gardenlet with `debug` log level and want to look up this message hours/days later, then it would be beneficial. But in this particular case, I doubt that it makes too much sense, tbh.

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 3 above)
Comment (voelzmo) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go:316]: I realized the behavior of `cri:nil` and `cri.name:docker` specified by the worker should be treated in the same way by the maintenance controller: update only if the image explicitly supports `docker` as a runtime.
This comes with the requirement to add this to your Cloud Profile (I've adapted the release notes above with a **breaking** note).

I guess now people can decide at any moment that they want to provide an image without support for e.g. the `docker` runtime and mark it accordingly in their Cloud Profile.

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 1 above)
Comment (voelzmo) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: So should I be removing the duplicated log output or do we want to leave it like it is now?

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 3 above)
Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go:316]: Thanks for the explanation and the change. I just wonder why we shouldn't treat a CloudProfile image version without a CRI specification as it was configured with Docker, as well? This would be a backwards compatible change.

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 1 above)
Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go]: No strong opinion from my side.

File: pkg/controllermanager/controller/shoot/shoot_maintenance_control.go (hunk 3 above)
Comment (voelzmo) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go:316]: > I just wonder why we shouldn't treat a CloudProfile image version without a CRI specification as it was configured with Docker

Are you suggesting there should be a special case where an image doesn't specify *any* supported CRIs, meaning `.spec.machineImages[].versions[].cri` is `nil`? This would certainly be possible, I think we decided against it, because it adds more logic around the implicit special casing of `docker`, which we are trying to get rid of currently. Furthermore, it gets even harder to explain, `.spec.machineImages[].versions[].cri: nil` means `docker` is supported while `.spec.machineImages[].versions[].cri: [{name: containerd}]` means that only `containerd` is supported.

I understand this might solve a very specific problem for a very specific set of people: Operators, who have a CloudProfile with MachineImageVersions which **only** support `docker` (or never want to support using `containerd`) don't need to do anything. All other people would still have to make changes. I'm nor sure how big this set of people is and if we want to add special casing for them. WDYT?

Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go:316]: I'm thinking that after your latest change, things got a little asymmetric. On the one hand you treat `cri:nil` as `cri.name:docker` for `Shoots`. But for `CloudProfiles` you don't handle `.spec.machineImages[].versions[].cri: nil` as `.spec.machineImages[].versions[].cri: [{name: containerd}]`.

I assume that today the majority of operators and users don't specify CRI (whether in `Shoot` or `CloudProfile`) at all, which means they use Docker. The issue I see with this incompatible change here is that operators will fail at a very late stage if they miss to follow the instructions (of course they should read it), i.e. an update did not happen when it was supposed to happen + there is no error message or error log which can help the operator to identify the issue. That is the reason I suggested this transition to become more operator/user friendly through one or a combination of:
- Backwards compatibility
- Automated migration, i.e. add `cri.name:docker` if `cri:nil` for `Shoots` and `CloudProfiles`
- Validation to fail early (e.g. `cri:nil` in `CloudProfiles` should not be a valid use case any more)
- Print error in log message if appropriate image could not be found

Comment (voelzmo) [reply pkg/controllermanager/controller/shoot/shoot_maintenance_control.go:316]: Great points, thanks! I've added the following story plus some sub-tasks to #4110 
> As an operator, I want Gardener take care of migrating my Cloud Profile from implicit docker runtime support to explicit specification of docker, such that I don't have to do error-prone manual work myself

For the Shoot defaulting: we decided explicitly against migrating automatically to `cri.name: docker`, as we want Shoot owners to face this decision as early as possible (do I need to change my production workload, such that I can switch to `containerd` once support for `docker` is removed?). Our assumption here is that when upgrading to k8s 1.22, most people will be fine with the new default of `containerd`.

**Review by timuthy — APPROVED** [review]
/lgtm
