### PR TITLE
Revert "Adapt `gardenlet` to use priority class `gardener-system-critical` (#6235)" 

### LINKED ISSUE #6422: Gardenlet deployment using helm fails
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
While deploying the Gardener v1.52.0 `gardenlet` deployment fails with the following error:
```
Error: kind PriorityClass with the name "gardener-system-critical" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
Error: UPGRADE FAILED: kind PriorityClass with the name "gardener-system-critical" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
```
 But the gardenlet images gets upgraded to the latest version. This removes the priority-class from managed resources and the priority class gets garbage collected. 
 So if one deploy the gardenelet again it will succeed without error.

**What you expected to happen**:
The gardenlet deployment should succeed without error.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.52.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR reverts #6235. Now gardenlet will create `gardener-system-critical` priority class as part of MR so the seed component can use it. For migrating gardenlet from `gardenlet` to `gardener-system-critical` priority class, we can use two-step process in the first release we will switch all the component which uses `gardener-system-critical` priority class to use some different priority class and delete `gardener-system-critical` priority class from managed resource and in second release switch back to `gardener-system-critical` priority class and let helm deploy it.

**Which issue(s) this PR fixes**:
Fixes #6422

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
A bug causing `gardenlet` helm chart deployment to fail is fixed.
```

### CODE REVIEW

File: pkg/operation/botanist/component/resourcemanager/resource_manager.go [hunk 1]
```diff
@@ -452,7 +452,7 @@ func (r *resourceManager) ensureDeployment(ctx context.Context) error {
 		return err
 	}
 
-	priorityClassName := v1beta1constants.PriorityClassNameSeedSystemCritical
+	priorityClassName := "gardenlet"
```
Comment (ialidzhikov) [inline pkg/operation/botanist/component/resourcemanager/resource_manager.go]: Why we need this change (ref https://github.com/gardener/gardener/compare/ce37e54493d833669772b67f0f9cd1c5aad275ed..5ce926a026832696f6f4032c8f457fce55b2810a)? Isn't possible GRM to use `gardener-system-critical`?

Comment (acumino) [reply pkg/operation/botanist/component/resourcemanager/resource_manager.go]: I changed this commit.
We can't use `gardener-system-critical` priority class for resource manager now as the deployment will not come up in our e2e test because `gardener-system-critical` is not getting created anywhere. This will cause our e2e test to fail.

Comment (acumino) [reply pkg/operation/botanist/component/resourcemanager/resource_manager.go]: Once cherry-pick PR of this PR is merged. A new PR can be opened for 1.53 release to use some other priority class instead of `gardener-system-critical` and drop it from managed resource and deploy through helm and in 1.54 switch it back to `gardener-system-critical`.

Comment (shafeeqes) [reply pkg/operation/botanist/component/resourcemanager/resource_manager.go]: > We can't use gardener-system-critical priority class for resource manager now as the deployment will not come up in our e2e test because gardener-system-critical is not getting created anywhere

In that case, there are istio components using this priority class as well. 

But won't be enough to just change the gardenlet priority class alone: 
1. Gardenlet uses the legacy `gardenlet` priorityclass itself.
2.  Make the gardenlet deploy `gardener-system-critical` priorityclass once it comes up
3. Resource manager can clean up the "managed" priorityclass
?

Comment (acumino) [reply pkg/operation/botanist/component/resourcemanager/resource_manager.go]: > In that case, there are istio components using this priority class as well. 

For that MR will be created and reconciled as GRM will be there.

> Make the gardenlet deploy gardener-system-critical priorityclass once it comes up

We can't make sure when the MR priority class will be cleaned/deleted by GRM meanwhile if gardenlet will try to create one it will throw an error.

Comment (shafeeqes) [reply pkg/operation/botanist/component/resourcemanager/resource_manager.go]: > For that MR will be created and reconciled as GRM will be there.

But isn't the goal to remove this priorityclass from MR?

Comment (shafeeqes) [reply pkg/operation/botanist/component/resourcemanager/resource_manager.go]: On disucssing this in a call with @acumino, maybe
"Once cherry-pick PR of this PR is merged. A new PR can be opened for 1.53 release to use some other priority class instead of gardener-system-critical and drop it from managed resource and deploy through helm and in 1.54 switch it back to gardener-system-critical."
is the way to go.

Comment (ialidzhikov) [reply pkg/operation/botanist/component/resourcemanager/resource_manager.go]: Okay, I now got why we need the special handling for GRM - when we bootstrap a new Seed we will fail to create the GRM Deployment because the PriorityClass will be missing (to be deployed by GRM itself later). This reverts the GRM adaptation from https://github.com/gardener/gardener/pull/6257. But for the v1.52 cherry-pick we will need only pure revert of https://github.com/gardener/gardener/pull/6235 (only the first commit of this PR), right?

I think I am fine with this approach. @timebertt @kris94 comments/objections?

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

File: pkg/operation/botanist/component/resourcemanager/resource_manager.go (hunk 1 above)
Comment (krgostev) [reply pkg/operation/botanist/component/resourcemanager/resource_manager.go]: No objections from my side, looks like you got the whole scenario.

**Comment by vpnachev** [comment]
@acumino you have to use the branch name which is `release-v1.52`, not the tag
/cherry-pick release-v1.52

**Comment by vpnachev** [comment]
@acumino you will have to cherry-pick this PR manually
