### PR TITLE
Fix panic during extension deletion

### LINKED ISSUE #2255: Gardenlet crashes waiting for Extension CRD to be deleted
**What happened**:

When waiting for an Extension CRD to be deleted the gardenlet crashes.
There was a bug introduces in PR #2248 that causes a panic when an Extension CRD does not have a last error in the status. 
[This LoC](https://github.com/gardener/gardener/blob/de96851b72d7956e84afc1e5605f75b4f6b01fdd/pkg/operation/common/extensions.go#L260) is causing the issue.

image

**What you expected to happen**:
Gardenlet does not crash.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot 
2. Make sure the Network CRD in the Seed does not have a Status.LastError
3. Delete the Shoot
4. Observe the Gardenlet crashing

**Anything else we need to know?**:

**Environment**:

- Gardener version: Current master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**What this PR does / why we need it**:

Fixes a panic during Extension CRD deletion. Please take a look at the referenced issue #2255.

**Which issue(s) this PR fixes**:
Fixes #2255

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]

File: pkg/operation/common/extensions.go [hunk 1]
```diff
@@ -257,7 +257,10 @@ func WaitUntilExtensionCRDeleted(
 		}
 
 		logger.Infof("Waiting for %s %s/%s to be deleted...", kind, namespace, name)
-		return retry.MinorError(fmt.Errorf("%s is still present, last observed error: %s", extensionKey(kind, namespace, name), lastObservedError.Error()))
+		if lastObservedError != nil {
+			retry.MinorError(fmt.Errorf("%s is still present, last observed error: %s", extensionKey(kind, namespace, name), lastObservedError.Error()))
+		}
+		return retry.MinorError(fmt.Errorf("%s is still present", extensionKey(kind, namespace, name)))
```
Comment (ialidzhikov) [inline pkg/operation/common/extensions.go]: What about
```golang
		var message = fmt.Sprintf("%s is still present", extensionKey(kind, namespace, name))
		if lastObservedError != nil {
			message += fmt.Sprintf(", last observed error: %s", lastObservedError.Error())
		}
		return retry.MinorError(fmt.Errorf(message))
```

Comment (danielfoehrKn) [reply pkg/operation/common/extensions.go]: Yup, changed it.

**Comment by ialidzhikov** [comment]
/kind/bug

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]
