### PR TITLE
Prevent apiserver from crashing when shoot volume is updated to nil.

### LINKED ISSUE #1838: apiserver crashes on shoot validation when updating machine worker volume to nil
**What happened**:

I had a shoot with `.spec.provider.workers[0].volume` properly in place. When I then set the volume to nil (which is a valid setting), the apiserver panics with a nil pointer dereference.

The suspicious line is here: https://github.com/gardener/gardener/blob/v0.35.0/plugin/pkg/shoot/validator/admission.go#L1196

**What you expected to happen**:

Shoot validation succeeds without server crashing.

**How to reproduce it (as minimally and precisely as possible)**:

as described above

**Anything else we need to know?**:

```
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver E0122 16:19:05.379912       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver goroutine 4920224 [running]:
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/endpoints/handlers.finishRequest.func1.1(0xc008df2720)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:229 +0xc9
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver panic(0x1de7b20, 0x36c32c0)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver github.com/gardener/gardener/plugin/pkg/shoot/validator.validateVolumeTypes(0xc008a9e460, 0x1, 0x4, 0x0, 0xc009151640, 0xc008a9e3c0, 0x2, 0x4, 0xc00989ff80, 0x3, ...)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/plugin/pkg/shoot/validator/admission.go:1196 +0x43
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver github.com/gardener/gardener/plugin/pkg/shoot/validator.validateProvider(0xc005ba9e80, 0xc002c5efc0, 0x20179e0, 0xc002bdc540)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/plugin/pkg/shoot/validator/admission.go:1009 +0x568
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver github.com/gardener/gardener/plugin/pkg/shoot/validator.(*ValidateShoot).Admit(0xc000116cd0, 0x25d8e00, 0xc002c5ed50, 0x260e460, 0xc0046cd0e0, 0x25e3a00, 0xc002d0f6c0, 0x1, 0x1)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/plugin/pkg/shoot/validator/admission.go:576 +0xc3c
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/admission/metrics.pluginHandlerWithMetrics.Admit(0x2584d80, 0xc000116cd0, 0xc0007fccf0, 0xc0007fcd00, 0x1, 0x1, 0x25d8e00, 0xc002c5ed50, 0x260e460, 0xc0046cd0e0, ...)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/admission/metrics/metrics.go:98 +0xfc
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/admission.chainAdmissionHandler.Admit(0xc000418500, 0xc, 0x10, 0x25d8e00, 0xc002c5ed50, 0x260e460, 0xc0046cd0e0, 0x25e3a00, 0xc002d0f6c0, 0x1, ...)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/admission/chain.go:37 +0x14d
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/admission.(*reinvoker).Admit(0xc0007fcfa0, 0x25d8e00, 0xc002c5ed50, 0x260e460, 0xc0046cd0e0, 0x25e3a00, 0xc002d0f6c0, 0x20c0e90, 0x6)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/admission/reinvocation.go:37 +0xcf
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/admission/metrics.pluginHandlerWithMetrics.Admit(0x25863c0, 0xc0007fcfa0, 0xc0007fcfb0, 0x0, 0x0, 0x0, 0x25d8e00, 0xc002c5ed50, 0x260e460, 0xc0046cd0e0, ...)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/admission/metrics/metrics.go:98 +0xfc
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/admission.auditHandler.Admit(0x25863e0, 0xc00070fe90, 0xc009acac80, 0x25d8e00, 0xc002c5ed50, 0x260e460, 0xc0046cd0e0, 0x25e3a00, 0xc002d0f6c0, 0x1bfa66b, ...)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/admission/audit.go:57 +0x136
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/endpoints/handlers.(*patcher).applyAdmission(0xc0060b03c0, 0x25d8e00, 0xc002c5ed50, 0x2596180, 0xc0064d6000, 0x2596180, 0xc0064b8380, 0x2596180, 0xc0064d6000, 0x0, ...)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go:518 +0x1da
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/registry/rest.(*defaultUpdatedObjectInfo).UpdatedObject(0xc002c5ee70, 0x25d8e00, 0xc002c5ed50, 0x2596180, 0xc0064b8380, 0x2621da0, 0xc001639490, 0xc0016394d0, 0x475f78)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/registry/rest/update.go:204 +0xbd
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Update.func1(0x2596180, 0xc0064b8380, 0x0, 0xaad39, 0x0, 0xc001639920, 0xbf823b5e566b3d0d, 0x1b3d4706382a, 0x36ea360)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:476 +0x117
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/storage/etcd3.(*store).updateState(0xc000f23d80, 0xc006f21380, 0xc005627360, 0x2596180, 0xc0064b8380, 0x0, 0x0, 0x21)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:773 +0x5b
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/storage/etcd3.(*store).GuaranteedUpdate(0xc000f23d80, 0x25d8e00, 0xc002c5ed50, 0xc0095581e0, 0x2b, 0x2596180, 0xc0064b8000, 0x1, 0xc0092e8930, 0xc005627360, ...)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:293 +0x5fc
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/storage/cacher.(*Cacher).GuaranteedUpdate(0xc0004bb760, 0x25d8e00, 0xc002c5ed50, 0xc0095581e0, 0x2b, 0x2596180, 0xc0064b8000, 0x301, 0xc0092e8930, 0xc005627360, ...)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go:740 +0x2e4
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/registry/generic/registry.(*DryRunnableStorage).GuaranteedUpdate(0xc000f9d0a8, 0x25d8e00, 0xc002c5ed50, 0xc0095581e0, 0x2b, 0x2596180, 0xc0064b8000, 0x1, 0xc0092e8930, 0xc005627360, ...)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/registry/generic/registry/dryrun.go:100 +0x2f4
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Update(0xc000f9cfc0, 0x25d8e00, 0xc002c5ed50, 0xc002305b6c, 0x9, 0x259d2c0, 0xc002c5ee70, 0xc003839770, 0xc006f21300, 0xc000e3f700, ...)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:474 +0x3d3
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/endpoints/handlers.(*patcher).patchResource.func1(0xc000e3f758, 0xc000e3f7a8, 0x8756ab, 0x3711de0)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go:561 +0x106
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver k8s.io/apiserver/pkg/endpoints/handlers.finishRequest.func1(0xc008df2720, 0xc002c5eea0, 0xc008df26c0, 0xc008df2660)
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:237 +0x72
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver created by k8s.io/apiserver/pkg/endpoints/handlers.finishRequest
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:218 +0xd4
gardener-apiserver-bd5c89c6c-6nwth gardener-apiserver 
...
```

**Environment**:

- Gardener version: v0.35.0
- Kubernetes version (use `kubectl version`): 1.15.8
- Cloud provider or hardware configuration: Metal on GKE
- Others:

### PR DESCRIPTION
**Pull request by Gerrit91**
**What this PR does / why we need it**:
Api server panics with nil pointer dereference if user updates a shoot's worker volume to nil.

**Which issue(s) this PR fixes**:
Fixes #1838 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Fix to prevent api server from crashing when shoot's worker volume is removed.
```

### CODE REVIEW

File: plugin/pkg/shoot/validator/admission.go [hunk 1]
```diff
@@ -1193,7 +1193,7 @@ top:
 }
 
 func validateVolumeTypes(constraints []garden.VolumeType, volume, oldVolume *garden.Volume, regions []garden.Region, region string, zones []string) (bool, []string) {
-	if (volume == nil && oldVolume == nil) || volume.Type == nil || (volume != nil && oldVolume != nil && volume.Type != nil && oldVolume.Type != nil && *volume.Type == *oldVolume.Type) {
+	if (volume == nil && oldVolume == nil) || (volume == nil && oldVolume != nil) || volume.Type == nil || (volume != nil && oldVolume != nil && volume.Type != nil && oldVolume.Type != nil && *volume.Type == *oldVolume.Type) {
```
Comment (plkokanov) [inline plugin/pkg/shoot/validator/admission.go]: The check:
`(volume == nil && oldVolume == nil) || (volume == nil && oldVolume != nil)`
 is the same as:
`volume == nil`
So perhaps we could just use the second.

Comment (Gerrit91) [reply plugin/pkg/shoot/validator/admission.go]: Correct. I changed this accordingly.

**Review by rfranzke — APPROVED** [review]
