### PR TITLE
Retrieve the first log lines from failed kube-apiserver when k8s version <1.19

### LINKED ISSUE #4010: Missing log line when KAS is configured with unsupported feature gate
**How to categorize this issue?**

/area ops-productivity quality robustness
/kind bug
/priority 3

**What happened**:
https://github.com/gardener/gardener/pull/3353 has improved a lot the ops experience by providing the latest log lines. 
Sometimes, it misses the log line about the misconfigured feature gate (maybe it is even not logged, changed log format or no more logging it).

**What you expected to happen**:
The logs from the kube-apiserver to contain the message what was wrongly configured and prevents successful start-up.

**How to reproduce it (as minimally and precisely as possible)**:
Not very clear, but try with shoot running k8s 1.20 and feature gate `ConfigurableFSGroupPolicy`.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.21.x
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**
/area ops-productivity quality robustness
/kind enhancement

**What this PR does / why we need it**:
In some cases the kube-apiserver reports the wrong the configuration at the beginning and then the error is not observed in the last 10 lines. To improve ops productivity, we can read also the first lines (actually there is no concept for lines, but bytes) from the log.

**Which issue(s) this PR fixes**:
Fixes #4010

**Special notes for your reviewer**:

**Release note**:

```other operator
Some shoot clusters try to wrongly configure the `kube-apiserver` and it fails to start. Since some time, Gardener shows the last 10 log lines for such kube-apiservers in the `shoot..status.lastOperation.description', but error message with the useful information might not be in those lines. Therefore, for shoots clusters running on k8s <1.19 now also the first 1KiB of logs will be shown.
```

### CODE REVIEW

File: pkg/utils/kubernetes/kubernetes.go [hunk 1]
```diff
@@ -513,13 +513,26 @@ func NewestPodForDeployment(ctx context.Context, c client.Reader, deployment *ap
...
+	if len(newestReplicaSet.Spec.Selector.MatchLabels)+len(newestReplicaSet.Spec.Selector.MatchExpressions) == 0 {
+		return nil, fmt.Errorf("no matchLabels or matchExpressions specified in replicaSet %s/%s", newestReplicaSet.Namespace, newestReplicaSet.Name)
+	}
+
+	podSelector, err := metav1.LabelSelectorAsSelector(newestReplicaSet.Spec.Selector)
+	if err != nil {
+		return nil, fmt.Errorf("failed to convert the pod selector from ReplicaSet %s/%s: %v", newestReplicaSet.Namespace, newestReplicaSet.Name, err)
+	}
+
+	listOpts = append(listOpts, client.MatchingLabelsSelector{Selector: podSelector})
```
Comment (ialidzhikov) [inline pkg/utils/kubernetes/kubernetes.go]: Well, IIUC this optimization is done to select only the Pods that belong to the  newest ReplicaSet, right?
I think that we won't gain much from such optimization as we already filter out by the Deployment matchLabels, so in worst case it will list few Pods more than without this optimization.
To be honest I vote to keep the old way as it seems to me much more elegant, easy to read && understand. Do you agree?

Comment (vpnachev) [reply pkg/utils/kubernetes/kubernetes.go]: If accept the replica set always use the `newestReplicaSet.Spec.Selector.MatchLabels` and never `newestReplicaSet.Spec.Selector.MatchExpressions`, as it is already done for the Deployment, it will be also very easy to read. 
I think it can be simplified even now by:
```golang
listOpts = append(listOpts, client.MatchingLabels(map[string]string{"pod-template-hash": newestReplicaSet.Name}))
```
but I suppose this is not defined in the API and can be changed in any future k8s version. 

I do not like the ownerReference filtering because it is done on the client side when it can be done on the server side with the label selector. 

So I am open to simplify the label selector but really would like to remove the ownerRef filtering.

Comment (ialidzhikov) [reply pkg/utils/kubernetes/kubernetes.go]: > [...] but really would like to remove the ownerRef filtering.

Such filtering is already in place few lines above for ReplicaSets.

I don't want to repeat myself with https://github.com/gardener/gardener/pull/4050#discussion_r632368582. I would rather vote to have the old logic in place (that can list for example 6 Pods, instead of 3). This code path is already being executed in special cases.
Is it possible to have a separate PR for this optimization where we can get a`second-opinion`? In this way we can proceed with this PR to fix corresponding issue?

Comment (vpnachev) [reply pkg/utils/kubernetes/kubernetes.go]: > Is it possible to have a separate PR for this optimization where we can get asecond-opinion? In this way we can proceed with this PR to fix corresponding issue

Sure.

**Review by ialidzhikov — APPROVED** [review]
/lgtm
