### PR TITLE
Deflake `operator/garden/garden` integration test

### LINKED ISSUE #10576: [Flaky Test] Garden controller tests [It] should successfully reconcile and delete a Garden
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
- Garden controller tests [It] should successfully reconcile and delete a Garden

**CI link**:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/10564/pull-gardener-integration/1839195831954051072
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/10472/pull-gardener-integration/1838993964762402816

**Reason for failure**:
```
 [FAILED] Timed out after 10.001s.
  Expected success, but got an error:
      <*errors.StatusError | 0xc00444d180>: 
      servicemonitors.monitoring.coreos.com "garden-gardener-operator" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "servicemonitors.monitoring.coreos.com \"garden-gardener-operator\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "garden-gardener-operator",
                  Group: "monitoring.coreos.com",
                  Kind: "servicemonitors",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/operator/garden/garden/garden_test.go:429 @ 09/26/24 06:56:54.405
```

**Anything else we need to know**:
N/A

### PR DESCRIPTION
**Pull request by tobschli**
**How to categorize this PR?**

/area dev-productivity
/kind flake

**What this PR does / why we need it**:

This PR aims to fix the flaky test mentioned in #10576.

As described in the meanwhile closed #10639, this PR is the first part of the implementation of a generic `CRDDeployer` that should fix the flake by providing an appropriate `Wait()` method.

**Which issue(s) this PR fixes**:
Fixes #10576 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/component/crddeployer/crd.go [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+	return WaitUntilCRDManifestsReady(ctx, c.client, maps.Keys(c.crdNameToManifest))
+}
+
+// WaitCleanup waits for destruction to finish and CRDs to be fully removed.
+func (c *crdDeployer) WaitCleanup(ctx context.Context) error {
+	return WaitUntilCRDManifestsDestroyed(ctx, c.client, maps.Keys(c.crdNameToManifest))
+}
+
+// MakeCRDNameMap returns a map that has the name of the resource as key, and the corresponding manifest as value.
+func MakeCRDNameMap(manifests []string) (map[string]string, error) {
```
Comment (timuthy) [inline pkg/component/crddeployer/crd.go]:
```suggestion
func generateNameToCRDMap(manifests []string) (map[string]string, error) {
```

File: pkg/component/crddeployer/crd.go [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+	var fns []flow.TaskFn
+	for _, crdName := range crdNames {
+		fns = append(fns, func(ctx context.Context) error {
+			timeoutCtx, cancel := context.WithTimeout(ctx, CRDWaitTimeout)
+			defer cancel()
+
+			return retry.Until(timeoutCtx, 1*time.Second, func(ctx context.Context) (done bool, err error) {
+				crd := &apiextensionsv1.CustomResourceDefinition{}
+
+				if err := c.Get(ctx, client.ObjectKey{Name: crdName}, crd); err != nil {
```
Comment (timuthy) [inline pkg/component/crddeployer/crd.go]: I assume that at least the first Get call will result in a `NotFoundError` when the cache is not refreshed yet. It may be better to treat those as `retry.MinorError(err)`. Could you double check please?

File: pkg/component/crddeployer/crd.go [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+				}
+				return retry.Ok()
+			})
+		})
+	}
+	return flow.Parallel(fns...)(ctx)
+}
+
+// WaitUntilCRDManifestsDestroyed takes names of CRDs and waits for them to get destroted with a timeout of 15 seconds.
+func WaitUntilCRDManifestsDestroyed(ctx context.Context, c client.Client, crdNames []string) error {
```
Comment (timuthy) [inline pkg/component/crddeployer/crd.go]:
```suggestion
func WaitUntilCRDManifestsDestroyed(ctx context.Context, c client.Client, crdNames ...string) error {
```
Slightly more convenient to use varargs for users of this function.

Also, I think package `pkg/utils/kubernetes` would be a better fit for such a utility function.

File: pkg/component/crddeployer/crd.go [hunk 4]
```diff
@@ -0,0 +1,155 @@
...
+					return retry.MinorError(err)
+				}
+				return retry.Ok()
+			})
+		})
+	}
+	return flow.Parallel(fns...)(ctx)
+}
+
+// WaitUntilCRDManifestsDestroyed takes names of CRDs and waits for them to get destroted with a timeout of 15 seconds.
```
Comment (timuthy) [inline pkg/component/crddeployer/crd.go]:
```suggestion
// WaitUntilCRDManifestsDestroyed takes CRD names and waits for them to be gone with a timeout of 15 seconds.
```

File: pkg/component/crddeployer/crd_test.go [hunk 5]
```diff
@@ -0,0 +1,175 @@
...
+		It("should throw an error when a non valid CRD is provided", func() {
+			crdMap, err := MakeCRDNameMap([]string{invalidManifest})
+			Expect(crdMap).To(BeNil())
+			Expect(err).To(MatchError(ContainSubstring("error unmarshaling JSON")))
+		})
+	})
+
+	Describe("#WaitUntilCRDManifestsReady", func() {
+		It("should return true because the CRD is ready", func() {
+			testClient := fakeclient.NewClientBuilder().
```
Comment (timuthy) [inline pkg/component/crddeployer/crd_test.go]: Why do you initiate a new test client here?

File: pkg/component/crddeployer/crd_test.go [hunk 6]
```diff
@@ -0,0 +1,175 @@
...
+				WithObjects(readyCRD).
+				Build()
+
+			Expect(WaitUntilCRDManifestsReady(ctx, testClient, []string{"myresources.mygroup.example.com"})).
+				To(Succeed())
+		})
+
+		It("should time out because CRD is not ready", func() {
+			// lower waiting timeout so that the unit test itself does not time out
+			CRDWaitTimeout = 10 * time.Millisecond
```
Comment (timuthy) [inline pkg/component/crddeployer/crd_test.go]: Please use [test.WithVar](https://github.com/gardener/gardener/blob/d1d774749d22de6b85f1e02b39d969fa9227e079/pkg/nodeagent/registry/containerd_extractor_test.go#L188).

File: pkg/component/crddeployer/crd.go [hunk 7]
```diff
@@ -0,0 +1,155 @@
...
+	"github.com/gardener/gardener/pkg/component"
+	"github.com/gardener/gardener/pkg/utils/flow"
+	kubernetesutils "github.com/gardener/gardener/pkg/utils/kubernetes"
+	"github.com/gardener/gardener/pkg/utils/kubernetes/health"
+	"github.com/gardener/gardener/pkg/utils/retry"
+)
+
+var (
+	// CRDWaitTimeout specifies the total time to wait for CRDs to become ready.
+	CRDWaitTimeout = 15 * time.Second
```
Comment (timuthy) [inline pkg/component/crddeployer/crd.go]:
```suggestion
	// WaitTimeout specifies the total time to wait for CRDs to become ready or to be deleted. Exposed for testing.
	WaitTimeout = 15 * time.Second
```

File: pkg/component/crddeployer/crd.go [hunk 8]
```diff
@@ -0,0 +1,155 @@
...
+			timeoutCtx, cancel := context.WithTimeout(ctx, CRDWaitTimeout)
+			defer cancel()
+			return kubernetesutils.WaitUntilResourceDeleted(timeoutCtx, c, crd, 1*time.Second)
+		})
+	}
+	return flow.Parallel(fns...)(ctx)
+}
+
+// GetObjectNameFromManifest takes a manifest and returns its corresponding name.
+func GetObjectNameFromManifest(manifest string) (string, error) {
```
Comment (timuthy) [inline pkg/component/crddeployer/crd.go]: This function is not really needed when I saw correctly in https://github.com/gardener/gardener/pull/10639. Could you please drop it? This `crd` package would anyway not be the perfect place for such a generic function.

File: pkg/component/crddeployer/crd_test.go [hunk 9]
```diff
@@ -0,0 +1,175 @@
...
+			actualCRD := &apiextensionsv1.CustomResourceDefinition{}
+
+			Expect(testClient.Create(ctx, readyCRD)).To(Succeed())
+
+			Expect(crdDeployer.Destroy(ctx)).To(Succeed())
+
+			Expect(testClient.Get(ctx, client.ObjectKey{Name: readyCRD.Name}, actualCRD)).To(matchers.BeNotFoundError())
+		})
+	})
+
```
Comment (timuthy) [inline pkg/component/crddeployer/crd_test.go:109]: Please also test `Wait` and `WaitCleanup`.

File: pkg/component/crddeployer/crd_test.go [hunk 10]
```diff
@@ -0,0 +1,175 @@
...
+metadata:
+    name: myresources.mygroup.example.com`
+		invalidManifest = `thisIsNotAValidManifest`
+
+		testClient = fakeclient.NewClientBuilder().WithScheme(kubernetesscheme.Scheme).Build()
+		mapper := meta.NewDefaultRESTMapper([]schema.GroupVersion{apiextensionsv1.SchemeGroupVersion})
+		mapper.Add(apiextensionsv1.SchemeGroupVersion.WithKind("CustomResourceDefinition"), meta.RESTScopeRoot)
+		applier = kubernetes.NewApplier(testClient, mapper)
+		var err error
+		crdDeployer, err = NewCRDDeployer(testClient, applier, []string{validManifest})
```
Comment (timuthy) [inline pkg/component/crddeployer/crd_test.go]: Could you add another CRD for test?

File: pkg/component/crddeployer/crd.go [hunk 11]
```diff
@@ -0,0 +1,155 @@
...
+
+// crdDeployer is a DeployWaiter that can deploy CRDs and wait for them to be ready.
+type crdDeployer struct {
+	client            client.Client
+	applier           kubernetes.Applier
+	crdNameToManifest map[string]string
+}
+
+// NewCRDDeployer returns a DeployWaiter that can deploy CRDs and wait for them to be ready.
+func NewCRDDeployer(client client.Client, applier kubernetes.Applier, manifests []string) (component.DeployWaiter, error) {
```
Comment (timuthy) [inline pkg/component/crddeployer/crd.go]:
```suggestion
// New returns a new instance of DeployWaiter for CRDs.
func New(client client.Client, applier kubernetes.Applier, manifests []string) (component.DeployWaiter, error) {
```

The package is already called `crddeployer`, no need for repetition.

File: pkg/component/crddeployer/crd.go [hunk 12]
```diff
@@ -0,0 +1,155 @@
...
+		if err != nil {
+			return nil, err
+		}
+		crdNameToManifest[name] = manifest
+	}
+	return crdNameToManifest, nil
+}
+
+// WaitUntilCRDManifestsReady takes names of CRDs and waits for them to get ready with a timeout of 15 seconds.
+func WaitUntilCRDManifestsReady(ctx context.Context, c client.Client, crdNames []string) error {
```
Comment (timuthy) [inline pkg/component/crddeployer/crd.go]:
```suggestion
func WaitUntilCRDManifestsReady(ctx context.Context, c client.Client, crdNames ...string) error {
```

Also, I think package `pkg/utils/kubernetes` would be a better fit for such a utility function.

**Review by timuthy — CHANGES_REQUESTED** [review]
Thanks for the PR. I'm very happy that the tests passed 😃  My comments are mostly related to code consistency and best practices.

File: pkg/component/crddeployer/crd.go (hunk 1 above)
Comment (tobschli) [reply pkg/component/crddeployer/crd.go]: This function will be used in the future by other packages ([ref](https://github.com/gardener/gardener/pull/10639/files#diff-f509e0b36930e845e5c75c98149f033654d387b64b15ba59982117e82551ad03R49)).

Should I not export it for the time being and export it when the alignment of the other deployers follows?

File: pkg/component/crddeployer/crd.go (hunk 2 above)
Comment (tobschli) [reply pkg/component/crddeployer/crd.go]: Yup, I will check that, but using `retry.MinorError(err)` really seems to be the way to go here :)

File: pkg/component/crddeployer/crd_test.go (hunk 5 above)
Comment (tobschli) [reply pkg/component/crddeployer/crd_test.go]: Sorry for the oversight :/
This is a remainder before I initialized with `BeforeEach`

File: pkg/component/crddeployer/crd.go (hunk 8 above)
Comment (tobschli) [reply pkg/component/crddeployer/crd.go]: I used it [here](https://github.com/gardener/gardener/pull/10639/files#diff-a21beedc94f33d1eb00d113858fa12050121bc8e0852520726150b4eda29626aR37) for the special case of the `vpa` CRD deployer.

Will drop it and possibly reintroduce (at a suitable spot then) when needed in the future PR

File: pkg/component/crddeployer/crd.go (hunk 1 above)
Comment (timuthy) [reply pkg/component/crddeployer/crd.go]: I'm not sure if it's still needed there. Let's not export it for now and discuss again in the next PR.

File: pkg/component/crddeployer/crd.go (hunk 8 above)
Comment (timuthy) [reply pkg/component/crddeployer/crd.go]: Thanks. 

Side remark: It's used at the linked place, but var `resourceNames` doesn't really have a meaning in the `vpa` package.

File: pkg/component/crddeployer/crd_test.go [hunk 13]
```diff
@@ -0,0 +1,154 @@
...
+	Describe("#WaitCleanup", func() {
+		It("should return because the CRD is gone", func() {
+			Expect(crdDeployer.Deploy(ctx)).To(Succeed())
+
+			Expect(crdDeployer.Destroy(ctx)).To(Succeed())
+
+			Expect(crdDeployer.WaitCleanup(ctx)).To(Succeed())
+		})
+
+		It("should time out because CRD is not ready", func() {
```
Comment (timuthy) [inline pkg/component/crddeployer/crd_test.go]:
```suggestion
		It("should time out because CRD is still present", func() {
```

File: pkg/component/crddeployer/crd_suite_test.go [hunk 14]
```diff
@@ -0,0 +1,17 @@
...
+import (
+	"testing"
+
+	. "github.com/onsi/ginkgo/v2"
+	. "github.com/onsi/gomega"
+)
+
+func TestCRDDeployer(t *testing.T) {
+	RegisterFailHandler(Fail)
+	RunSpecs(t, "CRDDeployer Suite")
```
Comment (timuthy) [inline pkg/component/crddeployer/crd_suite_test.go]:
```suggestion
	RunSpecs(t, "Component CRDDeployer Suite")
```

File: pkg/utils/kubernetes/crd_test.go [hunk 15]
```diff
@@ -0,0 +1,89 @@
...
+
+	BeforeEach(func() {
+		ctx = context.Background()
+		testClientBuilder = fakeclient.NewClientBuilder().WithScheme(apiextensionsscheme.Scheme)
+	})
+
+	JustBeforeEach(func() {
+		// lower waiting timeout so that the unit test itself does not time out.
+		DeferCleanup(test.WithVar(&WaitTimeout, 10*time.Millisecond))
+	})
```
Comment (timuthy) [inline pkg/utils/kubernetes/crd_test.go]: Move to `BeforeEach`?

**Review by timuthy — CHANGES_REQUESTED** [review]
Last comments ;)

File: pkg/utils/kubernetes/crd_test.go [hunk 16]
```diff
@@ -0,0 +1,89 @@
...
+
+	Describe("#WaitUntilCRDManifestsReady", func() {
```
Comment (timuthy) [inline pkg/utils/kubernetes/crd_test.go:55]: Please add another test case when CRD is not available.

**Review by timuthy — COMMENTED** [review]
Thank you!
/lgtm
/approve
