### PR TITLE
Fixes potential leaks of `ShootState`s

### LINKED ISSUE #7784: gardenlet can occasionally leak ShootStates
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
In our landscapes we see leaked ShootStates resources without any associated Shoot.
With had a short look with @plkokanov and @rfranzke and noticed the following gap/flaw:
In the Shoot deletion flow, the ShootState is being deleted after the deletion of the Shoot namespace in the Seed. https://github.com/gardener/gardener/blob/ad6bbae73a100376ff6332e469633ba67554686d/pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go#L637-L641

But we also have the following early exit in the beginning of the Shoot deletion flow - if the Shoot namespace in the Seed does not exist, then we early exit:
https://github.com/gardener/gardener/blob/ad6bbae73a100376ff6332e469633ba67554686d/pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go#L81-L85
https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/pkg/gardenlet/controller/shoot/shoot/reconciler.go#L872-L882

**What you expected to happen**:
No ShootState to be leaked.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot
2. Put a finalizer on the Infrastructure
3. Delete the Shoot
4. Stop gardenlet
5. Purge the Shoot namespace in the Seed
6. Start gardenlet
7. Make sure that the deletion succeeds but the ShootState leaks

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.68.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
This PR fixes a potential leak of `ShootState` resources when the cluster is deleted. The leak could happen if at the end of the deletion flow, the shoot's seed `Namespace` gets deleted then some error occurs and the `ShootState` does not get deleted. When the deletion is retried, there was a check whether the shoot's seed `Namespace` exists or not. If it did not exist, the reconciliation flow exits early and nothing else is done as it incorrectly assumes that all resources have been cleaned up. More details can be found in the corresponding issue - #7784 

The early check and exit is now removed. This has the benefit of not only fixing the potential leak of `ShootState`s but other problems that could occur due to this early exit. For instance: https://github.com/gardener/gardener/issues/7784#issuecomment-1506755764

The check is also removed from the migration flow for consistency.

If you want to test this PR you could introduce a dummy error at the end of the deletion and migration flows (after the shoot's seed `Namespace` is removed) so that they are retried

**Which issue(s) this PR fixes**:
Fixes #7784 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fixed potential leaks of `ShootState`s that could happen when a `Shoot` cluster is deleted. This is achieved by no longer exiting early from the deletion flow if the shoot's seed `Namespace` has been deleted. The same logic has been applied to the migration flow for consistency.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/lgtm

File: pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go [hunk 1]
```diff
@@ -271,7 +268,7 @@ func (r *Reconciler) runMigrateShootFlow(ctx context.Context, o *operation.Opera
 		})
 		deleteKubeAPIServer = g.Add(flow.Task{
 			Name:         "Deleting kube-apiserver deployment",
-			Fn:           flow.TaskFn(botanist.DeleteKubeAPIServer).SkipIf(!kubeAPIServerDeploymentFound),
+			Fn:           flow.TaskFn(botanist.DeleteKubeAPIServer),
```
Comment (oliver-goetz) [inline pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go]: In `reconciler_delete.go` we do this:
```suggestion
			Fn:           flow.TaskFn(botanist.DeleteKubeAPIServer).RetryUntilTimeout(defaultInterval, defaultTimeout),
```
does it make sense here too?

**Review by oliver-goetz — COMMENTED** [review]
🚀

File: pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go (hunk 1 above)
Comment (plkokanov) [reply pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go]: Generally, the migrate flow is a lot shorter than the delete so not having a `RetryUntilTimeout()` isn't a big deal, but I can add it here for consistency.

**Comment by plkokanov** [comment]
@oliver-goetz I applied your suggestion, ptal :)

**Comment by oliver-goetz** [comment]
thanks 🥳 

/lgtm
/approve
