### PR TITLE
Fix update of the Shoot hibernation status after successful reconciliation

### LINKED ISSUE #2960: Mid-air updates lead to shoot deletion failures
**How to categorize this issue?**

/area robustness
/kind bug
/priority normal

**What happened**:
A cluster which had been woken up from hibernation was deleted and but stuck in the deletion flow at the `Initializing connection to Shoot` step.

**What you expected to happen**:
The cluster to be deleted successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Hibernate existing or new cluster
2. Change `.spec` of shoot, e.g. a worker group
3. Wait for the reconciliation to beginn
4. Change `.spec.hibernation.enabled  = false` **during reconciliation**
5. Immediately delete shoot

After the first reconciliation you should notice that the shoot has `.status.hibernated: "false"` even though it's never woken up. As consequence, the deletion fails because Gardener never tries to wake up the control plane.

- Gardener version: v1.11.1

/cc @MartinWeindel

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**How to categorize this PR?**

/area quality
/kind bug
/priority normal

**What this PR does / why we need it**:

Fix update of the Shoot hibernation status after successful reconciliation by deriving the Shoot hibernation status from the Cluster resource instead of the Shoot resource (where the `Spec.Hibernation` could have been changed during the reconciliation).
**Which issue(s) this PR fixes**:
Fixes #2960

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Fixes a bug in the Shoot reconciliation that could lead to failed Shoot deletions when the Hibernation spec has been changed during an active reconciliation.
```

### CODE REVIEW

File: pkg/gardenlet/controller/shoot/shoot_control.go [hunk 1]
```diff
@@ -546,10 +547,12 @@ func (c *Controller) updateShootStatusOperationStart(ctx context.Context, g gard
...
 
-func (c *Controller) updateShootStatusOperationSuccess(ctx context.Context, g gardencore.Interface, shoot *gardencorev1beta1.Shoot, seedName string, operationType gardencorev1beta1.LastOperationType) (*gardencorev1beta1.Shoot, error) {
+func (c *Controller) updateShootStatusOperationSuccess(ctx context.Context, g gardencore.Interface, shoot *gardencorev1beta1.Shoot, shootSeedNamespace string, seedName string, operationType gardencorev1beta1.LastOperationType) (*gardencorev1beta1.Shoot, error) {
 	var (
-		now         = metav1.NewTime(time.Now().UTC())
-		description string
+		now          = metav1.NewTime(time.Now().UTC())
+		description  string
+		err          error
+		isHibernated bool
```
Comment (rfranzke) [inline pkg/gardenlet/controller/shoot/shoot_control.go]:
```suggestion
		isHibernated = gardencorev1beta1helper.HibernationIsEnabled(shoot)
```

File: pkg/gardenlet/controller/shoot/shoot_control.go [hunk 2]
```diff
@@ -560,10 +563,19 @@ func (c *Controller) updateShootStatusOperationSuccess(ctx context.Context, g ga
 		description = "Shoot cluster has been successfully deleted."
 	}
 
+	if len(shootSeedNamespace) > 0 {
+		isHibernated, err = c.isHibernationActive(ctx, shootSeedNamespace, seedName)
+		if err != nil {
+			return nil, fmt.Errorf("error updating Shoot (%s/%s) after successful reconciliation: %v", shoot.Namespace, shoot.Name, err)
+		}
+	} else {
+		isHibernated = gardencorev1beta1helper.HibernationIsEnabled(shoot)
```
Comment (rfranzke) [inline pkg/gardenlet/controller/shoot/shoot_control.go]:
```suggestion
```

File: pkg/gardenlet/controller/shoot/shoot_control.go [hunk 3]
```diff
@@ -560,10 +563,19 @@ func (c *Controller) updateShootStatusOperationSuccess(ctx context.Context, g ga
 		description = "Shoot cluster has been successfully deleted."
 	}
 
+	if len(shootSeedNamespace) > 0 {
+		isHibernated, err = c.isHibernationActive(ctx, shootSeedNamespace, seedName)
+		if err != nil {
+			return nil, fmt.Errorf("error updating Shoot (%s/%s) after successful reconciliation: %v", shoot.Namespace, shoot.Name, err)
```
Comment (rfranzke) [inline pkg/gardenlet/controller/shoot/shoot_control.go]:
```suggestion
			return nil, fmt.Errorf("error updating Shoot (%s/%s) after successful reconciliation when checking for active hiberation: %v", shoot.Namespace, shoot.Name, err)
```

**Review by rfranzke — CHANGES_REQUESTED** [review]
Thanks, looks great, only nits

File: pkg/gardenlet/controller/shoot/shoot_control.go (hunk 1 above)
Comment (danielfoehrKn) [reply pkg/gardenlet/controller/shoot/shoot_control.go]: This unfortunately causes `gardencorev1beta1helper.HibernationIsEnabled(shoot)` to always be executed even though it is not required if `len(shootSeedNamespace) > 0`. Thats why it is in an if-else block.

Comment (rfranzke) [reply pkg/gardenlet/controller/shoot/shoot_control.go]: Yes, but it's not a costly operation at all, so doing it here will save some nesting below (improving readability slightly). I don't insist on this, but I generally think it's a better readable style to do it like this in case the operation is cheap.

Comment (danielfoehrKn) [reply pkg/gardenlet/controller/shoot/shoot_control.go]: ok sure not problem - its indeed only a minimal gain. I though about it as well - but I see it is an issue for you so I ll change it.

**Review by rfranzke — APPROVED** [review]
/lgtm
/second-opinion
/invite @timuthy

**Review by timuthy — APPROVED** [review]
/lgtm
Thanks for taking care!
