### PR TITLE
Fix timestamp expectation when scaling etcd

### LINKED ISSUE #5240: Shoot deletion fails on `Waiting until main and event etcd report readiness`
/area quality
/kind bug
/kind regression
/priority 1

**What happened**:
Looks like with https://github.com/gardener/gardener/pull/5209 a regression is being introduced that prevents Shoot to be deleted successfully. 

**What you expected to happen**:
Shoot deletion to do not hang/fail on task `Waiting until main and event etcd report readiness`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot.

2. After successful creation delete the Shoot.

3. Make sure that the deletion fails with:
```yaml
  lastErrors:
  - description: "task \"Waiting until main and event etcd report readiness\" failed:
      2 errors occurred:\n\t* Error while waiting for Etcd shoot--foo--bar/etcd-events
      to become ready: object's \"gardener.cloud/timestamp\" annotation is not \"2022-01-10
      15:59:46.118532 +0000 UTC\" but \"2022-01-10 15:59:46.460425 +0000 UTC\"\n\t*
      Error while waiting for Etcd shoot--foo--bar/etcd-main to become
      ready: object's \"gardener.cloud/timestamp\" annotation is not \"2022-01-10
      15:59:46.120311 +0000 UTC\" but \"2022-01-10 15:59:46.594125 +0000 UTC\"\n\n"
    lastUpdateTime: "2022-01-10T16:04:46Z"
    taskID: Waiting until main and event etcd report readiness
```

**Environment**:

- Gardener version: 83f20512c06d5e7b6505c8d94db063585501e11a
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area control-plane
/kind regression

**What this PR does / why we need it**:
Fixes an issue introduced by #5209 where Gardener expects a wrong timestamp in the `etcd` resource when scaling happens.

**Which issue(s) this PR fixes**:
Fixes #5240

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by timuthy** [comment]
/needs cherry-pick
for `release-v1.37` and `release-v1.38`

File: pkg/operation/botanist/component/etcd/etcd.go [hunk 1]
```diff
@@ -616,6 +619,36 @@ func (e *etcd) SetOwnerCheckConfig(ownerCheckConfig *OwnerCheckConfig) {
 	e.ownerCheckConfig = ownerCheckConfig
 }
 
+func (e *etcd) ScaleETCD(ctx context.Context, replicas int) error {
```
Comment (rfranzke) [inline pkg/operation/botanist/component/etcd/etcd.go]: Nit Nit: Just call it `Scale` since the package already suggests that it's about etcd :)

**Review by rfranzke — DISMISSED** [review]
/lgtm

File: pkg/gardenlet/controller/shoot/shoot_control_delete.go [hunk 2]
```diff
@@ -255,15 +255,15 @@ func (r *shootReconciler) runDeleteShootFlow(ctx context.Context, o *operation.O
 			Fn:           flow.TaskFn(botanist.DeployEtcd).RetryUntilTimeout(defaultInterval, defaultTimeout).DoIf(cleanupShootResources),
 			Dependencies: flow.NewTaskIDs(deploySecrets, deployCloudProviderSecret, deployOwnerDomainDNSRecord),
 		})
-		_ = g.Add(flow.Task{
+		scaleETCD = g.Add(flow.Task{
```
Comment (timebertt) [inline pkg/gardenlet/controller/shoot/shoot_control_delete.go:258]: I'm wondering, why we need a separate task to scale up etcd at all. Can't we simply make the deploy etcd task scale it up in any case during the shoot deletion flow (always set `spec.replicas=1`)?

I.e. we would need to adapt https://github.com/gardener/gardener/blob/1e09e7d09543d0d4c96207b18703187c400b0e1d/pkg/operation/botanist/etcd.go#L58 to be `b.Shoot.HibernationEnabled && b.Shoot.GetInfo().DeletionTimestamp == nil`.
This will set `retainReplicas` to `false` for shoots in deletion, which will deploy etcd with `spec.replicas=1`, IISIC: https://github.com/gardener/gardener/blob/1e09e7d09543d0d4c96207b18703187c400b0e1d/pkg/operation/botanist/component/etcd/etcd.go#L698-L700

File: pkg/operation/botanist/component/etcd/etcd.go [hunk 3]
```diff
@@ -616,6 +619,36 @@ func (e *etcd) SetOwnerCheckConfig(ownerCheckConfig *OwnerCheckConfig) {
...
+		if err := health.ObjectHasAnnotationWithValue(v1beta1constants.GardenerTimestamp, expectedTimestamp)(etcdObj); err != nil {
+			return err
+		}
+	}
+
+	if _, ok := etcdObj.Annotations[v1beta1constants.GardenerOperation]; ok {
+		return fmt.Errorf("etcd object still has operation annotation set")
+	}
+
+	patch := client.MergeFrom(etcdObj.DeepCopy())
```
Comment (timebertt) [inline pkg/operation/botanist/component/etcd/etcd.go:638]: Only relevant if my first comment is not an option:

Why are you working on a new etcd object here? Components should keep working on the object they already have in memory.
IIUC, this func is always called after `Deploy`, hence `e.etcd` is already initialized with the last-known (relevant) state.

**Review by timebertt — CHANGES_REQUESTED** [review]
Thanks for the fix. I have some concerns, though.

File: pkg/operation/botanist/component/etcd/etcd.go (hunk 3 above)
Comment (timuthy) [reply pkg/operation/botanist/component/etcd/etcd.go:638]: > IIUC, this func is always called after Deploy, hence e.etcd is already initialized with the last-known (relevant) state.

This is only the case if we waited for the object to become ready before we scale. However, during deletion we only wait after we scaled. I tried to work with the in-mem object but that resulted in empty patches.

File: pkg/gardenlet/controller/shoot/shoot_control_delete.go (hunk 2 above)
Comment (timuthy) [reply pkg/gardenlet/controller/shoot/shoot_control_delete.go:258]: I wondered about this as well but decided to focus on the fix right now, i.e. to not change the deletion logic. Can we tackle this separately?

File: pkg/operation/botanist/component/etcd/etcd.go (hunk 1 above)
Comment (timuthy) [reply pkg/operation/botanist/component/etcd/etcd.go]: Nit Nit fixed 😄

File: pkg/gardenlet/controller/shoot/shoot_control_delete.go (hunk 2 above)
Comment (timebertt) [reply pkg/gardenlet/controller/shoot/shoot_control_delete.go:258]: Yes, fair enough. Let's tackle it separately.

File: pkg/operation/botanist/component/etcd/etcd.go (hunk 3 above)
Comment (timebertt) [reply pkg/operation/botanist/component/etcd/etcd.go:638]: Ok, thanks for explaining 👍

**Review by timebertt — APPROVED** [review]
Thanks, I'm fine with the PR now.
/lgtm
/squash
