### PR TITLE
Fix early exit in chart applier

### LINKED ISSUE #1939: Seed bootstrapping fails
**What happened**:
#1863 introduced a bug which causes the Seed bootstrapping to fail for a new Seed.

Bootstrapping fails on apllying the newly introduced VPA `kube-state-metrics-vpa` (see [here](https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/kube-state-metrics/templates/kube-state-metrics.yaml#L47-L58)):
```
time="2020-02-14T11:10:05+01:00" level=error msg="no matches for kind \"VerticalPodAutoscaler\" in version \"autoscaling.k8s.io/v1beta2\"" seed=local-seed
```
It looks like the issue here is the order in which we apply the rendered resources (VPA created before VPA CRD is created).

**What you expected to happen**:
Seed bootstrapping to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Spin up a cluster somewhere.
2. Register it as a seed.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timebertt**
**What this PR does / why we need it**:
Previously, the chart applier did an early exit on error if one of the manifests could not be applied (for example because of a `KindMismatch`). Consequently all following manifests would not be applied, even if they were correct.
With this PR, the chart applier instead tries to apply all given manifests and returns a combined error for all failed manifests if there are any.

**Which issue(s) this PR fixes**:
Fixes #1939

**Special notes for your reviewer**:
For example, when a new Seed is bootstrapped and one manifest cannot be applied (as described in #1939), the Seed condition will look similar to this:
```yaml
status:
  conditions:
  - lastTransitionTime: "2020-02-18T11:13:18Z"
    lastUpdateTime: "2020-02-18T11:13:18Z"
    message: 'failed to apply manifests: 1 error occurred: could not apply object
      of kind "VerticalPodAutoscaler" "garden/kube-state-metrics-vpa": no matches
      for kind "VerticalPodAutoscaler" in version "autoscaling.k8s.io/v1beta2"'
    reason: BootstrappingFailed
    status: "False"
    type: Bootstrapped
```
Though, the rest of the chart is still applied and the bootstrapping will succeed on the second try.

**Release note**:

```improvement operator
The Chart Applier now returns a combined error in case a rendered Manifest cannot be applied instead of doing an early exit on error.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Nice, thank you!
/lgtm

**Review by rfranzke — DISMISSED** [review]

File: pkg/client/kubernetes/apply.go [hunk 1]
```diff
@@ -188,44 +188,64 @@ func (c *Applier) mergeObjects(newObj, oldObj *unstructured.Unstructured, mergeF
...
+			errList = append(errList, fmt.Errorf("could not read object: %+v", err))
+			continue
 		}
 		if obj == nil {
 			continue
 		}
 
 		if err := c.applyObject(ctx, obj, options); err != nil {
-			return err
+			errList = append(errList, fmt.Errorf("could not apply object of kind '%s' '%s/%s': %+v", obj.GetKind(), obj.GetNamespace(), obj.GetName(), err))
```
Comment (timuthy) [inline pkg/client/kubernetes/apply.go]: Nit: Use `multierror.Append(errs, err)` instead of error slice.

Comment (timebertt) [reply pkg/client/kubernetes/apply.go]: Nice suggestion, done :)
PTAL

File: pkg/client/kubernetes/apply.go [hunk 2]
```diff
@@ -20,6 +20,8 @@ import (
 	"fmt"
 	"io"
 
+	"github.com/gardener/gardener/pkg/utils/errors"
```
Comment (rfranzke) [inline pkg/client/kubernetes/apply.go]:
```suggestion
	utilerrors "github.com/gardener/gardener/pkg/utils/errors"
```
to not accidentally mix up with the core `errors` package

File: pkg/utils/errors/multierror.go [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+// multierror.Error instances. The error string is prefixed with <prefix>, all errors are concatenated at the end.
+// This is similar to multierror.ListFormatFunc but does not use any escape sequences, which will look weird in
+// the status of Kubernetes objects or controller logs.
+func NewErrorFormatFuncWithPrefix(prefix string) multierror.ErrorFormatFunc {
+	return func(es []error) string {
+		if len(es) == 1 {
+			return fmt.Sprintf("%s: 1 error occurred: %s", prefix, es[0])
+		}
+
+		errStrings := make([]string, len(es))
```
Comment (rfranzke) [inline pkg/utils/errors/multierror.go]: What's the purpose/benefit of copying the errors over into `[]string` in order to iterate again over it when calling `strings.Join()`?
You are always iterating, can't you just construct the error message and return it?

Also, a small unit test could be added.

Comment (timebertt) [reply pkg/utils/errors/multierror.go]: Sorry, leftover.
Also added a small unit test, PTAL :)

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by timuthy — APPROVED** [review]
