### PR TITLE
Deflake Shootstate secret controller

### LINKED ISSUE #7171: [Flaky Test] Shootstate secret controller Test suite
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
```
------------------------------
• [FAILED] [0.444 seconds]
ShootSecret controller tests
/home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shootstate/secret/secret_test.go:37
  [It] should not remove secrets from shootstate when shoot is in migration
  /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shootstate/secret/secret_test.go:275

```

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7168/pull-gardener-integration/1600798555826556928

**Reason for failure**:
```
Failed after 0.002s.
  Expected
      <[]v1alpha1.GardenerResourceData | len:0, cap:0>: nil
  to contain element matching
      <*matchers.AndMatcher | 0xc0032f3770>: {
          Matchers: [
              <*gstruct.FieldsMatcher | 0xc0032f3740>{
                  Fields: {
                      "Name": <*matchers.EqualMatcher | 0xc0014fcb10>{
                          Expected: <string>"test-7f52c524",
                      },
                  },
                  IgnoreExtras: true,
                  IgnoreMissing: false,
                  failures: nil,
              },
          ],
          firstFailedMatcher: nil,
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/gardenlet/shootstate/secret/secret_test.go:314
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
This PR deflakes Shootstate secret controller test suite.

1. The cluster is created per test case, but uses the seedNamespace.Name which is created per test, which is fixed. Something similar to #7158 
2. Use labelselector for the manager cache.
3. Wait until the manager cache has observed relevant changes.

**Which issue(s) this PR fixes**:
Fixes #7171 

**Special notes for your reviewer**:
/cc @acumino

Before:
```
❯ stress -ignore "unable to grab random port | resource quota evaluation timed out" -p 32 ./test/integration/gardenlet/shootstate/secret/secret.test -ginkgo.v -ginkgo.progress
...
2m35s: 99 runs so far, 3 failures (3.03%)
2m40s: 114 runs so far, 3 failures (2.63%)
2m45s: 128 runs so far, 3 failures (2.34%)
2m50s: 128 runs so far, 3 failures (2.34%)
```
After:
```
❯ stress -ignore "unable to grab random port | resource quota evaluation timed out" -p 32 ./test/integration/gardenlet/shootstate/secret/secret.test -ginkgo.v -ginkgo.progress
...
21m5s: 992 runs so far, 0 failures
21m10s: 1015 runs so far, 0 failures
21m15s: 1024 runs so far, 0 failures
21m20s: 1024 runs so far, 0 failures 
```

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
> @shafeeqes: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-e2e-kind	[19a235b](https://github.com/gardener/gardener/commit/19a235b1fbed4135500ca06914253b35a290a95f)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7228/pull-gardener-e2e-kind/1604722649248829440)	true	`/test pull-gardener-e2e-kind`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=7228). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Ashafeeqes). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

Opened https://github.com/gardener/gardener/issues/7229
/test pull-gardener-e2e-kind

File: test/integration/gardenlet/shootstate/secret/secret_test.go [hunk 1]
```diff
@@ -42,10 +44,37 @@ var _ = Describe("ShootSecret controller tests", func() {
...
+		seedNamespace *corev1.Namespace
 	)
 
 	BeforeEach(func() {
-		resourceName = "test-" + utils.ComputeSHA256Hex([]byte(CurrentSpecReport().LeafNodeLocation.String()))[:8]
+		resourceName = "test-" + utils.ComputeSHA256Hex([]byte(uuid.NewUUID()))[:8]
+
+		By("creating seed namespace")
+		// name doesn't follow the usual naming scheme (technical ID), but this doesn't matter for this test, as
+		// long as the cluster has the same name
```
Comment (ary1992) [inline test/integration/gardenlet/shootstate/secret/secret_test.go:56]: Is this comment relevant here?

Comment (shafeeqes) [reply test/integration/gardenlet/shootstate/secret/secret_test.go:56]: Yes. The cluster name and the shoot namespace in the seed is usually the shoot technical ID which is not the case here.

**Review by rfranzke — COMMENTED** [review]
/approve
