### PR TITLE
Cache sync health check with deadline

### LINKED ISSUE #11944: Shoot deletion is stuck due to unready resource manager
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
The shoot deletion was stuck during deletion because the `gardener-resource-manager` deployment didn't get ready.

Task Error:

```
task "Waiting until gardener-resource-manager reports readiness" failed: retry failed with context deadline exceeded, last error: condition "Available" has invalid status False (expected True) due to MinimumReplicasUnavailable: Deployment does not have minimum availability.
```

GRM in Control-Plane:

```
NAME                                                  READY   STATUS    RESTARTS       AGE
gardener-resource-manager-8487456bb5-5vvdk            1/1     Running   0              6h2m
gardener-resource-manager-8487456bb5-6qx5s            0/1     Running   0              6h3m
```

GRM Error Log:

```
{"level":"error","ts":"2025-04-25T14:57:56.457Z","msg":"Reconciler error","controller":"garbage-collector","namespace":"","name":"","reconcileID":"43e9dd49-1d05-4db7-a9cb-453b71acc588","error":"failed listing objects of gvk monitoring.coreos.com/v1, Kind=PrometheusList: Timeout: failed waiting for *v1.PartialObjectMetadata Informer to sync","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"}
```

Root cause:

The error log of GRM already shows that it couldn't wait for the informer sync, a check that is reused for the readiness probe of the GRM itself (see [here](https://github.com/gardener/gardener/blob/23bf7c2dd2e63b338accc68c5b53c1209e9df79a/cmd/gardener-resource-manager/app/app.go#L200)).

@rfranzke and I could identify the following key events that lead to this behavior:

1. GRM is started and executes discovery, i.e. fills the REST mapper with all available API groups (incl. `monitoring.coreos.com/v1` in this case). **Important:** This happens before the replica is elected as a leader.
2. Gardener deletes the `Prometheus` CRD as part of its shoot cleanup.
3. GRM replica is elected as leader and starts all controllers.
4. Because it has a valid mapping from step 1, the target client builds an informer for `Prometheus` resources but only fails later when [`cache.WaitForCacheSync`](https://github.com/kubernetes-sigs/controller-runtime/blob/6ad5c1dd4418489606d19dfb87bf38905b440561/pkg/cache/internal/informers.go#L316) is called.
5. The `cache.WaitForCacheSync` result also leads to the failing readiness probe.

The situation can only be resolved by deleting the affected GRM pod.

**Anything else we need to know?**:

This problem can potentially occur in many Gardener components, not only the resource manager. We should add a liveness check that returns an error whenever the informer cache sync isn't successful for a certain period.

**Environment**:

- Gardener version: v1.117.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area robustness
/kind enhancement

**What this PR does / why we need it**:
This PR introduces a new liveness probe for all Gardener components which fails if their watch caches don't sync of `3m`. This will result in `kubelet` restarting them to allow them to rebuild their caches.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/11944

**Special notes for your reviewer**:
/cc @timuthy 

**Release note**:

```feature operator
Gardener core components are automatically restarted (due to a failing liveness probe) in case their Kubernetes API server watch caches do not sync for `3m`.
```

### CODE REVIEW

File: pkg/healthz/informer.go [hunk 1]
```diff
@@ -10,23 +10,55 @@ import (
...
+			if notSyncedSince == nil {
+				notSyncedSince = ptr.To(Now())
+			}
 
-		if !cacheSyncWaiter.WaitForCacheSync(ctx) {
-			return errors.New("informers not synced yet")
+			if Now().Sub(*notSyncedSince) >= deadline {
+				return err
+			}
+			return nil
```
Comment (timuthy) [inline pkg/healthz/informer.go:58]: What do you think adding a log entry here that the sync failed and for how long it's been the case?

File: pkg/healthz/informer_test.go [hunk 2]
```diff
@@ -6,26 +6,98 @@ package healthz_test
...
+
+		It("should succeed if all informers sync", func() {
+			checker = NewCacheSyncHealthzWithDeadline(&fakeSyncWaiter{true}, deadline)
+			Expect(checker(nil)).To(Succeed())
+		})
+
+		When("the informers are not synced", func() {
+			var (
+				waiter *fakeSyncWaiter
+				now    time.Time
```
Comment (timuthy) [inline pkg/healthz/informer_test.go]: Nit: Use `clock` which can be prepared more accurately for tests?

**Review by timuthy — COMMENTED** [review]
Nice, thanks for the fix 🚀

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve
