### PR TITLE
Validate that only `Secret` and `ConfigMap` can be referenced in `.spec.resources` in `Shoot`s

### LINKED ISSUE #7955: GCM reference protection controller is not (un)setting the finalizer on the referenced resources or does it too late
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
* User added a cm
* User was creating a shoot with auditlog policy enabled ([like this](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_auditpolicy.md))
* User was able to remove their auditlog policy configmap and their shoot failed to create

**What you expected to happen**:
User not to be able to break their shoot during deployment.

**How to reproduce it (as minimally and precisely as possible)**:
* create a configmap ([here, but change the namespace](https://github.com/gardener/gardener/blob/master/example/95-configmap-custom-audit-policy.yaml))
* Create a shoot with the spec from [doc](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_auditpolicy.md) added
* Delete the cm with `kubectl delete cm auditlog`
* Edit out the finalizer from that cm (`kubectl patch configmap auditlog --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'`)
* configmap is deleted and cluster fails to create

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.70.2
- Kubernetes version (use `kubectl version`):  v1.26.2 (doesn't really matter ) 
- Cloud provider or hardware configuration: Any
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR adds validation that only `Secret` and `ConfigMap` can be referenced in shoot `spec.resources` and updates shoot predicate for the shoot reference controller so a change in `spec.resources` also triggers its reconciliation.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/7955#issuecomment-1559321243

**Special notes for your reviewer**:

**Release note**:

```breaking user
Any resource with a kind other than `ConfigMap` or `Secret` in `.spec.resources` in `Shoot`s is now forcefully removed. New validation has been introduced to prevent adding other resources in the future.
```
```bugfix user
A bug that prevented referencing `ConfigMap`s in `.spec.resources` in `Shoot`s has been fixed.
```
```bugfix user
A bug that prevented finalizers from being added to referenced `Secret`s or `ConfigMap`s in `.spec.resources` in `Shoot`s has been fixed.
```

### CODE REVIEW

File: pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_shoot.go [hunk 1]
```diff
@@ -137,10 +137,16 @@ func (g *graph) handleShootCreateOrUpdate(shoot *gardencorev1beta1.Shoot) {
 	}
 
 	for _, resource := range shoot.Spec.Resources {
-		// only secrets are supported here
-		if resource.ResourceRef.APIVersion == "v1" && resource.ResourceRef.Kind == "Secret" {
-			secretVertex := g.getOrCreateVertex(VertexTypeSecret, shoot.Namespace, resource.ResourceRef.Name)
-			g.addEdge(secretVertex, shootVertex)
+		// only secrets and configMap are supported here
```
Comment (shafeeqes) [inline pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_shoot.go:140]: Please add unit tests in https://github.com/gardener/gardener/blob/8b3fe1899087fae38849d6ffea67e7b4217b2d78/pkg/admissioncontroller/webhook/auth/seed/graph/graph_test.go#L420

File: pkg/apis/core/validation/utils.go [hunk 2]
```diff
@@ -52,15 +52,25 @@ func validateSecretReference(ref corev1.SecretReference, fldPath *field.Path) fi
...
+	} else {
+		if ref.APIVersion != corev1.SchemeGroupVersion.String() {
+			allErrs = append(allErrs, field.NotSupported(fldPath.Child("apiVersion"), ref.APIVersion, []string{corev1.SchemeGroupVersion.String()}))
+		}
+	}
+
 	if len(ref.Kind) == 0 {
 		allErrs = append(allErrs, field.Required(fldPath.Child("kind"), "must provide a kind"))
+	} else {
+		if ref.Kind != "Secret" && ref.Kind != "ConfigMap" {
```
Comment (shafeeqes) [inline pkg/apis/core/validation/utils.go:66]: Unit tests missing

File: pkg/controllermanager/controller/shoot/reference/add_test.go [hunk 3]
```diff
@@ -92,6 +93,19 @@ var _ = Describe("Add", func() {
 					}
 					Expect(p.Update(event.UpdateEvent{ObjectNew: shoot, ObjectOld: oldShoot})).To(BeTrue())
 				})
+
+				It("should return false because the resources field changed", func() {
```
Comment (shafeeqes) [inline pkg/controllermanager/controller/shoot/reference/add_test.go]:
```suggestion
				It("should return true because the resources field changed", func() {
```

File: pkg/controllermanager/controller/shoot/reference/add_test.go [hunk 4]
```diff
@@ -81,7 +82,7 @@ var _ = Describe("Add", func() {
 					Expect(p.Update(event.UpdateEvent{ObjectNew: shoot, ObjectOld: oldShoot})).To(BeTrue())
 				})
 
-				It("should return because the audit policy fields changed", func() {
+				It("should return true because the audit policy field changed", func() {
```
Comment (shafeeqes) [inline pkg/controllermanager/controller/shoot/reference/add_test.go:85]:
```
				It("should return true because the DNS fields changed", func() {
```
Please correct the above description as well.

File: pkg/apis/core/validation/utils.go (hunk 2 above)
Comment (acumino) [reply pkg/apis/core/validation/utils.go:66]: `validateCrossVersionObjectReference` is not exported, so can't add unit test.

Comment (shafeeqes) [reply pkg/apis/core/validation/utils.go:66]: You can add a test in `core/validation/shoot_test.go`

File: pkg/controllermanager/controller/shoot/reference/add_test.go (hunk 4 above)
Comment (acumino) [reply pkg/controllermanager/controller/shoot/reference/add_test.go:85]: No, it's correct only. This test is for `AuditConfig`.

Comment (shafeeqes) [reply pkg/controllermanager/controller/shoot/reference/add_test.go:85]: I meant https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/pkg/controllermanager/controller/shoot/reference/add_test.go#L74

**Review by rfranzke — COMMENTED** [review]
What about existing `Shoot`s which already reference resources other than `Secret` or `ConfigMap`?

**Comment by acumino** [comment]
> What about existing `Shoot`s which already reference resources other than `Secret` or `ConfigMap`?

If anything other than `Secret`  would have referenced, Shoot would not have got healthy with the following error:
```
task "Deploying referenced resources" failed: retry failed with context deadline exceeded, last error: configmaps "foo" is forbidden: User "gardener.cloud:system:seed:local" cannot get resource "configmaps" in API group "" in the namespace "garden-local": no relationship found between seed 'local' and this object
```

**Comment by rfranzke** [comment]
> > What about existing `Shoot`s which already reference resources other than `Secret` or `ConfigMap`?
> 
> If anything other than `Secret` would have referenced, Shoot would not have got healthy with the following error:
> 
> ```
> task "Deploying referenced resources" failed: retry failed with context deadline exceeded, last error: configmaps "foo" is forbidden: User "gardener.cloud:system:seed:local" cannot get resource "configmaps" in API group "" in the namespace "garden-local": no relationship found between seed 'local' and this object
> ```

OK, but with this new validation, any updates on such `Shoot`s would be prevented, right? Is deletion still possible? What about `Shoot`s that are already in deletion?

**Comment by acumino** [comment]
> OK, but with this new validation, any updates on such `Shoot`s would be prevented, right? 

Yes, but if `spec.resources` is updated then it will be allowed.

> Is deletion still possible? 

No, It was not possible in the past also, to support deletion [this](https://github.com/gardener/gardener/blob/13d5158c55cc6b21ff1a24bb068c00dd223e8563/pkg/admissioncontroller/webhook/auth/seed/authorizer.go#L91) function need to be enhanced in such a way that if the shoot is in deletion then any referenced resource should be allowed, the one way to implement this is:
```
any requested resource which is in the namespace whose name is `garden-<something>` should be allowed
```
But this doesn't seem to be the correct approach.

> What about `Shoot`s that are already in deletion?

They will be stuck in deletion.

File: pkg/apis/core/v1beta1/helper/helper.go [hunk 5]
```diff
@@ -991,23 +991,27 @@ func ShootDNSProviderSecretNamesEqual(oldDNS, newDNS *gardencorev1beta1.DNS) boo
...
 		newNames = sets.New[string]()
 	)
 
 	for _, resource := range oldResources {
-		if resource.ResourceRef.APIVersion == "v1" && resource.ResourceRef.Kind == "Secret" {
-			oldNames.Insert(resource.ResourceRef.Name)
+		if resource.ResourceRef.APIVersion == "v1" {
+			if resource.ResourceRef.Kind == "Secret" || resource.ResourceRef.Kind == "ConfigMap" {
+				oldNames.Insert(resource.ResourceRef.Kind + resource.ResourceRef.Name)
+			}
```
Comment (rfranzke) [inline pkg/apis/core/v1beta1/helper/helper.go]:
```suggestion
		if resource.ResourceRef.APIVersion == "v1" && sets.New("Secret", "ConfigMap").Has(resource.ResourceRef.Kind) {
			oldNames.Insert(resource.ResourceRef.Kind + resource.ResourceRef.Name)
```

File: pkg/apis/core/v1beta1/helper/helper.go [hunk 6]
```diff
@@ -991,23 +991,27 @@ func ShootDNSProviderSecretNamesEqual(oldDNS, newDNS *gardencorev1beta1.DNS) boo
...
 		}
 	}
 
 	for _, resource := range newResources {
-		if resource.ResourceRef.APIVersion == "v1" && resource.ResourceRef.Kind == "Secret" {
-			newNames.Insert(resource.ResourceRef.Name)
+		if resource.ResourceRef.APIVersion == "v1" {
+			if resource.ResourceRef.Kind == "Secret" || resource.ResourceRef.Kind == "ConfigMap" {
```
Comment (rfranzke) [inline pkg/apis/core/v1beta1/helper/helper.go]: same here

File: pkg/apis/core/validation/utils.go [hunk 7]
```diff
@@ -52,15 +52,25 @@ func validateSecretReference(ref corev1.SecretReference, fldPath *field.Path) fi
 func validateCrossVersionObjectReference(ref autoscalingv1.CrossVersionObjectReference, fldPath *field.Path) field.ErrorList {
 	allErrs := field.ErrorList{}
 
+	if len(ref.APIVersion) == 0 {
+		allErrs = append(allErrs, field.Required(fldPath.Child("apiVersion"), "must provide a apiVersion"))
```
Comment (rfranzke) [inline pkg/apis/core/validation/utils.go]:
```suggestion
		allErrs = append(allErrs, field.Required(fldPath.Child("apiVersion"), "must provide an apiVersion"))
```

**Comment by rfranzke** [comment]
> > OK, but with this new validation, any updates on such `Shoot`s would be prevented, right?
> 
> Yes, but if `spec.resources` is updated then it will be allowed.
> 
> > Is deletion still possible?
> 
> No, It was not possible in the past also, to support deletion [this](https://github.com/gardener/gardener/blob/13d5158c55cc6b21ff1a24bb068c00dd223e8563/pkg/admissioncontroller/webhook/auth/seed/authorizer.go#L91) function need to be enhanced in such a way that if the shoot is in deletion then any referenced resource should be allowed, the one way to implement this is:
> 
> ```
> any requested resource which is in the namespace whose name is `garden-<something>` should be allowed
> ```
> 
> But this doesn't seem to be the correct approach.
> 
> > What about `Shoot`s that are already in deletion?
> 
> They will be stuck in deletion.

This doesn't sound too ops-friendly. Perhaps we should rather remove non-`Secret`/`ConfigMap` references from `Shoot`s as part of the API server registry to prevent that the new validation code blocks any (unrelated) client calls. Currently, API-wise the change is backwards-incompatible.

**Comment by acumino** [comment]
> 
> This doesn't sound too ops-friendly. Perhaps we should rather remove non-`Secret`/`ConfigMap` references from `Shoot`s as part of the API server registry to prevent that the new validation code blocks any (unrelated) client calls. Currently, API-wise the change is backwards-incompatible.

Added handling for it in 03e6461be164dcc192c9fc11e2ab5a731b9faa2a

File: pkg/registry/core/shoot/strategy.go [hunk 8]
```diff
@@ -191,6 +192,23 @@ func (shootStrategy) Canonicalize(obj runtime.Object) {
 	if versionutils.ConstraintK8sGreaterEqual125.Check(semver.MustParse(shoot.Spec.Kubernetes.Version)) {
 		cleanupAdmissionPlugins(shoot)
 	}
+	// TODO(acumino): Drop this in release v1.74
+	cleanupReferencedResources(shoot)
+}
+
+func cleanupReferencedResources(shoot *core.Shoot) {
```
Comment (rfranzke) [inline pkg/registry/core/shoot/strategy.go:199]: Can you add a small unit test for this logic?

File: pkg/apis/core/v1beta1/helper/helper.go [hunk 9]
```diff
@@ -991,23 +991,23 @@ func ShootDNSProviderSecretNamesEqual(oldDNS, newDNS *gardencorev1beta1.DNS) boo
...
+		if resource.ResourceRef.APIVersion == "v1" && sets.New("Secret", "ConfigMap").Has(resource.ResourceRef.Kind) {
+			oldNames.Insert(resource.ResourceRef.Kind + resource.ResourceRef.Name)
 		}
 	}
 
 	for _, resource := range newResources {
-		if resource.ResourceRef.APIVersion == "v1" && resource.ResourceRef.Kind == "Secret" {
-			newNames.Insert(resource.ResourceRef.Name)
+		if resource.ResourceRef.APIVersion == "v1" && sets.New("Secret", "ConfigMap").Has(resource.ResourceRef.Kind) {
+			newNames.Insert(resource.ResourceRef.Kind + resource.ResourceRef.Name)
```
Comment (shafeeqes) [inline pkg/apis/core/v1beta1/helper/helper.go]: Although it doesn't matter.
```suggestion
			newNames.Insert(resource.ResourceRef.Kind + "/" + resource.ResourceRef.Name)
```

File: pkg/apis/core/v1beta1/helper/helper_test.go [hunk 10]
```diff
@@ -1998,18 +1998,20 @@ var _ = Describe("helper", func() {
...
 		Entry("difference", []gardencorev1beta1.NamedResourceReference{{ResourceRef: autoscalingv1.CrossVersionObjectReference{APIVersion: "v1", Kind: "Secret", Name: "foo"}}}, []gardencorev1beta1.NamedResourceReference{{ResourceRef: autoscalingv1.CrossVersionObjectReference{APIVersion: "v1", Kind: "Secret", Name: "bar"}}}, BeFalse()),
 		Entry("difference because no secret", []gardencorev1beta1.NamedResourceReference{{ResourceRef: autoscalingv1.CrossVersionObjectReference{APIVersion: "v1", Kind: "Secret", Name: "foo"}}}, []gardencorev1beta1.NamedResourceReference{{ResourceRef: autoscalingv1.CrossVersionObjectReference{APIVersion: "v1", Kind: "ConfigMap", Name: "foo"}}}, BeFalse()),
+		Entry("difference beacuse new is configMap with same name", []gardencorev1beta1.NamedResourceReference{{ResourceRef: autoscalingv1.CrossVersionObjectReference{APIVersion: "v1", Kind: "Secret", Name: "foo"}}}, []gardencorev1beta1.NamedResourceReference{{ResourceRef: autoscalingv1.CrossVersionObjectReference{APIVersion: "v1", Kind: "ConfigMap", Name: "foo"}}}, BeFalse()),
```
Comment (shafeeqes) [inline pkg/apis/core/v1beta1/helper/helper_test.go:2014]: Isn't this test same as the previous one?

Comment (acumino) [reply pkg/apis/core/v1beta1/helper/helper_test.go:2014]: It was missed.

**Review by rfranzke — COMMENTED** [review]
/lgtm

File: pkg/controllermanager/controller/shoot/reference/add.go [hunk 11]
```diff
@@ -83,3 +84,7 @@ func shootDNSFieldChanged(oldShoot, newShoot *gardencorev1beta1.Shoot) bool {
 func shootKubeAPIServerAuditConfigFieldChanged(oldShoot, newShoot *gardencorev1beta1.Shoot) bool {
 	return !apiequality.Semantic.Equalities.DeepEqual(oldShoot.Spec.Kubernetes.KubeAPIServer.AuditConfig, newShoot.Spec.Kubernetes.KubeAPIServer.AuditConfig)
 }
+
+func shootReferencedResourceChanged(oldShoot, newShoot *gardencorev1beta1.Shoot) bool {
```
Comment (shafeeqes) [inline pkg/controllermanager/controller/shoot/reference/add.go:88]: Should we use `!v1beta1helper.ShootResourceReferencesEqual` too?

Comment (shafeeqes) [inline pkg/controllermanager/controller/shoot/reference/add.go]: Can we use `!v1beta1helper.ShootResourceReferencesEqual` here as well?

**Review by shafeeqes — APPROVED** [review]
/lgtm

**Comment by vpnachev** [comment]
What do you think about cherry-picking this change? 
I guess at least 51e597a940a9d66729cfaf23717c604b73827ee6 must be backported to the older versions, wdyt?

**Comment by acumino** [comment]
> What do you think about cherry-picking this change? I guess at least [51e597a](https://github.com/gardener/gardener/commit/51e597a940a9d66729cfaf23717c604b73827ee6) must be backported to the older versions, wdyt?

Minor version will be released by tomorrow, IMO we can leave the patch.

**Comment by vpnachev** [comment]
It is not like the older versions are not affected. We have users are affected on daily basis by shoots hanging in deletion because the referenced resources are not protected and deleted too early. So please, take care to fix the bug also in the still supported gardener versions (1.69, 1.70 and 1.71 as of today)!
