### PR TITLE
Fix nil pointer error in `seed-lifecycle` controller

### LINKED ISSUE #7235: gardener-controller-manager: invalid memory address or nil pointer dereference
**How to categorize this issue?**

/area control-plane
/kind bug
/kind regression

**What happened**:
I was following https://github.com/gardener/gardener/blob/master/docs/development/getting_started_locally.md. 
I executed:
```
$ make register-local-env
```

In the gardener-controller-manager logs there was the following panic:
```
2022-12-19T11:48:13.795+0200	ERROR	Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 873 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2770040?, 0x3ce9f10})
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:110 +0xb9
panic({0x2770040, 0x3ce9f10})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/gardener/gardener/pkg/controllermanager/controller/seed/lifecycle.(*Reconciler).Reconcile(0xc0000b9b30, {0x2d05278, 0xc000d1a660}, {{{0x0?, 0x10?}, {0xc0005ce824?, 0x100f287?}}})
	/Users/i331370/go/src/github.com/gardener/gardener/pkg/controllermanager/controller/seed/lifecycle/reconciler.go:135 +0x11a1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2d051d0?, {0x2d05278?, 0xc000d1a660?}, {{{0x0?, 0x28f07c0?}, {0xc0005ce824?, 0x1004dd4?}}})
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0006b1d60, {0x2d051d0, 0xc000d9b0c0}, {0x27ec520?, 0xc00129e9e0?})
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0006b1d60, {0x2d051d0, 0xc000d9b0c0})
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:230 +0x333

k8s.io/apimachinery/pkg/util/runtime.logPanic
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:79
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:110
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:884
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:835
github.com/gardener/gardener/pkg/controllermanager/controller/seed/lifecycle.(*Reconciler).Reconcile
	/Users/i331370/go/src/github.com/gardener/gardener/pkg/controllermanager/controller/seed/lifecycle/reconciler.go:135
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234
2022-12-19T11:48:13.796+0200	ERROR	Reconciler error	{"controller": "seed-lifecycle", "controllerGroup": "core.gardener.cloud", "controllerKind": "Seed", "Seed": {"name":"local"}, "namespace": "", "name": "local", "reconcileID": "709bd337-53ff-436f-8a67-5f4be0dc3cd9", "error": "panic: runtime error: invalid memory address or nil pointer dereference [recovered]"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:326
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/Users/i331370/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234
2022-12-19T11:48:13.801+0200	INFO	Setting Seed status to 'Unknown' as gardenlet stopped reporting seed status	{"controller": "seed-lifecycle", "controllerGroup": "core.gardener.cloud", "controllerKind": "Seed", "Seed": {"name":"local"}, "namespace": "", "name": "local", "
```

**What you expected to happen**:
No such panic.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 44c7c5613ed79a618900a5bfacd3d812224fb3e1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
A nil pointer Panic can occur in `seed-lifecycle`  controller in case `GardenletReady` condition is not set on seed.
This PR fixes nil pointer issues in the `seed-lifecycle` controller.

**Which issue(s) this PR fixes**:
Fixes #7235

**Special notes for your reviewer**:

**Release note**:

```other operator
An issue causing a nil pointer error in the `seed-lifecycle` controller is fixed.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
/milestone v1.65

File: pkg/controllermanager/controller/seed/lifecycle/reconciler.go [hunk 1]
```diff
@@ -132,8 +133,12 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
 		return reconcile.Result{RequeueAfter: r.Config.SyncPeriod.Duration}, nil
 	}
 
+	var lastTransitionTime time.Time
+	if conditionGardenletReady != nil {
+		lastTransitionTime = conditionGardenletReady.LastTransitionTime.UTC()
+	}
 	log.Info("Gardenlet has not sent heartbeats for at least the configured shoot monitor period, setting shoot conditions and constraints to 'Unknown' for all shoots on this seed",
-		"gardenletOfflineSince", conditionGardenletReady.LastTransitionTime.UTC(),
+		"gardenletOfflineSince", lastTransitionTime,
```
Comment (ialidzhikov) [inline pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: I guess it makes more sense to log `gardenletOfflineSince`: `unknown` instead of `gardenletOfflineSince`: ` 0001-01-01 00:00:00 +0000 UTC.`. Don't we want to improve this aspect?

/hold

Comment (acumino) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: Can we set the time to `unknown`?
What about setting it to seed creationTimestamp, if `GardenletReady` condition is not set?

Comment (ialidzhikov) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: > Can we set the time to `unknown`?

We cannot set time.Time to unknown but for the logger it should matter - it accepts key-values as `interface{}`.

> What about setting it to seed creationTimestamp, if `GardenletReady` condition is not set?

Theoretically, `GardenletReady` condition could be missing not only on Seed creation. It can be removed by operator for some reason, or removed due to a potential bug on our side. I rather vote for `gardenletOfflineSince: unknown` or completely omitting logging the `gardenletOfflineSince` when the `GardenletReady` condition is not present - we simply don't know since when gardenlet is offline. WDYT?

Comment (acumino) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: To make sure it logs the same thing, I prefer to keep `gardenletOfflineSince` with unknown. 
Made changes in 0b410ea43f46734d5e0230c9e69618370d5281a9. PTAL.

File: pkg/controllermanager/controller/seed/lifecycle/reconciler.go [hunk 2]
```diff
@@ -133,15 +132,19 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
 		return reconcile.Result{RequeueAfter: r.Config.SyncPeriod.Duration}, nil
 	}
 
-	var lastTransitionTime time.Time
```
Comment (ialidzhikov) [inline pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: Can it be written as 
```golang
	var gardenletOfflineSince interface{}
	if conditionGardenletReady != nil {
		gardenletOfflineSince = conditionGardenletReady.LastTransitionTime.UTC()
	} else {
		gardenletOfflineSince = "unknown"
	}
	log.Info("Gardenlet has not sent heartbeats for at least the configured shoot monitor period, setting shoot conditions and constraints to 'Unknown' for all shoots on this seed",
		"gardenletOfflineSince", gardenletOfflineSince,
		"now", r.Clock.Now().UTC(),
		"shootMonitorPeriod", r.Config.ShootMonitorPeriod.Duration,
	)
```

I think this way we duplicate much less things.

Comment (acumino) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: Thanks, this is better.

File: pkg/controllermanager/controller/seed/lifecycle/reconciler.go [hunk 3]
```diff
@@ -132,8 +132,15 @@ func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reco
 		return reconcile.Result{RequeueAfter: r.Config.SyncPeriod.Duration}, nil
 	}
 
+	var gardenletOfflineSince interface{}
+	if conditionGardenletReady != nil {
+		gardenletOfflineSince = conditionGardenletReady.LastTransitionTime.UTC()
+	} else {
+		gardenletOfflineSince = "Unknown"
+	}
```
Comment (Kostov6) [inline pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: I think it can be even further simplified

```suggestion
	gardenletOfflineSince := "Unknown"
	if conditionGardenletReady != nil {
		gardenletOfflineSince = conditionGardenletReady.LastTransitionTime.UTC().String()
	}
```

Comment (acumino) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: It can't be done, once the variable is initialized its type is set, and it can't be changed.

Comment (ialidzhikov) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: Hm, in `gardenletOfflineSince := "Unknown"`, `gardenletOfflineSince` is string. `conditionGardenletReady.LastTransitionTime.UTC().String()` also evaluates to string. We should not be changing the type of the `gardenletOfflineSince` var.

Comment (timuthy) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: +1 the logger has specific "stringify" logic depending on the underlying type.

**Review by timuthy — COMMENTED** [review]
/lgtm
@ialidzhikov feel free to approve (unhold) as soon as you are happy with the shape of this PR.

File: pkg/controllermanager/controller/seed/lifecycle/reconciler.go (hunk 3 above)
Comment (ialidzhikov) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: @timuthy can you elaborate more?

Comment (ialidzhikov) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: Do you mean that the logger has internal "stringify" logic for `time.Time` and we should rather avoid passing already stringified `time.Time`?

Comment (ialidzhikov) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: We could keep the var of type `interface{}` then:
```golang
	var gardenletOfflineSince interface{} = "Unknown"
	if conditionGardenletReady != nil {
		gardenletOfflineSince = conditionGardenletReady.LastTransitionTime.UTC()
	}
```

Is this approach ok for you?

Comment (timuthy) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: @acumino can you revert the latest changes? As said above by Ismail, we should keep the type time.Time.

**Review by ialidzhikov — COMMENTED** [review]
/lgtm
/unhold

File: pkg/controllermanager/controller/seed/lifecycle/reconciler.go (hunk 3 above)
Comment (acumino) [reply pkg/controllermanager/controller/seed/lifecycle/reconciler.go]: Update the PR.
