### PR TITLE
Fix(control-plane-migration): stuck for hibernated shoots at "Waiting until ManagedResources are deleted"

### LINKED ISSUE #7606: Control-plane migration stuck for shoots hibernated for at least 24 hours
**How to categorize this issue?**
/area control-plane-migration
/kind bug

**What happened**:
When triggering a control-plane migration for shoots that were hibernated for more than 24h, the migration gets stuck at the "Waiting until ManagedResources are deleted" step.

This happens because the token in the `shoot-access-gardener-resource-manager` secret expires after 24h and therefore the `gardener-resource-manager` is unable to communicate with the shoot apiserver.

**What you expected to happen**:
A successful control-plane migration 🙂
**How to reproduce it (as minimally and precisely as possible)**:
1. Hibernate shoot
2. Wait 24h **or** update the `shoot-access-gardener-resource-manager` secret token (to something invalid) and remove the `serviceaccount.resources.gardener.cloud/token-expiration-duration` label
3. Trigger a control-plane migration
4. See the `Migrate` operation being stuck at "Waiting until ManagedResources are deleted"

**Anything else we need to know?**:
In the migration flow the `gardener-resource-manager` deployment is only scaled up: https://github.com/gardener/gardener/blob/2f34cb1422985253aa47eb761bb759d6ae4823e3/pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go#L175-L179

However, it is necessary to re-run the bootstrap logic for the `gardener-resource-manager` due to the `shoot-access-gardener-resource-manager` secret being expired.

In every reconcile (which includes waking up a hibernated shoot) it is checked if the bootstrap logic must be triggered in the `DeployGardenerResourceManager` func:
https://github.com/gardener/gardener/blob/3f666d244bd497074b40c5e1182fa2f8ddc1e5e2/pkg/operation/botanist/resource_manager.go#L124-L152

I would therefore propose to additionally call `DeployGardenerResourceManager` before the  `ensureResourceManagerScaledUp` task of the migrate flow.
This PR contains the proposed change #7608  

**Environment**:

- Gardener version: 1.62.1
- Kubernetes version: 1.23.16

### PR DESCRIPTION
**Pull request by Kumm-Kai**
**How to categorize this PR?**
/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
Adds an additional task in the shoot migrate flow that calls `DeployGardenerResourceManager` which triggers a re-run of the bootstrap logic if needed.

**Which issue(s) this PR fixes**:
Fixes #7606 with my proposed change.

**Release note**:
```bugfix user
Fixes control-plane migration of hibernated shoot being stuck if shoot was hibernated for 24h
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Thanks, that's a nice finding :)
/lgtm
/ok-to-test
/cc @plkokanov

File: pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go [hunk 1]
```diff
@@ -172,10 +172,15 @@ func (r *Reconciler) runMigrateShootFlow(ctx context.Context, o *operation.Opera
 			Fn:           flow.TaskFn(botanist.WakeUpKubeAPIServer).DoIf(wakeupRequired),
 			Dependencies: flow.NewTaskIDs(deployETCD, scaleUpETCD, waitUntilControlPlaneReady),
 		})
+		deployGardenerResourceManager = g.Add(flow.Task{
+			Name:         "Deploying gardener-resource-manager (re-run bootstrap if needed)",
+			Fn:           flow.TaskFn(botanist.DeployGardenerResourceManager).DoIf(cleanupShootResources),
+			Dependencies: flow.NewTaskIDs(wakeUpKubeAPIServer),
+		})
 		ensureResourceManagerScaledUp = g.Add(flow.Task{
 			Name:         "Ensuring that the gardener resource manager is scaled to 1",
```
Comment (plkokanov) [inline pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go]: Can we also use this PR to change the name of the task here to:
```suggestion
			Name:         "Ensuring that the gardener-resource-manager is scaled to 1",
```
To keep it in line with the name of other similar tasks for GRM.

**Review by plkokanov — CHANGES_REQUESTED** [review]
Thanks a lot for the PR. I just have one suggestion for the next step that scales GRM to one.

File: pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go [hunk 2]
```diff
@@ -172,10 +172,15 @@ func (r *Reconciler) runMigrateShootFlow(ctx context.Context, o *operation.Opera
 			Fn:           flow.TaskFn(botanist.WakeUpKubeAPIServer).DoIf(wakeupRequired),
 			Dependencies: flow.NewTaskIDs(deployETCD, scaleUpETCD, waitUntilControlPlaneReady),
 		})
+		deployGardenerResourceManager = g.Add(flow.Task{
+			Name:         "Deploying gardener-resource-manager (re-run bootstrap if needed)",
```
Comment (timebertt) [inline pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go]: Nit: I would rather put the motivation in a code comment above the task and reference https://github.com/gardener/gardener/issues/7606 instead of in the task name 😄 
```suggestion
			Name:         "Deploying gardener-resource-manager",
```

**Review by timebertt — COMMENTED** [review]
Thanks @Kumm-Kai! This looks great :)

**Review by timebertt — COMMENTED** [review]
Thanks!
/lgtm
/approve
