### PR TITLE
operator: set dashboard apiServerCaData from SNI TLS secret ca.crt

### LINKED ISSUE #14215: dashboard terminal kubeconfig misses apiServerCaData for SNI/private-CA endpoints
**How to categorize this issue?**
/area control-plane
/kind bug

**What happened**:
When the garden API server endpoint is exposed via SNI and signed by a private CA, dashboard terminal sessions fail with x509 unknown authority.

The terminal kubeconfig generated by `terminal-controller-manager` contains `caData: null` for the garden cluster, so clients cannot verify the API server certificate chain.

**What you expected to happen**:
The dashboard terminal kubeconfig should contain CA data for the garden API server also in SNI setups, so terminal connections succeed with private CAs.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure a garden setup with SNI endpoint and private-CA-signed server certificate.
2. Open the Gardener Dashboard and start a terminal session.
3. Observe terminal startup/login failure with x509 unknown authority.
4. Inspect terminal kubeconfig and see missing `caData` for garden API server.

**Why is this needed**:
Without CA propagation for SNI/private-CA setups, dashboard terminal access is broken.

**Implementation hint**:
In `deployGardenerDashboard`, resolve the SNI TLS secret (`.spec.virtualCluster.garden.kubernetesAPI.serverCertificate`) and set dashboard `apiServerCaData` from `ca.crt` when present.

### PR DESCRIPTION
**Pull request by amendezsap**
## What this PR does / why we need it
For SNI-based garden API server endpoints signed by private CAs, dashboard terminal sessions can fail with x509 unknown authority because terminal kubeconfig has no CA data.

This PR sets dashboard apiServerCaData from the SNI TLS secret ca.crt when available, so terminal-generated kubeconfigs include the CA bundle.

## Which issue(s) this PR fixes
Fixes #14215

## Special notes for your reviewer
- Non-SNI behavior remains unchanged.
- For SNI, this uses the configured server certificate secret (or wildcard fallback) and reads ca.crt if present.

### CODE REVIEW

**Comment by amendezsap** [comment]
/kind bug

Could a maintainer please run /ok-to-test for this PR? Thank you.

**Review by rfranzke — COMMENTED** [review]
/ok-to-test

/cc @petersutter @grolu

File: pkg/operator/controller/garden/garden/reconciler_reconcile.go [hunk 1]
```diff
@@ -1219,6 +1219,24 @@ func (r *Reconciler) deployGardenerDashboard(ctx context.Context, dashboard gard
 			return fmt.Errorf("secret %q not found", v1beta1constants.SecretNameCACluster)
 		}
 		dashboard.SetAPIServerCABundle(ptr.To(utils.EncodeBase64(caSecret.Data[secretsutils.DataKeyCertificateBundle])))
+	} else {
+		tlsSecretName := garden.Spec.VirtualCluster.Kubernetes.KubeAPIServer.SNI.SecretName
+		if tlsSecretName == nil {
+			tlsSecret, err := gardenerutils.GetRequiredGardenWildcardCertificate(ctx, r.RuntimeClientSet.Client(), r.GardenNamespace)
+			if err != nil {
+				return fmt.Errorf("failed getting SNI TLS secret for dashboard API server CA bundle: %w", err)
```
Comment (petersutter) [inline pkg/operator/controller/garden/garden/reconciler_reconcile.go:1224]:
```suggestion
				return fmt.Errorf("failed getting garden wildcard certificate for dashboard API server CA bundle: %w", err)
```

File: pkg/operator/controller/garden/garden/reconciler_reconcile.go [hunk 2]
```diff
@@ -1219,6 +1219,24 @@ func (r *Reconciler) deployGardenerDashboard(ctx context.Context, dashboard gard
 			return fmt.Errorf("secret %q not found", v1beta1constants.SecretNameCACluster)
 		}
 		dashboard.SetAPIServerCABundle(ptr.To(utils.EncodeBase64(caSecret.Data[secretsutils.DataKeyCertificateBundle])))
+	} else {
+		tlsSecretName := garden.Spec.VirtualCluster.Kubernetes.KubeAPIServer.SNI.SecretName
+		if tlsSecretName == nil {
```
Comment (petersutter) [inline pkg/operator/controller/garden/garden/reconciler_reconcile.go:1221]: In the fallback branch, `GetRequiredGardenWildcardCertificate(...)` already returns the `Secret` object, but the code then re-fetches the same `Secret` by name. That looks unnecessary and could be simplified by carrying the loaded Secret forward instead of only its name.

File: pkg/operator/controller/garden/garden/reconciler_reconcile.go [hunk 3]
```diff
@@ -1219,6 +1219,24 @@ func (r *Reconciler) deployGardenerDashboard(ctx context.Context, dashboard gard
...
+			tlsSecret, err := gardenerutils.GetRequiredGardenWildcardCertificate(ctx, r.RuntimeClientSet.Client(), r.GardenNamespace)
+			if err != nil {
```
Comment (petersutter) [inline pkg/operator/controller/garden/garden/reconciler_reconcile.go:1223]: do we want to fail here, or ignore and continue (same behavior as before)?
cc @rfranzke

Comment (rfranzke) [reply pkg/operator/controller/garden/garden/reconciler_reconcile.go:1223]: Do you have concerns regarding backward compatibility if we failed here as proposed?

Comment (petersutter) [reply pkg/operator/controller/garden/garden/reconciler_reconcile.go:1223]: If it is typically the case that the wildcard cert secret is there, then I guess it's acceptable. But I don't know whether that's actually the case

Comment (rfranzke) [reply pkg/operator/controller/garden/garden/reconciler_reconcile.go:1223]: Probably this ("wildcard secret exists") is rather the non-default/exceptional case.

Comment (amendezsap) [reply pkg/operator/controller/garden/garden/reconciler_reconcile.go:1223]: Good point — updated in bad32195f9. The lookup is now best-effort: if neither the explicit SNI secret nor a wildcard cert exists, it skips gracefully (same behavior as before this PR). No hard failure on the non-default path.

File: pkg/operator/controller/garden/garden/reconciler_reconcile.go (hunk 2 above)
Comment (amendezsap) [reply pkg/operator/controller/garden/garden/reconciler_reconcile.go:1221]: Fixed in bad32195f9 — the wildcard fallback now carries the Secret forward directly instead of re-fetching by name.

File: pkg/operator/controller/garden/garden/reconciler_reconcile.go (hunk 1 above)
Comment (amendezsap) [reply pkg/operator/controller/garden/garden/reconciler_reconcile.go:1224]: This error path no longer exists after bad32195f9 — the wildcard lookup is now best-effort (no error returned on failure).

File: pkg/operator/controller/garden/garden/reconciler_reconcile.go [hunk 4]
```diff
@@ -1219,6 +1219,29 @@ func (r *Reconciler) deployGardenerDashboard(ctx context.Context, dashboard gard
...
+	} else {
+		// Best-effort: try to populate CA bundle from SNI TLS secret for private CA setups.
+		// If neither an explicit secret name nor a wildcard cert is available, skip gracefully
+		// (same behavior as before this change).
+		var tlsSecret *corev1.Secret
+
+		if secretName := garden.Spec.VirtualCluster.Kubernetes.KubeAPIServer.SNI.SecretName; secretName != nil {
+			s := &corev1.Secret{}
+			if err := r.RuntimeClientSet.Client().Get(ctx, client.ObjectKey{Name: *secretName, Namespace: r.GardenNamespace}, s); err == nil {
+				tlsSecret = s
```
Comment (rfranzke) [inline pkg/operator/controller/garden/garden/reconciler_reconcile.go]:
```suggestion
			tlsSecret = &corev1.Secret{ObjectMeta: metav1.ObjectMeta{Name: *secretName, Namespace: r.GardenNamespace}}
			if err := r.RuntimeClientSet.Client().Get(ctx, client.ObjectKeyFromObject(tlsSecret), tlsSecret); err != nil {
				// return err
```

File: pkg/operator/controller/garden/garden/reconciler_reconcile.go [hunk 5]
```diff
@@ -1219,6 +1219,29 @@ func (r *Reconciler) deployGardenerDashboard(ctx context.Context, dashboard gard
...
+			}
+		} else {
```
Comment (rfranzke) [inline pkg/operator/controller/garden/garden/reconciler_reconcile.go]: I don't understand why the error is silently ignored when `sni.secretName` is set. This should mean that the operator wants this configured secret to be used for the SNI configuration. Why would we ignore this in case reading fails?

Comment (petersutter) [reply pkg/operator/controller/garden/garden/reconciler_reconcile.go]: I agree, this should return an error

**Review by petersutter — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
/approve
