### PR TITLE
Prevent code generation after new release

### LINKED ISSUE #5197: Code generation is required after release
**How to categorize this issue?**

/area quality delivery
/kind regression
/kind bug

**What happened**:
After https://github.com/gardener/gardener/pull/5115 , `make check-generate` after a release will fail because the provider-local ControllerDeployment/ControllerRegistration is not up-to-date (ref https://github.com/gardener/gardener/pull/5115#discussion_r771513464).

**What you expected to happen**:
`make check-generate` to do not fail after a successful release.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Environment**:

- Gardener version: v1.39.0-dev
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area delivery
/kind regression

**What this PR does / why we need it**:
This PR prevents running code generation after a new release by not specifying a version for the `Controller{Registration,Deployment}` of `provider-local`. Instead, `v0.0.0` and tag `latest` are now used (this is anyways overwritten when deployed in the local scenario).

**Which issue(s) this PR fixes**:
Fixes #5197

**Special notes for your reviewer**:
/invite @timebertt @ialidzhikov 

**Release note**:

```breaking dependency
The `generate-controller-registration.sh` script does no longer take a path to a VERSION file but instead the VERSION directly.
```

### CODE REVIEW

**Review by timebertt — DISMISSED** [review]
/lgtm

File: charts/gardener/provider-local/extension/doc.go [hunk 1]
```diff
@@ -12,7 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-//go:generate ../../../../hack/generate-controller-registration.sh provider-local . ../../../../VERSION ../../../../example/provider-local/base/controller-registration.yaml DNSProvider:local DNSRecord:local ControlPlane:local Infrastructure:local Network:local OperatingSystemConfig:local Worker:local
+//go:generate ../../../../hack/generate-controller-registration.sh provider-local . '' ../../../../example/provider-local/base/controller-registration.yaml DNSProvider:local DNSRecord:local ControlPlane:local Infrastructure:local Network:local OperatingSystemConfig:local Worker:local
```
Comment (ialidzhikov) [inline charts/gardener/provider-local/extension/doc.go]: In general this looks odd. And error-prone - if there is a typo in the VERSION file path it will wrongly assume wrong version/tag, right? 
Anyways `eu.gcr.io/gardener-project/gardener/extensions/provider-local` does not seem to be build and pushed by Gardener CI/CD. WDYT about modifying the `generate-controller-registration.sh` to accept a `<version>` instead of a `<version-file>`? This will be a small breaking change for extensions (they will have to pass the VERSION file content instead of the VERSION file path). But I think this approach looks much better and cleaner. We would hard-code the version here  to some stable one for this extension.

Comment (rfranzke) [reply charts/gardener/provider-local/extension/doc.go]: I have tried your suggestion, however, besides from the downside that it's a breaking change it doesn't seem to make things much better. When I pass `latest` as `VERSION` as you suggested then the `helm package` complains with "Error: Invalid Semantic Version". I could now add two new arguments (chart version and tag instead of version file) but then all "regular" users have to pass the `VERSION` file twice. Do we really want all this? I can do it if you insist, but I doubt that it's much better compared to what is currently proposed, especially w.r.t. the effort adapting all extensions.

Comment (ialidzhikov) [reply charts/gardener/provider-local/extension/doc.go]: Probably I am missing details but do we want to always pass `latest`? My idea was to just push for example tag `v0.1.0` and hard-code this version. Do you want it to be `latest` because of e2e tests with prow?

Comment (rfranzke) [reply charts/gardener/provider-local/extension/doc.go]: OK, you're right, we don't have to use `latest`. It basically doesn't matter what is used since it is always overwritten anyways. Hence, I've addressed your suggestion and used `v0.0.0` for now. OK?

**Review by ialidzhikov — COMMENTED** [review]
Can you add a release note that describes the breaking change in `generate-controller-registration.sh`?

**Comment by rfranzke** [comment]
done

**Review by ialidzhikov — APPROVED** [review]
/lgtm

File: charts/gardener/provider-local/extension/doc.go [hunk 2]
```diff
@@ -12,7 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-//go:generate ../../../../hack/generate-controller-registration.sh provider-local . ../../../../VERSION ../../../../example/provider-local/base/controller-registration.yaml DNSProvider:local DNSRecord:local ControlPlane:local Infrastructure:local Network:local OperatingSystemConfig:local Worker:local
+//go:generate ../../../../hack/generate-controller-registration.sh provider-local . v0.0.0 ../../../../example/provider-local/base/controller-registration.yaml DNSProvider:local DNSRecord:local ControlPlane:local Infrastructure:local Network:local OperatingSystemConfig:local Worker:local
```
Comment (timebertt) [inline charts/gardener/provider-local/extension/doc.go:15]: If I would now like to pass a version that is defined in the `VERSION` file, can I simply do `$(cat VERSION)`? I expect, that this doesn't work with `go:generate`

Comment (rfranzke) [reply charts/gardener/provider-local/extension/doc.go:15]: You can't, you would have to use `sh -c "..."` instead.

Comment (timebertt) [reply charts/gardener/provider-local/extension/doc.go:15]: Hmm, ok. Fine then

**Review by timebertt — APPROVED** [review]
/lgtm
