### PR TITLE
Fix reset shoots method by adding reset-retry

### LINKED ISSUE #355: Reset failed Shoots when a new Gardener version gets deployed
Today, Gardener does retrying an operation (create/reconcile/delete) on `Shoot` resources in case it keeps failing for a [given maximum duration](https://github.com/gardener/gardener/blob/master/example/20-componentconfig-gardener-controller-manager.yaml#L13). If the operation did still not succeed after the duration was exceeded, Gardener will set the `.status.lastOperation.state=Failed` and will never start the same operation on it again, unless:
* the `.spec` of the `Shoot` is changed
* another operation is triggered (e.g., `Reconcile` operation was failing but now `Delete` is triggered)
* the end-user [manually triggers](https://github.com/gardener/gardener/blob/master/hack/retry-shoot-operation) Gardener to retry the same operation.

This behaviour is problematic as it requires manual interaction to let Gardener restart the operation again.

The first thing we should do is to automatically reset the failed Shoots when a new Gardener version takes over (meaning setting `.status.lastOperation.state=Error` and `.status.retryCycleStartTime=<current-timestamp>`). Gardener already writes its own version into the `Shoot` status, so it's relatively easy to find these Shoots:

```yaml
...
status:
  gardener:
    id: 4a659427e1953356dcf30faf651b8f9554bc9676f12810102fe5d67b596d69e4
    name: gardener-controller-manager-74c484b898-9v648
    version: 0.10.1
```

The next step would be to have an automatic unfreeze also within the same Gardener version, e.g. with an exponential backoff or similar means (same problem like https://github.com/gardener/machine-controller-manager/issues/75). Anyway, this is just to mention it and should be discussed/handled separately.

### PR DESCRIPTION
**Pull request by zanetworker**
Reset the failed Shoots when a new Gardener version takes over by setting .status.lastOperation.state=Error and .status.retryCycleStartTime=<current-timestamp>.

Co-authored-by: Axel Christ axel.christ@sap.com

**What this PR does / why we need it**:
It allows failed shoots to reset when new Gardener version takes over. 
 
**Which issue(s) this PR fixes**:
Fixes #355 

**Special notes for your reviewer**:

**Release note**:
```noteworthy user
Failed Shoot operations are now retried when a different Gardener version takes over without requiring user interaction.
```

### CODE REVIEW

File: pkg/controller/shoot/shoot_control.go [hunk 1]
```diff
@@ -214,8 +215,18 @@ func (c *defaultControl) ReconcileShoot(shootObj *gardenv1beta1.Shoot, key strin
 	// We check whether the Shoot's last operation status field indicates that the last operation failed (i.e. the operation
 	// will not be retried unless the shoot generation changes).
 	if lastOperation != nil && lastOperation.State == gardenv1beta1.ShootLastOperationStateFailed && shoot.Generation == shoot.Status.ObservedGeneration {
-		shootLogger.Infof("Will not reconcile as the last operation has been set to '%s' and the generation has not changed since then.", gardenv1beta1.ShootLastOperationStateFailed)
-		return false, nil
+		if shoot.Status.Gardener.Version == version.Version {
+			shootLogger.Infof("Gardener version %q, actual version %q", shoot.Status.Gardener.Version, version.Version)
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_control.go]: Needs to be removed according to @Adracus

File: pkg/controller/shoot/shoot_control.go [hunk 2]
```diff
@@ -214,8 +215,18 @@ func (c *defaultControl) ReconcileShoot(shootObj *gardenv1beta1.Shoot, key strin
...
+			shootLogger.Infof("Will not reconcile as the last operation has been set to '%s' and the generation has not changed since then.", gardenv1beta1.ShootLastOperationStateFailed)
+			return false, nil
+		}
+
+		if updateErr := c.updateShootStatusResetRetry(operation, operationType); err != nil {
+			shootLogger.Errorf("Could not reset shoot status for retrying: %+v", updateErr)
+			return true, updateErr
+		}
+
+		shootLogger.Infof("Reset state for shoot %s", shoot.GetName())
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_control.go]: Can we have a more descriptive message here?

File: pkg/controller/shoot/shoot_control.go [hunk 3]
```diff
@@ -214,8 +215,18 @@ func (c *defaultControl) ReconcileShoot(shootObj *gardenv1beta1.Shoot, key strin
...
-		shootLogger.Infof("Will not reconcile as the last operation has been set to '%s' and the generation has not changed since then.", gardenv1beta1.ShootLastOperationStateFailed)
-		return false, nil
+		if shoot.Status.Gardener.Version == version.Version {
+			shootLogger.Infof("Gardener version %q, actual version %q", shoot.Status.Gardener.Version, version.Version)
+			shootLogger.Infof("Will not reconcile as the last operation has been set to '%s' and the generation has not changed since then.", gardenv1beta1.ShootLastOperationStateFailed)
+			return false, nil
+		}
+
+		if updateErr := c.updateShootStatusResetRetry(operation, operationType); err != nil {
+			shootLogger.Errorf("Could not reset shoot status for retrying: %+v", updateErr)
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_control.go]: Can we have a more descriptive message here?

**Review by rfranzke — CHANGES_REQUESTED** [review]

**Review by rfranzke — APPROVED** [review]
