### PR TITLE
[node-agent] Delete systemd unit files and drop-ins only if the unit has been created by node-agent

### LINKED ISSUE #10809: Gardener Node Agent deletes containerd drop-in directory
**How to categorize this issue?**

/area os
/kind bug

**What happened**:

Gardener-Node-Agent deletes containerd drop-in directory when drop-in gets removed from OSC and no more reference to systemd unit exists.

Details:

We deployed a shoot with an OSC containing the following extension units in the status field:

```yaml
...
status:
  extensionUnits:
  - dropIns:
    - content: |
        [Service]
        ExecStartPre=/opt/gardener/bin/containerd_cgroup_driver.sh
      name: 10-configure-cgroup-driver.conf
    filePaths:
    - /opt/gardener/bin/g_functions.sh
    - /opt/gardener/bin/containerd_cgroup_driver.sh
    name: containerd.service
  - dropIns:
    - content: |
        [Service]
        ExecStartPre=/opt/gardener/bin/kubelet_cgroup_driver.sh
      name: 10-configure-cgroup-driver.conf
    filePaths:
    - /opt/gardener/bin/g_functions.sh
    - /opt/gardener/bin/kubelet_cgroup_driver.sh
    name: kubelet.service
```

This results in the following files to be present:

```bash
ls /etc/systemd/system/containerd.service.d

10-configure-cgroup-driver.conf  
11-exec_config.conf 
30-env_config.conf  
override.conf
```
Only one of these files was delivered by the OSC.

The OSC status was updated by the operating system controller and the extensionUnits were removed from it; the containerd extension unit.

```yaml
...
status:
  extensionUnits:
  - dropIns:
    - content: |
        [Service]
        ExecStartPre=/opt/gardener/bin/kubelet_cgroup_driver.sh
      name: 10-configure-cgroup-driver.conf
    filePaths:
    - /opt/gardener/bin/g_functions.sh
    - /opt/gardener/bin/kubelet_cgroup_driver.sh
    name: kubelet.service
```

As the containerd.service was defined only once in the status field, the entire drop-in directory was deleted. 

Even tho we just intended to remove one systemd drop-in file, the code in [here](https://github.com/gardener/gardener/blob/539913d05582f88b80ea99cc53f2487aebaeeeab/pkg/nodeagent/controller/operatingsystemconfig/changes.go#L187-L193) identifies the unit as to be deleted. And the code [here](https://github.com/gardener/gardener/blob/539913d05582f88b80ea99cc53f2487aebaeeeab/pkg/nodeagent/controller/operatingsystemconfig/reconciler.go#L385-L387) deletes the entire systemd drop-in directory.

**What you expected to happen**:

Gardener node agent should not delete an entire drop-in directory with drop-ins it never created.

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

In the garden-linux extension a drop-in for containerd is deployed that should no longer be deployed going forward. As a result we are removing the entire unit from the `status.extensionUnits` as described above. 

For this bug to occur it is important that we deployed a drop-in for a systemd unit delivered by the OS vendor. This does not happen to systemd units delivered by gardener directly. 

**Environment**:

- Gardener version: 1.107
- Kubernetes version (use `kubectl version`): ---
- Cloud provider or hardware configuration: ---
- Others: ---

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area robustness
/kind bug

**What this PR does / why we need it**:
Currently `gardener-node-agent` always deletes a systemd unit file and the drop-in folder when the unit was deleted from OperatingSystemConfig.
While this correct for units which have been created by `gardener-node-agent`, it incorrectly deletes `*.service` file and the drop-in folder for units created by other parties (like default OS units). This can be the case if we use the unit to add additional drop-ins or in order to change the start command.

With this PR, unit file is deleted only if `Unit.Content` of the old unit is not nil. Otherwise, it keeps the unit file and does not stop the unit.
Additionally, GNA deletes only the drop-in files listed in previously applied OSC. The drop-in folder is only deleted if it is empty. 

**Which issue(s) this PR fixes**:
Fixes #10809 

**Special notes for your reviewer**:
/cc @rfranzke 

The PR supersedes #10918 (see https://github.com/gardener/gardener/pull/10918#issuecomment-2532333523).

**Release note**:

```bugfix developer
`gardener-node-agent` deletes unit files and drop-ins only if it created them previously.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Can you please augment the integration test with the two new cases? :)

File: pkg/nodeagent/controller/operatingsystemconfig/containerd.go [hunk 1]
```diff
@@ -23,38 +23,59 @@ import (
...
 	}
 
-	if err := r.ensureContainerdConfiguration(log, criConfig); err != nil {
-		return fmt.Errorf("failed to ensure containerd config: %w", err)
+	// Ingest the containerd drop-in into the OSC to prevent side effects when containerd.service is changed by extensions too.
+	ingestContainerdEnvironmentDropIn(osc)
+
+	oscRawContainerd, err := runtime.Encode(codec, osc)
+	if err != nil {
+		return nil, fmt.Errorf("unable to encode OSC after ingesting containerd drop-in: %w", err)
```
Comment (timuthy) [inline pkg/nodeagent/controller/operatingsystemconfig/containerd.go]: I vote for doing this in the `Reconcile` function, just before writing the OSC to disk. It makes the signature of this function cleaner and in the future other functions might adjust the passed OSC, as well.

File: pkg/nodeagent/controller/operatingsystemconfig/containerd.go [hunk 2]
```diff
@@ -23,38 +23,59 @@ import (
...
-	if err := r.ensureContainerdEnvironment(); err != nil {
-		return fmt.Errorf("failed to ensure containerd environment: %w", err)
+	if err := r.ensureContainerdConfiguration(log, osc.Spec.CRIConfig); err != nil {
+		return nil, fmt.Errorf("failed to ensure containerd config: %w", err)
 	}
 
-	if err := r.ensureContainerdConfiguration(log, criConfig); err != nil {
-		return fmt.Errorf("failed to ensure containerd config: %w", err)
+	// Ingest the containerd drop-in into the OSC to prevent side effects when containerd.service is changed by extensions too.
+	ingestContainerdEnvironmentDropIn(osc)
```
Comment (timuthy) [inline pkg/nodeagent/controller/operatingsystemconfig/containerd.go]:
```suggestion
	addContainerdEnvironmentDropIn(osc)
```

Nit: The terminology we usually use.

File: pkg/nodeagent/controller/operatingsystemconfig/containerd.go [hunk 3]
```diff
@@ -23,38 +23,59 @@ import (
...
 
-	if err := r.ensureContainerdEnvironment(); err != nil {
-		return fmt.Errorf("failed to ensure containerd environment: %w", err)
+	if err := r.ensureContainerdConfiguration(log, osc.Spec.CRIConfig); err != nil {
+		return nil, fmt.Errorf("failed to ensure containerd config: %w", err)
 	}
 
-	if err := r.ensureContainerdConfiguration(log, criConfig); err != nil {
-		return fmt.Errorf("failed to ensure containerd config: %w", err)
+	// Ingest the containerd drop-in into the OSC to prevent side effects when containerd.service is changed by extensions too.
```
Comment (timuthy) [inline pkg/nodeagent/controller/operatingsystemconfig/containerd.go]: For my own education: Has the issue already happened, is there an example?

**Review by timuthy — COMMENTED** [review]
A few nits and questions.

File: pkg/nodeagent/controller/operatingsystemconfig/containerd.go (hunk 3 above)
Comment (oliver-goetz) [reply pkg/nodeagent/controller/operatingsystemconfig/containerd.go]: The issue occurred in the gardenlinux extension, when they tried to remove their containerd drop-ins ([ref](https://github.com/gardener/gardener-extension-os-gardenlinux/pull/169/files#diff-6fd53d334ef152de6ff0a3b9f75eb47da46910d5806fd787d0f51a65ee77e301R137-R142)).

**Comment by oliver-goetz** [comment]
> Can you please augment the integration test with the two new cases? :)

Done 😄 
While I updated the integration tests, I also adapted the logic slightly. If we remove a unit which was existing before from OSC, the unit should be restarted in the end in order to apply the changes.
Otherwise, the unit would keep running using our drop-in in case we added and removed one.

File: pkg/nodeagent/controller/operatingsystemconfig/reconciler.go [hunk 4]
```diff
@@ -85,11 +99,17 @@ func (r *Reconciler) Reconcile(ctx context.Context, request reconcile.Request) (
...
 
-	osc, oscRaw, oscChecksum, err := extractOSCFromSecret(secret)
+	osc, oscChecksum, err := extractOSCFromSecret(secret)
 	if err != nil {
 		return reconcile.Result{}, fmt.Errorf("failed extracting OSC from secret: %w", err)
 	}
 
+	log.Info("Applying containerd configuration")
+	err = r.ReconcileContainerdConfig(ctx, log, osc)
+	if err != nil {
```
Comment (rfranzke) [inline pkg/nodeagent/controller/operatingsystemconfig/reconciler.go]: one line

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Review by timuthy — COMMENTED** [review]
/retest-required
/lgtm
/approve
