### PR TITLE
Remove stale extension resources

### LINKED ISSUE #1338: Extension resource not deleted from seed
**What happened**:
Removing an extension from the extensions section of the shoot spec did not cause the extension resource to be deleted from the shoot namespace in the seed cluster.
In turn the reconcile loop of the extension controller is still triggered and the extension stays installed.

**What you expected to happen**:
The matching extension resource is deleted from the shoot namespace in the seed cluster during the next reconcile loop after removing it from the shoot spec.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new shoot
1. add an entry to the `extensions` section
1. wait for reconcile
1. remove extension

**Anything else we need to know?**:

**Environment**:

- Gardener version: 0.26.7
- Kubernetes version (use `kubectl version`): 
seed: v1.15.2
shoot: v1.15.2
garden: v1.13.8
- Cloud provider or hardware configuration: dev-cluster, gcp-seed

### PR DESCRIPTION
**Pull request by timuthy**
**What this PR does / why we need it**:
This PR makes Gardener remove `Extension` resources in case they were removed from the `Shoot` or the `ControllerRegistration`.

**Which issue(s) this PR fixes**:
Fixes #1338

**Release note**:

```improvement operator
`Extensions` that are removed from the `Shoot` or through the `ControllerRegistration` are now correctly deleted.
```

### CODE REVIEW

File: pkg/controllermanager/controller/shoot/shoot_control_reconcile.go [hunk 1]
```diff
@@ -278,15 +278,25 @@ func (c *Controller) runReconcileShootFlow(o *operation.Operation, operationType
 			Fn:           flow.TaskFn(botanist.HibernateControlPlane).RetryUntilTimeout(defaultInterval, 2*time.Minute).DoIf(o.Shoot.HibernationEnabled),
 			Dependencies: flow.NewTaskIDs(initializeShootClients, deploySeedMonitoring, deploySeedLogging, deployClusterAutoscaler),
 		})
-		deployExtensionResource = g.Add(flow.Task{
+		deployExtensionResources = g.Add(flow.Task{
 			Name:         "Deploying extension resources",
-			Fn:           flow.TaskFn(botanist.DeployExtensionResources).RetryUntilTimeout(defaultInterval, defaultTimeout),
+			Fn:           flow.TaskFn(botanist.DeployExtensionResources).RetryUntilTimeout(defaultInterval, defaultTimeout).SkipIf(o.Shoot.HibernationEnabled),
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/shoot_control_reconcile.go]: Why is that only done if the shoot is not hibernated? I think we have to do it always in order to give extension controllers the chance to do whatever is necessary if the shoot gets hibernated?

File: pkg/controllermanager/controller/shoot/shoot_control_reconcile.go [hunk 2]
```diff
@@ -278,15 +278,25 @@ func (c *Controller) runReconcileShootFlow(o *operation.Operation, operationType
...
 			Dependencies: flow.NewTaskIDs(initializeShootClients),
 		})
 		_ = g.Add(flow.Task{
 			Name:         "Waiting until extension resources are ready",
-			Fn:           flow.TaskFn(botanist.WaitUntilExtensionResourcesReady),
-			Dependencies: flow.NewTaskIDs(deployExtensionResource),
+			Fn:           flow.TaskFn(botanist.WaitUntilExtensionResourcesReady).SkipIf(o.Shoot.HibernationEnabled),
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/shoot_control_reconcile.go]: Same comment as above.

File: pkg/controllermanager/controller/shoot/shoot_control_reconcile.go [hunk 3]
```diff
@@ -278,15 +278,25 @@ func (c *Controller) runReconcileShootFlow(o *operation.Operation, operationType
...
+			Dependencies: flow.NewTaskIDs(deployExtensionResources),
+		})
+		deleteStaleExtensionResources = g.Add(flow.Task{
+			Name:         "Delete stale extension resources",
+			Fn:           flow.TaskFn(botanist.DeleteStaleExtensionResources).RetryUntilTimeout(defaultInterval, defaultTimeout).SkipIf(o.Shoot.HibernationEnabled),
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/shoot_control_reconcile.go]: Again, why not always?

File: pkg/operation/botanist/extension.go [hunk 4]
```diff
@@ -66,6 +70,36 @@ func (b *Botanist) DeployExtensionResources(ctx context.Context) error {
...
+	for _, deployedExtension := range deployedExtensions.Items {
+		if !wantedExtensions.Has(deployedExtension.Spec.Type) {
+			fns = append(fns, func(ctx context.Context) error {
+				toDelete := &extensionsv1alpha1.Extension{
+					ObjectMeta: metav1.ObjectMeta{
+						Name:      deployedExtension.Name,
+						Namespace: deployedExtension.Namespace,
+					},
+				}
+				return b.K8sSeedClient.Client().Delete(ctx, toDelete, kubernetes.DefaultDeleteOptionFuncs...)
```
Comment (rfranzke) [inline pkg/operation/botanist/extension.go]:
```suggestion
				return client.IgnoreNotFound(b.K8sSeedClient.Client().Delete(ctx, toDelete, kubernetes.DefaultDeleteOptionFuncs...))
```

File: pkg/controllermanager/controller/shoot/shoot_control_reconcile.go (hunk 3 above)
Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_control_reconcile.go]: Agreed! But you agree with only waiting for the deletion if the shoot is not hibernated, right?

Comment (rfranzke) [reply pkg/controllermanager/controller/shoot/shoot_control_reconcile.go]: Hm, not really, why should we do that?

Comment (timuthy) [reply pkg/controllermanager/controller/shoot/shoot_control_reconcile.go]: Let's say the extension controller deploys manifests to the shoot (possibly via G-Resource-Manager), the created resources cannot be cleaned up while the shoot is hibernated. So the extension controller will not remove the `finalizer` but we'd continue waiting.

Comment (rfranzke) [reply pkg/controllermanager/controller/shoot/shoot_control_reconcile.go]: Good point, thanks.. yes, well, we might be safer with keeping it as you suggested. We don't know how the extension controllers are implemented and not waiting during hibernation would not block us in such case (while still the resource is marked for deletion correctly in the system).
However, if an extension is implemented in the way you mentioned it will also not be easily possible to entirely remove it from the system. There will most probably be always at least one hibernated shoot, and then the corresponding `Extension` remains in the system (which will block our `ControllerInstallation` controller).

**Review by rfranzke — APPROVED** [review]
/lgtm
