### PR TITLE
Restore `worker-pools-operatingsystemconfig-hashes` secret during restore phase of control plane migration 

### LINKED ISSUE #12957: CPM causes worker pools to migrate to latest Hash version
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

During CPM after enabling the `NewWorkerPoolHash` we noticed that CPM would cause node rollouts without apparent cause.

We noticed that the difference between the pre and post updated Worker resource in the seed, is the existence of the `nodeAgentSecretName`. This combined with the observed behaviour of node rollout points likely to [this codepath](https://github.com/gardener/gardener/blob/6ce05226695202caf1313617ccaaa5663ab4286a/extensions/pkg/controller/worker/machines.go#L100).

Gardenlet has to calculate when a pool can update the hash version based on previous versions of the hash. It does it in the following reconciliation code: https://github.com/gardener/gardener/blob/6ce05226695202caf1313617ccaaa5663ab4286a/pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L346

However, our hypothesis is that the secret containing previous is not transported during CPM which triggers the behavior of updating the hash to the latest version.

cc: @plkokanov 

**What you expected to happen**:

CPM to succeed without the need for unnecesary node rollouts

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
This PR fixes an issue that caused node rollouts during control plane migration when the `NewWorkerPoolHash` feature gate was enabled.
The issue occurred because the `worker-pools-operatingsystemconfig-hashes` secret was not getting restored from the `ShootState` during the restore phase of control plane migration.
More information can be found in the respective issue: #12957

As part of this PR, I have also enhanced the cpm e2e tests to check for restoration of the `worker-pools-operatingsystemconfig-hashes` secret.

**Which issue(s) this PR fixes**:
Fixes #12957

**Special notes for your reviewer**:
/invite @kon-angelo @rfranzke 

**Release note**:

```bugfix operator
The `worker-pools-operatingsystemconfig-hashes` secret is now restored in the `Shoot`'s control plane during the restore phase of control plane migration. This fixes an issue which caused node rollouts to happen during control plane migration when the `NewWorkerPoolHash` feature gate is enabled.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
/assign @shafeeqes @ary1992 
as CPM reviewers

**Review by shafeeqes — COMMENTED** [review]
/lgtm

File: pkg/gardenlet/operation/botanist/secrets_test.go [hunk 1]
```diff
@@ -455,10 +455,6 @@ var _ = Describe("Secrets", func() {
 								Labels: map[string]string{"managed-by": "secrets-manager", "manager-identity": "extension-foo"},
 								Data:   runtime.RawExtension{Raw: rawData("extension-foo-secret")},
 							},
-							{
-								Name: "secret-without-labels",
-								Type: "secret",
-							},
```
Comment (rfranzke) [inline pkg/gardenlet/operation/botanist/secrets_test.go:461]: Why did you remove this secret from the test? 👀

File: test/framework/shootmigrationtest.go [hunk 2]
```diff
@@ -324,17 +318,12 @@ func (t *ShootMigrationTest) CheckObjectsTimestamp(ctx context.Context, mrExclud
 	return nil
 }
 
-// MarkOSCSecret marks the operating system config pool hashes secret to verify that it is correctly migrated
+// MarkOSCSecret marks the operating system config pool hashes secret to verify that it is correctly migrated.
 func (t ShootMigrationTest) MarkOSCSecret(ctx context.Context) error {
```
Comment (rfranzke) [inline test/framework/shootmigrationtest.go]: This function looks pretty useless now. Can we remove it and directly call `shootmigration.MarkOSCSecret`?

Comment (plkokanov) [reply test/framework/shootmigrationtest.go]: Sure, I followed what was done for https://github.com/gardener/gardener/blob/b95e2776bbc0461a337673c7615d9b976c3a2bf4/test/framework/shootmigrationtest.go#L224-L228 
In https://github.com/gardener/gardener/pull/11500

I could remove both.

File: pkg/gardenlet/operation/botanist/secrets_test.go (hunk 1 above)
Comment (plkokanov) [reply pkg/gardenlet/operation/botanist/secrets_test.go:461]: Thanks for pointing it out. Indeed it would've been better to keep it and modify the test to expect it to be restored now 😅

Comment (rfranzke) [reply pkg/gardenlet/operation/botanist/secrets_test.go:461]: Then please revert :)

File: test/framework/shootmigrationtest.go (hunk 2 above)
Comment (rfranzke) [reply test/framework/shootmigrationtest.go]: Makes sense 👍🏻

File: pkg/gardenlet/operation/botanist/secrets_test.go (hunk 1 above)
Comment (plkokanov) [reply pkg/gardenlet/operation/botanist/secrets_test.go:461]: done in https://github.com/gardener/gardener/pull/13056/commits/015ab0b6eb1ecfb134d862d0b06e7c8515c07714

File: test/framework/shootmigrationtest.go (hunk 2 above)
Comment (plkokanov) [reply test/framework/shootmigrationtest.go]: done in https://github.com/gardener/gardener/pull/13056/commits/4dba372334afacbdf2a0da4cea2382caa39beddb

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
