### PR TITLE
Don't kill terraform pod on context cancelation

### LINKED ISSUE #8058: Terraform state may leak on interrupt
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

We see in the recent weeks a lot of issues related to Terraformer leaked state. The issues may come up either in creation where the terraform pod is complaining that some infrastructure resources already exist, or in deletion where some resources cannot be deleted due to dependencies with other existing resources. All these are symptoms of the same problem and come after the fact that the terraformer is not as resilient as we thought of.

Recap: if the terraformer pod is interrupted (pod deleted, preemption or otherwise) the terraform pod should propagate the termination signal from the terraformer -> to the terraform -> to the terraform provider. The terraform provider should then gracefully stop and the terraformer should update the state `ConfigMap` one last time.

As we investigated we saw cases where the TF provider is not as good as we thought at stopping "gracefully". See [this umbrella issue](https://github.com/hashicorp/terraform/issues/33358).

Due to the inherent behavior/bugs of the terraform providers, Gardener and  the extensions should try to preserve the terraform from getting deleted during execution as much as possible. 

**How to reproduce**:
One confirmed way to reproduce this behavior is the following: 

When the provider-extension pod is terminated, it will also delete all running terraformer pods. This was introduced in https://github.com/gardener/gardener/pull/4720 and can happen during provider-extension rollouts, due to VPA etc.

1. When extension Pod is terminating, it cancels the contexts for all its reconcilers.

2. The context for the waitForPod func is cancelled [Ref](https://github.com/gardener/gardener/blob/13d5158c55cc6b21ff1a24bb068c00dd223e8563/extensions/pkg/terraformer/terraformer.go#L241-L242)

3. Then the running terraformer Pod is deleted. [Ref](https://github.com/gardener/gardener/blob/13d5158c55cc6b21ff1a24bb068c00dd223e8563/extensions/pkg/terraformer/terraformer.go#L266-L278)

However we may update the issue with additional findings

- Gardener version: v1.71.x
- Cloud provider or hardware configuration: gcp, aws, azure, openstack

CC: @ialidzhikov @Kostov6 @dimitar-kostadinov

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
Revert partially the behavior introduced with https://github.com/gardener/gardener/pull/4720 and only delete the TF pod when the context was in deadline exceeded. If the current context is cancelled this indicates likely that the parent context was deleted but still we should allow the Terraformer pod to continue its execution uninterrupted. 

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/8058

**Special notes for your reviewer**:
The terraformer library will now skip deletion of the Terraformer pod when the request context has been canceled. 
Previously, if the parent context of a reconciliation was cancelled (e.g. a provider-extension pod restart) during a command execution via Gardener's Terraformer interface, the library would attempt to delete the active Terraformer pod. However, not all Terraform providers handle abrupt terminations gracefully. This change aims to prevent inconsistencies in Terraform state by attempting to allow uninterrupted execution of healthy Terraformer pods. Subsequent calls to the Terraform interface should be able to proceed either via adopting currently running pods or by cleaning up already finished pods.

**Release note**:

```bugfix operator
The `terraformer` library will now skip deletion of the Terraformer pod when the request context has been canceled. This change aims to prevent inconsistencies in Terraform state by attempting to allow uninterrupted execution of healthy Terraformer pods.
```

### CODE REVIEW

File: extensions/pkg/terraformer/terraformer.go [hunk 1]
```diff
@@ -263,18 +263,25 @@ func (t *terraformer) execute(ctx context.Context, command string) error {
...
-		if ctx.Err() != nil {
+		switch {
+		case errors.Is(ctx.Err(), context.Canceled):
+			// If the context error is Canceled, the parent context has been canceled. Because the Terraform is fairly unstable
+			// and interruptions may cause it to not properly store the state, we will allow it to continue. The next reconciliation will
+			// adopt the running pod.
+			podLogger.Info("Skipping Terraformer pod deletion because context was cancelled")
+		case errors.Is(ctx.Err(), context.DeadlineExceeded):
+			// If the context error is deadline exceeded, create a new context for deleting the pod since attempting to use the
+			// original context will fail. The context might get cancelled for example by the owner check watchdog and the pod
```
Comment (rfranzke) [inline extensions/pkg/terraformer/terraformer.go]: We should no longer have any owner check watchdogs, do we?

Comment (ialidzhikov) [reply extensions/pkg/terraformer/terraformer.go]: You are right. Owner check + owner check watchdog has been removed as part of bad case control plane migration removal - ref https://github.com/gardener/gardener/issues/6302.

**Comment by rfranzke** [comment]
@kon-angelo Can you please provide a more meaningful release note? As an operator without much knowledge about the Gardener internals, I would not be able to understand it. What is the relevant effect/bugfix?

File: extensions/pkg/terraformer/terraformer.go [hunk 2]
```diff
@@ -263,18 +263,24 @@ func (t *terraformer) execute(ctx context.Context, command string) error {
...
-		// If the context error is non-nil (cancelled or deadline exceeded),
-		// create a new context for deleting the pod since attempting to use the original context will fail.
-		// The context might get cancelled for example by the owner check watchdog and the pod should be
-		// deleted to prevent the terraform script from running after the context was cancelled.
-		if ctx.Err() != nil {
+		switch {
+		case errors.Is(ctx.Err(), context.Canceled):
+			// If the context error is Canceled, the parent context has been canceled. Because the Terraform is fairly unstable
+			// and interruptions may cause it to not properly store the state, we will allow it to continue. The next reconciliation will
+			// adopt the running pod.
```
Comment (ialidzhikov) [inline extensions/pkg/terraformer/terraformer.go]: We can link the following umbrella upstream issue and just saying that terraform leaks state does not mean anything.

```suggestion
			// If the context error is Canceled, the parent context has been canceled. Because the Terraform is fairly unstable
			// and interruptions may cause it to not properly store the state (ref https://github.com/hashicorp/terraform/issues/33358),
			// we will allow it to continue. The next reconciliation will adopt the running pod.
```

**Review by ialidzhikov — COMMENTED** [review]
Minor suggestion, otherwise lgtm.

**Review by ialidzhikov — APPROVED** [review]
/lgtm
