### PR TITLE
kind: setup lo addresses with docker

### LINKED ISSUE #13012: Unable to setup local kind-cluster using docker powered by lima VM
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
Starting a local kind cluster with `make kind-up` fails if running docker daemon on a guest VM like with [lima](https://github.com/lima-vm/lima), because the loopback addresses are attached to the host's loopback device instead of the guest loopback where the kind containers are created.

```sh
$ make kind-up
./hack/kind-up.sh \
                --cluster-name gardener-local \
                --path-kubeconfig /Users/hoehll/workspace/Github/gardener/gardener/example/provider-local/seed-kind/base/kubeconfig \
                --path-cluster-values /Users/hoehll/workspace/Github/gardener/gardener/example/gardener-local/kind/local/values.yaml \
                --with-lpp-resize-support false \

Checking loopback device lo0...
Adding IP address 172.18.255.1 to lo0...
Executing: /usr/bin/sudo /sbin/ifconfig lo0 add 172.18.255.1

Adding IP address 172.18.255.22 to lo0...
Executing: /usr/bin/sudo /sbin/ifconfig lo0 add 172.18.255.22

Setting up loopback device lo0 completed.
Creating cluster "gardener-local" ...
 ✓ Ensuring node image (kindest/node:v1.33.4) 🖼
 ✗ Preparing nodes 📦
Deleted nodes: ["gardener-local-control-plane"]
ERROR: failed to create cluster: 
command "docker run --name gardener-local-control-plane --hostname gardener-local-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --detach --tty --label io.x-k8s.kind.cluster=gardener-local --net kind --restart=on-failure:1 --init=false --cgroupns=private 
--volume=/Users/hoehll/workspace/Github/gardener/gardener/example/gardener-local/kube-apiserver:/etc/gardener-local/kube-apiserver:ro --volume=/Users/hoehll/workspace/Github/gardener/gardener/example/gardener-local/controlplane:/etc/gardener/controlplane:ro --volume=/Users/hoehll/workspace/Github/gardener/gardener/dev/local-backupbuckets:/etc/gardener/local-backupbuckets --volume=/Users/hoehll/workspace/Github/gardener/gardener/dev/local-registry:/etc/gardener/local-registry 
--publish=0.0.0.0:32379:32379/TCP --publish=172.18.255.1:443:30443/TCP --publish=172.18.255.1:8132:32132/TCP --publish=172.18.255.22:8022:30022/TCP --publish=0.0.0.0:5001:5001/TCP --publish=172.18.255.1:5353:30053/TCP --publish=127.0.0.1:52073:6443/TCP -e KUBECONFIG=/etc/kubernetes/admin.conf kindest/node:v1.33.4@sha256:25a6018e48dfcaee478f4a59af81157a437f15e6e140bf103f85a2e7cd0cbbf2" 
failed with error: exit status 125
Command Output: 0cb62b3667b756665785214b4b41117d6c8f250f2f40131dfb8910b57e079007
docker: Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint gardener-local-control-plane (98b89a2be03434ed12aa1b948ab74865bb58bca37942f60dee19b7b7c6c8f3a9):
failed to bind host port for 172.18.255.22:8022:172.18.0.2:30022/tcp: cannot assign requested address

Run 'docker run --help' for more information
make: *** [kind-up] Error 1
```

**What you expected to happen**:
Kind cluster is able to bind to local addresses and start the nodes.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup docker using a lima VM -> https://github.com/lima-vm/lima/blob/master/templates/docker-rootful.yaml
2. Run `make kind-up`

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others: MacOS

### PR DESCRIPTION
**Pull request by hown3d**
**How to categorize this PR?**

/area dev-productivity
/kind technical-debt

**What this PR does / why we need it**:
Setups kind loopback devices with a docker container running on the host network.
If a developer uses a virtual-machine like lima for their docker setup, the local ip command won't add the addresses to the correct lo interface where kind expects them to be.
Using a docker container will always add them to the loopback device where the actual kind containers hosting the control-plane will live.

**Which issue(s) this PR fixes**:
Fixes #13012

**Special notes for your reviewer**:
/cc @oliver-goetz @plkokanov

### CODE REVIEW

**Review by LucaBernstein — COMMENTED** [review]
Nice, thank you! I really like the idea because it makes the setup work more generically. 🌟 
/ok-to-test

File: hack/kind-setup-loopback-devices.sh [hunk 1]
```diff
@@ -10,10 +10,9 @@ MULTI_ZONAL="false"
 CLUSTER_NAME=""
 IPFAMILY="ipv4"
 
-SUDO=""
-if [[ "$(id -u)" != "0" ]]; then
-  SUDO="sudo "
-fi
+ip() {
+  docker run --rm --cap-add NET_ADMIN --network=host alpine ip $@
```
Comment (ScheererJ) [inline hack/kind-setup-loopback-devices.sh]: Could you please explain how this is supposed to work? The loopback device in the container and on the host are not the same thing and adding an IP address in the container does not achieve the same result as before as far as I can tell.
You might have found a solution for other container runtimes, but for me it looks like your are breaking docker desktop, which is no option.

Comment (hown3d) [reply hack/kind-setup-loopback-devices.sh]: When running with network=host the docker container is using the devices from the host network namespace, therefore this is the same loopback device as the hosts one.
I don't use Docker Desktop, can we check together why this is not an option for it?

Comment (ScheererJ) [reply hack/kind-setup-loopback-devices.sh]: I use docker desktop on mac.

```
% docker run --rm --cap-add NET_ADMIN --network=host alpine ip a show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
% docker run --rm --cap-add NET_ADMIN --network=host alpine ip a add 192.168.254.0 dev lo
% docker run --rm --cap-add NET_ADMIN --network=host alpine ip a show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 192.168.254.0/32 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
% ip show dev lo
Object "show" is unknown, try "ip help".
% ip a show dev lo0
1: lo0: <UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384 status UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8
    inet6 ::1/128
    inet6 fe80::1/64
    inet 172.18.255.1/16
    inet 172.18.255.22/16
```

On linux, running something in a host network container may yield the same result as running it on the host, but on anything non-linux (windows/mac) where usually a virtual machine is used, `docker run --rm --cap-add NET_ADMIN --network=host alpine ip ...` and `sudo ip ...` are not the same thing.

I do not think we cannot change it, but we should change it in a way that does not break the local setup for docker desktop users on mac because there is a considerable amount of people working with such a setup.

/hold

Comment (ScheererJ) [reply hack/kind-setup-loopback-devices.sh]: Feel free to reach out if you want to discuss this in a call.

Comment (ScheererJ) [reply hack/kind-setup-loopback-devices.sh]: Discussed next steps in call on October 7th. Waiting for corresponding update.

Comment (hown3d) [reply hack/kind-setup-loopback-devices.sh]: I updated the script to check the container host with the docker container as well as the host.
Also added a comment describing the scenario.

File: hack/kind-setup-loopback-devices.sh [hunk 2]
```diff
@@ -75,14 +75,37 @@ if ! command -v ip &>/dev/null; then
...
+
+	for address in "${LOOPBACK_IP_ADDRESSES[@]}"; do
+		if ${ip_func} address show dev ${LOOPBACK_DEVICE} | grep -q $address/; then
+			echo "IP address $address already assigned to ${LOOPBACK_DEVICE}."
+		else
+			echo "Adding IP address $address to ${LOOPBACK_DEVICE}..."
+			if [[ ${ip_func} == "ip" ]]; then
+				ip_func=${SUDO}${ip_func}
+			fi
+			${ip_func} address add "$address" dev "${LOOPBACK_DEVICE}"
```
Comment (ScheererJ) [inline hack/kind-setup-loopback-devices.sh]: If the `for` loop is executed multiple times and `ip_func` is `ip`, the second iteration will use `${SUDO}ip`, which is probably not required/a side effect, i.e. the command in the first `if` block will run with `sudo` starting with the second loop iteration.

Let's fix this.

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve

**Review by LucaBernstein — COMMENTED** [review]
/lgtm
/unhold
