### PR TITLE
fix: overlap validation of shoot defaults with seed networks

### LINKED ISSUE #13335: Remove validation for ShootDefaults network disjointedness with SeedNetwork
**How to categorize this issue?**

/area networking
/kind enhancement

**What would you like to be added**:
Remove [validation](https://github.com/gardener/gardener/blob/2ae613cbb25dcebf106a52b2ea54f2a620091e33/pkg/apis/core/validation/seed.go#L305-L326) for ShootDefaults network disjointedness with SeedNetwork in case of IPv4 network.

**Why is this needed**:
Shoot network and Seed network IP ranges disjointedness restriction was removed in  https://github.com/gardener/gardener/pull/12204.
We should now allow overlapping `ShootDefaults` network with Seed network ranges.

### PR DESCRIPTION
**Pull request by domdom82**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:

- With overlapping CIDRs allowed for both HA and non-HA shoots we can also remove the validation for shoot defaults in seed networks.
- Also added tests to make sure IPv6 ranges are still checked for overlap
- Also added check for all reserved ranges

**Which issue(s) this PR fixes**:
Fixes #13335 

**Release note**:

```other operator
Removed obsolete validation for `shootDefaults` network disjointedness with `SeedNetworks`.
```

### CODE REVIEW

File: pkg/apis/core/validation/seed.go [hunk 1]
```diff
@@ -284,46 +284,90 @@ func validateSeedNetworks(seedNetworks core.SeedNetworks, fldPath *field.Path, i
...
-		networks                 []cidrvalidation.CIDR
-		reservedSeedServiceRange = cidrvalidation.NewCIDR(v1beta1constants.ReservedKubeApiServerMappingRange, field.NewPath(""))
+		primaryIPFamily                        = helper.DeterminePrimaryIPFamily(seedNetworks.IPFamilies)
+		allCIDRs                               []cidrvalidation.CIDR
+		seedCIDRs                              []cidrvalidation.CIDR
+		shootDefaultsV4                        []cidrvalidation.CIDR
+		shootDefaultsV6                        []cidrvalidation.CIDR
+		vpnRangeV6                             = cidrvalidation.NewCIDR(v1beta1constants.DefaultVPNRangeV6, field.NewPath(""))
+		reservedKubeApiServerMappingRange      = cidrvalidation.NewCIDR(v1beta1constants.ReservedKubeApiServerMappingRange, field.NewPath(""))
+		reservedSeedPodNetworkMappedRange      = cidrvalidation.NewCIDR(v1beta1constants.ReservedSeedPodNetworkMappedRange, field.NewPath(""))
```
Comment (timebertt) [inline pkg/apis/core/validation/seed.go]: It seems like some of these validations are already implemented in https://github.com/gardener/gardener/blob/bd26073d53dd985aeb88bdd0ec03a5f87e7d06f8/pkg/utils/validation/cidr/disjoint.go (used by gardener-scheduler).
Is there a way to reuse the validation code to prevent mismatches in multiple implementations?

Comment (domdom82) [reply pkg/apis/core/validation/seed.go]: the code in disjoint.go is very specific for shoots, not shootDefaults in Seeds. 
but I see your point, I'll try to refactor so that it all fits together.

Comment (domdom82) [reply pkg/apis/core/validation/seed.go]: @timebertt I think it should work now. I've generalised the reserved ranges check so that it works for both seeds and shoots now. So the code for that is now in one place only.

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve
