### PR TITLE
Force recreation of Kubernetes HTTP client

### LINKED ISSUE #288: initializeShootClient stuck in Timeout Error in the Cluster Creation Process
Currently we are experiencing an issue when creating Shoots on GCP. The creation of a cluster gets stuck with the following error:

```
Failed to reconcile Shoot cluster state: Errors occurred during flow execution: '(*Operation).InitializeShootClients' returned 'Get https://api.DNS-NAME-OF-MY-SHOOT/version?timeout=32s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)'
``` 

Eventually those failed clusters become healthy again after a 1-3 hour waiting period. it looks like there is a dead but established connection open against the Shoot API-server.

I found those issues on github which might be related:
https://github.com/giantswarm/kvm-operator/pull/484#issuecomment-395683790

> Problem is that k8sclient multiplexes multiple http connections thru one TCP connection and when TCP connection dead (but in established state), there is no way to force use new TCP connection.

This probably falls back to:
https://github.com/kubernetes/kubernetes/issues/133556
https://github.com/kubernetes/client-go/issues/374

Another possible solution (pretty ugly though) would be to fiddle around with the default timeout of the `RESTClient` [0]

[0] https://github.com/kubernetes/client-go/blob/master/discovery/discovery_client.go#L49

### PR DESCRIPTION
**Pull request by afritzler**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #288

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Force recreation of Kubernetes HTTP client
```

### CODE REVIEW

File: pkg/client/kubernetes/client.go [hunk 1]
```diff
@@ -57,6 +76,7 @@ func NewClientFromBytes(kubeconfig []byte) (Client, error) {
 	if err != nil {
 		return nil, err
 	}
+	config.Transport = newTransport()
```
Comment (adracus) [inline pkg/client/kubernetes/client.go]: Just saw it: Instead of assigning `config.Transport` here, we should assign it in `newClientSet` - this is our most 'low-level' method before creating a `kubernetes.Interface`

Comment (afritzler) [reply pkg/client/kubernetes/client.go]: so you mean something like that 
```
config.Transport = newTransport()
clientset, err := kubernetes.NewForConfig(config)
```
in the `newClientSet` method?

Comment (rfranzke) [reply pkg/client/kubernetes/client.go]: Exactly!

**Comment by rfranzke** [comment]
LGTM after squashing.

**Comment by afritzler** [comment]
Squashed!

**Review by rfranzke — APPROVED** [review]
