### PR TITLE
Vendor github.com/gardener/controller-runtime@v0.6.3-gardener.1

### LINKED ISSUE #2675: Dynamic RESTMapper limited
**How to categorize this issue?**

/area control-plane
/area scalability
/kind bug
/priority normal

**What happened**:
If the `APIServerSNI` feature gate is disabled and Istio is not installed on the Seed, it can happen, that under high load, the Shoot reconciliation will fail, because the dynamic REST mapper of the Seed client is rate limited:
```
could not delete object of kind \“EnvoyFilter\” \“istio-ingress/shoot--foo--bar\“: too many API calls to the RESTMapper within a timeframe, could not delete object of kind \“Gateway\” \“shoot--foo--bar/kube-apiserver\“: too many API calls to the RESTMapper within a timeframe, could not delete object of kind \“VirtualService\” \“shoot--foo--bar/kube-apiserver\“: too many API calls to the RESTMapper within a timeframe
```

The problem is, that the dynamic RESTMapper returns a different error than the expected `NoKindMatchError` in that case (ref https://github.com/kubernetes-sigs/controller-runtime/issues/1120) and therefore, the `TolerateErrorFunc` can't catch it:
https://github.com/gardener/gardener/blob/514f00cbd32cc3022032376f48ebaf0f3ad0ed3e/pkg/operation/botanist/controlplane/kube_apiserver_sni.go#L76-L85

The same problem can hit us in the seed bootstrap here:
https://github.com/gardener/gardener/blob/514f00cbd32cc3022032376f48ebaf0f3ad0ed3e/pkg/operation/seed/istio/proxy_protocol.go#L50-L58
e.g:
```
seed is not yet ready: condition \"Bootstrapped\" has invalid status False (expected True) due to BootstrappingFailed: failed to delete manifests: 1 error occurred: could not delete object of kind \"VirtualService\" \"istio-ingress/proxy-protocol-blackhole\": too many API calls to the RESTMapper within a timeframe"
```

**What you expected to happen**:
The Shoot reconciliation/Seed bootstrapping should not block in that case and should just ignore the error, because it means, that the Istio stuff is anyways not installed.

**How to reproduce it (as minimally and precisely as possible)**:
Simultaneously create hundreds of Shoots? 😁 🤔 

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.8.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### LINKED ISSUE #2747: Gardenlet times out talking to the Seed API server
**How to categorize this issue?**

/area quality performance robustness scalability
/kind bug
/priority normal

**What happened**:
Over the past few weeks we have observed, that the gardenlet is often timing out talking to the Seed API server during Shoot reconciliation but also while renewing the leader lease, ending in quite frequent logs including `context deadline exceeded`.
We have seen this on two of our shooted Seeds (Azure in the US, Control plane running in the EU), which have a quite dynamic load (many Shoots creating/deleting in parallel).

The problematic steps in the Shoot reconciliation/deletion that fail are mostly those, that use the `defaultTimeout` of 30s and touch a lot of resources (for example `DeleteSeedMonitoring`).

**What you expected to happen**:
The gardenlet should be able to cope with many Shoots being reconciled in parallel.

**How to reproduce it (as minimally and precisely as possible)**:
What actually limits the effect of this issue is to set the `shoot.concurrentSyncs` value of the gardenlet configuration to a low value (e.g. 20). With this, the `context deadline exceeded` errors cease to pop up in the logs.

**Anything else we need to know?**:

**Environment**:

- Gardener version: >= v1.7.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: azure (?)
- Others:

/cc @timuthy @dguendisch @zanetworker @rfranzke

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area scalability robustness
/kind bug
/priority normal

**What this PR does / why we need it**:
With this PR we vendor a forked `sigs.k8s.io/controller-runtime` repository which includes the not-yet-merged improvement from @timebertt (https://github.com/kubernetes-sigs/controller-runtime/pull/1151).

We also pass a custom rate limiter that allows one request every 5s as suggested in https://github.com/gardener/gardener/issues/2747#issuecomment-688064801.

**Which issue(s) this PR fixes**:
Fixes #2747
Fixes #2675

/invite @timebertt 
/assign @timebertt 

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

File: pkg/client/kubernetes/runtime_client.go [hunk 1]
```diff
@@ -93,7 +94,11 @@ func newRuntimeClientWithCache(config *rest.Config, options client.Options, cach
 func setClientOptionsDefaults(config *rest.Config, options *client.Options) error {
 	if options.Mapper == nil {
 		// default the client's REST mapper to a dynamic REST mapper (automatically rediscovers resources on NoMatchErrors)
-		mapper, err := apiutil.NewDynamicRESTMapper(config, apiutil.WithLazyDiscovery)
+		mapper, err := apiutil.NewDynamicRESTMapper(
+			config,
+			apiutil.WithLazyDiscovery,
+			apiutil.WithLimiter(rate.NewLimiter(0.2, 1)), // one request every 5s
```
Comment (timebertt) [inline pkg/client/kubernetes/runtime_client.go]:
```suggestion
			apiutil.WithLimiter(rate.NewLimiter(rate.Every(5*time.Second), 1)),
```

**Review by timebertt — COMMENTED** [review]
Thanks for taking care!
This will also fix #2675.

Only one nit suggestion, otherwise /lgtm.

**Review by timebertt — APPROVED** [review]
Thanks!
/lgtm
