### PR TITLE
Enhance error msg when trying to change `.spec.seedName` by patching a shoot

### LINKED ISSUE #9186: Unexpected error during PUT: spec.seedName cannot be changed by patching the shoot
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
Gardener API server rejects idempotent PUT shoot requests with error
```
Error from server (Forbidden): error when replacing "/tmp/shoot.yaml": shoots.core.gardener.cloud "<redacted>" is forbidden: spec.seedName cannot be changed by patching the shoot, please use the shoots/binding subresource
```

**What you expected to happen**:

This should of course work.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a shoot (e.g. `kubectl create`).
2. Do a put (e.g. `kubectl replace`) using the same descriptor used for creation.

**Anything else we need to know?**:

Nothing

**Environment**:

- Gardener version: 1.73.0
- Kubernetes version (use `kubectl version`): irrelevant (1.27.6, 1.28.4 in our case)
- Cloud provider or hardware configuration: AWS
- Others: nothing

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area usability
/kind enhancement

**What this PR does / why we need it**:
This PR enhances the validation error which is shown when trying to change a shoot's `.spec.seedName` without using the `shoots/binding` subresource. The new error message will also display the old and new `.spec.seedName`s to show that a change attempt was actually made. If one of the `.spec.seedName` fields are `nil` it will print 'nil' in the error message. You can check the following examples:
```
Error from server (Forbidden): error when replacing "example/provider-local/shoot.yaml": shoots.core.gardener.cloud "local" is forbidden: spec.seedName 'local' cannot be changed to 'nil' by patching the shoot, please use the shoots/binding subresource
```

```
Error from server (Forbidden): error when replacing "example/provider-local/shoot.yaml": shoots.core.gardener.cloud "local" is forbidden: spec.seedName 'local' cannot be changed to 'new-local' by patching the shoot, please use the shoots/binding subresource
```

**Which issue(s) this PR fixes**:
Fixes #9186 

**Special notes for your reviewer**:

**Release note**:

```other user
The validation error shown when a user tries to change the `.spec.seedName` field of a Shoot will now also display the old and new values to better indicate that a change was attempted.
```

### CODE REVIEW

File: plugin/pkg/shoot/validator/admission.go [hunk 1]
```diff
@@ -40,6 +40,7 @@ import (
 	"k8s.io/apiserver/pkg/authorization/authorizer"
 	kubeinformers "k8s.io/client-go/informers"
 	kubecorev1listers "k8s.io/client-go/listers/core/v1"
+	"k8s.io/utils/pointer"
```
Comment (rfranzke) [inline plugin/pkg/shoot/validator/admission.go]: Use `ptr` package only?

Comment (plkokanov) [reply plugin/pkg/shoot/validator/admission.go]: Ahh right, forgot for a second that `pointer` functions are deprecated and we removed them. Let me see if I can adapt this.

Comment (plkokanov) [reply plugin/pkg/shoot/validator/admission.go]: Done

File: plugin/pkg/shoot/validator/admission_test.go [hunk 2]
```diff
@@ -761,7 +761,7 @@ var _ = Describe("validator", func() {
 				err := admissionHandler.Admit(ctx, attrs, nil)
 
 				Expect(err).To(BeForbiddenError())
-				Expect(err).To(MatchError(ContainSubstring("spec.seedName cannot be changed by patching the shoot, please use the shoots/binding subresource")))
+				Expect(err).To(MatchError(ContainSubstring("spec.seedName 'seed' cannot be changed to 'nil' by patching the shoot, please use the shoots/binding subresource")))
```
Comment (shafeeqes) [inline plugin/pkg/shoot/validator/admission_test.go]: seedName cannot be set to nil once set, right? So maybe we print that it cannot be nil at all, even with the binding resource.

Comment (plkokanov) [reply plugin/pkg/shoot/validator/admission_test.go]: I was wondering about that as well, but decided to leave that error for the `binding` subresource validation so as to keep the current "behaviour".

Otherwise I could potentially print two errors depending on whether the new `.spec.seedName` is nil or not:

When it is not nil:
```
spec.seedName 'seed-name' cannot be changed to 'new-seed' by patching the shoot, please use the shoots/binding subresource
```
When it is nil:
```
spec.seedName is already set to `seed-name` and cannot be changed to 'nil'
```

Comment (shafeeqes) [reply plugin/pkg/shoot/validator/admission_test.go]: I would prefer the two error approach.
In binding, we print similar error for the nil case but a different message, you could use this error there too.

**Review by ScheererJ — COMMENTED** [review]
/approve

File: plugin/pkg/shoot/validator/admission_test.go (hunk 2 above)
Comment (plkokanov) [reply plugin/pkg/shoot/validator/admission_test.go]: Done

**Review by shafeeqes — APPROVED** [review]
Thanks!
/lgtm
