### PR TITLE
Prometheus alerts for when `etcd-druid`'s snapshot compaction jobs fail above a certain rate

### LINKED ISSUE #603: [Feature] Alerts for the compaction job metrics
**Feature (What you would like to be added):**
We are exposing metrics for compaction job in ETCD druid by #569 . Now we need to whitelist the metrics in g/g  and raise correct alerts based on the metrics. We have decided to raise alerts when `job_duration_seconds` and `jobs_total` with failed labels cross certain thresholds.
**Motivation (Why is this needed?):**

**Approach/Hint to the implement solution (optional):**
Threshold for `jobs_total` with failed label in a seed : 10% of aggregated `jobs_total` (This alert would be raised per seed)
Threshold for `jobs_total` with failed label in a shoot:  10% of `jobs_total`(This alert would be raised per shoot)

To raise the alert at seed level,  [Aggregate prometheus](https://github.com/gardener/gardener/tree/master/docs/monitoring#aggregate-prometheus) can be used. The metrics `jobs_total` with failed label is scraped by [cache prometheus](https://github.com/gardener/gardener/tree/master/docs/monitoring#prometheus) from etcd-druid. Aggregate prometheus can aggregate metrics `jobs_total` from cache prometheus. Seed level alerts can be raised on this aggregated metrics from aggregated prometheus. 

To raise the alert at shoot level, alerts can be raised in control plane prometheus. Control plane prometheus already federate shoot specific `jobs_total` from cache prometheus. So, to raise the alert for `jobs_total` at shoot level, we need to add an alert for `jobs_total` in  [here](https://github.com/gardener/gardener/blob/72ce85574d37e3a8ffcf2b082aca643f87059ed8/pkg/component/etcd/monitoring.go#L94)

Another idea is that we aggregate the alert data that is already raised on shoot control plane prometheus. Alerts from the shoot control plane prometheus are passed to aggregate prometheus in garden namespace. These are just alert data. We can aggregate these alert data streaming from multiple shoots to aggregate prometheus and send alert for `jobs_total` at seed level.

### PR DESCRIPTION
**Pull request by renormalize**
**How to categorize this PR?**

/area control-plane
/area monitoring
/kind enhancement

**What this PR does / why we need it**:

This PR enables alerts at the seed level when `etcd-druid`'s snapshot compaction jobs fail over a certain rate. If more than 10% (the currently agreed upon value by @gardener/etcd-druid-maintainers) of shoots have their corresponding compaction jobs fail, then this alert would be raised.

These alerts are a health check for the seed cluster in the sense that a large number of snapshot compaction jobs failing simultaneously would suggest:

- Connectivity issues to the remote object storage.
- Network issues for the cloud provider, leading to alerts on all seeds on that cloud provider.
- Early detection of backup corruption.

This PR proposes the following changes:

- Federate `etcd-druid` metrics from the Cache Prometheus to the Aggregate Prometheus.
- Raise alerts based on the `etcddruid_compaction_jobs_total` metric when more than 10% of shoots whose compaction jobs deployed in last 3 hours have failed (`succeeded="false"` label).

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/etcd-druid/issues/603

**Special notes for your reviewer**:

The commit [fb302e4](https://github.com/gardener/gardener/pull/9739/commits/fb302e414c9b87c3346d264c441578f0e6befd77) is changes I've made specifically to be able to test this feature in a local gardener setup. It includes an image for etcd-druid which labels all etcd-druid snapshot compaction jobs with the `succeeded="false"` label, to simulate failed jobs. The commit [79e7470](https://github.com/gardener/gardener/pull/9739/commits/79e7470b053842444234a46a86c57db5deab065d) reverts these changes.

The sources for that can be found on this [branch](https://github.com/renormalize/etcd-druid/tree/compaction-alerts) of my fork of etcd-druid which you can use to build the etcd-druid image locally yourself, and load it into the kind cluster.

The directory where compacted snapshots would be found:

```
➜  gardener git:(compaction-alerts) ✗ tree dev/local-backupbuckets
dev/local-backupbuckets
└── XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    └── shoot--local--local--XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
        └── etcd-main
            └── v2
                ├── Full-00000000-00000001-1715322606.gz
                ├── Full-00000000-00001714-1715322909.gz
                ├── Full-00000000-00002642-1715323208.gz
                ├── Full-00000000-00003505-1715323509.gz
                ├── Full-00000000-00004335-1715323809.gz
                ├── Full-00000000-00005161-1715324109.gz
                ├── Incr-00000002-00001714-1715322906.gz
                ├── Incr-00001715-00002642-1715323207.gz
                ├── Incr-00002643-00003505-1715323507.gz
                ├── Incr-00003506-00004335-1715323807.gz
                └── Incr-00004336-00005161-1715324107.gz

5 directories, 11 files
```

**Release note**:

```feature operator
Failure of snapshot compaction jobs at a rate greater than 10% of shoots in a seed will raise alerts now.
```

### CODE REVIEW

**Comment by rickardsjp** [comment]
Hi @renormalize, what's the intention behind doing a `count(increase(...))`? The `increase()` function calculates the increase in the number of time series (in this instance occurrences of failed compactions). The `count()` function then discards the value computed by the `increase()` function and counts the number of time series. How did you pick the `3h` window? Is that sufficient?

**Comment by renormalize** [comment]
Hey @rickardsjp, thanks for your comment.

`etcddruid_compaction_jobs_total` is a *counter*, and contains the total etcd snapshot compaction jobs that have been deployed since the controller was started, for a particular shoot.

**Why `increase()`?**

`increase()` as used in the PromQL query:

```
increase(etcddruid_compaction_jobs_total{succeeded="false"}[3h])
```

calculates the increase in the number of compaction jobs that have been deployed in the last 3 hours *for a shoot* - which have the `succeeded="false"` label. If a compaction job for a particular shoot has failed in the last 3 hours, a corresponding metric shows up when queried for with `increase()`.

**Why 3 hours?**

The idea is to monitor the overall health of the seed through the compaction jobs that have been deployed in a recent window into the past, and that window is chosen to be 3 hours. 3 hours was chosen as the window, since compaction jobs can run for *upto 3 hours*, after which they are cancelled and labelled as failed.

**Why `count()`?**

`count()` as used in the PromQL query:

```
count(increase(etcddruid_compaction_jobs_total{succeeded="false"}[3h]))
```

calculates the *number of shoots* for which the compaction jobs have been failing. Each shoot will have its corresponding compaction job, and when `increase()` is invoked, we get the individual time series for each shoot.

The key thing is that `etcddruid_compaction_jobs_total` is a metric that is reported per shoot, thus to derive statistics for all shoots, we need to *count* the number of such metrics that are reported.

**Final PromQL**

```
count(increase(etcddruid_compaction_jobs_total{succeeded="false"}[3h])) / count(increase(etcddruid_compaction_jobs_total[3h])) > 0.1
```

`count(increase(etcddruid_compaction_jobs_total[3h]))` is the total number of shoots which have compaction jobs deployed in the last 3 hours, and `count(increase(etcddruid_compaction_jobs_total{succeeded="false"}[3h]))` is the total number of shoots which have failed compactions jobs deployed in the last 3 hours. The final query returns whether the percentage is greater than 10%.

The name of the metric is slightly confusing since it reads as the total number of jobs deployed by etcd-druid, i.e. across the seed; but the metric actually reports the number of jobs deployed for a single shoot.

Let me know if you more questions.

**Comment by vicwicker** [comment]
Hi @renormalize . Thanks a lot for the detailed explanation. Similar to @rickardsjp , I also have a question about the `count(increase(...[3h]))` query that I'd like to clarify for the sake of my understanding so that I can also review this PR properly.

After reading your reply, I understand that `increase(...[3h])` will return how many compaction jobs run in the last 3h for a shoot but I wonder if `count(...)` is then discarding the value returned by `increase()`. For example, if we have 3 shoots and there hasn’t been any compaction job in the last 3h then, as far as I understand, `increase(…[3h]) = 0` and `count([0 0 0]) = 3` . I fear the `count()` is indeed returning the number of shoots, and not the number of compaction jobs. Do you know if this is true?

**Comment by renormalize** [comment]
Hi @rickardsjp. Thanks for your feedback.

I fear I've made a mistake while writing the PromQL query as pointed out by you. The query `count(increase(...))` indeed returns the number of shoots, since `count()` discounts the values returned by `increase()`, and a 0 increase is also counted.
I've run a local gardener setup with 3 shoots and `count(increase(...))` does ultimately return  3 even when one of the shoots had the increase as 0.

****

One way to potentially solve this:

Filter out values returned by `increase()` which are not greater than equal to 1.
Thus, if a shoot does not failed have any compaction jobs in the last 3 hours, then the `increase()` would return 0, and `>= 1` would filter out these results.

Thus, the above query for a:

- `count([1 0 3] >= 1)` would return 2
- `count([0 0 0] >= 1)` would return 0

which would be along the lines of what we want.

```
increase(etcddruid_compaction_jobs_total{succeeded="false"}[3h]) >= 1
```

Therefore, the final query would look like:

```
count(increase(etcddruid_compaction_jobs_total{succeeded="false"}[3h]) >= 1) / count(increase(etcddruid_compaction_jobs_total[3h])) > 0.1
```

****

Using `sum()` instead of `count` to sum all the compaction jobs that have failed over all shoots would not be preferable since one shoot can have a disproportionately large number of failed compaction jobs, which would skew the metric to raise the alert even when only a few number of shoots have compaction jobs failing.

If you think this would be the right way to fix the query or have suggestions on how I could improve this, or approach designing the query altogether, please let me know! Thanks!

**Comment by vicwicker** [comment]
Hi @renormalize . Thanks for looking into my comment. 

I think both `count(... >= 1)` or `sum()` are valid approaches although they measure slightly different things. The former would count how many shoots had a failing compaction job in the last 3h, and the latter how many compactions jobs failed. After reading the PR description, I would agree the `count(... >= 1)` is probably better for this case. 

> Therefore, the final query would look like:

Should we add the `>= 1` as well in the denominator so that we calculate the ratio between shoots with compaction jobs? Otherwise it reads a bit strange IMHO: shoots with failing jobs divided by number of shoots:

```
count(increase(etcddruid_compaction_jobs_total{succeeded="false"}[3h]) >= 1) / count(increase(etcddruid_compaction_jobs_total[3h]) >= 1) > 0.1

```

**Comment by renormalize** [comment]
Hi @vicwicker, thanks for your comment.

I have no issues with adding `>=1` to the denominator as well. This would not count shoots which don't have compaction jobs enabled, which makes more sense.

If you're fine with this, then I'll make the corresponding change and push the changes.

**Comment by vicwicker** [comment]
Hi @renormalize . Yes, I think that would look good to me. Thanks.

**Comment by renormalize** [comment]
I've made the necessary changes @vicwicker. Let me know if you have more suggestions/comments. Thanks.

File: pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go [hunk 1]
```diff
@@ -67,6 +67,20 @@ func CentralPrometheusRules() []*monitoringv1.PrometheusRule {
 								"summary":     "A node is not healthy.",
 							},
 						},
+						{
+							Alert: "TooManyEtcdSnapshotCompactionJobsFailing",
+							Expr:  intstr.FromString(`count(increase(etcddruid_compaction_jobs_total{succeeded="false"}[3h]) >= 1) / count(increase(etcddruid_compaction_jobs_total[3h]) >= 1) > 0.1`),
+							For:   ptr.To(monitoringv1.Duration("10m")),
```
Comment (vicwicker) [inline pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go]: I am not sure about the `for` clause of 10 minutes. The alert considers data for the last 3 hours and I think it feels a bit strange that, with such a time window of 3 hours, we are fine alerting if the condition didn’t recover within just 10 minutes. Usually, I’d expect alerts to consider smaller time windows and alert if the conditions keep failing for longer. You mentioned above that such compaction jobs might run up to 3h so I think 3 hours is okay but maybe, in this case, we could discuss removing the `for` clause so that the alert fires as soon as there are >10% of failing compaction jobs.

File: pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go [hunk 2]
```diff
@@ -67,6 +67,20 @@ func CentralPrometheusRules() []*monitoringv1.PrometheusRule {
...
+							Labels: map[string]string{
+								"severity":   "warning",
+								"type":       "seed",
+								"visibility": "operator",
+							},
+							Annotations: map[string]string{
+								"description": "Seed {{$labels.seed}} in landscape {{$externalLabels.landscape}} has too many etcd snapshot compaction jobs failing in the past 3 hours.",
```
Comment (vicwicker) [inline pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go]: I checked the labels available in the aggregate Prometheus configuration and in the seed Alertmanager when the alert is fired and I found the `seed` label is configured as external label and that the `landscape` label is unfortunately only available in the garden Prometheus but not here. That means, you probably need to drop it for now and change the description to something like the following:

```
Seed {{$externalLabels.seed}} has too many etcd snapshot compaction jobs failing in the past 3 hours.
```

**Review by vicwicker — COMMENTED** [review]
Hi @renormalize . Thanks a lot for addressing our comments. I still have a couple of additional concerns open for discussion, though. See comments below.

I also recently thought that alerts will fire if there are too many compaction jobs within 3 hours and that they might also auto-resolve later if no compactions ran at all (i.e., it does not mean the compactions are successful now). I can’t say if that’s correct or not but I wanted to double check with you if that’s expected behaviour.

File: pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go (hunk 1 above)
Comment (renormalize) [reply pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go]: Yes, I can go ahead and remove the `for` clause since it does not make too much sense given the context that you described here.

File: pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go (hunk 2 above)
Comment (renormalize) [reply pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go]: Thanks for the suggestion, will go ahead and make this change!

Comment (renormalize) [reply pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go]: Adressed in [1fac9a2](https://github.com/gardener/gardener/pull/9739/commits/1fac9a28b83c3dc7bffd27cce5617e37e1cea461).

File: pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go (hunk 1 above)
Comment (renormalize) [reply pkg/component/observability/monitoring/prometheus/aggregate/prometheusrules.go]: Adressed in [1fac9a2](https://github.com/gardener/gardener/pull/9739/commits/1fac9a28b83c3dc7bffd27cce5617e37e1cea461).

**Review by timuthy — COMMENTED** [review]
/approve
