### PR TITLE
Change `prometheus` label of `vpa` `ServiceMonitors` from `seed` to `garden` when deployed by `garden operator` 

### LINKED ISSUE #11270: Some `ServiceMonitors` deployed by the garden operator have label `prometheus: seed` instead of `prometheus: garden`
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:
Some `ServiceMonitors` are deployed with label `prometheus: seed` in the garden cluster by the `gardener-operator`. However, the `garden` `Prometheus` which is used to collect metrics for components in the garden cluster is configured to select `ServiceMonitors` with label `prometheus: garden`. This causes metrics for the corresponding components to not be collected. Additionally, these `ServiceMonitors` are deployed with the `seed-` prefix in their name instead of `garden-`:

```bash
kubectl -n garden get ServiceMonitors
NAME                                             AGE
aggregate-fluent-bit                             16m
aggregate-fluent-bit-output-plugin               16m
aggregate-vali                                   16m
cache-etcd-druid                                 16m
garden-alertmanager-garden                       9m51s
garden-gardener-admission-controller             11m
garden-gardener-apiserver                        14m
garden-gardener-controller-manager               11m
garden-gardener-dashboard                        9m52s
garden-gardener-discovery-server                 11m
garden-gardener-metrics-exporter                 11m
garden-gardener-operator                         16m
garden-gardener-scheduler                        11m
garden-virtual-garden-etcd-events                16m
garden-virtual-garden-etcd-main                  16m
garden-virtual-garden-kube-apiserver             15m
garden-virtual-garden-kube-controller-manager    14m
--------------------------------------------------------
seed-gardener-resource-manager                   16m
seed-vpa-admission-controller                    16m
seed-vpa-recommender                             16m
--------------------------------------------------------
shoot-virtual-garden-gardener-resource-manager   14m
```

```bash
kubectl -n garden get servicemonitors -l prometheus=seed
NAME                             AGE
seed-gardener-resource-manager   18m
seed-vpa-admission-controller    18m
seed-vpa-recommender             18m
```

```
kubectl -n garden get prometheus garden -o json | jq '.spec.serviceMonitorSelector'
{
  "matchLabels": {
    "prometheus": "garden"
  }
}
```

**What you expected to happen**:
`ServiceMonitors` to be deployed with the correct labels so that metrics for the corresponding components can be scraped by the `garden` `Prometheus` running in the garden cluster.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a local dev setup following the [garden operator local development guide](https://github.com/gardener/gardener/blob/master/docs/concepts/operator.md#local-development)
2. [Create a `Garden`](https://github.com/gardener/gardener/blob/master/docs/concepts/operator.md#creating-a-garden)
3. Observe that the mentioned `ServiceMonitors` above are not created with appropriate labels 
4. Port-forward to the `prometheus-garden` service using `kubectl -n garden port-forward service/prometheus-garden 9090:80`, open the prometheus UI on `http://localhost:9090/` and notice that metrics for `gardener-resource-manager`, `vpa-admission-controller` and `vpa-recommender` are missing from the garden prometheus.

**Anything else we need to know?**:
The name and labels used for these `ServiceMonitors` are calculated using the following function: 
- For GRM:
https://github.com/gardener/gardener/blob/d5d3c638c9092efcb68b030da49edc7d953f61f6/pkg/component/gardener/resourcemanager/resource_manager.go#L1122-L1127
For garden clusters `TargetDiffersFromSourceCluster` is false

- For `vpa-recommender` and `vpa-admission-controller`:
https://github.com/gardener/gardener/blob/d5d3c638c9092efcb68b030da49edc7d953f61f6/pkg/component/autoscaling/vpa/vpa.go#L320-L325
The cluster type for the garden cluster is `seed`.

When the garden cluster is also a seed cluster, GRM and vpa-{recommender,admission-controller} [are not deployed as part of the `Seed` reconciliation](https://github.com/gardener/gardener/blob/d5d3c638c9092efcb68b030da49edc7d953f61f6/docs/concepts/operator.md?plain=1#L654-L671). However, the seed's prometheus instance is deployed and it will start scraping the  `seed-gardener-resource-manager`, `seed-vpa-admission-controller` and `seed-vpa-recommender`  `ServiceMonitors` that were deployed as part of the `Garden` reconciliation.

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by vitanovs**
**How to categorize this PR?**

/area monitoring
/kind bug

**What this PR does / why we need it**:

This PR updates the `prometheus=seed` label of `vpa-admission-controller` and `vpa-recommender` `ServiceMonitors` entries with `prometheus=garden`, when the components are deployed in a **`Garden` cluster that is also a `Seed`**.

 Since the `Garden` cluster has a `Prometheus` setup, configured to match `ServiceMonitors` with `prometheus=garden` label:

```sh
➜ gardener git:(master) ✗ kubectl -n=garden get prometheus garden -o yaml | yq -r '.spec.serviceMonitorSelector'
matchLabels:
  prometheus: garden
```

we are not collecting metrics from the `vpa-admission-controller` and `vpa-recommender` components.
With the change introduced in this PR, both `ServiceMonitors` get their `prometheus` label updated, 
enabling the `Garden` cluster `Prometheus` matching.

**Which issue(s) this PR fixes**:

Fixes https://github.com/gardener/gardener/issues/11270

**Special notes for your reviewer**:

**Release note**:

```other operator
Update `prometheus` label of `vpa-admission-controller` and `vpa-recommender` `ServiceMonitors` from `seed` to `garden` when deployed by the `garden-operator`. With this change, the `Garden` cluster `Prometheus` will match the `ServiceMonitors` and start collecting metrics from the configured services.
```

### CODE REVIEW

File: pkg/operator/controller/garden/garden/components.go [hunk 1]
```diff
@@ -406,6 +407,7 @@ func (r *Reconciler) newVerticalPodAutoscaler(garden *operatorv1alpha1.Garden, s
 		v1beta1constants.PriorityClassNameGardenSystem300,
 		v1beta1constants.PriorityClassNameGardenSystem200,
 		v1beta1constants.PriorityClassNameGardenSystem200,
+		IsGardenCluster,
```
Comment (plkokanov) [inline pkg/operator/controller/garden/garden/components.go]:
```suggestion
		true,
```

File: pkg/operator/controller/garden/garden/components.go [hunk 2]
```diff
@@ -396,6 +396,7 @@ func (r *Reconciler) newVirtualGardenGardenerResourceManager(secretsManager secr
 }
 
 func (r *Reconciler) newVerticalPodAutoscaler(garden *operatorv1alpha1.Garden, secretsManager secretsmanager.Interface) (component.DeployWaiter, error) {
+	IsGardenCluster := true
```
Comment (plkokanov) [inline pkg/operator/controller/garden/garden/components.go]:
```suggestion
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 3]
```diff
@@ -1405,6 +1420,53 @@ var _ = Describe("VPA", func() {
...
+
+					It("should label `recommender` with `prometheus=garden`", func() {
+						serviceMonitorRecommender := serviceMonitorRecommenderFor(component.ClusterTypeSeed)
+						serviceMonitorRecommender.ObjectMeta.Name = "garden-vpa-recommender"
+						serviceMonitorRecommender.ObjectMeta.Labels = map[string]string{
+							"prometheus": "garden",
+						}
+						Expect(managedResource).To(contain(serviceMonitorRecommender))
+					})
+
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 4]
```diff
@@ -1405,6 +1420,53 @@ var _ = Describe("VPA", func() {
...
+					It("should label `admission-controller` with `prometheus=seed`", func() {
+						Expect(managedResource).To(contain(serviceMonitorAdmissionController))
+					})
+
+					It("should label `recommender` with `prometheus=seed`", func() {
+						serviceMonitorRecommender := serviceMonitorRecommenderFor(component.ClusterTypeSeed)
+						Expect(managedResource).To(contain(serviceMonitorRecommender))
+					})
+
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 5]
```diff
@@ -1405,6 +1420,53 @@ var _ = Describe("VPA", func() {
...
+				})
+
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go:1491]:
```suggestion
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 6]
```diff
@@ -1680,6 +1742,89 @@ var _ = Describe("VPA", func() {
...
+				Context("should always attach `prometheus=shoot` to `recommender`", func() {
+					var serviceMonitorExpected = &monitoringv1.ServiceMonitor{}
+
+					BeforeEach(func() {
+						serviceMonitorExpected = serviceMonitorRecommenderFor(component.ClusterTypeShoot)
+						serviceMonitorExpected.ResourceVersion = "1"
+
+					})
+					It("when IsGardenCluster=true", func() {
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion

					It("when IsGardenCluster=true", func() {
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 7]
```diff
@@ -1680,6 +1742,89 @@ var _ = Describe("VPA", func() {
...
+						Expect(c.Get(ctx, client.ObjectKey{Namespace: namespace, Name: "shoot-vpa-recommender"}, serviceMonitorActual)).To(Succeed())
+
+						By("verify Prometheus label")
+						Expect(serviceMonitorActual.Labels).To(Equal(serviceMonitorExpected.ObjectMeta.Labels))
+
+						By("verify object")
+						Expect(serviceMonitorActual).To(Equal(serviceMonitorExpected))
+					})
+				})
+
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 8]
```diff
@@ -1405,6 +1420,53 @@ var _ = Describe("VPA", func() {
 				managedResourceName = "vpa"
 			})
 
+			Context("Different ServiceMonitor labels", func() {
+				Context("when used with Garden cluster", func() {
+					BeforeEach(func() {
+						isGardenCluster := true
+						vpa = vpaFor(component.ClusterTypeSeed, isGardenCluster)
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]: What about using the `vpaFor` function in the BeforeEach on [line 1410]() as well, e.g.:
```go
	Describe("#Deploy", func() {
		Context("cluster type seed", func() {
			BeforeEach(func() {
				vpa = vpaFor(component.ClusterTypeSeed, false)
				managedResourceName = "vpa"
				...
```

Then you can only overwrite it in a `BeforeEach` in the case of garden cluster.

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 9]
```diff
@@ -1405,6 +1420,53 @@ var _ = Describe("VPA", func() {
 				managedResourceName = "vpa"
 			})
 
+			Context("Different ServiceMonitor labels", func() {
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
			Context("when deploying ServiceMonitors", func() {
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 10]
```diff
@@ -1405,6 +1420,53 @@ var _ = Describe("VPA", func() {
...
+				Context("when used with Garden cluster", func() {
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
				Context("in a garden cluster", func() {
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 11]
```diff
@@ -1405,6 +1420,53 @@ var _ = Describe("VPA", func() {
...
+						serviceMonitorRecommender.ObjectMeta.Name = "garden-vpa-recommender"
+						serviceMonitorRecommender.ObjectMeta.Labels = map[string]string{
+							"prometheus": "garden",
+						}
+						Expect(managedResource).To(contain(serviceMonitorRecommender))
+					})
+
+				})
+
+				Context("when used with non-Garden cluster", func() {
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
				Context("when not deployed in a garden cluster", func() {
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 12]
```diff
@@ -1405,6 +1420,53 @@ var _ = Describe("VPA", func() {
...
 
+			Context("Different ServiceMonitor labels", func() {
+				Context("when used with Garden cluster", func() {
+					BeforeEach(func() {
+						isGardenCluster := true
+						vpa = vpaFor(component.ClusterTypeSeed, isGardenCluster)
+						Expect(vpa.Deploy(ctx)).To(Succeed())
+					})
+
+					It("should label `admission-controller` with `prometheus=garden`", func() {
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
					It("should label vpa-admission-controller ServiceMonitor with `prometheus=garden`", func() {
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 13]
```diff
@@ -1405,6 +1420,53 @@ var _ = Describe("VPA", func() {
...
+						serviceMonitorAdmissionController.ObjectMeta.Name = "garden-vpa-admission-controller"
+						serviceMonitorAdmissionController.ObjectMeta.Labels = map[string]string{
+							"prometheus": "garden",
+						}
+						Expect(managedResource).To(contain(serviceMonitorAdmissionController))
+					})
+
+					It("should label `recommender` with `prometheus=garden`", func() {
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]: ### 
```suggestion
					It("should label vpa-recommender ServiceMonitor with `prometheus=garden`", func() {
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 14]
```diff
@@ -1680,6 +1742,89 @@ var _ = Describe("VPA", func() {
 				managedResourceName = "shoot-core-vpa"
 			})
 
+			Context("Different ServiceMonitor labels", func() {
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
			Context("when deploying ServiceMonitors", func() {
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 15]
```diff
@@ -1680,6 +1742,89 @@ var _ = Describe("VPA", func() {
...
+				Context("should always attach `prometheus=shoot` to `admission-controller`", func() {
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]: Can't we use the same approach here as the above tests for the seed? E.g. first test both ServiceMonitors when `IsGardenCluster=true` then both when `IsGardenCluster=false`

**Review by plkokanov — CHANGES_REQUESTED** [review]
Thanks for the PR!
Mostly some nits in the tests.

/cc @vicwicker @rickardsjp @istvanballok

File: pkg/operator/controller/garden/garden/components.go (hunk 1 above)
Comment (vitanovs) [reply pkg/operator/controller/garden/garden/components.go]: Thanks for suggestion, removed the redundant var and left only the `bool` value when calling the function.

File: pkg/operator/controller/garden/garden/components.go (hunk 2 above)
Comment (vitanovs) [reply pkg/operator/controller/garden/garden/components.go]: Thanks for the suggestion, removed it as it's no longer needed as per https://github.com/gardener/gardener/pull/11318#discussion_r1950547870

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 3 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for catching this leftover blank line. Removed it in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 4 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for catching this leftover blank line. Removed it in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 5 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go:1491]: Thanks for catching this leftover blank line. Removed it in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 6 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for pointing this missing newline b/w the cases. Added it in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 7 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for catching this leftover blank line. Removed it in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 9 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for the suggested wording. You can find the fixed version in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 10 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for the suggested wording. You can find the fixed version in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 11 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for the suggested wording. You can find the fixed version in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 12 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for the suggested wording. You can find the fixed version in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 13 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for the suggested wording. You can find the fixed version in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 14 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for the suggested wording. You can find the fixed version in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 8 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for the suggested improvement. You can find the changes in my latest updates where I moved the `vpaFor` in the `BeforeEach` within the `in a garden cluster` context.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 15 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for the suggested improvement. You can find the restructured version of the `shoot` ServiceMonitor test cases in my latest updates.
Now both `vpa-admission-controller` and `vpa-recommeder` ServiceMonitors are being checked within the context of `IsGardenCluster` configuration - when `true` or `false` in separate contexts.

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 16]
```diff
@@ -184,6 +185,20 @@ var _ = Describe("VPA", func() {
 		Expect(c.Create(ctx, &corev1.Secret{ObjectMeta: metav1.ObjectMeta{Name: "ca", Namespace: namespace}})).To(Succeed())
 		Expect(c.Create(ctx, &corev1.Secret{ObjectMeta: metav1.ObjectMeta{Name: "generic-token-kubeconfig", Namespace: namespace}})).To(Succeed())
 
+		vpaFor = func(clusterType component.ClusterType, IsGardenCluster bool) component.DeployWaiter {
```
Comment (vicwicker) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
		vpaFor = func(clusterType component.ClusterType, isGardenCluster bool) component.DeployWaiter {
```

I think lowercase is preferable in function arguments.

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 17]
```diff
@@ -1390,18 +1405,51 @@ var _ = Describe("VPA", func() {
...
+					It("should label vpa-admission-controller ServiceMonitor with `prometheus=garden`", func() {
+						serviceMonitorAdmissionController.ObjectMeta.Name = "garden-vpa-admission-controller"
+						serviceMonitorAdmissionController.ObjectMeta.Labels = map[string]string{
+							"prometheus": "garden",
+						}
+						Expect(managedResource).To(contain(serviceMonitorAdmissionController))
+					})
+
+					It("should label vpa-recommender ServiceMonitor with `prometheus=garden`", func() {
+						serviceMonitorRecommender := serviceMonitorRecommenderFor(component.ClusterTypeSeed)
```
Comment (vicwicker) [inline pkg/component/autoscaling/vpa/vpa_test.go]: Just some thoughts, but I wonder if it would be preferable to extend the `serviceMonitorRecommenderFor()` function to take a  `isGardenCluster` argument so that the service monitor returned is the correct expectation for the test. One the one hand, I see we don't want to add too much logic to `serviceMonitorRecommenderFor()` and rather keep it simple, but on the other hand the tests currently read a bit strange IMHO because `serviceMonitorRecommenderFor()` builds the service monitor with a certain name and labels, but then these are replaced in the test case if it is the garden cluster. Maybe the best would even be if `serviceMonitorRecommenderFor()` would take the service monitor name and the prometheus label as arguments instead.

Similarly, I wonder if it'd make sense to introduce a `serviceMonitorAdmissionControllerFor()` for consistency.

Comment (plkokanov) [reply pkg/component/autoscaling/vpa/vpa_test.go]: I would agree with extending `serviceMonitorRecommenderFor()` to accept the isGardenCluster argument and to also add a `serviceMonitorAdmissionControllerFor()`.
Could you do the same for the (already existing) services functions - `serviceRecommenderFor()` and `serviceAdmissionControllerFor()` and include them in the newly added tests?

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 18]
```diff
@@ -1665,18 +1713,87 @@ var _ = Describe("VPA", func() {
...
+					serviceMonitorExpected.ResourceVersion = "1"
+				})
+
+				Context("in a garden cluster", func() {
+					BeforeEach(func() {
+						vpa = vpaFor(component.ClusterTypeShoot, true)
+						Expect(vpa.Deploy(ctx)).To(Succeed())
+					})
+
+					It("should attach `prometheus=shoot` to vpa-admission-controller ServiceMonitor", func() {
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]: Let's keep the same description as the tests above:
```suggestion
					It("should label vpa-admission-controller ServiceMonitor with `prometheus=shoot`", func() {
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 19]
```diff
@@ -1665,18 +1713,87 @@ var _ = Describe("VPA", func() {
...
+						Expect(c.Get(ctx, client.ObjectKey{Namespace: namespace, Name: "shoot-vpa-admission-controller"}, serviceMonitor)).To(Succeed())
+
+						By("verify Prometheus label")
+						Expect(serviceMonitor.Labels).To(Equal(serviceMonitorAdmissionController.ObjectMeta.Labels))
+
+						By("verify object")
+						Expect(serviceMonitor).To(Equal(serviceMonitorAdmissionController))
+					})
+
+					It("should attach `prometheus=shoot` to vpa-recommender ServiceMonitor", func() {
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
					It("should label vpa-recommender ServiceMonitor with `prometheus=shoot`", func() {
```

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 20]
```diff
@@ -1665,18 +1713,87 @@ var _ = Describe("VPA", func() {
...
+						vpa = vpaFor(component.ClusterTypeShoot, true)
+						Expect(vpa.Deploy(ctx)).To(Succeed())
+					})
+
+					It("should attach `prometheus=shoot` to vpa-admission-controller ServiceMonitor", func() {
+						serviceMonitor := &monitoringv1.ServiceMonitor{}
+						Expect(c.Get(ctx, client.ObjectKey{Namespace: namespace, Name: "shoot-vpa-admission-controller"}, serviceMonitor)).To(Succeed())
+
+						By("verify Prometheus label")
+						Expect(serviceMonitor.Labels).To(Equal(serviceMonitorAdmissionController.ObjectMeta.Labels))
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]: I don't think you need to check both the labels and the object. The labels will be implicitly checked when you call `Expect(serviceMonitor).To(Equal(serviceMonitorAdmissionController))`

File: pkg/component/autoscaling/vpa/vpa_test.go [hunk 21]
```diff
@@ -1665,18 +1713,87 @@ var _ = Describe("VPA", func() {
...
+
+				BeforeEach(func() {
+					serviceMonitorAdmissionController.TypeMeta = metav1.TypeMeta{}
+					serviceMonitorAdmissionController.ResourceVersion = "1"
+					serviceMonitorAdmissionController.ObjectMeta.Name = "shoot-vpa-admission-controller"
+					serviceMonitorAdmissionController.ObjectMeta.Labels = map[string]string{
+						"prometheus": "shoot",
+					}
+
+					serviceMonitorExpected = serviceMonitorRecommenderFor(component.ClusterTypeShoot)
```
Comment (plkokanov) [inline pkg/component/autoscaling/vpa/vpa_test.go]:
```suggestion
					serviceMonitorRecommender = serviceMonitorRecommenderFor(component.ClusterTypeShoot)
```
Keep this consistent with the naming above.

**Review by plkokanov — CHANGES_REQUESTED** [review]

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 16 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for catching this typo, I fixed it in my latest updates.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 18 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for pointing this mismatched wording. I updated the `shoot` tests to have their titles matching the previously defined cases.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 19 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for pointing this mismatched wording. Updated the titles in my latest commits.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 20 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for the hint, updated the tests and removed the redundant `labels` validation.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 21 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for pointing this naming convention, updated the tests to match the existing pattern.

File: pkg/component/autoscaling/vpa/vpa_test.go (hunk 17 above)
Comment (vitanovs) [reply pkg/component/autoscaling/vpa/vpa_test.go]: Thanks for the suggestions, please find the following updates in my latest changes:
* make `serviceMonitorRecommenderFor()` accept `isGardenCluster` argument, returning cluster-context adjusted `ServiceMonitor` for the `vpa-recommender`.
  * Update the existing usages of the function with the additional `bool` parameter. 
* add new `serviceMonitorAdmissionControllerFor()` similar to the `vpa-recommender` utility that returns cluster-context specific `vpa-admission-controller` `ServiceMonitor`.
  * Update the usages of the existing `serviceMonitorAdmissionController` variable with the new utility.

**Review by plkokanov — COMMENTED** [review]
Thanks for addressing my comments :)

/lgtm

**Comment by vitanovs** [comment]
> Thanks for taking care of my comments :) I also checked that the increase in the number of scraped samples in the garden Prometheus is not significant.

Thanks for taking the time to review it and provide your feedback, I really appreciate it! :))

**Comment by vitanovs** [comment]
> Thanks for addressing my comments :)
> 
> /lgtm

Thank you for the great feedback and suggestions, much appreciated! :))

**Review by plkokanov — COMMENTED** [review]
/approve
