### PR TITLE
Remove empty cidr check

### LINKED ISSUE #11943: IPv6 shoot can't be scheduled on Seeds without shootDefaults.
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:
IPv6 shoots without a configuration for `spec.neworking.pod` can't be scheduled to Seeds that have  `shootDefaults configured`.  Without a default value for the pod range we run into this error:
https://github.com/gardener/gardener/blob/master/pkg/utils/validation/cidr/disjoint.go#L88-L90

**What you expected to happen**:
For IPv6 seeds shootDefaults are not needed. IPv6 shoots should be scheduled.

**How to reproduce it (as minimally and precisely as possible)**:
Create an IPv6 only shoot with a seed without `shootDefaults`.
**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by axel7born**
**How to categorize this PR?**

/area networking
/kind bug

**What this PR does / why we need it**:
In general, IPv6 shoots don't have pod and service ranges configured. For IPv4 shoots the ranges are required and checked during admission [here](https://github.com/gardener/gardener/blob/4026f2e30e4e6bacf185dd33393549da6b0a55cf/plugin/pkg/shoot/validator/admission.go#L921-L939).
We never ran into this issues, as all our seeds have IPv4 shootDefaults.

**Which issue(s) this PR fixes**:
Fixes #11943

**Special notes for your reviewer**:

**Release note**:

```other operator
Fixed an issue, where IPv6 shoots without configured pod and service ranges can't be scheduled on seeds without configured shootDefaults.
```

### CODE REVIEW

File: pkg/scheduler/controller/shoot/reconciler.go [hunk 1]
```diff
@@ -510,10 +510,20 @@ func networksAreDisjointed(seed *gardencorev1beta1.Seed, shoot *gardencorev1beta
 
 	if seed.Spec.Networks.ShootDefaults != nil {
 		if shootPodsNetwork == nil && !workerless {
-			shootPodsNetwork = seed.Spec.Networks.ShootDefaults.Pods
+			if cidrvalidation.NewCIDR(*seed.Spec.Networks.ShootDefaults.Pods, field.NewPath("spec", "networks", "shootDefaults", "pods")).IsIPv6() &&
+				slices.Contains(shoot.Spec.Networking.IPFamilies, gardencorev1beta1.IPFamilyIPv6) ||
+				cidrvalidation.NewCIDR(*seed.Spec.Networks.ShootDefaults.Pods, field.NewPath("spec", "networks", "shootDefaults", "pods")).IsIPv4() &&
+					slices.Contains(shoot.Spec.Networking.IPFamilies, gardencorev1beta1.IPFamilyIPv4) {
+				shootPodsNetwork = seed.Spec.Networks.ShootDefaults.Pods
+			}
```
Comment (ScheererJ) [inline pkg/scheduler/controller/shoot/reconciler.go]:
```suggestion
			if defaultPods := cidrvalidation.NewCIDR(*seed.Spec.Networks.ShootDefaults.Pods, field.NewPath("spec", "networks", "shootDefaults", "pods")); defaultPods.IsIPv6() &&
				slices.Contains(shoot.Spec.Networking.IPFamilies, gardencorev1beta1.IPFamilyIPv6) ||
				defaultPods.IsIPv4() &&
					slices.Contains(shoot.Spec.Networking.IPFamilies, gardencorev1beta1.IPFamilyIPv4) {
				shootPodsNetwork = seed.Spec.Networks.ShootDefaults.Pods
			}
```

File: pkg/scheduler/controller/shoot/reconciler.go [hunk 2]
```diff
@@ -510,10 +510,20 @@ func networksAreDisjointed(seed *gardencorev1beta1.Seed, shoot *gardencorev1beta
...
 		}
 		if shootServicesNetwork == nil {
-			shootServicesNetwork = seed.Spec.Networks.ShootDefaults.Services
+			if cidrvalidation.NewCIDR(*seed.Spec.Networks.ShootDefaults.Services, field.NewPath("spec", "networks", "shootDefaults", "services")).IsIPv6() &&
+				slices.Contains(shoot.Spec.Networking.IPFamilies, gardencorev1beta1.IPFamilyIPv6) ||
+				cidrvalidation.NewCIDR(*seed.Spec.Networks.ShootDefaults.Services, field.NewPath("spec", "networks", "shootDefaults", "services")).IsIPv4() &&
+					slices.Contains(shoot.Spec.Networking.IPFamilies, gardencorev1beta1.IPFamilyIPv4) {
+				shootServicesNetwork = seed.Spec.Networks.ShootDefaults.Services
+			}
```
Comment (ScheererJ) [inline pkg/scheduler/controller/shoot/reconciler.go]:
```suggestion
			if defaultServices := cidrvalidation.NewCIDR(*seed.Spec.Networks.ShootDefaults.Services, field.NewPath("spec", "networks", "shootDefaults", "services")); defaultServices.IsIPv6() &&
				slices.Contains(shoot.Spec.Networking.IPFamilies, gardencorev1beta1.IPFamilyIPv6) ||
				defaultServices.IsIPv4() &&
					slices.Contains(shoot.Spec.Networking.IPFamilies, gardencorev1beta1.IPFamilyIPv4) {
				shootServicesNetwork = seed.Spec.Networks.ShootDefaults.Services
			}
```

File: pkg/utils/validation/cidr/disjoint_test.go [hunk 3]
```diff
@@ -172,7 +166,6 @@ var _ = Describe("utils", func() {
 				&seedNodesCIDR,
 				seedPodsCIDR,
 				seedServicesCIDR,
-				true,
```
Comment (ScheererJ) [inline pkg/utils/validation/cidr/disjoint_test.go:184]: This test is now redundant and should be removed. The same applies for all other workerless tests.

File: pkg/utils/validation/cidr/disjoint.go [hunk 4]
```diff
@@ -17,8 +17,8 @@ func ValidateNetworkDisjointedness(fldPath *field.Path, shootNodes, shootPods, s
 	allErrs := field.ErrorList{}
 
 	allErrs = append(allErrs, validateOverlapWithSeedWrapper(fldPath.Child("nodes"), shootNodes, "node", false, allowOverlap, seedNodes, seedPods, seedServices)...)
-	allErrs = append(allErrs, validateOverlapWithSeedWrapper(fldPath.Child("services"), shootServices, "service", true, allowOverlap, seedNodes, seedPods, seedServices)...)
-	allErrs = append(allErrs, validateOverlapWithSeedWrapper(fldPath.Child("pods"), shootPods, "pod", !workerless, allowOverlap, seedNodes, seedPods, seedServices)...)
+	allErrs = append(allErrs, validateOverlapWithSeedWrapper(fldPath.Child("services"), shootServices, "service", false, allowOverlap, seedNodes, seedPods, seedServices)...)
+	allErrs = append(allErrs, validateOverlapWithSeedWrapper(fldPath.Child("pods"), shootPods, "pod", false, allowOverlap, seedNodes, seedPods, seedServices)...)
```
Comment (ScheererJ) [inline pkg/utils/validation/cidr/disjoint.go:21]: I am not sure I can follow this line of thought. Would we not want to check the service range for all clusters except for IPv6-only clusters? The same goes for the pod range for all clusters with workers, which are not IPv6-only.

An IPv4-only shoot cluster without pods/services could now be scheduled to a seed without any errors in scheduling and admission if the seed has no shoot defaults. I guess that the reconciliation will fail. Therefore, I would prefer the previous approach of blocking this early. Nevertheless, I understand the need for special handling of the IPv6-only case as it might not be covered by the shoot defaults and should in this case be provided by the infrastructure.

**Review by ScheererJ — COMMENTED** [review]
Thanks for the change.

I think that we need to ensure that errors are detected early for IPv4 shoot clusters, though.

File: pkg/utils/validation/cidr/disjoint.go (hunk 4 above)
Comment (axel7born) [reply pkg/utils/validation/cidr/disjoint.go:21]: The behavior for IPv4 shoots is not really changing. 
An IPv4-only shoot without pods/services will be created but can't be scheduled to a seed:
Only the message is slightly different.
Before this change:
```
 Warning  SchedulingFailed  2m41s (x19 over 24m)  shoot-scheduler  Failed to schedule Shoot: 0/1 seed cluster candidate(s) are eligible for scheduling: {pr
│ ovider-extensions => invalid networks: [Required value: services is required Required value: pods is required]}
```
With this change:
```
 Warning  SchedulingFailed  5m50s (x18 over 16m)  shoot-scheduler  Failed to schedule Shoot: shoots.core.gardener.cloud "d046309ls-1" is forbidden: [spec.netw
│ rking.pods: Required value: pods is required, spec.networking.services: Required value: services is required, spec.networking.pods: Required value: shoot po
│ d network is required, spec.networking.services: Required value: shoot service network is required[]
```
The difference is, that it doesn't fail in the overlap check but is forbidden by admission while updating  `seedName`.

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve
