### PR TITLE
Keep track of the last maintenance operation in the shoot status

### LINKED ISSUE #6592: The maintenance controller in GCM to keep track of the last maintenance operation in the shoot status
**How to categorize this issue?**

/area ops-productivity robustness usability
/kind enhancement

**What would you like to be added**:
The maintenance controller in GCM to keep track of the last maintenance operation in the shoot status - it could be either a condition or a new field similar to `lastOperation`. 

**Why is this needed**:
1. To have the timestamp of the last maintenance operation.
2. Any failed maintenance operations to be made visible to the shoot owner and gardener operators with reason/error message.
3. It would be nice to have summary of what was changed in the shoot spec during the last maintenance, e.g. OS/k8s version.

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
Shoot status now has a new field `lastMaintenanceOperations` which holds the information about the time when maintenance was triggered and changes in shoot in that maintenance cycle.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/6592

**Special notes for your reviewer**:
Shoot status will look something like this:
```
lastMaintenanceOperation:
      lastTriggeredTime: "2022-09-21T13:21:07Z"
      operations:
      - 'Machine image of worker-pool "sonu-shoot1" from "gardenlinux" version "576.1.0"
        to version "576.2.0". Reason: AutoUpdate of MachineImage configured'
      - 'Shoot Kubernetes version "1.24.3" to version "1.24.5". Reason: AutoUpdate
        of Kubernetes version configured'
      - 'For worker pool sonu-shoot1 : Kubernetes version "1.24.3" to version "1.24.5".
        Reason: AutoUpdate of Kubernetes version configured'
      - 'For worker pool sonu-shoot3 : Kubernetes version "1.24.3" to version "1.24.5".
        Reason: AutoUpdate of Kubernetes version configured'
```

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/apis/core/types_shoot.go [hunk 1]
```diff
@@ -154,6 +154,16 @@ type ShootStatus struct {
 	MigrationStartTime *metav1.Time
 	// Credentials contains information about the shoot credentials.
 	Credentials *ShootCredentials
+	// LastMaintenanceOperation holds information about the last maintenance operation on the Shoot.
+	LastMaintenanceOperation *LastMaintenanceOperation
```
Comment (vpnachev) [inline pkg/apis/core/types_shoot.go]: What do you think about using https://github.com/gardener/gardener/blob/017772a4526c5cf3b0f0469703f048f87e6fa211/pkg/apis/core/types_common.go#L105-L116 ?

This will allow to set the state of the operaiton, i.e. `Failed` or `Succeeded` which can be later shown in the Dashboard. 

Also, the maintenance operation status should considered when the shoot status label is computed here https://github.com/gardener/gardener/blob/cb5947fe332be9183500b089cffad2dd335e6a08/pkg/controllermanager/controller/shoot/statuslabel/reconciler.go#L52

Comment (acumino) [reply pkg/apis/core/types_shoot.go]: > What do you think about using

IIUC you want to enhance `LastOperation` so that it holds the maintenance information.

Comment (rfranzke) [reply pkg/apis/core/types_shoot.go]: @acumino I think @vpnachev's proposal was to extend the new `LastMaintenanceOperation` type with `LastOperation` so that it can contains information about whether the operation succeeded.

However, I think it's not quite accurate/a good fit since `LastOperation` contains too many unrelated fields.
What about extending `LastMaintenance` with 

```golang
 	// Status of the last operation, one of Aborted, Processing, Succeeded, Error, Failed. 
 	State LastOperationState 
```

only? Wouldn't this be good enough?

File: pkg/apis/core/v1alpha1/types_shoot.go [hunk 2]
```diff
@@ -184,6 +184,17 @@ type ShootStatus struct {
 	// managed to change the hibernation settings of the cluster
 	// +optional
 	LastHibernationTriggerTime *metav1.Time `json:"lastHibernationTriggerTime,omitempty" protobuf:"bytes,17,opt,name=lastHibernationTriggerTime"`
+	// LastMaintenanceOperation holds information about the last maintenance operation on the Shoot.
+	// +optional
+	LastMaintenanceOperation *LastMaintenanceOperation `json:"lastMaintenanceOperation,omitempty" protobuf:"bytes,18,opt,name=lastMaintenanceOperation"`
```
Comment (rfranzke) [inline pkg/apis/core/v1alpha1/types_shoot.go]:
```suggestion
	LastMaintenance *LastMaintenance `json:"lastMaintenance,omitempty" protobuf:"bytes,18,opt,name=lastMaintenance"`
```

Change this consistently everywhere

File: pkg/apis/core/v1beta1/types_shoot.go [hunk 3]
```diff
@@ -196,6 +196,17 @@ type ShootStatus struct {
...
+	// +optional
+	LastMaintenanceOperation *LastMaintenanceOperation `json:"lastMaintenanceOperation,omitempty" protobuf:"bytes,17,opt,name=lastMaintenanceOperation"`
+}
+
+// LastMaintenanceOperation holds information about the last maintenance operation on the Shoot.
+type LastMaintenanceOperation struct {
+	// A human readable message indicating details about the last maintenance operation.
+	Operations []string `json:"operations" protobuf:"bytes,1,rep,name=operations"`
+	// LastTriggeredTime is the most recent time when maintenance was triggered.
+	LastTriggeredTime metav1.Time `json:"lastTriggeredTime" protobuf:"bytes,2,opt,name=lastTriggeredTime"`
```
Comment (rfranzke) [inline pkg/apis/core/v1beta1/types_shoot.go]: What about making this a list, i.e. `LastMaintenances []LastMaintenance`

which contains the last 3 or 5 maintenance operations? This way, it would be quite easily trackable.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 4]
```diff
@@ -150,6 +157,11 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
 		reasonsForWorkerPoolKubernetesUpdate[w.Name] = reasonForWorkerPoolKubernetesUpdate
 	}
 
+	for workerPool, reason := range reasonsForWorkerPoolKubernetesUpdate {
+		operation := fmt.Sprintf("For worker pool %s : %s", workerPool, reason)
+		operations = append(operations, operation)
+	}
+
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go:171]: You should also add operation information about the below two functions:

```golang
	maintainOperation(shoot)
	maintainTasks(shoot, r.Config)
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 5]
```diff
@@ -159,6 +171,16 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
 		return err
 	}
 
+	now = metav1.NewTime(time.Now().UTC())
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: Can you introduce and use a clock instead?

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 6]
```diff
@@ -159,6 +171,16 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+	patch := client.MergeFrom(shoot.DeepCopy())
+	shoot.Status.LastMaintenanceOperation = &gardencorev1beta1.LastMaintenanceOperation{
+		Operations:        operations,
+		LastTriggeredTime: now,
+	}
+	if err := r.Client.Status().Patch(ctx, shoot, patch); err != nil {
+		log.Error(err, "Failed to patch shoot status")
+	}
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: If this patch fails then we lose the information about the last maintenance since the next reconciliation wouldn't do anything anymore, or?
Maybe set it before you patch the shoot to `state=Processing` and here to `state=Succeeded`?

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 7]
```diff
@@ -159,6 +171,16 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
 		return err
 	}
 
+	now = metav1.NewTime(time.Now().UTC())
+	patch := client.MergeFrom(shoot.DeepCopy())
+	shoot.Status.LastMaintenanceOperation = &gardencorev1beta1.LastMaintenanceOperation{
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: Also, don't forget to extend the integration tests :)

File: pkg/apis/core/types_shoot.go (hunk 1 above)
Comment (acumino) [reply pkg/apis/core/types_shoot.go]: Yes, IMO using LastOperation for LastMaintenanceOperation is not right, this will be too much duplication. Also in maintenance time we just update the shoot manifest and then shoot reconciliation takes over and does the rest of the task so having `Progress`, `LastOperationType `, and other fields in `LastMaintenanceOperation` doesn't make much sense to me.

> What about extending LastMaintenance with LastOperationState

For this one approach can be if update call for updating shoot in maintenance controller pass then it can be set to succeed and if not then set to false.

Comment (rfranzke) [reply pkg/apis/core/types_shoot.go]: > For this one approach can be if update call for updating shoot in maintenance controller pass then it can be set to succeed and if not then set to false.

Yes, that's the idea and one of the initial motivations for the backing issue, I think. We would like to know whether the last maintenances worked.

Comment (acumino) [reply pkg/apis/core/types_shoot.go]: There is no right way to figure out if the last maintenance was successful or not, cause we don't store any state of shoot in shoot status.

File: pkg/apis/core/v1alpha1/types_shoot.go [hunk 8]
```diff
@@ -184,6 +184,17 @@ type ShootStatus struct {
...
 	// +optional
 	LastHibernationTriggerTime *metav1.Time `json:"lastHibernationTriggerTime,omitempty" protobuf:"bytes,17,opt,name=lastHibernationTriggerTime"`
+	// LastMaintenance holds information about the last maintenance operation on the Shoot.
+	// +optional
+	LastMaintenance []LastMaintenance `json:"lastMaintenance,omitempty" protobuf:"bytes,18,opt,name=lastMaintenance"`
+}
+
+// LastMaintenance holds information about the last maintenance operation on the Shoot.
+type LastMaintenance struct {
+	// A human readable message indicating details about the last maintenance operation.
```
Comment (shafeeqes) [inline pkg/apis/core/v1alpha1/types_shoot.go]: How about
```suggestion
	// A human-readable message containing details about the operations performed in the last maintenance.
```
?

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 9]
```diff
@@ -93,9 +97,16 @@ func requeueAfterDuration(shoot *gardencorev1beta1.Shoot) (time.Duration, time.T
...
 
-func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gardencorev1beta1.Shoot, gardenClient client.Client) error {
+func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gardencorev1beta1.Shoot) error {
 	log.Info("Maintaining Shoot")
 
+	var (
+		now             time.Time
+		newShoot        = shoot.DeepCopy()
+		operations      []string
+		lastMaintenance = shoot.Status.LastMaintenance
```
Comment (shafeeqes) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: Will the field be present in the first reconciliation as well?

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 10]
```diff
@@ -150,12 +165,42 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
-	maintainOperation(shoot)
-	maintainTasks(shoot, r.Config)
+	for workerPool, reason := range reasonsForWorkerPoolKubernetesUpdate {
+		operation := fmt.Sprintf("For worker pool %s : %s", workerPool, reason)
+		operations = append(operations, operation)
+	}
+
+	operation := maintainOperation(shoot)
+	if operation != "" {
+		operations = append([]string{operation}, operations...)
```
Comment (shafeeqes) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: Why not
```
		operations = append(operations, operation)
``` 
?

File: test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go [hunk 11]
```diff
@@ -111,10 +113,12 @@ var _ = BeforeSuite(func() {
 	mgrClient = mgr.GetClient()
 
 	By("registering controller")
+	fakeClock = &testclock.FakeClock{}
```
Comment (shafeeqes) [inline test/integration/controllermanager/shoot/maintenance/maintenance_suite_test.go]: Maybe initialize it with `time.Now()`?
To avoid issues like https://github.com/gardener/gardener/pull/6619/files.

**Review by shafeeqes — COMMENTED** [review]
Generally looks good. Left few comments.

File: pkg/apis/core/types_shoot.go [hunk 12]
```diff
@@ -154,6 +154,16 @@ type ShootStatus struct {
 	MigrationStartTime *metav1.Time
 	// Credentials contains information about the shoot credentials.
 	Credentials *ShootCredentials
+	// LastMaintenance holds information about the last maintenance operation on the Shoot.
+	LastMaintenance []LastMaintenance
```
Comment (rfranzke) [inline pkg/apis/core/types_shoot.go]:
```suggestion
	LastMaintenances []LastMaintenance
```

File: pkg/apis/core/types_shoot.go [hunk 13]
```diff
@@ -154,6 +154,16 @@ type ShootStatus struct {
 	MigrationStartTime *metav1.Time
 	// Credentials contains information about the shoot credentials.
 	Credentials *ShootCredentials
+	// LastMaintenance holds information about the last maintenance operation on the Shoot.
```
Comment (rfranzke) [inline pkg/apis/core/types_shoot.go]:
```suggestion
	// LastMaintenance holds information about the last maintenance operations on the Shoot.
```

File: pkg/apis/core/types_shoot.go [hunk 14]
```diff
@@ -154,6 +154,16 @@ type ShootStatus struct {
...
+	LastMaintenance []LastMaintenance
+}
+
+// LastMaintenance holds information about the last maintenance operation on the Shoot.
```
Comment (rfranzke) [inline pkg/apis/core/types_shoot.go]:
```suggestion
// LastMaintenance holds information about a maintenance operation on the Shoot.
```

File: pkg/apis/core/types_shoot.go [hunk 15]
```diff
@@ -154,6 +154,16 @@ type ShootStatus struct {
...
+type LastMaintenance struct {
+	// A human readable message indicating details about the last maintenance operation.
+	Operations []string
+	// LastTriggeredTime is the most recent time when maintenance was triggered.
+	LastTriggeredTime metav1.Time
```
Comment (rfranzke) [inline pkg/apis/core/types_shoot.go]:
```suggestion
	TriggeredTime metav1.Time
```

File: pkg/apis/core/v1alpha1/types_shoot.go [hunk 16]
```diff
@@ -184,6 +184,17 @@ type ShootStatus struct {
 	// managed to change the hibernation settings of the cluster
 	// +optional
 	LastHibernationTriggerTime *metav1.Time `json:"lastHibernationTriggerTime,omitempty" protobuf:"bytes,17,opt,name=lastHibernationTriggerTime"`
+	// LastMaintenance holds information about the last maintenance operation on the Shoot.
+	// +optional
+	LastMaintenance []LastMaintenance `json:"lastMaintenance,omitempty" protobuf:"bytes,18,opt,name=lastMaintenance"`
```
Comment (rfranzke) [inline pkg/apis/core/v1alpha1/types_shoot.go]:
```suggestion
	LastMaintenance []LastMaintenance `json:"lastMaintenances,omitempty" protobuf:"bytes,18,opt,name=lastMaintenances"`
```

(as well as all other suggestions from `core/types_shoot.go`; same for `v1beta1` package)

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 17]
```diff
@@ -34,17 +34,21 @@ import (
...
 	"k8s.io/client-go/tools/record"
+	"k8s.io/utils/clock"
 	"k8s.io/utils/pointer"
 	"k8s.io/utils/strings/slices"
 	"sigs.k8s.io/controller-runtime/pkg/client"
 	logf "sigs.k8s.io/controller-runtime/pkg/log"
 	"sigs.k8s.io/controller-runtime/pkg/reconcile"
 )
 
+const maxMaintenanceStatus = 3
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
const maxTrackedMaintenanceOperations = 3
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 9 above)
Comment (rfranzke) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: It will be empty, but it shouldn't matter? What is your concern @shafeeqes?

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 18]
```diff
@@ -150,12 +165,42 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
 		reasonsForWorkerPoolKubernetesUpdate[w.Name] = reasonForWorkerPoolKubernetesUpdate
 	}
 
-	maintainOperation(shoot)
-	maintainTasks(shoot, r.Config)
+	for workerPool, reason := range reasonsForWorkerPoolKubernetesUpdate {
+		operation := fmt.Sprintf("For worker pool %s : %s", workerPool, reason)
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
		operation := fmt.Sprintf("For worker pool %s: %s", workerPool, reason)
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 19]
```diff
@@ -150,12 +165,42 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+		operations = append(operations, operation)
+	}
+
+	operation := maintainOperation(shoot)
+	if operation != "" {
+		operations = append([]string{operation}, operations...)
+	}
+
+	tasks := maintainTasks(shoot, r.Config)
+	operations = append(tasks, operations...)
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
	operations = append(operations, tasks...)
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 20]
```diff
@@ -150,12 +165,42 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+
+	now = r.Clock.Now()
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 21]
```diff
@@ -150,12 +165,42 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+	patch := client.MergeFrom(newShoot.DeepCopy())
+	lastMaintenance = append([]gardencorev1beta1.LastMaintenance{
+		{
+			Operations:        operations,
+			LastTriggeredTime: metav1.Time{Time: now},
+		},
+	}, lastMaintenance...)
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
	lastMaintenances = append([]gardencorev1beta1.LastMaintenance{{
		Operations:        operations,
		LastTriggeredTime: metav1.Time{Time: r.Clock.Now()},
	}}, lastMaintenance...)
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 9 above)
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
		lastMaintenances = shoot.Status.LastMaintenance
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 22]
```diff
@@ -93,9 +97,16 @@ func requeueAfterDuration(shoot *gardencorev1beta1.Shoot) (time.Duration, time.T
 	return duration, nextMaintenance
 }
 
-func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gardencorev1beta1.Shoot, gardenClient client.Client) error {
+func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gardencorev1beta1.Shoot) error {
 	log.Info("Maintaining Shoot")
 
+	var (
+		now             time.Time
+		newShoot        = shoot.DeepCopy()
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 23]
```diff
@@ -150,12 +165,42 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+	operation := maintainOperation(shoot)
+	if operation != "" {
+		operations = append([]string{operation}, operations...)
+	}
+
+	tasks := maintainTasks(shoot, r.Config)
+	operations = append(tasks, operations...)
+
+	now = r.Clock.Now()
+	patch := client.MergeFrom(newShoot.DeepCopy())
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go:180]:
```suggestion
	patch := client.MergeFrom(shoot.DeepCopy())
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 24]
```diff
@@ -150,12 +165,42 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+	lastMaintenance = append([]gardencorev1beta1.LastMaintenance{
+		{
+			Operations:        operations,
+			LastTriggeredTime: metav1.Time{Time: now},
+		},
+	}, lastMaintenance...)
+
+	if len(lastMaintenance) > maxMaintenanceStatus {
+		newShoot.Status.LastMaintenance = lastMaintenance[0:3]
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
		shoot.Status.LastMaintenance = lastMaintenance[0:3]
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 25]
```diff
@@ -150,12 +165,42 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+	} else {
+		newShoot.Status.LastMaintenance = lastMaintenance
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]:
```suggestion
		shoot.Status.LastMaintenance = lastMaintenance
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 26]
```diff
@@ -150,12 +165,42 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+	}
+
+	if err := r.Client.Status().Patch(ctx, newShoot, patch); err != nil {
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go:194]:
```suggestion
	if err := r.Client.Status().Patch(ctx, shoot, patch); err != nil {
```

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 27]
```diff
@@ -178,42 +223,56 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
 	if shoot.Status.LastOperation == nil {
-		return
+		return ""
 	}
 
 	switch {
 	case shoot.Status.LastOperation.State == gardencorev1beta1.LastOperationStateFailed:
 		if needsRetry(shoot) {
 			metav1.SetMetaDataAnnotation(&shoot.ObjectMeta, v1beta1constants.GardenerOperation, v1beta1constants.ShootOperationRetry)
+			operation = "gardener.cloud/operation: retry"
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: Use the constants?

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 28]
```diff
@@ -178,42 +223,56 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
 			delete(shoot.Annotations, v1beta1constants.FailedShootNeedsRetryOperation)
 		}
 	default:
-		metav1.SetMetaDataAnnotation(&shoot.ObjectMeta, v1beta1constants.GardenerOperation, getOperation(shoot))
+		operation = getOperation(shoot)
+		metav1.SetMetaDataAnnotation(&shoot.ObjectMeta, v1beta1constants.GardenerOperation, operation)
+		operation = "gardener.cloud/operation: " + operation
```
Comment (rfranzke) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go]: same here

File: test/integration/controllermanager/shoot/maintenance/maintenance_test.go [hunk 29]
```diff
@@ -342,6 +342,12 @@ var _ = Describe("Shoot Maintenance controller tests", func() {
 				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(shoot), shoot)).To(Succeed())
 				g.Expect(*shoot.Spec.Provider.Workers[0].Machine.Image).To(Equal(gardencorev1beta1.ShootMachineImage{Name: highestAMD64MachineImage.Name, Version: highestAMD64MachineImage.Version}))
 				g.Expect(*shoot.Spec.Provider.Workers[1].Machine.Image).To(Equal(gardencorev1beta1.ShootMachineImage{Name: highestARM64MachineImage.Name, Version: highestARM64MachineImage.Version}))
+				g.Expect(shoot.Status.LastMaintenance).ToNot(BeNil())
+				g.Expect(shoot.Status.LastMaintenance[0].Operations).To(Equal([]string{
```
Comment (rfranzke) [inline test/integration/controllermanager/shoot/maintenance/maintenance_test.go]: Use `ConsistOf` (same below)

File: pkg/apis/core/types_shoot.go (hunk 1 above)
Comment (rfranzke) [reply pkg/apis/core/types_shoot.go]: OK, the maintenance controller only updates the spec, and we only know whether it "worked" when the `Shoot` was successfully reconciled after the `triggeredTime`. Fine, we can also get started without this `State` field for now, see how it goes and improve later on if needed.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 23 above)
Comment (acumino) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go:180]: newShoot is required cause once patch operation is called it overwrites all the local changes on the object, so changes that would have been done on a shoot while checking for machine image and Kubernetes version upgrade will be lost if I use patch call on shoot instead of newShoot.

Comment (rfranzke) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go:180]: OK, understood. Not quite intuitive, though. It would be more clear if the various `maintain*` functions rather return mutation functions `func(*gardencorev1beta1.Shoot)` instead of directly modifying the object. Then we can call those at the end before the `Update()` call and don't need this `newShoot`. WDYT? I don't insist on it for now, just an idea.

Comment (acumino) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go:180]: Using mutate function for worker pool Kubernetes version is a bit to much overdo, so I will skip this.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go [hunk 30]
```diff
@@ -150,12 +164,41 @@ func (r *Reconciler) reconcile(ctx context.Context, log logr.Logger, shoot *gard
...
+	tasks := maintainTasks(shoot, r.Config)
+	operations = append(operations, tasks...)
+
+	patch := client.MergeFrom(newShoot.DeepCopy())
+	lastMaintenances = append([]gardencorev1beta1.LastMaintenance{
+		{
+			Operations:    operations,
+			TriggeredTime: metav1.Time{Time: r.Clock.Now()},
+		},
+	}, lastMaintenances...)
```
Comment (shafeeqes) [inline pkg/controllermanager/controller/shoot/maintenance/reconciler.go:186]:
```suggestion
	lastMaintenances = append(lastMaintenances, gardencorev1beta1.LastMaintenance{
		Operations:    operations,
		TriggeredTime: metav1.Time{Time: r.Clock.Now()},
	})
```

File: test/integration/controllermanager/shoot/maintenance/maintenance_test.go [hunk 31]
```diff
@@ -342,6 +342,12 @@ var _ = Describe("Shoot Maintenance controller tests", func() {
 				g.Expect(testClient.Get(ctx, client.ObjectKeyFromObject(shoot), shoot)).To(Succeed())
 				g.Expect(*shoot.Spec.Provider.Workers[0].Machine.Image).To(Equal(gardencorev1beta1.ShootMachineImage{Name: highestAMD64MachineImage.Name, Version: highestAMD64MachineImage.Version}))
 				g.Expect(*shoot.Spec.Provider.Workers[1].Machine.Image).To(Equal(gardencorev1beta1.ShootMachineImage{Name: highestARM64MachineImage.Name, Version: highestARM64MachineImage.Version}))
+				g.Expect(shoot.Status.LastMaintenances).ToNot(BeNil())
```
Comment (shafeeqes) [inline test/integration/controllermanager/shoot/maintenance/maintenance_test.go]:
```suggestion
				g.Expect(shoot.Status.LastMaintenances).NotTo(BeEmpty())
```
since it's a slice. same for all other occurences.

File: test/integration/controllermanager/shoot/maintenance/maintenance_test.go [hunk 32]
```diff
@@ -358,6 +364,12 @@ var _ = Describe("Shoot Maintenance controller tests", func() {
...
+				g.Expect(shoot.Status.LastMaintenances[0].Operations).To(ConsistOf(
+					"Reconcile following resources: Infrastructure, DNSRecordInternal, DNSRecordExternal, DNSRecordIngress",
+					"Machine image of worker-pool \"cpu-worker1\" from \"foo-image\" version \"0.0.1-beta\" to version \"1.1.1\". Reason: MachineImage expired - force update required",
```
Comment (shafeeqes) [inline test/integration/controllermanager/shoot/maintenance/maintenance_test.go:370]: Nit:
```suggestion
					ContainSubstring("Machine image of worker-pool %q from %q version %q to version %q. Reason: MachineImage expired - force update required", "cpu-worker1", "foo-image", "0.0.1-beta", "1.1.1"),
```
same for others.

File: pkg/controllermanager/controller/shoot/maintenance/reconciler.go (hunk 30 above)
Comment (acumino) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go:186]: this is intentional.

Comment (shafeeqes) [reply pkg/controllermanager/controller/shoot/maintenance/reconciler.go:186]: Oh, for the latest one to be on top. Okay.

File: test/integration/controllermanager/shoot/maintenance/maintenance_test.go (hunk 32 above)
Comment (acumino) [reply test/integration/controllermanager/shoot/maintenance/maintenance_test.go:370]: Is this required, for the test I think a static string should be fine.

Comment (shafeeqes) [reply test/integration/controllermanager/shoot/maintenance/maintenance_test.go:370]: I don't have a strong opinion.

**Comment by rfranzke** [comment]
/lgtm

Waiting for @shafeeqes's review
