### PR TITLE
Continuous Shoot status checks

### LINKED ISSUE #343: shoot.status.conditions are removed
I'd expect shoots' `.status.conditions` fields not to be empty ever once they have successfully provisioned, but we regularly see as reconciliation fails the conditions field is removed.  I'm not sure about the best practices here but we expect to see a value for the rest of the shoot's lifecycle if once there was any value.

For reconciliation failures there should be dedicated reason (e.g. Stale) to be place into the corresponding conditions rather than removing the conditions field at all.

This is a regular issue for shoots on Azure since we have reconciliations failing regularly due to Azure API not being as fast as Gardener expects. (e.g. volume detach/attach or LB creations for services could take up to an hour, or VM provisioning taking longer in some regions)

Example shoot status on one of our gardener installations:
```
[msa-dev-garden:garden]~ $ kubectl get --all-namespaces shoots | sed 's/dub.*io/<cropped>/'
NAMESPACE   NAME        CLOUDPROFILE   VERSION   SEED              DOMAIN                OPERATION    PROGRESS   CONTROL     NODES       SYSTEM      AGE
cloud-9     cloud-9     azure          1.10.5    azure-eastus-01   cloud-9.<cropped>     Processing   84         <unknown>   <unknown>   <unknown>   65d
consus      axeda       azure          1.10.5    azure-eastus-01   axeda.<cropped>       Failed       84         False       False       False       14d
consus      consus      azure          1.10.5    azure-eastus-01   consus.<cropped>      Processing   80         <unknown>   <unknown>   <unknown>   65d
flow        flow        azure          1.10.5    azure-eastus-01   flow.<cropped>        Processing   80         <unknown>   <unknown>   <unknown>   65d
ipa         ipa         azure          1.10.5    azure-eastus-01   ipa.<cropped>         Processing   80         <unknown>   <unknown>   <unknown>   39d
man         man         azure          1.10.5    azure-eastus-01   man.<cropped>         Processing   80         <unknown>   <unknown>   <unknown>   66d
studio      studio      azure          1.10.5    azure-eastus-01   studio.<cropped>      Processing   84         <unknown>   <unknown>   <unknown>   1d
wnc         windchill   azure          1.10.5    azure-eastus-01   windchill.<cropped>   Processing   80         <unknown>   <unknown>   <unknown>   62d
[msa-dev-garden:garden]~ $ 
```

consus shoot status field doesn't have a`conditions` field:
```
[msa-dev-garden:garden]~ $ kubectl get shoot -n consus consus -o yaml
...
status:
  gardener:
    id: 2166589d48b6804b9da69e7d2ae2a33f6901aae1a8bff6579f48e8f764cf0408
    name: gardener-controller-manager-587bd55dfc-8cqcw
    version: 0.10.0-dev
  lastError:
    description: 'Failed to reconcile Shoot cluster state: Errors occurred during
      flow execution: ''(*HybridBotanist).ReconcileMachines'' returned ''Failed while
      waiting for all machine deployments to be ready: ''timed out waiting for the
      condition'''''
  lastOperation:
    description: Executing ReconcileMachines.
    lastUpdateTime: 2018-08-29T10:55:38Z
    progress: 80
    state: Processing
    type: Reconcile
  observedGeneration: 10
  retryCycleStartTime: 2018-08-28T11:18:18Z
  seed: azure-eastus-01
  technicalID: shoot--consus--consus
  uid: 9e488c58-77c4-11e8-8af0-5635bb14771b
```

axeda shoot has the `.status.conditions` field (included just as an example):
```  conditions:
  - lastTransitionTime: 2018-08-29T11:17:57Z
    message: Deployment machine-controller-manager has not yet the desired number
      of available pods.
    reason: DeploymentUnavailable
    status: "False"
    type: ControlPlaneHealthy
  - lastTransitionTime: 2018-08-29T09:21:11Z
    message: Node shoot--consus--axeda-cpu-worker-69fc66b955-gfk74 is not ready.
    reason: NodeNotReady
    status: "False"
    type: EveryNodeReady
  - lastTransitionTime: 2018-08-29T09:21:11Z
    message: Deployment addons-heapster-e3b0c has not yet the desired number of available
      pods.
    reason: DeploymentUnavailable
    status: "False"
    type: SystemComponentsHealthy
```

### PR DESCRIPTION
**Pull request by adracus**
continuously do health checks on shoots
refactor health checks to deal with uninitialized state of shoot
change health checks to only operate on required resources
update charts to include `garden.sapcloud.io/role` `controlplane` /
`system-component` labels
create test cases

**What this PR does / why we need it**:
With this change, Shoots are continuously checked for status. Also, the conditions are not removed anymore during reconciliation and during deletion. Condition checks will only end once a shoot is gone.
Of course, continuous monitoring during reconciliation will display some conditions of a Shoot as
red during reconciliation (if the Shoot was not high-availably configured and some of its critical components go down) but overall the monitoring of a shoot will improve by this change. 

**Which issue(s) this PR fixes**:
Fixes #343 

**Special notes for your reviewer**:

**Release note**:

```noteworthy user
Shoot conditions are now retained during reconciliation and deletion operations. The checks are being conducted during the initial creation of shoots as well. The condition checks themselves now also check more thoroughly on the existence of specific Kubernetes objects (`Deployment`s, `DaemonSet`s, `StatefulSet`s) in both the seed and the shoot.
```

### CODE REVIEW

File: pkg/apis/garden/v1beta1/helper/helpers.go [hunk 1]
```diff
@@ -126,25 +126,24 @@ func InitCondition(conditionType gardenv1beta1.ConditionType, reason, message st
...
-		(*condition).Status = status
-	}
-	if reason != (*condition).Reason {
-		update = true
-		(*condition).Reason = reason
-	}
-	if message != (*condition).Message {
-		update = true
-		(*condition).Message = message
+// UpdatedCondition updates the properties of one specific condition.
```
Comment (rfranzke) [inline pkg/apis/garden/v1beta1/helper/helpers.go:192]: Shouldn't it be called `UpdateCondition`?

File: pkg/client/kubernetes/base/daemonsets.go [hunk 2]
```diff
@@ -0,0 +1,11 @@
+package kubernetesbase
```
Comment (rfranzke) [inline pkg/client/kubernetes/base/daemonsets.go:15]: License header is missing

File: pkg/controller/shoot/shoot_care_control.go [hunk 3]
```diff
@@ -61,20 +47,16 @@ func (c *Controller) reconcileShootCareKey(key string) error {
...
 	shoot, err := c.shootLister.Shoots(namespace).Get(name)
 	if apierrors.IsNotFound(err) {
-		logger.Logger.Debugf("[SHOOT CARE] %s - skipping because Shoot has been deleted", key)
+		logger.Logger.Infof("[SHOOT CARE] Stopping care operations for Shoot %s since it has been deleted", key)
+		c.shootCareQueue.Done(key)
 		return nil
 	}
 	if err != nil {
 		logger.Logger.Infof("[SHOOT CARE] %s - unable to retrieve object from store: %v", key, err)
 		return err
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_care_control.go:58]: I guess we should re-add the key in this case, would you agree?

File: pkg/controller/shoot/shoot_care_control.go [hunk 4]
```diff
@@ -127,37 +109,41 @@ func (c *defaultCareControl) Care(shootObj *gardenv1beta1.Shoot, key string) err
...
-		conditionEveryNodeReady = helper.ModifyCondition(conditionEveryNodeReady, corev1.ConditionUnknown, gardenv1beta1.ConditionCheckError, message)
-		conditionSystemComponentsHealthy = helper.ModifyCondition(conditionSystemComponentsHealthy, corev1.ConditionUnknown, gardenv1beta1.ConditionCheckError, message)
-		operation.Logger.Error(message)
+		var (
+			message string
+			reason  string
+		)
+		if apierrors.IsNotFound(err) {
+			message = "No kubernetes API server available to do care operations."
+			reason = "NoKubeAPIServer"
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_care_control.go]: `KubeAPIServerMissing`?

File: pkg/controller/shoot/shoot_care_control.go [hunk 5]
```diff
@@ -127,37 +109,41 @@ func (c *defaultCareControl) Care(shootObj *gardenv1beta1.Shoot, key string) err
...
-		message := fmt.Sprintf("Failed to create a K8SClient for the Shoot cluster to perform the care operations (%s).", err.Error())
-		conditionEveryNodeReady = helper.ModifyCondition(conditionEveryNodeReady, corev1.ConditionUnknown, gardenv1beta1.ConditionCheckError, message)
-		conditionSystemComponentsHealthy = helper.ModifyCondition(conditionSystemComponentsHealthy, corev1.ConditionUnknown, gardenv1beta1.ConditionCheckError, message)
-		operation.Logger.Error(message)
+		var (
+			message string
+			reason  string
+		)
+		if apierrors.IsNotFound(err) {
+			message = "No kubernetes API server available to do care operations."
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_care_control.go]: s/kubernetes API server/kube-apiserver pod

File: pkg/controller/shoot/shoot_care_control.go [hunk 6]
```diff
@@ -127,37 +109,41 @@ func (c *defaultCareControl) Care(shootObj *gardenv1beta1.Shoot, key string) err
...
+		conditionEveryNodeReady = helper.UpdatedCondition(conditionEveryNodeReady, corev1.ConditionUnknown, reason, message)
+		conditionSystemComponentsHealthy = helper.UpdatedCondition(conditionSystemComponentsHealthy, corev1.ConditionUnknown, reason, message)
 		c.updateShootStatus(shoot, *conditionControlPlaneHealthy, *conditionEveryNodeReady, *conditionSystemComponentsHealthy)
 		return nil
 	}
 
-	// Trigger garbage collection
-	go garbageCollection(botanist)
+	// Trigger garbage collection only when shoot is not deleting
+	if shoot.DeletionTimestamp == nil {
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_care_control.go]: See comment in #343: Shouldn't we trigger the garbage collection always? One part of the garbage collection is that stuck terminated pods are deleted forcefully after a grace period. We have seen cases in which clusters were not terminating because pods were stuck, and as the care controller was not running they couldn't get deleted.

If we decide to not run the garbage collector always then we need to implement the forceful deletion of stuck terminating pods similar to what we did for `APIService`s and `CustomResourceDefinition`s.

File: pkg/controller/shoot/shoot_care_control.go [hunk 7]
```diff
@@ -221,24 +207,41 @@ func garbageCollection(botanist *botanistpkg.Botanist) {
...
+		updatedClusterNodesCondition     *gardenv1beta1.Condition
+		updatedSystemComponentsCondition *gardenv1beta1.Condition
+	)
 
 	wg.Add(3)
 	go func() {
 		defer wg.Done()
-		conditionControlPlaneHealthy = botanist.CheckConditionControlPlaneHealthy(conditionControlPlaneHealthy)
+		var err error
+		updatedControlPlaneCondition, err = botanist.CheckControlPlane(controlPlaneCondition)
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_care_control.go]: Why explicitly declaring
```golang
var err error
```
? What about
```suggestion
		updatedControlPlaneCondition, err := botanist.CheckControlPlane(controlPlaneCondition)
```

(Same for other occurrences here)

File: pkg/controller/shoot/shoot_care_control.go [hunk 8]
```diff
@@ -221,24 +207,41 @@ func garbageCollection(botanist *botanistpkg.Botanist) {
...
+		updatedSystemComponentsCondition, err = botanist.CheckSystemComponents(systemComponentsCondition)
+		if err != nil {
+			updatedSystemComponentsCondition = helper.UpdatedConditionUnknownError(updatedSystemComponentsCondition, err)
+		}
 	}()
 	wg.Wait()
 
-	botanist.Logger.Debugf("Successfully performed health check for Shoot cluster '%s'", botanist.Shoot.Info.Name)
-	return conditionControlPlaneHealthy, conditionEveryNodeReady, conditionSystemComponentsHealthy
+	botanist.Logger.Infof("Successfully performed health check for Shoot cluster '%s'", botanist.Shoot.Info.Name)
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_care_control.go]: Shouldn't we keep this at debug level?

File: pkg/operation/common/types.go [hunk 9]
```diff
@@ -253,6 +282,45 @@ const (
...
 
+var (
+	// ETCDMainStatefulSetName is the name of the etcd-main stateful set.
+	ETCDMainStatefulSetName = fmt.Sprintf("etcd-%s", EtcdRoleMain)
+	// ETCDEventsStatefulSetName is the name of the etcd-events stateful set.
+	ETCDEventsStatefulSetName = fmt.Sprintf("etcd-%s", EtcdRoleEvents)
+
+	// RequiredSeedShootControlPlaneDeployments is a set of the required shoot control plane deployments
+	// running in the seed.
+	RequiredSeedShootControlPlaneDeployments = sets.NewString(
```
Comment (rfranzke) [inline pkg/operation/common/types.go]: The AWS LB Readvertiser might also be a required deployment.

File: pkg/utils/kubernetes/health/health.go [hunk 10]
```diff
@@ -0,0 +1,117 @@
...
+	}
+
+	replicas := int32(1)
+	if deployment.Spec.Replicas != nil {
+		replicas = *deployment.Spec.Replicas
+	}
+
+	if deployment.Status.UpdatedReplicas != replicas {
+		return fmt.Errorf("deployment does not have enough updated replicas (%d/%d)", deployment.Status.UpdatedReplicas, replicas)
+	}
```
Comment (rfranzke) [inline pkg/utils/kubernetes/health/health.go:117]: Shouldn't we check the  `readyReplicas` as well (same for StatefulSets)?

File: pkg/utils/kubernetes/health/health.go [hunk 11]
```diff
@@ -0,0 +1,117 @@
...
+	"fmt"
+	"github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1"
+	appsv1 "k8s.io/api/apps/v1"
+	corev1 "k8s.io/api/core/v1"
+	"k8s.io/client-go/kubernetes"
+)
+
+// CheckHealthzEndpoint checks the Kubernetes `healthz` endpoint.
+// A cluster is considered healthy if its status code is >= 200 and < 300.
+func CheckHealthzEndpoint(k kubernetes.Interface) (bool, error) {
```
Comment (rfranzke) [inline pkg/utils/kubernetes/health/health.go]: Can this be omitted at all if we would check the `.status.readyReplicas` (see comment below) when checking a deployment? The kube-apiserver pod gets unready anyway if the `/healthz` endpoint check performed by the kubelet fails.

File: pkg/utils/kubernetes/health/health.go [hunk 12]
```diff
@@ -0,0 +1,117 @@
...
+
+// CheckDaemonSet checks whether the given DaemonSet is healthy.
+// A DaemonSet is considered healthy if its controller observed its current revision and if
+// its desired number of scheduled pods is equal to its updated number of scheduled pods.
+func CheckDaemonSet(daemonSet *appsv1.DaemonSet) error {
+	if daemonSet.Status.ObservedGeneration < daemonSet.Generation {
+		return fmt.Errorf("daemon set has not been observed at its latest version")
+	}
+
+	if daemonSet.Status.DesiredNumberScheduled != daemonSet.Status.UpdatedNumberScheduled {
```
Comment (rfranzke) [inline pkg/utils/kubernetes/health/health.go]: What about `.status.currentNumberScheduled`? Shouldn't we compare this one against `.status.desiredNumberScheduled` for health checking a DaemonSet?

File: pkg/utils/kubernetes/health/health_test.go [hunk 13]
```diff
@@ -0,0 +1,129 @@
+package health_test
```
Comment (rfranzke) [inline pkg/utils/kubernetes/health/health_test.go:15]: License header is missing

File: pkg/utils/kubernetes/health/health.go [hunk 14]
```diff
@@ -0,0 +1,117 @@
+package health
```
Comment (rfranzke) [inline pkg/utils/kubernetes/health/health.go:15]: License header is missing

File: pkg/operation/botanist/health_check.go [hunk 15]
```diff
@@ -19,161 +19,299 @@ import (
...
 	}
-	var statusCode int
-	response.StatusCode(&statusCode)
-	if statusCode < 200 || statusCode >= 400 {
-		return helper.ModifyCondition(condition, corev1.ConditionFalse, "KubeAPIServerNotHealthy", "Shoot cluster kube-apiserver's /healthz endpoint indicates unhealthiness.")
+	if !healthy {
+		return helper.UpdatedCondition(
+				condition,
+				corev1.ConditionFalse,
+				"KubeAPIServerNotHealthy",
```
Comment (rfranzke) [inline pkg/operation/botanist/health_check.go]: s/NotHealthy/Unhealthy ?

File: pkg/operation/botanist/health_check.go [hunk 16]
```diff
@@ -19,161 +19,299 @@ import (
 
 	gardenv1beta1 "github.com/gardener/gardener/pkg/apis/garden/v1beta1"
 	"github.com/gardener/gardener/pkg/apis/garden/v1beta1/helper"
-	"github.com/gardener/gardener/pkg/client/kubernetes"
+	"github.com/gardener/gardener/pkg/operation/common"
+	"github.com/gardener/gardener/pkg/utils/kubernetes/health"
 	machinev1alpha1 "github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1"
+	"k8s.io/api/apps/v1"
```
Comment (rfranzke) [inline pkg/operation/botanist/health_check.go]: better alias that one to `appsv1`

File: pkg/operation/botanist/health_check.go [hunk 17]
```diff
@@ -19,161 +19,299 @@ import (
...
-	// Check whether the number of running containers matching the number of actual containers within all our pods (i.e., everything we deploy
-	// is running).
-	if updatedCondition, modified := verifyPodHealthiness(condition, b.K8sShootClient, metav1.NamespaceSystem, listOptions); modified {
-		return updatedCondition
+	if exitCondition, err := b.checkControlPlaneShoot(condition); err != nil || exitCondition != nil {
+		return exitCondition, err
 	}
 
-	return helper.ModifyCondition(condition, corev1.ConditionTrue, "AllPodsRunning", "All pods in the kube-system namespace of the Shoot cluster are running.")
+	return helper.UpdatedCondition(condition, corev1.ConditionTrue, "SeedAndShootControlPlaneUp", "All components of the control plane are healthy."), nil
```
Comment (rfranzke) [inline pkg/operation/botanist/health_check.go]: s/SeedAndShootControlPlaneUp/ControlPlaneRunning

**Review by rfranzke — CHANGES_REQUESTED** [review]
Thank you, a few comments apart from those made inline:

1. You are considering some of the pods running in the shoot's `kube-system` namespace to be part of the control plane. I'd refrain from doing this (it's even incorrect) and keep the behavior as before: The first condition is indicating health of the components running in the shoot namespace in the seed cluster, and the third condition is indicating health of the kube-system pods deployed by Gardener.
1. You don't do checking whether the monitoring stack in the shoot's namespace in the seed is running. Please include this. How should we know that it's failing?
1. From what I see without digging deeper: The `garden.sapcloud.io/role` labels are missing for a few components: aws-lb-readvertiser, helm-tiller, monocular-ui, coredns, node-exporter. Please check again whether you have covered all components deployed by us.
1. Speaking of the labels, as said, I'd label all pods in the shoot's namespace in the seed with `garden.sapcloud.io/role=controlplane` (also the monitoring pods), the critical system pods like kube-proxy, coredns, calico, etc. with `garden.sapcloud.io/role=system-component`, and all the optional addons like nginx, dashboard, etc. with `garden.sapcloud.io/role=optional-addon`

File: pkg/controller/shoot/shoot_care_control.go (hunk 7 above)
Comment (adracus) [reply pkg/controller/shoot/shoot_care_control.go]: If you not explicitly declare `err error` , the assignment to `updatedControlPlaneCondition` and others would only be visible in the goroutine but not outside for the final return.

File: pkg/apis/garden/v1beta1/helper/helpers.go (hunk 1 above)
Comment (adracus) [reply pkg/apis/garden/v1beta1/helper/helpers.go:192]: Intentionally called it `UpdatedCondition` since it returns a new condition instead of modifying the old one (what `UpdateCondition` could suggest).

File: pkg/utils/kubernetes/health/health.go (hunk 10 above)
Comment (adracus) [reply pkg/utils/kubernetes/health/health.go:117]: `readyReplicas` is the accumulated number of replicas, regardless of the version of the StatefulSet / Deployment / DaemonSet. So if there is e.g. a RollingUpdate, the number of `readyReplicas` may be higher than the number of `replicas` due to a `surge` in the update while there are still not enough `updatedReplicas`.

Comment (rfranzke) [reply pkg/utils/kubernetes/health/health.go:117]: Thx, agreed.

File: pkg/apis/garden/v1beta1/helper/helpers.go (hunk 1 above)
Comment (rfranzke) [reply pkg/apis/garden/v1beta1/helper/helpers.go:192]: Makes sense, agreed. Thx.

File: pkg/controller/shoot/shoot_care_control.go (hunk 7 above)
Comment (rfranzke) [reply pkg/controller/shoot/shoot_care_control.go]: OK, I missed that one. Thanks.

File: pkg/controller/shoot/shoot_care_control.go (hunk 3 above)
Comment (adracus) [reply pkg/controller/shoot/shoot_care_control.go:58]: Re-adding already happens with the worker controller loop we have (rate-limited in this case).

File: pkg/controller/shoot/shoot_care_control.go [hunk 18]
```diff
@@ -127,28 +109,30 @@ func (c *defaultCareControl) Care(shootObj *gardenv1beta1.Shoot, key string) err
...
 	if err := botanist.InitializeShootClients(); err != nil {
-		message := fmt.Sprintf("Failed to create a K8SClient for the Shoot cluster to perform the care operations (%s).", err.Error())
-		conditionEveryNodeReady = helper.ModifyCondition(conditionEveryNodeReady, corev1.ConditionUnknown, gardenv1beta1.ConditionCheckError, message)
-		conditionSystemComponentsHealthy = helper.ModifyCondition(conditionSystemComponentsHealthy, corev1.ConditionUnknown, gardenv1beta1.ConditionCheckError, message)
-		operation.Logger.Error(message)
+		var (
+			message string
+			reason  string
+		)
+		if apierrors.IsNotFound(err) {
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_care_control.go]: Hm, if this function returns this error then we only know that the secret Gardener using to talk to the kube-apiserver is not found.  We can't really deduce that the kube-apiserver pod is not available.
If we want to deduce this and propagate it to the user we should find a better check, otherwise we should adapt the error message.

**Review by rfranzke — COMMENTED** [review]
Looks good, one code-wise comment. I still need to functionally play around with it.

File: pkg/controller/shoot/shoot_care_control.go (hunk 18 above)
Comment (adracus) [reply pkg/controller/shoot/shoot_care_control.go]: Reverted to old behavior

**Comment by rfranzke** [comment]
As discussed in-person the status report seems to be broken (shoot controller and shoot care controller are simultaneously updating `.status` and probably get many conflicts). Also, commits should be squashed.

**Comment by rfranzke** [comment]
FYI: The logging PR is merged (#176), and they introduced new deployments/statefulsets to the seed cluster's control plane. You might want to label those properly (`garden.sapcloud.io/role={controlplane,logging,monitoring}`).

**Comment by adracus** [comment]
@rfranzke Regarding logging this seems rather difficult to me: Logging is only deployed during seed-bootstrap and is not part of any of seed-controlplane / shoot-core / shoot-addons... Isn't it then rather something that's relevant for a seed health check? If possible, let's keep this change small, it already has grown quite big.

**Comment by rfranzke** [comment]
The logging stack is once deployed per seed in the seed bootstrapping phase, and once at the end of each shoot reconcile flow: https://github.com/gardener/gardener/blob/master/pkg/controller/shoot/shoot_control_reconcile.go#L201-L205
The chart, however, does only exist once in seed-bootstrap because it's identical.
You can treat the logging stack similar to the monitoring stack in the shoot namespace in the seed.

**Comment by adracus** [comment]
@rfranzke I did the changes in the same way as for monitoring.

File: charts/shoot-addons/charts/helm-tiller/templates/helm-tiller.yaml [hunk 19]
```diff
@@ -33,6 +33,7 @@ apiVersion: {{ include "deploymentversion" . }}
 kind: Deployment
 metadata:
   labels:
+    garden.sapcloud.io/role: optional-addon
```
Comment (rfranzke) [inline charts/shoot-addons/charts/helm-tiller/templates/helm-tiller.yaml:36]: This should be added to `.spec.template.metadata.labels` as well.

File: charts/seed-bootstrap/charts/fluentd-es/values.yaml [hunk 20]
```diff
@@ -9,9 +9,11 @@ fluentd:
   ports:
     forward: 24224
   labels:
+    garden.sapcloud.io/role: logging
     app: fluentd-es
     role: logging
 fluentbit:
   labels:
+    garden.sapcloud.io/role: logging
```
Comment (rfranzke) [inline charts/seed-bootstrap/charts/fluentd-es/values.yaml:17]: What about the labels for the curator `CronJob`s?

File: pkg/controller/shoot/shoot_care_control.go [hunk 21]
```diff
@@ -127,41 +113,36 @@ func (c *defaultCareControl) Care(shootObj *gardenv1beta1.Shoot, key string) err
...
+
+		_, err := c.updateShootConditions(shoot, *conditionControlPlaneHealthy, *conditionEveryNodeReady, *conditionSystemComponentsHealthy)
+		return err
 	}
+
 	if err := botanist.InitializeShootClients(); err != nil {
 		message := fmt.Sprintf("Failed to create a K8SClient for the Shoot cluster to perform the care operations (%s).", err.Error())
-		conditionEveryNodeReady = helper.ModifyCondition(conditionEveryNodeReady, corev1.ConditionUnknown, gardenv1beta1.ConditionCheckError, message)
-		conditionSystemComponentsHealthy = helper.ModifyCondition(conditionSystemComponentsHealthy, corev1.ConditionUnknown, gardenv1beta1.ConditionCheckError, message)
+		conditionControlPlaneHealthy = helper.UpdatedConditionUnknownErrorMessage(conditionControlPlaneHealthy, message)
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_care_control.go]: If `InitializeShootClients` we could have checked this condition, right? There are no dependencies to the shoot API server (other than its `/healthz` endpoint)? What do you think?

File: pkg/controller/shoot/shoot_control_reconcile.go [hunk 22]
```diff
@@ -313,36 +319,45 @@ func (c *defaultControl) updateShootStatusReconcileError(o *operation.Operation,
 		description   = lastError.Description
 		lastOperation = o.Shoot.Info.Status.LastOperation
 		progress      = 1
+		willRetry     = utils.TimeElapsed(o.Shoot.Info.Status.RetryCycleStartTime, c.config.Controllers.Shoot.RetryDuration.Duration)
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_control_reconcile.go]: Shouldn't this be 
```suggestion
		willNotRetry     = utils.TimeElapsed(o.Shoot.Info.Status.RetryCycleStartTime, c.config.Controllers.Shoot.RetryDuration.Duration)
```

or

```suggestion
		willRetry     = !utils.TimeElapsed(o.Shoot.Info.Status.RetryCycleStartTime, c.config.Controllers.Shoot.RetryDuration.Duration)
```

File: pkg/controller/shoot/shoot_control_reconcile.go [hunk 23]
```diff
@@ -313,36 +319,45 @@ func (c *defaultControl) updateShootStatusReconcileError(o *operation.Operation,
...
 	)
 
-	if !utils.TimeElapsed(o.Shoot.Info.Status.RetryCycleStartTime, c.config.Controllers.Shoot.RetryDuration.Duration) {
-		description += " Operation will be retried."
+	if willRetry {
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_control_reconcile.go]: Why do we have that compared to line `333`?

File: pkg/controller/shoot/shoot_maintenance_control.go [hunk 24]
```diff
@@ -176,40 +177,58 @@ func (c *defaultMaintenanceControl) Maintain(shootObj *gardenv1beta1.Shoot, key
...
 		}
 	}
 
-	// Remove operation annotation.
-	delete(shoot.Annotations, common.ShootOperation)
-
 	// Update the Shoot resource object.
-	if _, err := c.updater.UpdateShoot(shoot); err != nil {
+	_, err = kutil.TryUpdateShoot(c.k8sGardenClient.GardenClientset(), retry.DefaultBackoff, shoot.ObjectMeta, func(s *gardenv1beta1.Shoot) (*gardenv1beta1.Shoot, error) {
+		if !apiequality.Semantic.DeepEqual(shootObj.Spec.Maintenance.AutoUpdate, s.Spec.Maintenance.AutoUpdate) {
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_maintenance_control.go:214]: nice!

File: pkg/controller/shoot/shoot_maintenance_control.go [hunk 25]
```diff
@@ -176,40 +177,58 @@ func (c *defaultMaintenanceControl) Maintain(shootObj *gardenv1beta1.Shoot, key
...
+			return nil, fmt.Errorf("auto update section of Shoot %s/%s changed mid-air", s.Namespace, s.Name)
+		}
+
+		if annotations := shoot.Annotations; annotations != nil {
+			if v, ok := annotations[common.ShootOperation]; ok && v == common.ShootOperationMaintain {
```
Comment (rfranzke) [inline pkg/controller/shoot/shoot_maintenance_control.go]: Both checks are unneeded, right? Can't we keep it as it was?
```golang
  delete(shoot.Annotations, common.ShootOperation)
```

File: pkg/utils/kubernetes/health/health.go [hunk 26]
```diff
@@ -0,0 +1,262 @@
...
+		appsv1.DeploymentReplicaFailure,
+	}
+)
+
+// CheckDeployment checks whether the given Deployment is healthy.
+// A deployment is considered healthy if the controller observed its current revision and
+// if the number of updated replicas is equal to the number of replicas.
+func CheckDeployment(deployment *appsv1.Deployment) error {
+	if deployment.Status.ObservedGeneration < deployment.Generation {
+		return fmt.Errorf("observed generation outdated (%d/%d)", deployment.Status.ObservedGeneration, deployment.Generation)
```
Comment (rfranzke) [inline pkg/utils/kubernetes/health/health.go:83]: Should we have a more user-friendly message here? Something like "Deployment will be updated" or "Deployment update processing" or something similar?

Comment (rfranzke) [reply pkg/utils/kubernetes/health/health.go:83]: (same for the other occurrences)

File: pkg/operation/botanist/health_check.go [hunk 27]
```diff
@@ -16,172 +16,422 @@ package botanist
...
+	// This is a hack to quickly do a cloud provider specific check for the required control plane deployments.
+	// As this will anyways change with the Gardener extensibility, for now, this will check for the only
+	// cloud provider where it differs (AWS). Once cloud provider specific code moves out, this will also have to
+	// be refactored / re-aligned.
+	requiredControlPlaneDeployments := sets.NewString(common.RequiredControlPlaneDeployments.UnsortedList()...)
+	if b.Shoot.CloudProvider == gardenv1beta1.CloudProviderAWS {
+		requiredControlPlaneDeployments.Insert(common.AWSLBReadvertiserDeploymentName)
+	}
+	if addons := b.Shoot.Info.Spec.Addons; addons != nil {
+		if clusterAutoscaler := addons.ClusterAutoscaler; clusterAutoscaler != nil && clusterAutoscaler.Enabled {
```
Comment (rfranzke) [inline pkg/operation/botanist/health_check.go]: This field is deprecated and will be removed in the future.
Better depend on `b.Shoot.WantsAutoscaler`

File: pkg/operation/botanist/health_check.go [hunk 28]
```diff
@@ -16,172 +16,422 @@ package botanist
...
+	}
+
+	if exitCondition := checkRequiredStatefulSets(condition, common.RequiredLoggingStatefulSets, statefulSetList.Items); exitCondition != nil {
+		return exitCondition, nil
+	}
+	if exitCondition := checkStatefulSets(condition, statefulSetList.Items); exitCondition != nil {
+		return exitCondition, nil
+	}
+
+	daemonSetList, err := b.K8sSeedClient.ListDaemonSets(b.Shoot.SeedNamespace, loggingListOptions)
```
Comment (rfranzke) [inline pkg/operation/botanist/health_check.go]: I see a lot of `List{Deployments,StatefulSets,DaemonSets}` calls in this file (though, with different list options/label selectors, but still). Can we please reduce this to exactly ONE `ListDeployments`, `ListStatefulSets`, `ListDaemonSets` call and filter ourselves on the wanted object in the individual functions?

**Review by rfranzke — CHANGES_REQUESTED** [review]
Cool, thank you! PTAL at a few code-wise suggestions before doing another test run in action.

File: pkg/utils/kubernetes/health/health.go (hunk 26 above)
Comment (adracus) [reply pkg/utils/kubernetes/health/health.go:83]: Check `checkRequiredDeployments` or `checkDeployments`: The user message is being made more friendly by prefixing the affected k8s object's name.
Also, by my current design, the health checks should only print the issues with the object but not the objects name itself.

**Review by rfranzke — APPROVED** [review]
/lgtm
