### PR TITLE
Resolve conflict when configuring anonymous authentication

### LINKED ISSUE #12191: Flag `--anonymous-auth` conflicts with anonymous authentication in `AuthenticationConfig`
**How to categorize this issue?**

/area security 
/kind bug

**What happened**:
I tried [enabling anonymous authentication via AuthenticationConfig](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#anonymous-authenticator-configuration) in order to create a PoC for what is requested in https://github.com/gardener/gardener/issues/12189, however because the flag `--anonymous-auth` and anonymous authentication via `AuthenticationConfig` are mutually exclusive the `kube-apiserver` did not start successfully.

```
E0527 08:17:59.371126       1 run.go:72] "command failed" err="anonymous: Forbidden: --anonynous-auth flag cannot be set when anonymous field is configured in authentication configuration file"
```

The `--anonymous-auth` flag [should not be set unconditionally](https://github.com/gardener/gardener/blob/485c25124ea536e4610c627109017dd34d434921/pkg/component/kubernetes/apiserver/deployment.go#L392), but rather only when the `AuthenticationConfig` does not specify anonymous authentication configuration.

For clusters with k8s version >= 1.32 for which the `AnonymousAuthConfigurableEndpoints` is enabled we should not use the `--anonymous-auth` flag at all but rather translate it into `AuthenticationConfig` the same way we do with the `oidc` flags.

**What you expected to happen**:
A normal start of the `kube-apiserver`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**How to categorize this PR?**

/area security
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #12191

**Special notes for your reviewer**:

**Release note**:

```bugfix user
A bug causing the `kube-apiserver` to crash when anonymous authentication is configured via `StructuredAuthentication` was fixed.
```

### CODE REVIEW

File: pkg/component/kubernetes/apiserver/authentication.go [hunk 1]
```diff
@@ -44,90 +45,113 @@ func (k *kubeAPIServer) reconcileConfigMapAuthenticationConfig(ctx context.Conte
 		return errors.New("oidc configuration is incompatible with structured authentication")
 	}
 
-	if value, ok := k.values.FeatureGates["StructuredAuthenticationConfiguration"]; (ok && !value) ||
-		(k.values.AuthenticationConfiguration == nil && k.values.OIDC == nil) ||
+	var (
+		structAuthGateEnabled, structAuthGateSet  = k.values.FeatureGates["StructuredAuthenticationConfiguration"]
+		anonymousGateEnabled, anonymousGateSet    = k.values.FeatureGates["AnonymousAuthConfigurableEndpoints"]
+		shouldConfigureAnonymousViaStructuredAuth = (!anonymousGateSet || (anonymousGateSet && anonymousGateEnabled)) && versionutils.ConstraintK8sGreaterEqual132.Check(k.values.Version)
```
Comment (timuthy) [inline pkg/component/kubernetes/apiserver/authentication.go]:
```suggestion
		shouldConfigureAnonymousViaStructuredAuth = (!anonymousGateSet || anonymousGateEnabled) && versionutils.ConstraintK8sGreaterEqual132.Check(k.values.Version)
```

Nit, to increase readability.

File: pkg/component/kubernetes/apiserver/authentication.go [hunk 2]
```diff
@@ -44,90 +45,113 @@ func (k *kubeAPIServer) reconcileConfigMapAuthenticationConfig(ctx context.Conte
...
 
 func (k *kubeAPIServer) handleAuthenticationSettings(deployment *appsv1.Deployment, configMapAuthenticationConfig *corev1.ConfigMap, secretOIDCCABundle *corev1.Secret) {
 	if value, ok := k.values.FeatureGates["StructuredAuthenticationConfiguration"]; versionutils.ConstraintK8sLess130.Check(k.values.Version) || (ok && !value) {
 		k.handleOIDCSettings(deployment, secretOIDCCABundle)
-		return
+	}
+
+	var (
+		anonymousGateEnabled, anonymousGateSet    = k.values.FeatureGates["AnonymousAuthConfigurableEndpoints"]
+		shouldConfigureAnonymousViaStructuredAuth = (!anonymousGateSet || (anonymousGateSet && anonymousGateEnabled)) && versionutils.ConstraintK8sGreaterEqual132.Check(k.values.Version)
```
Comment (timuthy) [inline pkg/component/kubernetes/apiserver/authentication.go]:
```suggestion
		shouldConfigureAnonymousViaStructuredAuth = (!anonymousGateSet || anonymousGateEnabled) && versionutils.ConstraintK8sGreaterEqual132.Check(k.values.Version)
```

Nit

File: pkg/component/kubernetes/apiserver/authentication.go [hunk 3]
```diff
@@ -44,90 +45,113 @@ func (k *kubeAPIServer) reconcileConfigMapAuthenticationConfig(ctx context.Conte
...
+	)
+
+	if !shouldConfigureAnonymousViaStructuredAuth {
```
Comment (timuthy) [inline pkg/component/kubernetes/apiserver/authentication.go]:
```suggestion
	if !shouldConfigureAnonymousViaStructuredAuth && !structAuthGateEnabled {
```

Should the `StructuredAuthenticationConfiguration` be checked here as well?

**Review by timuthy — COMMENTED** [review]
Thanks for the fix 🚀

File: pkg/component/kubernetes/apiserver/authentication.go (hunk 3 above)
Comment (dimityrmirchev) [reply pkg/component/kubernetes/apiserver/authentication.go]: Thanks for reviewing @timuthy. Those are some tricky statements. Should be addressed with https://github.com/gardener/gardener/pull/12198/commits/b5ef554ac615e8fc52fcbd259ec0b3a72eba2ff2

Mind that my additional check looks a bit different, but I think it should be correct

File: pkg/component/kubernetes/apiserver/authentication.go [hunk 4]
```diff
@@ -44,90 +45,115 @@ func (k *kubeAPIServer) reconcileConfigMapAuthenticationConfig(ctx context.Conte
...
+		shouldConfigureAnonymousViaStructuredAuth = (!anonymousGateSet || anonymousGateEnabled) && versionutils.ConstraintK8sGreaterEqual132.Check(k.values.Version)
+	)
+
+	if versionutils.ConstraintK8sLess130.Check(k.values.Version) || structAuthIsDisabled {
 		k.handleOIDCSettings(deployment, secretOIDCCABundle)
-		return
+	}
+
+	if !shouldConfigureAnonymousViaStructuredAuth || structAuthIsDisabled {
+		deployment.Spec.Template.Spec.Containers[0].Args = append(deployment.Spec.Template.Spec.Containers[0].Args, "--anonymous-auth="+strconv.FormatBool(ptr.Deref(k.values.AnonymousAuthenticationEnabled, false)))
```
Comment (timuthy) [inline pkg/component/kubernetes/apiserver/authentication.go:159]: IIUC, this flag would be set for `1.31` clusters that configure anonymous-auth via the `AuthenticationConfiguration`. Can you double check? WDYT adding a test for this scenario as well?

**Review by timuthy — COMMENTED** [review]
Thanks for addressing my comments. 

As you said, the conditions are quite intricate and after another iteration I might found an unwanted result. Let me know what you think 🙂

File: pkg/component/kubernetes/apiserver/authentication.go (hunk 4 above)
Comment (dimityrmirchev) [reply pkg/component/kubernetes/apiserver/authentication.go:159]: You are right! I now do a more practical check https://github.com/gardener/gardener/pull/12198/commits/574b089e85e82ae75034de463f88a5978f92dc85 which I think works better. PTAL

**Review by timuthy — COMMENTED** [review]
/lgtm
Leaving approval up you @ialidzhikov

**Comment by ialidzhikov** [comment]
> Leaving approval up you @ialidzhikov

Thanks! And sorry for the delay! Let me build some context and try to provide feedback! :)

File: pkg/component/kubernetes/apiserver/authentication.go [hunk 5]
```diff
@@ -44,94 +45,133 @@ func (k *kubeAPIServer) reconcileConfigMapAuthenticationConfig(ctx context.Conte
 		return errors.New("oidc configuration is incompatible with structured authentication")
 	}
 
-	if value, ok := k.values.FeatureGates["StructuredAuthenticationConfiguration"]; (ok && !value) ||
-		(k.values.AuthenticationConfiguration == nil && k.values.OIDC == nil) ||
+	var (
+		structAuthGateEnabled, structAuthGateSet  = k.values.FeatureGates["StructuredAuthenticationConfiguration"]
```
Comment (ialidzhikov) [inline pkg/component/kubernetes/apiserver/authentication.go]: Shouldn't we have a func like:

```go
func (k *kubeAPIServer) structuredAuthenticationFeatureGateEnabled() bool {
	if versionutils.ConstraintK8sLess130.Check(k.values.Version) {
		return false
	}

	featureGateEnabled, featureGateSet := k.values.FeatureGates["StructuredAuthenticationConfiguration"]
	if featureGateSet {
		return featureGateEnabled
	}

	if versionutils.ConstraintK8sGreaterEqual132.Check(k.values.Version) {
		return true
	}

	return false
}
```

to decice if the StructuredAuthenticationConfiguration feature gate is enabled or not? Here we are only checking if the feature gate is explicitly specified. Shouldn't we consider also the cases where the feature gate is enabled by default (K8s 1.32+)?

It looks like in many places we such logic if the StructureAuthenticationConfiguration feature gate is effectively enabled:
- https://github.com/gardener/gardener/blob/485c25124ea536e4610c627109017dd34d434921/pkg/component/kubernetes/apiserver/secrets.go#L55-L57
- https://github.com/gardener/gardener/blob/574b089e85e82ae75034de463f88a5978f92dc85/pkg/component/kubernetes/apiserver/authentication.go#L145

Can we adapt all of them to use a single func?

File: pkg/component/kubernetes/apiserver/authentication.go [hunk 6]
```diff
@@ -44,94 +45,133 @@ func (k *kubeAPIServer) reconcileConfigMapAuthenticationConfig(ctx context.Conte
...
+		anonymousGateEnabled, anonymousGateSet    = k.values.FeatureGates["AnonymousAuthConfigurableEndpoints"]
```
Comment (ialidzhikov) [inline pkg/component/kubernetes/apiserver/authentication.go]: Similar comment: Shouldn't we have a func like `structuredAuthenticationFeatureGateEnabled` for this feature gate (`anonymousAuthConfigurableEndpointsFeatureGateEnabled`) and consider the K8s versions this feature gate is enabled by default?

File: pkg/component/kubernetes/apiserver/authentication.go [hunk 7]
```diff
@@ -44,94 +45,133 @@ func (k *kubeAPIServer) reconcileConfigMapAuthenticationConfig(ctx context.Conte
...
+		shouldConfigureAnonymousViaStructuredAuth = (!anonymousGateSet || anonymousGateEnabled) && versionutils.ConstraintK8sGreaterEqual132.Check(k.values.Version)
+	)
+
+	if (structAuthGateSet && !structAuthGateEnabled) ||
+		(k.values.AuthenticationConfiguration == nil && k.values.OIDC == nil && !shouldConfigureAnonymousViaStructuredAuth) ||
 		versionutils.ConstraintK8sLess130.Check(k.values.Version) {
```
Comment (ialidzhikov) [inline pkg/component/kubernetes/apiserver/authentication.go]: Maybe this if statement can be simplified by having helper funcs like `structuredAuthenticationFeatureGateEnabled ` and `anonymousAuthConfigurableEndpointsFeatureGateEnabled`?
Otherwise I cannot easily follow the logic in this if statement.

File: pkg/component/kubernetes/apiserver/authentication.go [hunk 8]
```diff
@@ -44,94 +45,133 @@ func (k *kubeAPIServer) reconcileConfigMapAuthenticationConfig(ctx context.Conte
...
-func (k *kubeAPIServer) handleAuthenticationSettings(deployment *appsv1.Deployment, configMapAuthenticationConfig *corev1.ConfigMap, secretOIDCCABundle *corev1.Secret) {
-	if value, ok := k.values.FeatureGates["StructuredAuthenticationConfiguration"]; versionutils.ConstraintK8sLess130.Check(k.values.Version) || (ok && !value) {
+func (k *kubeAPIServer) handleAuthenticationSettings(deployment *appsv1.Deployment, configMapAuthenticationConfig *corev1.ConfigMap, secretOIDCCABundle *corev1.Secret) error {
+	var (
+		structAuthGateEnabled, structAuthGateSet    = k.values.FeatureGates["StructuredAuthenticationConfiguration"]
+		structAuthIsDisabled                        = (structAuthGateSet && !structAuthGateEnabled)
+		structAuthConfiguresAnonymousAuthentication bool
+	)
+
+	if versionutils.ConstraintK8sLess130.Check(k.values.Version) || structAuthIsDisabled {
```
Comment (ialidzhikov) [inline pkg/component/kubernetes/apiserver/authentication.go]: This looks like a great candidate to be replaced by the `structuredAuthenticationFeatureGateEnabled` func.

**Review by ialidzhikov — COMMENTED** [review]
I am posting some preliminary comments. I will finish the review in the next days.

**Comment by dimityrmirchev** [comment]
Thanks for reviewing @ialidzhikov ! The initial comments should be addressed.

**Review by timuthy — COMMENTED** [review]
Looks good, thanks for the simplification 🙂 
/lgtm

**Comment by ialidzhikov** [comment]
The [pull-gardener-e2e-kind-operator-seed](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/12198/pull-gardener-e2e-kind-operator-seed/1930624289451544576) failure is occurrence of https://github.com/gardener/gardener/issues/12279.

/test pull-gardener-e2e-kind-operator-seed

File: pkg/component/kubernetes/apiserver/authentication.go [hunk 9]
```diff
@@ -251,3 +240,29 @@ func (k *kubeAPIServer) handleOIDCSettings(deployment *appsv1.Deployment, secret
...
+	featureGateEnabled, featureGateSet := k.values.FeatureGates["StructuredAuthenticationConfiguration"]
+	if featureGateSet {
+		return featureGateEnabled
+	}
+
+	return true
+}
+
+func (k *kubeAPIServer) anonymousAuthConfigurableEndpointsFeatureGateEnabled() bool {
+	if !versionutils.ConstraintK8sGreaterEqual132.Check(k.values.Version) {
```
Comment (ialidzhikov) [inline pkg/component/kubernetes/apiserver/authentication.go]: I was initially confused why we don't allow `StructuredAuthenticationConfiguration` to be enabled for K8s 1.29 where the feature gate is alpha. Ref https://github.com/kubernetes/kubernetes/blob/v1.33.0/pkg/features/kube_features.go

I asked @AleksandarSavchev about it and he couldn't explain why we decided `StructuredAuthenticationConfiguration` to be enabled only for K8s >= 1.30 although the feature gate is introduced as alpha in K8s 1.29.

`AnonymousAuthConfigurableEndpoints ` is introduced as alpha in K8s 1.31 and is promoted to beta (and enabled by default) in K8s 1.32. Shouldn't this check be for K8s < 1.31? And we would need to have another if statement for the version in which the feature gate is enabled as beta. Otherwise, one could enable the `AnonymousAuthConfigurableEndpoints` feature explicitly  for K8s 1.31 and this func will return false in that case.

I don't suggest to change the version constraints for `StructuredAuthenticationConfiguration`. But maybe we could do it better for `StructuredAuthenticationConfiguration`?

Let me know if I am missing something obvious.

**Review by ialidzhikov — COMMENTED** [review]
Final comment, otherwise lgtm

File: pkg/component/kubernetes/apiserver/authentication.go (hunk 9 above)
Comment (dimityrmirchev) [reply pkg/component/kubernetes/apiserver/authentication.go]: > I asked @AleksandarSavchev about it and he couldn't explain why we decided StructuredAuthenticationConfiguration to be enabled only for K8s >= 1.30 although the feature gate is introduced as alpha in K8s 1.29.

This was a conscious decision. As the introduction of structured authentication was related to a migration we wanted to introduce the feature only when no more api changes were expected + it was simpler this way as we skipped checks for < 1.30 and immediately started using it for clusters >= 1.30 as beta features are expected to be well tested already.

> AnonymousAuthConfigurableEndpoints  is introduced as alpha in K8s 1.31 and is promoted to beta (and enabled by default) in K8s 1.32. Shouldn't this check be for K8s < 1.31? And we would need to have another if statement for the version in which the feature gate is enabled as beta. Otherwise, one could enable the AnonymousAuthConfigurableEndpoints feature explicitly for K8s 1.31 and this func will return false in that case.

Sure, I will add the extra case.

**Review by ialidzhikov — APPROVED** [review]
/lgtm
