### PR TITLE
Fix race condition leading to `Pod`s without any projected token volumes

### LINKED ISSUE #5530: Nginx Ingress Controller misses projected volume
**How to categorize this issue?**

/area security
/kind bug

**What happened**:
The Nginx Ingress Controller pod crash looped because it cannot connect to the Kube-Apiserver:

```
F0307 12:43:19.843203       7 main.go:299] Error while initiating a connection to the Kubernetes API server. This could mean the cluster is misconfigured (e.g. it has invalid API server certificates or Service Accounts configuration). Reason: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
Refer to the troubleshooting guide for more information: https://kubernetes.github.io/ingress-nginx/troubleshooting/
```

**What you expected to happen**:
The Nginx Ingress Controller to work.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new shoot with Nginx Ingress Addon enabled. This is a race, so the issue does not happen every time.

**Anything else we need to know?**:
The Nginx Ingress Controller pod misses the required projected volume to be able to connect to the Kube-Apiserver.

- Creation timestamps:
  - Nginx Pod: creationTimestamp: `"2022-03-07T04:17:12Z"`
  - MutatingWebhookConfiguration: creationTimestamp: `"2022-03-07T04:16:44Z"`

After deleting the pod, the new Nginx Controller pod receives the necessary updates from the webhook:

image

**Environment**:

- Gardener version: `v1.41.1`

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind bug

**What this PR does / why we need it**:
As explained in https://github.com/gardener/gardener/issues/5530#issuecomment-1063840390, there is a race condition for newly created shoots which can lead to pods without any projected token volumes.

This PR fixes the issue by first deploying the `namespaces` component (responsible for labelling the `kube-system` namespace), waiting for its successful reconciliation, and only afterwards deploying the system components and addons.

On the way I fixed the logging for the webhook handlers in GRM since in some cases they don't contain valuable information.

**Which issue(s) this PR fixes**:
Fixes #5530

**Release note**:

```bugfix user
A race condition has been fixed which can lead to pods without any projected token volumes for newly created shoots.
```

### CODE REVIEW

File: pkg/utils/kubernetes/kubernetes.go [hunk 1]
```diff
@@ -657,3 +657,18 @@ func NewKubeconfig(contextName, server string, caCert []byte, authInfo clientcmd
 		}},
 	}
 }
+
+// ObjectKeyForCreateWebhooks creates an object key for an object handled by webhooks registered for CREATE verbs.
+func ObjectKeyForCreateWebhooks(obj client.Object) client.ObjectKey {
+	namespace := obj.GetNamespace()
+	if len(namespace) == 0 {
+		namespace = "default"
```
Comment (ialidzhikov) [inline pkg/utils/kubernetes/kubernetes.go]:
```suggestion
		namespace = metav1.NamespaceDefault
```

**Review by ialidzhikov — COMMENTED** [review]
Minor nit, otherwise lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/squash
