### PR TITLE
Set operation annotation when scaling etcd

### LINKED ISSUE #5188: gardenlet does not wait for `Etcd`s to be scaled down in hibernation flow
**How to categorize this issue?**

/area cost
/kind bug

**What happened**:

Shoot was hibernated, but the etcd pods remained in the shoot's control plane:
```
$ k get etcd,sts
NAME                                    READY   AGE
etcd.druid.gardener.cloud/etcd-events   true    75m
etcd.druid.gardener.cloud/etcd-main     true    75m

NAME                           READY   AGE
statefulset.apps/etcd-events   1/1     75m
statefulset.apps/etcd-main     1/1     75m

$ k get etcd etcd-main -oyaml
metadata:
  generation: 2
spec:
  replicas: 0
status:
  clusterSize: 1
  conditions:
  - lastTransitionTime: "2021-12-20T09:24:55Z"
    lastUpdateTime: "2021-12-20T10:54:14Z"
    message: Cannot determine readiness since status has no members
    reason: NoMembersInStatus
    status: Unknown
    type: AllMembersReady
  - lastTransitionTime: "2021-12-20T09:24:55Z"
    lastUpdateTime: "2021-12-20T10:54:14Z"
    message: Cannot determine readiness since status has no members
    reason: NoMembersInStatus
    status: Unknown
    type: Ready
  currentReplicas: 1
  etcd:
    apiVersion: apps/v1
    kind: StatefulSet
    name: etcd-main
  observedGeneration: 1
  ready: true
  readyReplicas: 1
  serviceName: etcd-main-client
  updatedReplicas: 1
```

**What you expected to happen**:

- etcd statefulsets should be scaled down during hibernation. However, that seems to be an etcd-druid issue, as gardenlet correctly manipulated the `Etcd` resource as expected. Only mentioning it here for completeness and as a cause for another bug on gardenlet side.
- gardenlet should make sure, `Etcd` objects are reconciled when hibernating the shoot, so that the hibernation is retried in case it fails for some reasons (e.g. because of such a problem with etcd-druid)

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce gardenlet's part of the issue:

1. Create a shoot
2. Scale down `etcd-druid` and make sure, it doesn't act upon changes in `Etcd` objects
2. Hibernate the shoot
3. Make sure, `Etcd` objects specify `spec.replicas=0` but are not "ready" (e.g. `observedGeneration` outdated)
4. Observe, that the shoot is hibernated successfully, although etcd pods still remain

**Anything else we need to know?**:

Waiting for etcds is simply skipped during hibernation: https://github.com/gardener/gardener/blob/6d2c84080d9c05f3432cd626c0114fa04e8d12b0/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L261-L265

I'm wondering if there is a particular reason for it and whether we could not skip it. Hence, opening this issue for discussion.

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR adds the `gardener.cloud/operation: reconcile` annotation to `etcd` when scaling the resource (during hibernation and when deleting hibernated clusters).

**Which issue(s) this PR fixes**:
Fixes #5188

**Special notes for your reviewer**:
We can still discuss if it makes sense to wait for the `etcd` resource although we don't wait for anything when we hibernate the control plane, so I decided to not do it in this PR either. Doing it as a "best effort" should still be enough in my opinion.

**Release note**:

```bugfix operator
A bug has been fixed that caused `etcd` pods still to be active in the control plane even though the cluster was hibernated successfully.  
```

### CODE REVIEW

**Review by shreyas-s-rao — DISMISSED** [review]
@timuthy Thanks for the investigation and quick fix! Looks like the etcd resource was being scaled without reconcile annotation all these days, but became an issue post the fix in https://github.com/gardener/etcd-druid/pull/202

File: pkg/client/kubernetes/scaling.go [hunk 1]
```diff
@@ -49,7 +50,19 @@ func ScaleEtcd(ctx context.Context, c client.Client, key client.ObjectKey, repli
...
+	if err := c.Get(ctx, key, etcd); err != nil {
+		return err
+	}
+
+	patch := client.MergeFrom(etcd.DeepCopy())
+	if etcd.Annotations == nil {
+		etcd.SetAnnotations(make(map[string]string))
+	}
+
+	etcd.Annotations[gardencorev1beta1constants.GardenerOperation] = gardencorev1beta1constants.GardenerOperationReconcile
```
Comment (rfranzke) [inline pkg/client/kubernetes/scaling.go]: Should we also set the timestamp annotation here (since we usually do this when setting the operation annotation)?

Comment (timuthy) [reply pkg/client/kubernetes/scaling.go]: Thanks, done in 9272e4811c4deee1425e205f47b4f31b80c3a2b9.

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by timuthy** [comment]
I missed to push a missing test file @rfranzke and corrected it in 9272e4811c4deee1425e205f47b4f31b80c3a2b9.

**Review by rfranzke — APPROVED** [review]
