### PR TITLE
Prevent panic in gardenlet when shoot namespace doesn't have required project label

### LINKED ISSUE #6286: gardenlet panics when Shoot is created in a Namespace that does not have the Project labels
**How to categorize this issue?**
/area quality
/kind bug

**What happened**:
gardenlet panics when Shoot is created in a Namespace that does not have the Project labels

**What you expected to happen**:
No panic.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a ns `garden-test` without Project labels

```
$ k create ns garden-test
```

2. Create the following Project that uses this namespace

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Project
metadata:
  name: test
spec:
  owner:
    apiGroup: rbac.authorization.k8s.io
    kind: User
    name: john.doe@example.com
  namespace: garden-test
```

3. Make sure the Project is failed with reason:

```
Events:
  Type     Reason                    Age                   From                         Message
  ----     ------                    ----                  ----                         -------
  Warning  NamespaceReconcileFailed  39s (x16 over 3m14s)  gardener-controller-manager  namespace cannot be used as it needs the project labels map[string]string{"gardener.cloud/role":"project", "project.gardener.cloud/name":"test"}
```

4. Create a Shoot in the `garden-test` Namespace

5. Make sure gardenlet panics with the following:
```
E0707 09:22:59.235847       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1310 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x20699e0?, 0x3a51540})
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc019ffa640?})
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x20699e0, 0x3a51540})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/gardener/gardener/pkg/operation.(*Builder).WithShootFromCluster.func1({0x27aef90, 0xc01a0f2900}, {0x7fce69129428, 0xc00004dca0}, 0xc01b8b6ff0, 0xc01c202480)
	/go/src/github.com/gardener/gardener/pkg/operation/operation.go:171 +0x86
github.com/gardener/gardener/pkg/operation.(*Builder).Build(0xc01b4ec320, {0x27aef90, 0xc01a0f2900}, {0x279ecd0?, 0xc000aee7c0})
	/go/src/github.com/gardener/gardener/pkg/operation/operation.go:273 +0x509
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.glob..func5({0x27aef90, 0xc01a0f2900}, {0x27b9a40, 0xc0003ee6e0}, {0x27b9a40, 0xc000456210}, 0xc0004b03c0, 0xc000954cf0, {0xc0007eb0c8, 0x11}, ...)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_care_control_types.go:132 +0x397
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.(*careReconciler).care(0xc00be7c240, {0x27aef20, 0xc000bd4a80}, {0x27b9a40, 0xc0003ee6e0}, 0xc01a0f7000, {0x27bd8f0?, 0xc01a08a620?})
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_care_control.go:283 +0x84b
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.(*careReconciler).Reconcile(0xc00be7c240, {0x27aef20, 0xc000bd4a80}, {{{0xc019ff4480?, 0x0?}, {0xc019ff448c?, 0x40bb94?}}})
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_care_control.go:214 +0x275
github.com/gardener/gardener/pkg/controllerutils.worker.func1({0x27b8f00, 0xc00be76460}, {{0x0?, 0x0?}, 0xc01aa72ae0?}, {0x27aef20, 0xc000bd4a80}, {0x278b700, 0xc00be7c240}, {0x238c2ce, ...})
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:122 +0x493
github.com/gardener/gardener/pkg/controllerutils.worker({0x27aef20, 0xc000bd4a80}, {0x27b8f00, 0xc00be76460}, {0x238c2ce, 0xa}, {0x278b700, 0xc00be7c240}, {{{0x0, 0x0}, ...}})
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:145 +0x8e
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func1.1({0x27aef20?, 0xc000bd4a80?})
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:64 +0x58
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:188 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x3?)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1?, {0x278e660, 0xc01a0816b0}, 0x1, 0xc0074505a0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00150c840?, 0x3b9aca00, 0x0, 0xe8?, 0xc000820300?)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x27aef20, 0xc000bd4a80}, 0xc000ecb790, 0xc0005282a0?, 0xc000820301?, 0x0?)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:188 +0x99
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func1()
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:63 +0xba
created by github.com/gardener/gardener/pkg/controllerutils.CreateWorker
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:62 +0x20a
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d1a1e6]

goroutine 1310 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc019ffa640?})
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd8
panic({0x20699e0, 0x3a51540})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/gardener/gardener/pkg/operation.(*Builder).WithShootFromCluster.func1({0x27aef90, 0xc01a0f2900}, {0x7fce69129428, 0xc00004dca0}, 0xc01b8b6ff0, 0xc01c202480)
	/go/src/github.com/gardener/gardener/pkg/operation/operation.go:171 +0x86
github.com/gardener/gardener/pkg/operation.(*Builder).Build(0xc01b4ec320, {0x27aef90, 0xc01a0f2900}, {0x279ecd0?, 0xc000aee7c0})
	/go/src/github.com/gardener/gardener/pkg/operation/operation.go:273 +0x509
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.glob..func5({0x27aef90, 0xc01a0f2900}, {0x27b9a40, 0xc0003ee6e0}, {0x27b9a40, 0xc000456210}, 0xc0004b03c0, 0xc000954cf0, {0xc0007eb0c8, 0x11}, ...)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_care_control_types.go:132 +0x397
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.(*careReconciler).care(0xc00be7c240, {0x27aef20, 0xc000bd4a80}, {0x27b9a40, 0xc0003ee6e0}, 0xc01a0f7000, {0x27bd8f0?, 0xc01a08a620?})
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_care_control.go:283 +0x84b
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.(*careReconciler).Reconcile(0xc00be7c240, {0x27aef20, 0xc000bd4a80}, {{{0xc019ff4480?, 0x0?}, {0xc019ff448c?, 0x40bb94?}}})
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_care_control.go:214 +0x275
github.com/gardener/gardener/pkg/controllerutils.worker.func1({0x27b8f00, 0xc00be76460}, {{0x0?, 0x0?}, 0xc01aa72ae0?}, {0x27aef20, 0xc000bd4a80}, {0x278b700, 0xc00be7c240}, {0x238c2ce, ...})
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:122 +0x493
github.com/gardener/gardener/pkg/controllerutils.worker({0x27aef20, 0xc000bd4a80}, {0x27b8f00, 0xc00be76460}, {0x238c2ce, 0xa}, {0x278b700, 0xc00be7c240}, {{{0x0, 0x0}, ...}})
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:145 +0x8e
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func1.1({0x27aef20?, 0xc000bd4a80?})
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:64 +0x58
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:188 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x3?)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1?, {0x278e660, 0xc01a0816b0}, 0x1, 0xc0074505a0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00150c840?, 0x3b9aca00, 0x0, 0xe8?, 0xc000820300?)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x27aef20, 0xc000bd4a80}, 0xc000ecb790, 0xc0005282a0?, 0xc000820301?, 0x0?)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:188 +0x99
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func1()
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:63 +0xba
created by github.com/gardener/gardener/pkg/controllerutils.CreateWorker
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:62 +0x20a
```

**Anything else we need to know?**:
Usually end users don't have rights to create Namespaces. But it will be still nice to safe-guard against similar cases.

**Environment**:

- Gardener version: v1.50.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
Before #4040 we used `ProjectForNamespaceFromReader ` which returns an `error` if the project is not found but with #4040 we switched it to  `ProjectAndNamespaceFromReader` which if the project is not found doesn't return an error and the project is set to nil. Which causes panic in gardenlet because it tries to fetch the project name from nil value.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/6286

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
A bug causing `gardenlet` to panic in case of shoot using namespace which doesn't have the required project label is fixed.
```

### CODE REVIEW

File: pkg/utils/gardener/project.go [hunk 1]
```diff
@@ -46,13 +47,35 @@ func ProjectForNamespaceFromReader(ctx context.Context, reader client.Reader, na
...
+// fetches the project name label. Then it will read the project with the respective name and returns error if there is no
+// project for given namespace.
 func ProjectAndNamespaceFromReader(ctx context.Context, reader client.Reader, namespaceName string) (*gardencorev1beta1.Project, *corev1.Namespace, error) {
 	namespace := &corev1.Namespace{}
 	if err := reader.Get(ctx, kutil.Key(namespaceName), namespace); err != nil {
 		return nil, nil, err
 	}
 
+	projectName := namespace.Labels[v1beta1constants.ProjectName]
+	if projectName == "" {
```
Comment (shafeeqes) [inline pkg/utils/gardener/project.go]:
```suggestion
	projectName, ok := namespace.Labels[v1beta1constants.ProjectName]
	if !ok {
```

File: pkg/utils/gardener/project.go [hunk 2]
```diff
@@ -46,13 +47,35 @@ func ProjectForNamespaceFromReader(ctx context.Context, reader client.Reader, na
 }
 
 // ProjectAndNamespaceFromReader returns the Project responsible for a given <namespace>. It reads the namespace and
-// fetches the project name label. Then it will read the project with the respective name.
+// fetches the project name label. Then it will read the project with the respective name and returns error if there is no
+// project for given namespace.
```
Comment (shafeeqes) [inline pkg/utils/gardener/project.go]:
```suggestion
// fetches the project name label. Then it will read the project with the respective name or returns an error if there is no
// project for the given namespace.
```

File: pkg/utils/gardener/project.go [hunk 3]
```diff
@@ -46,15 +47,37 @@ func ProjectForNamespaceFromReader(ctx context.Context, reader client.Reader, na
...
+	if err := reader.Get(ctx, kutil.Key(projectName), project); err != nil {
+		return nil, namespace, err
+	}
+
+	return project, namespace, nil
+}
+
+// NamespaceBelongsToAnyProject returns the Project responsible for a given <namespace>. It reads the namespace and
+// fetches the project name label. Then it will read the project with the respective name.
+func NamespaceBelongsToAnyProject(ctx context.Context, reader client.Reader, namespaceName string) (*gardencorev1beta1.Project, *corev1.Namespace, error) {
```
Comment (timebertt) [inline pkg/utils/gardener/project.go]: What is your reasoning for duplicating the `ProjectAndNamespaceFromReader` function with only so little difference?

**Review by timebertt — COMMENTED** [review]
Can you add a release note?

File: pkg/utils/gardener/project.go (hunk 3 above)
Comment (acumino) [reply pkg/utils/gardener/project.go]: In the admission plugin for releasing the namespace, we don't need the error if the project is not found because it checks if the given namespace doesn't have a required label for the project then it can be released.

Comment (acumino) [reply pkg/utils/gardener/project.go]: https://github.com/gardener/gardener/blob/ac97d589d5f5191dd1472ff70e3c1d0ccbd8947a/pkg/admissioncontroller/webhooks/admission/namespacedeletion/admission.go#L111-L124 I was looking for better alternative but didn't find one.

Comment (ialidzhikov) [inline pkg/utils/gardener/project.go]: Instead of duplicating the function, can't we handle this corner case in the invocations of the `gutil.ProjectAndNamespaceFromReader` func? For example

```diff
diff --git a/pkg/operation/garden/garden.go b/pkg/operation/garden/garden.go
index 619b2a274..043881c85 100644
--- a/pkg/operation/garden/garden.go
+++ b/pkg/operation/garden/garden.go
@@ -55,7 +55,14 @@ func (b *Builder) WithProject(project *gardencorev1beta1.Project) *Builder {
 func (b *Builder) WithProjectFrom(reader client.Reader, namespace string) *Builder {
        b.projectFunc = func(ctx context.Context) (*gardencorev1beta1.Project, error) {
                project, _, err := gutil.ProjectAndNamespaceFromReader(ctx, reader, namespace)
-               return project, err
+               if err != nil {
+                       return nil, err
+               }
+               if project == nil {
+                       return nil, fmt.Errorf("cannot find Project for namespace '%s'", namespace)
+               }
+
+               return project, nil
        }
        return b
 }
```

It can be the case some other invocation of `ProjectAndNamespaceFromReader` that needs to be adapted - the one in shoot_control.go of gardenlet.

File: pkg/operation/garden/garden.go [hunk 4]
```diff
@@ -55,6 +55,10 @@ func (b *Builder) WithProject(project *gardencorev1beta1.Project) *Builder {
 func (b *Builder) WithProjectFrom(reader client.Reader, namespace string) *Builder {
 	b.projectFunc = func(ctx context.Context) (*gardencorev1beta1.Project, error) {
 		project, _, err := gutil.ProjectAndNamespaceFromReader(ctx, reader, namespace)
+		if project == nil {
+			return nil, fmt.Errorf("cannot find Project for namespace '%s'", namespace)
+		}
```
Comment (ialidzhikov) [inline pkg/operation/garden/garden.go:63]: I think we first want to check the err:

```suggestion
		if err != nil {
			return nil, err
		}
		if project == nil {
			return nil, fmt.Errorf("cannot find Project for namespace '%s'", namespace)
		}
```

For example the err can actually be "namespace not found" or "project not found" or any other but we would always kind of ignore this error and return "cannot find Project for namespace" err.

**Review by ialidzhikov — COMMENTED** [review]
/lgtm
/approve
