### PR TITLE
Always add default issuer to accepted issuers, add documentation

### LINKED ISSUE #5817: Changing the `ServiceAccount` issuer of a `Shoot` breaks the cluster
**How to categorize this issue?**

/area usability
/kind bug

**What happened**:
When changing the `ServiceAccount` issuer for an existing shoot cluster then the control plane and system components start to fail.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new `Shoot` with a standard manifest (ref https://github.com/gardener/gardener/blob/master/example/provider-local/shoot.yaml)
2. Set `.spec.kubernetes.kubeAPIServer.serviceAccountConfig.issuer="https://foo.bar.com"`
3. See the control plane and system components fail

**Anything else we need to know?**:
According to https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/, the `--service-account-issuer` field does the following:

> [...] The issuer will assert this identifier in "iss" claim of issued tokens. [...] When this flag is specified multiple times, the first is used to generate tokens and all are used to determine which issuers are accepted.

By default, the issuer is the external hostname of the cluster itself: https://github.com/gardener/gardener/blob/1b10d51dfe74e32bdbd73fe5b8efa903f71b417f/pkg/operation/botanist/kubeapiserver.go#L339. Hence, after creating a shoot, all tokens used by control plane and system components for communication with the `kube-apiserver` have this issuer.
Now, after changing this for an existing shoot, we just set the flag to the provided value: https://github.com/gardener/gardener/blob/1b10d51dfe74e32bdbd73fe5b8efa903f71b417f/pkg/operation/botanist/kubeapiserver.go#L348-L350
This will make `kube-apiserver` no longer accepting old tokens.

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind bug 

**What this PR does / why we need it**:
This PR adds the default `ServiceAccount` issuer to the list of accepted issuers as proposed in https://github.com/gardener/gardener/issues/5817#issuecomment-1108287261.
Also, it adds a new document explaining the various `ServiceAccount` configurations (and their caveats) for shoot clusters.

**Which issue(s) this PR fixes**:
Fixes #5817

/cc @acumino 

**Release note**:

```bugfix user
Changing the default `ServiceAccount` issuer to a custom issuer for shoot clusters is now supported.
```
```doc user
There is a [new document](https://github.com/gardener/gardener/tree/master/docs/usage/shoot_serviceaccounts.md) explaining the various configurations (and caveats) regarding the `ServiceAccount` configuration for shoot clusters.
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
/test pull-gardener-unit
wrong image for unit test

File: pkg/operation/botanist/kubeapiserver.go [hunk 1]
```diff
@@ -348,6 +351,9 @@ func (b *Botanist) computeKubeAPIServerServiceAccountConfig(ctx context.Context,
 		out.Issuer = *config.ServiceAccountConfig.Issuer
 	}
 	out.AcceptedIssuers = config.ServiceAccountConfig.AcceptedIssuers
+	if out.Issuer != defaultIssuer && !utils.ValueExists(defaultIssuer, out.AcceptedIssuers) {
```
Comment (acumino) [inline pkg/operation/botanist/kubeapiserver.go:354]: If issuer and accepted issuer both are not provided in that case what should be the accepted issuers? in the current scenario it is being set to nil, but shouldn't be default issuer should be added to the accepted issuer?

Comment (rfranzke) [reply pkg/operation/botanist/kubeapiserver.go:354]: In this case, the `kube-apiserver` will be configured with `--service-account-issuer=<default-issuer>` only which makes it issue tokens with the `<default-issuer>` and verify them with the `<default-issuer>` as well. No need to specify it twice.

**Comment by rfranzke** [comment]
@ialidzhikov Can this be included in 1.46? We should probably even cherry-pick it?!

**Comment by ialidzhikov** [comment]
Sure, go ahead.
