### PR TITLE
Fix kubernetes dashboard integration test to fetch the token from the kubeconfig

### LINKED ISSUE #6911: ☂️ Drop support for Shoots with K8s < 1.20
**How to categorize this issue?**
/kind cleanup

**What would you like to be added**:
We can drop support for Shoots with K8s < 1.20.

Gardener:
- [x] https://github.com/gardener/gardener: https://github.com/gardener/gardener/pull/6987
   - [x] Clean up support for [`BasicAuthFormatCSV`](https://github.com/gardener/gardener/blob/c38a317bb0dccea0f25546acdffc39e697d0588a/pkg/utils/secrets/basic_auth.go#L35-L36): https://github.com/gardener/gardener/pull/7362
   - [x] Drop the [defaulting for the `EnableBasicAuthentication` field](https://github.com/gardener/gardener/blob/629e94d066f09d0af2888e2511c19b6189b845e2/pkg/apis/core/v1beta1/defaults.go#L107-L109):
     - https://github.com/gardener/gardener/pull/7534
     - https://github.com/gardener/gardener/pull/7886

Extensions:
- [x] https://github.com/gardener/gardener-extension-provider-alicloud: https://github.com/gardener/gardener-extension-provider-alicloud/pull/555
- [x] https://github.com/gardener/gardener-extension-provider-aws: https://github.com/gardener/gardener-extension-provider-aws/pull/667
- [x] https://github.com/gardener/gardener-extension-provider-gcp: https://github.com/gardener/gardener-extension-provider-gcp/pull/533
- [x] https://github.com/gardener/gardener-extension-provider-azure: https://github.com/gardener/gardener-extension-provider-azure/pull/608
- [x] https://github.com/gardener/gardener-extension-provider-openstack: https://github.com/gardener/gardener-extension-provider-openstack/pull/541
- [x] https://github.com/gardener/gardener-extension-networking-calico: https://github.com/gardener/gardener-extension-networking-calico/pull/226
- [x] https://github.com/gardener/gardener-extension-networking-cilium: https://github.com/gardener/gardener-extension-networking-cilium/pull/145
- ...

K8s test infra:
- [x] https://github.com/kubernetes/test-infra: https://github.com/kubernetes/test-infra/pull/28352

**Why is this needed**:
Drop support for quite old K8s versions.

### PR DESCRIPTION
**Pull request by dimitar-kostadinov**
**How to categorize this PR?**

/area testing
/kind bug

**What this PR does / why we need it**:
Adapts shoot_app test to use `.data.kubeconfig` kubeconfig secret field to get the client token

**Which issue(s) this PR fixes**:
Part of #6911

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: test/testmachinery/shoots/applications/shoot_app.go [hunk 1]
```diff
@@ -86,8 +87,11 @@ var _ = ginkgo.Describe("Shoot application testing", func() {
 		}
 
 		url := fmt.Sprintf("https://api.%s/api/v1/namespaces/%s/services/https:kubernetes-dashboard:/proxy", *f.Shoot.Spec.DNS.Domain, "kubernetes-dashboard")
-		dashboardToken, err := framework.GetObjectFromSecret(ctx, f.GardenClient, f.Shoot.Namespace, f.Shoot.Name+"."+gutil.ShootProjectSecretSuffixKubeconfig, "token")
+		kubeConfig, err := framework.GetObjectFromSecret(ctx, f.GardenClient, f.Shoot.Namespace, f.Shoot.Name+"."+gutil.ShootProjectSecretSuffixKubeconfig, framework.KubeconfigSecretKeyName)
 		framework.ExpectNoError(err)
+		client, err := kubernetes.NewClientFromBytes([]byte(kubeConfig))
+		framework.ExpectNoError(err)
+		dashboardToken := client.RESTConfig().BearerToken
```
Comment (ialidzhikov) [inline test/testmachinery/shoots/applications/shoot_app.go]: We don't need to create a new client just to fetch the token from the kubeconfig.

```suggestion
		kubeconfigData, err := framework.GetObjectFromSecret(ctx, f.GardenClient, f.Shoot.Namespace, f.Shoot.Name+"."+gutil.ShootProjectSecretSuffixKubeconfig, framework.KubeconfigSecretKeyName)
		framework.ExpectNoError(err)

		kubeconfig := &clientcmdv1.Config{}
		_, _, err = clientcmdlatest.Codec.Decode([]byte(kubeconfigData), nil, kubeconfig)
		framework.ExpectNoError(err)

		Expect(kubeconfig.AuthInfos).To(HaveLen(1))
		Expect(kubeconfig.AuthInfos[0].AuthInfo.Token).NotTo(BeEmpty())
		dashboardToken := kubeconfig.AuthInfos[0].AuthInfo.Token
```

**Review by ialidzhikov — CHANGES_REQUESTED** [review]

**Review by ialidzhikov — APPROVED** [review]
/lgtm
